namespace JJ.Framework.Existence.Core;
using SB = StringBuilder;

/// <inheritdoc cref="_coalesce"/>
public static class CoalesceExtensions
{ 
          // [Prio] attributes:
          // These overloads clash: first.Coalesce(others), List.Coalesce(), and string.Coalesce().
          // Prio(1) on IEnumerable<T> for List.Coalesce() else List becomes the first arg in (first, others).
          // Prio(2) on string.Coalesce() makes it win over IEnumerable<char> in string-specific calls.
          // Prio(2) on other string-only variants makes e.g. null be seen as string rather than StringBuilder.
          
          // 1 Arg (for some)
          
          /// <inheritdoc cref="_coalesce" />
[Prio(2)] public static string Coalesce   (this string? text)                  => CoalesceText    (text);
          /// <inheritdoc cref="_coalesce" />
          public static SB     Coalesce   (this SB?     sb  )                  => CoalesceSB      (sb);
          /// <inheritdoc cref="_coalesce" />
          public static T      Coalesce<T>(this T       val ) where T : struct => CoalesceVal     (val);
          /// <inheritdoc cref="_coalesce" />
          public static T      Coalesce<T>(this T?      val ) where T : struct => CoalesceValNully(val);
          
          // 2 Args (for some)
          
          /// <inheritdoc cref="_coalesce" /> 
[Prio(2)] public static string Coalesce   (this string? text, string? fallback                           ) => CoalesceTwoTexts      (text, fallback);
          /// <inheritdoc cref="_coalesce" />
[Prio(2)] public static string Coalesce   (this string? text, string? fallback, bool         spaceMatters) => CoalesceTwoTexts      (text, fallback, spaceMatters);
          /// <inheritdoc cref="_coalesce" />
[Prio(2)] public static string Coalesce   (this string? text, string? fallback, SpaceMatters spaceMatters) => CoalesceTwoTexts      (text, fallback, spaceMatters);
          /// <inheritdoc cref="_coalesce" />
          public static string Coalesce   (this string? text, SB?     fallback                           ) => CoalesceTextAndSB     (text, fallback);
          /// <inheritdoc cref="_coalesce" />
          public static string Coalesce   (this string? text, SB?     fallback, bool         spaceMatters) => CoalesceTextAndSB     (text, fallback, spaceMatters);
          /// <inheritdoc cref="_coalesce" />
          public static string Coalesce   (this string? text, SB?     fallback, SpaceMatters spaceMatters) => CoalesceTextAndSB     (text, fallback, spaceMatters);
          /// <inheritdoc cref="_coalesce" />
          public static string Coalesce   (this SB?     sb,   string? fallback                           ) => CoalesceSBAndText     (sb,   fallback);
          /// <inheritdoc cref="_coalesce" />
          public static string Coalesce   (this SB?     sb,   string? fallback, bool         spaceMatters) => CoalesceSBAndText     (sb,   fallback, spaceMatters);
          /// <inheritdoc cref="_coalesce" />
          public static string Coalesce   (this SB?     sb,   string? fallback, SpaceMatters spaceMatters) => CoalesceSBAndText     (sb,   fallback, spaceMatters);
          /// <inheritdoc cref="_coalesce" />
          public static SB     Coalesce   (this SB?     sb,   SB?     fallback                           ) => CoalesceTwoSBs        (sb,   fallback);
          /// <inheritdoc cref="_coalesce" />
          public static SB     Coalesce   (this SB?     sb,   SB?     fallback, bool         spaceMatters) => CoalesceTwoSBs        (sb,   fallback, spaceMatters);
          /// <inheritdoc cref="_coalesce" />
          public static SB     Coalesce   (this SB?     sb,   SB?     fallback, SpaceMatters spaceMatters) => CoalesceTwoSBs        (sb,   fallback, spaceMatters);
          /// <inheritdoc cref="_coalesce" />
          public static string Coalesce   (this object? obj,  string? fallback)                            => CoalesceObjectToText  (obj,  fallback);
          
          /// <inheritdoc cref="_coalesce" />
          public static string Coalesce<T>(this T       val,  string? fallback                           ) where T : struct => CoalesceValToText     (val,  fallback);
          /// <inheritdoc cref="_coalesce" />
          public static string Coalesce<T>(this T       val,  string? fallback, bool         zeroMatters ) where T : struct => CoalesceValToText     (val,  fallback, zeroMatters);
          /// <inheritdoc cref="_coalesce" />
          public static string Coalesce<T>(this T       val,  string? fallback, ZeroMatters  zeroMatters ) where T : struct => CoalesceValToText     (val,  fallback, zeroMatters);
          /// <inheritdoc cref="_coalesce" />
          public static string Coalesce<T>(this T?      val,  string? fallback                           ) where T : struct => CoalesceNullyValToText(val,  fallback);
          /// <inheritdoc cref="_coalesce" />
          public static string Coalesce<T>(this T?      val,  string? fallback, bool         zeroMatters ) where T : struct => CoalesceNullyValToText(val,  fallback, zeroMatters);
          /// <inheritdoc cref="_coalesce" />
          public static string Coalesce<T>(this T?      val,  string? fallback, ZeroMatters  zeroMatters ) where T : struct => CoalesceNullyValToText(val,  fallback, zeroMatters);
          /// <inheritdoc cref="_coalesce" />
          public static T      Coalesce<T>(this T?      val,  T?      fallback                           ) where T : struct => CoalesceTwoNullyVals  (val,  fallback);
          /// <inheritdoc cref="_coalesce" />
          public static T      Coalesce<T>(this T?      val,  T?      fallback, bool         zeroMatters ) where T : struct => CoalesceTwoNullyVals  (val,  fallback, zeroMatters);
          /// <inheritdoc cref="_coalesce" />
          public static T      Coalesce<T>(this T?      val,  T?      fallback, ZeroMatters  zeroMatters ) where T : struct => CoalesceTwoNullyVals  (val,  fallback, zeroMatters);
          /// <inheritdoc cref="_coalesce" />
          public static T      Coalesce<T>(this T?      val,  T       fallback                           ) where T : struct => CoalesceNullyAndVal   (val,  fallback);
          /// <inheritdoc cref="_coalesce" />
          public static T      Coalesce<T>(this T?      val,  T       fallback, bool         zeroMatters ) where T : struct => CoalesceNullyAndVal   (val,  fallback, zeroMatters);
          /// <inheritdoc cref="_coalesce" />
          public static T      Coalesce<T>(this T?      val,  T       fallback, ZeroMatters  zeroMatters ) where T : struct => CoalesceNullyAndVal   (val,  fallback, zeroMatters);
          /// <inheritdoc cref="_coalesce" />
          public static T      Coalesce<T>(this T       val,  T?      fallback                           ) where T : struct => CoalesceValAndNully   (val,  fallback);
          /// <inheritdoc cref="_coalesce" />
          public static T      Coalesce<T>(this T       val,  T?      fallback, bool         zeroMatters ) where T : struct => CoalesceValAndNully   (val,  fallback, zeroMatters);
          /// <inheritdoc cref="_coalesce" />
          public static T      Coalesce<T>(this T       val,  T?      fallback, ZeroMatters  zeroMatters ) where T : struct => CoalesceValAndNully   (val,  fallback, zeroMatters);
          /// <inheritdoc cref="_coalesce" />
          public static T      Coalesce<T>(this T       val,  T       fallback                           ) where T : struct => CoalesceTwoVals       (val,  fallback);
          /// <inheritdoc cref="_coalesce" />
          public static T      Coalesce<T>(this T       val,  T       fallback, bool         zeroMatters ) where T : struct => CoalesceTwoVals       (val,  fallback, zeroMatters);
          /// <inheritdoc cref="_coalesce" />
          public static T      Coalesce<T>(this T       val,  T       fallback, ZeroMatters  zeroMatters ) where T : struct => CoalesceTwoVals       (val,  fallback, zeroMatters);
          
          // 3 Args (for some)
          
          /// <inheritdoc cref="_coalesce" />  
[Prio(2)] public static string Coalesce   (this string? text, string? fallback, string? fallback2                           ) => CoalesceTwoTexts      (text, CoalesceTwoTexts      (fallback, fallback2));
          /// <inheritdoc cref="_coalesce" />
[Prio(2)] public static string Coalesce   (this string? text, string? fallback, string? fallback2, bool         spaceMatters) => CoalesceTwoTexts      (text, CoalesceTwoTexts      (fallback, fallback2, spaceMatters), spaceMatters);
          /// <inheritdoc cref="_coalesce" />
[Prio(2)] public static string Coalesce   (this string? text, string? fallback, string? fallback2, SpaceMatters spaceMatters) => CoalesceTwoTexts      (text, CoalesceTwoTexts      (fallback, fallback2, spaceMatters), spaceMatters);
          /// <inheritdoc cref="_coalesce" />
          public static string Coalesce   (this string? text, string? fallback, SB?     fallback2                           ) => CoalesceTwoTexts      (text, CoalesceTextAndSB     (fallback, fallback2));
          /// <inheritdoc cref="_coalesce" />
          public static string Coalesce   (this string? text, string? fallback, SB?     fallback2, bool         spaceMatters) => CoalesceTwoTexts      (text, CoalesceTextAndSB     (fallback, fallback2, spaceMatters), spaceMatters);
          /// <inheritdoc cref="_coalesce" />
          public static string Coalesce   (this string? text, string? fallback, SB?     fallback2, SpaceMatters spaceMatters) => CoalesceTwoTexts      (text, CoalesceTextAndSB     (fallback, fallback2, spaceMatters), spaceMatters);
          /// <inheritdoc cref="_coalesce" />
          public static string Coalesce   (this string? text, SB?     fallback, string? fallback2                           ) => CoalesceTwoTexts      (text, CoalesceSBAndText     (fallback, fallback2));
          /// <inheritdoc cref="_coalesce" />
          public static string Coalesce   (this string? text, SB?     fallback, string? fallback2, bool         spaceMatters) => CoalesceTwoTexts      (text, CoalesceSBAndText     (fallback, fallback2, spaceMatters), spaceMatters);
          /// <inheritdoc cref="_coalesce" />
          public static string Coalesce   (this string? text, SB?     fallback, string? fallback2, SpaceMatters spaceMatters) => CoalesceTwoTexts      (text, CoalesceSBAndText     (fallback, fallback2, spaceMatters), spaceMatters);
          /// <inheritdoc cref="_coalesce" />
          public static string Coalesce   (this string? text, SB?     fallback, SB?     fallback2                           ) => CoalesceTextAndSB     (text, CoalesceTwoSBs        (fallback, fallback2));
          /// <inheritdoc cref="_coalesce" />
          public static string Coalesce   (this string? text, SB?     fallback, SB?     fallback2, bool         spaceMatters) => CoalesceTextAndSB     (text, CoalesceTwoSBs        (fallback, fallback2, spaceMatters), spaceMatters);
          /// <inheritdoc cref="_coalesce" />
          public static string Coalesce   (this string? text, SB?     fallback, SB?     fallback2, SpaceMatters spaceMatters) => CoalesceTextAndSB     (text, CoalesceTwoSBs        (fallback, fallback2, spaceMatters), spaceMatters);
          /// <inheritdoc cref="_coalesce" />
          public static string Coalesce   (this SB?     sb,   string? fallback, string? fallback2                           ) => CoalesceSBAndText     (sb,   CoalesceTwoTexts      (fallback, fallback2));
          /// <inheritdoc cref="_coalesce" />
          public static string Coalesce   (this SB?     sb,   string? fallback, string? fallback2, bool         spaceMatters) => CoalesceSBAndText     (sb,   CoalesceTwoTexts      (fallback, fallback2, spaceMatters), spaceMatters);
          /// <inheritdoc cref="_coalesce" />
          public static string Coalesce   (this SB?     sb,   string? fallback, string? fallback2, SpaceMatters spaceMatters) => CoalesceSBAndText     (sb,   CoalesceTwoTexts      (fallback, fallback2, spaceMatters), spaceMatters);
          /// <inheritdoc cref="_coalesce" />
          public static string Coalesce   (this SB?     sb,   string? fallback, SB?     fallback2                           ) => CoalesceSBAndText     (sb,   CoalesceTextAndSB     (fallback, fallback2));
          /// <inheritdoc cref="_coalesce" />
          public static string Coalesce   (this SB?     sb,   string? fallback, SB?     fallback2, bool         spaceMatters) => CoalesceSBAndText     (sb,   CoalesceTextAndSB     (fallback, fallback2, spaceMatters), spaceMatters);
          /// <inheritdoc cref="_coalesce" />
          public static string Coalesce   (this SB?     sb,   string? fallback, SB?     fallback2, SpaceMatters spaceMatters) => CoalesceSBAndText     (sb,   CoalesceTextAndSB     (fallback, fallback2, spaceMatters), spaceMatters);
          /// <inheritdoc cref="_coalesce" />
          public static string Coalesce   (this SB?     sb,   SB?     fallback, string? fallback2                           ) => CoalesceSBAndText     (sb,   CoalesceSBAndText     (fallback, fallback2));
          /// <inheritdoc cref="_coalesce" />
          public static string Coalesce   (this SB?     sb,   SB?     fallback, string? fallback2, bool         spaceMatters) => CoalesceSBAndText     (sb,   CoalesceSBAndText     (fallback, fallback2, spaceMatters), spaceMatters);
          /// <inheritdoc cref="_coalesce" />
          public static string Coalesce   (this SB?     sb,   SB?     fallback, string? fallback2, SpaceMatters spaceMatters) => CoalesceSBAndText     (sb,   CoalesceSBAndText     (fallback, fallback2, spaceMatters), spaceMatters);
          /// <inheritdoc cref="_coalesce" />
          public static SB     Coalesce   (this SB?     sb,   SB?     fallback, SB?     fallback2                           ) => CoalesceTwoSBs        (sb,   CoalesceTwoSBs        (fallback, fallback2));
          /// <inheritdoc cref="_coalesce" />
          public static SB     Coalesce   (this SB?     sb,   SB?     fallback, SB?     fallback2, bool         spaceMatters) => CoalesceTwoSBs        (sb,   CoalesceTwoSBs        (fallback, fallback2, spaceMatters), spaceMatters);
          /// <inheritdoc cref="_coalesce" />
          public static SB     Coalesce   (this SB?     sb,   SB?     fallback, SB?     fallback2, SpaceMatters spaceMatters) => CoalesceTwoSBs        (sb,   CoalesceTwoSBs        (fallback, fallback2, spaceMatters), spaceMatters);
          /// <inheritdoc cref="_coalesce" />
          public static string Coalesce   (this object? obj,  object? fallback, string? fallback2)                            => CoalesceObjectToText  (obj,  CoalesceObjectToText  (fallback, fallback2));
          /// <inheritdoc cref="_coalesce" />
          public static string Coalesce<T>(this T       val,  T       fallback, string? fallback2                           ) where T : struct => CoalesceValToText     (val,  CoalesceValToText     (fallback, fallback2));
          /// <inheritdoc cref="_coalesce" />
          public static string Coalesce<T>(this T       val,  T       fallback, string? fallback2, bool         zeroMatters ) where T : struct => CoalesceValToText     (val,  CoalesceValToText     (fallback, fallback2, zeroMatters), zeroMatters);
          /// <inheritdoc cref="_coalesce" />
          public static string Coalesce<T>(this T       val,  T       fallback, string? fallback2, ZeroMatters  zeroMatters ) where T : struct => CoalesceValToText     (val,  CoalesceValToText     (fallback, fallback2, zeroMatters), zeroMatters);
          /// <inheritdoc cref="_coalesce" />
          public static string Coalesce<T>(this T       val,  T?      fallback, string? fallback2                           ) where T : struct => CoalesceValToText     (val,  CoalesceNullyValToText(fallback, fallback2));
          /// <inheritdoc cref="_coalesce" />
          public static string Coalesce<T>(this T       val,  T?      fallback, string? fallback2, bool         zeroMatters ) where T : struct => CoalesceValToText     (val,  CoalesceNullyValToText(fallback, fallback2, zeroMatters), zeroMatters);
          /// <inheritdoc cref="_coalesce" />
          public static string Coalesce<T>(this T       val,  T?      fallback, string? fallback2, ZeroMatters  zeroMatters ) where T : struct => CoalesceValToText     (val,  CoalesceNullyValToText(fallback, fallback2, zeroMatters), zeroMatters);
          /// <inheritdoc cref="_coalesce" />
          public static string Coalesce<T>(this T?      val,  T       fallback, string? fallback2                           ) where T : struct => CoalesceNullyValToText(val,  CoalesceValToText     (fallback, fallback2));
          /// <inheritdoc cref="_coalesce" />
          public static string Coalesce<T>(this T?      val,  T       fallback, string? fallback2, bool         zeroMatters ) where T : struct => CoalesceNullyValToText(val,  CoalesceValToText     (fallback, fallback2, zeroMatters), zeroMatters);
          /// <inheritdoc cref="_coalesce" />
          public static string Coalesce<T>(this T?      val,  T       fallback, string? fallback2, ZeroMatters  zeroMatters ) where T : struct => CoalesceNullyValToText(val,  CoalesceValToText     (fallback, fallback2, zeroMatters), zeroMatters);
          /// <inheritdoc cref="_coalesce" />
          public static string Coalesce<T>(this T?      val,  T?      fallback, string? fallback2                           ) where T : struct => CoalesceNullyValToText(val,  CoalesceNullyValToText(fallback, fallback2));
          /// <inheritdoc cref="_coalesce" />
          public static string Coalesce<T>(this T?      val,  T?      fallback, string? fallback2, bool         zeroMatters ) where T : struct => CoalesceNullyValToText(val,  CoalesceNullyValToText(fallback, fallback2, zeroMatters), zeroMatters);
          /// <inheritdoc cref="_coalesce" />
          public static string Coalesce<T>(this T?      val,  T?      fallback, string? fallback2, ZeroMatters  zeroMatters ) where T : struct => CoalesceNullyValToText(val,  CoalesceNullyValToText(fallback, fallback2, zeroMatters), zeroMatters);
          /// <inheritdoc cref="_coalesce" />
          public static T      Coalesce<T>(this T?      val,  T?      fallback, T?      fallback2                           ) where T : struct => CoalesceNullyAndVal   (val,  CoalesceTwoNullyVals  (fallback, fallback2));
          /// <inheritdoc cref="_coalesce" />
          public static T      Coalesce<T>(this T?      val,  T?      fallback, T?      fallback2, bool         zeroMatters ) where T : struct => CoalesceNullyAndVal   (val,  CoalesceTwoNullyVals  (fallback, fallback2, zeroMatters), zeroMatters);
          /// <inheritdoc cref="_coalesce" />
          public static T      Coalesce<T>(this T?      val,  T?      fallback, T?      fallback2, ZeroMatters  zeroMatters ) where T : struct => CoalesceNullyAndVal   (val,  CoalesceTwoNullyVals  (fallback, fallback2, zeroMatters), zeroMatters);
          /// <inheritdoc cref="_coalesce" />
          public static T      Coalesce<T>(this T?      val,  T?      fallback, T       fallback2                           ) where T : struct => CoalesceNullyAndVal   (val,  CoalesceNullyAndVal   (fallback, fallback2));
          /// <inheritdoc cref="_coalesce" />
          public static T      Coalesce<T>(this T?      val,  T?      fallback, T       fallback2, bool         zeroMatters ) where T : struct => CoalesceNullyAndVal   (val,  CoalesceNullyAndVal   (fallback, fallback2, zeroMatters), zeroMatters);
          /// <inheritdoc cref="_coalesce" />
          public static T      Coalesce<T>(this T?      val,  T?      fallback, T       fallback2, ZeroMatters  zeroMatters ) where T : struct => CoalesceNullyAndVal   (val,  CoalesceNullyAndVal   (fallback, fallback2, zeroMatters), zeroMatters);
          /// <inheritdoc cref="_coalesce" />
          public static T      Coalesce<T>(this T?      val,  T       fallback, T?      fallback2                           ) where T : struct => CoalesceNullyAndVal   (val,  CoalesceValAndNully   (fallback, fallback2));
          /// <inheritdoc cref="_coalesce" />
          public static T      Coalesce<T>(this T?      val,  T       fallback, T?      fallback2, bool         zeroMatters ) where T : struct => CoalesceNullyAndVal   (val,  CoalesceValAndNully   (fallback, fallback2, zeroMatters), zeroMatters);
          /// <inheritdoc cref="_coalesce" />
          public static T      Coalesce<T>(this T?      val,  T       fallback, T?      fallback2, ZeroMatters  zeroMatters ) where T : struct => CoalesceNullyAndVal   (val,  CoalesceValAndNully   (fallback, fallback2, zeroMatters), zeroMatters);
          /// <inheritdoc cref="_coalesce" />
          public static T      Coalesce<T>(this T?      val,  T       fallback, T       fallback2                           ) where T : struct => CoalesceNullyAndVal   (val,  CoalesceTwoVals       (fallback, fallback2));
          /// <inheritdoc cref="_coalesce" />
          public static T      Coalesce<T>(this T?      val,  T       fallback, T       fallback2, bool         zeroMatters ) where T : struct => CoalesceNullyAndVal   (val,  CoalesceTwoVals       (fallback, fallback2, zeroMatters), zeroMatters);
          /// <inheritdoc cref="_coalesce" />
          public static T      Coalesce<T>(this T?      val,  T       fallback, T       fallback2, ZeroMatters  zeroMatters ) where T : struct => CoalesceNullyAndVal   (val,  CoalesceTwoVals       (fallback, fallback2, zeroMatters), zeroMatters);
          /// <inheritdoc cref="_coalesce" />
          public static T      Coalesce<T>(this T       val,  T?      fallback, T?      fallback2                           ) where T : struct => CoalesceTwoVals       (val,  CoalesceTwoNullyVals  (fallback, fallback2));
          /// <inheritdoc cref="_coalesce" />
          public static T      Coalesce<T>(this T       val,  T?      fallback, T?      fallback2, bool         zeroMatters ) where T : struct => CoalesceTwoVals       (val,  CoalesceTwoNullyVals  (fallback, fallback2, zeroMatters), zeroMatters);
          /// <inheritdoc cref="_coalesce" />
          public static T      Coalesce<T>(this T       val,  T?      fallback, T?      fallback2, ZeroMatters  zeroMatters ) where T : struct => CoalesceTwoVals       (val,  CoalesceTwoNullyVals  (fallback, fallback2, zeroMatters), zeroMatters);
          /// <inheritdoc cref="_coalesce" />
          public static T      Coalesce<T>(this T       val,  T?      fallback, T       fallback2                           ) where T : struct => CoalesceTwoVals       (val,  CoalesceNullyAndVal   (fallback, fallback2));
          /// <inheritdoc cref="_coalesce" />
          public static T      Coalesce<T>(this T       val,  T?      fallback, T       fallback2, bool         zeroMatters ) where T : struct => CoalesceTwoVals       (val,  CoalesceNullyAndVal   (fallback, fallback2, zeroMatters), zeroMatters);
          /// <inheritdoc cref="_coalesce" />
          public static T      Coalesce<T>(this T       val,  T?      fallback, T       fallback2, ZeroMatters  zeroMatters ) where T : struct => CoalesceTwoVals       (val,  CoalesceNullyAndVal   (fallback, fallback2, zeroMatters), zeroMatters);
          /// <inheritdoc cref="_coalesce" />
          public static T      Coalesce<T>(this T       val,  T       fallback, T?      fallback2                           ) where T : struct => CoalesceTwoVals       (val,  CoalesceValAndNully   (fallback, fallback2));
          /// <inheritdoc cref="_coalesce" />
          public static T      Coalesce<T>(this T       val,  T       fallback, T?      fallback2, bool         zeroMatters ) where T : struct => CoalesceTwoVals       (val,  CoalesceValAndNully   (fallback, fallback2, zeroMatters), zeroMatters);
          /// <inheritdoc cref="_coalesce" />
          public static T      Coalesce<T>(this T       val,  T       fallback, T?      fallback2, ZeroMatters  zeroMatters ) where T : struct => CoalesceTwoVals       (val,  CoalesceValAndNully   (fallback, fallback2, zeroMatters), zeroMatters);
          /// <inheritdoc cref="_coalesce" />
          public static T      Coalesce<T>(this T       val,  T       fallback, T       fallback2                           ) where T : struct => CoalesceTwoVals       (val,  CoalesceTwoVals       (fallback, fallback2));
          /// <inheritdoc cref="_coalesce" />
          public static T      Coalesce<T>(this T       val,  T       fallback, T       fallback2, bool         zeroMatters ) where T : struct => CoalesceTwoVals       (val,  CoalesceTwoVals       (fallback, fallback2, zeroMatters), zeroMatters);
          /// <inheritdoc cref="_coalesce" />
          public static T      Coalesce<T>(this T       val,  T       fallback, T       fallback2, ZeroMatters  zeroMatters ) where T : struct => CoalesceTwoVals       (val,  CoalesceTwoVals       (fallback, fallback2, zeroMatters), zeroMatters);
          
          // N Args (for all others)
          
          /// <inheritdoc cref="_coalesce" />  
[Prio(1)] public static string Coalesce   (this IEnumerable<string?>? fallbacks                           ) => CoalesceManyTexts  (fallbacks);
          /// <inheritdoc cref="_coalesce" />
[Prio(1)] public static string Coalesce   (this IEnumerable<string?>? fallbacks, SpaceMatters spaceMatters) => CoalesceManyTexts  (fallbacks, spaceMatters);
          /// <inheritdoc cref="_coalesce" />
[Prio(1)] public static string Coalesce   (this IEnumerable<string?>? fallbacks, bool         spaceMatters) => CoalesceManyTexts  (fallbacks, spaceMatters);
          /// <inheritdoc cref="_coalesce" />
[Prio(1)] public static SB     Coalesce   (this IEnumerable<SB?>?     fallbacks                           ) => CoalesceManySBs    (fallbacks);
          /// <inheritdoc cref="_coalesce" />
[Prio(1)] public static SB     Coalesce   (this IEnumerable<SB?>?     fallbacks, SpaceMatters spaceMatters) => CoalesceManySBs    (fallbacks, spaceMatters);
          /// <inheritdoc cref="_coalesce" />
[Prio(1)] public static SB     Coalesce   (this IEnumerable<SB?>?     fallbacks, bool         spaceMatters) => CoalesceManySBs    (fallbacks, spaceMatters);
          /// <inheritdoc cref="_coalesce" />
[Prio(1)] public static T      Coalesce<T>(this IEnumerable<T?>?      fallbacks                           ) where T : new()  => CoalesceManyObjects(fallbacks);
          /// <inheritdoc cref="_coalesce" />
[Prio(1)] public static T      Coalesce<T>(this IEnumerable<T?>?      fallbacks                           ) where T : struct => CoalesceManyVals   (fallbacks);
          /// <inheritdoc cref="_coalesce" />
[Prio(1)] public static T      Coalesce<T>(this IEnumerable<T?>?      fallbacks, bool         zeroMatters ) where T : struct => CoalesceManyVals   (fallbacks, zeroMatters);
          /// <inheritdoc cref="_coalesce" />
[Prio(1)] public static T      Coalesce<T>(this IEnumerable<T?>?      fallbacks, ZeroMatters  zeroMatters ) where T : struct => CoalesceManyVals   (fallbacks, zeroMatters);
          
          /// <inheritdoc cref="_coalesce" />
          public static string Coalesce   (this string? first,                                     params IEnumerable<string?>? fallbacks   )                  => CoalesceManyTexts  (new [] {    first }.Concat(fallbacks ?? [ ]));
          /// <inheritdoc cref="_coalesce" />
          public static string Coalesce   (this string? first, bool                  spaceMatters, params IEnumerable<string?>? fallbacks   )                  => CoalesceManyTexts  (new [] {    first }.Concat(fallbacks ?? [ ]), spaceMatters);
          /// <inheritdoc cref="_coalesce" />
          public static string Coalesce   (this string? first, SpaceMatters          spaceMatters, params IEnumerable<string?>? fallbacks   )                  => CoalesceManyTexts  (new [] {    first }.Concat(fallbacks ?? [ ]), spaceMatters);
          /// <inheritdoc cref="_coalesce" />
          public static SB     Coalesce   (this SB?     first,                                     params IEnumerable<SB?>?     fallbacks   )                  => CoalesceManySBs    (new [] {    first }.Concat(fallbacks ?? [ ]));
          /// <inheritdoc cref="_coalesce" />
          public static SB     Coalesce   (this SB?     first, bool                  spaceMatters, params IEnumerable<SB?>?     fallbacks   )                  => CoalesceManySBs    (new [] {    first }.Concat(fallbacks ?? [ ]), spaceMatters);
          /// <inheritdoc cref="_coalesce" />
          public static SB     Coalesce   (this SB?     first, SpaceMatters          spaceMatters, params IEnumerable<SB?>?     fallbacks   )                  => CoalesceManySBs    (new [] {    first }.Concat(fallbacks ?? [ ]), spaceMatters);
          /// <inheritdoc cref="_coalesce" />
          public static string Coalesce   (this string? first, IEnumerable<string?>? fallbacks,    bool                         spaceMatters)                  => CoalesceManyTexts  (new [] {    first }.Concat(fallbacks ?? [ ]), spaceMatters);
          /// <inheritdoc cref="_coalesce" />
          public static string Coalesce   (this string? first, IEnumerable<string?>? fallbacks,    SpaceMatters                 spaceMatters)                  => CoalesceManyTexts  (new [] {    first }.Concat(fallbacks ?? [ ]), spaceMatters);
          /// <inheritdoc cref="_coalesce" />
          public static SB     Coalesce   (this SB?     first, IEnumerable<SB?>?     fallbacks,    bool                         spaceMatters)                  => CoalesceManySBs    (new [] {    first }.Concat(fallbacks ?? [ ]), spaceMatters);
          /// <inheritdoc cref="_coalesce" />
          public static SB     Coalesce   (this SB?     first, IEnumerable<SB?>?     fallbacks,    SpaceMatters                 spaceMatters)                  => CoalesceManySBs    (new [] {    first }.Concat(fallbacks ?? [ ]), spaceMatters);
          /// <inheritdoc cref="_coalesce" />
          public static T      Coalesce<T>(this T?      first,                                     params IEnumerable<T?>?      fallbacks   ) where T : new()  => CoalesceManyObjects(new [] {    first }.Concat(fallbacks ?? [ ]));
          /// <inheritdoc cref="_coalesce" />
          public static T      Coalesce<T>(this T?      first,                                     params IEnumerable<T?>?      fallbacks   ) where T : struct => CoalesceManyVals   (new [] {    first }.Concat(fallbacks ?? [ ]));
          /// <inheritdoc cref="_coalesce" />
          public static T      Coalesce<T>(this T?      first, bool                  zeroMatters,  params IEnumerable<T?>?      fallbacks   ) where T : struct => CoalesceManyVals   (new [] {    first }.Concat(fallbacks ?? [ ]), zeroMatters);
          /// <inheritdoc cref="_coalesce" />
          public static T      Coalesce<T>(this T?      first, ZeroMatters           zeroMatters,  params IEnumerable<T?>?      fallbacks   ) where T : struct => CoalesceManyVals   (new [] {    first }.Concat(fallbacks ?? [ ]), zeroMatters);
          /// <inheritdoc cref="_coalesce" />
          public static T      Coalesce<T>(this T?      first, IEnumerable<T?>?      fallbacks,    bool                         zeroMatters ) where T : struct => CoalesceManyVals   (new [] {    first }.Concat(fallbacks ?? [ ]), zeroMatters);
          /// <inheritdoc cref="_coalesce" />
          public static T      Coalesce<T>(this T?      first, IEnumerable<T?>?      fallbacks,    ZeroMatters                  zeroMatters ) where T : struct => CoalesceManyVals   (new [] {    first }.Concat(fallbacks ?? [ ]), zeroMatters);
          /// <inheritdoc cref="_coalesce" />
          public static T      Coalesce<T>(this T       first,                                     params IEnumerable<T?>?      fallbacks   ) where T : struct => CoalesceManyVals   (new [] {(T?)first }.Concat(fallbacks ?? [ ]));
          /// <inheritdoc cref="_coalesce" />
          public static T      Coalesce<T>(this T       first, bool                  zeroMatters,  params IEnumerable<T?>?      fallbacks   ) where T : struct => CoalesceManyVals   (new [] {(T?)first }.Concat(fallbacks ?? [ ]), zeroMatters);
          /// <inheritdoc cref="_coalesce" />
          public static T      Coalesce<T>(this T       first, ZeroMatters           zeroMatters,  params IEnumerable<T?>?      fallbacks   ) where T : struct => CoalesceManyVals   (new [] {(T?)first }.Concat(fallbacks ?? [ ]), zeroMatters);
          /// <inheritdoc cref="_coalesce" />
          public static T      Coalesce<T>(this T       first, IEnumerable<T?>?      fallbacks,    bool                         zeroMatters ) where T : struct => CoalesceManyVals   (new [] {(T?)first }.Concat(fallbacks ?? [ ]), zeroMatters);
          /// <inheritdoc cref="_coalesce" />
          public static T      Coalesce<T>(this T       first, IEnumerable<T?>?      fallbacks,    ZeroMatters                  zeroMatters ) where T : struct => CoalesceManyVals   (new [] {(T?)first }.Concat(fallbacks ?? [ ]), zeroMatters);
}