namespace JJ.Framework.Existence.Core;
using SB = StringBuilder;

/// <inheritdoc cref="_existencecore"/>
public static partial class FilledInHelper
{ 
    // 1 Arg (for some)
    
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce   (     string? text)                  => CoalesceText    (text);
    /// <inheritdoc cref="_coalesce" />
    public static SB     Coalesce   (     SB?     sb  )                  => CoalesceSB      (sb  );
    /// <inheritdoc cref="_coalesce" />
    public static T      Coalesce<T>(     T       val ) where T : struct => CoalesceVal     (val );
    /// <inheritdoc cref="_coalesce" />
    public static T      Coalesce<T>(     T?      val ) where T : struct => CoalesceValNully(val );
    
    // 2 Args (for text)
    
    /// <inheritdoc cref="_coalesce" /> 
    public static string Coalesce   (     string? text, string? fallback                           ) => CoalesceTwoTexts    (text, fallback              );
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce   (     string? text, SB?     fallback                           ) => CoalesceTextAndSB   (text, fallback              );
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce   (     SB?     sb,   string? fallback                           ) => CoalesceSBAndText   (sb,   fallback              );
    /// <inheritdoc cref="_coalesce" />
    public static SB     Coalesce   (     SB?     sb,   SB?     fallback                           ) => CoalesceTwoSBs      (sb,   fallback              );
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce   (     string? text, string? fallback, bool         spaceMatters) => CoalesceTwoTexts    (text, fallback, spaceMatters);
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce   (     string? text, SB?     fallback, bool         spaceMatters) => CoalesceTextAndSB   (text, fallback, spaceMatters);
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce   (     SB?     sb,   string? fallback, bool         spaceMatters) => CoalesceSBAndText   (sb,   fallback, spaceMatters);
    /// <inheritdoc cref="_coalesce" />
    public static SB     Coalesce   (     SB?     sb,   SB?     fallback, bool         spaceMatters) => CoalesceTwoSBs      (sb,   fallback, spaceMatters);
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce   (     string? text, string? fallback, SpaceMatters spaceMatters) => CoalesceTwoTexts    (text, fallback, spaceMatters);
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce   (     string? text, SB?     fallback, SpaceMatters spaceMatters) => CoalesceTextAndSB   (text, fallback, spaceMatters);
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce   (     SB?     sb,   string? fallback, SpaceMatters spaceMatters) => CoalesceSBAndText   (sb,   fallback, spaceMatters);
    /// <inheritdoc cref="_coalesce" />
    public static SB     Coalesce   (     SB?     sb,   SB?     fallback, SpaceMatters spaceMatters) => CoalesceTwoSBs      (sb,   fallback, spaceMatters);
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce   (     bool         spaceMatters, string? text, string? fallback) => CoalesceTwoTexts    (text, fallback, spaceMatters);
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce   (     bool         spaceMatters, string? text, SB?     fallback) => CoalesceTextAndSB   (text, fallback, spaceMatters);
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce   (     bool         spaceMatters, SB?     sb,   string? fallback) => CoalesceSBAndText   (sb,   fallback, spaceMatters);
    /// <inheritdoc cref="_coalesce" />
    public static SB     Coalesce   (     bool         spaceMatters, SB?     sb,   SB?     fallback) => CoalesceTwoSBs      (sb,   fallback, spaceMatters);
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce   (     SpaceMatters spaceMatters, string? text, string? fallback) => CoalesceTwoTexts    (text, fallback, spaceMatters);
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce   (     SpaceMatters spaceMatters, string? text, SB?     fallback) => CoalesceTextAndSB   (text, fallback, spaceMatters);
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce   (     SpaceMatters spaceMatters, SB?     sb,   string? fallback) => CoalesceSBAndText   (sb,   fallback, spaceMatters);
    /// <inheritdoc cref="_coalesce" />
    public static SB     Coalesce   (     SpaceMatters spaceMatters, SB?     sb,   SB?     fallback) => CoalesceTwoSBs      (sb,   fallback, spaceMatters);
    
    // 2 Args (for some)
    
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce   (     object? obj,  string? fallback                          ) => CoalesceObjectToText(obj,  fallback              );
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce<T>(     T?      val,  string? fallback                          ) where T : struct => CoalesceNullyValToText(val, fallback             );
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce<T>(     T       val,  string? fallback                          ) where T : struct => CoalesceValToText     (val, fallback             );
    /// <inheritdoc cref="_coalesce" />
    public static T      Coalesce<T>(     T?      val,  T?      fallback                          ) where T : struct => CoalesceTwoNullyVals  (val, fallback             );
    /// <inheritdoc cref="_coalesce" />
    public static T      Coalesce<T>(     T?      val,  T       fallback                          ) where T : struct => CoalesceNullyAndVal   (val, fallback             );
    /// <inheritdoc cref="_coalesce" />
    public static T      Coalesce<T>(     T       val,  T?      fallback                          ) where T : struct => CoalesceValAndNully   (val, fallback             );
    /// <inheritdoc cref="_coalesce" />
    public static T      Coalesce<T>(     T       val,  T       fallback                          ) where T : struct => CoalesceTwoVals       (val, fallback             );
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce<T>(     T?      val,  string? fallback, bool         zeroMatters) where T : struct => CoalesceNullyValToText(val, fallback, zeroMatters);
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce<T>(     T       val,  string? fallback, bool         zeroMatters) where T : struct => CoalesceValToText     (val, fallback, zeroMatters);
    /// <inheritdoc cref="_coalesce" />
    public static T      Coalesce<T>(     T?      val,  T?      fallback, bool         zeroMatters) where T : struct => CoalesceTwoNullyVals  (val, fallback, zeroMatters);
    /// <inheritdoc cref="_coalesce" />
    public static T      Coalesce<T>(     T?      val,  T       fallback, bool         zeroMatters) where T : struct => CoalesceNullyAndVal   (val, fallback, zeroMatters);
    /// <inheritdoc cref="_coalesce" />
    public static T      Coalesce<T>(     T       val,  T?      fallback, bool         zeroMatters) where T : struct => CoalesceValAndNully   (val, fallback, zeroMatters);
    /// <inheritdoc cref="_coalesce" />
    public static T      Coalesce<T>(     T       val,  T       fallback, bool         zeroMatters) where T : struct => CoalesceTwoVals       (val, fallback, zeroMatters);
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce<T>(     T?      val,  string? fallback, ZeroMatters  zeroMatters) where T : struct => CoalesceNullyValToText(val, fallback, zeroMatters);
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce<T>(     T       val,  string? fallback, ZeroMatters  zeroMatters) where T : struct => CoalesceValToText     (val, fallback, zeroMatters);
    /// <inheritdoc cref="_coalesce" />
    public static T      Coalesce<T>(     T?      val,  T?      fallback, ZeroMatters  zeroMatters) where T : struct => CoalesceTwoNullyVals  (val, fallback, zeroMatters);
    /// <inheritdoc cref="_coalesce" />
    public static T      Coalesce<T>(     T?      val,  T       fallback, ZeroMatters  zeroMatters) where T : struct => CoalesceNullyAndVal   (val, fallback, zeroMatters);
    /// <inheritdoc cref="_coalesce" />
    public static T      Coalesce<T>(     T       val,  T?      fallback, ZeroMatters  zeroMatters) where T : struct => CoalesceValAndNully   (val, fallback, zeroMatters);
    /// <inheritdoc cref="_coalesce" />
    public static T      Coalesce<T>(     T       val,  T       fallback, ZeroMatters  zeroMatters) where T : struct => CoalesceTwoVals       (val, fallback, zeroMatters);
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce<T>(     bool         zeroMatters, T?      val,  string? fallback) where T : struct => CoalesceNullyValToText(val, fallback, zeroMatters);
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce<T>(     bool         zeroMatters, T       val,  string? fallback) where T : struct => CoalesceValToText     (val, fallback, zeroMatters);
    /// <inheritdoc cref="_coalesce" />
    public static T      Coalesce<T>(     bool         zeroMatters, T?      val,  T?      fallback) where T : struct => CoalesceTwoNullyVals  (val, fallback, zeroMatters);
    /// <inheritdoc cref="_coalesce" />
    public static T      Coalesce<T>(     bool         zeroMatters, T?      val,  T       fallback) where T : struct => CoalesceNullyAndVal   (val, fallback, zeroMatters);
    /// <inheritdoc cref="_coalesce" />
    public static T      Coalesce<T>(     bool         zeroMatters, T       val,  T?      fallback) where T : struct => CoalesceValAndNully   (val, fallback, zeroMatters);
    /// <inheritdoc cref="_coalesce" />
    public static T      Coalesce<T>(     bool         zeroMatters, T       val,  T       fallback) where T : struct => CoalesceTwoVals       (val, fallback, zeroMatters);
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce<T>(     ZeroMatters  zeroMatters, T?      val,  string? fallback) where T : struct => CoalesceNullyValToText(val, fallback, zeroMatters);
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce<T>(     ZeroMatters  zeroMatters, T       val,  string? fallback) where T : struct => CoalesceValToText     (val, fallback, zeroMatters);
    /// <inheritdoc cref="_coalesce" />
    public static T      Coalesce<T>(     ZeroMatters  zeroMatters, T?      val,  T?      fallback) where T : struct => CoalesceTwoNullyVals  (val, fallback, zeroMatters);
    /// <inheritdoc cref="_coalesce" />
    public static T      Coalesce<T>(     ZeroMatters  zeroMatters, T?      val,  T       fallback) where T : struct => CoalesceNullyAndVal   (val, fallback, zeroMatters);
    /// <inheritdoc cref="_coalesce" />
    public static T      Coalesce<T>(     ZeroMatters  zeroMatters, T       val,  T?      fallback) where T : struct => CoalesceValAndNully   (val, fallback, zeroMatters);
    /// <inheritdoc cref="_coalesce" />
    public static T      Coalesce<T>(     ZeroMatters  zeroMatters, T       val,  T       fallback) where T : struct => CoalesceTwoVals       (val, fallback, zeroMatters);
    
    // 3 Args (for text)
    
    /// <inheritdoc cref="_coalesce" /> 
    public static string Coalesce   (     string? text, string? fallback, string? fallback2                           ) => CoalesceTwoTexts (text, CoalesceTwoTexts (fallback, fallback2));
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce   (     string? text, SB?     fallback, string? fallback2                           ) => CoalesceTwoTexts (text, CoalesceSBAndText(fallback, fallback2));
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce   (     string? text, string? fallback, SB?     fallback2                           ) => CoalesceTwoTexts (text, CoalesceTextAndSB(fallback, fallback2));
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce   (     string? text, SB?     fallback, SB?     fallback2                           ) => CoalesceTextAndSB(text, CoalesceTwoSBs   (fallback, fallback2));
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce   (     SB?     sb,   string? fallback, string? fallback2                           ) => CoalesceSBAndText(sb,   CoalesceTwoTexts (fallback, fallback2));
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce   (     SB?     sb,   string? fallback, SB?     fallback2                           ) => CoalesceSBAndText(sb,   CoalesceTextAndSB(fallback, fallback2));
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce   (     SB?     sb,   SB?     fallback, string? fallback2                           ) => CoalesceSBAndText(sb,   CoalesceSBAndText(fallback, fallback2));
    /// <inheritdoc cref="_coalesce" />
    public static SB     Coalesce   (     SB?     sb,   SB?     fallback, SB?     fallback2                           ) => CoalesceTwoSBs   (sb,   CoalesceTwoSBs   (fallback, fallback2));
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce   (     string? text, string? fallback, string? fallback2, bool         spaceMatters) => CoalesceTwoTexts (text, CoalesceTwoTexts (fallback, fallback2, spaceMatters), spaceMatters);
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce   (     string? text, string? fallback, SB?     fallback2, bool         spaceMatters) => CoalesceTwoTexts (text, CoalesceTextAndSB(fallback, fallback2, spaceMatters), spaceMatters);
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce   (     string? text, SB?     fallback, string? fallback2, bool         spaceMatters) => CoalesceTwoTexts (text, CoalesceSBAndText(fallback, fallback2, spaceMatters), spaceMatters);
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce   (     string? text, SB?     fallback, SB?     fallback2, bool         spaceMatters) => CoalesceTextAndSB(text, CoalesceTwoSBs   (fallback, fallback2, spaceMatters), spaceMatters);
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce   (     SB?     sb,   string? fallback, string? fallback2, bool         spaceMatters) => CoalesceSBAndText(sb,   CoalesceTwoTexts (fallback, fallback2, spaceMatters), spaceMatters);
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce   (     SB?     sb,   string? fallback, SB?     fallback2, bool         spaceMatters) => CoalesceSBAndText(sb,   CoalesceTextAndSB(fallback, fallback2, spaceMatters), spaceMatters);
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce   (     SB?     sb,   SB?     fallback, string? fallback2, bool         spaceMatters) => CoalesceSBAndText(sb,   CoalesceSBAndText(fallback, fallback2, spaceMatters), spaceMatters);
    /// <inheritdoc cref="_coalesce" />
    public static SB     Coalesce   (     SB?     sb,   SB?     fallback, SB?     fallback2, bool         spaceMatters) => CoalesceTwoSBs   (sb,   CoalesceTwoSBs   (fallback, fallback2, spaceMatters), spaceMatters);
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce   (     string? text, string? fallback, string? fallback2, SpaceMatters spaceMatters) => CoalesceTwoTexts (text, CoalesceTwoTexts (fallback, fallback2, spaceMatters), spaceMatters);
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce   (     string? text, string? fallback, SB?     fallback2, SpaceMatters spaceMatters) => CoalesceTwoTexts (text, CoalesceTextAndSB(fallback, fallback2, spaceMatters), spaceMatters);
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce   (     string? text, SB?     fallback, string? fallback2, SpaceMatters spaceMatters) => CoalesceTwoTexts (text, CoalesceSBAndText(fallback, fallback2, spaceMatters), spaceMatters);
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce   (     string? text, SB?     fallback, SB?     fallback2, SpaceMatters spaceMatters) => CoalesceTextAndSB(text, CoalesceTwoSBs   (fallback, fallback2, spaceMatters), spaceMatters);
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce   (     SB?     sb,   string? fallback, string? fallback2, SpaceMatters spaceMatters) => CoalesceSBAndText(sb,   CoalesceTwoTexts (fallback, fallback2, spaceMatters), spaceMatters);
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce   (     SB?     sb,   string? fallback, SB?     fallback2, SpaceMatters spaceMatters) => CoalesceSBAndText(sb,   CoalesceTextAndSB(fallback, fallback2, spaceMatters), spaceMatters);
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce   (     SB?     sb,   SB?     fallback, string? fallback2, SpaceMatters spaceMatters) => CoalesceSBAndText(sb,   CoalesceSBAndText(fallback, fallback2, spaceMatters), spaceMatters);
    /// <inheritdoc cref="_coalesce" />
    public static SB     Coalesce   (     SB?     sb,   SB?     fallback, SB?     fallback2, SpaceMatters spaceMatters) => CoalesceTwoSBs   (sb,   CoalesceTwoSBs   (fallback, fallback2, spaceMatters), spaceMatters);
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce   (     bool         spaceMatters, string? text, string? fallback, string? fallback2) => CoalesceTwoTexts (text, CoalesceTwoTexts (fallback, fallback2, spaceMatters), spaceMatters);
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce   (     bool         spaceMatters, string? text, string? fallback, SB?     fallback2) => CoalesceTwoTexts (text, CoalesceTextAndSB(fallback, fallback2, spaceMatters), spaceMatters);
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce   (     bool         spaceMatters, string? text, SB?     fallback, string? fallback2) => CoalesceTwoTexts (text, CoalesceSBAndText(fallback, fallback2, spaceMatters), spaceMatters);
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce   (     bool         spaceMatters, string? text, SB?     fallback, SB?     fallback2) => CoalesceTextAndSB(text, CoalesceTwoSBs   (fallback, fallback2, spaceMatters), spaceMatters);
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce   (     bool         spaceMatters, SB?     sb,   string? fallback, string? fallback2) => CoalesceSBAndText(sb,   CoalesceTwoTexts (fallback, fallback2, spaceMatters), spaceMatters);
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce   (     bool         spaceMatters, SB?     sb,   string? fallback, SB?     fallback2) => CoalesceSBAndText(sb,   CoalesceTextAndSB(fallback, fallback2, spaceMatters), spaceMatters);
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce   (     bool         spaceMatters, SB?     sb,   SB?     fallback, string? fallback2) => CoalesceSBAndText(sb,   CoalesceSBAndText(fallback, fallback2, spaceMatters), spaceMatters);
    /// <inheritdoc cref="_coalesce" />
    public static SB     Coalesce   (     bool         spaceMatters, SB?     sb,   SB?     fallback, SB?     fallback2) => CoalesceTwoSBs   (sb,   CoalesceTwoSBs   (fallback, fallback2, spaceMatters), spaceMatters);
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce   (     SpaceMatters spaceMatters, string? text, string? fallback, string? fallback2) => CoalesceTwoTexts (text, CoalesceTwoTexts (fallback, fallback2, spaceMatters), spaceMatters);
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce   (     SpaceMatters spaceMatters, string? text, string? fallback, SB?     fallback2) => CoalesceTwoTexts (text, CoalesceTextAndSB(fallback, fallback2, spaceMatters), spaceMatters);
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce   (     SpaceMatters spaceMatters, string? text, SB?     fallback, string? fallback2) => CoalesceTwoTexts (text, CoalesceSBAndText(fallback, fallback2, spaceMatters), spaceMatters);
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce   (     SpaceMatters spaceMatters, string? text, SB?     fallback, SB?     fallback2) => CoalesceTextAndSB(text, CoalesceTwoSBs   (fallback, fallback2, spaceMatters), spaceMatters);
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce   (     SpaceMatters spaceMatters, SB?     sb,   string? fallback, string? fallback2) => CoalesceSBAndText(sb,   CoalesceTwoTexts (fallback, fallback2, spaceMatters), spaceMatters);
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce   (     SpaceMatters spaceMatters, SB?     sb,   string? fallback, SB?     fallback2) => CoalesceSBAndText(sb,   CoalesceTextAndSB(fallback, fallback2, spaceMatters), spaceMatters);
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce   (     SpaceMatters spaceMatters, SB?     sb,   SB?     fallback, string? fallback2) => CoalesceSBAndText(sb,   CoalesceSBAndText(fallback, fallback2, spaceMatters), spaceMatters);
    /// <inheritdoc cref="_coalesce" />
    public static SB     Coalesce   (     SpaceMatters spaceMatters, SB?     sb,   SB?     fallback, SB?     fallback2) => CoalesceTwoSBs   (sb,   CoalesceTwoSBs   (fallback, fallback2, spaceMatters), spaceMatters);
    
    // TODO: Flags in Front

    // 3 Args (for some)
    
    /// <inheritdoc cref="_coalesce" /> 
    public static string Coalesce   (     object? obj,  object? fallback, string? fallback2                           )                  => CoalesceObjectToText  (obj,  CoalesceObjectToText  (fallback, fallback2));
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce<T>(     T?      val,  T?      fallback, string? fallback2                           ) where T : struct => CoalesceNullyValToText(val,  CoalesceNullyValToText(fallback, fallback2));
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce<T>(     T       val,  T?      fallback, string? fallback2                           ) where T : struct => CoalesceValToText     (val,  CoalesceNullyValToText(fallback, fallback2));
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce<T>(     T?      val,  T       fallback, string? fallback2                           ) where T : struct => CoalesceNullyValToText(val,  CoalesceValToText     (fallback, fallback2));
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce<T>(     T       val,  T       fallback, string? fallback2                           ) where T : struct => CoalesceValToText     (val,  CoalesceValToText     (fallback, fallback2));
    /// <inheritdoc cref="_coalesce" />
    public static T      Coalesce<T>(     T?      val,  T?      fallback, T?      fallback2                           ) where T : struct => CoalesceNullyAndVal   (val,  CoalesceTwoNullyVals  (fallback, fallback2));
    /// <inheritdoc cref="_coalesce" />
    public static T      Coalesce<T>(     T?      val,  T?      fallback, T       fallback2                           ) where T : struct => CoalesceNullyAndVal   (val,  CoalesceNullyAndVal   (fallback, fallback2));
    /// <inheritdoc cref="_coalesce" />
    public static T      Coalesce<T>(     T?      val,  T       fallback, T?      fallback2                           ) where T : struct => CoalesceNullyAndVal   (val,  CoalesceValAndNully   (fallback, fallback2));
    /// <inheritdoc cref="_coalesce" />
    public static T      Coalesce<T>(     T?      val,  T       fallback, T       fallback2                           ) where T : struct => CoalesceNullyAndVal   (val,  CoalesceTwoVals       (fallback, fallback2));
    /// <inheritdoc cref="_coalesce" />
    public static T      Coalesce<T>(     T       val,  T?      fallback, T?      fallback2                           ) where T : struct => CoalesceTwoVals       (val,  CoalesceTwoNullyVals  (fallback, fallback2));
    /// <inheritdoc cref="_coalesce" />
    public static T      Coalesce<T>(     T       val,  T?      fallback, T       fallback2                           ) where T : struct => CoalesceTwoVals       (val,  CoalesceNullyAndVal   (fallback, fallback2));
    /// <inheritdoc cref="_coalesce" />
    public static T      Coalesce<T>(     T       val,  T       fallback, T?      fallback2                           ) where T : struct => CoalesceTwoVals       (val,  CoalesceValAndNully   (fallback, fallback2));
    /// <inheritdoc cref="_coalesce" />
    public static T      Coalesce<T>(     T       val,  T       fallback, T       fallback2                           ) where T : struct => CoalesceTwoVals       (val,  CoalesceTwoVals       (fallback, fallback2));
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce<T>(     T?      val,  T?      fallback, string? fallback2, bool         zeroMatters ) where T : struct => CoalesceNullyValToText(val,  CoalesceNullyValToText(fallback, fallback2, zeroMatters), zeroMatters);
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce<T>(     T       val,  T?      fallback, string? fallback2, bool         zeroMatters ) where T : struct => CoalesceValToText     (val,  CoalesceNullyValToText(fallback, fallback2, zeroMatters), zeroMatters);
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce<T>(     T?      val,  T       fallback, string? fallback2, bool         zeroMatters ) where T : struct => CoalesceNullyValToText(val,  CoalesceValToText     (fallback, fallback2, zeroMatters), zeroMatters);
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce<T>(     T       val,  T       fallback, string? fallback2, bool         zeroMatters ) where T : struct => CoalesceValToText     (val,  CoalesceValToText     (fallback, fallback2, zeroMatters), zeroMatters);
    /// <inheritdoc cref="_coalesce" />
    public static T      Coalesce<T>(     T?      val,  T?      fallback, T?      fallback2, bool         zeroMatters ) where T : struct => CoalesceNullyAndVal   (val,  CoalesceTwoNullyVals  (fallback, fallback2, zeroMatters), zeroMatters);
    /// <inheritdoc cref="_coalesce" />
    public static T      Coalesce<T>(     T?      val,  T?      fallback, T       fallback2, bool         zeroMatters ) where T : struct => CoalesceNullyAndVal   (val,  CoalesceNullyAndVal   (fallback, fallback2, zeroMatters), zeroMatters);
    /// <inheritdoc cref="_coalesce" />
    public static T      Coalesce<T>(     T?      val,  T       fallback, T?      fallback2, bool         zeroMatters ) where T : struct => CoalesceNullyAndVal   (val,  CoalesceValAndNully   (fallback, fallback2, zeroMatters), zeroMatters);
    /// <inheritdoc cref="_coalesce" />
    public static T      Coalesce<T>(     T?      val,  T       fallback, T       fallback2, bool         zeroMatters ) where T : struct => CoalesceNullyAndVal   (val,  CoalesceTwoVals       (fallback, fallback2, zeroMatters), zeroMatters);
    /// <inheritdoc cref="_coalesce" />
    public static T      Coalesce<T>(     T       val,  T?      fallback, T?      fallback2, bool         zeroMatters ) where T : struct => CoalesceTwoVals       (val,  CoalesceTwoNullyVals  (fallback, fallback2, zeroMatters), zeroMatters);
    /// <inheritdoc cref="_coalesce" />
    public static T      Coalesce<T>(     T       val,  T?      fallback, T       fallback2, bool         zeroMatters ) where T : struct => CoalesceTwoVals       (val,  CoalesceNullyAndVal   (fallback, fallback2, zeroMatters), zeroMatters);
    /// <inheritdoc cref="_coalesce" />
    public static T      Coalesce<T>(     T       val,  T       fallback, T?      fallback2, bool         zeroMatters ) where T : struct => CoalesceTwoVals       (val,  CoalesceValAndNully   (fallback, fallback2, zeroMatters), zeroMatters);
    /// <inheritdoc cref="_coalesce" />
    public static T      Coalesce<T>(     T       val,  T       fallback, T       fallback2, bool         zeroMatters ) where T : struct => CoalesceTwoVals       (val,  CoalesceTwoVals       (fallback, fallback2, zeroMatters), zeroMatters);
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce<T>(     T?      val,  T?      fallback, string? fallback2, ZeroMatters  zeroMatters ) where T : struct => CoalesceNullyValToText(val,  CoalesceNullyValToText(fallback, fallback2, zeroMatters), zeroMatters);
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce<T>(     T       val,  T?      fallback, string? fallback2, ZeroMatters  zeroMatters ) where T : struct => CoalesceValToText     (val,  CoalesceNullyValToText(fallback, fallback2, zeroMatters), zeroMatters);
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce<T>(     T?      val,  T       fallback, string? fallback2, ZeroMatters  zeroMatters ) where T : struct => CoalesceNullyValToText(val,  CoalesceValToText     (fallback, fallback2, zeroMatters), zeroMatters);
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce<T>(     T       val,  T       fallback, string? fallback2, ZeroMatters  zeroMatters ) where T : struct => CoalesceValToText     (val,  CoalesceValToText     (fallback, fallback2, zeroMatters), zeroMatters);
    /// <inheritdoc cref="_coalesce" />
    public static T      Coalesce<T>(     T?      val,  T?      fallback, T?      fallback2, ZeroMatters  zeroMatters ) where T : struct => CoalesceNullyAndVal   (val,  CoalesceTwoNullyVals  (fallback, fallback2, zeroMatters), zeroMatters);
    /// <inheritdoc cref="_coalesce" />
    public static T      Coalesce<T>(     T?      val,  T?      fallback, T       fallback2, ZeroMatters  zeroMatters ) where T : struct => CoalesceNullyAndVal   (val,  CoalesceNullyAndVal   (fallback, fallback2, zeroMatters), zeroMatters);
    /// <inheritdoc cref="_coalesce" />
    public static T      Coalesce<T>(     T?      val,  T       fallback, T?      fallback2, ZeroMatters  zeroMatters ) where T : struct => CoalesceNullyAndVal   (val,  CoalesceValAndNully   (fallback, fallback2, zeroMatters), zeroMatters);
    /// <inheritdoc cref="_coalesce" />
    public static T      Coalesce<T>(     T?      val,  T       fallback, T       fallback2, ZeroMatters  zeroMatters ) where T : struct => CoalesceNullyAndVal   (val,  CoalesceTwoVals       (fallback, fallback2, zeroMatters), zeroMatters);
    /// <inheritdoc cref="_coalesce" />
    public static T      Coalesce<T>(     T       val,  T?      fallback, T?      fallback2, ZeroMatters  zeroMatters ) where T : struct => CoalesceTwoVals       (val,  CoalesceTwoNullyVals  (fallback, fallback2, zeroMatters), zeroMatters);
    /// <inheritdoc cref="_coalesce" />
    public static T      Coalesce<T>(     T       val,  T?      fallback, T       fallback2, ZeroMatters  zeroMatters ) where T : struct => CoalesceTwoVals       (val,  CoalesceNullyAndVal   (fallback, fallback2, zeroMatters), zeroMatters);
    /// <inheritdoc cref="_coalesce" />
    public static T      Coalesce<T>(     T       val,  T       fallback, T?      fallback2, ZeroMatters  zeroMatters ) where T : struct => CoalesceTwoVals       (val,  CoalesceValAndNully   (fallback, fallback2, zeroMatters), zeroMatters);
    /// <inheritdoc cref="_coalesce" />
    public static T      Coalesce<T>(     T       val,  T       fallback, T       fallback2, ZeroMatters  zeroMatters ) where T : struct => CoalesceTwoVals       (val,  CoalesceTwoVals       (fallback, fallback2, zeroMatters), zeroMatters);
    
    // N Args (for all others)
    
    /// <inheritdoc cref="_coalesce" /> 
    public static string Coalesce   (                                    params IEnumerable<string?>? fallbacks   )                  => CoalesceManyTexts  (fallbacks);
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce   (bool                  spaceMatters, params IEnumerable<string?>? fallbacks   )                  => CoalesceManyTexts  (fallbacks, spaceMatters);
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce   (SpaceMatters          spaceMatters, params IEnumerable<string?>? fallbacks   )                  => CoalesceManyTexts  (fallbacks, spaceMatters);
    /// <inheritdoc cref="_coalesce" />
    public static SB     Coalesce   (                                    params IEnumerable<SB?>?     fallbacks   )                  => CoalesceManySBs    (fallbacks              );
    /// <inheritdoc cref="_coalesce" />
    public static SB     Coalesce   (bool                  spaceMatters, params IEnumerable<SB?>?     fallbacks   )                  => CoalesceManySBs    (fallbacks, spaceMatters);
    /// <inheritdoc cref="_coalesce" />
    public static SB     Coalesce   (SpaceMatters          spaceMatters, params IEnumerable<SB?>?     fallbacks   )                  => CoalesceManySBs    (fallbacks, spaceMatters);
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce   (IEnumerable<string?>? fallbacks,    bool                         spaceMatters)                  => CoalesceManyTexts  (fallbacks, spaceMatters);
    /// <inheritdoc cref="_coalesce" />
    public static string Coalesce   (IEnumerable<string?>? fallbacks,    SpaceMatters                 spaceMatters)                  => CoalesceManyTexts  (fallbacks, spaceMatters);
    /// <inheritdoc cref="_coalesce" />
    public static SB     Coalesce   (IEnumerable<SB?>?     fallbacks,    bool                         spaceMatters)                  => CoalesceManySBs    (fallbacks, spaceMatters);
    /// <inheritdoc cref="_coalesce" />
    public static SB     Coalesce   (IEnumerable<SB?>?     fallbacks,    SpaceMatters                 spaceMatters)                  => CoalesceManySBs    (fallbacks, spaceMatters);
    /// <inheritdoc cref="_coalesce" />
    public static T      Coalesce<T>(                                    params IEnumerable<T?>?      fallbacks   ) where T : new()  => CoalesceManyObjects(fallbacks);
    /// <inheritdoc cref="_coalesce" />
    public static T      Coalesce<T>(                                    params IEnumerable<T?>?      fallbacks   ) where T : struct => CoalesceManyVals   (fallbacks);
    /// <inheritdoc cref="_coalesce" />
    public static T      Coalesce<T>(bool                  zeroMatters,  params IEnumerable<T?>?      fallbacks   ) where T : struct => CoalesceManyVals   (fallbacks, zeroMatters);
    /// <inheritdoc cref="_coalesce" />
    public static T      Coalesce<T>(ZeroMatters           zeroMatters,  params IEnumerable<T?>?      fallbacks   ) where T : struct => CoalesceManyVals   (fallbacks, zeroMatters);
    /// <inheritdoc cref="_coalesce" />
    public static T      Coalesce<T>(IEnumerable<T?>?      fallbacks,    bool                         zeroMatters ) where T : struct => CoalesceManyVals   (fallbacks, zeroMatters);
    /// <inheritdoc cref="_coalesce" />
    public static T      Coalesce<T>(IEnumerable<T?>?      fallbacks,    ZeroMatters                  zeroMatters ) where T : struct => CoalesceManyVals   (fallbacks, zeroMatters);
}
