using JetBrains.Annotations;

namespace JJ.Framework.VectorGraphics.Enums
{
    /// <summary> An enumeration of different keys on a computer keyboard that a user might strike. </summary>
    [PublicAPI]
    public enum KeyCodeEnum
    {
        /// <inheritdoc cref="DashStyleEnum.Undefined" />
        [UsedImplicitly] Undefined,
        /// <inheritdoc cref="KeyCodeEnum" />
        Back = 8,
        /// <inheritdoc cref="KeyCodeEnum" />
        Tab = 9,
        /// <inheritdoc cref="KeyCodeEnum" />
        Enter = 13,
        /// <inheritdoc cref="KeyCodeEnum" />
        Shift = 16,
        /// <inheritdoc cref="KeyCodeEnum" />
        Control = 17,
        /// <inheritdoc cref="KeyCodeEnum" />
        Alt = 18,
        /// <inheritdoc cref="KeyCodeEnum" />
        Pause = 19,
        /// <inheritdoc cref="KeyCodeEnum" />
        CapsLock = 20,
        /// <inheritdoc cref="KeyCodeEnum" />
        Escape = 27,
        /// <inheritdoc cref="KeyCodeEnum" />
        Space = 32,
        /// <inheritdoc cref="KeyCodeEnum" />
        PageUp = 33,
        /// <inheritdoc cref="KeyCodeEnum" />
        PageDown = 34,
        /// <inheritdoc cref="KeyCodeEnum" />
        End = 35,
        /// <inheritdoc cref="KeyCodeEnum" />
        Home = 36,
        /// <inheritdoc cref="KeyCodeEnum" />
        Left = 37,
        /// <inheritdoc cref="KeyCodeEnum" />
        Up = 38,
        /// <inheritdoc cref="KeyCodeEnum" />
        Right = 39,
        /// <inheritdoc cref="KeyCodeEnum" />
        Down = 40,
        /// <inheritdoc cref="KeyCodeEnum" />
        Print = 42,
        /// <inheritdoc cref="KeyCodeEnum" />
        PrintScreen = 44,
        /// <inheritdoc cref="KeyCodeEnum" />
        Insert = 45,
        /// <inheritdoc cref="KeyCodeEnum" />
        Delete = 46,
        /// <inheritdoc cref="KeyCodeEnum" />
        Digit0 = 48,
        /// <inheritdoc cref="KeyCodeEnum" />
        Digit1 = 49,
        /// <inheritdoc cref="KeyCodeEnum" />
        Digit2 = 50,
        /// <inheritdoc cref="KeyCodeEnum" />
        Digit3 = 51,
        /// <inheritdoc cref="KeyCodeEnum" />
        Digit4 = 52,
        /// <inheritdoc cref="KeyCodeEnum" />
        Digit5 = 53,
        /// <inheritdoc cref="KeyCodeEnum" />
        Digit6 = 54,
        /// <inheritdoc cref="KeyCodeEnum" />
        Digit7 = 55,
        /// <inheritdoc cref="KeyCodeEnum" />
        Digit8 = 56,
        /// <inheritdoc cref="KeyCodeEnum" />
        Digit9 = 57,
        /// <inheritdoc cref="KeyCodeEnum" />
        A = 65,
        /// <inheritdoc cref="KeyCodeEnum" />
        B = 66,
        /// <inheritdoc cref="KeyCodeEnum" />
        C = 67,
        /// <inheritdoc cref="KeyCodeEnum" />
        D = 68,
        /// <inheritdoc cref="KeyCodeEnum" />
        E = 69,
        /// <inheritdoc cref="KeyCodeEnum" />
        F = 70,
        /// <inheritdoc cref="KeyCodeEnum" />
        G = 71,
        /// <inheritdoc cref="KeyCodeEnum" />
        H = 72,
        /// <inheritdoc cref="KeyCodeEnum" />
        I = 73,
        /// <inheritdoc cref="KeyCodeEnum" />
        J = 74,
        /// <inheritdoc cref="KeyCodeEnum" />
        K = 75,
        /// <inheritdoc cref="KeyCodeEnum" />
        L = 76,
        /// <inheritdoc cref="KeyCodeEnum" />
        M = 77,
        /// <inheritdoc cref="KeyCodeEnum" />
        N = 78,
        /// <inheritdoc cref="KeyCodeEnum" />
        O = 79,
        /// <inheritdoc cref="KeyCodeEnum" />
        P = 80,
        /// <inheritdoc cref="KeyCodeEnum" />
        Q = 81,
        /// <inheritdoc cref="KeyCodeEnum" />
        R = 82,
        /// <inheritdoc cref="KeyCodeEnum" />
        S = 83,
        /// <inheritdoc cref="KeyCodeEnum" />
        T = 84,
        /// <inheritdoc cref="KeyCodeEnum" />
        U = 85,
        /// <inheritdoc cref="KeyCodeEnum" />
        V = 86,
        /// <inheritdoc cref="KeyCodeEnum" />
        W = 87,
        /// <inheritdoc cref="KeyCodeEnum" />
        X = 88,
        /// <inheritdoc cref="KeyCodeEnum" />
        Y = 89,
        /// <inheritdoc cref="KeyCodeEnum" />
        Z = 90,
        /// <inheritdoc cref="KeyCodeEnum" />
        LogoLeft = 91,
        /// <inheritdoc cref="KeyCodeEnum" />
        LogoRight = 92,
        /// <inheritdoc cref="KeyCodeEnum" />
        Sleep = 95,
        /// <inheritdoc cref="KeyCodeEnum" />
        NumericPad0 = 96,
        /// <inheritdoc cref="KeyCodeEnum" />
        NumericPad1 = 97,
        /// <inheritdoc cref="KeyCodeEnum" />
        NumericPad2 = 98,
        /// <inheritdoc cref="KeyCodeEnum" />
        NumericPad3 = 99,
        /// <inheritdoc cref="KeyCodeEnum" />
        NumericPad4 = 100,
        /// <inheritdoc cref="KeyCodeEnum" />
        NumericPad5 = 101,
        /// <inheritdoc cref="KeyCodeEnum" />
        NumericPad6 = 102,
        /// <inheritdoc cref="KeyCodeEnum" />
        NumericPad7 = 103,
        /// <inheritdoc cref="KeyCodeEnum" />
        NumericPad8 = 104,
        /// <inheritdoc cref="KeyCodeEnum" />
        NumericPad9 = 105,
        /// <inheritdoc cref="KeyCodeEnum" />
        Multiply = 106,
        /// <inheritdoc cref="KeyCodeEnum" />
        Add = 107,
        /// <inheritdoc cref="KeyCodeEnum" />
        DigitGroupingSymbol = 108,
        /// <inheritdoc cref="KeyCodeEnum" />
        Subtract = 109,
        /// <inheritdoc cref="KeyCodeEnum" />
        DecimalSymbol = 110,
        /// <inheritdoc cref="KeyCodeEnum" />
        Divide = 111,
        /// <inheritdoc cref="KeyCodeEnum" />
        F1 = 112,
        /// <inheritdoc cref="KeyCodeEnum" />
        F2 = 113,
        /// <inheritdoc cref="KeyCodeEnum" />
        F3 = 114,
        /// <inheritdoc cref="KeyCodeEnum" />
        F4 = 115,
        /// <inheritdoc cref="KeyCodeEnum" />
        F5 = 116,
        /// <inheritdoc cref="KeyCodeEnum" />
        F6 = 117,
        /// <inheritdoc cref="KeyCodeEnum" />
        F7 = 118,
        /// <inheritdoc cref="KeyCodeEnum" />
        F8 = 119,
        /// <inheritdoc cref="KeyCodeEnum" />
        F9 = 120,
        /// <inheritdoc cref="KeyCodeEnum" />
        F10 = 121,
        /// <inheritdoc cref="KeyCodeEnum" />
        F11 = 122,
        /// <inheritdoc cref="KeyCodeEnum" />
        F12 = 123,
        /// <inheritdoc cref="KeyCodeEnum" />
        NumLock = 144,
        /// <inheritdoc cref="KeyCodeEnum" />
        Scroll = 145,
        /// <inheritdoc cref="KeyCodeEnum" />
        LeftShift = 160,
        /// <inheritdoc cref="KeyCodeEnum" />
        RightShift = 161,
        /// <inheritdoc cref="KeyCodeEnum" />
        LeftControl = 162,
        /// <inheritdoc cref="KeyCodeEnum" />
        RightControl = 163,
        /// <inheritdoc cref="KeyCodeEnum" />
        LeftAlt = 164,
        /// <inheritdoc cref="KeyCodeEnum" />
        RightAlt = 165,
        /// <inheritdoc cref="KeyCodeEnum" />
        Mute = 173,
        /// <inheritdoc cref="KeyCodeEnum" />
        VolumeDown = 174,
        /// <inheritdoc cref="KeyCodeEnum" />
        VolumeUp = 175,
        /// <inheritdoc cref="KeyCodeEnum" />
        NextTrack = 176,
        /// <inheritdoc cref="KeyCodeEnum" />
        PreviousTrack = 177,
        /// <inheritdoc cref="KeyCodeEnum" />
        Stop = 178,
        /// <inheritdoc cref="KeyCodeEnum" />
        PlayPause = 179,
        /// <inheritdoc cref="KeyCodeEnum" />
        Email = 180,
        /// <inheritdoc cref="KeyCodeEnum" />
        Play = 250,
    }
}