using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Security;

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.4952
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyTitleAttribute("Iesi.Collections")]
[assembly: AssemblyDescriptionAttribute("Enhanced Collections for .NET.  Code was published at http://www.codeproject.com/" +
    "csharp/sets.asp")]
[assembly: AssemblyCompanyAttribute("NHibernate.org")]
[assembly: AssemblyProductAttribute("Iesi.Collections")]
[assembly: AssemblyCopyrightAttribute("Declaration of code in public domain can be found in comment by Jason Smith at ht" +
    "tp://www.codeproject.com/csharp/sets.asp#xx703510xx.  Copyright © 2002-2004 by A" +
    "idant Systems, Inc., and by Jason Smith.")]
[assembly: AssemblyVersionAttribute("1.0.1.0")]
[assembly: AssemblyInformationalVersionAttribute("1.0")]
[assembly: AssemblyFileVersionAttribute("3.1.0.4000")]
[assembly: AssemblyDelaySignAttribute(false)]
[assembly: AllowPartiallyTrustedCallersAttribute()]

