global using System;
global using System.Linq;
global using System.Text;
global using System.Diagnostics;
global using System.Reflection;
global using System.Runtime.InteropServices;
global using System.Runtime.Versioning;
global using System.Diagnostics.CodeAnalysis;
global using JJ.Framework.Common.Legacy;
global using JJ.Framework.Existence.Core;
global using JJ.Framework.Compilation.Core.docs;
global using JJ.Framework.PlatformCompatibility.Core;
global using JJ.Framework.Compilation.Core.Primitives;
global using static System.Environment;
global using static System.Reflection.Assembly;
global using static System.String;
global using static System.StringComparison;
global using static JJ.Framework.Common.Core.NameHelper;
global using static JJ.Framework.Common.Core.EnvironmentHelper;
global using static JJ.Framework.Existence.Core.FilledInHelper;
global using static JJ.Framework.Compilation.Core.DotNetFilledInHelper;
global using static JJ.Framework.Compilation.Core.DotNetEnricher;
global using static JJ.Framework.Compilation.Core.DotNetLogger;
global using static JJ.Framework.Compilation.Core.Formatters.DotNetFormatterHelper;
global using static JJ.Framework.Compilation.Core.Formatters.DotNetArgsFormatter;
global using static JJ.Framework.Compilation.Core.Formatters.DotNetArgOptFormatter;
global using static JJ.Framework.Compilation.Core.Formatters.DotNetCmdFormatter;
global using static JJ.Framework.Compilation.Core.Formatters.DotNetOptionsFormatter;
global using static JJ.Framework.Compilation.Core.Formatters.DotNetResultFormatter;
global using static JJ.Framework.Compilation.Core.Primitives.DotNetVerbosity;
global using static JJ.Framework.Compilation.Core.Primitives.DotNetCommandEnum;
global using static JJ.Framework.Compilation.Core.Primitives.DotNetOptions;
