global using System;
global using System.Linq;
global using System.Text;
global using System.Diagnostics;
global using System.Reflection;
global using System.Runtime.InteropServices;
global using System.Runtime.Versioning;
global using JJ.Framework.Common.Legacy;
global using JJ.Framework.Existence.Core;
global using JJ.Framework.PlatformCompatibility.Core;
global using JJ.Framework.Compilation.Core.docs;
global using static System.Environment;
global using static System.Reflection.Assembly;
global using static System.String;
global using static System.StringComparison;
global using static JJ.Framework.Exceptions.Core.Throw;
global using static JJ.Framework.Existence.Core.FilledInHelper;
global using static JJ.Framework.Compilation.Core.DotNetVerbosity;
global using static JJ.Framework.Compilation.Core.DotNetCommand;
global using static JJ.Framework.Compilation.Core.DotNetOptions;
global using static JJ.Framework.Compilation.Core.DotNetFormatter;
global using static JJ.Framework.Compilation.Core.DotNetLogger;
