global using System;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.Linq;
global using System.Text;
global using JJ.Framework.SharedProject.Core;
global using JJ.Framework.Common.Legacy;
global using JJ.Framework.Common.Core.Tests.docs;
global using JJ.Framework.Business.Core;
global using JJ.Framework.Reflection.Legacy;
global using JJ.Framework.Testing.Legacy;
global using JJ.Framework.Testing.Core;
global using JJ.Framework.Testing.Core.MSTestless;
global using JJ.Framework.Common.Core.Tests.Helpers;
global using JJ.Framework.IO.Legacy;
global using JJ.Framework.Common.Core.Tests;
global using Microsoft.VisualStudio.TestTools.UnitTesting;
global using static JJ.Framework.SharedProject.Core.NoTrimReasons;
global using static JJ.Framework.Common.Core.FlagHelper;
global using static JJ.Framework.Common.Core.Tests.Helpers.DebuggerDisplayFormatter;
global using static JJ.Framework.Testing.Legacy.AssertHelper;
global using static JJ.Framework.Testing.Core.AssertCore;
