global using System.Reflection;
global using System.Diagnostics.CodeAnalysis;
global using JJ.Framework.SharedProject.Core;
global using JJ.Framework.PlatformCompatibility.Legacy;
global using JJ.Framework.Reflection.Legacy.docs;
global using JJ.Framework.Common.Legacy;
global using static System.String;
global using static System.StringComparison;
global using static System.Reflection.BindingFlags;
global using static System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes;
global using static JJ.Framework.SharedProject.Core.DynamicallyAccessedMemberTypesEx;
global using static JJ.Framework.SharedProject.Core.NoTrimReasons;
