namespace JJ.Framework.Existence.Core.Tests;

[TestClass]
public class Coalesce_3Args_SBs_Static_NoFlags
{
    [TestMethod]
    public void Coalesce_3Args_SBs_Static_NoFlags_Batch1()
    {
        NoNullRet(                 Coalesce(NullSB,        NullSB,        NullSB       ));
        NoNullRet($"{EmptySB}", $"{Coalesce(NullSB,        NullSB,        NullSB       )}");
        NoNullRet(   EmptySB,      Coalesce(NullSB,        NullSB,        NullyEmptySB ));
        NoNullRet(   SpaceSB,      Coalesce(NullSB,        NullSB,        NullySpaceSB ));
        NoNullRet(   FilledSB,     Coalesce(NullSB,        NullSB,        NullyFilledSB));
        NoNullRet(   EmptySB,      Coalesce(NullSB,        NullSB,        EmptySB      ));
        NoNullRet(   SpaceSB,      Coalesce(NullSB,        NullSB,        SpaceSB      ));
        NoNullRet(   FilledSB,     Coalesce(NullSB,        NullSB,        FilledSB     ));
        NoNullRet(                 Coalesce(NullSB,        NullyEmptySB,  NullSB       ));
        NoNullRet($"{EmptySB}", $"{Coalesce(NullSB,        NullyEmptySB,  NullSB       )}");
        NoNullRet(   EmptySB,      Coalesce(NullSB,        NullyEmptySB,  NullyEmptySB ));
        NoNullRet(   SpaceSB,      Coalesce(NullSB,        NullyEmptySB,  NullySpaceSB ));
        NoNullRet(   FilledSB,     Coalesce(NullSB,        NullyEmptySB,  NullyFilledSB));
        NoNullRet(   EmptySB,      Coalesce(NullSB,        NullyEmptySB,  EmptySB      ));
        NoNullRet(   SpaceSB,      Coalesce(NullSB,        NullyEmptySB,  SpaceSB      ));
        NoNullRet(   FilledSB,     Coalesce(NullSB,        NullyEmptySB,  FilledSB     ));
        NoNullRet(                 Coalesce(NullSB,        NullySpaceSB,  NullSB       ));
        NoNullRet($"{EmptySB}", $"{Coalesce(NullSB,        NullySpaceSB,  NullSB       )}");
        NoNullRet(   EmptySB,      Coalesce(NullSB,        NullySpaceSB,  NullyEmptySB ));
        NoNullRet(   SpaceSB,      Coalesce(NullSB,        NullySpaceSB,  NullySpaceSB ));
        NoNullRet(   FilledSB,     Coalesce(NullSB,        NullySpaceSB,  NullyFilledSB));
        NoNullRet(   EmptySB,      Coalesce(NullSB,        NullySpaceSB,  EmptySB      ));
        NoNullRet(   SpaceSB,      Coalesce(NullSB,        NullySpaceSB,  SpaceSB      ));
        NoNullRet(   FilledSB,     Coalesce(NullSB,        NullySpaceSB,  FilledSB     ));
        NoNullRet(   FilledSB,     Coalesce(NullSB,        NullyFilledSB, NullSB       ));
        NoNullRet(   FilledSB,     Coalesce(NullSB,        NullyFilledSB, NullyEmptySB ));
        NoNullRet(   FilledSB,     Coalesce(NullSB,        NullyFilledSB, NullySpaceSB ));
        NoNullRet(   FilledSB,     Coalesce(NullSB,        NullyFilledSB, NullyFilledSB));
        NoNullRet(   FilledSB,     Coalesce(NullSB,        NullyFilledSB, EmptySB      ));
        NoNullRet(   FilledSB,     Coalesce(NullSB,        NullyFilledSB, SpaceSB      ));
        NoNullRet(   FilledSB,     Coalesce(NullSB,        NullyFilledSB, FilledSB     ));
        NoNullRet(                 Coalesce(NullSB,        EmptySB,       NullSB       ));
        NoNullRet($"{EmptySB}", $"{Coalesce(NullSB,        EmptySB,       NullSB       )}");
        NoNullRet(   EmptySB,      Coalesce(NullSB,        EmptySB,       NullyEmptySB ));
        NoNullRet(   SpaceSB,      Coalesce(NullSB,        EmptySB,       NullySpaceSB ));
        NoNullRet(   FilledSB,     Coalesce(NullSB,        EmptySB,       NullyFilledSB));
        NoNullRet(   EmptySB,      Coalesce(NullSB,        EmptySB,       EmptySB      ));
        NoNullRet(   SpaceSB,      Coalesce(NullSB,        EmptySB,       SpaceSB      ));
        NoNullRet(   FilledSB,     Coalesce(NullSB,        EmptySB,       FilledSB     ));
        NoNullRet(                 Coalesce(NullSB,        SpaceSB,       NullSB       ));
        NoNullRet($"{EmptySB}", $"{Coalesce(NullSB,        SpaceSB,       NullSB       )}");
        NoNullRet(   EmptySB,      Coalesce(NullSB,        SpaceSB,       NullyEmptySB ));
        NoNullRet(   SpaceSB,      Coalesce(NullSB,        SpaceSB,       NullySpaceSB ));
        NoNullRet(   FilledSB,     Coalesce(NullSB,        SpaceSB,       NullyFilledSB));
        NoNullRet(   EmptySB,      Coalesce(NullSB,        SpaceSB,       EmptySB      ));
        NoNullRet(   SpaceSB,      Coalesce(NullSB,        SpaceSB,       SpaceSB      ));
        NoNullRet(   FilledSB,     Coalesce(NullSB,        SpaceSB,       FilledSB     ));
        NoNullRet(   FilledSB,     Coalesce(NullSB,        FilledSB,      NullSB       ));
        NoNullRet(   FilledSB,     Coalesce(NullSB,        FilledSB,      NullyEmptySB ));
        NoNullRet(   FilledSB,     Coalesce(NullSB,        FilledSB,      NullySpaceSB ));
        NoNullRet(   FilledSB,     Coalesce(NullSB,        FilledSB,      NullyFilledSB));
        NoNullRet(   FilledSB,     Coalesce(NullSB,        FilledSB,      EmptySB      ));
        NoNullRet(   FilledSB,     Coalesce(NullSB,        FilledSB,      SpaceSB      ));
        NoNullRet(   FilledSB,     Coalesce(NullSB,        FilledSB,      FilledSB     ));
    }

    [TestMethod]
    public void Coalesce_3Args_SBs_Static_NoFlags_Batch2()
    {
        NoNullRet(                 Coalesce(NullyEmptySB,  NullSB,        NullSB       ));
        NoNullRet($"{EmptySB}", $"{Coalesce(NullyEmptySB,  NullSB,        NullSB       )}");
        NoNullRet(   EmptySB,      Coalesce(NullyEmptySB,  NullSB,        NullyEmptySB ));
        NoNullRet(   SpaceSB,      Coalesce(NullyEmptySB,  NullSB,        NullySpaceSB ));
        NoNullRet(   FilledSB,     Coalesce(NullyEmptySB,  NullSB,        NullyFilledSB));
        NoNullRet(   EmptySB,      Coalesce(NullyEmptySB,  NullSB,        EmptySB      ));
        NoNullRet(   SpaceSB,      Coalesce(NullyEmptySB,  NullSB,        SpaceSB      ));
        NoNullRet(   FilledSB,     Coalesce(NullyEmptySB,  NullSB,        FilledSB     ));
        NoNullRet(                 Coalesce(NullyEmptySB,  NullyEmptySB,  NullSB       ));
        NoNullRet($"{EmptySB}", $"{Coalesce(NullyEmptySB,  NullyEmptySB,  NullSB       )}");
        NoNullRet(   EmptySB,      Coalesce(NullyEmptySB,  NullyEmptySB,  NullyEmptySB ));
        NoNullRet(   SpaceSB,      Coalesce(NullyEmptySB,  NullyEmptySB,  NullySpaceSB ));
        NoNullRet(   FilledSB,     Coalesce(NullyEmptySB,  NullyEmptySB,  NullyFilledSB));
        NoNullRet(   EmptySB,      Coalesce(NullyEmptySB,  NullyEmptySB,  EmptySB      ));
        NoNullRet(   SpaceSB,      Coalesce(NullyEmptySB,  NullyEmptySB,  SpaceSB      ));
        NoNullRet(   FilledSB,     Coalesce(NullyEmptySB,  NullyEmptySB,  FilledSB     ));
        NoNullRet(                 Coalesce(NullyEmptySB,  NullySpaceSB,  NullSB       ));
        NoNullRet($"{EmptySB}", $"{Coalesce(NullyEmptySB,  NullySpaceSB,  NullSB       )}");
        NoNullRet(   EmptySB,      Coalesce(NullyEmptySB,  NullySpaceSB,  NullyEmptySB ));
        NoNullRet(   SpaceSB,      Coalesce(NullyEmptySB,  NullySpaceSB,  NullySpaceSB ));
        NoNullRet(   FilledSB,     Coalesce(NullyEmptySB,  NullySpaceSB,  NullyFilledSB));
        NoNullRet(   EmptySB,      Coalesce(NullyEmptySB,  NullySpaceSB,  EmptySB      ));
        NoNullRet(   SpaceSB,      Coalesce(NullyEmptySB,  NullySpaceSB,  SpaceSB      ));
        NoNullRet(   FilledSB,     Coalesce(NullyEmptySB,  NullySpaceSB,  FilledSB     ));
        NoNullRet(   FilledSB,     Coalesce(NullyEmptySB,  NullyFilledSB, NullSB       ));
        NoNullRet(   FilledSB,     Coalesce(NullyEmptySB,  NullyFilledSB, NullyEmptySB ));
        NoNullRet(   FilledSB,     Coalesce(NullyEmptySB,  NullyFilledSB, NullySpaceSB ));
        NoNullRet(   FilledSB,     Coalesce(NullyEmptySB,  NullyFilledSB, NullyFilledSB));
        NoNullRet(   FilledSB,     Coalesce(NullyEmptySB,  NullyFilledSB, EmptySB      ));
        NoNullRet(   FilledSB,     Coalesce(NullyEmptySB,  NullyFilledSB, SpaceSB      ));
        NoNullRet(   FilledSB,     Coalesce(NullyEmptySB,  NullyFilledSB, FilledSB     ));
        NoNullRet(                 Coalesce(NullyEmptySB,  EmptySB,       NullSB       ));
        NoNullRet($"{EmptySB}", $"{Coalesce(NullyEmptySB,  EmptySB,       NullSB       )}");
        NoNullRet(   EmptySB,      Coalesce(NullyEmptySB,  EmptySB,       NullyEmptySB ));
        NoNullRet(   SpaceSB,      Coalesce(NullyEmptySB,  EmptySB,       NullySpaceSB ));
        NoNullRet(   FilledSB,     Coalesce(NullyEmptySB,  EmptySB,       NullyFilledSB));
        NoNullRet(   EmptySB,      Coalesce(NullyEmptySB,  EmptySB,       EmptySB      ));
        NoNullRet(   SpaceSB,      Coalesce(NullyEmptySB,  EmptySB,       SpaceSB      ));
        NoNullRet(   FilledSB,     Coalesce(NullyEmptySB,  EmptySB,       FilledSB     ));
        NoNullRet(                 Coalesce(NullyEmptySB,  SpaceSB,       NullSB       ));
        NoNullRet($"{EmptySB}", $"{Coalesce(NullyEmptySB,  SpaceSB,       NullSB       )}");
        NoNullRet(   EmptySB,      Coalesce(NullyEmptySB,  SpaceSB,       NullyEmptySB ));
        NoNullRet(   SpaceSB,      Coalesce(NullyEmptySB,  SpaceSB,       NullySpaceSB ));
        NoNullRet(   FilledSB,     Coalesce(NullyEmptySB,  SpaceSB,       NullyFilledSB));
        NoNullRet(   EmptySB,      Coalesce(NullyEmptySB,  SpaceSB,       EmptySB      ));
        NoNullRet(   SpaceSB,      Coalesce(NullyEmptySB,  SpaceSB,       SpaceSB      ));
        NoNullRet(   FilledSB,     Coalesce(NullyEmptySB,  SpaceSB,       FilledSB     ));
        NoNullRet(   FilledSB,     Coalesce(NullyEmptySB,  FilledSB,      NullSB       ));
        NoNullRet(   FilledSB,     Coalesce(NullyEmptySB,  FilledSB,      NullyEmptySB ));
        NoNullRet(   FilledSB,     Coalesce(NullyEmptySB,  FilledSB,      NullySpaceSB ));
        NoNullRet(   FilledSB,     Coalesce(NullyEmptySB,  FilledSB,      NullyFilledSB));
        NoNullRet(   FilledSB,     Coalesce(NullyEmptySB,  FilledSB,      EmptySB      ));
        NoNullRet(   FilledSB,     Coalesce(NullyEmptySB,  FilledSB,      SpaceSB      ));
        NoNullRet(   FilledSB,     Coalesce(NullyEmptySB,  FilledSB,      FilledSB     ));
    }

    [TestMethod]
    public void Coalesce_3Args_SBs_Static_NoFlags_Batch3()
    {
        NoNullRet(                 Coalesce(NullySpaceSB,  NullSB,        NullSB       ));
        NoNullRet($"{EmptySB}", $"{Coalesce(NullySpaceSB,  NullSB,        NullSB       )}");
        NoNullRet(   EmptySB,      Coalesce(NullySpaceSB,  NullSB,        NullyEmptySB ));
        NoNullRet(   SpaceSB,      Coalesce(NullySpaceSB,  NullSB,        NullySpaceSB ));
        NoNullRet(   FilledSB,     Coalesce(NullySpaceSB,  NullSB,        NullyFilledSB));
        NoNullRet(   EmptySB,      Coalesce(NullySpaceSB,  NullSB,        EmptySB      ));
        NoNullRet(   SpaceSB,      Coalesce(NullySpaceSB,  NullSB,        SpaceSB      ));
        NoNullRet(   FilledSB,     Coalesce(NullySpaceSB,  NullSB,        FilledSB     ));
        NoNullRet(                 Coalesce(NullySpaceSB,  NullyEmptySB,  NullSB       ));
        NoNullRet($"{EmptySB}", $"{Coalesce(NullySpaceSB,  NullyEmptySB,  NullSB       )}");
        NoNullRet(   EmptySB,      Coalesce(NullySpaceSB,  NullyEmptySB,  NullyEmptySB ));
        NoNullRet(   SpaceSB,      Coalesce(NullySpaceSB,  NullyEmptySB,  NullySpaceSB ));
        NoNullRet(   FilledSB,     Coalesce(NullySpaceSB,  NullyEmptySB,  NullyFilledSB));
        NoNullRet(   EmptySB,      Coalesce(NullySpaceSB,  NullyEmptySB,  EmptySB      ));
        NoNullRet(   SpaceSB,      Coalesce(NullySpaceSB,  NullyEmptySB,  SpaceSB      ));
        NoNullRet(   FilledSB,     Coalesce(NullySpaceSB,  NullyEmptySB,  FilledSB     ));
        NoNullRet(                 Coalesce(NullySpaceSB,  NullySpaceSB,  NullSB       ));
        NoNullRet($"{EmptySB}", $"{Coalesce(NullySpaceSB,  NullySpaceSB,  NullSB       )}");
        NoNullRet(   EmptySB,      Coalesce(NullySpaceSB,  NullySpaceSB,  NullyEmptySB ));
        NoNullRet(   SpaceSB,      Coalesce(NullySpaceSB,  NullySpaceSB,  NullySpaceSB ));
        NoNullRet(   FilledSB,     Coalesce(NullySpaceSB,  NullySpaceSB,  NullyFilledSB));
        NoNullRet(   EmptySB,      Coalesce(NullySpaceSB,  NullySpaceSB,  EmptySB      ));
        NoNullRet(   SpaceSB,      Coalesce(NullySpaceSB,  NullySpaceSB,  SpaceSB      ));
        NoNullRet(   FilledSB,     Coalesce(NullySpaceSB,  NullySpaceSB,  FilledSB     ));
        NoNullRet(   FilledSB,     Coalesce(NullySpaceSB,  NullyFilledSB, NullSB       ));
        NoNullRet(   FilledSB,     Coalesce(NullySpaceSB,  NullyFilledSB, NullyEmptySB ));
        NoNullRet(   FilledSB,     Coalesce(NullySpaceSB,  NullyFilledSB, NullySpaceSB ));
        NoNullRet(   FilledSB,     Coalesce(NullySpaceSB,  NullyFilledSB, NullyFilledSB));
        NoNullRet(   FilledSB,     Coalesce(NullySpaceSB,  NullyFilledSB, EmptySB      ));
        NoNullRet(   FilledSB,     Coalesce(NullySpaceSB,  NullyFilledSB, SpaceSB      ));
        NoNullRet(   FilledSB,     Coalesce(NullySpaceSB,  NullyFilledSB, FilledSB     ));
        NoNullRet(                 Coalesce(NullySpaceSB,  EmptySB,       NullSB       ));
        NoNullRet($"{EmptySB}", $"{Coalesce(NullySpaceSB,  EmptySB,       NullSB       )}");
        NoNullRet(   EmptySB,      Coalesce(NullySpaceSB,  EmptySB,       NullyEmptySB ));
        NoNullRet(   SpaceSB,      Coalesce(NullySpaceSB,  EmptySB,       NullySpaceSB ));
        NoNullRet(   FilledSB,     Coalesce(NullySpaceSB,  EmptySB,       NullyFilledSB));
        NoNullRet(   EmptySB,      Coalesce(NullySpaceSB,  EmptySB,       EmptySB      ));
        NoNullRet(   SpaceSB,      Coalesce(NullySpaceSB,  EmptySB,       SpaceSB      ));
        NoNullRet(   FilledSB,     Coalesce(NullySpaceSB,  EmptySB,       FilledSB     ));
        NoNullRet(                 Coalesce(NullySpaceSB,  SpaceSB,       NullSB       ));
        NoNullRet($"{EmptySB}", $"{Coalesce(NullySpaceSB,  SpaceSB,       NullSB       )}");
        NoNullRet(   EmptySB,      Coalesce(NullySpaceSB,  SpaceSB,       NullyEmptySB ));
        NoNullRet(   SpaceSB,      Coalesce(NullySpaceSB,  SpaceSB,       NullySpaceSB ));
        NoNullRet(   FilledSB,     Coalesce(NullySpaceSB,  SpaceSB,       NullyFilledSB));
        NoNullRet(   EmptySB,      Coalesce(NullySpaceSB,  SpaceSB,       EmptySB      ));
        NoNullRet(   SpaceSB,      Coalesce(NullySpaceSB,  SpaceSB,       SpaceSB      ));
        NoNullRet(   FilledSB,     Coalesce(NullySpaceSB,  SpaceSB,       FilledSB     ));
        NoNullRet(   FilledSB,     Coalesce(NullySpaceSB,  FilledSB,      NullSB       ));
        NoNullRet(   FilledSB,     Coalesce(NullySpaceSB,  FilledSB,      NullyEmptySB ));
        NoNullRet(   FilledSB,     Coalesce(NullySpaceSB,  FilledSB,      NullySpaceSB ));
        NoNullRet(   FilledSB,     Coalesce(NullySpaceSB,  FilledSB,      NullyFilledSB));
        NoNullRet(   FilledSB,     Coalesce(NullySpaceSB,  FilledSB,      EmptySB      ));
        NoNullRet(   FilledSB,     Coalesce(NullySpaceSB,  FilledSB,      SpaceSB      ));
        NoNullRet(   FilledSB,     Coalesce(NullySpaceSB,  FilledSB,      FilledSB     ));
    }

    [TestMethod]
    public void Coalesce_3Args_SBs_Static_NoFlags_Batch4()
    {
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, NullSB,        NullSB       ));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, NullSB,        NullyEmptySB ));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, NullSB,        NullySpaceSB ));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, NullSB,        NullyFilledSB));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, NullSB,        EmptySB      ));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, NullSB,        SpaceSB      ));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, NullSB,        FilledSB     ));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, NullyEmptySB,  NullSB       ));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, NullyEmptySB,  NullyEmptySB ));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, NullyEmptySB,  NullySpaceSB ));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, NullyEmptySB,  NullyFilledSB));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, NullyEmptySB,  EmptySB      ));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, NullyEmptySB,  SpaceSB      ));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, NullyEmptySB,  FilledSB     ));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, NullySpaceSB,  NullSB       ));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, NullySpaceSB,  NullyEmptySB ));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, NullySpaceSB,  NullySpaceSB ));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, NullySpaceSB,  NullyFilledSB));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, NullySpaceSB,  EmptySB      ));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, NullySpaceSB,  SpaceSB      ));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, NullySpaceSB,  FilledSB     ));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, NullyFilledSB, NullSB       ));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, NullyFilledSB, NullyEmptySB ));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, NullyFilledSB, NullySpaceSB ));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, NullyFilledSB, NullyFilledSB));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, NullyFilledSB, EmptySB      ));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, NullyFilledSB, SpaceSB      ));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, NullyFilledSB, FilledSB     ));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, EmptySB,       NullSB       ));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, EmptySB,       NullyEmptySB ));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, EmptySB,       NullySpaceSB ));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, EmptySB,       NullyFilledSB));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, EmptySB,       EmptySB      ));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, EmptySB,       SpaceSB      ));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, EmptySB,       FilledSB     ));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, SpaceSB,       NullSB       ));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, SpaceSB,       NullyEmptySB ));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, SpaceSB,       NullySpaceSB ));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, SpaceSB,       NullyFilledSB));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, SpaceSB,       EmptySB      ));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, SpaceSB,       SpaceSB      ));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, SpaceSB,       FilledSB     ));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, FilledSB,      NullSB       ));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, FilledSB,      NullyEmptySB ));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, FilledSB,      NullySpaceSB ));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, FilledSB,      NullyFilledSB));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, FilledSB,      EmptySB      ));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, FilledSB,      SpaceSB      ));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, FilledSB,      FilledSB     ));
    }

    [TestMethod]
    public void Coalesce_3Args_SBs_Static_NoFlags_Batch5()
    {
        NoNullRet(                 Coalesce(EmptySB,       NullSB,        NullSB       ));
        NoNullRet($"{EmptySB}", $"{Coalesce(EmptySB,       NullSB,        NullSB       )}");
        NoNullRet(   EmptySB,      Coalesce(EmptySB,       NullSB,        NullyEmptySB ));
        NoNullRet(   SpaceSB,      Coalesce(EmptySB,       NullSB,        NullySpaceSB ));
        NoNullRet(   FilledSB,     Coalesce(EmptySB,       NullSB,        NullyFilledSB));
        NoNullRet(   EmptySB,      Coalesce(EmptySB,       NullSB,        EmptySB      ));
        NoNullRet(   SpaceSB,      Coalesce(EmptySB,       NullSB,        SpaceSB      ));
        NoNullRet(   FilledSB,     Coalesce(EmptySB,       NullSB,        FilledSB     ));
        NoNullRet(                 Coalesce(EmptySB,       NullyEmptySB,  NullSB       ));
        NoNullRet($"{EmptySB}", $"{Coalesce(EmptySB,       NullyEmptySB,  NullSB       )}");
        NoNullRet(   EmptySB,      Coalesce(EmptySB,       NullyEmptySB,  NullyEmptySB ));
        NoNullRet(   SpaceSB,      Coalesce(EmptySB,       NullyEmptySB,  NullySpaceSB ));
        NoNullRet(   FilledSB,     Coalesce(EmptySB,       NullyEmptySB,  NullyFilledSB));
        NoNullRet(   EmptySB,      Coalesce(EmptySB,       NullyEmptySB,  EmptySB      ));
        NoNullRet(   SpaceSB,      Coalesce(EmptySB,       NullyEmptySB,  SpaceSB      ));
        NoNullRet(   FilledSB,     Coalesce(EmptySB,       NullyEmptySB,  FilledSB     ));
        NoNullRet(                 Coalesce(EmptySB,       NullySpaceSB,  NullSB       ));
        NoNullRet($"{EmptySB}", $"{Coalesce(EmptySB,       NullySpaceSB,  NullSB       )}");
        NoNullRet(   EmptySB,      Coalesce(EmptySB,       NullySpaceSB,  NullyEmptySB ));
        NoNullRet(   SpaceSB,      Coalesce(EmptySB,       NullySpaceSB,  NullySpaceSB ));
        NoNullRet(   FilledSB,     Coalesce(EmptySB,       NullySpaceSB,  NullyFilledSB));
        NoNullRet(   EmptySB,      Coalesce(EmptySB,       NullySpaceSB,  EmptySB      ));
        NoNullRet(   SpaceSB,      Coalesce(EmptySB,       NullySpaceSB,  SpaceSB      ));
        NoNullRet(   FilledSB,     Coalesce(EmptySB,       NullySpaceSB,  FilledSB     ));
        NoNullRet(   FilledSB,     Coalesce(EmptySB,       NullyFilledSB, NullSB       ));
        NoNullRet(   FilledSB,     Coalesce(EmptySB,       NullyFilledSB, NullyEmptySB ));
        NoNullRet(   FilledSB,     Coalesce(EmptySB,       NullyFilledSB, NullySpaceSB ));
        NoNullRet(   FilledSB,     Coalesce(EmptySB,       NullyFilledSB, NullyFilledSB));
        NoNullRet(   FilledSB,     Coalesce(EmptySB,       NullyFilledSB, EmptySB      ));
        NoNullRet(   FilledSB,     Coalesce(EmptySB,       NullyFilledSB, SpaceSB      ));
        NoNullRet(   FilledSB,     Coalesce(EmptySB,       NullyFilledSB, FilledSB     ));
        NoNullRet(                 Coalesce(EmptySB,       EmptySB,       NullSB       ));
        NoNullRet($"{EmptySB}", $"{Coalesce(EmptySB,       EmptySB,       NullSB       )}");
        NoNullRet(   EmptySB,      Coalesce(EmptySB,       EmptySB,       NullyEmptySB ));
        NoNullRet(   SpaceSB,      Coalesce(EmptySB,       EmptySB,       NullySpaceSB ));
        NoNullRet(   FilledSB,     Coalesce(EmptySB,       EmptySB,       NullyFilledSB));
        NoNullRet(   EmptySB,      Coalesce(EmptySB,       EmptySB,       EmptySB      ));
        NoNullRet(   SpaceSB,      Coalesce(EmptySB,       EmptySB,       SpaceSB      ));
        NoNullRet(   FilledSB,     Coalesce(EmptySB,       EmptySB,       FilledSB     ));
        NoNullRet(                 Coalesce(EmptySB,       SpaceSB,       NullSB       ));
        NoNullRet($"{EmptySB}", $"{Coalesce(EmptySB,       SpaceSB,       NullSB       )}");
        NoNullRet(   EmptySB,      Coalesce(EmptySB,       SpaceSB,       NullyEmptySB ));
        NoNullRet(   SpaceSB,      Coalesce(EmptySB,       SpaceSB,       NullySpaceSB ));
        NoNullRet(   FilledSB,     Coalesce(EmptySB,       SpaceSB,       NullyFilledSB));
        NoNullRet(   EmptySB,      Coalesce(EmptySB,       SpaceSB,       EmptySB      ));
        NoNullRet(   SpaceSB,      Coalesce(EmptySB,       SpaceSB,       SpaceSB      ));
        NoNullRet(   FilledSB,     Coalesce(EmptySB,       SpaceSB,       FilledSB     ));
        NoNullRet(   FilledSB,     Coalesce(EmptySB,       FilledSB,      NullSB       ));
        NoNullRet(   FilledSB,     Coalesce(EmptySB,       FilledSB,      NullyEmptySB ));
        NoNullRet(   FilledSB,     Coalesce(EmptySB,       FilledSB,      NullySpaceSB ));
        NoNullRet(   FilledSB,     Coalesce(EmptySB,       FilledSB,      NullyFilledSB));
        NoNullRet(   FilledSB,     Coalesce(EmptySB,       FilledSB,      EmptySB      ));
        NoNullRet(   FilledSB,     Coalesce(EmptySB,       FilledSB,      SpaceSB      ));
        NoNullRet(   FilledSB,     Coalesce(EmptySB,       FilledSB,      FilledSB     ));
    }

    [TestMethod]
    public void Coalesce_3Args_SBs_Static_NoFlags_Batch6()
    {
        NoNullRet(                 Coalesce(SpaceSB,       NullSB,        NullSB       ));
        NoNullRet($"{EmptySB}", $"{Coalesce(SpaceSB,       NullSB,        NullSB       )}");
        NoNullRet(   EmptySB,      Coalesce(SpaceSB,       NullSB,        NullyEmptySB ));
        NoNullRet(   SpaceSB,      Coalesce(SpaceSB,       NullSB,        NullySpaceSB ));
        NoNullRet(   FilledSB,     Coalesce(SpaceSB,       NullSB,        NullyFilledSB));
        NoNullRet(   EmptySB,      Coalesce(SpaceSB,       NullSB,        EmptySB      ));
        NoNullRet(   SpaceSB,      Coalesce(SpaceSB,       NullSB,        SpaceSB      ));
        NoNullRet(   FilledSB,     Coalesce(SpaceSB,       NullSB,        FilledSB     ));
        NoNullRet(                 Coalesce(SpaceSB,       NullyEmptySB,  NullSB       ));
        NoNullRet($"{EmptySB}", $"{Coalesce(SpaceSB,       NullyEmptySB,  NullSB       )}");
        NoNullRet(   EmptySB,      Coalesce(SpaceSB,       NullyEmptySB,  NullyEmptySB ));
        NoNullRet(   SpaceSB,      Coalesce(SpaceSB,       NullyEmptySB,  NullySpaceSB ));
        NoNullRet(   FilledSB,     Coalesce(SpaceSB,       NullyEmptySB,  NullyFilledSB));
        NoNullRet(   EmptySB,      Coalesce(SpaceSB,       NullyEmptySB,  EmptySB      ));
        NoNullRet(   SpaceSB,      Coalesce(SpaceSB,       NullyEmptySB,  SpaceSB      ));
        NoNullRet(   FilledSB,     Coalesce(SpaceSB,       NullyEmptySB,  FilledSB     ));
        NoNullRet(                 Coalesce(SpaceSB,       NullySpaceSB,  NullSB       ));
        NoNullRet($"{EmptySB}", $"{Coalesce(SpaceSB,       NullySpaceSB,  NullSB       )}");
        NoNullRet(   EmptySB,      Coalesce(SpaceSB,       NullySpaceSB,  NullyEmptySB ));
        NoNullRet(   SpaceSB,      Coalesce(SpaceSB,       NullySpaceSB,  NullySpaceSB ));
        NoNullRet(   FilledSB,     Coalesce(SpaceSB,       NullySpaceSB,  NullyFilledSB));
        NoNullRet(   EmptySB,      Coalesce(SpaceSB,       NullySpaceSB,  EmptySB      ));
        NoNullRet(   SpaceSB,      Coalesce(SpaceSB,       NullySpaceSB,  SpaceSB      ));
        NoNullRet(   FilledSB,     Coalesce(SpaceSB,       NullySpaceSB,  FilledSB     ));
        NoNullRet(   FilledSB,     Coalesce(SpaceSB,       NullyFilledSB, NullSB       ));
        NoNullRet(   FilledSB,     Coalesce(SpaceSB,       NullyFilledSB, NullyEmptySB ));
        NoNullRet(   FilledSB,     Coalesce(SpaceSB,       NullyFilledSB, NullySpaceSB ));
        NoNullRet(   FilledSB,     Coalesce(SpaceSB,       NullyFilledSB, NullyFilledSB));
        NoNullRet(   FilledSB,     Coalesce(SpaceSB,       NullyFilledSB, EmptySB      ));
        NoNullRet(   FilledSB,     Coalesce(SpaceSB,       NullyFilledSB, SpaceSB      ));
        NoNullRet(   FilledSB,     Coalesce(SpaceSB,       NullyFilledSB, FilledSB     ));
        NoNullRet(                 Coalesce(SpaceSB,       EmptySB,       NullSB       ));
        NoNullRet($"{EmptySB}", $"{Coalesce(SpaceSB,       EmptySB,       NullSB       )}");
        NoNullRet(   EmptySB,      Coalesce(SpaceSB,       EmptySB,       NullyEmptySB ));
        NoNullRet(   SpaceSB,      Coalesce(SpaceSB,       EmptySB,       NullySpaceSB ));
        NoNullRet(   FilledSB,     Coalesce(SpaceSB,       EmptySB,       NullyFilledSB));
        NoNullRet(   EmptySB,      Coalesce(SpaceSB,       EmptySB,       EmptySB      ));
        NoNullRet(   SpaceSB,      Coalesce(SpaceSB,       EmptySB,       SpaceSB      ));
        NoNullRet(   FilledSB,     Coalesce(SpaceSB,       EmptySB,       FilledSB     ));
        NoNullRet(                 Coalesce(SpaceSB,       SpaceSB,       NullSB       ));
        NoNullRet($"{EmptySB}", $"{Coalesce(SpaceSB,       SpaceSB,       NullSB       )}");
        NoNullRet(   EmptySB,      Coalesce(SpaceSB,       SpaceSB,       NullyEmptySB ));
        NoNullRet(   SpaceSB,      Coalesce(SpaceSB,       SpaceSB,       NullySpaceSB ));
        NoNullRet(   FilledSB,     Coalesce(SpaceSB,       SpaceSB,       NullyFilledSB));
        NoNullRet(   EmptySB,      Coalesce(SpaceSB,       SpaceSB,       EmptySB      ));
        NoNullRet(   SpaceSB,      Coalesce(SpaceSB,       SpaceSB,       SpaceSB      ));
        NoNullRet(   FilledSB,     Coalesce(SpaceSB,       SpaceSB,       FilledSB     ));
        NoNullRet(   FilledSB,     Coalesce(SpaceSB,       FilledSB,      NullSB       ));
        NoNullRet(   FilledSB,     Coalesce(SpaceSB,       FilledSB,      NullyEmptySB ));
        NoNullRet(   FilledSB,     Coalesce(SpaceSB,       FilledSB,      NullySpaceSB ));
        NoNullRet(   FilledSB,     Coalesce(SpaceSB,       FilledSB,      NullyFilledSB));
        NoNullRet(   FilledSB,     Coalesce(SpaceSB,       FilledSB,      EmptySB      ));
        NoNullRet(   FilledSB,     Coalesce(SpaceSB,       FilledSB,      SpaceSB      ));
        NoNullRet(   FilledSB,     Coalesce(SpaceSB,       FilledSB,      FilledSB     ));
    }

    [TestMethod]
    public void Coalesce_3Args_SBs_Static_NoFlags_Batch7()
    {
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      NullSB,        NullSB       ));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      NullSB,        NullyEmptySB ));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      NullSB,        NullySpaceSB ));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      NullSB,        NullyFilledSB));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      NullSB,        EmptySB      ));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      NullSB,        SpaceSB      ));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      NullSB,        FilledSB     ));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      NullyEmptySB,  NullSB       ));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      NullyEmptySB,  NullyEmptySB ));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      NullyEmptySB,  NullySpaceSB ));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      NullyEmptySB,  NullyFilledSB));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      NullyEmptySB,  EmptySB      ));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      NullyEmptySB,  SpaceSB      ));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      NullyEmptySB,  FilledSB     ));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      NullySpaceSB,  NullSB       ));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      NullySpaceSB,  NullyEmptySB ));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      NullySpaceSB,  NullySpaceSB ));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      NullySpaceSB,  NullyFilledSB));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      NullySpaceSB,  EmptySB      ));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      NullySpaceSB,  SpaceSB      ));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      NullySpaceSB,  FilledSB     ));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      NullyFilledSB, NullSB       ));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      NullyFilledSB, NullyEmptySB ));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      NullyFilledSB, NullySpaceSB ));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      NullyFilledSB, NullyFilledSB));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      NullyFilledSB, EmptySB      ));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      NullyFilledSB, SpaceSB      ));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      NullyFilledSB, FilledSB     ));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      EmptySB,       NullSB       ));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      EmptySB,       NullyEmptySB ));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      EmptySB,       NullySpaceSB ));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      EmptySB,       NullyFilledSB));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      EmptySB,       EmptySB      ));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      EmptySB,       SpaceSB      ));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      EmptySB,       FilledSB     ));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      SpaceSB,       NullSB       ));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      SpaceSB,       NullyEmptySB ));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      SpaceSB,       NullySpaceSB ));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      SpaceSB,       NullyFilledSB));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      SpaceSB,       EmptySB      ));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      SpaceSB,       SpaceSB      ));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      SpaceSB,       FilledSB     ));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      FilledSB,      NullSB       ));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      FilledSB,      NullyEmptySB ));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      FilledSB,      NullySpaceSB ));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      FilledSB,      NullyFilledSB));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      FilledSB,      EmptySB      ));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      FilledSB,      SpaceSB      ));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      FilledSB,      FilledSB     ));
    }
}