namespace JJ.Framework.Existence.Core.Bool.Tests;

/// <inheritdoc cref="_coalesce4argsbool" />
[TestClass]
public class Coalesce_4Args_Bool_Static : TestBase
{
    private readonly bool? Null = null;

    [TestMethod]
    public void Coalesce_4Args_Bool_StaticBatch1()
    {
        NoNullRet(false, Coalesce(Null,       Null,       Null,       Null      ));
        NoNullRet(false, Coalesce(Null,       Null,       Null,       False     ));
        NoNullRet(true,  Coalesce(Null,       Null,       Null,       True      ));
        NoNullRet(false, Coalesce(Null,       Null,       Null,       NullyFalse));
        NoNullRet(true,  Coalesce(Null,       Null,       Null,       NullyTrue ));
        NoNullRet(false, Coalesce(Null,       Null,       False,      Null      ));
        NoNullRet(false, Coalesce(Null,       Null,       False,      False     ));
        NoNullRet(true,  Coalesce(Null,       Null,       False,      True      ));
        NoNullRet(false, Coalesce(Null,       Null,       False,      NullyFalse));
        NoNullRet(true,  Coalesce(Null,       Null,       False,      NullyTrue ));
        NoNullRet(true,  Coalesce(Null,       Null,       True,       Null      ));
        NoNullRet(true,  Coalesce(Null,       Null,       True,       False     ));
        NoNullRet(true,  Coalesce(Null,       Null,       True,       True      ));
        NoNullRet(true,  Coalesce(Null,       Null,       True,       NullyFalse));
        NoNullRet(true,  Coalesce(Null,       Null,       True,       NullyTrue ));
        NoNullRet(false, Coalesce(Null,       Null,       NullyFalse, Null      ));
        NoNullRet(false, Coalesce(Null,       Null,       NullyFalse, False     ));
        NoNullRet(true,  Coalesce(Null,       Null,       NullyFalse, True      ));
        NoNullRet(false, Coalesce(Null,       Null,       NullyFalse, NullyFalse));
        NoNullRet(true,  Coalesce(Null,       Null,       NullyFalse, NullyTrue ));
        NoNullRet(true,  Coalesce(Null,       Null,       NullyTrue,  Null      ));
        NoNullRet(true,  Coalesce(Null,       Null,       NullyTrue,  False     ));
        NoNullRet(true,  Coalesce(Null,       Null,       NullyTrue,  True      ));
        NoNullRet(true,  Coalesce(Null,       Null,       NullyTrue,  NullyFalse));
        NoNullRet(true,  Coalesce(Null,       Null,       NullyTrue,  NullyTrue ));
        NoNullRet(false, Coalesce(Null,       False,      Null,       Null      ));
        NoNullRet(false, Coalesce(Null,       False,      Null,       False     ));
        NoNullRet(true,  Coalesce(Null,       False,      Null,       True      ));
        NoNullRet(false, Coalesce(Null,       False,      Null,       NullyFalse));
        NoNullRet(true,  Coalesce(Null,       False,      Null,       NullyTrue ));
        NoNullRet(false, Coalesce(Null,       False,      False,      Null      ));
        NoNullRet(false, Coalesce(Null,       False,      False,      False     ));
        NoNullRet(true,  Coalesce(Null,       False,      False,      True      ));
        NoNullRet(false, Coalesce(Null,       False,      False,      NullyFalse));
        NoNullRet(true,  Coalesce(Null,       False,      False,      NullyTrue ));
        NoNullRet(true,  Coalesce(Null,       False,      True,       Null      ));
        NoNullRet(true,  Coalesce(Null,       False,      True,       False     ));
        NoNullRet(true,  Coalesce(Null,       False,      True,       True      ));
        NoNullRet(true,  Coalesce(Null,       False,      True,       NullyFalse));
        NoNullRet(true,  Coalesce(Null,       False,      True,       NullyTrue ));
        NoNullRet(false, Coalesce(Null,       False,      NullyFalse, Null      ));
        NoNullRet(false, Coalesce(Null,       False,      NullyFalse, False     ));
        NoNullRet(true,  Coalesce(Null,       False,      NullyFalse, True      ));
        NoNullRet(false, Coalesce(Null,       False,      NullyFalse, NullyFalse));
        NoNullRet(true,  Coalesce(Null,       False,      NullyFalse, NullyTrue ));
        NoNullRet(true,  Coalesce(Null,       False,      NullyTrue,  Null      ));
        NoNullRet(true,  Coalesce(Null,       False,      NullyTrue,  False     ));
        NoNullRet(true,  Coalesce(Null,       False,      NullyTrue,  True      ));
        NoNullRet(true,  Coalesce(Null,       False,      NullyTrue,  NullyFalse));
        NoNullRet(true,  Coalesce(Null,       False,      NullyTrue,  NullyTrue ));
        NoNullRet(true,  Coalesce(Null,       True,       Null,       Null      ));
        NoNullRet(true,  Coalesce(Null,       True,       Null,       False     ));
        NoNullRet(true,  Coalesce(Null,       True,       Null,       True      ));
        NoNullRet(true,  Coalesce(Null,       True,       Null,       NullyFalse));
        NoNullRet(true,  Coalesce(Null,       True,       Null,       NullyTrue ));
        NoNullRet(true,  Coalesce(Null,       True,       False,      Null      ));
        NoNullRet(true,  Coalesce(Null,       True,       False,      False     ));
        NoNullRet(true,  Coalesce(Null,       True,       False,      True      ));
        NoNullRet(true,  Coalesce(Null,       True,       False,      NullyFalse));
        NoNullRet(true,  Coalesce(Null,       True,       False,      NullyTrue ));
        NoNullRet(true,  Coalesce(Null,       True,       True,       Null      ));
        NoNullRet(true,  Coalesce(Null,       True,       True,       False     ));
        NoNullRet(true,  Coalesce(Null,       True,       True,       True      ));
        NoNullRet(true,  Coalesce(Null,       True,       True,       NullyFalse));
        NoNullRet(true,  Coalesce(Null,       True,       True,       NullyTrue ));
        NoNullRet(true,  Coalesce(Null,       True,       NullyFalse, Null      ));
        NoNullRet(true,  Coalesce(Null,       True,       NullyFalse, False     ));
        NoNullRet(true,  Coalesce(Null,       True,       NullyFalse, True      ));
        NoNullRet(true,  Coalesce(Null,       True,       NullyFalse, NullyFalse));
        NoNullRet(true,  Coalesce(Null,       True,       NullyFalse, NullyTrue ));
        NoNullRet(true,  Coalesce(Null,       True,       NullyTrue,  Null      ));
        NoNullRet(true,  Coalesce(Null,       True,       NullyTrue,  False     ));
        NoNullRet(true,  Coalesce(Null,       True,       NullyTrue,  True      ));
        NoNullRet(true,  Coalesce(Null,       True,       NullyTrue,  NullyFalse));
        NoNullRet(true,  Coalesce(Null,       True,       NullyTrue,  NullyTrue ));
        NoNullRet(false, Coalesce(Null,       NullyFalse, Null,       Null      ));
        NoNullRet(false, Coalesce(Null,       NullyFalse, Null,       False     ));
        NoNullRet(true,  Coalesce(Null,       NullyFalse, Null,       True      ));
        NoNullRet(false, Coalesce(Null,       NullyFalse, Null,       NullyFalse));
        NoNullRet(true,  Coalesce(Null,       NullyFalse, Null,       NullyTrue ));
        NoNullRet(false, Coalesce(Null,       NullyFalse, False,      Null      ));
        NoNullRet(false, Coalesce(Null,       NullyFalse, False,      False     ));
        NoNullRet(true,  Coalesce(Null,       NullyFalse, False,      True      ));
        NoNullRet(false, Coalesce(Null,       NullyFalse, False,      NullyFalse));
        NoNullRet(true,  Coalesce(Null,       NullyFalse, False,      NullyTrue ));
        NoNullRet(true,  Coalesce(Null,       NullyFalse, True,       Null      ));
        NoNullRet(true,  Coalesce(Null,       NullyFalse, True,       False     ));
        NoNullRet(true,  Coalesce(Null,       NullyFalse, True,       True      ));
        NoNullRet(true,  Coalesce(Null,       NullyFalse, True,       NullyFalse));
        NoNullRet(true,  Coalesce(Null,       NullyFalse, True,       NullyTrue ));
        NoNullRet(false, Coalesce(Null,       NullyFalse, NullyFalse, Null      ));
        NoNullRet(false, Coalesce(Null,       NullyFalse, NullyFalse, False     ));
        NoNullRet(true,  Coalesce(Null,       NullyFalse, NullyFalse, True      ));
        NoNullRet(false, Coalesce(Null,       NullyFalse, NullyFalse, NullyFalse));
        NoNullRet(true,  Coalesce(Null,       NullyFalse, NullyFalse, NullyTrue ));
        NoNullRet(true,  Coalesce(Null,       NullyFalse, NullyTrue,  Null      ));
        NoNullRet(true,  Coalesce(Null,       NullyFalse, NullyTrue,  False     ));
        NoNullRet(true,  Coalesce(Null,       NullyFalse, NullyTrue,  True      ));
        NoNullRet(true,  Coalesce(Null,       NullyFalse, NullyTrue,  NullyFalse));
        NoNullRet(true,  Coalesce(Null,       NullyFalse, NullyTrue,  NullyTrue ));
        NoNullRet(true,  Coalesce(Null,       NullyTrue,  Null,       Null      ));
        NoNullRet(true,  Coalesce(Null,       NullyTrue,  Null,       False     ));
        NoNullRet(true,  Coalesce(Null,       NullyTrue,  Null,       True      ));
        NoNullRet(true,  Coalesce(Null,       NullyTrue,  Null,       NullyFalse));
        NoNullRet(true,  Coalesce(Null,       NullyTrue,  Null,       NullyTrue ));
        NoNullRet(true,  Coalesce(Null,       NullyTrue,  False,      Null      ));
        NoNullRet(true,  Coalesce(Null,       NullyTrue,  False,      False     ));
        NoNullRet(true,  Coalesce(Null,       NullyTrue,  False,      True      ));
        NoNullRet(true,  Coalesce(Null,       NullyTrue,  False,      NullyFalse));
        NoNullRet(true,  Coalesce(Null,       NullyTrue,  False,      NullyTrue ));
        NoNullRet(true,  Coalesce(Null,       NullyTrue,  True,       Null      ));
        NoNullRet(true,  Coalesce(Null,       NullyTrue,  True,       False     ));
        NoNullRet(true,  Coalesce(Null,       NullyTrue,  True,       True      ));
        NoNullRet(true,  Coalesce(Null,       NullyTrue,  True,       NullyFalse));
        NoNullRet(true,  Coalesce(Null,       NullyTrue,  True,       NullyTrue ));
        NoNullRet(true,  Coalesce(Null,       NullyTrue,  NullyFalse, Null      ));
        NoNullRet(true,  Coalesce(Null,       NullyTrue,  NullyFalse, False     ));
        NoNullRet(true,  Coalesce(Null,       NullyTrue,  NullyFalse, True      ));
        NoNullRet(true,  Coalesce(Null,       NullyTrue,  NullyFalse, NullyFalse));
        NoNullRet(true,  Coalesce(Null,       NullyTrue,  NullyFalse, NullyTrue ));
        NoNullRet(true,  Coalesce(Null,       NullyTrue,  NullyTrue,  Null      ));
        NoNullRet(true,  Coalesce(Null,       NullyTrue,  NullyTrue,  False     ));
        NoNullRet(true,  Coalesce(Null,       NullyTrue,  NullyTrue,  True      ));
        NoNullRet(true,  Coalesce(Null,       NullyTrue,  NullyTrue,  NullyFalse));
        NoNullRet(true,  Coalesce(Null,       NullyTrue,  NullyTrue,  NullyTrue ));
    }

    [TestMethod]
    public void Coalesce_4Args_Bool_StaticBatch2()
    {
        NoNullRet(false, Coalesce(False,      Null,       Null,       Null      ));
        NoNullRet(false, Coalesce(False,      Null,       Null,       False     ));
        NoNullRet(true,  Coalesce(False,      Null,       Null,       True      ));
        NoNullRet(false, Coalesce(False,      Null,       Null,       NullyFalse));
        NoNullRet(true,  Coalesce(False,      Null,       Null,       NullyTrue ));
        NoNullRet(false, Coalesce(False,      Null,       False,      Null      ));
        NoNullRet(false, Coalesce(False,      Null,       False,      False     ));
        NoNullRet(true,  Coalesce(False,      Null,       False,      True      ));
        NoNullRet(false, Coalesce(False,      Null,       False,      NullyFalse));
        NoNullRet(true,  Coalesce(False,      Null,       False,      NullyTrue ));
        NoNullRet(true,  Coalesce(False,      Null,       True,       Null      ));
        NoNullRet(true,  Coalesce(False,      Null,       True,       False     ));
        NoNullRet(true,  Coalesce(False,      Null,       True,       True      ));
        NoNullRet(true,  Coalesce(False,      Null,       True,       NullyFalse));
        NoNullRet(true,  Coalesce(False,      Null,       True,       NullyTrue ));
        NoNullRet(false, Coalesce(False,      Null,       NullyFalse, Null      ));
        NoNullRet(false, Coalesce(False,      Null,       NullyFalse, False     ));
        NoNullRet(true,  Coalesce(False,      Null,       NullyFalse, True      ));
        NoNullRet(false, Coalesce(False,      Null,       NullyFalse, NullyFalse));
        NoNullRet(true,  Coalesce(False,      Null,       NullyFalse, NullyTrue ));
        NoNullRet(true,  Coalesce(False,      Null,       NullyTrue,  Null      ));
        NoNullRet(true,  Coalesce(False,      Null,       NullyTrue,  False     ));
        NoNullRet(true,  Coalesce(False,      Null,       NullyTrue,  True      ));
        NoNullRet(true,  Coalesce(False,      Null,       NullyTrue,  NullyFalse));
        NoNullRet(true,  Coalesce(False,      Null,       NullyTrue,  NullyTrue ));
        NoNullRet(false, Coalesce(False,      False,      Null,       Null      ));
        NoNullRet(false, Coalesce(False,      False,      Null,       False     ));
        NoNullRet(true,  Coalesce(False,      False,      Null,       True      ));
        NoNullRet(false, Coalesce(False,      False,      Null,       NullyFalse));
        NoNullRet(true,  Coalesce(False,      False,      Null,       NullyTrue ));
        NoNullRet(false, Coalesce(False,      False,      False,      Null      ));
        NoNullRet(false, Coalesce(False,      False,      False,      False     ));
        NoNullRet(true,  Coalesce(False,      False,      False,      True      ));
        NoNullRet(false, Coalesce(False,      False,      False,      NullyFalse));
        NoNullRet(true,  Coalesce(False,      False,      False,      NullyTrue ));
        NoNullRet(true,  Coalesce(False,      False,      True,       Null      ));
        NoNullRet(true,  Coalesce(False,      False,      True,       False     ));
        NoNullRet(true,  Coalesce(False,      False,      True,       True      ));
        NoNullRet(true,  Coalesce(False,      False,      True,       NullyFalse));
        NoNullRet(true,  Coalesce(False,      False,      True,       NullyTrue ));
        NoNullRet(false, Coalesce(False,      False,      NullyFalse, Null      ));
        NoNullRet(false, Coalesce(False,      False,      NullyFalse, False     ));
        NoNullRet(true,  Coalesce(False,      False,      NullyFalse, True      ));
        NoNullRet(false, Coalesce(False,      False,      NullyFalse, NullyFalse));
        NoNullRet(true,  Coalesce(False,      False,      NullyFalse, NullyTrue ));
        NoNullRet(true,  Coalesce(False,      False,      NullyTrue,  Null      ));
        NoNullRet(true,  Coalesce(False,      False,      NullyTrue,  False     ));
        NoNullRet(true,  Coalesce(False,      False,      NullyTrue,  True      ));
        NoNullRet(true,  Coalesce(False,      False,      NullyTrue,  NullyFalse));
        NoNullRet(true,  Coalesce(False,      False,      NullyTrue,  NullyTrue ));
        NoNullRet(true,  Coalesce(False,      True,       Null,       Null      ));
        NoNullRet(true,  Coalesce(False,      True,       Null,       False     ));
        NoNullRet(true,  Coalesce(False,      True,       Null,       True      ));
        NoNullRet(true,  Coalesce(False,      True,       Null,       NullyFalse));
        NoNullRet(true,  Coalesce(False,      True,       Null,       NullyTrue ));
        NoNullRet(true,  Coalesce(False,      True,       False,      Null      ));
        NoNullRet(true,  Coalesce(False,      True,       False,      False     ));
        NoNullRet(true,  Coalesce(False,      True,       False,      True      ));
        NoNullRet(true,  Coalesce(False,      True,       False,      NullyFalse));
        NoNullRet(true,  Coalesce(False,      True,       False,      NullyTrue ));
        NoNullRet(true,  Coalesce(False,      True,       True,       Null      ));
        NoNullRet(true,  Coalesce(False,      True,       True,       False     ));
        NoNullRet(true,  Coalesce(False,      True,       True,       True      ));
        NoNullRet(true,  Coalesce(False,      True,       True,       NullyFalse));
        NoNullRet(true,  Coalesce(False,      True,       True,       NullyTrue ));
        NoNullRet(true,  Coalesce(False,      True,       NullyFalse, Null      ));
        NoNullRet(true,  Coalesce(False,      True,       NullyFalse, False     ));
        NoNullRet(true,  Coalesce(False,      True,       NullyFalse, True      ));
        NoNullRet(true,  Coalesce(False,      True,       NullyFalse, NullyFalse));
        NoNullRet(true,  Coalesce(False,      True,       NullyFalse, NullyTrue ));
        NoNullRet(true,  Coalesce(False,      True,       NullyTrue,  Null      ));
        NoNullRet(true,  Coalesce(False,      True,       NullyTrue,  False     ));
        NoNullRet(true,  Coalesce(False,      True,       NullyTrue,  True      ));
        NoNullRet(true,  Coalesce(False,      True,       NullyTrue,  NullyFalse));
        NoNullRet(true,  Coalesce(False,      True,       NullyTrue,  NullyTrue ));
        NoNullRet(false, Coalesce(False,      NullyFalse, Null,       Null      ));
        NoNullRet(false, Coalesce(False,      NullyFalse, Null,       False     ));
        NoNullRet(true,  Coalesce(False,      NullyFalse, Null,       True      ));
        NoNullRet(false, Coalesce(False,      NullyFalse, Null,       NullyFalse));
        NoNullRet(true,  Coalesce(False,      NullyFalse, Null,       NullyTrue ));
        NoNullRet(false, Coalesce(False,      NullyFalse, False,      Null      ));
        NoNullRet(false, Coalesce(False,      NullyFalse, False,      False     ));
        NoNullRet(true,  Coalesce(False,      NullyFalse, False,      True      ));
        NoNullRet(false, Coalesce(False,      NullyFalse, False,      NullyFalse));
        NoNullRet(true,  Coalesce(False,      NullyFalse, False,      NullyTrue ));
        NoNullRet(true,  Coalesce(False,      NullyFalse, True,       Null      ));
        NoNullRet(true,  Coalesce(False,      NullyFalse, True,       False     ));
        NoNullRet(true,  Coalesce(False,      NullyFalse, True,       True      ));
        NoNullRet(true,  Coalesce(False,      NullyFalse, True,       NullyFalse));
        NoNullRet(true,  Coalesce(False,      NullyFalse, True,       NullyTrue ));
        NoNullRet(false, Coalesce(False,      NullyFalse, NullyFalse, Null      ));
        NoNullRet(false, Coalesce(False,      NullyFalse, NullyFalse, False     ));
        NoNullRet(true,  Coalesce(False,      NullyFalse, NullyFalse, True      ));
        NoNullRet(false, Coalesce(False,      NullyFalse, NullyFalse, NullyFalse));
        NoNullRet(true,  Coalesce(False,      NullyFalse, NullyFalse, NullyTrue ));
        NoNullRet(true,  Coalesce(False,      NullyFalse, NullyTrue,  Null      ));
        NoNullRet(true,  Coalesce(False,      NullyFalse, NullyTrue,  False     ));
        NoNullRet(true,  Coalesce(False,      NullyFalse, NullyTrue,  True      ));
        NoNullRet(true,  Coalesce(False,      NullyFalse, NullyTrue,  NullyFalse));
        NoNullRet(true,  Coalesce(False,      NullyFalse, NullyTrue,  NullyTrue ));
        NoNullRet(true,  Coalesce(False,      NullyTrue,  Null,       Null      ));
        NoNullRet(true,  Coalesce(False,      NullyTrue,  Null,       False     ));
        NoNullRet(true,  Coalesce(False,      NullyTrue,  Null,       True      ));
        NoNullRet(true,  Coalesce(False,      NullyTrue,  Null,       NullyFalse));
        NoNullRet(true,  Coalesce(False,      NullyTrue,  Null,       NullyTrue ));
        NoNullRet(true,  Coalesce(False,      NullyTrue,  False,      Null      ));
        NoNullRet(true,  Coalesce(False,      NullyTrue,  False,      False     ));
        NoNullRet(true,  Coalesce(False,      NullyTrue,  False,      True      ));
        NoNullRet(true,  Coalesce(False,      NullyTrue,  False,      NullyFalse));
        NoNullRet(true,  Coalesce(False,      NullyTrue,  False,      NullyTrue ));
        NoNullRet(true,  Coalesce(False,      NullyTrue,  True,       Null      ));
        NoNullRet(true,  Coalesce(False,      NullyTrue,  True,       False     ));
        NoNullRet(true,  Coalesce(False,      NullyTrue,  True,       True      ));
        NoNullRet(true,  Coalesce(False,      NullyTrue,  True,       NullyFalse));
        NoNullRet(true,  Coalesce(False,      NullyTrue,  True,       NullyTrue ));
        NoNullRet(true,  Coalesce(False,      NullyTrue,  NullyFalse, Null      ));
        NoNullRet(true,  Coalesce(False,      NullyTrue,  NullyFalse, False     ));
        NoNullRet(true,  Coalesce(False,      NullyTrue,  NullyFalse, True      ));
        NoNullRet(true,  Coalesce(False,      NullyTrue,  NullyFalse, NullyFalse));
        NoNullRet(true,  Coalesce(False,      NullyTrue,  NullyFalse, NullyTrue ));
        NoNullRet(true,  Coalesce(False,      NullyTrue,  NullyTrue,  Null      ));
        NoNullRet(true,  Coalesce(False,      NullyTrue,  NullyTrue,  False     ));
        NoNullRet(true,  Coalesce(False,      NullyTrue,  NullyTrue,  True      ));
        NoNullRet(true,  Coalesce(False,      NullyTrue,  NullyTrue,  NullyFalse));
        NoNullRet(true,  Coalesce(False,      NullyTrue,  NullyTrue,  NullyTrue ));
    }

    [TestMethod]
    public void Coalesce_4Args_Bool_StaticBatch3()
    {
        NoNullRet(true,  Coalesce(True,       Null,       Null,       Null      ));
        NoNullRet(true,  Coalesce(True,       Null,       Null,       False     ));
        NoNullRet(true,  Coalesce(True,       Null,       Null,       True      ));
        NoNullRet(true,  Coalesce(True,       Null,       Null,       NullyFalse));
        NoNullRet(true,  Coalesce(True,       Null,       Null,       NullyTrue ));
        NoNullRet(true,  Coalesce(True,       Null,       False,      Null      ));
        NoNullRet(true,  Coalesce(True,       Null,       False,      False     ));
        NoNullRet(true,  Coalesce(True,       Null,       False,      True      ));
        NoNullRet(true,  Coalesce(True,       Null,       False,      NullyFalse));
        NoNullRet(true,  Coalesce(True,       Null,       False,      NullyTrue ));
        NoNullRet(true,  Coalesce(True,       Null,       True,       Null      ));
        NoNullRet(true,  Coalesce(True,       Null,       True,       False     ));
        NoNullRet(true,  Coalesce(True,       Null,       True,       True      ));
        NoNullRet(true,  Coalesce(True,       Null,       True,       NullyFalse));
        NoNullRet(true,  Coalesce(True,       Null,       True,       NullyTrue ));
        NoNullRet(true,  Coalesce(True,       Null,       NullyFalse, Null      ));
        NoNullRet(true,  Coalesce(True,       Null,       NullyFalse, False     ));
        NoNullRet(true,  Coalesce(True,       Null,       NullyFalse, True      ));
        NoNullRet(true,  Coalesce(True,       Null,       NullyFalse, NullyFalse));
        NoNullRet(true,  Coalesce(True,       Null,       NullyFalse, NullyTrue ));
        NoNullRet(true,  Coalesce(True,       Null,       NullyTrue,  Null      ));
        NoNullRet(true,  Coalesce(True,       Null,       NullyTrue,  False     ));
        NoNullRet(true,  Coalesce(True,       Null,       NullyTrue,  True      ));
        NoNullRet(true,  Coalesce(True,       Null,       NullyTrue,  NullyFalse));
        NoNullRet(true,  Coalesce(True,       Null,       NullyTrue,  NullyTrue ));
        NoNullRet(true,  Coalesce(True,       False,      Null,       Null      ));
        NoNullRet(true,  Coalesce(True,       False,      Null,       False     ));
        NoNullRet(true,  Coalesce(True,       False,      Null,       True      ));
        NoNullRet(true,  Coalesce(True,       False,      Null,       NullyFalse));
        NoNullRet(true,  Coalesce(True,       False,      Null,       NullyTrue ));
        NoNullRet(true,  Coalesce(True,       False,      False,      Null      ));
        NoNullRet(true,  Coalesce(True,       False,      False,      False     ));
        NoNullRet(true,  Coalesce(True,       False,      False,      True      ));
        NoNullRet(true,  Coalesce(True,       False,      False,      NullyFalse));
        NoNullRet(true,  Coalesce(True,       False,      False,      NullyTrue ));
        NoNullRet(true,  Coalesce(True,       False,      True,       Null      ));
        NoNullRet(true,  Coalesce(True,       False,      True,       False     ));
        NoNullRet(true,  Coalesce(True,       False,      True,       True      ));
        NoNullRet(true,  Coalesce(True,       False,      True,       NullyFalse));
        NoNullRet(true,  Coalesce(True,       False,      True,       NullyTrue ));
        NoNullRet(true,  Coalesce(True,       False,      NullyFalse, Null      ));
        NoNullRet(true,  Coalesce(True,       False,      NullyFalse, False     ));
        NoNullRet(true,  Coalesce(True,       False,      NullyFalse, True      ));
        NoNullRet(true,  Coalesce(True,       False,      NullyFalse, NullyFalse));
        NoNullRet(true,  Coalesce(True,       False,      NullyFalse, NullyTrue ));
        NoNullRet(true,  Coalesce(True,       False,      NullyTrue,  Null      ));
        NoNullRet(true,  Coalesce(True,       False,      NullyTrue,  False     ));
        NoNullRet(true,  Coalesce(True,       False,      NullyTrue,  True      ));
        NoNullRet(true,  Coalesce(True,       False,      NullyTrue,  NullyFalse));
        NoNullRet(true,  Coalesce(True,       False,      NullyTrue,  NullyTrue ));
        NoNullRet(true,  Coalesce(True,       True,       Null,       Null      ));
        NoNullRet(true,  Coalesce(True,       True,       Null,       False     ));
        NoNullRet(true,  Coalesce(True,       True,       Null,       True      ));
        NoNullRet(true,  Coalesce(True,       True,       Null,       NullyFalse));
        NoNullRet(true,  Coalesce(True,       True,       Null,       NullyTrue ));
        NoNullRet(true,  Coalesce(True,       True,       False,      Null      ));
        NoNullRet(true,  Coalesce(True,       True,       False,      False     ));
        NoNullRet(true,  Coalesce(True,       True,       False,      True      ));
        NoNullRet(true,  Coalesce(True,       True,       False,      NullyFalse));
        NoNullRet(true,  Coalesce(True,       True,       False,      NullyTrue ));
        NoNullRet(true,  Coalesce(True,       True,       True,       Null      ));
        NoNullRet(true,  Coalesce(True,       True,       True,       False     ));
        NoNullRet(true,  Coalesce(True,       True,       True,       True      ));
        NoNullRet(true,  Coalesce(True,       True,       True,       NullyFalse));
        NoNullRet(true,  Coalesce(True,       True,       True,       NullyTrue ));
        NoNullRet(true,  Coalesce(True,       True,       NullyFalse, Null      ));
        NoNullRet(true,  Coalesce(True,       True,       NullyFalse, False     ));
        NoNullRet(true,  Coalesce(True,       True,       NullyFalse, True      ));
        NoNullRet(true,  Coalesce(True,       True,       NullyFalse, NullyFalse));
        NoNullRet(true,  Coalesce(True,       True,       NullyFalse, NullyTrue ));
        NoNullRet(true,  Coalesce(True,       True,       NullyTrue,  Null      ));
        NoNullRet(true,  Coalesce(True,       True,       NullyTrue,  False     ));
        NoNullRet(true,  Coalesce(True,       True,       NullyTrue,  True      ));
        NoNullRet(true,  Coalesce(True,       True,       NullyTrue,  NullyFalse));
        NoNullRet(true,  Coalesce(True,       True,       NullyTrue,  NullyTrue ));
        NoNullRet(true,  Coalesce(True,       NullyFalse, Null,       Null      ));
        NoNullRet(true,  Coalesce(True,       NullyFalse, Null,       False     ));
        NoNullRet(true,  Coalesce(True,       NullyFalse, Null,       True      ));
        NoNullRet(true,  Coalesce(True,       NullyFalse, Null,       NullyFalse));
        NoNullRet(true,  Coalesce(True,       NullyFalse, Null,       NullyTrue ));
        NoNullRet(true,  Coalesce(True,       NullyFalse, False,      Null      ));
        NoNullRet(true,  Coalesce(True,       NullyFalse, False,      False     ));
        NoNullRet(true,  Coalesce(True,       NullyFalse, False,      True      ));
        NoNullRet(true,  Coalesce(True,       NullyFalse, False,      NullyFalse));
        NoNullRet(true,  Coalesce(True,       NullyFalse, False,      NullyTrue ));
        NoNullRet(true,  Coalesce(True,       NullyFalse, True,       Null      ));
        NoNullRet(true,  Coalesce(True,       NullyFalse, True,       False     ));
        NoNullRet(true,  Coalesce(True,       NullyFalse, True,       True      ));
        NoNullRet(true,  Coalesce(True,       NullyFalse, True,       NullyFalse));
        NoNullRet(true,  Coalesce(True,       NullyFalse, True,       NullyTrue ));
        NoNullRet(true,  Coalesce(True,       NullyFalse, NullyFalse, Null      ));
        NoNullRet(true,  Coalesce(True,       NullyFalse, NullyFalse, False     ));
        NoNullRet(true,  Coalesce(True,       NullyFalse, NullyFalse, True      ));
        NoNullRet(true,  Coalesce(True,       NullyFalse, NullyFalse, NullyFalse));
        NoNullRet(true,  Coalesce(True,       NullyFalse, NullyFalse, NullyTrue ));
        NoNullRet(true,  Coalesce(True,       NullyFalse, NullyTrue,  Null      ));
        NoNullRet(true,  Coalesce(True,       NullyFalse, NullyTrue,  False     ));
        NoNullRet(true,  Coalesce(True,       NullyFalse, NullyTrue,  True      ));
        NoNullRet(true,  Coalesce(True,       NullyFalse, NullyTrue,  NullyFalse));
        NoNullRet(true,  Coalesce(True,       NullyFalse, NullyTrue,  NullyTrue ));
        NoNullRet(true,  Coalesce(True,       NullyTrue,  Null,       Null      ));
        NoNullRet(true,  Coalesce(True,       NullyTrue,  Null,       False     ));
        NoNullRet(true,  Coalesce(True,       NullyTrue,  Null,       True      ));
        NoNullRet(true,  Coalesce(True,       NullyTrue,  Null,       NullyFalse));
        NoNullRet(true,  Coalesce(True,       NullyTrue,  Null,       NullyTrue ));
        NoNullRet(true,  Coalesce(True,       NullyTrue,  False,      Null      ));
        NoNullRet(true,  Coalesce(True,       NullyTrue,  False,      False     ));
        NoNullRet(true,  Coalesce(True,       NullyTrue,  False,      True      ));
        NoNullRet(true,  Coalesce(True,       NullyTrue,  False,      NullyFalse));
        NoNullRet(true,  Coalesce(True,       NullyTrue,  False,      NullyTrue ));
        NoNullRet(true,  Coalesce(True,       NullyTrue,  True,       Null      ));
        NoNullRet(true,  Coalesce(True,       NullyTrue,  True,       False     ));
        NoNullRet(true,  Coalesce(True,       NullyTrue,  True,       True      ));
        NoNullRet(true,  Coalesce(True,       NullyTrue,  True,       NullyFalse));
        NoNullRet(true,  Coalesce(True,       NullyTrue,  True,       NullyTrue ));
        NoNullRet(true,  Coalesce(True,       NullyTrue,  NullyFalse, Null      ));
        NoNullRet(true,  Coalesce(True,       NullyTrue,  NullyFalse, False     ));
        NoNullRet(true,  Coalesce(True,       NullyTrue,  NullyFalse, True      ));
        NoNullRet(true,  Coalesce(True,       NullyTrue,  NullyFalse, NullyFalse));
        NoNullRet(true,  Coalesce(True,       NullyTrue,  NullyFalse, NullyTrue ));
        NoNullRet(true,  Coalesce(True,       NullyTrue,  NullyTrue,  Null      ));
        NoNullRet(true,  Coalesce(True,       NullyTrue,  NullyTrue,  False     ));
        NoNullRet(true,  Coalesce(True,       NullyTrue,  NullyTrue,  True      ));
        NoNullRet(true,  Coalesce(True,       NullyTrue,  NullyTrue,  NullyFalse));
        NoNullRet(true,  Coalesce(True,       NullyTrue,  NullyTrue,  NullyTrue ));
    }

    [TestMethod]
    public void Coalesce_4Args_Bool_StaticBatch4()
    {
        NoNullRet(false, Coalesce(NullyFalse, Null,       Null,       Null      ));
        NoNullRet(false, Coalesce(NullyFalse, Null,       Null,       False     ));
        NoNullRet(true,  Coalesce(NullyFalse, Null,       Null,       True      ));
        NoNullRet(false, Coalesce(NullyFalse, Null,       Null,       NullyFalse));
        NoNullRet(true,  Coalesce(NullyFalse, Null,       Null,       NullyTrue ));
        NoNullRet(false, Coalesce(NullyFalse, Null,       False,      Null      ));
        NoNullRet(false, Coalesce(NullyFalse, Null,       False,      False     ));
        NoNullRet(true,  Coalesce(NullyFalse, Null,       False,      True      ));
        NoNullRet(false, Coalesce(NullyFalse, Null,       False,      NullyFalse));
        NoNullRet(true,  Coalesce(NullyFalse, Null,       False,      NullyTrue ));
        NoNullRet(true,  Coalesce(NullyFalse, Null,       True,       Null      ));
        NoNullRet(true,  Coalesce(NullyFalse, Null,       True,       False     ));
        NoNullRet(true,  Coalesce(NullyFalse, Null,       True,       True      ));
        NoNullRet(true,  Coalesce(NullyFalse, Null,       True,       NullyFalse));
        NoNullRet(true,  Coalesce(NullyFalse, Null,       True,       NullyTrue ));
        NoNullRet(false, Coalesce(NullyFalse, Null,       NullyFalse, Null      ));
        NoNullRet(false, Coalesce(NullyFalse, Null,       NullyFalse, False     ));
        NoNullRet(true,  Coalesce(NullyFalse, Null,       NullyFalse, True      ));
        NoNullRet(false, Coalesce(NullyFalse, Null,       NullyFalse, NullyFalse));
        NoNullRet(true,  Coalesce(NullyFalse, Null,       NullyFalse, NullyTrue ));
        NoNullRet(true,  Coalesce(NullyFalse, Null,       NullyTrue,  Null      ));
        NoNullRet(true,  Coalesce(NullyFalse, Null,       NullyTrue,  False     ));
        NoNullRet(true,  Coalesce(NullyFalse, Null,       NullyTrue,  True      ));
        NoNullRet(true,  Coalesce(NullyFalse, Null,       NullyTrue,  NullyFalse));
        NoNullRet(true,  Coalesce(NullyFalse, Null,       NullyTrue,  NullyTrue ));
        NoNullRet(false, Coalesce(NullyFalse, False,      Null,       Null      ));
        NoNullRet(false, Coalesce(NullyFalse, False,      Null,       False     ));
        NoNullRet(true,  Coalesce(NullyFalse, False,      Null,       True      ));
        NoNullRet(false, Coalesce(NullyFalse, False,      Null,       NullyFalse));
        NoNullRet(true,  Coalesce(NullyFalse, False,      Null,       NullyTrue ));
        NoNullRet(false, Coalesce(NullyFalse, False,      False,      Null      ));
        NoNullRet(false, Coalesce(NullyFalse, False,      False,      False     ));
        NoNullRet(true,  Coalesce(NullyFalse, False,      False,      True      ));
        NoNullRet(false, Coalesce(NullyFalse, False,      False,      NullyFalse));
        NoNullRet(true,  Coalesce(NullyFalse, False,      False,      NullyTrue ));
        NoNullRet(true,  Coalesce(NullyFalse, False,      True,       Null      ));
        NoNullRet(true,  Coalesce(NullyFalse, False,      True,       False     ));
        NoNullRet(true,  Coalesce(NullyFalse, False,      True,       True      ));
        NoNullRet(true,  Coalesce(NullyFalse, False,      True,       NullyFalse));
        NoNullRet(true,  Coalesce(NullyFalse, False,      True,       NullyTrue ));
        NoNullRet(false, Coalesce(NullyFalse, False,      NullyFalse, Null      ));
        NoNullRet(false, Coalesce(NullyFalse, False,      NullyFalse, False     ));
        NoNullRet(true,  Coalesce(NullyFalse, False,      NullyFalse, True      ));
        NoNullRet(false, Coalesce(NullyFalse, False,      NullyFalse, NullyFalse));
        NoNullRet(true,  Coalesce(NullyFalse, False,      NullyFalse, NullyTrue ));
        NoNullRet(true,  Coalesce(NullyFalse, False,      NullyTrue,  Null      ));
        NoNullRet(true,  Coalesce(NullyFalse, False,      NullyTrue,  False     ));
        NoNullRet(true,  Coalesce(NullyFalse, False,      NullyTrue,  True      ));
        NoNullRet(true,  Coalesce(NullyFalse, False,      NullyTrue,  NullyFalse));
        NoNullRet(true,  Coalesce(NullyFalse, False,      NullyTrue,  NullyTrue ));
        NoNullRet(true,  Coalesce(NullyFalse, True,       Null,       Null      ));
        NoNullRet(true,  Coalesce(NullyFalse, True,       Null,       False     ));
        NoNullRet(true,  Coalesce(NullyFalse, True,       Null,       True      ));
        NoNullRet(true,  Coalesce(NullyFalse, True,       Null,       NullyFalse));
        NoNullRet(true,  Coalesce(NullyFalse, True,       Null,       NullyTrue ));
        NoNullRet(true,  Coalesce(NullyFalse, True,       False,      Null      ));
        NoNullRet(true,  Coalesce(NullyFalse, True,       False,      False     ));
        NoNullRet(true,  Coalesce(NullyFalse, True,       False,      True      ));
        NoNullRet(true,  Coalesce(NullyFalse, True,       False,      NullyFalse));
        NoNullRet(true,  Coalesce(NullyFalse, True,       False,      NullyTrue ));
        NoNullRet(true,  Coalesce(NullyFalse, True,       True,       Null      ));
        NoNullRet(true,  Coalesce(NullyFalse, True,       True,       False     ));
        NoNullRet(true,  Coalesce(NullyFalse, True,       True,       True      ));
        NoNullRet(true,  Coalesce(NullyFalse, True,       True,       NullyFalse));
        NoNullRet(true,  Coalesce(NullyFalse, True,       True,       NullyTrue ));
        NoNullRet(true,  Coalesce(NullyFalse, True,       NullyFalse, Null      ));
        NoNullRet(true,  Coalesce(NullyFalse, True,       NullyFalse, False     ));
        NoNullRet(true,  Coalesce(NullyFalse, True,       NullyFalse, True      ));
        NoNullRet(true,  Coalesce(NullyFalse, True,       NullyFalse, NullyFalse));
        NoNullRet(true,  Coalesce(NullyFalse, True,       NullyFalse, NullyTrue ));
        NoNullRet(true,  Coalesce(NullyFalse, True,       NullyTrue,  Null      ));
        NoNullRet(true,  Coalesce(NullyFalse, True,       NullyTrue,  False     ));
        NoNullRet(true,  Coalesce(NullyFalse, True,       NullyTrue,  True      ));
        NoNullRet(true,  Coalesce(NullyFalse, True,       NullyTrue,  NullyFalse));
        NoNullRet(true,  Coalesce(NullyFalse, True,       NullyTrue,  NullyTrue ));
        NoNullRet(false, Coalesce(NullyFalse, NullyFalse, Null,       Null      ));
        NoNullRet(false, Coalesce(NullyFalse, NullyFalse, Null,       False     ));
        NoNullRet(true,  Coalesce(NullyFalse, NullyFalse, Null,       True      ));
        NoNullRet(false, Coalesce(NullyFalse, NullyFalse, Null,       NullyFalse));
        NoNullRet(true,  Coalesce(NullyFalse, NullyFalse, Null,       NullyTrue ));
        NoNullRet(false, Coalesce(NullyFalse, NullyFalse, False,      Null      ));
        NoNullRet(false, Coalesce(NullyFalse, NullyFalse, False,      False     ));
        NoNullRet(true,  Coalesce(NullyFalse, NullyFalse, False,      True      ));
        NoNullRet(false, Coalesce(NullyFalse, NullyFalse, False,      NullyFalse));
        NoNullRet(true,  Coalesce(NullyFalse, NullyFalse, False,      NullyTrue ));
        NoNullRet(true,  Coalesce(NullyFalse, NullyFalse, True,       Null      ));
        NoNullRet(true,  Coalesce(NullyFalse, NullyFalse, True,       False     ));
        NoNullRet(true,  Coalesce(NullyFalse, NullyFalse, True,       True      ));
        NoNullRet(true,  Coalesce(NullyFalse, NullyFalse, True,       NullyFalse));
        NoNullRet(true,  Coalesce(NullyFalse, NullyFalse, True,       NullyTrue ));
        NoNullRet(false, Coalesce(NullyFalse, NullyFalse, NullyFalse, Null      ));
        NoNullRet(false, Coalesce(NullyFalse, NullyFalse, NullyFalse, False     ));
        NoNullRet(true,  Coalesce(NullyFalse, NullyFalse, NullyFalse, True      ));
        NoNullRet(false, Coalesce(NullyFalse, NullyFalse, NullyFalse, NullyFalse));
        NoNullRet(true,  Coalesce(NullyFalse, NullyFalse, NullyFalse, NullyTrue ));
        NoNullRet(true,  Coalesce(NullyFalse, NullyFalse, NullyTrue,  Null      ));
        NoNullRet(true,  Coalesce(NullyFalse, NullyFalse, NullyTrue,  False     ));
        NoNullRet(true,  Coalesce(NullyFalse, NullyFalse, NullyTrue,  True      ));
        NoNullRet(true,  Coalesce(NullyFalse, NullyFalse, NullyTrue,  NullyFalse));
        NoNullRet(true,  Coalesce(NullyFalse, NullyFalse, NullyTrue,  NullyTrue ));
        NoNullRet(true,  Coalesce(NullyFalse, NullyTrue,  Null,       Null      ));
        NoNullRet(true,  Coalesce(NullyFalse, NullyTrue,  Null,       False     ));
        NoNullRet(true,  Coalesce(NullyFalse, NullyTrue,  Null,       True      ));
        NoNullRet(true,  Coalesce(NullyFalse, NullyTrue,  Null,       NullyFalse));
        NoNullRet(true,  Coalesce(NullyFalse, NullyTrue,  Null,       NullyTrue ));
        NoNullRet(true,  Coalesce(NullyFalse, NullyTrue,  False,      Null      ));
        NoNullRet(true,  Coalesce(NullyFalse, NullyTrue,  False,      False     ));
        NoNullRet(true,  Coalesce(NullyFalse, NullyTrue,  False,      True      ));
        NoNullRet(true,  Coalesce(NullyFalse, NullyTrue,  False,      NullyFalse));
        NoNullRet(true,  Coalesce(NullyFalse, NullyTrue,  False,      NullyTrue ));
        NoNullRet(true,  Coalesce(NullyFalse, NullyTrue,  True,       Null      ));
        NoNullRet(true,  Coalesce(NullyFalse, NullyTrue,  True,       False     ));
        NoNullRet(true,  Coalesce(NullyFalse, NullyTrue,  True,       True      ));
        NoNullRet(true,  Coalesce(NullyFalse, NullyTrue,  True,       NullyFalse));
        NoNullRet(true,  Coalesce(NullyFalse, NullyTrue,  True,       NullyTrue ));
        NoNullRet(true,  Coalesce(NullyFalse, NullyTrue,  NullyFalse, Null      ));
        NoNullRet(true,  Coalesce(NullyFalse, NullyTrue,  NullyFalse, False     ));
        NoNullRet(true,  Coalesce(NullyFalse, NullyTrue,  NullyFalse, True      ));
        NoNullRet(true,  Coalesce(NullyFalse, NullyTrue,  NullyFalse, NullyFalse));
        NoNullRet(true,  Coalesce(NullyFalse, NullyTrue,  NullyFalse, NullyTrue ));
        NoNullRet(true,  Coalesce(NullyFalse, NullyTrue,  NullyTrue,  Null      ));
        NoNullRet(true,  Coalesce(NullyFalse, NullyTrue,  NullyTrue,  False     ));
        NoNullRet(true,  Coalesce(NullyFalse, NullyTrue,  NullyTrue,  True      ));
        NoNullRet(true,  Coalesce(NullyFalse, NullyTrue,  NullyTrue,  NullyFalse));
        NoNullRet(true,  Coalesce(NullyFalse, NullyTrue,  NullyTrue,  NullyTrue ));
    }

    [TestMethod]
    public void Coalesce_4Args_Bool_StaticBatch5()
    {
        NoNullRet(true,  Coalesce(NullyTrue,  Null,       Null,       Null      ));
        NoNullRet(true,  Coalesce(NullyTrue,  Null,       Null,       False     ));
        NoNullRet(true,  Coalesce(NullyTrue,  Null,       Null,       True      ));
        NoNullRet(true,  Coalesce(NullyTrue,  Null,       Null,       NullyFalse));
        NoNullRet(true,  Coalesce(NullyTrue,  Null,       Null,       NullyTrue ));
        NoNullRet(true,  Coalesce(NullyTrue,  Null,       False,      Null      ));
        NoNullRet(true,  Coalesce(NullyTrue,  Null,       False,      False     ));
        NoNullRet(true,  Coalesce(NullyTrue,  Null,       False,      True      ));
        NoNullRet(true,  Coalesce(NullyTrue,  Null,       False,      NullyFalse));
        NoNullRet(true,  Coalesce(NullyTrue,  Null,       False,      NullyTrue ));
        NoNullRet(true,  Coalesce(NullyTrue,  Null,       True,       Null      ));
        NoNullRet(true,  Coalesce(NullyTrue,  Null,       True,       False     ));
        NoNullRet(true,  Coalesce(NullyTrue,  Null,       True,       True      ));
        NoNullRet(true,  Coalesce(NullyTrue,  Null,       True,       NullyFalse));
        NoNullRet(true,  Coalesce(NullyTrue,  Null,       True,       NullyTrue ));
        NoNullRet(true,  Coalesce(NullyTrue,  Null,       NullyFalse, Null      ));
        NoNullRet(true,  Coalesce(NullyTrue,  Null,       NullyFalse, False     ));
        NoNullRet(true,  Coalesce(NullyTrue,  Null,       NullyFalse, True      ));
        NoNullRet(true,  Coalesce(NullyTrue,  Null,       NullyFalse, NullyFalse));
        NoNullRet(true,  Coalesce(NullyTrue,  Null,       NullyFalse, NullyTrue ));
        NoNullRet(true,  Coalesce(NullyTrue,  Null,       NullyTrue,  Null      ));
        NoNullRet(true,  Coalesce(NullyTrue,  Null,       NullyTrue,  False     ));
        NoNullRet(true,  Coalesce(NullyTrue,  Null,       NullyTrue,  True      ));
        NoNullRet(true,  Coalesce(NullyTrue,  Null,       NullyTrue,  NullyFalse));
        NoNullRet(true,  Coalesce(NullyTrue,  Null,       NullyTrue,  NullyTrue ));
        NoNullRet(true,  Coalesce(NullyTrue,  False,      Null,       Null      ));
        NoNullRet(true,  Coalesce(NullyTrue,  False,      Null,       False     ));
        NoNullRet(true,  Coalesce(NullyTrue,  False,      Null,       True      ));
        NoNullRet(true,  Coalesce(NullyTrue,  False,      Null,       NullyFalse));
        NoNullRet(true,  Coalesce(NullyTrue,  False,      Null,       NullyTrue ));
        NoNullRet(true,  Coalesce(NullyTrue,  False,      False,      Null      ));
        NoNullRet(true,  Coalesce(NullyTrue,  False,      False,      False     ));
        NoNullRet(true,  Coalesce(NullyTrue,  False,      False,      True      ));
        NoNullRet(true,  Coalesce(NullyTrue,  False,      False,      NullyFalse));
        NoNullRet(true,  Coalesce(NullyTrue,  False,      False,      NullyTrue ));
        NoNullRet(true,  Coalesce(NullyTrue,  False,      True,       Null      ));
        NoNullRet(true,  Coalesce(NullyTrue,  False,      True,       False     ));
        NoNullRet(true,  Coalesce(NullyTrue,  False,      True,       True      ));
        NoNullRet(true,  Coalesce(NullyTrue,  False,      True,       NullyFalse));
        NoNullRet(true,  Coalesce(NullyTrue,  False,      True,       NullyTrue ));
        NoNullRet(true,  Coalesce(NullyTrue,  False,      NullyFalse, Null      ));
        NoNullRet(true,  Coalesce(NullyTrue,  False,      NullyFalse, False     ));
        NoNullRet(true,  Coalesce(NullyTrue,  False,      NullyFalse, True      ));
        NoNullRet(true,  Coalesce(NullyTrue,  False,      NullyFalse, NullyFalse));
        NoNullRet(true,  Coalesce(NullyTrue,  False,      NullyFalse, NullyTrue ));
        NoNullRet(true,  Coalesce(NullyTrue,  False,      NullyTrue,  Null      ));
        NoNullRet(true,  Coalesce(NullyTrue,  False,      NullyTrue,  False     ));
        NoNullRet(true,  Coalesce(NullyTrue,  False,      NullyTrue,  True      ));
        NoNullRet(true,  Coalesce(NullyTrue,  False,      NullyTrue,  NullyFalse));
        NoNullRet(true,  Coalesce(NullyTrue,  False,      NullyTrue,  NullyTrue ));
        NoNullRet(true,  Coalesce(NullyTrue,  True,       Null,       Null      ));
        NoNullRet(true,  Coalesce(NullyTrue,  True,       Null,       False     ));
        NoNullRet(true,  Coalesce(NullyTrue,  True,       Null,       True      ));
        NoNullRet(true,  Coalesce(NullyTrue,  True,       Null,       NullyFalse));
        NoNullRet(true,  Coalesce(NullyTrue,  True,       Null,       NullyTrue ));
        NoNullRet(true,  Coalesce(NullyTrue,  True,       False,      Null      ));
        NoNullRet(true,  Coalesce(NullyTrue,  True,       False,      False     ));
        NoNullRet(true,  Coalesce(NullyTrue,  True,       False,      True      ));
        NoNullRet(true,  Coalesce(NullyTrue,  True,       False,      NullyFalse));
        NoNullRet(true,  Coalesce(NullyTrue,  True,       False,      NullyTrue ));
        NoNullRet(true,  Coalesce(NullyTrue,  True,       True,       Null      ));
        NoNullRet(true,  Coalesce(NullyTrue,  True,       True,       False     ));
        NoNullRet(true,  Coalesce(NullyTrue,  True,       True,       True      ));
        NoNullRet(true,  Coalesce(NullyTrue,  True,       True,       NullyFalse));
        NoNullRet(true,  Coalesce(NullyTrue,  True,       True,       NullyTrue ));
        NoNullRet(true,  Coalesce(NullyTrue,  True,       NullyFalse, Null      ));
        NoNullRet(true,  Coalesce(NullyTrue,  True,       NullyFalse, False     ));
        NoNullRet(true,  Coalesce(NullyTrue,  True,       NullyFalse, True      ));
        NoNullRet(true,  Coalesce(NullyTrue,  True,       NullyFalse, NullyFalse));
        NoNullRet(true,  Coalesce(NullyTrue,  True,       NullyFalse, NullyTrue ));
        NoNullRet(true,  Coalesce(NullyTrue,  True,       NullyTrue,  Null      ));
        NoNullRet(true,  Coalesce(NullyTrue,  True,       NullyTrue,  False     ));
        NoNullRet(true,  Coalesce(NullyTrue,  True,       NullyTrue,  True      ));
        NoNullRet(true,  Coalesce(NullyTrue,  True,       NullyTrue,  NullyFalse));
        NoNullRet(true,  Coalesce(NullyTrue,  True,       NullyTrue,  NullyTrue ));
        NoNullRet(true,  Coalesce(NullyTrue,  NullyFalse, Null,       Null      ));
        NoNullRet(true,  Coalesce(NullyTrue,  NullyFalse, Null,       False     ));
        NoNullRet(true,  Coalesce(NullyTrue,  NullyFalse, Null,       True      ));
        NoNullRet(true,  Coalesce(NullyTrue,  NullyFalse, Null,       NullyFalse));
        NoNullRet(true,  Coalesce(NullyTrue,  NullyFalse, Null,       NullyTrue ));
        NoNullRet(true,  Coalesce(NullyTrue,  NullyFalse, False,      Null      ));
        NoNullRet(true,  Coalesce(NullyTrue,  NullyFalse, False,      False     ));
        NoNullRet(true,  Coalesce(NullyTrue,  NullyFalse, False,      True      ));
        NoNullRet(true,  Coalesce(NullyTrue,  NullyFalse, False,      NullyFalse));
        NoNullRet(true,  Coalesce(NullyTrue,  NullyFalse, False,      NullyTrue ));
        NoNullRet(true,  Coalesce(NullyTrue,  NullyFalse, True,       Null      ));
        NoNullRet(true,  Coalesce(NullyTrue,  NullyFalse, True,       False     ));
        NoNullRet(true,  Coalesce(NullyTrue,  NullyFalse, True,       True      ));
        NoNullRet(true,  Coalesce(NullyTrue,  NullyFalse, True,       NullyFalse));
        NoNullRet(true,  Coalesce(NullyTrue,  NullyFalse, True,       NullyTrue ));
        NoNullRet(true,  Coalesce(NullyTrue,  NullyFalse, NullyFalse, Null      ));
        NoNullRet(true,  Coalesce(NullyTrue,  NullyFalse, NullyFalse, False     ));
        NoNullRet(true,  Coalesce(NullyTrue,  NullyFalse, NullyFalse, True      ));
        NoNullRet(true,  Coalesce(NullyTrue,  NullyFalse, NullyFalse, NullyFalse));
        NoNullRet(true,  Coalesce(NullyTrue,  NullyFalse, NullyFalse, NullyTrue ));
        NoNullRet(true,  Coalesce(NullyTrue,  NullyFalse, NullyTrue,  Null      ));
        NoNullRet(true,  Coalesce(NullyTrue,  NullyFalse, NullyTrue,  False     ));
        NoNullRet(true,  Coalesce(NullyTrue,  NullyFalse, NullyTrue,  True      ));
        NoNullRet(true,  Coalesce(NullyTrue,  NullyFalse, NullyTrue,  NullyFalse));
        NoNullRet(true,  Coalesce(NullyTrue,  NullyFalse, NullyTrue,  NullyTrue ));
        NoNullRet(true,  Coalesce(NullyTrue,  NullyTrue,  Null,       Null      ));
        NoNullRet(true,  Coalesce(NullyTrue,  NullyTrue,  Null,       False     ));
        NoNullRet(true,  Coalesce(NullyTrue,  NullyTrue,  Null,       True      ));
        NoNullRet(true,  Coalesce(NullyTrue,  NullyTrue,  Null,       NullyFalse));
        NoNullRet(true,  Coalesce(NullyTrue,  NullyTrue,  Null,       NullyTrue ));
        NoNullRet(true,  Coalesce(NullyTrue,  NullyTrue,  False,      Null      ));
        NoNullRet(true,  Coalesce(NullyTrue,  NullyTrue,  False,      False     ));
        NoNullRet(true,  Coalesce(NullyTrue,  NullyTrue,  False,      True      ));
        NoNullRet(true,  Coalesce(NullyTrue,  NullyTrue,  False,      NullyFalse));
        NoNullRet(true,  Coalesce(NullyTrue,  NullyTrue,  False,      NullyTrue ));
        NoNullRet(true,  Coalesce(NullyTrue,  NullyTrue,  True,       Null      ));
        NoNullRet(true,  Coalesce(NullyTrue,  NullyTrue,  True,       False     ));
        NoNullRet(true,  Coalesce(NullyTrue,  NullyTrue,  True,       True      ));
        NoNullRet(true,  Coalesce(NullyTrue,  NullyTrue,  True,       NullyFalse));
        NoNullRet(true,  Coalesce(NullyTrue,  NullyTrue,  True,       NullyTrue ));
        NoNullRet(true,  Coalesce(NullyTrue,  NullyTrue,  NullyFalse, Null      ));
        NoNullRet(true,  Coalesce(NullyTrue,  NullyTrue,  NullyFalse, False     ));
        NoNullRet(true,  Coalesce(NullyTrue,  NullyTrue,  NullyFalse, True      ));
        NoNullRet(true,  Coalesce(NullyTrue,  NullyTrue,  NullyFalse, NullyFalse));
        NoNullRet(true,  Coalesce(NullyTrue,  NullyTrue,  NullyFalse, NullyTrue ));
        NoNullRet(true,  Coalesce(NullyTrue,  NullyTrue,  NullyTrue,  Null      ));
        NoNullRet(true,  Coalesce(NullyTrue,  NullyTrue,  NullyTrue,  False     ));
        NoNullRet(true,  Coalesce(NullyTrue,  NullyTrue,  NullyTrue,  True      ));
        NoNullRet(true,  Coalesce(NullyTrue,  NullyTrue,  NullyTrue,  NullyFalse));
        NoNullRet(true,  Coalesce(NullyTrue,  NullyTrue,  NullyTrue,  NullyTrue ));
    }
}
