namespace JJ.Framework.Existence.Core.SBs.Tests;

[TestClass]
public class Coalesce_3Args_SBs_Extensions_NoFlags : TestBase
{
    [TestMethod]
    public void Coalesce_3Args_SBs_Extensions_NoFlags_Batch1()
    {
        NoNullRet(                 NullSB       .Coalesce(NullSB,        NullSB       ));
        NoNullRet($"{EmptySB}", $"{NullSB       .Coalesce(NullSB,        NullSB       )}");
        NoNullRet(   EmptySB,      NullSB       .Coalesce(NullSB,        NullyEmptySB ));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(NullSB,        NullySpaceSB ));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(NullSB,        NullyFilledSB));
        NoNullRet(   EmptySB,      NullSB       .Coalesce(NullSB,        EmptySB      ));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(NullSB,        SpaceSB      ));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(NullSB,        FilledSB     ));
        NoNullRet(                 NullSB       .Coalesce(NullyEmptySB,  NullSB       ));
        NoNullRet($"{EmptySB}", $"{NullSB       .Coalesce(NullyEmptySB,  NullSB       )}");
        NoNullRet(   EmptySB,      NullSB       .Coalesce(NullyEmptySB,  NullyEmptySB ));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(NullyEmptySB,  NullySpaceSB ));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(NullyEmptySB,  NullyFilledSB));
        NoNullRet(   EmptySB,      NullSB       .Coalesce(NullyEmptySB,  EmptySB      ));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(NullyEmptySB,  SpaceSB      ));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(NullyEmptySB,  FilledSB     ));
        NoNullRet(                 NullSB       .Coalesce(NullySpaceSB,  NullSB       ));
        NoNullRet($"{EmptySB}", $"{NullSB       .Coalesce(NullySpaceSB,  NullSB       )}");
        NoNullRet(   EmptySB,      NullSB       .Coalesce(NullySpaceSB,  NullyEmptySB ));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(NullySpaceSB,  NullySpaceSB ));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(NullySpaceSB,  NullyFilledSB));
        NoNullRet(   EmptySB,      NullSB       .Coalesce(NullySpaceSB,  EmptySB      ));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(NullySpaceSB,  SpaceSB      ));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(NullySpaceSB,  FilledSB     ));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(NullyFilledSB, NullSB       ));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(NullyFilledSB, NullyEmptySB ));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(NullyFilledSB, NullySpaceSB ));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(NullyFilledSB, NullyFilledSB));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(NullyFilledSB, EmptySB      ));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(NullyFilledSB, SpaceSB      ));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(NullyFilledSB, FilledSB     ));
        NoNullRet(                 NullSB       .Coalesce(EmptySB,       NullSB       ));
        NoNullRet($"{EmptySB}", $"{NullSB       .Coalesce(EmptySB,       NullSB       )}");
        NoNullRet(   EmptySB,      NullSB       .Coalesce(EmptySB,       NullyEmptySB ));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(EmptySB,       NullySpaceSB ));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(EmptySB,       NullyFilledSB));
        NoNullRet(   EmptySB,      NullSB       .Coalesce(EmptySB,       EmptySB      ));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(EmptySB,       SpaceSB      ));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(EmptySB,       FilledSB     ));
        NoNullRet(                 NullSB       .Coalesce(SpaceSB,       NullSB       ));
        NoNullRet($"{EmptySB}", $"{NullSB       .Coalesce(SpaceSB,       NullSB       )}");
        NoNullRet(   EmptySB,      NullSB       .Coalesce(SpaceSB,       NullyEmptySB ));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(SpaceSB,       NullySpaceSB ));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(SpaceSB,       NullyFilledSB));
        NoNullRet(   EmptySB,      NullSB       .Coalesce(SpaceSB,       EmptySB      ));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(SpaceSB,       SpaceSB      ));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(SpaceSB,       FilledSB     ));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(FilledSB,      NullSB       ));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(FilledSB,      NullyEmptySB ));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(FilledSB,      NullySpaceSB ));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(FilledSB,      NullyFilledSB));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(FilledSB,      EmptySB      ));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(FilledSB,      SpaceSB      ));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(FilledSB,      FilledSB     ));
    }

    [TestMethod]
    public void Coalesce_3Args_SBs_Extensions_NoFlags_Batch2()
    {
        NoNullRet(                 NullyEmptySB .Coalesce(NullSB,        NullSB       ));
        NoNullRet($"{EmptySB}", $"{NullyEmptySB .Coalesce(NullSB,        NullSB       )}");
        NoNullRet(   EmptySB,      NullyEmptySB .Coalesce(NullSB,        NullyEmptySB ));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(NullSB,        NullySpaceSB ));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(NullSB,        NullyFilledSB));
        NoNullRet(   EmptySB,      NullyEmptySB .Coalesce(NullSB,        EmptySB      ));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(NullSB,        SpaceSB      ));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(NullSB,        FilledSB     ));
        NoNullRet(                 NullyEmptySB .Coalesce(NullyEmptySB,  NullSB       ));
        NoNullRet($"{EmptySB}", $"{NullyEmptySB .Coalesce(NullyEmptySB,  NullSB       )}");
        NoNullRet(   EmptySB,      NullyEmptySB .Coalesce(NullyEmptySB,  NullyEmptySB ));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(NullyEmptySB,  NullySpaceSB ));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(NullyEmptySB,  NullyFilledSB));
        NoNullRet(   EmptySB,      NullyEmptySB .Coalesce(NullyEmptySB,  EmptySB      ));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(NullyEmptySB,  SpaceSB      ));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(NullyEmptySB,  FilledSB     ));
        NoNullRet(                 NullyEmptySB .Coalesce(NullySpaceSB,  NullSB       ));
        NoNullRet($"{EmptySB}", $"{NullyEmptySB .Coalesce(NullySpaceSB,  NullSB       )}");
        NoNullRet(   EmptySB,      NullyEmptySB .Coalesce(NullySpaceSB,  NullyEmptySB ));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(NullySpaceSB,  NullySpaceSB ));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(NullySpaceSB,  NullyFilledSB));
        NoNullRet(   EmptySB,      NullyEmptySB .Coalesce(NullySpaceSB,  EmptySB      ));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(NullySpaceSB,  SpaceSB      ));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(NullySpaceSB,  FilledSB     ));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(NullyFilledSB, NullSB       ));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(NullyFilledSB, NullyEmptySB ));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(NullyFilledSB, NullySpaceSB ));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(NullyFilledSB, NullyFilledSB));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(NullyFilledSB, EmptySB      ));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(NullyFilledSB, SpaceSB      ));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(NullyFilledSB, FilledSB     ));
        NoNullRet(                 NullyEmptySB .Coalesce(EmptySB,       NullSB       ));
        NoNullRet($"{EmptySB}", $"{NullyEmptySB .Coalesce(EmptySB,       NullSB       )}");
        NoNullRet(   EmptySB,      NullyEmptySB .Coalesce(EmptySB,       NullyEmptySB ));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(EmptySB,       NullySpaceSB ));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(EmptySB,       NullyFilledSB));
        NoNullRet(   EmptySB,      NullyEmptySB .Coalesce(EmptySB,       EmptySB      ));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(EmptySB,       SpaceSB      ));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(EmptySB,       FilledSB     ));
        NoNullRet(                 NullyEmptySB .Coalesce(SpaceSB,       NullSB       ));
        NoNullRet($"{EmptySB}", $"{NullyEmptySB .Coalesce(SpaceSB,       NullSB       )}");
        NoNullRet(   EmptySB,      NullyEmptySB .Coalesce(SpaceSB,       NullyEmptySB ));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(SpaceSB,       NullySpaceSB ));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(SpaceSB,       NullyFilledSB));
        NoNullRet(   EmptySB,      NullyEmptySB .Coalesce(SpaceSB,       EmptySB      ));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(SpaceSB,       SpaceSB      ));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(SpaceSB,       FilledSB     ));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(FilledSB,      NullSB       ));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(FilledSB,      NullyEmptySB ));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(FilledSB,      NullySpaceSB ));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(FilledSB,      NullyFilledSB));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(FilledSB,      EmptySB      ));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(FilledSB,      SpaceSB      ));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(FilledSB,      FilledSB     ));
    }

    [TestMethod]
    public void Coalesce_3Args_SBs_Extensions_NoFlags_Batch3()
    {
        NoNullRet(                 NullySpaceSB .Coalesce(NullSB,        NullSB       ));
        NoNullRet($"{EmptySB}", $"{NullySpaceSB .Coalesce(NullSB,        NullSB       )}");
        NoNullRet(   EmptySB,      NullySpaceSB .Coalesce(NullSB,        NullyEmptySB ));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullSB,        NullySpaceSB ));
        NoNullRet(   FilledSB,     NullySpaceSB .Coalesce(NullSB,        NullyFilledSB));
        NoNullRet(   EmptySB,      NullySpaceSB .Coalesce(NullSB,        EmptySB      ));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullSB,        SpaceSB      ));
        NoNullRet(   FilledSB,     NullySpaceSB .Coalesce(NullSB,        FilledSB     ));
        NoNullRet(                 NullySpaceSB .Coalesce(NullyEmptySB,  NullSB       ));
        NoNullRet($"{EmptySB}", $"{NullySpaceSB. Coalesce(NullyEmptySB,  NullSB       )}");
        NoNullRet(   EmptySB,      NullySpaceSB .Coalesce(NullyEmptySB,  NullyEmptySB ));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullyEmptySB,  NullySpaceSB ));
        NoNullRet(   FilledSB,     NullySpaceSB .Coalesce(NullyEmptySB,  NullyFilledSB));
        NoNullRet(   EmptySB,      NullySpaceSB .Coalesce(NullyEmptySB,  EmptySB      ));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullyEmptySB,  SpaceSB      ));
        NoNullRet(   FilledSB,     NullySpaceSB .Coalesce(NullyEmptySB,  FilledSB     ));
        NoNullRet(                 NullySpaceSB .Coalesce(NullySpaceSB,  NullSB       ));
        NoNullRet($"{EmptySB}", $"{NullySpaceSB .Coalesce(NullySpaceSB,  NullSB       )}");
        NoNullRet(   EmptySB,      NullySpaceSB .Coalesce(NullySpaceSB,  NullyEmptySB ));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullySpaceSB,  NullySpaceSB ));
        NoNullRet(   FilledSB,     NullySpaceSB .Coalesce(NullySpaceSB,  NullyFilledSB));
        NoNullRet(   EmptySB,      NullySpaceSB .Coalesce(NullySpaceSB,  EmptySB      ));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullySpaceSB,  SpaceSB      ));
        NoNullRet(   FilledSB,     NullySpaceSB .Coalesce(NullySpaceSB,  FilledSB     ));
        NoNullRet(   FilledSB,     NullySpaceSB .Coalesce(NullyFilledSB, NullSB       ));
        NoNullRet(   FilledSB,     NullySpaceSB .Coalesce(NullyFilledSB, NullyEmptySB ));
        NoNullRet(   FilledSB,     NullySpaceSB .Coalesce(NullyFilledSB, NullySpaceSB ));
        NoNullRet(   FilledSB,     NullySpaceSB .Coalesce(NullyFilledSB, NullyFilledSB));
        NoNullRet(   FilledSB,     NullySpaceSB .Coalesce(NullyFilledSB, EmptySB      ));
        NoNullRet(   FilledSB,     NullySpaceSB .Coalesce(NullyFilledSB, SpaceSB      ));
        NoNullRet(   FilledSB,     NullySpaceSB .Coalesce(NullyFilledSB, FilledSB     ));
        NoNullRet(                 NullySpaceSB .Coalesce(EmptySB,       NullSB       ));
        NoNullRet($"{EmptySB}", $"{NullySpaceSB .Coalesce(EmptySB,       NullSB       )}");
        NoNullRet(   EmptySB,      NullySpaceSB .Coalesce(EmptySB,       NullyEmptySB ));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(EmptySB,       NullySpaceSB ));
        NoNullRet(   FilledSB,     NullySpaceSB .Coalesce(EmptySB,       NullyFilledSB));
        NoNullRet(   EmptySB,      NullySpaceSB .Coalesce(EmptySB,       EmptySB      ));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(EmptySB,       SpaceSB      ));
        NoNullRet(   FilledSB,     NullySpaceSB .Coalesce(EmptySB,       FilledSB     ));
        NoNullRet(                 NullySpaceSB .Coalesce(SpaceSB,       NullSB       ));
        NoNullRet($"{EmptySB}", $"{NullySpaceSB .Coalesce(SpaceSB,       NullSB       )}");
        NoNullRet(   EmptySB,      NullySpaceSB .Coalesce(SpaceSB,       NullyEmptySB ));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(SpaceSB,       NullySpaceSB ));
        NoNullRet(   FilledSB,     NullySpaceSB .Coalesce(SpaceSB,       NullyFilledSB));
        NoNullRet(   EmptySB,      NullySpaceSB .Coalesce(SpaceSB,       EmptySB      ));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(SpaceSB,       SpaceSB      ));
        NoNullRet(   FilledSB,     NullySpaceSB .Coalesce(SpaceSB,       FilledSB     ));
        NoNullRet(   FilledSB,     NullySpaceSB .Coalesce(FilledSB,      NullSB       ));
        NoNullRet(   FilledSB,     NullySpaceSB .Coalesce(FilledSB,      NullyEmptySB ));
        NoNullRet(   FilledSB,     NullySpaceSB .Coalesce(FilledSB,      NullySpaceSB ));
        NoNullRet(   FilledSB,     NullySpaceSB .Coalesce(FilledSB,      NullyFilledSB));
        NoNullRet(   FilledSB,     NullySpaceSB .Coalesce(FilledSB,      EmptySB      ));
        NoNullRet(   FilledSB,     NullySpaceSB .Coalesce(FilledSB,      SpaceSB      ));
        NoNullRet(   FilledSB,     NullySpaceSB .Coalesce(FilledSB,      FilledSB     ));
    }

    [TestMethod]
    public void Coalesce_3Args_SBs_Extensions_NoFlags_Batch4()
    {
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullSB,        NullSB       ));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullSB,        NullyEmptySB ));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullSB,        NullySpaceSB ));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullSB,        NullyFilledSB));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullSB,        EmptySB      ));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullSB,        SpaceSB      ));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullSB,        FilledSB     ));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullyEmptySB,  NullSB       ));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullyEmptySB,  NullyEmptySB ));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullyEmptySB,  NullySpaceSB ));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullyEmptySB,  NullyFilledSB));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullyEmptySB,  EmptySB      ));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullyEmptySB,  SpaceSB      ));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullyEmptySB,  FilledSB     ));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullySpaceSB,  NullSB       ));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullySpaceSB,  NullyEmptySB ));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullySpaceSB,  NullySpaceSB ));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullySpaceSB,  NullyFilledSB));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullySpaceSB,  EmptySB      ));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullySpaceSB,  SpaceSB      ));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullySpaceSB,  FilledSB     ));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullyFilledSB, NullSB       ));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullyFilledSB, NullyEmptySB ));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullyFilledSB, NullySpaceSB ));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullyFilledSB, NullyFilledSB));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullyFilledSB, EmptySB      ));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullyFilledSB, SpaceSB      ));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullyFilledSB, FilledSB     ));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(EmptySB,       NullSB       ));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(EmptySB,       NullyEmptySB ));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(EmptySB,       NullySpaceSB ));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(EmptySB,       NullyFilledSB));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(EmptySB,       EmptySB      ));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(EmptySB,       SpaceSB      ));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(EmptySB,       FilledSB     ));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(SpaceSB,       NullSB       ));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(SpaceSB,       NullyEmptySB ));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(SpaceSB,       NullySpaceSB ));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(SpaceSB,       NullyFilledSB));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(SpaceSB,       EmptySB      ));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(SpaceSB,       SpaceSB      ));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(SpaceSB,       FilledSB     ));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(FilledSB,      NullSB       ));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(FilledSB,      NullyEmptySB ));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(FilledSB,      NullySpaceSB ));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(FilledSB,      NullyFilledSB));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(FilledSB,      EmptySB      ));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(FilledSB,      SpaceSB      ));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(FilledSB,      FilledSB     ));
    }

    [TestMethod]
    public void Coalesce_3Args_SBs_Extensions_NoFlags_Batch5()
    {
        NoNullRet(                 EmptySB      .Coalesce(NullSB,        NullSB       ));
        NoNullRet($"{EmptySB}", $"{EmptySB      .Coalesce(NullSB,        NullSB       )}");
        NoNullRet(   EmptySB,      EmptySB      .Coalesce(NullSB,        NullyEmptySB ));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(NullSB,        NullySpaceSB ));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(NullSB,        NullyFilledSB));
        NoNullRet(   EmptySB,      EmptySB      .Coalesce(NullSB,        EmptySB      ));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(NullSB,        SpaceSB      ));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(NullSB,        FilledSB     ));
        NoNullRet(                 EmptySB      .Coalesce(NullyEmptySB,  NullSB       ));
        NoNullRet($"{EmptySB}", $"{EmptySB      .Coalesce(NullyEmptySB,  NullSB       )}");
        NoNullRet(   EmptySB,      EmptySB      .Coalesce(NullyEmptySB,  NullyEmptySB ));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(NullyEmptySB,  NullySpaceSB ));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(NullyEmptySB,  NullyFilledSB));
        NoNullRet(   EmptySB,      EmptySB      .Coalesce(NullyEmptySB,  EmptySB      ));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(NullyEmptySB,  SpaceSB      ));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(NullyEmptySB,  FilledSB     ));
        NoNullRet(                 EmptySB      .Coalesce(NullySpaceSB,  NullSB       ));
        NoNullRet($"{EmptySB}", $"{EmptySB      .Coalesce(NullySpaceSB,  NullSB       )}");
        NoNullRet(   EmptySB,      EmptySB      .Coalesce(NullySpaceSB,  NullyEmptySB ));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(NullySpaceSB,  NullySpaceSB ));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(NullySpaceSB,  NullyFilledSB));
        NoNullRet(   EmptySB,      EmptySB      .Coalesce(NullySpaceSB,  EmptySB      ));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(NullySpaceSB,  SpaceSB      ));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(NullySpaceSB,  FilledSB     ));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(NullyFilledSB, NullSB       ));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(NullyFilledSB, NullyEmptySB ));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(NullyFilledSB, NullySpaceSB ));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(NullyFilledSB, NullyFilledSB));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(NullyFilledSB, EmptySB      ));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(NullyFilledSB, SpaceSB      ));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(NullyFilledSB, FilledSB     ));
        NoNullRet(                 EmptySB      .Coalesce(EmptySB,       NullSB       ));
        NoNullRet($"{EmptySB}", $"{EmptySB      .Coalesce(EmptySB,       NullSB       )}");
        NoNullRet(   EmptySB,      EmptySB      .Coalesce(EmptySB,       NullyEmptySB ));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(EmptySB,       NullySpaceSB ));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(EmptySB,       NullyFilledSB));
        NoNullRet(   EmptySB,      EmptySB      .Coalesce(EmptySB,       EmptySB      ));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(EmptySB,       SpaceSB      ));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(EmptySB,       FilledSB     ));
        NoNullRet(                 EmptySB      .Coalesce(SpaceSB,       NullSB       ));
        NoNullRet($"{EmptySB}", $"{EmptySB      .Coalesce(SpaceSB,       NullSB       )}");
        NoNullRet(   EmptySB,      EmptySB      .Coalesce(SpaceSB,       NullyEmptySB ));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(SpaceSB,       NullySpaceSB ));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(SpaceSB,       NullyFilledSB));
        NoNullRet(   EmptySB,      EmptySB      .Coalesce(SpaceSB,       EmptySB      ));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(SpaceSB,       SpaceSB      ));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(SpaceSB,       FilledSB     ));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(FilledSB,      NullSB       ));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(FilledSB,      NullyEmptySB ));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(FilledSB,      NullySpaceSB ));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(FilledSB,      NullyFilledSB));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(FilledSB,      EmptySB      ));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(FilledSB,      SpaceSB      ));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(FilledSB,      FilledSB     ));
    }

    [TestMethod]
    public void Coalesce_3Args_SBs_Extensions_NoFlags_Batch6()
    {
        NoNullRet(                 SpaceSB      .Coalesce(NullSB,        NullSB       ));
        NoNullRet($"{EmptySB}", $"{SpaceSB      .Coalesce(NullSB,        NullSB       )}");
        NoNullRet(   EmptySB,      SpaceSB      .Coalesce(NullSB,        NullyEmptySB ));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullSB,        NullySpaceSB ));
        NoNullRet(   FilledSB,     SpaceSB      .Coalesce(NullSB,        NullyFilledSB));
        NoNullRet(   EmptySB,      SpaceSB      .Coalesce(NullSB,        EmptySB      ));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullSB,        SpaceSB      ));
        NoNullRet(   FilledSB,     SpaceSB      .Coalesce(NullSB,        FilledSB     ));
        NoNullRet(                 SpaceSB      .Coalesce(NullyEmptySB,  NullSB       ));
        NoNullRet($"{EmptySB}", $"{SpaceSB      .Coalesce(NullyEmptySB,  NullSB       )}");
        NoNullRet(   EmptySB,      SpaceSB      .Coalesce(NullyEmptySB,  NullyEmptySB ));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullyEmptySB,  NullySpaceSB ));
        NoNullRet(   FilledSB,     SpaceSB      .Coalesce(NullyEmptySB,  NullyFilledSB));
        NoNullRet(   EmptySB,      SpaceSB      .Coalesce(NullyEmptySB,  EmptySB      ));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullyEmptySB,  SpaceSB      ));
        NoNullRet(   FilledSB,     SpaceSB      .Coalesce(NullyEmptySB,  FilledSB     ));
        NoNullRet(                 SpaceSB      .Coalesce(NullySpaceSB,  NullSB       ));
        NoNullRet($"{EmptySB}", $"{SpaceSB      .Coalesce(NullySpaceSB,  NullSB       )}");
        NoNullRet(   EmptySB,      SpaceSB      .Coalesce(NullySpaceSB,  NullyEmptySB ));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullySpaceSB,  NullySpaceSB ));
        NoNullRet(   FilledSB,     SpaceSB      .Coalesce(NullySpaceSB,  NullyFilledSB));
        NoNullRet(   EmptySB,      SpaceSB      .Coalesce(NullySpaceSB,  EmptySB      ));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullySpaceSB,  SpaceSB      ));
        NoNullRet(   FilledSB,     SpaceSB      .Coalesce(NullySpaceSB,  FilledSB     ));
        NoNullRet(   FilledSB,     SpaceSB      .Coalesce(NullyFilledSB, NullSB       ));
        NoNullRet(   FilledSB,     SpaceSB      .Coalesce(NullyFilledSB, NullyEmptySB ));
        NoNullRet(   FilledSB,     SpaceSB      .Coalesce(NullyFilledSB, NullySpaceSB ));
        NoNullRet(   FilledSB,     SpaceSB      .Coalesce(NullyFilledSB, NullyFilledSB));
        NoNullRet(   FilledSB,     SpaceSB      .Coalesce(NullyFilledSB, EmptySB      ));
        NoNullRet(   FilledSB,     SpaceSB      .Coalesce(NullyFilledSB, SpaceSB      ));
        NoNullRet(   FilledSB,     SpaceSB      .Coalesce(NullyFilledSB, FilledSB     ));
        NoNullRet(                 SpaceSB      .Coalesce(EmptySB,       NullSB       ));
        NoNullRet($"{EmptySB}", $"{SpaceSB      .Coalesce(EmptySB,       NullSB       )}");
        NoNullRet(   EmptySB,      SpaceSB      .Coalesce(EmptySB,       NullyEmptySB ));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(EmptySB,       NullySpaceSB ));
        NoNullRet(   FilledSB,     SpaceSB      .Coalesce(EmptySB,       NullyFilledSB));
        NoNullRet(   EmptySB,      SpaceSB      .Coalesce(EmptySB,       EmptySB      ));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(EmptySB,       SpaceSB      ));
        NoNullRet(   FilledSB,     SpaceSB      .Coalesce(EmptySB,       FilledSB     ));
        NoNullRet(                 SpaceSB      .Coalesce(SpaceSB,       NullSB       ));
        NoNullRet($"{EmptySB}", $"{SpaceSB      .Coalesce(SpaceSB,       NullSB       )}");
        NoNullRet(   EmptySB,      SpaceSB      .Coalesce(SpaceSB,       NullyEmptySB ));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(SpaceSB,       NullySpaceSB ));
        NoNullRet(   FilledSB,     SpaceSB      .Coalesce(SpaceSB,       NullyFilledSB));
        NoNullRet(   EmptySB,      SpaceSB      .Coalesce(SpaceSB,       EmptySB      ));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(SpaceSB,       SpaceSB      ));
        NoNullRet(   FilledSB,     SpaceSB      .Coalesce(SpaceSB,       FilledSB     ));
        NoNullRet(   FilledSB,     SpaceSB      .Coalesce(FilledSB,      NullSB       ));
        NoNullRet(   FilledSB,     SpaceSB      .Coalesce(FilledSB,      NullyEmptySB ));
        NoNullRet(   FilledSB,     SpaceSB      .Coalesce(FilledSB,      NullySpaceSB ));
        NoNullRet(   FilledSB,     SpaceSB      .Coalesce(FilledSB,      NullyFilledSB));
        NoNullRet(   FilledSB,     SpaceSB      .Coalesce(FilledSB,      EmptySB      ));
        NoNullRet(   FilledSB,     SpaceSB      .Coalesce(FilledSB,      SpaceSB      ));
        NoNullRet(   FilledSB,     SpaceSB      .Coalesce(FilledSB,      FilledSB     ));
    }

    [TestMethod]
    public void Coalesce_3Args_SBs_Extensions_NoFlags_Batch7()
    {
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullSB,        NullSB       ));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullSB,        NullyEmptySB ));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullSB,        NullySpaceSB ));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullSB,        NullyFilledSB));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullSB,        EmptySB      ));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullSB,        SpaceSB      ));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullSB,        FilledSB     ));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullyEmptySB,  NullSB       ));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullyEmptySB,  NullyEmptySB ));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullyEmptySB,  NullySpaceSB ));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullyEmptySB,  NullyFilledSB));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullyEmptySB,  EmptySB      ));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullyEmptySB,  SpaceSB      ));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullyEmptySB,  FilledSB     ));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullySpaceSB,  NullSB       ));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullySpaceSB,  NullyEmptySB ));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullySpaceSB,  NullySpaceSB ));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullySpaceSB,  NullyFilledSB));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullySpaceSB,  EmptySB      ));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullySpaceSB,  SpaceSB      ));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullySpaceSB,  FilledSB     ));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullyFilledSB, NullSB       ));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullyFilledSB, NullyEmptySB ));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullyFilledSB, NullySpaceSB ));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullyFilledSB, NullyFilledSB));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullyFilledSB, EmptySB      ));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullyFilledSB, SpaceSB      ));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullyFilledSB, FilledSB     ));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(EmptySB,       NullSB       ));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(EmptySB,       NullyEmptySB ));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(EmptySB,       NullySpaceSB ));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(EmptySB,       NullyFilledSB));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(EmptySB,       EmptySB      ));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(EmptySB,       SpaceSB      ));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(EmptySB,       FilledSB     ));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(SpaceSB,       NullSB       ));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(SpaceSB,       NullyEmptySB ));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(SpaceSB,       NullySpaceSB ));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(SpaceSB,       NullyFilledSB));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(SpaceSB,       EmptySB      ));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(SpaceSB,       SpaceSB      ));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(SpaceSB,       FilledSB     ));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(FilledSB,      NullSB       ));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(FilledSB,      NullyEmptySB ));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(FilledSB,      NullySpaceSB ));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(FilledSB,      NullyFilledSB));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(FilledSB,      EmptySB      ));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(FilledSB,      SpaceSB      ));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(FilledSB,      FilledSB     ));
    }
}