namespace JJ.Framework.Existence.Core.Tests;

[TestClass]
public class Coalesce_3Args_BoolToText_StaticZeroMattersFlagsInFront : TestBase
{
    [TestMethod]
    public void Coalesce_3Args_BoolToText_StaticZeroMattersFlagsInFront_Batch1()
    {
        NoNullRet("",      Coalesce(                    NullBool,   NullyFalse, NullText         ));
        NoNullRet("",      Coalesce(zeroMatters: false, NullBool,   NullyFalse, NullText         ));
        NoNullRet("",      Coalesce(             false, NullBool,   NullyFalse, NullText         ));
        NoNullRet("False", Coalesce(zeroMatters,        NullBool,   NullyFalse, NullText         ));
        NoNullRet("False", Coalesce(zeroMatters: true,  NullBool,   NullyFalse, NullText         ));
        NoNullRet("False", Coalesce(             true,  NullBool,   NullyFalse, NullText         ));
        NoNullRet("",      Coalesce(                    NullBool,   NullyFalse, Empty            ));
        NoNullRet("",      Coalesce(zeroMatters: false, NullBool,   NullyFalse, Empty            ));
        NoNullRet("",      Coalesce(             false, NullBool,   NullyFalse, Empty            ));
        NoNullRet("False", Coalesce(zeroMatters,        NullBool,   NullyFalse, Empty            ));
        NoNullRet("False", Coalesce(zeroMatters: true,  NullBool,   NullyFalse, Empty            ));
        NoNullRet("False", Coalesce(             true,  NullBool,   NullyFalse, Empty            ));
        NoNullRet(" ",     Coalesce(                    NullBool,   NullyFalse, Space            ));
        NoNullRet(" ",     Coalesce(zeroMatters: false, NullBool,   NullyFalse, Space            ));
        NoNullRet(" ",     Coalesce(             false, NullBool,   NullyFalse, Space            ));
        NoNullRet("False", Coalesce(zeroMatters,        NullBool,   NullyFalse, Space            ));
        NoNullRet("False", Coalesce(zeroMatters: true,  NullBool,   NullyFalse, Space            ));
        NoNullRet("False", Coalesce(             true,  NullBool,   NullyFalse, Space            ));
        NoNullRet(Text,    Coalesce(                    NullBool,   NullyFalse, Text             ));
        NoNullRet(Text,    Coalesce(zeroMatters: false, NullBool,   NullyFalse, Text             ));
        NoNullRet(Text,    Coalesce(             false, NullBool,   NullyFalse, Text             ));
        NoNullRet("False", Coalesce(zeroMatters,        NullBool,   NullyFalse, Text             ));
        NoNullRet("False", Coalesce(zeroMatters: true,  NullBool,   NullyFalse, Text             ));
        NoNullRet("False", Coalesce(             true,  NullBool,   NullyFalse, Text             ));
        NoNullRet("",      Coalesce(                    NullBool,   NullyFalse, NullyEmpty       ));
        NoNullRet("",      Coalesce(zeroMatters: false, NullBool,   NullyFalse, NullyEmpty       ));
        NoNullRet("",      Coalesce(             false, NullBool,   NullyFalse, NullyEmpty       ));
        NoNullRet("False", Coalesce(zeroMatters,        NullBool,   NullyFalse, NullyEmpty       ));
        NoNullRet("False", Coalesce(zeroMatters: true,  NullBool,   NullyFalse, NullyEmpty       ));
        NoNullRet("False", Coalesce(             true,  NullBool,   NullyFalse, NullyEmpty       ));
        NoNullRet(" ",     Coalesce(                    NullBool,   NullyFalse, NullySpace       ));
        NoNullRet(" ",     Coalesce(zeroMatters: false, NullBool,   NullyFalse, NullySpace       ));
        NoNullRet(" ",     Coalesce(             false, NullBool,   NullyFalse, NullySpace       ));
        NoNullRet("False", Coalesce(zeroMatters,        NullBool,   NullyFalse, NullySpace       ));
        NoNullRet("False", Coalesce(zeroMatters: true,  NullBool,   NullyFalse, NullySpace       ));
        NoNullRet("False", Coalesce(             true,  NullBool,   NullyFalse, NullySpace       ));
        NoNullRet(Text,    Coalesce(                    NullBool,   NullyFalse, NullyFilledText  ));
        NoNullRet(Text,    Coalesce(zeroMatters: false, NullBool,   NullyFalse, NullyFilledText  ));
        NoNullRet(Text,    Coalesce(             false, NullBool,   NullyFalse, NullyFilledText  ));
        NoNullRet("False", Coalesce(zeroMatters,        NullBool,   NullyFalse, NullyFilledText  ));
        NoNullRet("False", Coalesce(zeroMatters: true,  NullBool,   NullyFalse, NullyFilledText  ));
        NoNullRet("False", Coalesce(             true,  NullBool,   NullyFalse, NullyFilledText  ));
        NoNullRet("True",  Coalesce(                    NullBool,   NullyTrue,  NullText         ));
        NoNullRet("True",  Coalesce(zeroMatters: false, NullBool,   NullyTrue,  NullText         ));
        NoNullRet("True",  Coalesce(             false, NullBool,   NullyTrue,  NullText         ));
        NoNullRet("True",  Coalesce(zeroMatters,        NullBool,   NullyTrue,  NullText         ));
        NoNullRet("True",  Coalesce(zeroMatters: true,  NullBool,   NullyTrue,  NullText         ));
        NoNullRet("True",  Coalesce(             true,  NullBool,   NullyTrue,  NullText         ));
        NoNullRet("True",  Coalesce(                    NullBool,   NullyTrue,  Empty            ));
        NoNullRet("True",  Coalesce(zeroMatters: false, NullBool,   NullyTrue,  Empty            ));
        NoNullRet("True",  Coalesce(             false, NullBool,   NullyTrue,  Empty            ));
        NoNullRet("True",  Coalesce(zeroMatters,        NullBool,   NullyTrue,  Empty            ));
        NoNullRet("True",  Coalesce(zeroMatters: true,  NullBool,   NullyTrue,  Empty            ));
        NoNullRet("True",  Coalesce(             true,  NullBool,   NullyTrue,  Empty            ));
        NoNullRet("True",  Coalesce(                    NullBool,   NullyTrue,  Space            ));
        NoNullRet("True",  Coalesce(zeroMatters: false, NullBool,   NullyTrue,  Space            ));
        NoNullRet("True",  Coalesce(             false, NullBool,   NullyTrue,  Space            ));
        NoNullRet("True",  Coalesce(zeroMatters,        NullBool,   NullyTrue,  Space            ));
        NoNullRet("True",  Coalesce(zeroMatters: true,  NullBool,   NullyTrue,  Space            ));
        NoNullRet("True",  Coalesce(             true,  NullBool,   NullyTrue,  Space            ));
        NoNullRet("True",  Coalesce(                    NullBool,   NullyTrue,  Text             ));
        NoNullRet("True",  Coalesce(zeroMatters: false, NullBool,   NullyTrue,  Text             ));
        NoNullRet("True",  Coalesce(             false, NullBool,   NullyTrue,  Text             ));
        NoNullRet("True",  Coalesce(zeroMatters,        NullBool,   NullyTrue,  Text             ));
        NoNullRet("True",  Coalesce(zeroMatters: true,  NullBool,   NullyTrue,  Text             ));
        NoNullRet("True",  Coalesce(             true,  NullBool,   NullyTrue,  Text             ));
        NoNullRet("True",  Coalesce(                    NullBool,   NullyTrue,  NullyEmpty       ));
        NoNullRet("True",  Coalesce(zeroMatters: false, NullBool,   NullyTrue,  NullyEmpty       ));
        NoNullRet("True",  Coalesce(             false, NullBool,   NullyTrue,  NullyEmpty       ));
        NoNullRet("True",  Coalesce(zeroMatters,        NullBool,   NullyTrue,  NullyEmpty       ));
        NoNullRet("True",  Coalesce(zeroMatters: true,  NullBool,   NullyTrue,  NullyEmpty       ));
        NoNullRet("True",  Coalesce(             true,  NullBool,   NullyTrue,  NullyEmpty       ));
        NoNullRet("True",  Coalesce(                    NullBool,   NullyTrue,  NullySpace       ));
        NoNullRet("True",  Coalesce(zeroMatters: false, NullBool,   NullyTrue,  NullySpace       ));
        NoNullRet("True",  Coalesce(             false, NullBool,   NullyTrue,  NullySpace       ));
        NoNullRet("True",  Coalesce(zeroMatters,        NullBool,   NullyTrue,  NullySpace       ));
        NoNullRet("True",  Coalesce(zeroMatters: true,  NullBool,   NullyTrue,  NullySpace       ));
        NoNullRet("True",  Coalesce(             true,  NullBool,   NullyTrue,  NullySpace       ));
        NoNullRet("True",  Coalesce(                    NullBool,   NullyTrue,  NullyFilledText  ));
        NoNullRet("True",  Coalesce(zeroMatters: false, NullBool,   NullyTrue,  NullyFilledText  ));
        NoNullRet("True",  Coalesce(             false, NullBool,   NullyTrue,  NullyFilledText  ));
        NoNullRet("True",  Coalesce(zeroMatters,        NullBool,   NullyTrue,  NullyFilledText  ));
        NoNullRet("True",  Coalesce(zeroMatters: true,  NullBool,   NullyTrue,  NullyFilledText  ));
        NoNullRet("True",  Coalesce(             true,  NullBool,   NullyTrue,  NullyFilledText  ));
        NoNullRet("",      Coalesce(                    NullBool,   false,      NullText         ));
        NoNullRet("",      Coalesce(zeroMatters: false, NullBool,   false,      NullText         ));
        NoNullRet("",      Coalesce(             false, NullBool,   false,      NullText         ));
        NoNullRet("False", Coalesce(zeroMatters,        NullBool,   false,      NullText         ));
        NoNullRet("False", Coalesce(zeroMatters: true,  NullBool,   false,      NullText         ));
        NoNullRet("False", Coalesce(             true,  NullBool,   false,      NullText         ));
        NoNullRet("",      Coalesce(                    NullBool,   false,      Empty            ));
        NoNullRet("",      Coalesce(zeroMatters: false, NullBool,   false,      Empty            ));
        NoNullRet("",      Coalesce(             false, NullBool,   false,      Empty            ));
        NoNullRet("False", Coalesce(zeroMatters,        NullBool,   false,      Empty            ));
        NoNullRet("False", Coalesce(zeroMatters: true,  NullBool,   false,      Empty            ));
        NoNullRet("False", Coalesce(             true,  NullBool,   false,      Empty            ));
        NoNullRet(" ",     Coalesce(                    NullBool,   false,      Space            ));
        NoNullRet(" ",     Coalesce(zeroMatters: false, NullBool,   false,      Space            ));
        NoNullRet(" ",     Coalesce(             false, NullBool,   false,      Space            ));
        NoNullRet("False", Coalesce(zeroMatters,        NullBool,   false,      Space            ));
        NoNullRet("False", Coalesce(zeroMatters: true,  NullBool,   false,      Space            ));
        NoNullRet("False", Coalesce(             true,  NullBool,   false,      Space            ));
        NoNullRet(Text,    Coalesce(                    NullBool,   false,      Text             ));
        NoNullRet(Text,    Coalesce(zeroMatters: false, NullBool,   false,      Text             ));
        NoNullRet(Text,    Coalesce(             false, NullBool,   false,      Text             ));
        NoNullRet("False", Coalesce(zeroMatters,        NullBool,   false,      Text             ));
        NoNullRet("False", Coalesce(zeroMatters: true,  NullBool,   false,      Text             ));
        NoNullRet("False", Coalesce(             true,  NullBool,   false,      Text             ));
        NoNullRet("",      Coalesce(                    NullBool,   false,      NullyEmpty       ));
        NoNullRet("",      Coalesce(zeroMatters: false, NullBool,   false,      NullyEmpty       ));
        NoNullRet("",      Coalesce(             false, NullBool,   false,      NullyEmpty       ));
        NoNullRet("False", Coalesce(zeroMatters,        NullBool,   false,      NullyEmpty       ));
        NoNullRet("False", Coalesce(zeroMatters: true,  NullBool,   false,      NullyEmpty       ));
        NoNullRet("False", Coalesce(             true,  NullBool,   false,      NullyEmpty       ));
        NoNullRet(" ",     Coalesce(                    NullBool,   false,      NullySpace       ));
        NoNullRet(" ",     Coalesce(zeroMatters: false, NullBool,   false,      NullySpace       ));
        NoNullRet(" ",     Coalesce(             false, NullBool,   false,      NullySpace       ));
        NoNullRet("False", Coalesce(zeroMatters,        NullBool,   false,      NullySpace       ));
        NoNullRet("False", Coalesce(zeroMatters: true,  NullBool,   false,      NullySpace       ));
        NoNullRet("False", Coalesce(             true,  NullBool,   false,      NullySpace       ));
        NoNullRet(Text,    Coalesce(                    NullBool,   false,      NullyFilledText  ));
        NoNullRet(Text,    Coalesce(zeroMatters: false, NullBool,   false,      NullyFilledText  ));
        NoNullRet(Text,    Coalesce(             false, NullBool,   false,      NullyFilledText  ));
        NoNullRet("False", Coalesce(zeroMatters,        NullBool,   false,      NullyFilledText  ));
        NoNullRet("False", Coalesce(zeroMatters: true,  NullBool,   false,      NullyFilledText  ));
        NoNullRet("False", Coalesce(             true,  NullBool,   false,      NullyFilledText  ));
        NoNullRet("True",  Coalesce(                    NullBool,   true,       NullText         ));
        NoNullRet("True",  Coalesce(zeroMatters: false, NullBool,   true,       NullText         ));
        NoNullRet("True",  Coalesce(             false, NullBool,   true,       NullText         ));
        NoNullRet("True",  Coalesce(zeroMatters,        NullBool,   true,       NullText         ));
        NoNullRet("True",  Coalesce(zeroMatters: true,  NullBool,   true,       NullText         ));
        NoNullRet("True",  Coalesce(             true,  NullBool,   true,       NullText         ));
        NoNullRet("True",  Coalesce(                    NullBool,   true,       Empty            ));
        NoNullRet("True",  Coalesce(zeroMatters: false, NullBool,   true,       Empty            ));
        NoNullRet("True",  Coalesce(             false, NullBool,   true,       Empty            ));
        NoNullRet("True",  Coalesce(zeroMatters,        NullBool,   true,       Empty            ));
        NoNullRet("True",  Coalesce(zeroMatters: true,  NullBool,   true,       Empty            ));
        NoNullRet("True",  Coalesce(             true,  NullBool,   true,       Empty            ));
        NoNullRet("True",  Coalesce(                    NullBool,   true,       Space            ));
        NoNullRet("True",  Coalesce(zeroMatters: false, NullBool,   true,       Space            ));
        NoNullRet("True",  Coalesce(             false, NullBool,   true,       Space            ));
        NoNullRet("True",  Coalesce(zeroMatters,        NullBool,   true,       Space            ));
        NoNullRet("True",  Coalesce(zeroMatters: true,  NullBool,   true,       Space            ));
        NoNullRet("True",  Coalesce(             true,  NullBool,   true,       Space            ));
        NoNullRet("True",  Coalesce(                    NullBool,   true,       Text             ));
        NoNullRet("True",  Coalesce(zeroMatters: false, NullBool,   true,       Text             ));
        NoNullRet("True",  Coalesce(             false, NullBool,   true,       Text             ));
        NoNullRet("True",  Coalesce(zeroMatters,        NullBool,   true,       Text             ));
        NoNullRet("True",  Coalesce(zeroMatters: true,  NullBool,   true,       Text             ));
        NoNullRet("True",  Coalesce(             true,  NullBool,   true,       Text             ));
        NoNullRet("True",  Coalesce(                    NullBool,   true,       NullyEmpty       ));
        NoNullRet("True",  Coalesce(zeroMatters: false, NullBool,   true,       NullyEmpty       ));
        NoNullRet("True",  Coalesce(             false, NullBool,   true,       NullyEmpty       ));
        NoNullRet("True",  Coalesce(zeroMatters,        NullBool,   true,       NullyEmpty       ));
        NoNullRet("True",  Coalesce(zeroMatters: true,  NullBool,   true,       NullyEmpty       ));
        NoNullRet("True",  Coalesce(             true,  NullBool,   true,       NullyEmpty       ));
        NoNullRet("True",  Coalesce(                    NullBool,   true,       NullySpace       ));
        NoNullRet("True",  Coalesce(zeroMatters: false, NullBool,   true,       NullySpace       ));
        NoNullRet("True",  Coalesce(             false, NullBool,   true,       NullySpace       ));
        NoNullRet("True",  Coalesce(zeroMatters,        NullBool,   true,       NullySpace       ));
        NoNullRet("True",  Coalesce(zeroMatters: true,  NullBool,   true,       NullySpace       ));
        NoNullRet("True",  Coalesce(             true,  NullBool,   true,       NullySpace       ));
        NoNullRet("True",  Coalesce(                    NullBool,   true,       NullyFilledText  ));
        NoNullRet("True",  Coalesce(zeroMatters: false, NullBool,   true,       NullyFilledText  ));
        NoNullRet("True",  Coalesce(             false, NullBool,   true,       NullyFilledText  ));
        NoNullRet("True",  Coalesce(zeroMatters,        NullBool,   true,       NullyFilledText  ));
        NoNullRet("True",  Coalesce(zeroMatters: true,  NullBool,   true,       NullyFilledText  ));
        NoNullRet("True",  Coalesce(             true,  NullBool,   true,       NullyFilledText  ));
    }

    [TestMethod]
    public void Coalesce_3Args_BoolToText_StaticZeroMattersFlagsInFront_Batch2()
    {
        NoNullRet("",      Coalesce(                    NullyFalse, NullBool,   NullText         ));
        NoNullRet("",      Coalesce(zeroMatters: false, NullyFalse, NullBool,   NullText         ));
        NoNullRet("",      Coalesce(             false, NullyFalse, NullBool,   NullText         ));
        NoNullRet("False", Coalesce(zeroMatters,        NullyFalse, NullBool,   NullText         ));
        NoNullRet("False", Coalesce(zeroMatters: true,  NullyFalse, NullBool,   NullText         ));
        NoNullRet("False", Coalesce(             true,  NullyFalse, NullBool,   NullText         ));
        NoNullRet("",      Coalesce(                    NullyFalse, NullBool,   Empty            ));
        NoNullRet("",      Coalesce(zeroMatters: false, NullyFalse, NullBool,   Empty            ));
        NoNullRet("",      Coalesce(             false, NullyFalse, NullBool,   Empty            ));
        NoNullRet("False", Coalesce(zeroMatters,        NullyFalse, NullBool,   Empty            ));
        NoNullRet("False", Coalesce(zeroMatters: true,  NullyFalse, NullBool,   Empty            ));
        NoNullRet("False", Coalesce(             true,  NullyFalse, NullBool,   Empty            ));
        NoNullRet(" ",     Coalesce(                    NullyFalse, NullBool,   Space            ));
        NoNullRet(" ",     Coalesce(zeroMatters: false, NullyFalse, NullBool,   Space            ));
        NoNullRet(" ",     Coalesce(             false, NullyFalse, NullBool,   Space            ));
        NoNullRet("False", Coalesce(zeroMatters,        NullyFalse, NullBool,   Space            ));
        NoNullRet("False", Coalesce(zeroMatters: true,  NullyFalse, NullBool,   Space            ));
        NoNullRet("False", Coalesce(             true,  NullyFalse, NullBool,   Space            ));
        NoNullRet(Text,    Coalesce(                    NullyFalse, NullBool,   Text             ));
        NoNullRet(Text,    Coalesce(zeroMatters: false, NullyFalse, NullBool,   Text             ));
        NoNullRet(Text,    Coalesce(             false, NullyFalse, NullBool,   Text             ));
        NoNullRet("False", Coalesce(zeroMatters,        NullyFalse, NullBool,   Text             ));
        NoNullRet("False", Coalesce(zeroMatters: true,  NullyFalse, NullBool,   Text             ));
        NoNullRet("False", Coalesce(             true,  NullyFalse, NullBool,   Text             ));
        NoNullRet("",      Coalesce(                    NullyFalse, NullBool,   NullyEmpty       ));
        NoNullRet("",      Coalesce(zeroMatters: false, NullyFalse, NullBool,   NullyEmpty       ));
        NoNullRet("",      Coalesce(             false, NullyFalse, NullBool,   NullyEmpty       ));
        NoNullRet("False", Coalesce(zeroMatters,        NullyFalse, NullBool,   NullyEmpty       ));
        NoNullRet("False", Coalesce(zeroMatters: true,  NullyFalse, NullBool,   NullyEmpty       ));
        NoNullRet("False", Coalesce(             true,  NullyFalse, NullBool,   NullyEmpty       ));
        NoNullRet(" ",     Coalesce(                    NullyFalse, NullBool,   NullySpace       ));
        NoNullRet(" ",     Coalesce(zeroMatters: false, NullyFalse, NullBool,   NullySpace       ));
        NoNullRet(" ",     Coalesce(             false, NullyFalse, NullBool,   NullySpace       ));
        NoNullRet("False", Coalesce(zeroMatters,        NullyFalse, NullBool,   NullySpace       ));
        NoNullRet("False", Coalesce(zeroMatters: true,  NullyFalse, NullBool,   NullySpace       ));
        NoNullRet("False", Coalesce(             true,  NullyFalse, NullBool,   NullySpace       ));
        NoNullRet(Text,    Coalesce(                    NullyFalse, NullBool,   NullyFilledText  ));
        NoNullRet(Text,    Coalesce(zeroMatters: false, NullyFalse, NullBool,   NullyFilledText  ));
        NoNullRet(Text,    Coalesce(             false, NullyFalse, NullBool,   NullyFilledText  ));
        NoNullRet("False", Coalesce(zeroMatters,        NullyFalse, NullBool,   NullyFilledText  ));
        NoNullRet("False", Coalesce(zeroMatters: true,  NullyFalse, NullBool,   NullyFilledText  ));
        NoNullRet("False", Coalesce(             true,  NullyFalse, NullBool,   NullyFilledText  ));
        NoNullRet("True",  Coalesce(                    NullyFalse, NullyTrue,  NullText         ));
        NoNullRet("True",  Coalesce(zeroMatters: false, NullyFalse, NullyTrue,  NullText         ));
        NoNullRet("True",  Coalesce(             false, NullyFalse, NullyTrue,  NullText         ));
        NoNullRet("False", Coalesce(zeroMatters,        NullyFalse, NullyTrue,  NullText         ));
        NoNullRet("False", Coalesce(zeroMatters: true,  NullyFalse, NullyTrue,  NullText         ));
        NoNullRet("False", Coalesce(             true,  NullyFalse, NullyTrue,  NullText         ));
        NoNullRet("True",  Coalesce(                    NullyFalse, NullyTrue,  Empty            ));
        NoNullRet("True",  Coalesce(zeroMatters: false, NullyFalse, NullyTrue,  Empty            ));
        NoNullRet("True",  Coalesce(             false, NullyFalse, NullyTrue,  Empty            ));
        NoNullRet("False", Coalesce(zeroMatters,        NullyFalse, NullyTrue,  Empty            ));
        NoNullRet("False", Coalesce(zeroMatters: true,  NullyFalse, NullyTrue,  Empty            ));
        NoNullRet("False", Coalesce(             true,  NullyFalse, NullyTrue,  Empty            ));
        NoNullRet("True",  Coalesce(                    NullyFalse, NullyTrue,  Space            ));
        NoNullRet("True",  Coalesce(zeroMatters: false, NullyFalse, NullyTrue,  Space            ));
        NoNullRet("True",  Coalesce(             false, NullyFalse, NullyTrue,  Space            ));
        NoNullRet("False", Coalesce(zeroMatters,        NullyFalse, NullyTrue,  Space            ));
        NoNullRet("False", Coalesce(zeroMatters: true,  NullyFalse, NullyTrue,  Space            ));
        NoNullRet("False", Coalesce(             true,  NullyFalse, NullyTrue,  Space            ));
        NoNullRet("True",  Coalesce(                    NullyFalse, NullyTrue,  Text             ));
        NoNullRet("True",  Coalesce(zeroMatters: false, NullyFalse, NullyTrue,  Text             ));
        NoNullRet("True",  Coalesce(             false, NullyFalse, NullyTrue,  Text             ));
        NoNullRet("False", Coalesce(zeroMatters,        NullyFalse, NullyTrue,  Text             ));
        NoNullRet("False", Coalesce(zeroMatters: true,  NullyFalse, NullyTrue,  Text             ));
        NoNullRet("False", Coalesce(             true,  NullyFalse, NullyTrue,  Text             ));
        NoNullRet("True",  Coalesce(                    NullyFalse, NullyTrue,  NullyEmpty       ));
        NoNullRet("True",  Coalesce(zeroMatters: false, NullyFalse, NullyTrue,  NullyEmpty       ));
        NoNullRet("True",  Coalesce(             false, NullyFalse, NullyTrue,  NullyEmpty       ));
        NoNullRet("False", Coalesce(zeroMatters,        NullyFalse, NullyTrue,  NullyEmpty       ));
        NoNullRet("False", Coalesce(zeroMatters: true,  NullyFalse, NullyTrue,  NullyEmpty       ));
        NoNullRet("False", Coalesce(             true,  NullyFalse, NullyTrue,  NullyEmpty       ));
        NoNullRet("True",  Coalesce(                    NullyFalse, NullyTrue,  NullySpace       ));
        NoNullRet("True",  Coalesce(zeroMatters: false, NullyFalse, NullyTrue,  NullySpace       ));
        NoNullRet("True",  Coalesce(             false, NullyFalse, NullyTrue,  NullySpace       ));
        NoNullRet("False", Coalesce(zeroMatters,        NullyFalse, NullyTrue,  NullySpace       ));
        NoNullRet("False", Coalesce(zeroMatters: true,  NullyFalse, NullyTrue,  NullySpace       ));
        NoNullRet("False", Coalesce(             true,  NullyFalse, NullyTrue,  NullySpace       ));
        NoNullRet("True",  Coalesce(                    NullyFalse, NullyTrue,  NullyFilledText  ));
        NoNullRet("True",  Coalesce(zeroMatters: false, NullyFalse, NullyTrue,  NullyFilledText  ));
        NoNullRet("True",  Coalesce(             false, NullyFalse, NullyTrue,  NullyFilledText  ));
        NoNullRet("False", Coalesce(zeroMatters,        NullyFalse, NullyTrue,  NullyFilledText  ));
        NoNullRet("False", Coalesce(zeroMatters: true,  NullyFalse, NullyTrue,  NullyFilledText  ));
        NoNullRet("False", Coalesce(             true,  NullyFalse, NullyTrue,  NullyFilledText  ));
        NoNullRet("True",  Coalesce(                    NullyFalse, true,       NullText         ));
        NoNullRet("True",  Coalesce(zeroMatters: false, NullyFalse, true,       NullText         ));
        NoNullRet("True",  Coalesce(             false, NullyFalse, true,       NullText         ));
        NoNullRet("False", Coalesce(zeroMatters,        NullyFalse, true,       NullText         ));
        NoNullRet("False", Coalesce(zeroMatters: true,  NullyFalse, true,       NullText         ));
        NoNullRet("False", Coalesce(             true,  NullyFalse, true,       NullText         ));
        NoNullRet("True",  Coalesce(                    NullyFalse, true,       Empty            ));
        NoNullRet("True",  Coalesce(zeroMatters: false, NullyFalse, true,       Empty            ));
        NoNullRet("True",  Coalesce(             false, NullyFalse, true,       Empty            ));
        NoNullRet("False", Coalesce(zeroMatters,        NullyFalse, true,       Empty            ));
        NoNullRet("False", Coalesce(zeroMatters: true,  NullyFalse, true,       Empty            ));
        NoNullRet("False", Coalesce(             true,  NullyFalse, true,       Empty            ));
        NoNullRet("True",  Coalesce(                    NullyFalse, true,       Space            ));
        NoNullRet("True",  Coalesce(zeroMatters: false, NullyFalse, true,       Space            ));
        NoNullRet("True",  Coalesce(             false, NullyFalse, true,       Space            ));
        NoNullRet("False", Coalesce(zeroMatters,        NullyFalse, true,       Space            ));
        NoNullRet("False", Coalesce(zeroMatters: true,  NullyFalse, true,       Space            ));
        NoNullRet("False", Coalesce(             true,  NullyFalse, true,       Space            ));
        NoNullRet("True",  Coalesce(                    NullyFalse, true,       Text             ));
        NoNullRet("True",  Coalesce(zeroMatters: false, NullyFalse, true,       Text             ));
        NoNullRet("True",  Coalesce(             false, NullyFalse, true,       Text             ));
        NoNullRet("False", Coalesce(zeroMatters,        NullyFalse, true,       Text             ));
        NoNullRet("False", Coalesce(zeroMatters: true,  NullyFalse, true,       Text             ));
        NoNullRet("False", Coalesce(             true,  NullyFalse, true,       Text             ));
        NoNullRet("True",  Coalesce(                    NullyFalse, true,       NullyEmpty       ));
        NoNullRet("True",  Coalesce(zeroMatters: false, NullyFalse, true,       NullyEmpty       ));
        NoNullRet("True",  Coalesce(             false, NullyFalse, true,       NullyEmpty       ));
        NoNullRet("False", Coalesce(zeroMatters,        NullyFalse, true,       NullyEmpty       ));
        NoNullRet("False", Coalesce(zeroMatters: true,  NullyFalse, true,       NullyEmpty       ));
        NoNullRet("False", Coalesce(             true,  NullyFalse, true,       NullyEmpty       ));
        NoNullRet("True",  Coalesce(                    NullyFalse, true,       NullySpace       ));
        NoNullRet("True",  Coalesce(zeroMatters: false, NullyFalse, true,       NullySpace       ));
        NoNullRet("True",  Coalesce(             false, NullyFalse, true,       NullySpace       ));
        NoNullRet("False", Coalesce(zeroMatters,        NullyFalse, true,       NullySpace       ));
        NoNullRet("False", Coalesce(zeroMatters: true,  NullyFalse, true,       NullySpace       ));
        NoNullRet("False", Coalesce(             true,  NullyFalse, true,       NullySpace       ));
        NoNullRet("True",  Coalesce(                    NullyFalse, true,       NullyFilledText  ));
        NoNullRet("True",  Coalesce(zeroMatters: false, NullyFalse, true,       NullyFilledText  ));
        NoNullRet("True",  Coalesce(             false, NullyFalse, true,       NullyFilledText  ));
        NoNullRet("False", Coalesce(zeroMatters,        NullyFalse, true,       NullyFilledText  ));
        NoNullRet("False", Coalesce(zeroMatters: true,  NullyFalse, true,       NullyFilledText  ));
        NoNullRet("False", Coalesce(             true,  NullyFalse, true,       NullyFilledText  ));
    }

    [TestMethod]
    public void Coalesce_3Args_BoolToText_StaticZeroMattersFlagsInFront_Batch3()
    {
        NoNullRet("True",  Coalesce(                    NullyTrue,  NullBool,   NullText         ));
        NoNullRet("True",  Coalesce(zeroMatters: false, NullyTrue,  NullBool,   NullText         ));
        NoNullRet("True",  Coalesce(             false, NullyTrue,  NullBool,   NullText         ));
        NoNullRet("True",  Coalesce(zeroMatters,        NullyTrue,  NullBool,   NullText         ));
        NoNullRet("True",  Coalesce(zeroMatters: true,  NullyTrue,  NullBool,   NullText         ));
        NoNullRet("True",  Coalesce(             true,  NullyTrue,  NullBool,   NullText         ));
        NoNullRet("True",  Coalesce(                    NullyTrue,  NullBool,   Empty            ));
        NoNullRet("True",  Coalesce(zeroMatters: false, NullyTrue,  NullBool,   Empty            ));
        NoNullRet("True",  Coalesce(             false, NullyTrue,  NullBool,   Empty            ));
        NoNullRet("True",  Coalesce(zeroMatters,        NullyTrue,  NullBool,   Empty            ));
        NoNullRet("True",  Coalesce(zeroMatters: true,  NullyTrue,  NullBool,   Empty            ));
        NoNullRet("True",  Coalesce(             true,  NullyTrue,  NullBool,   Empty            ));
        NoNullRet("True",  Coalesce(                    NullyTrue,  NullBool,   Space            ));
        NoNullRet("True",  Coalesce(zeroMatters: false, NullyTrue,  NullBool,   Space            ));
        NoNullRet("True",  Coalesce(             false, NullyTrue,  NullBool,   Space            ));
        NoNullRet("True",  Coalesce(zeroMatters,        NullyTrue,  NullBool,   Space            ));
        NoNullRet("True",  Coalesce(zeroMatters: true,  NullyTrue,  NullBool,   Space            ));
        NoNullRet("True",  Coalesce(             true,  NullyTrue,  NullBool,   Space            ));
        NoNullRet("True",  Coalesce(                    NullyTrue,  NullBool,   Text             ));
        NoNullRet("True",  Coalesce(zeroMatters: false, NullyTrue,  NullBool,   Text             ));
        NoNullRet("True",  Coalesce(             false, NullyTrue,  NullBool,   Text             ));
        NoNullRet("True",  Coalesce(zeroMatters,        NullyTrue,  NullBool,   Text             ));
        NoNullRet("True",  Coalesce(zeroMatters: true,  NullyTrue,  NullBool,   Text             ));
        NoNullRet("True",  Coalesce(             true,  NullyTrue,  NullBool,   Text             ));
        NoNullRet("True",  Coalesce(                    NullyTrue,  NullBool,   NullyEmpty       ));
        NoNullRet("True",  Coalesce(zeroMatters: false, NullyTrue,  NullBool,   NullyEmpty       ));
        NoNullRet("True",  Coalesce(             false, NullyTrue,  NullBool,   NullyEmpty       ));
        NoNullRet("True",  Coalesce(zeroMatters,        NullyTrue,  NullBool,   NullyEmpty       ));
        NoNullRet("True",  Coalesce(zeroMatters: true,  NullyTrue,  NullBool,   NullyEmpty       ));
        NoNullRet("True",  Coalesce(             true,  NullyTrue,  NullBool,   NullyEmpty       ));
        NoNullRet("True",  Coalesce(                    NullyTrue,  NullBool,   NullySpace       ));
        NoNullRet("True",  Coalesce(zeroMatters: false, NullyTrue,  NullBool,   NullySpace       ));
        NoNullRet("True",  Coalesce(             false, NullyTrue,  NullBool,   NullySpace       ));
        NoNullRet("True",  Coalesce(zeroMatters,        NullyTrue,  NullBool,   NullySpace       ));
        NoNullRet("True",  Coalesce(zeroMatters: true,  NullyTrue,  NullBool,   NullySpace       ));
        NoNullRet("True",  Coalesce(             true,  NullyTrue,  NullBool,   NullySpace       ));
        NoNullRet("True",  Coalesce(                    NullyTrue,  NullBool,   NullyFilledText  ));
        NoNullRet("True",  Coalesce(zeroMatters: false, NullyTrue,  NullBool,   NullyFilledText  ));
        NoNullRet("True",  Coalesce(             false, NullyTrue,  NullBool,   NullyFilledText  ));
        NoNullRet("True",  Coalesce(zeroMatters,        NullyTrue,  NullBool,   NullyFilledText  ));
        NoNullRet("True",  Coalesce(zeroMatters: true,  NullyTrue,  NullBool,   NullyFilledText  ));
        NoNullRet("True",  Coalesce(             true,  NullyTrue,  NullBool,   NullyFilledText  ));
        NoNullRet("True",  Coalesce(                    NullyTrue,  NullyFalse, NullText         ));
        NoNullRet("True",  Coalesce(zeroMatters: false, NullyTrue,  NullyFalse, NullText         ));
        NoNullRet("True",  Coalesce(             false, NullyTrue,  NullyFalse, NullText         ));
        NoNullRet("True",  Coalesce(zeroMatters,        NullyTrue,  NullyFalse, NullText         ));
        NoNullRet("True",  Coalesce(zeroMatters: true,  NullyTrue,  NullyFalse, NullText         ));
        NoNullRet("True",  Coalesce(             true,  NullyTrue,  NullyFalse, NullText         ));
        NoNullRet("True",  Coalesce(                    NullyTrue,  NullyFalse, Empty            ));
        NoNullRet("True",  Coalesce(zeroMatters: false, NullyTrue,  NullyFalse, Empty            ));
        NoNullRet("True",  Coalesce(             false, NullyTrue,  NullyFalse, Empty            ));
        NoNullRet("True",  Coalesce(zeroMatters,        NullyTrue,  NullyFalse, Empty            ));
        NoNullRet("True",  Coalesce(zeroMatters: true,  NullyTrue,  NullyFalse, Empty            ));
        NoNullRet("True",  Coalesce(             true,  NullyTrue,  NullyFalse, Empty            ));
        NoNullRet("True",  Coalesce(                    NullyTrue,  NullyFalse, Space            ));
        NoNullRet("True",  Coalesce(zeroMatters: false, NullyTrue,  NullyFalse, Space            ));
        NoNullRet("True",  Coalesce(             false, NullyTrue,  NullyFalse, Space            ));
        NoNullRet("True",  Coalesce(zeroMatters,        NullyTrue,  NullyFalse, Space            ));
        NoNullRet("True",  Coalesce(zeroMatters: true,  NullyTrue,  NullyFalse, Space            ));
        NoNullRet("True",  Coalesce(             true,  NullyTrue,  NullyFalse, Space            ));
        NoNullRet("True",  Coalesce(                    NullyTrue,  NullyFalse, Text             ));
        NoNullRet("True",  Coalesce(zeroMatters: false, NullyTrue,  NullyFalse, Text             ));
        NoNullRet("True",  Coalesce(             false, NullyTrue,  NullyFalse, Text             ));
        NoNullRet("True",  Coalesce(zeroMatters,        NullyTrue,  NullyFalse, Text             ));
        NoNullRet("True",  Coalesce(zeroMatters: true,  NullyTrue,  NullyFalse, Text             ));
        NoNullRet("True",  Coalesce(             true,  NullyTrue,  NullyFalse, Text             ));
        NoNullRet("True",  Coalesce(                    NullyTrue,  NullyFalse, NullyEmpty       ));
        NoNullRet("True",  Coalesce(zeroMatters: false, NullyTrue,  NullyFalse, NullyEmpty       ));
        NoNullRet("True",  Coalesce(             false, NullyTrue,  NullyFalse, NullyEmpty       ));
        NoNullRet("True",  Coalesce(zeroMatters,        NullyTrue,  NullyFalse, NullyEmpty       ));
        NoNullRet("True",  Coalesce(zeroMatters: true,  NullyTrue,  NullyFalse, NullyEmpty       ));
        NoNullRet("True",  Coalesce(             true,  NullyTrue,  NullyFalse, NullyEmpty       ));
        NoNullRet("True",  Coalesce(                    NullyTrue,  NullyFalse, NullySpace       ));
        NoNullRet("True",  Coalesce(zeroMatters: false, NullyTrue,  NullyFalse, NullySpace       ));
        NoNullRet("True",  Coalesce(             false, NullyTrue,  NullyFalse, NullySpace       ));
        NoNullRet("True",  Coalesce(zeroMatters,        NullyTrue,  NullyFalse, NullySpace       ));
        NoNullRet("True",  Coalesce(zeroMatters: true,  NullyTrue,  NullyFalse, NullySpace       ));
        NoNullRet("True",  Coalesce(             true,  NullyTrue,  NullyFalse, NullySpace       ));
        NoNullRet("True",  Coalesce(                    NullyTrue,  NullyFalse, NullyFilledText  ));
        NoNullRet("True",  Coalesce(zeroMatters: false, NullyTrue,  NullyFalse, NullyFilledText  ));
        NoNullRet("True",  Coalesce(             false, NullyTrue,  NullyFalse, NullyFilledText  ));
        NoNullRet("True",  Coalesce(zeroMatters,        NullyTrue,  NullyFalse, NullyFilledText  ));
        NoNullRet("True",  Coalesce(zeroMatters: true,  NullyTrue,  NullyFalse, NullyFilledText  ));
        NoNullRet("True",  Coalesce(             true,  NullyTrue,  NullyFalse, NullyFilledText  ));
        NoNullRet("True",  Coalesce(                    NullyTrue,  false,      NullText         ));
        NoNullRet("True",  Coalesce(zeroMatters: false, NullyTrue,  false,      NullText         ));
        NoNullRet("True",  Coalesce(             false, NullyTrue,  false,      NullText         ));
        NoNullRet("True",  Coalesce(zeroMatters,        NullyTrue,  false,      NullText         ));
        NoNullRet("True",  Coalesce(zeroMatters: true,  NullyTrue,  false,      NullText         ));
        NoNullRet("True",  Coalesce(             true,  NullyTrue,  false,      NullText         ));
        NoNullRet("True",  Coalesce(                    NullyTrue,  false,      Empty            ));
        NoNullRet("True",  Coalesce(zeroMatters: false, NullyTrue,  false,      Empty            ));
        NoNullRet("True",  Coalesce(             false, NullyTrue,  false,      Empty            ));
        NoNullRet("True",  Coalesce(zeroMatters,        NullyTrue,  false,      Empty            ));
        NoNullRet("True",  Coalesce(zeroMatters: true,  NullyTrue,  false,      Empty            ));
        NoNullRet("True",  Coalesce(             true,  NullyTrue,  false,      Empty            ));
        NoNullRet("True",  Coalesce(                    NullyTrue,  false,      Space            ));
        NoNullRet("True",  Coalesce(zeroMatters: false, NullyTrue,  false,      Space            ));
        NoNullRet("True",  Coalesce(             false, NullyTrue,  false,      Space            ));
        NoNullRet("True",  Coalesce(zeroMatters,        NullyTrue,  false,      Space            ));
        NoNullRet("True",  Coalesce(zeroMatters: true,  NullyTrue,  false,      Space            ));
        NoNullRet("True",  Coalesce(             true,  NullyTrue,  false,      Space            ));
        NoNullRet("True",  Coalesce(                    NullyTrue,  false,      Text             ));
        NoNullRet("True",  Coalesce(zeroMatters: false, NullyTrue,  false,      Text             ));
        NoNullRet("True",  Coalesce(             false, NullyTrue,  false,      Text             ));
        NoNullRet("True",  Coalesce(zeroMatters,        NullyTrue,  false,      Text             ));
        NoNullRet("True",  Coalesce(zeroMatters: true,  NullyTrue,  false,      Text             ));
        NoNullRet("True",  Coalesce(             true,  NullyTrue,  false,      Text             ));
        NoNullRet("True",  Coalesce(                    NullyTrue,  false,      NullyEmpty       ));
        NoNullRet("True",  Coalesce(zeroMatters: false, NullyTrue,  false,      NullyEmpty       ));
        NoNullRet("True",  Coalesce(             false, NullyTrue,  false,      NullyEmpty       ));
        NoNullRet("True",  Coalesce(zeroMatters,        NullyTrue,  false,      NullyEmpty       ));
        NoNullRet("True",  Coalesce(zeroMatters: true,  NullyTrue,  false,      NullyEmpty       ));
        NoNullRet("True",  Coalesce(             true,  NullyTrue,  false,      NullyEmpty       ));
        NoNullRet("True",  Coalesce(                    NullyTrue,  false,      NullySpace       ));
        NoNullRet("True",  Coalesce(zeroMatters: false, NullyTrue,  false,      NullySpace       ));
        NoNullRet("True",  Coalesce(             false, NullyTrue,  false,      NullySpace       ));
        NoNullRet("True",  Coalesce(zeroMatters,        NullyTrue,  false,      NullySpace       ));
        NoNullRet("True",  Coalesce(zeroMatters: true,  NullyTrue,  false,      NullySpace       ));
        NoNullRet("True",  Coalesce(             true,  NullyTrue,  false,      NullySpace       ));
        NoNullRet("True",  Coalesce(                    NullyTrue,  false,      NullyFilledText  ));
        NoNullRet("True",  Coalesce(zeroMatters: false, NullyTrue,  false,      NullyFilledText  ));
        NoNullRet("True",  Coalesce(             false, NullyTrue,  false,      NullyFilledText  ));
        NoNullRet("True",  Coalesce(zeroMatters,        NullyTrue,  false,      NullyFilledText  ));
        NoNullRet("True",  Coalesce(zeroMatters: true,  NullyTrue,  false,      NullyFilledText  ));
        NoNullRet("True",  Coalesce(             true,  NullyTrue,  false,      NullyFilledText  ));
    }

    [TestMethod]
    public void Coalesce_3Args_BoolToText_StaticZeroMattersFlagsInFront_Batch4()
    {
        NoNullRet("",      Coalesce(                    false,       NullBool,   NullText         ));
        NoNullRet("",      Coalesce(zeroMatters: false, false,       NullBool,   NullText         ));
        NoNullRet("",      Coalesce(             false, false,       NullBool,   NullText         ));
        NoNullRet("False", Coalesce(zeroMatters,        false,       NullBool,   NullText         ));
        NoNullRet("False", Coalesce(zeroMatters: true,  false,       NullBool,   NullText         ));
        NoNullRet("False", Coalesce(             true,  false,       NullBool,   NullText         ));
        NoNullRet("",      Coalesce(                    false,       NullBool,   Empty            ));
        NoNullRet("",      Coalesce(zeroMatters: false, false,       NullBool,   Empty            ));
        NoNullRet("",      Coalesce(             false, false,       NullBool,   Empty            ));
        NoNullRet("False", Coalesce(zeroMatters,        false,       NullBool,   Empty            ));
        NoNullRet("False", Coalesce(zeroMatters: true,  false,       NullBool,   Empty            ));
        NoNullRet("False", Coalesce(             true,  false,       NullBool,   Empty            ));
        NoNullRet(" ",     Coalesce(                    false,       NullBool,   Space            ));
        NoNullRet(" ",     Coalesce(zeroMatters: false, false,       NullBool,   Space            ));
        NoNullRet(" ",     Coalesce(             false, false,       NullBool,   Space            ));
        NoNullRet("False", Coalesce(zeroMatters,        false,       NullBool,   Space            ));
        NoNullRet("False", Coalesce(zeroMatters: true,  false,       NullBool,   Space            ));
        NoNullRet("False", Coalesce(             true,  false,       NullBool,   Space            ));
        NoNullRet(Text,    Coalesce(                    false,       NullBool,   Text             ));
        NoNullRet(Text,    Coalesce(zeroMatters: false, false,       NullBool,   Text             ));
        NoNullRet(Text,    Coalesce(             false, false,       NullBool,   Text             ));
        NoNullRet("False", Coalesce(zeroMatters,        false,       NullBool,   Text             ));
        NoNullRet("False", Coalesce(zeroMatters: true,  false,       NullBool,   Text             ));
        NoNullRet("False", Coalesce(             true,  false,       NullBool,   Text             ));
        NoNullRet("",      Coalesce(                    false,       NullBool,   NullyEmpty       ));
        NoNullRet("",      Coalesce(zeroMatters: false, false,       NullBool,   NullyEmpty       ));
        NoNullRet("",      Coalesce(             false, false,       NullBool,   NullyEmpty       ));
        NoNullRet("False", Coalesce(zeroMatters,        false,       NullBool,   NullyEmpty       ));
        NoNullRet("False", Coalesce(zeroMatters: true,  false,       NullBool,   NullyEmpty       ));
        NoNullRet("False", Coalesce(             true,  false,       NullBool,   NullyEmpty       ));
        NoNullRet(" ",     Coalesce(                    false,       NullBool,   NullySpace       ));
        NoNullRet(" ",     Coalesce(zeroMatters: false, false,       NullBool,   NullySpace       ));
        NoNullRet(" ",     Coalesce(             false, false,       NullBool,   NullySpace       ));
        NoNullRet("False", Coalesce(zeroMatters,        false,       NullBool,   NullySpace       ));
        NoNullRet("False", Coalesce(zeroMatters: true,  false,       NullBool,   NullySpace       ));
        NoNullRet("False", Coalesce(             true,  false,       NullBool,   NullySpace       ));
        NoNullRet(Text,    Coalesce(                    false,       NullBool,   NullyFilledText  ));
        NoNullRet(Text,    Coalesce(zeroMatters: false, false,       NullBool,   NullyFilledText  ));
        NoNullRet(Text,    Coalesce(             false, false,       NullBool,   NullyFilledText  ));
        NoNullRet("False", Coalesce(zeroMatters,        false,       NullBool,   NullyFilledText  ));
        NoNullRet("False", Coalesce(zeroMatters: true,  false,       NullBool,   NullyFilledText  ));
        NoNullRet("False", Coalesce(             true,  false,       NullBool,   NullyFilledText  ));
        NoNullRet("True",  Coalesce(                    false,       NullyTrue,  NullText         ));
        NoNullRet("True",  Coalesce(zeroMatters: false, false,       NullyTrue,  NullText         ));
        NoNullRet("True",  Coalesce(             false, false,       NullyTrue,  NullText         ));
        NoNullRet("False", Coalesce(zeroMatters,        false,       NullyTrue,  NullText         ));
        NoNullRet("False", Coalesce(zeroMatters: true,  false,       NullyTrue,  NullText         ));
        NoNullRet("False", Coalesce(             true,  false,       NullyTrue,  NullText         ));
        NoNullRet("True",  Coalesce(                    false,       NullyTrue,  Empty            ));
        NoNullRet("True",  Coalesce(zeroMatters: false, false,       NullyTrue,  Empty            ));
        NoNullRet("True",  Coalesce(             false, false,       NullyTrue,  Empty            ));
        NoNullRet("False", Coalesce(zeroMatters,        false,       NullyTrue,  Empty            ));
        NoNullRet("False", Coalesce(zeroMatters: true,  false,       NullyTrue,  Empty            ));
        NoNullRet("False", Coalesce(             true,  false,       NullyTrue,  Empty            ));
        NoNullRet("True",  Coalesce(                    false,       NullyTrue,  Space            ));
        NoNullRet("True",  Coalesce(zeroMatters: false, false,       NullyTrue,  Space            ));
        NoNullRet("True",  Coalesce(             false, false,       NullyTrue,  Space            ));
        NoNullRet("False", Coalesce(zeroMatters,        false,       NullyTrue,  Space            ));
        NoNullRet("False", Coalesce(zeroMatters: true,  false,       NullyTrue,  Space            ));
        NoNullRet("False", Coalesce(             true,  false,       NullyTrue,  Space            ));
        NoNullRet("True",  Coalesce(                    false,       NullyTrue,  Text             ));
        NoNullRet("True",  Coalesce(zeroMatters: false, false,       NullyTrue,  Text             ));
        NoNullRet("True",  Coalesce(             false, false,       NullyTrue,  Text             ));
        NoNullRet("False", Coalesce(zeroMatters,        false,       NullyTrue,  Text             ));
        NoNullRet("False", Coalesce(zeroMatters: true,  false,       NullyTrue,  Text             ));
        NoNullRet("False", Coalesce(             true,  false,       NullyTrue,  Text             ));
        NoNullRet("True",  Coalesce(                    false,       NullyTrue,  NullyEmpty       ));
        NoNullRet("True",  Coalesce(zeroMatters: false, false,       NullyTrue,  NullyEmpty       ));
        NoNullRet("True",  Coalesce(             false, false,       NullyTrue,  NullyEmpty       ));
        NoNullRet("False", Coalesce(zeroMatters,        false,       NullyTrue,  NullyEmpty       ));
        NoNullRet("False", Coalesce(zeroMatters: true,  false,       NullyTrue,  NullyEmpty       ));
        NoNullRet("False", Coalesce(             true,  false,       NullyTrue,  NullyEmpty       ));
        NoNullRet("True",  Coalesce(                    false,       NullyTrue,  NullySpace       ));
        NoNullRet("True",  Coalesce(zeroMatters: false, false,       NullyTrue,  NullySpace       ));
        NoNullRet("True",  Coalesce(             false, false,       NullyTrue,  NullySpace       ));
        NoNullRet("False", Coalesce(zeroMatters,        false,       NullyTrue,  NullySpace       ));
        NoNullRet("False", Coalesce(zeroMatters: true,  false,       NullyTrue,  NullySpace       ));
        NoNullRet("False", Coalesce(             true,  false,       NullyTrue,  NullySpace       ));
        NoNullRet("True",  Coalesce(                    false,       NullyTrue,  NullyFilledText  ));
        NoNullRet("True",  Coalesce(zeroMatters: false, false,       NullyTrue,  NullyFilledText  ));
        NoNullRet("True",  Coalesce(             false, false,       NullyTrue,  NullyFilledText  ));
        NoNullRet("False", Coalesce(zeroMatters,        false,       NullyTrue,  NullyFilledText  ));
        NoNullRet("False", Coalesce(zeroMatters: true,  false,       NullyTrue,  NullyFilledText  ));
        NoNullRet("False", Coalesce(             true,  false,       NullyTrue,  NullyFilledText  ));
        NoNullRet("True",  Coalesce(                    false,       true,       NullText         ));
        NoNullRet("True",  Coalesce(zeroMatters: false, false,       true,       NullText         ));
        NoNullRet("True",  Coalesce(             false, false,       true,       NullText         ));
        NoNullRet("False", Coalesce(zeroMatters,        false,       true,       NullText         ));
        NoNullRet("False", Coalesce(zeroMatters: true,  false,       true,       NullText         ));
        NoNullRet("False", Coalesce(             true,  false,       true,       NullText         ));
        NoNullRet("True",  Coalesce(                    false,       true,       Empty            ));
        NoNullRet("True",  Coalesce(zeroMatters: false, false,       true,       Empty            ));
        NoNullRet("True",  Coalesce(             false, false,       true,       Empty            ));
        NoNullRet("False", Coalesce(zeroMatters,        false,       true,       Empty            ));
        NoNullRet("False", Coalesce(zeroMatters: true,  false,       true,       Empty            ));
        NoNullRet("False", Coalesce(             true,  false,       true,       Empty            ));
        NoNullRet("True",  Coalesce(                    false,       true,       Space            ));
        NoNullRet("True",  Coalesce(zeroMatters: false, false,       true,       Space            ));
        NoNullRet("True",  Coalesce(             false, false,       true,       Space            ));
        NoNullRet("False", Coalesce(zeroMatters,        false,       true,       Space            ));
        NoNullRet("False", Coalesce(zeroMatters: true,  false,       true,       Space            ));
        NoNullRet("False", Coalesce(             true,  false,       true,       Space            ));
        NoNullRet("True",  Coalesce(                    false,       true,       Text             ));
        NoNullRet("True",  Coalesce(zeroMatters: false, false,       true,       Text             ));
        NoNullRet("True",  Coalesce(             false, false,       true,       Text             ));
        NoNullRet("False", Coalesce(zeroMatters,        false,       true,       Text             ));
        NoNullRet("False", Coalesce(zeroMatters: true,  false,       true,       Text             ));
        NoNullRet("False", Coalesce(             true,  false,       true,       Text             ));
        NoNullRet("True",  Coalesce(                    false,       true,       NullyEmpty       ));
        NoNullRet("True",  Coalesce(zeroMatters: false, false,       true,       NullyEmpty       ));
        NoNullRet("True",  Coalesce(             false, false,       true,       NullyEmpty       ));
        NoNullRet("False", Coalesce(zeroMatters,        false,       true,       NullyEmpty       ));
        NoNullRet("False", Coalesce(zeroMatters: true,  false,       true,       NullyEmpty       ));
        NoNullRet("False", Coalesce(             true,  false,       true,       NullyEmpty       ));
        NoNullRet("True",  Coalesce(                    false,       true,       NullySpace       ));
        NoNullRet("True",  Coalesce(zeroMatters: false, false,       true,       NullySpace       ));
        NoNullRet("True",  Coalesce(             false, false,       true,       NullySpace       ));
        NoNullRet("False", Coalesce(zeroMatters,        false,       true,       NullySpace       ));
        NoNullRet("False", Coalesce(zeroMatters: true,  false,       true,       NullySpace       ));
        NoNullRet("False", Coalesce(             true,  false,       true,       NullySpace       ));
        NoNullRet("True",  Coalesce(                    false,       true,       NullyFilledText  ));
        NoNullRet("True",  Coalesce(zeroMatters: false, false,       true,       NullyFilledText  ));
        NoNullRet("True",  Coalesce(             false, false,       true,       NullyFilledText  ));
        NoNullRet("False", Coalesce(zeroMatters,        false,       true,       NullyFilledText  ));
        NoNullRet("False", Coalesce(zeroMatters: true,  false,       true,       NullyFilledText  ));
        NoNullRet("False", Coalesce(             true,  false,       true,       NullyFilledText  ));
    }

    [TestMethod]
    public void Coalesce_3Args_BoolToText_StaticZeroMattersFlagsInFront_Batch5()
    {
        NoNullRet("True",  Coalesce(                    true,        NullBool,   NullText         ));
        NoNullRet("True",  Coalesce(zeroMatters: false, true,        NullBool,   NullText         ));
        NoNullRet("True",  Coalesce(             false, true,        NullBool,   NullText         ));
        NoNullRet("True",  Coalesce(zeroMatters,        true,        NullBool,   NullText         ));
        NoNullRet("True",  Coalesce(zeroMatters: true,  true,        NullBool,   NullText         ));
        NoNullRet("True",  Coalesce(             true,  true,        NullBool,   NullText         ));
        NoNullRet("True",  Coalesce(                    true,        NullBool,   Empty            ));
        NoNullRet("True",  Coalesce(zeroMatters: false, true,        NullBool,   Empty            ));
        NoNullRet("True",  Coalesce(             false, true,        NullBool,   Empty            ));
        NoNullRet("True",  Coalesce(zeroMatters,        true,        NullBool,   Empty            ));
        NoNullRet("True",  Coalesce(zeroMatters: true,  true,        NullBool,   Empty            ));
        NoNullRet("True",  Coalesce(             true,  true,        NullBool,   Empty            ));
        NoNullRet("True",  Coalesce(                    true,        NullBool,   Space            ));
        NoNullRet("True",  Coalesce(zeroMatters: false, true,        NullBool,   Space            ));
        NoNullRet("True",  Coalesce(             false, true,        NullBool,   Space            ));
        NoNullRet("True",  Coalesce(zeroMatters,        true,        NullBool,   Space            ));
        NoNullRet("True",  Coalesce(zeroMatters: true,  true,        NullBool,   Space            ));
        NoNullRet("True",  Coalesce(             true,  true,        NullBool,   Space            ));
        NoNullRet("True",  Coalesce(                    true,        NullBool,   Text             ));
        NoNullRet("True",  Coalesce(zeroMatters: false, true,        NullBool,   Text             ));
        NoNullRet("True",  Coalesce(             false, true,        NullBool,   Text             ));
        NoNullRet("True",  Coalesce(zeroMatters,        true,        NullBool,   Text             ));
        NoNullRet("True",  Coalesce(zeroMatters: true,  true,        NullBool,   Text             ));
        NoNullRet("True",  Coalesce(             true,  true,        NullBool,   Text             ));
        NoNullRet("True",  Coalesce(                    true,        NullBool,   NullyEmpty       ));
        NoNullRet("True",  Coalesce(zeroMatters: false, true,        NullBool,   NullyEmpty       ));
        NoNullRet("True",  Coalesce(             false, true,        NullBool,   NullyEmpty       ));
        NoNullRet("True",  Coalesce(zeroMatters,        true,        NullBool,   NullyEmpty       ));
        NoNullRet("True",  Coalesce(zeroMatters: true,  true,        NullBool,   NullyEmpty       ));
        NoNullRet("True",  Coalesce(             true,  true,        NullBool,   NullyEmpty       ));
        NoNullRet("True",  Coalesce(                    true,        NullBool,   NullySpace       ));
        NoNullRet("True",  Coalesce(zeroMatters: false, true,        NullBool,   NullySpace       ));
        NoNullRet("True",  Coalesce(             false, true,        NullBool,   NullySpace       ));
        NoNullRet("True",  Coalesce(zeroMatters,        true,        NullBool,   NullySpace       ));
        NoNullRet("True",  Coalesce(zeroMatters: true,  true,        NullBool,   NullySpace       ));
        NoNullRet("True",  Coalesce(             true,  true,        NullBool,   NullySpace       ));
        NoNullRet("True",  Coalesce(                    true,        NullBool,   NullyFilledText  ));
        NoNullRet("True",  Coalesce(zeroMatters: false, true,        NullBool,   NullyFilledText  ));
        NoNullRet("True",  Coalesce(             false, true,        NullBool,   NullyFilledText  ));
        NoNullRet("True",  Coalesce(zeroMatters,        true,        NullBool,   NullyFilledText  ));
        NoNullRet("True",  Coalesce(zeroMatters: true,  true,        NullBool,   NullyFilledText  ));
        NoNullRet("True",  Coalesce(             true,  true,        NullBool,   NullyFilledText  ));
        NoNullRet("True",  Coalesce(                    true,        NullyFalse, NullText         ));
        NoNullRet("True",  Coalesce(zeroMatters: false, true,        NullyFalse, NullText         ));
        NoNullRet("True",  Coalesce(             false, true,        NullyFalse, NullText         ));
        NoNullRet("True",  Coalesce(zeroMatters,        true,        NullyFalse, NullText         ));
        NoNullRet("True",  Coalesce(zeroMatters: true,  true,        NullyFalse, NullText         ));
        NoNullRet("True",  Coalesce(             true,  true,        NullyFalse, NullText         ));
        NoNullRet("True",  Coalesce(                    true,        NullyFalse, Empty            ));
        NoNullRet("True",  Coalesce(zeroMatters: false, true,        NullyFalse, Empty            ));
        NoNullRet("True",  Coalesce(             false, true,        NullyFalse, Empty            ));
        NoNullRet("True",  Coalesce(zeroMatters,        true,        NullyFalse, Empty            ));
        NoNullRet("True",  Coalesce(zeroMatters: true,  true,        NullyFalse, Empty            ));
        NoNullRet("True",  Coalesce(             true,  true,        NullyFalse, Empty            ));
        NoNullRet("True",  Coalesce(                    true,        NullyFalse, Space            ));
        NoNullRet("True",  Coalesce(zeroMatters: false, true,        NullyFalse, Space            ));
        NoNullRet("True",  Coalesce(             false, true,        NullyFalse, Space            ));
        NoNullRet("True",  Coalesce(zeroMatters,        true,        NullyFalse, Space            ));
        NoNullRet("True",  Coalesce(zeroMatters: true,  true,        NullyFalse, Space            ));
        NoNullRet("True",  Coalesce(             true,  true,        NullyFalse, Space            ));
        NoNullRet("True",  Coalesce(                    true,        NullyFalse, Text             ));
        NoNullRet("True",  Coalesce(zeroMatters: false, true,        NullyFalse, Text             ));
        NoNullRet("True",  Coalesce(             false, true,        NullyFalse, Text             ));
        NoNullRet("True",  Coalesce(zeroMatters,        true,        NullyFalse, Text             ));
        NoNullRet("True",  Coalesce(zeroMatters: true,  true,        NullyFalse, Text             ));
        NoNullRet("True",  Coalesce(             true,  true,        NullyFalse, Text             ));
        NoNullRet("True",  Coalesce(                    true,        NullyFalse, NullyEmpty       ));
        NoNullRet("True",  Coalesce(zeroMatters: false, true,        NullyFalse, NullyEmpty       ));
        NoNullRet("True",  Coalesce(             false, true,        NullyFalse, NullyEmpty       ));
        NoNullRet("True",  Coalesce(zeroMatters,        true,        NullyFalse, NullyEmpty       ));
        NoNullRet("True",  Coalesce(zeroMatters: true,  true,        NullyFalse, NullyEmpty       ));
        NoNullRet("True",  Coalesce(             true,  true,        NullyFalse, NullyEmpty       ));
        NoNullRet("True",  Coalesce(                    true,        NullyFalse, NullySpace       ));
        NoNullRet("True",  Coalesce(zeroMatters: false, true,        NullyFalse, NullySpace       ));
        NoNullRet("True",  Coalesce(             false, true,        NullyFalse, NullySpace       ));
        NoNullRet("True",  Coalesce(zeroMatters,        true,        NullyFalse, NullySpace       ));
        NoNullRet("True",  Coalesce(zeroMatters: true,  true,        NullyFalse, NullySpace       ));
        NoNullRet("True",  Coalesce(             true,  true,        NullyFalse, NullySpace       ));
        NoNullRet("True",  Coalesce(                    true,        NullyFalse, NullyFilledText  ));
        NoNullRet("True",  Coalesce(zeroMatters: false, true,        NullyFalse, NullyFilledText  ));
        NoNullRet("True",  Coalesce(             false, true,        NullyFalse, NullyFilledText  ));
        NoNullRet("True",  Coalesce(zeroMatters,        true,        NullyFalse, NullyFilledText  ));
        NoNullRet("True",  Coalesce(zeroMatters: true,  true,        NullyFalse, NullyFilledText  ));
        NoNullRet("True",  Coalesce(             true,  true,        NullyFalse, NullyFilledText  ));
    }
}