namespace JJ.Framework.Existence.Core.Tests;

[TestClass]
public class Coalesce_3Args_BoolToText_StaticZeroMattersFlagsInFront : TestBase
{
    [TestMethod]
    public void Coalesce_3Args_BoolToText_StaticZeroMattersFlagsInFront_Batch1()
    {
        NoNullRet("",   Coalesce(                    NullNum,  Nully0, NullText         ));
        NoNullRet("",   Coalesce(zeroMatters: false, NullNum,  Nully0, NullText         ));
        NoNullRet("",   Coalesce(             false, NullNum,  Nully0, NullText         ));
        NoNullRet("0",  Coalesce(zeroMatters       , NullNum,  Nully0, NullText         ));
        NoNullRet("0",  Coalesce(zeroMatters: true , NullNum,  Nully0, NullText         ));
        NoNullRet("0",  Coalesce(             true , NullNum,  Nully0, NullText         ));
        NoNullRet("",   Coalesce(                    NullNum,  Nully0, Empty            ));
        NoNullRet("",   Coalesce(zeroMatters: false, NullNum,  Nully0, Empty            ));
        NoNullRet("",   Coalesce(             false, NullNum,  Nully0, Empty            ));
        NoNullRet("0",  Coalesce(zeroMatters       , NullNum,  Nully0, Empty            ));
        NoNullRet("0",  Coalesce(zeroMatters: true , NullNum,  Nully0, Empty            ));
        NoNullRet("0",  Coalesce(             true , NullNum,  Nully0, Empty            ));
        NoNullRet(" ",  Coalesce(                    NullNum,  Nully0, Space            ));
        NoNullRet(" ",  Coalesce(zeroMatters: false, NullNum,  Nully0, Space            ));
        NoNullRet(" ",  Coalesce(             false, NullNum,  Nully0, Space            ));
        NoNullRet("0",  Coalesce(zeroMatters       , NullNum,  Nully0, Space            ));
        NoNullRet("0",  Coalesce(zeroMatters: true , NullNum,  Nully0, Space            ));
        NoNullRet("0",  Coalesce(             true , NullNum,  Nully0, Space            ));
        NoNullRet(Text, Coalesce(                    NullNum,  Nully0, Text             ));
        NoNullRet(Text, Coalesce(zeroMatters: false, NullNum,  Nully0, Text             ));
        NoNullRet(Text, Coalesce(             false, NullNum,  Nully0, Text             ));
        NoNullRet("0",  Coalesce(zeroMatters       , NullNum,  Nully0, Text             ));
        NoNullRet("0",  Coalesce(zeroMatters: true , NullNum,  Nully0, Text             ));
        NoNullRet("0",  Coalesce(             true , NullNum,  Nully0, Text             ));
        NoNullRet("",   Coalesce(                    NullNum,  Nully0, NullyEmpty       ));
        NoNullRet("",   Coalesce(zeroMatters: false, NullNum,  Nully0, NullyEmpty       ));
        NoNullRet("",   Coalesce(             false, NullNum,  Nully0, NullyEmpty       ));
        NoNullRet("0",  Coalesce(zeroMatters       , NullNum,  Nully0, NullyEmpty       ));
        NoNullRet("0",  Coalesce(zeroMatters: true , NullNum,  Nully0, NullyEmpty       ));
        NoNullRet("0",  Coalesce(             true , NullNum,  Nully0, NullyEmpty       ));
        NoNullRet(" ",  Coalesce(                    NullNum,  Nully0, NullySpace       ));
        NoNullRet(" ",  Coalesce(zeroMatters: false, NullNum,  Nully0, NullySpace       ));
        NoNullRet(" ",  Coalesce(             false, NullNum,  Nully0, NullySpace       ));
        NoNullRet("0",  Coalesce(zeroMatters       , NullNum,  Nully0, NullySpace       ));
        NoNullRet("0",  Coalesce(zeroMatters: true , NullNum,  Nully0, NullySpace       ));
        NoNullRet("0",  Coalesce(             true , NullNum,  Nully0, NullySpace       ));
        NoNullRet(Text, Coalesce(                    NullNum,  Nully0, NullyFilledText  ));
        NoNullRet(Text, Coalesce(zeroMatters: false, NullNum,  Nully0, NullyFilledText  ));
        NoNullRet(Text, Coalesce(             false, NullNum,  Nully0, NullyFilledText  ));
        NoNullRet("0",  Coalesce(zeroMatters       , NullNum,  Nully0, NullyFilledText  ));
        NoNullRet("0",  Coalesce(zeroMatters: true , NullNum,  Nully0, NullyFilledText  ));
        NoNullRet("0",  Coalesce(             true , NullNum,  Nully0, NullyFilledText  ));
        NoNullRet("1",  Coalesce(                    NullNum,  Nully1, NullText         ));
        NoNullRet("1",  Coalesce(zeroMatters: false, NullNum,  Nully1, NullText         ));
        NoNullRet("1",  Coalesce(             false, NullNum,  Nully1, NullText         ));
        NoNullRet("1",  Coalesce(zeroMatters       , NullNum,  Nully1, NullText         ));
        NoNullRet("1",  Coalesce(zeroMatters: true , NullNum,  Nully1, NullText         ));
        NoNullRet("1",  Coalesce(             true , NullNum,  Nully1, NullText         ));
        NoNullRet("1",  Coalesce(                    NullNum,  Nully1, Empty            ));
        NoNullRet("1",  Coalesce(zeroMatters: false, NullNum,  Nully1, Empty            ));
        NoNullRet("1",  Coalesce(             false, NullNum,  Nully1, Empty            ));
        NoNullRet("1",  Coalesce(zeroMatters       , NullNum,  Nully1, Empty            ));
        NoNullRet("1",  Coalesce(zeroMatters: true , NullNum,  Nully1, Empty            ));
        NoNullRet("1",  Coalesce(             true , NullNum,  Nully1, Empty            ));
        NoNullRet("1",  Coalesce(                    NullNum,  Nully1, Space            ));
        NoNullRet("1",  Coalesce(zeroMatters: false, NullNum,  Nully1, Space            ));
        NoNullRet("1",  Coalesce(             false, NullNum,  Nully1, Space            ));
        NoNullRet("1",  Coalesce(zeroMatters       , NullNum,  Nully1, Space            ));
        NoNullRet("1",  Coalesce(zeroMatters: true , NullNum,  Nully1, Space            ));
        NoNullRet("1",  Coalesce(             true , NullNum,  Nully1, Space            ));
        NoNullRet("1",  Coalesce(                    NullNum,  Nully1, Text             ));
        NoNullRet("1",  Coalesce(zeroMatters: false, NullNum,  Nully1, Text             ));
        NoNullRet("1",  Coalesce(             false, NullNum,  Nully1, Text             ));
        NoNullRet("1",  Coalesce(zeroMatters       , NullNum,  Nully1, Text             ));
        NoNullRet("1",  Coalesce(zeroMatters: true , NullNum,  Nully1, Text             ));
        NoNullRet("1",  Coalesce(             true , NullNum,  Nully1, Text             ));
        NoNullRet("1",  Coalesce(                    NullNum,  Nully1, NullyEmpty       ));
        NoNullRet("1",  Coalesce(zeroMatters: false, NullNum,  Nully1, NullyEmpty       ));
        NoNullRet("1",  Coalesce(             false, NullNum,  Nully1, NullyEmpty       ));
        NoNullRet("1",  Coalesce(zeroMatters       , NullNum,  Nully1, NullyEmpty       ));
        NoNullRet("1",  Coalesce(zeroMatters: true , NullNum,  Nully1, NullyEmpty       ));
        NoNullRet("1",  Coalesce(             true , NullNum,  Nully1, NullyEmpty       ));
        NoNullRet("1",  Coalesce(                    NullNum,  Nully1, NullySpace       ));
        NoNullRet("1",  Coalesce(zeroMatters: false, NullNum,  Nully1, NullySpace       ));
        NoNullRet("1",  Coalesce(             false, NullNum,  Nully1, NullySpace       ));
        NoNullRet("1",  Coalesce(zeroMatters       , NullNum,  Nully1, NullySpace       ));
        NoNullRet("1",  Coalesce(zeroMatters: true , NullNum,  Nully1, NullySpace       ));
        NoNullRet("1",  Coalesce(             true , NullNum,  Nully1, NullySpace       ));
        NoNullRet("1",  Coalesce(                    NullNum,  Nully1, NullyFilledText  ));
        NoNullRet("1",  Coalesce(zeroMatters: false, NullNum,  Nully1, NullyFilledText  ));
        NoNullRet("1",  Coalesce(             false, NullNum,  Nully1, NullyFilledText  ));
        NoNullRet("1",  Coalesce(zeroMatters       , NullNum,  Nully1, NullyFilledText  ));
        NoNullRet("1",  Coalesce(zeroMatters: true , NullNum,  Nully1, NullyFilledText  ));
        NoNullRet("1",  Coalesce(             true , NullNum,  Nully1, NullyFilledText  ));
        NoNullRet("",   Coalesce(                    NullNum,       0, NullText         ));
        NoNullRet("",   Coalesce(zeroMatters: false, NullNum,       0, NullText         ));
        NoNullRet("",   Coalesce(             false, NullNum,       0, NullText         ));
        NoNullRet("0",  Coalesce(zeroMatters       , NullNum,       0, NullText         ));
        NoNullRet("0",  Coalesce(zeroMatters: true , NullNum,       0, NullText         ));
        NoNullRet("0",  Coalesce(             true , NullNum,       0, NullText         ));
        NoNullRet("",   Coalesce(                    NullNum,       0, Empty            ));
        NoNullRet("",   Coalesce(zeroMatters: false, NullNum,       0, Empty            ));
        NoNullRet("",   Coalesce(             false, NullNum,       0, Empty            ));
        NoNullRet("0",  Coalesce(zeroMatters       , NullNum,       0, Empty            ));
        NoNullRet("0",  Coalesce(zeroMatters: true , NullNum,       0, Empty            ));
        NoNullRet("0",  Coalesce(             true , NullNum,       0, Empty            ));
        NoNullRet(" ",  Coalesce(                    NullNum,       0, Space            ));
        NoNullRet(" ",  Coalesce(zeroMatters: false, NullNum,       0, Space            ));
        NoNullRet(" ",  Coalesce(             false, NullNum,       0, Space            ));
        NoNullRet("0",  Coalesce(zeroMatters       , NullNum,       0, Space            ));
        NoNullRet("0",  Coalesce(zeroMatters: true , NullNum,       0, Space            ));
        NoNullRet("0",  Coalesce(             true , NullNum,       0, Space            ));
        NoNullRet(Text, Coalesce(                    NullNum,       0, Text             ));
        NoNullRet(Text, Coalesce(zeroMatters: false, NullNum,       0, Text             ));
        NoNullRet(Text, Coalesce(             false, NullNum,       0, Text             ));
        NoNullRet("0",  Coalesce(zeroMatters       , NullNum,       0, Text             ));
        NoNullRet("0",  Coalesce(zeroMatters: true , NullNum,       0, Text             ));
        NoNullRet("0",  Coalesce(             true , NullNum,       0, Text             ));
        NoNullRet("",   Coalesce(                    NullNum,       0, NullyEmpty       ));
        NoNullRet("",   Coalesce(zeroMatters: false, NullNum,       0, NullyEmpty       ));
        NoNullRet("",   Coalesce(             false, NullNum,       0, NullyEmpty       ));
        NoNullRet("0",  Coalesce(zeroMatters       , NullNum,       0, NullyEmpty       ));
        NoNullRet("0",  Coalesce(zeroMatters: true , NullNum,       0, NullyEmpty       ));
        NoNullRet("0",  Coalesce(             true , NullNum,       0, NullyEmpty       ));
        NoNullRet(" ",  Coalesce(                    NullNum,       0, NullySpace       ));
        NoNullRet(" ",  Coalesce(zeroMatters: false, NullNum,       0, NullySpace       ));
        NoNullRet(" ",  Coalesce(             false, NullNum,       0, NullySpace       ));
        NoNullRet("0",  Coalesce(zeroMatters       , NullNum,       0, NullySpace       ));
        NoNullRet("0",  Coalesce(zeroMatters: true , NullNum,       0, NullySpace       ));
        NoNullRet("0",  Coalesce(             true , NullNum,       0, NullySpace       ));
        NoNullRet(Text, Coalesce(                    NullNum,       0, NullyFilledText  ));
        NoNullRet(Text, Coalesce(zeroMatters: false, NullNum,       0, NullyFilledText  ));
        NoNullRet(Text, Coalesce(             false, NullNum,       0, NullyFilledText  ));
        NoNullRet("0",  Coalesce(zeroMatters       , NullNum,       0, NullyFilledText  ));
        NoNullRet("0",  Coalesce(zeroMatters: true , NullNum,       0, NullyFilledText  ));
        NoNullRet("0",  Coalesce(             true , NullNum,       0, NullyFilledText  ));
        NoNullRet("1",  Coalesce(                    NullNum,       1, NullText         ));
        NoNullRet("1",  Coalesce(zeroMatters: false, NullNum,       1, NullText         ));
        NoNullRet("1",  Coalesce(             false, NullNum,       1, NullText         ));
        NoNullRet("1",  Coalesce(zeroMatters       , NullNum,       1, NullText         ));
        NoNullRet("1",  Coalesce(zeroMatters: true , NullNum,       1, NullText         ));
        NoNullRet("1",  Coalesce(             true , NullNum,       1, NullText         ));
        NoNullRet("1",  Coalesce(                    NullNum,       1, Empty            ));
        NoNullRet("1",  Coalesce(zeroMatters: false, NullNum,       1, Empty            ));
        NoNullRet("1",  Coalesce(             false, NullNum,       1, Empty            ));
        NoNullRet("1",  Coalesce(zeroMatters       , NullNum,       1, Empty            ));
        NoNullRet("1",  Coalesce(zeroMatters: true , NullNum,       1, Empty            ));
        NoNullRet("1",  Coalesce(             true , NullNum,       1, Empty            ));
        NoNullRet("1",  Coalesce(                    NullNum,       1, Space            ));
        NoNullRet("1",  Coalesce(zeroMatters: false, NullNum,       1, Space            ));
        NoNullRet("1",  Coalesce(             false, NullNum,       1, Space            ));
        NoNullRet("1",  Coalesce(zeroMatters       , NullNum,       1, Space            ));
        NoNullRet("1",  Coalesce(zeroMatters: true , NullNum,       1, Space            ));
        NoNullRet("1",  Coalesce(             true , NullNum,       1, Space            ));
        NoNullRet("1",  Coalesce(                    NullNum,       1, Text             ));
        NoNullRet("1",  Coalesce(zeroMatters: false, NullNum,       1, Text             ));
        NoNullRet("1",  Coalesce(             false, NullNum,       1, Text             ));
        NoNullRet("1",  Coalesce(zeroMatters       , NullNum,       1, Text             ));
        NoNullRet("1",  Coalesce(zeroMatters: true , NullNum,       1, Text             ));
        NoNullRet("1",  Coalesce(             true , NullNum,       1, Text             ));
        NoNullRet("1",  Coalesce(                    NullNum,       1, NullyEmpty       ));
        NoNullRet("1",  Coalesce(zeroMatters: false, NullNum,       1, NullyEmpty       ));
        NoNullRet("1",  Coalesce(             false, NullNum,       1, NullyEmpty       ));
        NoNullRet("1",  Coalesce(zeroMatters       , NullNum,       1, NullyEmpty       ));
        NoNullRet("1",  Coalesce(zeroMatters: true , NullNum,       1, NullyEmpty       ));
        NoNullRet("1",  Coalesce(             true , NullNum,       1, NullyEmpty       ));
        NoNullRet("1",  Coalesce(                    NullNum,       1, NullySpace       ));
        NoNullRet("1",  Coalesce(zeroMatters: false, NullNum,       1, NullySpace       ));
        NoNullRet("1",  Coalesce(             false, NullNum,       1, NullySpace       ));
        NoNullRet("1",  Coalesce(zeroMatters       , NullNum,       1, NullySpace       ));
        NoNullRet("1",  Coalesce(zeroMatters: true , NullNum,       1, NullySpace       ));
        NoNullRet("1",  Coalesce(             true , NullNum,       1, NullySpace       ));
        NoNullRet("1",  Coalesce(                    NullNum,       1, NullyFilledText  ));
        NoNullRet("1",  Coalesce(zeroMatters: false, NullNum,       1, NullyFilledText  ));
        NoNullRet("1",  Coalesce(             false, NullNum,       1, NullyFilledText  ));
        NoNullRet("1",  Coalesce(zeroMatters       , NullNum,       1, NullyFilledText  ));
        NoNullRet("1",  Coalesce(zeroMatters: true , NullNum,       1, NullyFilledText  ));
        NoNullRet("1",  Coalesce(             true , NullNum,       1, NullyFilledText  ));
    }

    [TestMethod]
    public void Coalesce_3Args_BoolToText_StaticZeroMattersFlagsInFront_Batch2()
    {
        NoNullRet("",   Coalesce(                    Nully0,  NullNum, NullText         ));
        NoNullRet("",   Coalesce(zeroMatters: false, Nully0,  NullNum, NullText         ));
        NoNullRet("",   Coalesce(             false, Nully0,  NullNum, NullText         ));
        NoNullRet("0",  Coalesce(zeroMatters       , Nully0,  NullNum, NullText         ));
        NoNullRet("0",  Coalesce(zeroMatters: true , Nully0,  NullNum, NullText         ));
        NoNullRet("0",  Coalesce(             true , Nully0,  NullNum, NullText         ));
        NoNullRet("",   Coalesce(                    Nully0,  NullNum, Empty            ));
        NoNullRet("",   Coalesce(zeroMatters: false, Nully0,  NullNum, Empty            ));
        NoNullRet("",   Coalesce(             false, Nully0,  NullNum, Empty            ));
        NoNullRet("0",  Coalesce(zeroMatters       , Nully0,  NullNum, Empty            ));
        NoNullRet("0",  Coalesce(zeroMatters: true , Nully0,  NullNum, Empty            ));
        NoNullRet("0",  Coalesce(             true , Nully0,  NullNum, Empty            ));
        NoNullRet(" ",  Coalesce(                    Nully0,  NullNum, Space            ));
        NoNullRet(" ",  Coalesce(zeroMatters: false, Nully0,  NullNum, Space            ));
        NoNullRet(" ",  Coalesce(             false, Nully0,  NullNum, Space            ));
        NoNullRet("0",  Coalesce(zeroMatters       , Nully0,  NullNum, Space            ));
        NoNullRet("0",  Coalesce(zeroMatters: true , Nully0,  NullNum, Space            ));
        NoNullRet("0",  Coalesce(             true , Nully0,  NullNum, Space            ));
        NoNullRet(Text, Coalesce(                    Nully0,  NullNum, Text             ));
        NoNullRet(Text, Coalesce(zeroMatters: false, Nully0,  NullNum, Text             ));
        NoNullRet(Text, Coalesce(             false, Nully0,  NullNum, Text             ));
        NoNullRet("0",  Coalesce(zeroMatters       , Nully0,  NullNum, Text             ));
        NoNullRet("0",  Coalesce(zeroMatters: true , Nully0,  NullNum, Text             ));
        NoNullRet("0",  Coalesce(             true , Nully0,  NullNum, Text             ));
        NoNullRet("",   Coalesce(                    Nully0,  NullNum, NullyEmpty       ));
        NoNullRet("",   Coalesce(zeroMatters: false, Nully0,  NullNum, NullyEmpty       ));
        NoNullRet("",   Coalesce(             false, Nully0,  NullNum, NullyEmpty       ));
        NoNullRet("0",  Coalesce(zeroMatters       , Nully0,  NullNum, NullyEmpty       ));
        NoNullRet("0",  Coalesce(zeroMatters: true , Nully0,  NullNum, NullyEmpty       ));
        NoNullRet("0",  Coalesce(             true , Nully0,  NullNum, NullyEmpty       ));
        NoNullRet(" ",  Coalesce(                    Nully0,  NullNum, NullySpace       ));
        NoNullRet(" ",  Coalesce(zeroMatters: false, Nully0,  NullNum, NullySpace       ));
        NoNullRet(" ",  Coalesce(             false, Nully0,  NullNum, NullySpace       ));
        NoNullRet("0",  Coalesce(zeroMatters       , Nully0,  NullNum, NullySpace       ));
        NoNullRet("0",  Coalesce(zeroMatters: true , Nully0,  NullNum, NullySpace       ));
        NoNullRet("0",  Coalesce(             true , Nully0,  NullNum, NullySpace       ));
        NoNullRet(Text, Coalesce(                    Nully0,  NullNum, NullyFilledText  ));
        NoNullRet(Text, Coalesce(zeroMatters: false, Nully0,  NullNum, NullyFilledText  ));
        NoNullRet(Text, Coalesce(             false, Nully0,  NullNum, NullyFilledText  ));
        NoNullRet("0",  Coalesce(zeroMatters       , Nully0,  NullNum, NullyFilledText  ));
        NoNullRet("0",  Coalesce(zeroMatters: true , Nully0,  NullNum, NullyFilledText  ));
        NoNullRet("0",  Coalesce(             true , Nully0,  NullNum, NullyFilledText  ));
        NoNullRet("1",  Coalesce(                    Nully0,   Nully1, NullText         ));
        NoNullRet("1",  Coalesce(zeroMatters: false, Nully0,   Nully1, NullText         ));
        NoNullRet("1",  Coalesce(             false, Nully0,   Nully1, NullText         ));
        NoNullRet("0",  Coalesce(zeroMatters       , Nully0,   Nully1, NullText         ));
        NoNullRet("0",  Coalesce(zeroMatters: true , Nully0,   Nully1, NullText         ));
        NoNullRet("0",  Coalesce(             true , Nully0,   Nully1, NullText         ));
        NoNullRet("1",  Coalesce(                    Nully0,   Nully1, Empty            ));
        NoNullRet("1",  Coalesce(zeroMatters: false, Nully0,   Nully1, Empty            ));
        NoNullRet("1",  Coalesce(             false, Nully0,   Nully1, Empty            ));
        NoNullRet("0",  Coalesce(zeroMatters       , Nully0,   Nully1, Empty            ));
        NoNullRet("0",  Coalesce(zeroMatters: true , Nully0,   Nully1, Empty            ));
        NoNullRet("0",  Coalesce(             true , Nully0,   Nully1, Empty            ));
        NoNullRet("1",  Coalesce(                    Nully0,   Nully1, Space            ));
        NoNullRet("1",  Coalesce(zeroMatters: false, Nully0,   Nully1, Space            ));
        NoNullRet("1",  Coalesce(             false, Nully0,   Nully1, Space            ));
        NoNullRet("0",  Coalesce(zeroMatters       , Nully0,   Nully1, Space            ));
        NoNullRet("0",  Coalesce(zeroMatters: true , Nully0,   Nully1, Space            ));
        NoNullRet("0",  Coalesce(             true , Nully0,   Nully1, Space            ));
        NoNullRet("1",  Coalesce(                    Nully0,   Nully1, Text             ));
        NoNullRet("1",  Coalesce(zeroMatters: false, Nully0,   Nully1, Text             ));
        NoNullRet("1",  Coalesce(             false, Nully0,   Nully1, Text             ));
        NoNullRet("0",  Coalesce(zeroMatters       , Nully0,   Nully1, Text             ));
        NoNullRet("0",  Coalesce(zeroMatters: true , Nully0,   Nully1, Text             ));
        NoNullRet("0",  Coalesce(             true , Nully0,   Nully1, Text             ));
        NoNullRet("1",  Coalesce(                    Nully0,   Nully1, NullyEmpty       ));
        NoNullRet("1",  Coalesce(zeroMatters: false, Nully0,   Nully1, NullyEmpty       ));
        NoNullRet("1",  Coalesce(             false, Nully0,   Nully1, NullyEmpty       ));
        NoNullRet("0",  Coalesce(zeroMatters       , Nully0,   Nully1, NullyEmpty       ));
        NoNullRet("0",  Coalesce(zeroMatters: true , Nully0,   Nully1, NullyEmpty       ));
        NoNullRet("0",  Coalesce(             true , Nully0,   Nully1, NullyEmpty       ));
        NoNullRet("1",  Coalesce(                    Nully0,   Nully1, NullySpace       ));
        NoNullRet("1",  Coalesce(zeroMatters: false, Nully0,   Nully1, NullySpace       ));
        NoNullRet("1",  Coalesce(             false, Nully0,   Nully1, NullySpace       ));
        NoNullRet("0",  Coalesce(zeroMatters       , Nully0,   Nully1, NullySpace       ));
        NoNullRet("0",  Coalesce(zeroMatters: true , Nully0,   Nully1, NullySpace       ));
        NoNullRet("0",  Coalesce(             true , Nully0,   Nully1, NullySpace       ));
        NoNullRet("1",  Coalesce(                    Nully0,   Nully1, NullyFilledText  ));
        NoNullRet("1",  Coalesce(zeroMatters: false, Nully0,   Nully1, NullyFilledText  ));
        NoNullRet("1",  Coalesce(             false, Nully0,   Nully1, NullyFilledText  ));
        NoNullRet("0",  Coalesce(zeroMatters       , Nully0,   Nully1, NullyFilledText  ));
        NoNullRet("0",  Coalesce(zeroMatters: true , Nully0,   Nully1, NullyFilledText  ));
        NoNullRet("0",  Coalesce(             true , Nully0,   Nully1, NullyFilledText  ));
        NoNullRet("1",  Coalesce(                    Nully0,        1, NullText         ));
        NoNullRet("1",  Coalesce(zeroMatters: false, Nully0,        1, NullText         ));
        NoNullRet("1",  Coalesce(             false, Nully0,        1, NullText         ));
        NoNullRet("0",  Coalesce(zeroMatters       , Nully0,        1, NullText         ));
        NoNullRet("0",  Coalesce(zeroMatters: true , Nully0,        1, NullText         ));
        NoNullRet("0",  Coalesce(             true , Nully0,        1, NullText         ));
        NoNullRet("1",  Coalesce(                    Nully0,        1, Empty            ));
        NoNullRet("1",  Coalesce(zeroMatters: false, Nully0,        1, Empty            ));
        NoNullRet("1",  Coalesce(             false, Nully0,        1, Empty            ));
        NoNullRet("0",  Coalesce(zeroMatters       , Nully0,        1, Empty            ));
        NoNullRet("0",  Coalesce(zeroMatters: true , Nully0,        1, Empty            ));
        NoNullRet("0",  Coalesce(             true , Nully0,        1, Empty            ));
        NoNullRet("1",  Coalesce(                    Nully0,        1, Space            ));
        NoNullRet("1",  Coalesce(zeroMatters: false, Nully0,        1, Space            ));
        NoNullRet("1",  Coalesce(             false, Nully0,        1, Space            ));
        NoNullRet("0",  Coalesce(zeroMatters       , Nully0,        1, Space            ));
        NoNullRet("0",  Coalesce(zeroMatters: true , Nully0,        1, Space            ));
        NoNullRet("0",  Coalesce(             true , Nully0,        1, Space            ));
        NoNullRet("1",  Coalesce(                    Nully0,        1, Text             ));
        NoNullRet("1",  Coalesce(zeroMatters: false, Nully0,        1, Text             ));
        NoNullRet("1",  Coalesce(             false, Nully0,        1, Text             ));
        NoNullRet("0",  Coalesce(zeroMatters       , Nully0,        1, Text             ));
        NoNullRet("0",  Coalesce(zeroMatters: true , Nully0,        1, Text             ));
        NoNullRet("0",  Coalesce(             true , Nully0,        1, Text             ));
        NoNullRet("1",  Coalesce(                    Nully0,        1, NullyEmpty       ));
        NoNullRet("1",  Coalesce(zeroMatters: false, Nully0,        1, NullyEmpty       ));
        NoNullRet("1",  Coalesce(             false, Nully0,        1, NullyEmpty       ));
        NoNullRet("0",  Coalesce(zeroMatters       , Nully0,        1, NullyEmpty       ));
        NoNullRet("0",  Coalesce(zeroMatters: true , Nully0,        1, NullyEmpty       ));
        NoNullRet("0",  Coalesce(             true , Nully0,        1, NullyEmpty       ));
        NoNullRet("1",  Coalesce(                    Nully0,        1, NullySpace       ));
        NoNullRet("1",  Coalesce(zeroMatters: false, Nully0,        1, NullySpace       ));
        NoNullRet("1",  Coalesce(             false, Nully0,        1, NullySpace       ));
        NoNullRet("0",  Coalesce(zeroMatters       , Nully0,        1, NullySpace       ));
        NoNullRet("0",  Coalesce(zeroMatters: true , Nully0,        1, NullySpace       ));
        NoNullRet("0",  Coalesce(             true , Nully0,        1, NullySpace       ));
        NoNullRet("1",  Coalesce(                    Nully0,        1, NullyFilledText  ));
        NoNullRet("1",  Coalesce(zeroMatters: false, Nully0,        1, NullyFilledText  ));
        NoNullRet("1",  Coalesce(             false, Nully0,        1, NullyFilledText  ));
        NoNullRet("0",  Coalesce(zeroMatters       , Nully0,        1, NullyFilledText  ));
        NoNullRet("0",  Coalesce(zeroMatters: true , Nully0,        1, NullyFilledText  ));
        NoNullRet("0",  Coalesce(             true , Nully0,        1, NullyFilledText  ));
    }

    [TestMethod]
    public void Coalesce_3Args_BoolToText_StaticZeroMattersFlagsInFront_Batch3()
    {
        NoNullRet("1",  Coalesce(                    Nully1,  NullNum, NullText         ));
        NoNullRet("1",  Coalesce(zeroMatters: false, Nully1,  NullNum, NullText         ));
        NoNullRet("1",  Coalesce(             false, Nully1,  NullNum, NullText         ));
        NoNullRet("1",  Coalesce(zeroMatters       , Nully1,  NullNum, NullText         ));
        NoNullRet("1",  Coalesce(zeroMatters: true , Nully1,  NullNum, NullText         ));
        NoNullRet("1",  Coalesce(             true , Nully1,  NullNum, NullText         ));
        NoNullRet("1",  Coalesce(                    Nully1,  NullNum, Empty            ));
        NoNullRet("1",  Coalesce(zeroMatters: false, Nully1,  NullNum, Empty            ));
        NoNullRet("1",  Coalesce(             false, Nully1,  NullNum, Empty            ));
        NoNullRet("1",  Coalesce(zeroMatters       , Nully1,  NullNum, Empty            ));
        NoNullRet("1",  Coalesce(zeroMatters: true , Nully1,  NullNum, Empty            ));
        NoNullRet("1",  Coalesce(             true , Nully1,  NullNum, Empty            ));
        NoNullRet("1",  Coalesce(                    Nully1,  NullNum, Space            ));
        NoNullRet("1",  Coalesce(zeroMatters: false, Nully1,  NullNum, Space            ));
        NoNullRet("1",  Coalesce(             false, Nully1,  NullNum, Space            ));
        NoNullRet("1",  Coalesce(zeroMatters       , Nully1,  NullNum, Space            ));
        NoNullRet("1",  Coalesce(zeroMatters: true , Nully1,  NullNum, Space            ));
        NoNullRet("1",  Coalesce(             true , Nully1,  NullNum, Space            ));
        NoNullRet("1",  Coalesce(                    Nully1,  NullNum, Text             ));
        NoNullRet("1",  Coalesce(zeroMatters: false, Nully1,  NullNum, Text             ));
        NoNullRet("1",  Coalesce(             false, Nully1,  NullNum, Text             ));
        NoNullRet("1",  Coalesce(zeroMatters       , Nully1,  NullNum, Text             ));
        NoNullRet("1",  Coalesce(zeroMatters: true , Nully1,  NullNum, Text             ));
        NoNullRet("1",  Coalesce(             true , Nully1,  NullNum, Text             ));
        NoNullRet("1",  Coalesce(                    Nully1,  NullNum, NullyEmpty       ));
        NoNullRet("1",  Coalesce(zeroMatters: false, Nully1,  NullNum, NullyEmpty       ));
        NoNullRet("1",  Coalesce(             false, Nully1,  NullNum, NullyEmpty       ));
        NoNullRet("1",  Coalesce(zeroMatters       , Nully1,  NullNum, NullyEmpty       ));
        NoNullRet("1",  Coalesce(zeroMatters: true , Nully1,  NullNum, NullyEmpty       ));
        NoNullRet("1",  Coalesce(             true , Nully1,  NullNum, NullyEmpty       ));
        NoNullRet("1",  Coalesce(                    Nully1,  NullNum, NullySpace       ));
        NoNullRet("1",  Coalesce(zeroMatters: false, Nully1,  NullNum, NullySpace       ));
        NoNullRet("1",  Coalesce(             false, Nully1,  NullNum, NullySpace       ));
        NoNullRet("1",  Coalesce(zeroMatters       , Nully1,  NullNum, NullySpace       ));
        NoNullRet("1",  Coalesce(zeroMatters: true , Nully1,  NullNum, NullySpace       ));
        NoNullRet("1",  Coalesce(             true , Nully1,  NullNum, NullySpace       ));
        NoNullRet("1",  Coalesce(                    Nully1,  NullNum, NullyFilledText  ));
        NoNullRet("1",  Coalesce(zeroMatters: false, Nully1,  NullNum, NullyFilledText  ));
        NoNullRet("1",  Coalesce(             false, Nully1,  NullNum, NullyFilledText  ));
        NoNullRet("1",  Coalesce(zeroMatters       , Nully1,  NullNum, NullyFilledText  ));
        NoNullRet("1",  Coalesce(zeroMatters: true , Nully1,  NullNum, NullyFilledText  ));
        NoNullRet("1",  Coalesce(             true , Nully1,  NullNum, NullyFilledText  ));
        NoNullRet("1",  Coalesce(                    Nully1,   Nully0, NullText         ));
        NoNullRet("1",  Coalesce(zeroMatters: false, Nully1,   Nully0, NullText         ));
        NoNullRet("1",  Coalesce(             false, Nully1,   Nully0, NullText         ));
        NoNullRet("1",  Coalesce(zeroMatters       , Nully1,   Nully0, NullText         ));
        NoNullRet("1",  Coalesce(zeroMatters: true , Nully1,   Nully0, NullText         ));
        NoNullRet("1",  Coalesce(             true , Nully1,   Nully0, NullText         ));
        NoNullRet("1",  Coalesce(                    Nully1,   Nully0, Empty            ));
        NoNullRet("1",  Coalesce(zeroMatters: false, Nully1,   Nully0, Empty            ));
        NoNullRet("1",  Coalesce(             false, Nully1,   Nully0, Empty            ));
        NoNullRet("1",  Coalesce(zeroMatters       , Nully1,   Nully0, Empty            ));
        NoNullRet("1",  Coalesce(zeroMatters: true , Nully1,   Nully0, Empty            ));
        NoNullRet("1",  Coalesce(             true , Nully1,   Nully0, Empty            ));
        NoNullRet("1",  Coalesce(                    Nully1,   Nully0, Space            ));
        NoNullRet("1",  Coalesce(zeroMatters: false, Nully1,   Nully0, Space            ));
        NoNullRet("1",  Coalesce(             false, Nully1,   Nully0, Space            ));
        NoNullRet("1",  Coalesce(zeroMatters       , Nully1,   Nully0, Space            ));
        NoNullRet("1",  Coalesce(zeroMatters: true , Nully1,   Nully0, Space            ));
        NoNullRet("1",  Coalesce(             true , Nully1,   Nully0, Space            ));
        NoNullRet("1",  Coalesce(                    Nully1,   Nully0, Text             ));
        NoNullRet("1",  Coalesce(zeroMatters: false, Nully1,   Nully0, Text             ));
        NoNullRet("1",  Coalesce(             false, Nully1,   Nully0, Text             ));
        NoNullRet("1",  Coalesce(zeroMatters       , Nully1,   Nully0, Text             ));
        NoNullRet("1",  Coalesce(zeroMatters: true , Nully1,   Nully0, Text             ));
        NoNullRet("1",  Coalesce(             true , Nully1,   Nully0, Text             ));
        NoNullRet("1",  Coalesce(                    Nully1,   Nully0, NullyEmpty       ));
        NoNullRet("1",  Coalesce(zeroMatters: false, Nully1,   Nully0, NullyEmpty       ));
        NoNullRet("1",  Coalesce(             false, Nully1,   Nully0, NullyEmpty       ));
        NoNullRet("1",  Coalesce(zeroMatters       , Nully1,   Nully0, NullyEmpty       ));
        NoNullRet("1",  Coalesce(zeroMatters: true , Nully1,   Nully0, NullyEmpty       ));
        NoNullRet("1",  Coalesce(             true , Nully1,   Nully0, NullyEmpty       ));
        NoNullRet("1",  Coalesce(                    Nully1,   Nully0, NullySpace       ));
        NoNullRet("1",  Coalesce(zeroMatters: false, Nully1,   Nully0, NullySpace       ));
        NoNullRet("1",  Coalesce(             false, Nully1,   Nully0, NullySpace       ));
        NoNullRet("1",  Coalesce(zeroMatters       , Nully1,   Nully0, NullySpace       ));
        NoNullRet("1",  Coalesce(zeroMatters: true , Nully1,   Nully0, NullySpace       ));
        NoNullRet("1",  Coalesce(             true , Nully1,   Nully0, NullySpace       ));
        NoNullRet("1",  Coalesce(                    Nully1,   Nully0, NullyFilledText  ));
        NoNullRet("1",  Coalesce(zeroMatters: false, Nully1,   Nully0, NullyFilledText  ));
        NoNullRet("1",  Coalesce(             false, Nully1,   Nully0, NullyFilledText  ));
        NoNullRet("1",  Coalesce(zeroMatters       , Nully1,   Nully0, NullyFilledText  ));
        NoNullRet("1",  Coalesce(zeroMatters: true , Nully1,   Nully0, NullyFilledText  ));
        NoNullRet("1",  Coalesce(             true , Nully1,   Nully0, NullyFilledText  ));
        NoNullRet("1",  Coalesce(                    Nully1,        0, NullText         ));
        NoNullRet("1",  Coalesce(zeroMatters: false, Nully1,        0, NullText         ));
        NoNullRet("1",  Coalesce(             false, Nully1,        0, NullText         ));
        NoNullRet("1",  Coalesce(zeroMatters       , Nully1,        0, NullText         ));
        NoNullRet("1",  Coalesce(zeroMatters: true , Nully1,        0, NullText         ));
        NoNullRet("1",  Coalesce(             true , Nully1,        0, NullText         ));
        NoNullRet("1",  Coalesce(                    Nully1,        0, Empty            ));
        NoNullRet("1",  Coalesce(zeroMatters: false, Nully1,        0, Empty            ));
        NoNullRet("1",  Coalesce(             false, Nully1,        0, Empty            ));
        NoNullRet("1",  Coalesce(zeroMatters       , Nully1,        0, Empty            ));
        NoNullRet("1",  Coalesce(zeroMatters: true , Nully1,        0, Empty            ));
        NoNullRet("1",  Coalesce(             true , Nully1,        0, Empty            ));
        NoNullRet("1",  Coalesce(                    Nully1,        0, Space            ));
        NoNullRet("1",  Coalesce(zeroMatters: false, Nully1,        0, Space            ));
        NoNullRet("1",  Coalesce(             false, Nully1,        0, Space            ));
        NoNullRet("1",  Coalesce(zeroMatters       , Nully1,        0, Space            ));
        NoNullRet("1",  Coalesce(zeroMatters: true , Nully1,        0, Space            ));
        NoNullRet("1",  Coalesce(             true , Nully1,        0, Space            ));
        NoNullRet("1",  Coalesce(                    Nully1,        0, Text             ));
        NoNullRet("1",  Coalesce(zeroMatters: false, Nully1,        0, Text             ));
        NoNullRet("1",  Coalesce(             false, Nully1,        0, Text             ));
        NoNullRet("1",  Coalesce(zeroMatters       , Nully1,        0, Text             ));
        NoNullRet("1",  Coalesce(zeroMatters: true , Nully1,        0, Text             ));
        NoNullRet("1",  Coalesce(             true , Nully1,        0, Text             ));
        NoNullRet("1",  Coalesce(                    Nully1,        0, NullyEmpty       ));
        NoNullRet("1",  Coalesce(zeroMatters: false, Nully1,        0, NullyEmpty       ));
        NoNullRet("1",  Coalesce(             false, Nully1,        0, NullyEmpty       ));
        NoNullRet("1",  Coalesce(zeroMatters       , Nully1,        0, NullyEmpty       ));
        NoNullRet("1",  Coalesce(zeroMatters: true , Nully1,        0, NullyEmpty       ));
        NoNullRet("1",  Coalesce(             true , Nully1,        0, NullyEmpty       ));
        NoNullRet("1",  Coalesce(                    Nully1,        0, NullySpace       ));
        NoNullRet("1",  Coalesce(zeroMatters: false, Nully1,        0, NullySpace       ));
        NoNullRet("1",  Coalesce(             false, Nully1,        0, NullySpace       ));
        NoNullRet("1",  Coalesce(zeroMatters       , Nully1,        0, NullySpace       ));
        NoNullRet("1",  Coalesce(zeroMatters: true , Nully1,        0, NullySpace       ));
        NoNullRet("1",  Coalesce(             true , Nully1,        0, NullySpace       ));
        NoNullRet("1",  Coalesce(                    Nully1,        0, NullyFilledText  ));
        NoNullRet("1",  Coalesce(zeroMatters: false, Nully1,        0, NullyFilledText  ));
        NoNullRet("1",  Coalesce(             false, Nully1,        0, NullyFilledText  ));
        NoNullRet("1",  Coalesce(zeroMatters       , Nully1,        0, NullyFilledText  ));
        NoNullRet("1",  Coalesce(zeroMatters: true , Nully1,        0, NullyFilledText  ));
        NoNullRet("1",  Coalesce(             true , Nully1,        0, NullyFilledText  ));
    }

    [TestMethod]
    public void Coalesce_3Args_BoolToText_StaticZeroMattersFlagsInFront_Batch4()
    {
        NoNullRet("",   Coalesce(                    0,       NullNum, NullText         ));
        NoNullRet("",   Coalesce(zeroMatters: false, 0,       NullNum, NullText         ));
        NoNullRet("",   Coalesce(             false, 0,       NullNum, NullText         ));
        NoNullRet("0",  Coalesce(zeroMatters       , 0,       NullNum, NullText         ));
        NoNullRet("0",  Coalesce(zeroMatters: true , 0,       NullNum, NullText         ));
        NoNullRet("0",  Coalesce(             true , 0,       NullNum, NullText         ));
        NoNullRet("",   Coalesce(                    0,       NullNum, Empty            ));
        NoNullRet("",   Coalesce(zeroMatters: false, 0,       NullNum, Empty            ));
        NoNullRet("",   Coalesce(             false, 0,       NullNum, Empty            ));
        NoNullRet("0",  Coalesce(zeroMatters       , 0,       NullNum, Empty            ));
        NoNullRet("0",  Coalesce(zeroMatters: true , 0,       NullNum, Empty            ));
        NoNullRet("0",  Coalesce(             true , 0,       NullNum, Empty            ));
        NoNullRet(" ",  Coalesce(                    0,       NullNum, Space            ));
        NoNullRet(" ",  Coalesce(zeroMatters: false, 0,       NullNum, Space            ));
        NoNullRet(" ",  Coalesce(             false, 0,       NullNum, Space            ));
        NoNullRet("0",  Coalesce(zeroMatters       , 0,       NullNum, Space            ));
        NoNullRet("0",  Coalesce(zeroMatters: true , 0,       NullNum, Space            ));
        NoNullRet("0",  Coalesce(             true , 0,       NullNum, Space            ));
        NoNullRet(Text, Coalesce(                    0,       NullNum, Text             ));
        NoNullRet(Text, Coalesce(zeroMatters: false, 0,       NullNum, Text             ));
        NoNullRet(Text, Coalesce(             false, 0,       NullNum, Text             ));
        NoNullRet("0",  Coalesce(zeroMatters       , 0,       NullNum, Text             ));
        NoNullRet("0",  Coalesce(zeroMatters: true , 0,       NullNum, Text             ));
        NoNullRet("0",  Coalesce(             true , 0,       NullNum, Text             ));
        NoNullRet("",   Coalesce(                    0,       NullNum, NullyEmpty       ));
        NoNullRet("",   Coalesce(zeroMatters: false, 0,       NullNum, NullyEmpty       ));
        NoNullRet("",   Coalesce(             false, 0,       NullNum, NullyEmpty       ));
        NoNullRet("0",  Coalesce(zeroMatters       , 0,       NullNum, NullyEmpty       ));
        NoNullRet("0",  Coalesce(zeroMatters: true , 0,       NullNum, NullyEmpty       ));
        NoNullRet("0",  Coalesce(             true , 0,       NullNum, NullyEmpty       ));
        NoNullRet(" ",  Coalesce(                    0,       NullNum, NullySpace       ));
        NoNullRet(" ",  Coalesce(zeroMatters: false, 0,       NullNum, NullySpace       ));
        NoNullRet(" ",  Coalesce(             false, 0,       NullNum, NullySpace       ));
        NoNullRet("0",  Coalesce(zeroMatters       , 0,       NullNum, NullySpace       ));
        NoNullRet("0",  Coalesce(zeroMatters: true , 0,       NullNum, NullySpace       ));
        NoNullRet("0",  Coalesce(             true , 0,       NullNum, NullySpace       ));
        NoNullRet(Text, Coalesce(                    0,       NullNum, NullyFilledText  ));
        NoNullRet(Text, Coalesce(zeroMatters: false, 0,       NullNum, NullyFilledText  ));
        NoNullRet(Text, Coalesce(             false, 0,       NullNum, NullyFilledText  ));
        NoNullRet("0",  Coalesce(zeroMatters       , 0,       NullNum, NullyFilledText  ));
        NoNullRet("0",  Coalesce(zeroMatters: true , 0,       NullNum, NullyFilledText  ));
        NoNullRet("0",  Coalesce(             true , 0,       NullNum, NullyFilledText  ));
        NoNullRet("1",  Coalesce(                    0,        Nully1, NullText         ));
        NoNullRet("1",  Coalesce(zeroMatters: false, 0,        Nully1, NullText         ));
        NoNullRet("1",  Coalesce(             false, 0,        Nully1, NullText         ));
        NoNullRet("0",  Coalesce(zeroMatters       , 0,        Nully1, NullText         ));
        NoNullRet("0",  Coalesce(zeroMatters: true , 0,        Nully1, NullText         ));
        NoNullRet("0",  Coalesce(             true , 0,        Nully1, NullText         ));
        NoNullRet("1",  Coalesce(                    0,        Nully1, Empty            ));
        NoNullRet("1",  Coalesce(zeroMatters: false, 0,        Nully1, Empty            ));
        NoNullRet("1",  Coalesce(             false, 0,        Nully1, Empty            ));
        NoNullRet("0",  Coalesce(zeroMatters       , 0,        Nully1, Empty            ));
        NoNullRet("0",  Coalesce(zeroMatters: true , 0,        Nully1, Empty            ));
        NoNullRet("0",  Coalesce(             true , 0,        Nully1, Empty            ));
        NoNullRet("1",  Coalesce(                    0,        Nully1, Space            ));
        NoNullRet("1",  Coalesce(zeroMatters: false, 0,        Nully1, Space            ));
        NoNullRet("1",  Coalesce(             false, 0,        Nully1, Space            ));
        NoNullRet("0",  Coalesce(zeroMatters       , 0,        Nully1, Space            ));
        NoNullRet("0",  Coalesce(zeroMatters: true , 0,        Nully1, Space            ));
        NoNullRet("0",  Coalesce(             true , 0,        Nully1, Space            ));
        NoNullRet("1",  Coalesce(                    0,        Nully1, Text             ));
        NoNullRet("1",  Coalesce(zeroMatters: false, 0,        Nully1, Text             ));
        NoNullRet("1",  Coalesce(             false, 0,        Nully1, Text             ));
        NoNullRet("0",  Coalesce(zeroMatters       , 0,        Nully1, Text             ));
        NoNullRet("0",  Coalesce(zeroMatters: true , 0,        Nully1, Text             ));
        NoNullRet("0",  Coalesce(             true , 0,        Nully1, Text             ));
        NoNullRet("1",  Coalesce(                    0,        Nully1, NullyEmpty       ));
        NoNullRet("1",  Coalesce(zeroMatters: false, 0,        Nully1, NullyEmpty       ));
        NoNullRet("1",  Coalesce(             false, 0,        Nully1, NullyEmpty       ));
        NoNullRet("0",  Coalesce(zeroMatters       , 0,        Nully1, NullyEmpty       ));
        NoNullRet("0",  Coalesce(zeroMatters: true , 0,        Nully1, NullyEmpty       ));
        NoNullRet("0",  Coalesce(             true , 0,        Nully1, NullyEmpty       ));
        NoNullRet("1",  Coalesce(                    0,        Nully1, NullySpace       ));
        NoNullRet("1",  Coalesce(zeroMatters: false, 0,        Nully1, NullySpace       ));
        NoNullRet("1",  Coalesce(             false, 0,        Nully1, NullySpace       ));
        NoNullRet("0",  Coalesce(zeroMatters       , 0,        Nully1, NullySpace       ));
        NoNullRet("0",  Coalesce(zeroMatters: true , 0,        Nully1, NullySpace       ));
        NoNullRet("0",  Coalesce(             true , 0,        Nully1, NullySpace       ));
        NoNullRet("1",  Coalesce(                    0,        Nully1, NullyFilledText  ));
        NoNullRet("1",  Coalesce(zeroMatters: false, 0,        Nully1, NullyFilledText  ));
        NoNullRet("1",  Coalesce(             false, 0,        Nully1, NullyFilledText  ));
        NoNullRet("0",  Coalesce(zeroMatters       , 0,        Nully1, NullyFilledText  ));
        NoNullRet("0",  Coalesce(zeroMatters: true , 0,        Nully1, NullyFilledText  ));
        NoNullRet("0",  Coalesce(             true , 0,        Nully1, NullyFilledText  ));
        NoNullRet("1",  Coalesce(                    0,             1, NullText         ));
        NoNullRet("1",  Coalesce(zeroMatters: false, 0,             1, NullText         ));
        NoNullRet("1",  Coalesce(             false, 0,             1, NullText         ));
        NoNullRet("0",  Coalesce(zeroMatters       , 0,             1, NullText         ));
        NoNullRet("0",  Coalesce(zeroMatters: true , 0,             1, NullText         ));
        NoNullRet("0",  Coalesce(             true , 0,             1, NullText         ));
        NoNullRet("1",  Coalesce(                    0,             1, Empty            ));
        NoNullRet("1",  Coalesce(zeroMatters: false, 0,             1, Empty            ));
        NoNullRet("1",  Coalesce(             false, 0,             1, Empty            ));
        NoNullRet("0",  Coalesce(zeroMatters       , 0,             1, Empty            ));
        NoNullRet("0",  Coalesce(zeroMatters: true , 0,             1, Empty            ));
        NoNullRet("0",  Coalesce(             true , 0,             1, Empty            ));
        NoNullRet("1",  Coalesce(                    0,             1, Space            ));
        NoNullRet("1",  Coalesce(zeroMatters: false, 0,             1, Space            ));
        NoNullRet("1",  Coalesce(             false, 0,             1, Space            ));
        NoNullRet("0",  Coalesce(zeroMatters       , 0,             1, Space            ));
        NoNullRet("0",  Coalesce(zeroMatters: true , 0,             1, Space            ));
        NoNullRet("0",  Coalesce(             true , 0,             1, Space            ));
        NoNullRet("1",  Coalesce(                    0,             1, Text             ));
        NoNullRet("1",  Coalesce(zeroMatters: false, 0,             1, Text             ));
        NoNullRet("1",  Coalesce(             false, 0,             1, Text             ));
        NoNullRet("0",  Coalesce(zeroMatters       , 0,             1, Text             ));
        NoNullRet("0",  Coalesce(zeroMatters: true , 0,             1, Text             ));
        NoNullRet("0",  Coalesce(             true , 0,             1, Text             ));
        NoNullRet("1",  Coalesce(                    0,             1, NullyEmpty       ));
        NoNullRet("1",  Coalesce(zeroMatters: false, 0,             1, NullyEmpty       ));
        NoNullRet("1",  Coalesce(             false, 0,             1, NullyEmpty       ));
        NoNullRet("0",  Coalesce(zeroMatters       , 0,             1, NullyEmpty       ));
        NoNullRet("0",  Coalesce(zeroMatters: true , 0,             1, NullyEmpty       ));
        NoNullRet("0",  Coalesce(             true , 0,             1, NullyEmpty       ));
        NoNullRet("1",  Coalesce(                    0,             1, NullySpace       ));
        NoNullRet("1",  Coalesce(zeroMatters: false, 0,             1, NullySpace       ));
        NoNullRet("1",  Coalesce(             false, 0,             1, NullySpace       ));
        NoNullRet("0",  Coalesce(zeroMatters       , 0,             1, NullySpace       ));
        NoNullRet("0",  Coalesce(zeroMatters: true , 0,             1, NullySpace       ));
        NoNullRet("0",  Coalesce(             true , 0,             1, NullySpace       ));
        NoNullRet("1",  Coalesce(                    0,             1, NullyFilledText  ));
        NoNullRet("1",  Coalesce(zeroMatters: false, 0,             1, NullyFilledText  ));
        NoNullRet("1",  Coalesce(             false, 0,             1, NullyFilledText  ));
        NoNullRet("0",  Coalesce(zeroMatters       , 0,             1, NullyFilledText  ));
        NoNullRet("0",  Coalesce(zeroMatters: true , 0,             1, NullyFilledText  ));
        NoNullRet("0",  Coalesce(             true , 0,             1, NullyFilledText  ));
    }

    [TestMethod]
    public void Coalesce_3Args_BoolToText_StaticZeroMattersFlagsInFront_Batch5()
    {
        NoNullRet("1",  Coalesce(                    1,       NullNum, NullText         ));
        NoNullRet("1",  Coalesce(zeroMatters: false, 1,       NullNum, NullText         ));
        NoNullRet("1",  Coalesce(             false, 1,       NullNum, NullText         ));
        NoNullRet("1",  Coalesce(zeroMatters       , 1,       NullNum, NullText         ));
        NoNullRet("1",  Coalesce(zeroMatters: true , 1,       NullNum, NullText         ));
        NoNullRet("1",  Coalesce(             true , 1,       NullNum, NullText         ));
        NoNullRet("1",  Coalesce(                    1,       NullNum, Empty            ));
        NoNullRet("1",  Coalesce(zeroMatters: false, 1,       NullNum, Empty            ));
        NoNullRet("1",  Coalesce(             false, 1,       NullNum, Empty            ));
        NoNullRet("1",  Coalesce(zeroMatters       , 1,       NullNum, Empty            ));
        NoNullRet("1",  Coalesce(zeroMatters: true , 1,       NullNum, Empty            ));
        NoNullRet("1",  Coalesce(             true , 1,       NullNum, Empty            ));
        NoNullRet("1",  Coalesce(                    1,       NullNum, Space            ));
        NoNullRet("1",  Coalesce(zeroMatters: false, 1,       NullNum, Space            ));
        NoNullRet("1",  Coalesce(             false, 1,       NullNum, Space            ));
        NoNullRet("1",  Coalesce(zeroMatters       , 1,       NullNum, Space            ));
        NoNullRet("1",  Coalesce(zeroMatters: true , 1,       NullNum, Space            ));
        NoNullRet("1",  Coalesce(             true , 1,       NullNum, Space            ));
        NoNullRet("1",  Coalesce(                    1,       NullNum, Text             ));
        NoNullRet("1",  Coalesce(zeroMatters: false, 1,       NullNum, Text             ));
        NoNullRet("1",  Coalesce(             false, 1,       NullNum, Text             ));
        NoNullRet("1",  Coalesce(zeroMatters       , 1,       NullNum, Text             ));
        NoNullRet("1",  Coalesce(zeroMatters: true , 1,       NullNum, Text             ));
        NoNullRet("1",  Coalesce(             true , 1,       NullNum, Text             ));
        NoNullRet("1",  Coalesce(                    1,       NullNum, NullyEmpty       ));
        NoNullRet("1",  Coalesce(zeroMatters: false, 1,       NullNum, NullyEmpty       ));
        NoNullRet("1",  Coalesce(             false, 1,       NullNum, NullyEmpty       ));
        NoNullRet("1",  Coalesce(zeroMatters       , 1,       NullNum, NullyEmpty       ));
        NoNullRet("1",  Coalesce(zeroMatters: true , 1,       NullNum, NullyEmpty       ));
        NoNullRet("1",  Coalesce(             true , 1,       NullNum, NullyEmpty       ));
        NoNullRet("1",  Coalesce(                    1,       NullNum, NullySpace       ));
        NoNullRet("1",  Coalesce(zeroMatters: false, 1,       NullNum, NullySpace       ));
        NoNullRet("1",  Coalesce(             false, 1,       NullNum, NullySpace       ));
        NoNullRet("1",  Coalesce(zeroMatters       , 1,       NullNum, NullySpace       ));
        NoNullRet("1",  Coalesce(zeroMatters: true , 1,       NullNum, NullySpace       ));
        NoNullRet("1",  Coalesce(             true , 1,       NullNum, NullySpace       ));
        NoNullRet("1",  Coalesce(                    1,       NullNum, NullyFilledText  ));
        NoNullRet("1",  Coalesce(zeroMatters: false, 1,       NullNum, NullyFilledText  ));
        NoNullRet("1",  Coalesce(             false, 1,       NullNum, NullyFilledText  ));
        NoNullRet("1",  Coalesce(zeroMatters       , 1,       NullNum, NullyFilledText  ));
        NoNullRet("1",  Coalesce(zeroMatters: true , 1,       NullNum, NullyFilledText  ));
        NoNullRet("1",  Coalesce(             true , 1,       NullNum, NullyFilledText  ));
        NoNullRet("1",  Coalesce(                    1,        Nully0, NullText         ));
        NoNullRet("1",  Coalesce(zeroMatters: false, 1,        Nully0, NullText         ));
        NoNullRet("1",  Coalesce(             false, 1,        Nully0, NullText         ));
        NoNullRet("1",  Coalesce(zeroMatters       , 1,        Nully0, NullText         ));
        NoNullRet("1",  Coalesce(zeroMatters: true , 1,        Nully0, NullText         ));
        NoNullRet("1",  Coalesce(             true , 1,        Nully0, NullText         ));
        NoNullRet("1",  Coalesce(                    1,        Nully0, Empty            ));
        NoNullRet("1",  Coalesce(zeroMatters: false, 1,        Nully0, Empty            ));
        NoNullRet("1",  Coalesce(             false, 1,        Nully0, Empty            ));
        NoNullRet("1",  Coalesce(zeroMatters       , 1,        Nully0, Empty            ));
        NoNullRet("1",  Coalesce(zeroMatters: true , 1,        Nully0, Empty            ));
        NoNullRet("1",  Coalesce(             true , 1,        Nully0, Empty            ));
        NoNullRet("1",  Coalesce(                    1,        Nully0, Space            ));
        NoNullRet("1",  Coalesce(zeroMatters: false, 1,        Nully0, Space            ));
        NoNullRet("1",  Coalesce(             false, 1,        Nully0, Space            ));
        NoNullRet("1",  Coalesce(zeroMatters       , 1,        Nully0, Space            ));
        NoNullRet("1",  Coalesce(zeroMatters: true , 1,        Nully0, Space            ));
        NoNullRet("1",  Coalesce(             true , 1,        Nully0, Space            ));
        NoNullRet("1",  Coalesce(                    1,        Nully0, Text             ));
        NoNullRet("1",  Coalesce(zeroMatters: false, 1,        Nully0, Text             ));
        NoNullRet("1",  Coalesce(             false, 1,        Nully0, Text             ));
        NoNullRet("1",  Coalesce(zeroMatters       , 1,        Nully0, Text             ));
        NoNullRet("1",  Coalesce(zeroMatters: true , 1,        Nully0, Text             ));
        NoNullRet("1",  Coalesce(             true , 1,        Nully0, Text             ));
        NoNullRet("1",  Coalesce(                    1,        Nully0, NullyEmpty       ));
        NoNullRet("1",  Coalesce(zeroMatters: false, 1,        Nully0, NullyEmpty       ));
        NoNullRet("1",  Coalesce(             false, 1,        Nully0, NullyEmpty       ));
        NoNullRet("1",  Coalesce(zeroMatters       , 1,        Nully0, NullyEmpty       ));
        NoNullRet("1",  Coalesce(zeroMatters: true , 1,        Nully0, NullyEmpty       ));
        NoNullRet("1",  Coalesce(             true , 1,        Nully0, NullyEmpty       ));
        NoNullRet("1",  Coalesce(                    1,        Nully0, NullySpace       ));
        NoNullRet("1",  Coalesce(zeroMatters: false, 1,        Nully0, NullySpace       ));
        NoNullRet("1",  Coalesce(             false, 1,        Nully0, NullySpace       ));
        NoNullRet("1",  Coalesce(zeroMatters       , 1,        Nully0, NullySpace       ));
        NoNullRet("1",  Coalesce(zeroMatters: true , 1,        Nully0, NullySpace       ));
        NoNullRet("1",  Coalesce(             true , 1,        Nully0, NullySpace       ));
        NoNullRet("1",  Coalesce(                    1,        Nully0, NullyFilledText  ));
        NoNullRet("1",  Coalesce(zeroMatters: false, 1,        Nully0, NullyFilledText  ));
        NoNullRet("1",  Coalesce(             false, 1,        Nully0, NullyFilledText  ));
        NoNullRet("1",  Coalesce(zeroMatters       , 1,        Nully0, NullyFilledText  ));
        NoNullRet("1",  Coalesce(zeroMatters: true , 1,        Nully0, NullyFilledText  ));
        NoNullRet("1",  Coalesce(             true , 1,        Nully0, NullyFilledText  ));
    }
}