namespace JJ.Framework.Existence.Core.Tests;

[TestClass]
public class Coalesce_3Args_BoolToText_StaticZeroMattersFlagsInBack : TestBase
{
    [TestMethod]
    public void Coalesce_3Args_BoolToText_StaticZeroMattersFlagsInBack_Batch1()
    {
        NoNullRet("",      Coalesce(NullBool,   NullyFalse, NullText                           ));
        NoNullRet("",      Coalesce(NullBool,   NullyFalse, NullText,        zeroMatters: false));
        NoNullRet("",      Coalesce(NullBool,   NullyFalse, NullText,                     false));
        NoNullRet("False", Coalesce(NullBool,   NullyFalse, NullText,        zeroMatters       ));
        NoNullRet("False", Coalesce(NullBool,   NullyFalse, NullText,        zeroMatters: true ));
        NoNullRet("False", Coalesce(NullBool,   NullyFalse, NullText,                     true ));
        NoNullRet("",      Coalesce(NullBool,   NullyFalse, Empty                              ));
        NoNullRet("",      Coalesce(NullBool,   NullyFalse, Empty,           zeroMatters: false));
        NoNullRet("",      Coalesce(NullBool,   NullyFalse, Empty,                        false));
        NoNullRet("False", Coalesce(NullBool,   NullyFalse, Empty,           zeroMatters       ));
        NoNullRet("False", Coalesce(NullBool,   NullyFalse, Empty,           zeroMatters: true ));
        NoNullRet("False", Coalesce(NullBool,   NullyFalse, Empty,                        true ));
        NoNullRet(" ",     Coalesce(NullBool,   NullyFalse, Space                              ));
        NoNullRet(" ",     Coalesce(NullBool,   NullyFalse, Space,           zeroMatters: false));
        NoNullRet(" ",     Coalesce(NullBool,   NullyFalse, Space,                        false));
        NoNullRet("False", Coalesce(NullBool,   NullyFalse, Space,           zeroMatters       ));
        NoNullRet("False", Coalesce(NullBool,   NullyFalse, Space,           zeroMatters: true ));
        NoNullRet("False", Coalesce(NullBool,   NullyFalse, Space,                        true ));
        NoNullRet(Text,    Coalesce(NullBool,   NullyFalse, Text                               ));
        NoNullRet(Text,    Coalesce(NullBool,   NullyFalse, Text,            zeroMatters: false));
        NoNullRet(Text,    Coalesce(NullBool,   NullyFalse, Text,                         false));
        NoNullRet("False", Coalesce(NullBool,   NullyFalse, Text,            zeroMatters       ));
        NoNullRet("False", Coalesce(NullBool,   NullyFalse, Text,            zeroMatters: true ));
        NoNullRet("False", Coalesce(NullBool,   NullyFalse, Text,                         true ));
        NoNullRet("",      Coalesce(NullBool,   NullyFalse, NullyEmpty                         ));
        NoNullRet("",      Coalesce(NullBool,   NullyFalse, NullyEmpty,      zeroMatters: false));
        NoNullRet("",      Coalesce(NullBool,   NullyFalse, NullyEmpty,                   false));
        NoNullRet("False", Coalesce(NullBool,   NullyFalse, NullyEmpty,      zeroMatters       ));
        NoNullRet("False", Coalesce(NullBool,   NullyFalse, NullyEmpty,      zeroMatters: true ));
        NoNullRet("False", Coalesce(NullBool,   NullyFalse, NullyEmpty,                   true ));
        NoNullRet(" ",     Coalesce(NullBool,   NullyFalse, NullySpace                         ));
        NoNullRet(" ",     Coalesce(NullBool,   NullyFalse, NullySpace,      zeroMatters: false));
        NoNullRet(" ",     Coalesce(NullBool,   NullyFalse, NullySpace,                   false));
        NoNullRet("False", Coalesce(NullBool,   NullyFalse, NullySpace,      zeroMatters       ));
        NoNullRet("False", Coalesce(NullBool,   NullyFalse, NullySpace,      zeroMatters: true ));
        NoNullRet("False", Coalesce(NullBool,   NullyFalse, NullySpace,                   true ));
        NoNullRet(Text,    Coalesce(NullBool,   NullyFalse, NullyFilledText                    ));
        NoNullRet(Text,    Coalesce(NullBool,   NullyFalse, NullyFilledText, zeroMatters: false));
        NoNullRet(Text,    Coalesce(NullBool,   NullyFalse, NullyFilledText,              false));
        NoNullRet("False", Coalesce(NullBool,   NullyFalse, NullyFilledText, zeroMatters       ));
        NoNullRet("False", Coalesce(NullBool,   NullyFalse, NullyFilledText, zeroMatters: true ));
        NoNullRet("False", Coalesce(NullBool,   NullyFalse, NullyFilledText,              true ));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  NullText                           ));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  NullText,        zeroMatters: false));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  NullText,                     false));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  NullText,        zeroMatters       ));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  NullText,        zeroMatters: true ));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  NullText,                     true ));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  Empty                              ));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  Empty,           zeroMatters: false));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  Empty,                        false));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  Empty,           zeroMatters       ));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  Empty,           zeroMatters: true ));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  Empty,                        true ));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  Space                              ));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  Space,           zeroMatters: false));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  Space,                        false));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  Space,           zeroMatters       ));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  Space,           zeroMatters: true ));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  Space,                        true ));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  Text                               ));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  Text,            zeroMatters: false));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  Text,                         false));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  Text,            zeroMatters       ));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  Text,            zeroMatters: true ));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  Text,                         true ));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  NullyEmpty                         ));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  NullyEmpty,      zeroMatters: false));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  NullyEmpty,                   false));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  NullyEmpty,      zeroMatters       ));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  NullyEmpty,      zeroMatters: true ));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  NullyEmpty,                   true ));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  NullySpace                         ));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  NullySpace,      zeroMatters: false));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  NullySpace,                   false));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  NullySpace,      zeroMatters       ));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  NullySpace,      zeroMatters: true ));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  NullySpace,                   true ));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  NullyFilledText                    ));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  NullyFilledText, zeroMatters: false));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  NullyFilledText,              false));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  NullyFilledText, zeroMatters       ));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  NullyFilledText, zeroMatters: true ));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  NullyFilledText,              true ));
        NoNullRet("",      Coalesce(NullBool,   false,      NullText                           ));
        NoNullRet("",      Coalesce(NullBool,   false,      NullText,        zeroMatters: false));
        NoNullRet("",      Coalesce(NullBool,   false,      NullText,                     false));
        NoNullRet("False", Coalesce(NullBool,   false,      NullText,        zeroMatters       ));
        NoNullRet("False", Coalesce(NullBool,   false,      NullText,        zeroMatters: true ));
        NoNullRet("False", Coalesce(NullBool,   false,      NullText,                     true ));
        NoNullRet("",      Coalesce(NullBool,   false,      Empty                              ));
        NoNullRet("",      Coalesce(NullBool,   false,      Empty,           zeroMatters: false));
        NoNullRet("",      Coalesce(NullBool,   false,      Empty,                        false));
        NoNullRet("False", Coalesce(NullBool,   false,      Empty,           zeroMatters       ));
        NoNullRet("False", Coalesce(NullBool,   false,      Empty,           zeroMatters: true ));
        NoNullRet("False", Coalesce(NullBool,   false,      Empty,                        true ));
        NoNullRet(" ",     Coalesce(NullBool,   false,      Space                              ));
        NoNullRet(" ",     Coalesce(NullBool,   false,      Space,           zeroMatters: false));
        NoNullRet(" ",     Coalesce(NullBool,   false,      Space,                        false));
        NoNullRet("False", Coalesce(NullBool,   false,      Space,           zeroMatters       ));
        NoNullRet("False", Coalesce(NullBool,   false,      Space,           zeroMatters: true ));
        NoNullRet("False", Coalesce(NullBool,   false,      Space,                        true ));
        NoNullRet(Text,    Coalesce(NullBool,   false,      Text                               ));
        NoNullRet(Text,    Coalesce(NullBool,   false,      Text,            zeroMatters: false));
        NoNullRet(Text,    Coalesce(NullBool,   false,      Text,                         false));
        NoNullRet("False", Coalesce(NullBool,   false,      Text,            zeroMatters       ));
        NoNullRet("False", Coalesce(NullBool,   false,      Text,            zeroMatters: true ));
        NoNullRet("False", Coalesce(NullBool,   false,      Text,                         true ));
        NoNullRet("",      Coalesce(NullBool,   false,      NullyEmpty                         ));
        NoNullRet("",      Coalesce(NullBool,   false,      NullyEmpty,      zeroMatters: false));
        NoNullRet("",      Coalesce(NullBool,   false,      NullyEmpty,                   false));
        NoNullRet("False", Coalesce(NullBool,   false,      NullyEmpty,      zeroMatters       ));
        NoNullRet("False", Coalesce(NullBool,   false,      NullyEmpty,      zeroMatters: true ));
        NoNullRet("False", Coalesce(NullBool,   false,      NullyEmpty,                   true ));
        NoNullRet(" ",     Coalesce(NullBool,   false,      NullySpace                         ));
        NoNullRet(" ",     Coalesce(NullBool,   false,      NullySpace,      zeroMatters: false));
        NoNullRet(" ",     Coalesce(NullBool,   false,      NullySpace,                   false));
        NoNullRet("False", Coalesce(NullBool,   false,      NullySpace,      zeroMatters       ));
        NoNullRet("False", Coalesce(NullBool,   false,      NullySpace,      zeroMatters: true ));
        NoNullRet("False", Coalesce(NullBool,   false,      NullySpace,                   true ));
        NoNullRet(Text,    Coalesce(NullBool,   false,      NullyFilledText                    ));
        NoNullRet(Text,    Coalesce(NullBool,   false,      NullyFilledText, zeroMatters: false));
        NoNullRet(Text,    Coalesce(NullBool,   false,      NullyFilledText,              false));
        NoNullRet("False", Coalesce(NullBool,   false,      NullyFilledText, zeroMatters       ));
        NoNullRet("False", Coalesce(NullBool,   false,      NullyFilledText, zeroMatters: true ));
        NoNullRet("False", Coalesce(NullBool,   false,      NullyFilledText,              true ));
        NoNullRet("True",  Coalesce(NullBool,   true,       NullText                           ));
        NoNullRet("True",  Coalesce(NullBool,   true,       NullText,        zeroMatters: false));
        NoNullRet("True",  Coalesce(NullBool,   true,       NullText,                     false));
        NoNullRet("True",  Coalesce(NullBool,   true,       NullText,        zeroMatters       ));
        NoNullRet("True",  Coalesce(NullBool,   true,       NullText,        zeroMatters: true ));
        NoNullRet("True",  Coalesce(NullBool,   true,       NullText,                     true ));
        NoNullRet("True",  Coalesce(NullBool,   true,       Empty                              ));
        NoNullRet("True",  Coalesce(NullBool,   true,       Empty,           zeroMatters: false));
        NoNullRet("True",  Coalesce(NullBool,   true,       Empty,                        false));
        NoNullRet("True",  Coalesce(NullBool,   true,       Empty,           zeroMatters       ));
        NoNullRet("True",  Coalesce(NullBool,   true,       Empty,           zeroMatters: true ));
        NoNullRet("True",  Coalesce(NullBool,   true,       Empty,                        true ));
        NoNullRet("True",  Coalesce(NullBool,   true,       Space                              ));
        NoNullRet("True",  Coalesce(NullBool,   true,       Space,           zeroMatters: false));
        NoNullRet("True",  Coalesce(NullBool,   true,       Space,                        false));
        NoNullRet("True",  Coalesce(NullBool,   true,       Space,           zeroMatters       ));
        NoNullRet("True",  Coalesce(NullBool,   true,       Space,           zeroMatters: true ));
        NoNullRet("True",  Coalesce(NullBool,   true,       Space,                        true ));
        NoNullRet("True",  Coalesce(NullBool,   true,       Text                               ));
        NoNullRet("True",  Coalesce(NullBool,   true,       Text,            zeroMatters: false));
        NoNullRet("True",  Coalesce(NullBool,   true,       Text,                         false));
        NoNullRet("True",  Coalesce(NullBool,   true,       Text,            zeroMatters       ));
        NoNullRet("True",  Coalesce(NullBool,   true,       Text,            zeroMatters: true ));
        NoNullRet("True",  Coalesce(NullBool,   true,       Text,                         true ));
        NoNullRet("True",  Coalesce(NullBool,   true,       NullyEmpty                         ));
        NoNullRet("True",  Coalesce(NullBool,   true,       NullyEmpty,      zeroMatters: false));
        NoNullRet("True",  Coalesce(NullBool,   true,       NullyEmpty,                   false));
        NoNullRet("True",  Coalesce(NullBool,   true,       NullyEmpty,      zeroMatters       ));
        NoNullRet("True",  Coalesce(NullBool,   true,       NullyEmpty,      zeroMatters: true ));
        NoNullRet("True",  Coalesce(NullBool,   true,       NullyEmpty,                   true ));
        NoNullRet("True",  Coalesce(NullBool,   true,       NullySpace                         ));
        NoNullRet("True",  Coalesce(NullBool,   true,       NullySpace,      zeroMatters: false));
        NoNullRet("True",  Coalesce(NullBool,   true,       NullySpace,                   false));
        NoNullRet("True",  Coalesce(NullBool,   true,       NullySpace,      zeroMatters       ));
        NoNullRet("True",  Coalesce(NullBool,   true,       NullySpace,      zeroMatters: true ));
        NoNullRet("True",  Coalesce(NullBool,   true,       NullySpace,                   true ));
        NoNullRet("True",  Coalesce(NullBool,   true,       NullyFilledText                    ));
        NoNullRet("True",  Coalesce(NullBool,   true,       NullyFilledText, zeroMatters: false));
        NoNullRet("True",  Coalesce(NullBool,   true,       NullyFilledText,              false));
        NoNullRet("True",  Coalesce(NullBool,   true,       NullyFilledText, zeroMatters       ));
        NoNullRet("True",  Coalesce(NullBool,   true,       NullyFilledText, zeroMatters: true ));
        NoNullRet("True",  Coalesce(NullBool,   true,       NullyFilledText,              true ));
    }

    [TestMethod]
    public void Coalesce_3Args_BoolToText_StaticZeroMattersFlagsInBack_Batch2()
    {
        NoNullRet("",      Coalesce(NullyFalse, NullBool,   NullText                           ));
        NoNullRet("",      Coalesce(NullyFalse, NullBool,   NullText,        zeroMatters: false));
        NoNullRet("",      Coalesce(NullyFalse, NullBool,   NullText,                     false));
        NoNullRet("False", Coalesce(NullyFalse, NullBool,   NullText,        zeroMatters       ));
        NoNullRet("False", Coalesce(NullyFalse, NullBool,   NullText,        zeroMatters: true ));
        NoNullRet("False", Coalesce(NullyFalse, NullBool,   NullText,                     true ));
        NoNullRet("",      Coalesce(NullyFalse, NullBool,   Empty                              ));
        NoNullRet("",      Coalesce(NullyFalse, NullBool,   Empty,           zeroMatters: false));
        NoNullRet("",      Coalesce(NullyFalse, NullBool,   Empty,                        false));
        NoNullRet("False", Coalesce(NullyFalse, NullBool,   Empty,           zeroMatters       ));
        NoNullRet("False", Coalesce(NullyFalse, NullBool,   Empty,           zeroMatters: true ));
        NoNullRet("False", Coalesce(NullyFalse, NullBool,   Empty,                        true ));
        NoNullRet(" ",     Coalesce(NullyFalse, NullBool,   Space                              ));
        NoNullRet(" ",     Coalesce(NullyFalse, NullBool,   Space,           zeroMatters: false));
        NoNullRet(" ",     Coalesce(NullyFalse, NullBool,   Space,                        false));
        NoNullRet("False", Coalesce(NullyFalse, NullBool,   Space,           zeroMatters       ));
        NoNullRet("False", Coalesce(NullyFalse, NullBool,   Space,           zeroMatters: true ));
        NoNullRet("False", Coalesce(NullyFalse, NullBool,   Space,                        true ));
        NoNullRet(Text,    Coalesce(NullyFalse, NullBool,   Text                               ));
        NoNullRet(Text,    Coalesce(NullyFalse, NullBool,   Text,            zeroMatters: false));
        NoNullRet(Text,    Coalesce(NullyFalse, NullBool,   Text,                         false));
        NoNullRet("False", Coalesce(NullyFalse, NullBool,   Text,            zeroMatters       ));
        NoNullRet("False", Coalesce(NullyFalse, NullBool,   Text,            zeroMatters: true ));
        NoNullRet("False", Coalesce(NullyFalse, NullBool,   Text,                         true ));
        NoNullRet("",      Coalesce(NullyFalse, NullBool,   NullyEmpty                         ));
        NoNullRet("",      Coalesce(NullyFalse, NullBool,   NullyEmpty,      zeroMatters: false));
        NoNullRet("",      Coalesce(NullyFalse, NullBool,   NullyEmpty,                   false));
        NoNullRet("False", Coalesce(NullyFalse, NullBool,   NullyEmpty,      zeroMatters       ));
        NoNullRet("False", Coalesce(NullyFalse, NullBool,   NullyEmpty,      zeroMatters: true ));
        NoNullRet("False", Coalesce(NullyFalse, NullBool,   NullyEmpty,                   true ));
        NoNullRet(" ",     Coalesce(NullyFalse, NullBool,   NullySpace                         ));
        NoNullRet(" ",     Coalesce(NullyFalse, NullBool,   NullySpace,      zeroMatters: false));
        NoNullRet(" ",     Coalesce(NullyFalse, NullBool,   NullySpace,                   false));
        NoNullRet("False", Coalesce(NullyFalse, NullBool,   NullySpace,      zeroMatters       ));
        NoNullRet("False", Coalesce(NullyFalse, NullBool,   NullySpace,      zeroMatters: true ));
        NoNullRet("False", Coalesce(NullyFalse, NullBool,   NullySpace,                   true ));
        NoNullRet(Text,    Coalesce(NullyFalse, NullBool,   NullyFilledText                    ));
        NoNullRet(Text,    Coalesce(NullyFalse, NullBool,   NullyFilledText, zeroMatters: false));
        NoNullRet(Text,    Coalesce(NullyFalse, NullBool,   NullyFilledText,              false));
        NoNullRet("False", Coalesce(NullyFalse, NullBool,   NullyFilledText, zeroMatters       ));
        NoNullRet("False", Coalesce(NullyFalse, NullBool,   NullyFilledText, zeroMatters: true ));
        NoNullRet("False", Coalesce(NullyFalse, NullBool,   NullyFilledText,              true ));
        NoNullRet("True",  Coalesce(NullyFalse, NullyTrue,  NullText                           ));
        NoNullRet("True",  Coalesce(NullyFalse, NullyTrue,  NullText,        zeroMatters: false));
        NoNullRet("True",  Coalesce(NullyFalse, NullyTrue,  NullText,                     false));
        NoNullRet("False", Coalesce(NullyFalse, NullyTrue,  NullText,        zeroMatters       ));
        NoNullRet("False", Coalesce(NullyFalse, NullyTrue,  NullText,        zeroMatters: true ));
        NoNullRet("False", Coalesce(NullyFalse, NullyTrue,  NullText,                     true ));
        NoNullRet("True",  Coalesce(NullyFalse, NullyTrue,  Empty                              ));
        NoNullRet("True",  Coalesce(NullyFalse, NullyTrue,  Empty,           zeroMatters: false));
        NoNullRet("True",  Coalesce(NullyFalse, NullyTrue,  Empty,                        false));
        NoNullRet("False", Coalesce(NullyFalse, NullyTrue,  Empty,           zeroMatters       ));
        NoNullRet("False", Coalesce(NullyFalse, NullyTrue,  Empty,           zeroMatters: true ));
        NoNullRet("False", Coalesce(NullyFalse, NullyTrue,  Empty,                        true ));
        NoNullRet("True",  Coalesce(NullyFalse, NullyTrue,  Space                              ));
        NoNullRet("True",  Coalesce(NullyFalse, NullyTrue,  Space,           zeroMatters: false));
        NoNullRet("True",  Coalesce(NullyFalse, NullyTrue,  Space,                        false));
        NoNullRet("False", Coalesce(NullyFalse, NullyTrue,  Space,           zeroMatters       ));
        NoNullRet("False", Coalesce(NullyFalse, NullyTrue,  Space,           zeroMatters: true ));
        NoNullRet("False", Coalesce(NullyFalse, NullyTrue,  Space,                        true ));
        NoNullRet("True",  Coalesce(NullyFalse, NullyTrue,  Text                               ));
        NoNullRet("True",  Coalesce(NullyFalse, NullyTrue,  Text,            zeroMatters: false));
        NoNullRet("True",  Coalesce(NullyFalse, NullyTrue,  Text,                         false));
        NoNullRet("False", Coalesce(NullyFalse, NullyTrue,  Text,            zeroMatters       ));
        NoNullRet("False", Coalesce(NullyFalse, NullyTrue,  Text,            zeroMatters: true ));
        NoNullRet("False", Coalesce(NullyFalse, NullyTrue,  Text,                         true ));
        NoNullRet("True",  Coalesce(NullyFalse, NullyTrue,  NullyEmpty                         ));
        NoNullRet("True",  Coalesce(NullyFalse, NullyTrue,  NullyEmpty,      zeroMatters: false));
        NoNullRet("True",  Coalesce(NullyFalse, NullyTrue,  NullyEmpty,                   false));
        NoNullRet("False", Coalesce(NullyFalse, NullyTrue,  NullyEmpty,      zeroMatters       ));
        NoNullRet("False", Coalesce(NullyFalse, NullyTrue,  NullyEmpty,      zeroMatters: true ));
        NoNullRet("False", Coalesce(NullyFalse, NullyTrue,  NullyEmpty,                   true ));
        NoNullRet("True",  Coalesce(NullyFalse, NullyTrue,  NullySpace                         ));
        NoNullRet("True",  Coalesce(NullyFalse, NullyTrue,  NullySpace,      zeroMatters: false));
        NoNullRet("True",  Coalesce(NullyFalse, NullyTrue,  NullySpace,                   false));
        NoNullRet("False", Coalesce(NullyFalse, NullyTrue,  NullySpace,      zeroMatters       ));
        NoNullRet("False", Coalesce(NullyFalse, NullyTrue,  NullySpace,      zeroMatters: true ));
        NoNullRet("False", Coalesce(NullyFalse, NullyTrue,  NullySpace,                   true ));
        NoNullRet("True",  Coalesce(NullyFalse, NullyTrue,  NullyFilledText                    ));
        NoNullRet("True",  Coalesce(NullyFalse, NullyTrue,  NullyFilledText, zeroMatters: false));
        NoNullRet("True",  Coalesce(NullyFalse, NullyTrue,  NullyFilledText,              false));
        NoNullRet("False", Coalesce(NullyFalse, NullyTrue,  NullyFilledText, zeroMatters       ));
        NoNullRet("False", Coalesce(NullyFalse, NullyTrue,  NullyFilledText, zeroMatters: true ));
        NoNullRet("False", Coalesce(NullyFalse, NullyTrue,  NullyFilledText,              true ));
        NoNullRet("True",  Coalesce(NullyFalse, true,       NullText                           ));
        NoNullRet("True",  Coalesce(NullyFalse, true,       NullText,        zeroMatters: false));
        NoNullRet("True",  Coalesce(NullyFalse, true,       NullText,                     false));
        NoNullRet("False", Coalesce(NullyFalse, true,       NullText,        zeroMatters       ));
        NoNullRet("False", Coalesce(NullyFalse, true,       NullText,        zeroMatters: true ));
        NoNullRet("False", Coalesce(NullyFalse, true,       NullText,                     true ));
        NoNullRet("True",  Coalesce(NullyFalse, true,       Empty                              ));
        NoNullRet("True",  Coalesce(NullyFalse, true,       Empty,           zeroMatters: false));
        NoNullRet("True",  Coalesce(NullyFalse, true,       Empty,                        false));
        NoNullRet("False", Coalesce(NullyFalse, true,       Empty,           zeroMatters       ));
        NoNullRet("False", Coalesce(NullyFalse, true,       Empty,           zeroMatters: true ));
        NoNullRet("False", Coalesce(NullyFalse, true,       Empty,                        true ));
        NoNullRet("True",  Coalesce(NullyFalse, true,       Space                              ));
        NoNullRet("True",  Coalesce(NullyFalse, true,       Space,           zeroMatters: false));
        NoNullRet("True",  Coalesce(NullyFalse, true,       Space,                        false));
        NoNullRet("False", Coalesce(NullyFalse, true,       Space,           zeroMatters       ));
        NoNullRet("False", Coalesce(NullyFalse, true,       Space,           zeroMatters: true ));
        NoNullRet("False", Coalesce(NullyFalse, true,       Space,                        true ));
        NoNullRet("True",  Coalesce(NullyFalse, true,       Text                               ));
        NoNullRet("True",  Coalesce(NullyFalse, true,       Text,            zeroMatters: false));
        NoNullRet("True",  Coalesce(NullyFalse, true,       Text,                         false));
        NoNullRet("False", Coalesce(NullyFalse, true,       Text,            zeroMatters       ));
        NoNullRet("False", Coalesce(NullyFalse, true,       Text,            zeroMatters: true ));
        NoNullRet("False", Coalesce(NullyFalse, true,       Text,                         true ));
        NoNullRet("True",  Coalesce(NullyFalse, true,       NullyEmpty                         ));
        NoNullRet("True",  Coalesce(NullyFalse, true,       NullyEmpty,      zeroMatters: false));
        NoNullRet("True",  Coalesce(NullyFalse, true,       NullyEmpty,                   false));
        NoNullRet("False", Coalesce(NullyFalse, true,       NullyEmpty,      zeroMatters       ));
        NoNullRet("False", Coalesce(NullyFalse, true,       NullyEmpty,      zeroMatters: true ));
        NoNullRet("False", Coalesce(NullyFalse, true,       NullyEmpty,                   true ));
        NoNullRet("True",  Coalesce(NullyFalse, true,       NullySpace                         ));
        NoNullRet("True",  Coalesce(NullyFalse, true,       NullySpace,      zeroMatters: false));
        NoNullRet("True",  Coalesce(NullyFalse, true,       NullySpace,                   false));
        NoNullRet("False", Coalesce(NullyFalse, true,       NullySpace,      zeroMatters       ));
        NoNullRet("False", Coalesce(NullyFalse, true,       NullySpace,      zeroMatters: true ));
        NoNullRet("False", Coalesce(NullyFalse, true,       NullySpace,                   true ));
        NoNullRet("True",  Coalesce(NullyFalse, true,       NullyFilledText                    ));
        NoNullRet("True",  Coalesce(NullyFalse, true,       NullyFilledText, zeroMatters: false));
        NoNullRet("True",  Coalesce(NullyFalse, true,       NullyFilledText,              false));
        NoNullRet("False", Coalesce(NullyFalse, true,       NullyFilledText, zeroMatters       ));
        NoNullRet("False", Coalesce(NullyFalse, true,       NullyFilledText, zeroMatters: true ));
        NoNullRet("False", Coalesce(NullyFalse, true,       NullyFilledText,              true ));
    }

    [TestMethod]
    public void Coalesce_3Args_BoolToText_StaticZeroMattersFlagsInBack_Batch3()
    {
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   NullText                           ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   NullText,        zeroMatters: false));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   NullText,                     false));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   NullText,        zeroMatters       ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   NullText,        zeroMatters: true ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   NullText,                     true ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   Empty                              ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   Empty,           zeroMatters: false));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   Empty,                        false));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   Empty,           zeroMatters       ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   Empty,           zeroMatters: true ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   Empty,                        true ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   Space                              ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   Space,           zeroMatters: false));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   Space,                        false));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   Space,           zeroMatters       ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   Space,           zeroMatters: true ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   Space,                        true ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   Text                               ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   Text,            zeroMatters: false));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   Text,                         false));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   Text,            zeroMatters       ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   Text,            zeroMatters: true ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   Text,                         true ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   NullyEmpty                         ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   NullyEmpty,      zeroMatters: false));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   NullyEmpty,                   false));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   NullyEmpty,      zeroMatters       ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   NullyEmpty,      zeroMatters: true ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   NullyEmpty,                   true ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   NullySpace                         ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   NullySpace,      zeroMatters: false));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   NullySpace,                   false));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   NullySpace,      zeroMatters       ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   NullySpace,      zeroMatters: true ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   NullySpace,                   true ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   NullyFilledText                    ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   NullyFilledText, zeroMatters: false));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   NullyFilledText,              false));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   NullyFilledText, zeroMatters       ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   NullyFilledText, zeroMatters: true ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   NullyFilledText,              true ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, NullText                           ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, NullText,        zeroMatters: false));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, NullText,                     false));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, NullText,        zeroMatters       ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, NullText,        zeroMatters: true ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, NullText,                     true ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, Empty                              ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, Empty,           zeroMatters: false));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, Empty,                        false));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, Empty,           zeroMatters       ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, Empty,           zeroMatters: true ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, Empty,                        true ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, Space                              ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, Space,           zeroMatters: false));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, Space,                        false));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, Space,           zeroMatters       ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, Space,           zeroMatters: true ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, Space,                        true ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, Text                               ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, Text,            zeroMatters: false));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, Text,                         false));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, Text,            zeroMatters       ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, Text,            zeroMatters: true ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, Text,                         true ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, NullyEmpty                         ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, NullyEmpty,      zeroMatters: false));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, NullyEmpty,                   false));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, NullyEmpty,      zeroMatters       ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, NullyEmpty,      zeroMatters: true ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, NullyEmpty,                   true ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, NullySpace                         ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, NullySpace,      zeroMatters: false));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, NullySpace,                   false));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, NullySpace,      zeroMatters       ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, NullySpace,      zeroMatters: true ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, NullySpace,                   true ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, NullyFilledText                    ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, NullyFilledText, zeroMatters: false));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, NullyFilledText,              false));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, NullyFilledText, zeroMatters       ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, NullyFilledText, zeroMatters: true ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, NullyFilledText,              true ));
        NoNullRet("True",  Coalesce(NullyTrue,  false,      NullText                           ));
        NoNullRet("True",  Coalesce(NullyTrue,  false,      NullText,        zeroMatters: false));
        NoNullRet("True",  Coalesce(NullyTrue,  false,      NullText,                     false));
        NoNullRet("True",  Coalesce(NullyTrue,  false,      NullText,        zeroMatters       ));
        NoNullRet("True",  Coalesce(NullyTrue,  false,      NullText,        zeroMatters: true ));
        NoNullRet("True",  Coalesce(NullyTrue,  false,      NullText,                     true ));
        NoNullRet("True",  Coalesce(NullyTrue,  false,      Empty                              ));
        NoNullRet("True",  Coalesce(NullyTrue,  false,      Empty,           zeroMatters: false));
        NoNullRet("True",  Coalesce(NullyTrue,  false,      Empty,                        false));
        NoNullRet("True",  Coalesce(NullyTrue,  false,      Empty,           zeroMatters       ));
        NoNullRet("True",  Coalesce(NullyTrue,  false,      Empty,           zeroMatters: true ));
        NoNullRet("True",  Coalesce(NullyTrue,  false,      Empty,                        true ));
        NoNullRet("True",  Coalesce(NullyTrue,  false,      Space                              ));
        NoNullRet("True",  Coalesce(NullyTrue,  false,      Space,           zeroMatters: false));
        NoNullRet("True",  Coalesce(NullyTrue,  false,      Space,                        false));
        NoNullRet("True",  Coalesce(NullyTrue,  false,      Space,           zeroMatters       ));
        NoNullRet("True",  Coalesce(NullyTrue,  false,      Space,           zeroMatters: true ));
        NoNullRet("True",  Coalesce(NullyTrue,  false,      Space,                        true ));
        NoNullRet("True",  Coalesce(NullyTrue,  false,      Text                               ));
        NoNullRet("True",  Coalesce(NullyTrue,  false,      Text,            zeroMatters: false));
        NoNullRet("True",  Coalesce(NullyTrue,  false,      Text,                         false));
        NoNullRet("True",  Coalesce(NullyTrue,  false,      Text,            zeroMatters       ));
        NoNullRet("True",  Coalesce(NullyTrue,  false,      Text,            zeroMatters: true ));
        NoNullRet("True",  Coalesce(NullyTrue,  false,      Text,                         true ));
        NoNullRet("True",  Coalesce(NullyTrue,  false,      NullyEmpty                         ));
        NoNullRet("True",  Coalesce(NullyTrue,  false,      NullyEmpty,      zeroMatters: false));
        NoNullRet("True",  Coalesce(NullyTrue,  false,      NullyEmpty,                   false));
        NoNullRet("True",  Coalesce(NullyTrue,  false,      NullyEmpty,      zeroMatters       ));
        NoNullRet("True",  Coalesce(NullyTrue,  false,      NullyEmpty,      zeroMatters: true ));
        NoNullRet("True",  Coalesce(NullyTrue,  false,      NullyEmpty,                   true ));
        NoNullRet("True",  Coalesce(NullyTrue,  false,      NullySpace                         ));
        NoNullRet("True",  Coalesce(NullyTrue,  false,      NullySpace,      zeroMatters: false));
        NoNullRet("True",  Coalesce(NullyTrue,  false,      NullySpace,                   false));
        NoNullRet("True",  Coalesce(NullyTrue,  false,      NullySpace,      zeroMatters       ));
        NoNullRet("True",  Coalesce(NullyTrue,  false,      NullySpace,      zeroMatters: true ));
        NoNullRet("True",  Coalesce(NullyTrue,  false,      NullySpace,                   true ));
        NoNullRet("True",  Coalesce(NullyTrue,  false,      NullyFilledText                    ));
        NoNullRet("True",  Coalesce(NullyTrue,  false,      NullyFilledText, zeroMatters: false));
        NoNullRet("True",  Coalesce(NullyTrue,  false,      NullyFilledText,              false));
        NoNullRet("True",  Coalesce(NullyTrue,  false,      NullyFilledText, zeroMatters       ));
        NoNullRet("True",  Coalesce(NullyTrue,  false,      NullyFilledText, zeroMatters: true ));
        NoNullRet("True",  Coalesce(NullyTrue,  false,      NullyFilledText,              true ));
    }

    [TestMethod]
    public void Coalesce_3Args_BoolToText_StaticZeroMattersFlagsInBack_Batch4()
    {
        NoNullRet("",      Coalesce(false,       NullBool,   NullText                           ));
        NoNullRet("",      Coalesce(false,       NullBool,   NullText,        zeroMatters: false));
        NoNullRet("",      Coalesce(false,       NullBool,   NullText,                     false));
        NoNullRet("False", Coalesce(false,       NullBool,   NullText,        zeroMatters       ));
        NoNullRet("False", Coalesce(false,       NullBool,   NullText,        zeroMatters: true ));
        NoNullRet("False", Coalesce(false,       NullBool,   NullText,                     true ));
        NoNullRet("",      Coalesce(false,       NullBool,   Empty                              ));
        NoNullRet("",      Coalesce(false,       NullBool,   Empty,           zeroMatters: false));
        NoNullRet("",      Coalesce(false,       NullBool,   Empty,                        false));
        NoNullRet("False", Coalesce(false,       NullBool,   Empty,           zeroMatters       ));
        NoNullRet("False", Coalesce(false,       NullBool,   Empty,           zeroMatters: true ));
        NoNullRet("False", Coalesce(false,       NullBool,   Empty,                        true ));
        NoNullRet(" ",     Coalesce(false,       NullBool,   Space                              ));
        NoNullRet(" ",     Coalesce(false,       NullBool,   Space,           zeroMatters: false));
        NoNullRet(" ",     Coalesce(false,       NullBool,   Space,                        false));
        NoNullRet("False", Coalesce(false,       NullBool,   Space,           zeroMatters       ));
        NoNullRet("False", Coalesce(false,       NullBool,   Space,           zeroMatters: true ));
        NoNullRet("False", Coalesce(false,       NullBool,   Space,                        true ));
        NoNullRet(Text,    Coalesce(false,       NullBool,   Text                               ));
        NoNullRet(Text,    Coalesce(false,       NullBool,   Text,            zeroMatters: false));
        NoNullRet(Text,    Coalesce(false,       NullBool,   Text,                         false));
        NoNullRet("False", Coalesce(false,       NullBool,   Text,            zeroMatters       ));
        NoNullRet("False", Coalesce(false,       NullBool,   Text,            zeroMatters: true ));
        NoNullRet("False", Coalesce(false,       NullBool,   Text,                         true ));
        NoNullRet("",      Coalesce(false,       NullBool,   NullyEmpty                         ));
        NoNullRet("",      Coalesce(false,       NullBool,   NullyEmpty,      zeroMatters: false));
        NoNullRet("",      Coalesce(false,       NullBool,   NullyEmpty,                   false));
        NoNullRet("False", Coalesce(false,       NullBool,   NullyEmpty,      zeroMatters       ));
        NoNullRet("False", Coalesce(false,       NullBool,   NullyEmpty,      zeroMatters: true ));
        NoNullRet("False", Coalesce(false,       NullBool,   NullyEmpty,                   true ));
        NoNullRet(" ",     Coalesce(false,       NullBool,   NullySpace                         ));
        NoNullRet(" ",     Coalesce(false,       NullBool,   NullySpace,      zeroMatters: false));
        NoNullRet(" ",     Coalesce(false,       NullBool,   NullySpace,                   false));
        NoNullRet("False", Coalesce(false,       NullBool,   NullySpace,      zeroMatters       ));
        NoNullRet("False", Coalesce(false,       NullBool,   NullySpace,      zeroMatters: true ));
        NoNullRet("False", Coalesce(false,       NullBool,   NullySpace,                   true ));
        NoNullRet(Text,    Coalesce(false,       NullBool,   NullyFilledText                    ));
        NoNullRet(Text,    Coalesce(false,       NullBool,   NullyFilledText, zeroMatters: false));
        NoNullRet(Text,    Coalesce(false,       NullBool,   NullyFilledText,              false));
        NoNullRet("False", Coalesce(false,       NullBool,   NullyFilledText, zeroMatters       ));
        NoNullRet("False", Coalesce(false,       NullBool,   NullyFilledText, zeroMatters: true ));
        NoNullRet("False", Coalesce(false,       NullBool,   NullyFilledText,              true ));
        NoNullRet("True",  Coalesce(false,       NullyTrue,  NullText                           ));
        NoNullRet("True",  Coalesce(false,       NullyTrue,  NullText,        zeroMatters: false));
        NoNullRet("True",  Coalesce(false,       NullyTrue,  NullText,                     false));
        NoNullRet("False", Coalesce(false,       NullyTrue,  NullText,        zeroMatters       ));
        NoNullRet("False", Coalesce(false,       NullyTrue,  NullText,        zeroMatters: true ));
        NoNullRet("False", Coalesce(false,       NullyTrue,  NullText,                     true ));
        NoNullRet("True",  Coalesce(false,       NullyTrue,  Empty                              ));
        NoNullRet("True",  Coalesce(false,       NullyTrue,  Empty,           zeroMatters: false));
        NoNullRet("True",  Coalesce(false,       NullyTrue,  Empty,                        false));
        NoNullRet("False", Coalesce(false,       NullyTrue,  Empty,           zeroMatters       ));
        NoNullRet("False", Coalesce(false,       NullyTrue,  Empty,           zeroMatters: true ));
        NoNullRet("False", Coalesce(false,       NullyTrue,  Empty,                        true ));
        NoNullRet("True",  Coalesce(false,       NullyTrue,  Space                              ));
        NoNullRet("True",  Coalesce(false,       NullyTrue,  Space,           zeroMatters: false));
        NoNullRet("True",  Coalesce(false,       NullyTrue,  Space,                        false));
        NoNullRet("False", Coalesce(false,       NullyTrue,  Space,           zeroMatters       ));
        NoNullRet("False", Coalesce(false,       NullyTrue,  Space,           zeroMatters: true ));
        NoNullRet("False", Coalesce(false,       NullyTrue,  Space,                        true ));
        NoNullRet("True",  Coalesce(false,       NullyTrue,  Text                               ));
        NoNullRet("True",  Coalesce(false,       NullyTrue,  Text,            zeroMatters: false));
        NoNullRet("True",  Coalesce(false,       NullyTrue,  Text,                         false));
        NoNullRet("False", Coalesce(false,       NullyTrue,  Text,            zeroMatters       ));
        NoNullRet("False", Coalesce(false,       NullyTrue,  Text,            zeroMatters: true ));
        NoNullRet("False", Coalesce(false,       NullyTrue,  Text,                         true ));
        NoNullRet("True",  Coalesce(false,       NullyTrue,  NullyEmpty                         ));
        NoNullRet("True",  Coalesce(false,       NullyTrue,  NullyEmpty,      zeroMatters: false));
        NoNullRet("True",  Coalesce(false,       NullyTrue,  NullyEmpty,                   false));
        NoNullRet("False", Coalesce(false,       NullyTrue,  NullyEmpty,      zeroMatters       ));
        NoNullRet("False", Coalesce(false,       NullyTrue,  NullyEmpty,      zeroMatters: true ));
        NoNullRet("False", Coalesce(false,       NullyTrue,  NullyEmpty,                   true ));
        NoNullRet("True",  Coalesce(false,       NullyTrue,  NullySpace                         ));
        NoNullRet("True",  Coalesce(false,       NullyTrue,  NullySpace,      zeroMatters: false));
        NoNullRet("True",  Coalesce(false,       NullyTrue,  NullySpace,                   false));
        NoNullRet("False", Coalesce(false,       NullyTrue,  NullySpace,      zeroMatters       ));
        NoNullRet("False", Coalesce(false,       NullyTrue,  NullySpace,      zeroMatters: true ));
        NoNullRet("False", Coalesce(false,       NullyTrue,  NullySpace,                   true ));
        NoNullRet("True",  Coalesce(false,       NullyTrue,  NullyFilledText                    ));
        NoNullRet("True",  Coalesce(false,       NullyTrue,  NullyFilledText, zeroMatters: false));
        NoNullRet("True",  Coalesce(false,       NullyTrue,  NullyFilledText,              false));
        NoNullRet("False", Coalesce(false,       NullyTrue,  NullyFilledText, zeroMatters       ));
        NoNullRet("False", Coalesce(false,       NullyTrue,  NullyFilledText, zeroMatters: true ));
        NoNullRet("False", Coalesce(false,       NullyTrue,  NullyFilledText,              true ));
        NoNullRet("True",  Coalesce(false,       true,       NullText                           ));
        NoNullRet("True",  Coalesce(false,       true,       NullText,        zeroMatters: false));
        NoNullRet("True",  Coalesce(false,       true,       NullText,                     false));
        NoNullRet("False", Coalesce(false,       true,       NullText,        zeroMatters       ));
        NoNullRet("False", Coalesce(false,       true,       NullText,        zeroMatters: true ));
        NoNullRet("False", Coalesce(false,       true,       NullText,                     true ));
        NoNullRet("True",  Coalesce(false,       true,       Empty                              ));
        NoNullRet("True",  Coalesce(false,       true,       Empty,           zeroMatters: false));
        NoNullRet("True",  Coalesce(false,       true,       Empty,                        false));
        NoNullRet("False", Coalesce(false,       true,       Empty,           zeroMatters       ));
        NoNullRet("False", Coalesce(false,       true,       Empty,           zeroMatters: true ));
        NoNullRet("False", Coalesce(false,       true,       Empty,                        true ));
        NoNullRet("True",  Coalesce(false,       true,       Space                              ));
        NoNullRet("True",  Coalesce(false,       true,       Space,           zeroMatters: false));
        NoNullRet("True",  Coalesce(false,       true,       Space,                        false));
        NoNullRet("False", Coalesce(false,       true,       Space,           zeroMatters       ));
        NoNullRet("False", Coalesce(false,       true,       Space,           zeroMatters: true ));
        NoNullRet("False", Coalesce(false,       true,       Space,                        true ));
        NoNullRet("True",  Coalesce(false,       true,       Text                               ));
        NoNullRet("True",  Coalesce(false,       true,       Text,            zeroMatters: false));
        NoNullRet("True",  Coalesce(false,       true,       Text,                         false));
        NoNullRet("False", Coalesce(false,       true,       Text,            zeroMatters       ));
        NoNullRet("False", Coalesce(false,       true,       Text,            zeroMatters: true ));
        NoNullRet("False", Coalesce(false,       true,       Text,                         true ));
        NoNullRet("True",  Coalesce(false,       true,       NullyEmpty                         ));
        NoNullRet("True",  Coalesce(false,       true,       NullyEmpty,      zeroMatters: false));
        NoNullRet("True",  Coalesce(false,       true,       NullyEmpty,                   false));
        NoNullRet("False", Coalesce(false,       true,       NullyEmpty,      zeroMatters       ));
        NoNullRet("False", Coalesce(false,       true,       NullyEmpty,      zeroMatters: true ));
        NoNullRet("False", Coalesce(false,       true,       NullyEmpty,                   true ));
        NoNullRet("True",  Coalesce(false,       true,       NullySpace                         ));
        NoNullRet("True",  Coalesce(false,       true,       NullySpace,      zeroMatters: false));
        NoNullRet("True",  Coalesce(false,       true,       NullySpace,                   false));
        NoNullRet("False", Coalesce(false,       true,       NullySpace,      zeroMatters       ));
        NoNullRet("False", Coalesce(false,       true,       NullySpace,      zeroMatters: true ));
        NoNullRet("False", Coalesce(false,       true,       NullySpace,                   true ));
        NoNullRet("True",  Coalesce(false,       true,       NullyFilledText                    ));
        NoNullRet("True",  Coalesce(false,       true,       NullyFilledText, zeroMatters: false));
        NoNullRet("True",  Coalesce(false,       true,       NullyFilledText,              false));
        NoNullRet("False", Coalesce(false,       true,       NullyFilledText, zeroMatters       ));
        NoNullRet("False", Coalesce(false,       true,       NullyFilledText, zeroMatters: true ));
        NoNullRet("False", Coalesce(false,       true,       NullyFilledText,              true ));
    }

    [TestMethod]
    public void Coalesce_3Args_BoolToText_StaticZeroMattersFlagsInBack_Batch5()
    {
        NoNullRet("True",  Coalesce(true,       NullBool,   NullText                           ));
        NoNullRet("True",  Coalesce(true,       NullBool,   NullText,        zeroMatters: false));
        NoNullRet("True",  Coalesce(true,       NullBool,   NullText,                     false));
        NoNullRet("True",  Coalesce(true,       NullBool,   NullText,        zeroMatters       ));
        NoNullRet("True",  Coalesce(true,       NullBool,   NullText,        zeroMatters: true ));
        NoNullRet("True",  Coalesce(true,       NullBool,   NullText,                     true ));
        NoNullRet("True",  Coalesce(true,       NullBool,   Empty                              ));
        NoNullRet("True",  Coalesce(true,       NullBool,   Empty,           zeroMatters: false));
        NoNullRet("True",  Coalesce(true,       NullBool,   Empty,                        false));
        NoNullRet("True",  Coalesce(true,       NullBool,   Empty,           zeroMatters       ));
        NoNullRet("True",  Coalesce(true,       NullBool,   Empty,           zeroMatters: true ));
        NoNullRet("True",  Coalesce(true,       NullBool,   Empty,                        true ));
        NoNullRet("True",  Coalesce(true,       NullBool,   Space                              ));
        NoNullRet("True",  Coalesce(true,       NullBool,   Space,           zeroMatters: false));
        NoNullRet("True",  Coalesce(true,       NullBool,   Space,                        false));
        NoNullRet("True",  Coalesce(true,       NullBool,   Space,           zeroMatters       ));
        NoNullRet("True",  Coalesce(true,       NullBool,   Space,           zeroMatters: true ));
        NoNullRet("True",  Coalesce(true,       NullBool,   Space,                        true ));
        NoNullRet("True",  Coalesce(true,       NullBool,   Text                               ));
        NoNullRet("True",  Coalesce(true,       NullBool,   Text,            zeroMatters: false));
        NoNullRet("True",  Coalesce(true,       NullBool,   Text,                         false));
        NoNullRet("True",  Coalesce(true,       NullBool,   Text,            zeroMatters       ));
        NoNullRet("True",  Coalesce(true,       NullBool,   Text,            zeroMatters: true ));
        NoNullRet("True",  Coalesce(true,       NullBool,   Text,                         true ));
        NoNullRet("True",  Coalesce(true,       NullBool,   NullyEmpty                         ));
        NoNullRet("True",  Coalesce(true,       NullBool,   NullyEmpty,      zeroMatters: false));
        NoNullRet("True",  Coalesce(true,       NullBool,   NullyEmpty,                   false));
        NoNullRet("True",  Coalesce(true,       NullBool,   NullyEmpty,      zeroMatters       ));
        NoNullRet("True",  Coalesce(true,       NullBool,   NullyEmpty,      zeroMatters: true ));
        NoNullRet("True",  Coalesce(true,       NullBool,   NullyEmpty,                   true ));
        NoNullRet("True",  Coalesce(true,       NullBool,   NullySpace                         ));
        NoNullRet("True",  Coalesce(true,       NullBool,   NullySpace,      zeroMatters: false));
        NoNullRet("True",  Coalesce(true,       NullBool,   NullySpace,                   false));
        NoNullRet("True",  Coalesce(true,       NullBool,   NullySpace,      zeroMatters       ));
        NoNullRet("True",  Coalesce(true,       NullBool,   NullySpace,      zeroMatters: true ));
        NoNullRet("True",  Coalesce(true,       NullBool,   NullySpace,                   true ));
        NoNullRet("True",  Coalesce(true,       NullBool,   NullyFilledText                    ));
        NoNullRet("True",  Coalesce(true,       NullBool,   NullyFilledText, zeroMatters: false));
        NoNullRet("True",  Coalesce(true,       NullBool,   NullyFilledText,              false));
        NoNullRet("True",  Coalesce(true,       NullBool,   NullyFilledText, zeroMatters       ));
        NoNullRet("True",  Coalesce(true,       NullBool,   NullyFilledText, zeroMatters: true ));
        NoNullRet("True",  Coalesce(true,       NullBool,   NullyFilledText,              true ));
        NoNullRet("True",  Coalesce(true,       NullyFalse, NullText                           ));
        NoNullRet("True",  Coalesce(true,       NullyFalse, NullText,        zeroMatters: false));
        NoNullRet("True",  Coalesce(true,       NullyFalse, NullText,                     false));
        NoNullRet("True",  Coalesce(true,       NullyFalse, NullText,        zeroMatters       ));
        NoNullRet("True",  Coalesce(true,       NullyFalse, NullText,        zeroMatters: true ));
        NoNullRet("True",  Coalesce(true,       NullyFalse, NullText,                     true ));
        NoNullRet("True",  Coalesce(true,       NullyFalse, Empty                              ));
        NoNullRet("True",  Coalesce(true,       NullyFalse, Empty,           zeroMatters: false));
        NoNullRet("True",  Coalesce(true,       NullyFalse, Empty,                        false));
        NoNullRet("True",  Coalesce(true,       NullyFalse, Empty,           zeroMatters       ));
        NoNullRet("True",  Coalesce(true,       NullyFalse, Empty,           zeroMatters: true ));
        NoNullRet("True",  Coalesce(true,       NullyFalse, Empty,                        true ));
        NoNullRet("True",  Coalesce(true,       NullyFalse, Space                              ));
        NoNullRet("True",  Coalesce(true,       NullyFalse, Space,           zeroMatters: false));
        NoNullRet("True",  Coalesce(true,       NullyFalse, Space,                        false));
        NoNullRet("True",  Coalesce(true,       NullyFalse, Space,           zeroMatters       ));
        NoNullRet("True",  Coalesce(true,       NullyFalse, Space,           zeroMatters: true ));
        NoNullRet("True",  Coalesce(true,       NullyFalse, Space,                        true ));
        NoNullRet("True",  Coalesce(true,       NullyFalse, Text                               ));
        NoNullRet("True",  Coalesce(true,       NullyFalse, Text,            zeroMatters: false));
        NoNullRet("True",  Coalesce(true,       NullyFalse, Text,                         false));
        NoNullRet("True",  Coalesce(true,       NullyFalse, Text,            zeroMatters       ));
        NoNullRet("True",  Coalesce(true,       NullyFalse, Text,            zeroMatters: true ));
        NoNullRet("True",  Coalesce(true,       NullyFalse, Text,                         true ));
        NoNullRet("True",  Coalesce(true,       NullyFalse, NullyEmpty                         ));
        NoNullRet("True",  Coalesce(true,       NullyFalse, NullyEmpty,      zeroMatters: false));
        NoNullRet("True",  Coalesce(true,       NullyFalse, NullyEmpty,                   false));
        NoNullRet("True",  Coalesce(true,       NullyFalse, NullyEmpty,      zeroMatters       ));
        NoNullRet("True",  Coalesce(true,       NullyFalse, NullyEmpty,      zeroMatters: true ));
        NoNullRet("True",  Coalesce(true,       NullyFalse, NullyEmpty,                   true ));
        NoNullRet("True",  Coalesce(true,       NullyFalse, NullySpace                         ));
        NoNullRet("True",  Coalesce(true,       NullyFalse, NullySpace,      zeroMatters: false));
        NoNullRet("True",  Coalesce(true,       NullyFalse, NullySpace,                   false));
        NoNullRet("True",  Coalesce(true,       NullyFalse, NullySpace,      zeroMatters       ));
        NoNullRet("True",  Coalesce(true,       NullyFalse, NullySpace,      zeroMatters: true ));
        NoNullRet("True",  Coalesce(true,       NullyFalse, NullySpace,                   true ));
        NoNullRet("True",  Coalesce(true,       NullyFalse, NullyFilledText                    ));
        NoNullRet("True",  Coalesce(true,       NullyFalse, NullyFilledText, zeroMatters: false));
        NoNullRet("True",  Coalesce(true,       NullyFalse, NullyFilledText,              false));
        NoNullRet("True",  Coalesce(true,       NullyFalse, NullyFilledText, zeroMatters       ));
        NoNullRet("True",  Coalesce(true,       NullyFalse, NullyFilledText, zeroMatters: true ));
        NoNullRet("True",  Coalesce(true,       NullyFalse, NullyFilledText,              true ));
    }
}