namespace JJ.Framework.Existence.Core.Tests;

[TestClass]
public class Coalesce_3Args_BoolToText_ExtensionsZeroMattersFlagsInBack : TestBase
{
    [TestMethod]
    public void Coalesce_3Args_BoolToText_ExtensionsZeroMattersFlagsInBack_Batch1()
    {
        NoNullRet("",      NullBool  .Coalesce(NullyFalse, NullText                           ));
        NoNullRet("",      NullBool  .Coalesce(NullyFalse, NullText,        zeroMatters: false));
        NoNullRet("",      NullBool  .Coalesce(NullyFalse, NullText,                     false));
        NoNullRet("False", NullBool  .Coalesce(NullyFalse, NullText,        zeroMatters       ));
        NoNullRet("False", NullBool  .Coalesce(NullyFalse, NullText,        zeroMatters: true ));
        NoNullRet("False", NullBool  .Coalesce(NullyFalse, NullText,                     true ));
        NoNullRet("",      NullBool  .Coalesce(NullyFalse, Empty                              ));
        NoNullRet("",      NullBool  .Coalesce(NullyFalse, Empty,           zeroMatters: false));
        NoNullRet("",      NullBool  .Coalesce(NullyFalse, Empty,                        false));
        NoNullRet("False", NullBool  .Coalesce(NullyFalse, Empty,           zeroMatters       ));
        NoNullRet("False", NullBool  .Coalesce(NullyFalse, Empty,           zeroMatters: true ));
        NoNullRet("False", NullBool  .Coalesce(NullyFalse, Empty,                        true ));
        NoNullRet(" ",     NullBool  .Coalesce(NullyFalse, Space                              ));
        NoNullRet(" ",     NullBool  .Coalesce(NullyFalse, Space,           zeroMatters: false));
        NoNullRet(" ",     NullBool  .Coalesce(NullyFalse, Space,                        false));
        NoNullRet("False", NullBool  .Coalesce(NullyFalse, Space,           zeroMatters       ));
        NoNullRet("False", NullBool  .Coalesce(NullyFalse, Space,           zeroMatters: true ));
        NoNullRet("False", NullBool  .Coalesce(NullyFalse, Space,                        true ));
        NoNullRet(Text,    NullBool  .Coalesce(NullyFalse, Text                               ));
        NoNullRet(Text,    NullBool  .Coalesce(NullyFalse, Text,            zeroMatters: false));
        NoNullRet(Text,    NullBool  .Coalesce(NullyFalse, Text,                         false));
        NoNullRet("False", NullBool  .Coalesce(NullyFalse, Text,            zeroMatters       ));
        NoNullRet("False", NullBool  .Coalesce(NullyFalse, Text,            zeroMatters: true ));
        NoNullRet("False", NullBool  .Coalesce(NullyFalse, Text,                         true ));
        NoNullRet("",      NullBool  .Coalesce(NullyFalse, NullyEmpty                         ));
        NoNullRet("",      NullBool  .Coalesce(NullyFalse, NullyEmpty,      zeroMatters: false));
        NoNullRet("",      NullBool  .Coalesce(NullyFalse, NullyEmpty,                   false));
        NoNullRet("False", NullBool  .Coalesce(NullyFalse, NullyEmpty,      zeroMatters       ));
        NoNullRet("False", NullBool  .Coalesce(NullyFalse, NullyEmpty,      zeroMatters: true ));
        NoNullRet("False", NullBool  .Coalesce(NullyFalse, NullyEmpty,                   true ));
        NoNullRet(" ",     NullBool  .Coalesce(NullyFalse, NullySpace                         ));
        NoNullRet(" ",     NullBool  .Coalesce(NullyFalse, NullySpace,      zeroMatters: false));
        NoNullRet(" ",     NullBool  .Coalesce(NullyFalse, NullySpace,                   false));
        NoNullRet("False", NullBool  .Coalesce(NullyFalse, NullySpace,      zeroMatters       ));
        NoNullRet("False", NullBool  .Coalesce(NullyFalse, NullySpace,      zeroMatters: true ));
        NoNullRet("False", NullBool  .Coalesce(NullyFalse, NullySpace,                   true ));
        NoNullRet(Text,    NullBool  .Coalesce(NullyFalse, NullyFilledText                    ));
        NoNullRet(Text,    NullBool  .Coalesce(NullyFalse, NullyFilledText, zeroMatters: false));
        NoNullRet(Text,    NullBool  .Coalesce(NullyFalse, NullyFilledText,              false));
        NoNullRet("False", NullBool  .Coalesce(NullyFalse, NullyFilledText, zeroMatters       ));
        NoNullRet("False", NullBool  .Coalesce(NullyFalse, NullyFilledText, zeroMatters: true ));
        NoNullRet("False", NullBool  .Coalesce(NullyFalse, NullyFilledText,              true ));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  NullText                           ));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  NullText,        zeroMatters: false));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  NullText,                     false));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  NullText,        zeroMatters       ));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  NullText,        zeroMatters: true ));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  NullText,                     true ));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  Empty                              ));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  Empty,           zeroMatters: false));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  Empty,                        false));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  Empty,           zeroMatters       ));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  Empty,           zeroMatters: true ));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  Empty,                        true ));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  Space                              ));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  Space,           zeroMatters: false));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  Space,                        false));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  Space,           zeroMatters       ));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  Space,           zeroMatters: true ));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  Space,                        true ));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  Text                               ));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  Text,            zeroMatters: false));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  Text,                         false));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  Text,            zeroMatters       ));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  Text,            zeroMatters: true ));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  Text,                         true ));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  NullyEmpty                         ));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  NullyEmpty,      zeroMatters: false));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  NullyEmpty,                   false));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  NullyEmpty,      zeroMatters       ));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  NullyEmpty,      zeroMatters: true ));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  NullyEmpty,                   true ));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  NullySpace                         ));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  NullySpace,      zeroMatters: false));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  NullySpace,                   false));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  NullySpace,      zeroMatters       ));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  NullySpace,      zeroMatters: true ));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  NullySpace,                   true ));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  NullyFilledText                    ));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  NullyFilledText, zeroMatters: false));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  NullyFilledText,              false));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  NullyFilledText, zeroMatters       ));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  NullyFilledText, zeroMatters: true ));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  NullyFilledText,              true ));
        NoNullRet("",      NullBool  .Coalesce(false,      NullText                           ));
        NoNullRet("",      NullBool  .Coalesce(false,      NullText,        zeroMatters: false));
        NoNullRet("",      NullBool  .Coalesce(false,      NullText,                     false));
        NoNullRet("False", NullBool  .Coalesce(false,      NullText,        zeroMatters       ));
        NoNullRet("False", NullBool  .Coalesce(false,      NullText,        zeroMatters: true ));
        NoNullRet("False", NullBool  .Coalesce(false,      NullText,                     true ));
        NoNullRet("",      NullBool  .Coalesce(false,      Empty                              ));
        NoNullRet("",      NullBool  .Coalesce(false,      Empty,           zeroMatters: false));
        NoNullRet("",      NullBool  .Coalesce(false,      Empty,                        false));
        NoNullRet("False", NullBool  .Coalesce(false,      Empty,           zeroMatters       ));
        NoNullRet("False", NullBool  .Coalesce(false,      Empty,           zeroMatters: true ));
        NoNullRet("False", NullBool  .Coalesce(false,      Empty,                        true ));
        NoNullRet(" ",     NullBool  .Coalesce(false,      Space                              ));
        NoNullRet(" ",     NullBool  .Coalesce(false,      Space,           zeroMatters: false));
        NoNullRet(" ",     NullBool  .Coalesce(false,      Space,                        false));
        NoNullRet("False", NullBool  .Coalesce(false,      Space,           zeroMatters       ));
        NoNullRet("False", NullBool  .Coalesce(false,      Space,           zeroMatters: true ));
        NoNullRet("False", NullBool  .Coalesce(false,      Space,                        true ));
        NoNullRet(Text,    NullBool  .Coalesce(false,      Text                               ));
        NoNullRet(Text,    NullBool  .Coalesce(false,      Text,            zeroMatters: false));
        NoNullRet(Text,    NullBool  .Coalesce(false,      Text,                         false));
        NoNullRet("False", NullBool  .Coalesce(false,      Text,            zeroMatters       ));
        NoNullRet("False", NullBool  .Coalesce(false,      Text,            zeroMatters: true ));
        NoNullRet("False", NullBool  .Coalesce(false,      Text,                         true ));
        NoNullRet("",      NullBool  .Coalesce(false,      NullyEmpty                         ));
        NoNullRet("",      NullBool  .Coalesce(false,      NullyEmpty,      zeroMatters: false));
        NoNullRet("",      NullBool  .Coalesce(false,      NullyEmpty,                   false));
        NoNullRet("False", NullBool  .Coalesce(false,      NullyEmpty,      zeroMatters       ));
        NoNullRet("False", NullBool  .Coalesce(false,      NullyEmpty,      zeroMatters: true ));
        NoNullRet("False", NullBool  .Coalesce(false,      NullyEmpty,                   true ));
        NoNullRet(" ",     NullBool  .Coalesce(false,      NullySpace                         ));
        NoNullRet(" ",     NullBool  .Coalesce(false,      NullySpace,      zeroMatters: false));
        NoNullRet(" ",     NullBool  .Coalesce(false,      NullySpace,                   false));
        NoNullRet("False", NullBool  .Coalesce(false,      NullySpace,      zeroMatters       ));
        NoNullRet("False", NullBool  .Coalesce(false,      NullySpace,      zeroMatters: true ));
        NoNullRet("False", NullBool  .Coalesce(false,      NullySpace,                   true ));
        NoNullRet(Text,    NullBool  .Coalesce(false,      NullyFilledText                    ));
        NoNullRet(Text,    NullBool  .Coalesce(false,      NullyFilledText, zeroMatters: false));
        NoNullRet(Text,    NullBool  .Coalesce(false,      NullyFilledText,              false));
        NoNullRet("False", NullBool  .Coalesce(false,      NullyFilledText, zeroMatters       ));
        NoNullRet("False", NullBool  .Coalesce(false,      NullyFilledText, zeroMatters: true ));
        NoNullRet("False", NullBool  .Coalesce(false,      NullyFilledText,              true ));
        NoNullRet("True",  NullBool  .Coalesce(true,       NullText                           ));
        NoNullRet("True",  NullBool  .Coalesce(true,       NullText,        zeroMatters: false));
        NoNullRet("True",  NullBool  .Coalesce(true,       NullText,                     false));
        NoNullRet("True",  NullBool  .Coalesce(true,       NullText,        zeroMatters       ));
        NoNullRet("True",  NullBool  .Coalesce(true,       NullText,        zeroMatters: true ));
        NoNullRet("True",  NullBool  .Coalesce(true,       NullText,                     true ));
        NoNullRet("True",  NullBool  .Coalesce(true,       Empty                              ));
        NoNullRet("True",  NullBool  .Coalesce(true,       Empty,           zeroMatters: false));
        NoNullRet("True",  NullBool  .Coalesce(true,       Empty,                        false));
        NoNullRet("True",  NullBool  .Coalesce(true,       Empty,           zeroMatters       ));
        NoNullRet("True",  NullBool  .Coalesce(true,       Empty,           zeroMatters: true ));
        NoNullRet("True",  NullBool  .Coalesce(true,       Empty,                        true ));
        NoNullRet("True",  NullBool  .Coalesce(true,       Space                              ));
        NoNullRet("True",  NullBool  .Coalesce(true,       Space,           zeroMatters: false));
        NoNullRet("True",  NullBool  .Coalesce(true,       Space,                        false));
        NoNullRet("True",  NullBool  .Coalesce(true,       Space,           zeroMatters       ));
        NoNullRet("True",  NullBool  .Coalesce(true,       Space,           zeroMatters: true ));
        NoNullRet("True",  NullBool  .Coalesce(true,       Space,                        true ));
        NoNullRet("True",  NullBool  .Coalesce(true,       Text                               ));
        NoNullRet("True",  NullBool  .Coalesce(true,       Text,            zeroMatters: false));
        NoNullRet("True",  NullBool  .Coalesce(true,       Text,                         false));
        NoNullRet("True",  NullBool  .Coalesce(true,       Text,            zeroMatters       ));
        NoNullRet("True",  NullBool  .Coalesce(true,       Text,            zeroMatters: true ));
        NoNullRet("True",  NullBool  .Coalesce(true,       Text,                         true ));
        NoNullRet("True",  NullBool  .Coalesce(true,       NullyEmpty                         ));
        NoNullRet("True",  NullBool  .Coalesce(true,       NullyEmpty,      zeroMatters: false));
        NoNullRet("True",  NullBool  .Coalesce(true,       NullyEmpty,                   false));
        NoNullRet("True",  NullBool  .Coalesce(true,       NullyEmpty,      zeroMatters       ));
        NoNullRet("True",  NullBool  .Coalesce(true,       NullyEmpty,      zeroMatters: true ));
        NoNullRet("True",  NullBool  .Coalesce(true,       NullyEmpty,                   true ));
        NoNullRet("True",  NullBool  .Coalesce(true,       NullySpace                         ));
        NoNullRet("True",  NullBool  .Coalesce(true,       NullySpace,      zeroMatters: false));
        NoNullRet("True",  NullBool  .Coalesce(true,       NullySpace,                   false));
        NoNullRet("True",  NullBool  .Coalesce(true,       NullySpace,      zeroMatters       ));
        NoNullRet("True",  NullBool  .Coalesce(true,       NullySpace,      zeroMatters: true ));
        NoNullRet("True",  NullBool  .Coalesce(true,       NullySpace,                   true ));
        NoNullRet("True",  NullBool  .Coalesce(true,       NullyFilledText                    ));
        NoNullRet("True",  NullBool  .Coalesce(true,       NullyFilledText, zeroMatters: false));
        NoNullRet("True",  NullBool  .Coalesce(true,       NullyFilledText,              false));
        NoNullRet("True",  NullBool  .Coalesce(true,       NullyFilledText, zeroMatters       ));
        NoNullRet("True",  NullBool  .Coalesce(true,       NullyFilledText, zeroMatters: true ));
        NoNullRet("True",  NullBool  .Coalesce(true,       NullyFilledText,              true ));
    }

    [TestMethod]
    public void Coalesce_3Args_BoolToText_ExtensionsZeroMattersFlagsInBack_Batch2()
    {
        NoNullRet("",      NullyFalse.Coalesce(NullBool,   NullText                           ));
        NoNullRet("",      NullyFalse.Coalesce(NullBool,   NullText,        zeroMatters: false));
        NoNullRet("",      NullyFalse.Coalesce(NullBool,   NullText,                     false));
        NoNullRet("False", NullyFalse.Coalesce(NullBool,   NullText,        zeroMatters       ));
        NoNullRet("False", NullyFalse.Coalesce(NullBool,   NullText,        zeroMatters: true ));
        NoNullRet("False", NullyFalse.Coalesce(NullBool,   NullText,                     true ));
        NoNullRet("",      NullyFalse.Coalesce(NullBool,   Empty                              ));
        NoNullRet("",      NullyFalse.Coalesce(NullBool,   Empty,           zeroMatters: false));
        NoNullRet("",      NullyFalse.Coalesce(NullBool,   Empty,                        false));
        NoNullRet("False", NullyFalse.Coalesce(NullBool,   Empty,           zeroMatters       ));
        NoNullRet("False", NullyFalse.Coalesce(NullBool,   Empty,           zeroMatters: true ));
        NoNullRet("False", NullyFalse.Coalesce(NullBool,   Empty,                        true ));
        NoNullRet(" ",     NullyFalse.Coalesce(NullBool,   Space                              ));
        NoNullRet(" ",     NullyFalse.Coalesce(NullBool,   Space,           zeroMatters: false));
        NoNullRet(" ",     NullyFalse.Coalesce(NullBool,   Space,                        false));
        NoNullRet("False", NullyFalse.Coalesce(NullBool,   Space,           zeroMatters       ));
        NoNullRet("False", NullyFalse.Coalesce(NullBool,   Space,           zeroMatters: true ));
        NoNullRet("False", NullyFalse.Coalesce(NullBool,   Space,                        true ));
        NoNullRet(Text,    NullyFalse.Coalesce(NullBool,   Text                               ));
        NoNullRet(Text,    NullyFalse.Coalesce(NullBool,   Text,            zeroMatters: false));
        NoNullRet(Text,    NullyFalse.Coalesce(NullBool,   Text,                         false));
        NoNullRet("False", NullyFalse.Coalesce(NullBool,   Text,            zeroMatters       ));
        NoNullRet("False", NullyFalse.Coalesce(NullBool,   Text,            zeroMatters: true ));
        NoNullRet("False", NullyFalse.Coalesce(NullBool,   Text,                         true ));
        NoNullRet("",      NullyFalse.Coalesce(NullBool,   NullyEmpty                         ));
        NoNullRet("",      NullyFalse.Coalesce(NullBool,   NullyEmpty,      zeroMatters: false));
        NoNullRet("",      NullyFalse.Coalesce(NullBool,   NullyEmpty,                   false));
        NoNullRet("False", NullyFalse.Coalesce(NullBool,   NullyEmpty,      zeroMatters       ));
        NoNullRet("False", NullyFalse.Coalesce(NullBool,   NullyEmpty,      zeroMatters: true ));
        NoNullRet("False", NullyFalse.Coalesce(NullBool,   NullyEmpty,                   true ));
        NoNullRet(" ",     NullyFalse.Coalesce(NullBool,   NullySpace                         ));
        NoNullRet(" ",     NullyFalse.Coalesce(NullBool,   NullySpace,      zeroMatters: false));
        NoNullRet(" ",     NullyFalse.Coalesce(NullBool,   NullySpace,                   false));
        NoNullRet("False", NullyFalse.Coalesce(NullBool,   NullySpace,      zeroMatters       ));
        NoNullRet("False", NullyFalse.Coalesce(NullBool,   NullySpace,      zeroMatters: true ));
        NoNullRet("False", NullyFalse.Coalesce(NullBool,   NullySpace,                   true ));
        NoNullRet(Text,    NullyFalse.Coalesce(NullBool,   NullyFilledText                    ));
        NoNullRet(Text,    NullyFalse.Coalesce(NullBool,   NullyFilledText, zeroMatters: false));
        NoNullRet(Text,    NullyFalse.Coalesce(NullBool,   NullyFilledText,              false));
        NoNullRet("False", NullyFalse.Coalesce(NullBool,   NullyFilledText, zeroMatters       ));
        NoNullRet("False", NullyFalse.Coalesce(NullBool,   NullyFilledText, zeroMatters: true ));
        NoNullRet("False", NullyFalse.Coalesce(NullBool,   NullyFilledText,              true ));
        NoNullRet("True",  NullyFalse.Coalesce(NullyTrue,  NullText                           ));
        NoNullRet("True",  NullyFalse.Coalesce(NullyTrue,  NullText,        zeroMatters: false));
        NoNullRet("True",  NullyFalse.Coalesce(NullyTrue,  NullText,                     false));
        NoNullRet("False", NullyFalse.Coalesce(NullyTrue,  NullText,        zeroMatters       ));
        NoNullRet("False", NullyFalse.Coalesce(NullyTrue,  NullText,        zeroMatters: true ));
        NoNullRet("False", NullyFalse.Coalesce(NullyTrue,  NullText,                     true ));
        NoNullRet("True",  NullyFalse.Coalesce(NullyTrue,  Empty                              ));
        NoNullRet("True",  NullyFalse.Coalesce(NullyTrue,  Empty,           zeroMatters: false));
        NoNullRet("True",  NullyFalse.Coalesce(NullyTrue,  Empty,                        false));
        NoNullRet("False", NullyFalse.Coalesce(NullyTrue,  Empty,           zeroMatters       ));
        NoNullRet("False", NullyFalse.Coalesce(NullyTrue,  Empty,           zeroMatters: true ));
        NoNullRet("False", NullyFalse.Coalesce(NullyTrue,  Empty,                        true ));
        NoNullRet("True",  NullyFalse.Coalesce(NullyTrue,  Space                              ));
        NoNullRet("True",  NullyFalse.Coalesce(NullyTrue,  Space,           zeroMatters: false));
        NoNullRet("True",  NullyFalse.Coalesce(NullyTrue,  Space,                        false));
        NoNullRet("False", NullyFalse.Coalesce(NullyTrue,  Space,           zeroMatters       ));
        NoNullRet("False", NullyFalse.Coalesce(NullyTrue,  Space,           zeroMatters: true ));
        NoNullRet("False", NullyFalse.Coalesce(NullyTrue,  Space,                        true ));
        NoNullRet("True",  NullyFalse.Coalesce(NullyTrue,  Text                               ));
        NoNullRet("True",  NullyFalse.Coalesce(NullyTrue,  Text,            zeroMatters: false));
        NoNullRet("True",  NullyFalse.Coalesce(NullyTrue,  Text,                         false));
        NoNullRet("False", NullyFalse.Coalesce(NullyTrue,  Text,            zeroMatters       ));
        NoNullRet("False", NullyFalse.Coalesce(NullyTrue,  Text,            zeroMatters: true ));
        NoNullRet("False", NullyFalse.Coalesce(NullyTrue,  Text,                         true ));
        NoNullRet("True",  NullyFalse.Coalesce(NullyTrue,  NullyEmpty                         ));
        NoNullRet("True",  NullyFalse.Coalesce(NullyTrue,  NullyEmpty,      zeroMatters: false));
        NoNullRet("True",  NullyFalse.Coalesce(NullyTrue,  NullyEmpty,                   false));
        NoNullRet("False", NullyFalse.Coalesce(NullyTrue,  NullyEmpty,      zeroMatters       ));
        NoNullRet("False", NullyFalse.Coalesce(NullyTrue,  NullyEmpty,      zeroMatters: true ));
        NoNullRet("False", NullyFalse.Coalesce(NullyTrue,  NullyEmpty,                   true ));
        NoNullRet("True",  NullyFalse.Coalesce(NullyTrue,  NullySpace                         ));
        NoNullRet("True",  NullyFalse.Coalesce(NullyTrue,  NullySpace,      zeroMatters: false));
        NoNullRet("True",  NullyFalse.Coalesce(NullyTrue,  NullySpace,                   false));
        NoNullRet("False", NullyFalse.Coalesce(NullyTrue,  NullySpace,      zeroMatters       ));
        NoNullRet("False", NullyFalse.Coalesce(NullyTrue,  NullySpace,      zeroMatters: true ));
        NoNullRet("False", NullyFalse.Coalesce(NullyTrue,  NullySpace,                   true ));
        NoNullRet("True",  NullyFalse.Coalesce(NullyTrue,  NullyFilledText                    ));
        NoNullRet("True",  NullyFalse.Coalesce(NullyTrue,  NullyFilledText, zeroMatters: false));
        NoNullRet("True",  NullyFalse.Coalesce(NullyTrue,  NullyFilledText,              false));
        NoNullRet("False", NullyFalse.Coalesce(NullyTrue,  NullyFilledText, zeroMatters       ));
        NoNullRet("False", NullyFalse.Coalesce(NullyTrue,  NullyFilledText, zeroMatters: true ));
        NoNullRet("False", NullyFalse.Coalesce(NullyTrue,  NullyFilledText,              true ));
        NoNullRet("True",  NullyFalse.Coalesce(true,       NullText                           ));
        NoNullRet("True",  NullyFalse.Coalesce(true,       NullText,        zeroMatters: false));
        NoNullRet("True",  NullyFalse.Coalesce(true,       NullText,                     false));
        NoNullRet("False", NullyFalse.Coalesce(true,       NullText,        zeroMatters       ));
        NoNullRet("False", NullyFalse.Coalesce(true,       NullText,        zeroMatters: true ));
        NoNullRet("False", NullyFalse.Coalesce(true,       NullText,                     true ));
        NoNullRet("True",  NullyFalse.Coalesce(true,       Empty                              ));
        NoNullRet("True",  NullyFalse.Coalesce(true,       Empty,           zeroMatters: false));
        NoNullRet("True",  NullyFalse.Coalesce(true,       Empty,                        false));
        NoNullRet("False", NullyFalse.Coalesce(true,       Empty,           zeroMatters       ));
        NoNullRet("False", NullyFalse.Coalesce(true,       Empty,           zeroMatters: true ));
        NoNullRet("False", NullyFalse.Coalesce(true,       Empty,                        true ));
        NoNullRet("True",  NullyFalse.Coalesce(true,       Space                              ));
        NoNullRet("True",  NullyFalse.Coalesce(true,       Space,           zeroMatters: false));
        NoNullRet("True",  NullyFalse.Coalesce(true,       Space,                        false));
        NoNullRet("False", NullyFalse.Coalesce(true,       Space,           zeroMatters       ));
        NoNullRet("False", NullyFalse.Coalesce(true,       Space,           zeroMatters: true ));
        NoNullRet("False", NullyFalse.Coalesce(true,       Space,                        true ));
        NoNullRet("True",  NullyFalse.Coalesce(true,       Text                               ));
        NoNullRet("True",  NullyFalse.Coalesce(true,       Text,            zeroMatters: false));
        NoNullRet("True",  NullyFalse.Coalesce(true,       Text,                         false));
        NoNullRet("False", NullyFalse.Coalesce(true,       Text,            zeroMatters       ));
        NoNullRet("False", NullyFalse.Coalesce(true,       Text,            zeroMatters: true ));
        NoNullRet("False", NullyFalse.Coalesce(true,       Text,                         true ));
        NoNullRet("True",  NullyFalse.Coalesce(true,       NullyEmpty                         ));
        NoNullRet("True",  NullyFalse.Coalesce(true,       NullyEmpty,      zeroMatters: false));
        NoNullRet("True",  NullyFalse.Coalesce(true,       NullyEmpty,                   false));
        NoNullRet("False", NullyFalse.Coalesce(true,       NullyEmpty,      zeroMatters       ));
        NoNullRet("False", NullyFalse.Coalesce(true,       NullyEmpty,      zeroMatters: true ));
        NoNullRet("False", NullyFalse.Coalesce(true,       NullyEmpty,                   true ));
        NoNullRet("True",  NullyFalse.Coalesce(true,       NullySpace                         ));
        NoNullRet("True",  NullyFalse.Coalesce(true,       NullySpace,      zeroMatters: false));
        NoNullRet("True",  NullyFalse.Coalesce(true,       NullySpace,                   false));
        NoNullRet("False", NullyFalse.Coalesce(true,       NullySpace,      zeroMatters       ));
        NoNullRet("False", NullyFalse.Coalesce(true,       NullySpace,      zeroMatters: true ));
        NoNullRet("False", NullyFalse.Coalesce(true,       NullySpace,                   true ));
        NoNullRet("True",  NullyFalse.Coalesce(true,       NullyFilledText                    ));
        NoNullRet("True",  NullyFalse.Coalesce(true,       NullyFilledText, zeroMatters: false));
        NoNullRet("True",  NullyFalse.Coalesce(true,       NullyFilledText,              false));
        NoNullRet("False", NullyFalse.Coalesce(true,       NullyFilledText, zeroMatters       ));
        NoNullRet("False", NullyFalse.Coalesce(true,       NullyFilledText, zeroMatters: true ));
        NoNullRet("False", NullyFalse.Coalesce(true,       NullyFilledText,              true ));
    }

    [TestMethod]
    public void Coalesce_3Args_BoolToText_ExtensionsZeroMattersFlagsInBack_Batch3()
    {
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   NullText                           ));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   NullText,        zeroMatters: false));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   NullText,                     false));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   NullText,        zeroMatters       ));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   NullText,        zeroMatters: true ));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   NullText,                     true ));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   Empty                              ));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   Empty,           zeroMatters: false));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   Empty,                        false));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   Empty,           zeroMatters       ));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   Empty,           zeroMatters: true ));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   Empty,                        true ));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   Space                              ));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   Space,           zeroMatters: false));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   Space,                        false));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   Space,           zeroMatters       ));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   Space,           zeroMatters: true ));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   Space,                        true ));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   Text                               ));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   Text,            zeroMatters: false));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   Text,                         false));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   Text,            zeroMatters       ));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   Text,            zeroMatters: true ));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   Text,                         true ));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   NullyEmpty                         ));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   NullyEmpty,      zeroMatters: false));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   NullyEmpty,                   false));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   NullyEmpty,      zeroMatters       ));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   NullyEmpty,      zeroMatters: true ));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   NullyEmpty,                   true ));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   NullySpace                         ));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   NullySpace,      zeroMatters: false));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   NullySpace,                   false));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   NullySpace,      zeroMatters       ));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   NullySpace,      zeroMatters: true ));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   NullySpace,                   true ));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   NullyFilledText                    ));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   NullyFilledText, zeroMatters: false));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   NullyFilledText,              false));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   NullyFilledText, zeroMatters       ));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   NullyFilledText, zeroMatters: true ));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   NullyFilledText,              true ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, NullText                           ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, NullText,        zeroMatters: false));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, NullText,                     false));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, NullText,        zeroMatters       ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, NullText,        zeroMatters: true ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, NullText,                     true ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, Empty                              ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, Empty,           zeroMatters: false));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, Empty,                        false));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, Empty,           zeroMatters       ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, Empty,           zeroMatters: true ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, Empty,                        true ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, Space                              ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, Space,           zeroMatters: false));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, Space,                        false));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, Space,           zeroMatters       ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, Space,           zeroMatters: true ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, Space,                        true ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, Text                               ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, Text,            zeroMatters: false));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, Text,                         false));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, Text,            zeroMatters       ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, Text,            zeroMatters: true ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, Text,                         true ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, NullyEmpty                         ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, NullyEmpty,      zeroMatters: false));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, NullyEmpty,                   false));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, NullyEmpty,      zeroMatters       ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, NullyEmpty,      zeroMatters: true ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, NullyEmpty,                   true ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, NullySpace                         ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, NullySpace,      zeroMatters: false));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, NullySpace,                   false));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, NullySpace,      zeroMatters       ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, NullySpace,      zeroMatters: true ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, NullySpace,                   true ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, NullyFilledText                    ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, NullyFilledText, zeroMatters: false));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, NullyFilledText,              false));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, NullyFilledText, zeroMatters       ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, NullyFilledText, zeroMatters: true ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, NullyFilledText,              true ));
        NoNullRet("True",  NullyTrue .Coalesce(false,      NullText                           ));
        NoNullRet("True",  NullyTrue .Coalesce(false,      NullText,        zeroMatters: false));
        NoNullRet("True",  NullyTrue .Coalesce(false,      NullText,                     false));
        NoNullRet("True",  NullyTrue .Coalesce(false,      NullText,        zeroMatters       ));
        NoNullRet("True",  NullyTrue .Coalesce(false,      NullText,        zeroMatters: true ));
        NoNullRet("True",  NullyTrue .Coalesce(false,      NullText,                     true ));
        NoNullRet("True",  NullyTrue .Coalesce(false,      Empty                              ));
        NoNullRet("True",  NullyTrue .Coalesce(false,      Empty,           zeroMatters: false));
        NoNullRet("True",  NullyTrue .Coalesce(false,      Empty,                        false));
        NoNullRet("True",  NullyTrue .Coalesce(false,      Empty,           zeroMatters       ));
        NoNullRet("True",  NullyTrue .Coalesce(false,      Empty,           zeroMatters: true ));
        NoNullRet("True",  NullyTrue .Coalesce(false,      Empty,                        true ));
        NoNullRet("True",  NullyTrue .Coalesce(false,      Space                              ));
        NoNullRet("True",  NullyTrue .Coalesce(false,      Space,           zeroMatters: false));
        NoNullRet("True",  NullyTrue .Coalesce(false,      Space,                        false));
        NoNullRet("True",  NullyTrue .Coalesce(false,      Space,           zeroMatters       ));
        NoNullRet("True",  NullyTrue .Coalesce(false,      Space,           zeroMatters: true ));
        NoNullRet("True",  NullyTrue .Coalesce(false,      Space,                        true ));
        NoNullRet("True",  NullyTrue .Coalesce(false,      Text                               ));
        NoNullRet("True",  NullyTrue .Coalesce(false,      Text,            zeroMatters: false));
        NoNullRet("True",  NullyTrue .Coalesce(false,      Text,                         false));
        NoNullRet("True",  NullyTrue .Coalesce(false,      Text,            zeroMatters       ));
        NoNullRet("True",  NullyTrue .Coalesce(false,      Text,            zeroMatters: true ));
        NoNullRet("True",  NullyTrue .Coalesce(false,      Text,                         true ));
        NoNullRet("True",  NullyTrue .Coalesce(false,      NullyEmpty                         ));
        NoNullRet("True",  NullyTrue .Coalesce(false,      NullyEmpty,      zeroMatters: false));
        NoNullRet("True",  NullyTrue .Coalesce(false,      NullyEmpty,                   false));
        NoNullRet("True",  NullyTrue .Coalesce(false,      NullyEmpty,      zeroMatters       ));
        NoNullRet("True",  NullyTrue .Coalesce(false,      NullyEmpty,      zeroMatters: true ));
        NoNullRet("True",  NullyTrue .Coalesce(false,      NullyEmpty,                   true ));
        NoNullRet("True",  NullyTrue .Coalesce(false,      NullySpace                         ));
        NoNullRet("True",  NullyTrue .Coalesce(false,      NullySpace,      zeroMatters: false));
        NoNullRet("True",  NullyTrue .Coalesce(false,      NullySpace,                   false));
        NoNullRet("True",  NullyTrue .Coalesce(false,      NullySpace,      zeroMatters       ));
        NoNullRet("True",  NullyTrue .Coalesce(false,      NullySpace,      zeroMatters: true ));
        NoNullRet("True",  NullyTrue .Coalesce(false,      NullySpace,                   true ));
        NoNullRet("True",  NullyTrue .Coalesce(false,      NullyFilledText                    ));
        NoNullRet("True",  NullyTrue .Coalesce(false,      NullyFilledText, zeroMatters: false));
        NoNullRet("True",  NullyTrue .Coalesce(false,      NullyFilledText,              false));
        NoNullRet("True",  NullyTrue .Coalesce(false,      NullyFilledText, zeroMatters       ));
        NoNullRet("True",  NullyTrue .Coalesce(false,      NullyFilledText, zeroMatters: true ));
        NoNullRet("True",  NullyTrue .Coalesce(false,      NullyFilledText,              true ));
    }

    [TestMethod]
    public void Coalesce_3Args_BoolToText_ExtensionsZeroMattersFlagsInBack_Batch4()
    {
        NoNullRet("",      false     .Coalesce(NullBool,   NullText                           ));
        NoNullRet("",      false     .Coalesce(NullBool,   NullText,        zeroMatters: false));
        NoNullRet("",      false     .Coalesce(NullBool,   NullText,                     false));
        NoNullRet("False", false     .Coalesce(NullBool,   NullText,        zeroMatters       ));
        NoNullRet("False", false     .Coalesce(NullBool,   NullText,        zeroMatters: true ));
        NoNullRet("False", false     .Coalesce(NullBool,   NullText,                     true ));
        NoNullRet("",      false     .Coalesce(NullBool,   Empty                              ));
        NoNullRet("",      false     .Coalesce(NullBool,   Empty,           zeroMatters: false));
        NoNullRet("",      false     .Coalesce(NullBool,   Empty,                        false));
        NoNullRet("False", false     .Coalesce(NullBool,   Empty,           zeroMatters       ));
        NoNullRet("False", false     .Coalesce(NullBool,   Empty,           zeroMatters: true ));
        NoNullRet("False", false     .Coalesce(NullBool,   Empty,                        true ));
        NoNullRet(" ",     false     .Coalesce(NullBool,   Space                              ));
        NoNullRet(" ",     false     .Coalesce(NullBool,   Space,           zeroMatters: false));
        NoNullRet(" ",     false     .Coalesce(NullBool,   Space,                        false));
        NoNullRet("False", false     .Coalesce(NullBool,   Space,           zeroMatters       ));
        NoNullRet("False", false     .Coalesce(NullBool,   Space,           zeroMatters: true ));
        NoNullRet("False", false     .Coalesce(NullBool,   Space,                        true ));
        NoNullRet(Text,    false     .Coalesce(NullBool,   Text                               ));
        NoNullRet(Text,    false     .Coalesce(NullBool,   Text,            zeroMatters: false));
        NoNullRet(Text,    false     .Coalesce(NullBool,   Text,                         false));
        NoNullRet("False", false     .Coalesce(NullBool,   Text,            zeroMatters       ));
        NoNullRet("False", false     .Coalesce(NullBool,   Text,            zeroMatters: true ));
        NoNullRet("False", false     .Coalesce(NullBool,   Text,                         true ));
        NoNullRet("",      false     .Coalesce(NullBool,   NullyEmpty                         ));
        NoNullRet("",      false     .Coalesce(NullBool,   NullyEmpty,      zeroMatters: false));
        NoNullRet("",      false     .Coalesce(NullBool,   NullyEmpty,                   false));
        NoNullRet("False", false     .Coalesce(NullBool,   NullyEmpty,      zeroMatters       ));
        NoNullRet("False", false     .Coalesce(NullBool,   NullyEmpty,      zeroMatters: true ));
        NoNullRet("False", false     .Coalesce(NullBool,   NullyEmpty,                   true ));
        NoNullRet(" ",     false     .Coalesce(NullBool,   NullySpace                         ));
        NoNullRet(" ",     false     .Coalesce(NullBool,   NullySpace,      zeroMatters: false));
        NoNullRet(" ",     false     .Coalesce(NullBool,   NullySpace,                   false));
        NoNullRet("False", false     .Coalesce(NullBool,   NullySpace,      zeroMatters       ));
        NoNullRet("False", false     .Coalesce(NullBool,   NullySpace,      zeroMatters: true ));
        NoNullRet("False", false     .Coalesce(NullBool,   NullySpace,                   true ));
        NoNullRet(Text,    false     .Coalesce(NullBool,   NullyFilledText                    ));
        NoNullRet(Text,    false     .Coalesce(NullBool,   NullyFilledText, zeroMatters: false));
        NoNullRet(Text,    false     .Coalesce(NullBool,   NullyFilledText,              false));
        NoNullRet("False", false     .Coalesce(NullBool,   NullyFilledText, zeroMatters       ));
        NoNullRet("False", false     .Coalesce(NullBool,   NullyFilledText, zeroMatters: true ));
        NoNullRet("False", false     .Coalesce(NullBool,   NullyFilledText,              true ));
        NoNullRet("True",  false     .Coalesce(NullyTrue,  NullText                           ));
        NoNullRet("True",  false     .Coalesce(NullyTrue,  NullText,        zeroMatters: false));
        NoNullRet("True",  false     .Coalesce(NullyTrue,  NullText,                     false));
        NoNullRet("False", false     .Coalesce(NullyTrue,  NullText,        zeroMatters       ));
        NoNullRet("False", false     .Coalesce(NullyTrue,  NullText,        zeroMatters: true ));
        NoNullRet("False", false     .Coalesce(NullyTrue,  NullText,                     true ));
        NoNullRet("True",  false     .Coalesce(NullyTrue,  Empty                              ));
        NoNullRet("True",  false     .Coalesce(NullyTrue,  Empty,           zeroMatters: false));
        NoNullRet("True",  false     .Coalesce(NullyTrue,  Empty,                        false));
        NoNullRet("False", false     .Coalesce(NullyTrue,  Empty,           zeroMatters       ));
        NoNullRet("False", false     .Coalesce(NullyTrue,  Empty,           zeroMatters: true ));
        NoNullRet("False", false     .Coalesce(NullyTrue,  Empty,                        true ));
        NoNullRet("True",  false     .Coalesce(NullyTrue,  Space                              ));
        NoNullRet("True",  false     .Coalesce(NullyTrue,  Space,           zeroMatters: false));
        NoNullRet("True",  false     .Coalesce(NullyTrue,  Space,                        false));
        NoNullRet("False", false     .Coalesce(NullyTrue,  Space,           zeroMatters       ));
        NoNullRet("False", false     .Coalesce(NullyTrue,  Space,           zeroMatters: true ));
        NoNullRet("False", false     .Coalesce(NullyTrue,  Space,                        true ));
        NoNullRet("True",  false     .Coalesce(NullyTrue,  Text                               ));
        NoNullRet("True",  false     .Coalesce(NullyTrue,  Text,            zeroMatters: false));
        NoNullRet("True",  false     .Coalesce(NullyTrue,  Text,                         false));
        NoNullRet("False", false     .Coalesce(NullyTrue,  Text,            zeroMatters       ));
        NoNullRet("False", false     .Coalesce(NullyTrue,  Text,            zeroMatters: true ));
        NoNullRet("False", false     .Coalesce(NullyTrue,  Text,                         true ));
        NoNullRet("True",  false     .Coalesce(NullyTrue,  NullyEmpty                         ));
        NoNullRet("True",  false     .Coalesce(NullyTrue,  NullyEmpty,      zeroMatters: false));
        NoNullRet("True",  false     .Coalesce(NullyTrue,  NullyEmpty,                   false));
        NoNullRet("False", false     .Coalesce(NullyTrue,  NullyEmpty,      zeroMatters       ));
        NoNullRet("False", false     .Coalesce(NullyTrue,  NullyEmpty,      zeroMatters: true ));
        NoNullRet("False", false     .Coalesce(NullyTrue,  NullyEmpty,                   true ));
        NoNullRet("True",  false     .Coalesce(NullyTrue,  NullySpace                         ));
        NoNullRet("True",  false     .Coalesce(NullyTrue,  NullySpace,      zeroMatters: false));
        NoNullRet("True",  false     .Coalesce(NullyTrue,  NullySpace,                   false));
        NoNullRet("False", false     .Coalesce(NullyTrue,  NullySpace,      zeroMatters       ));
        NoNullRet("False", false     .Coalesce(NullyTrue,  NullySpace,      zeroMatters: true ));
        NoNullRet("False", false     .Coalesce(NullyTrue,  NullySpace,                   true ));
        NoNullRet("True",  false     .Coalesce(NullyTrue,  NullyFilledText                    ));
        NoNullRet("True",  false     .Coalesce(NullyTrue,  NullyFilledText, zeroMatters: false));
        NoNullRet("True",  false     .Coalesce(NullyTrue,  NullyFilledText,              false));
        NoNullRet("False", false     .Coalesce(NullyTrue,  NullyFilledText, zeroMatters       ));
        NoNullRet("False", false     .Coalesce(NullyTrue,  NullyFilledText, zeroMatters: true ));
        NoNullRet("False", false     .Coalesce(NullyTrue,  NullyFilledText,              true ));
        NoNullRet("True",  false     .Coalesce(true,       NullText                           ));
        NoNullRet("True",  false     .Coalesce(true,       NullText,        zeroMatters: false));
        NoNullRet("True",  false     .Coalesce(true,       NullText,                     false));
        NoNullRet("False", false     .Coalesce(true,       NullText,        zeroMatters       ));
        NoNullRet("False", false     .Coalesce(true,       NullText,        zeroMatters: true ));
        NoNullRet("False", false     .Coalesce(true,       NullText,                     true ));
        NoNullRet("True",  false     .Coalesce(true,       Empty                              ));
        NoNullRet("True",  false     .Coalesce(true,       Empty,           zeroMatters: false));
        NoNullRet("True",  false     .Coalesce(true,       Empty,                        false));
        NoNullRet("False", false     .Coalesce(true,       Empty,           zeroMatters       ));
        NoNullRet("False", false     .Coalesce(true,       Empty,           zeroMatters: true ));
        NoNullRet("False", false     .Coalesce(true,       Empty,                        true ));
        NoNullRet("True",  false     .Coalesce(true,       Space                              ));
        NoNullRet("True",  false     .Coalesce(true,       Space,           zeroMatters: false));
        NoNullRet("True",  false     .Coalesce(true,       Space,                        false));
        NoNullRet("False", false     .Coalesce(true,       Space,           zeroMatters       ));
        NoNullRet("False", false     .Coalesce(true,       Space,           zeroMatters: true ));
        NoNullRet("False", false     .Coalesce(true,       Space,                        true ));
        NoNullRet("True",  false     .Coalesce(true,       Text                               ));
        NoNullRet("True",  false     .Coalesce(true,       Text,            zeroMatters: false));
        NoNullRet("True",  false     .Coalesce(true,       Text,                         false));
        NoNullRet("False", false     .Coalesce(true,       Text,            zeroMatters       ));
        NoNullRet("False", false     .Coalesce(true,       Text,            zeroMatters: true ));
        NoNullRet("False", false     .Coalesce(true,       Text,                         true ));
        NoNullRet("True",  false     .Coalesce(true,       NullyEmpty                         ));
        NoNullRet("True",  false     .Coalesce(true,       NullyEmpty,      zeroMatters: false));
        NoNullRet("True",  false     .Coalesce(true,       NullyEmpty,                   false));
        NoNullRet("False", false     .Coalesce(true,       NullyEmpty,      zeroMatters       ));
        NoNullRet("False", false     .Coalesce(true,       NullyEmpty,      zeroMatters: true ));
        NoNullRet("False", false     .Coalesce(true,       NullyEmpty,                   true ));
        NoNullRet("True",  false     .Coalesce(true,       NullySpace                         ));
        NoNullRet("True",  false     .Coalesce(true,       NullySpace,      zeroMatters: false));
        NoNullRet("True",  false     .Coalesce(true,       NullySpace,                   false));
        NoNullRet("False", false     .Coalesce(true,       NullySpace,      zeroMatters       ));
        NoNullRet("False", false     .Coalesce(true,       NullySpace,      zeroMatters: true ));
        NoNullRet("False", false     .Coalesce(true,       NullySpace,                   true ));
        NoNullRet("True",  false     .Coalesce(true,       NullyFilledText                    ));
        NoNullRet("True",  false     .Coalesce(true,       NullyFilledText, zeroMatters: false));
        NoNullRet("True",  false     .Coalesce(true,       NullyFilledText,              false));
        NoNullRet("False", false     .Coalesce(true,       NullyFilledText, zeroMatters       ));
        NoNullRet("False", false     .Coalesce(true,       NullyFilledText, zeroMatters: true ));
        NoNullRet("False", false     .Coalesce(true,       NullyFilledText,              true ));
    }

    [TestMethod]
    public void Coalesce_3Args_BoolToText_ExtensionsZeroMattersFlagsInBack_Batch5()
    {
        NoNullRet("True",  true      .Coalesce(NullBool,   NullText                           ));
        NoNullRet("True",  true      .Coalesce(NullBool,   NullText,        zeroMatters: false));
        NoNullRet("True",  true      .Coalesce(NullBool,   NullText,                     false));
        NoNullRet("True",  true      .Coalesce(NullBool,   NullText,        zeroMatters       ));
        NoNullRet("True",  true      .Coalesce(NullBool,   NullText,        zeroMatters: true ));
        NoNullRet("True",  true      .Coalesce(NullBool,   NullText,                     true ));
        NoNullRet("True",  true      .Coalesce(NullBool,   Empty                              ));
        NoNullRet("True",  true      .Coalesce(NullBool,   Empty,           zeroMatters: false));
        NoNullRet("True",  true      .Coalesce(NullBool,   Empty,                        false));
        NoNullRet("True",  true      .Coalesce(NullBool,   Empty,           zeroMatters       ));
        NoNullRet("True",  true      .Coalesce(NullBool,   Empty,           zeroMatters: true ));
        NoNullRet("True",  true      .Coalesce(NullBool,   Empty,                        true ));
        NoNullRet("True",  true      .Coalesce(NullBool,   Space                              ));
        NoNullRet("True",  true      .Coalesce(NullBool,   Space,           zeroMatters: false));
        NoNullRet("True",  true      .Coalesce(NullBool,   Space,                        false));
        NoNullRet("True",  true      .Coalesce(NullBool,   Space,           zeroMatters       ));
        NoNullRet("True",  true      .Coalesce(NullBool,   Space,           zeroMatters: true ));
        NoNullRet("True",  true      .Coalesce(NullBool,   Space,                        true ));
        NoNullRet("True",  true      .Coalesce(NullBool,   Text                               ));
        NoNullRet("True",  true      .Coalesce(NullBool,   Text,            zeroMatters: false));
        NoNullRet("True",  true      .Coalesce(NullBool,   Text,                         false));
        NoNullRet("True",  true      .Coalesce(NullBool,   Text,            zeroMatters       ));
        NoNullRet("True",  true      .Coalesce(NullBool,   Text,            zeroMatters: true ));
        NoNullRet("True",  true      .Coalesce(NullBool,   Text,                         true ));
        NoNullRet("True",  true      .Coalesce(NullBool,   NullyEmpty                         ));
        NoNullRet("True",  true      .Coalesce(NullBool,   NullyEmpty,      zeroMatters: false));
        NoNullRet("True",  true      .Coalesce(NullBool,   NullyEmpty,                   false));
        NoNullRet("True",  true      .Coalesce(NullBool,   NullyEmpty,      zeroMatters       ));
        NoNullRet("True",  true      .Coalesce(NullBool,   NullyEmpty,      zeroMatters: true ));
        NoNullRet("True",  true      .Coalesce(NullBool,   NullyEmpty,                   true ));
        NoNullRet("True",  true      .Coalesce(NullBool,   NullySpace                         ));
        NoNullRet("True",  true      .Coalesce(NullBool,   NullySpace,      zeroMatters: false));
        NoNullRet("True",  true      .Coalesce(NullBool,   NullySpace,                   false));
        NoNullRet("True",  true      .Coalesce(NullBool,   NullySpace,      zeroMatters       ));
        NoNullRet("True",  true      .Coalesce(NullBool,   NullySpace,      zeroMatters: true ));
        NoNullRet("True",  true      .Coalesce(NullBool,   NullySpace,                   true ));
        NoNullRet("True",  true      .Coalesce(NullBool,   NullyFilledText                    ));
        NoNullRet("True",  true      .Coalesce(NullBool,   NullyFilledText, zeroMatters: false));
        NoNullRet("True",  true      .Coalesce(NullBool,   NullyFilledText,              false));
        NoNullRet("True",  true      .Coalesce(NullBool,   NullyFilledText, zeroMatters       ));
        NoNullRet("True",  true      .Coalesce(NullBool,   NullyFilledText, zeroMatters: true ));
        NoNullRet("True",  true      .Coalesce(NullBool,   NullyFilledText,              true ));
        NoNullRet("True",  true      .Coalesce(NullyFalse, NullText                           ));
        NoNullRet("True",  true      .Coalesce(NullyFalse, NullText,        zeroMatters: false));
        NoNullRet("True",  true      .Coalesce(NullyFalse, NullText,                     false));
        NoNullRet("True",  true      .Coalesce(NullyFalse, NullText,        zeroMatters       ));
        NoNullRet("True",  true      .Coalesce(NullyFalse, NullText,        zeroMatters: true ));
        NoNullRet("True",  true      .Coalesce(NullyFalse, NullText,                     true ));
        NoNullRet("True",  true      .Coalesce(NullyFalse, Empty                              ));
        NoNullRet("True",  true      .Coalesce(NullyFalse, Empty,           zeroMatters: false));
        NoNullRet("True",  true      .Coalesce(NullyFalse, Empty,                        false));
        NoNullRet("True",  true      .Coalesce(NullyFalse, Empty,           zeroMatters       ));
        NoNullRet("True",  true      .Coalesce(NullyFalse, Empty,           zeroMatters: true ));
        NoNullRet("True",  true      .Coalesce(NullyFalse, Empty,                        true ));
        NoNullRet("True",  true      .Coalesce(NullyFalse, Space                              ));
        NoNullRet("True",  true      .Coalesce(NullyFalse, Space,           zeroMatters: false));
        NoNullRet("True",  true      .Coalesce(NullyFalse, Space,                        false));
        NoNullRet("True",  true      .Coalesce(NullyFalse, Space,           zeroMatters       ));
        NoNullRet("True",  true      .Coalesce(NullyFalse, Space,           zeroMatters: true ));
        NoNullRet("True",  true      .Coalesce(NullyFalse, Space,                        true ));
        NoNullRet("True",  true      .Coalesce(NullyFalse, Text                               ));
        NoNullRet("True",  true      .Coalesce(NullyFalse, Text,            zeroMatters: false));
        NoNullRet("True",  true      .Coalesce(NullyFalse, Text,                         false));
        NoNullRet("True",  true      .Coalesce(NullyFalse, Text,            zeroMatters       ));
        NoNullRet("True",  true      .Coalesce(NullyFalse, Text,            zeroMatters: true ));
        NoNullRet("True",  true      .Coalesce(NullyFalse, Text,                         true ));
        NoNullRet("True",  true      .Coalesce(NullyFalse, NullyEmpty                         ));
        NoNullRet("True",  true      .Coalesce(NullyFalse, NullyEmpty,      zeroMatters: false));
        NoNullRet("True",  true      .Coalesce(NullyFalse, NullyEmpty,                   false));
        NoNullRet("True",  true      .Coalesce(NullyFalse, NullyEmpty,      zeroMatters       ));
        NoNullRet("True",  true      .Coalesce(NullyFalse, NullyEmpty,      zeroMatters: true ));
        NoNullRet("True",  true      .Coalesce(NullyFalse, NullyEmpty,                   true ));
        NoNullRet("True",  true      .Coalesce(NullyFalse, NullySpace                         ));
        NoNullRet("True",  true      .Coalesce(NullyFalse, NullySpace,      zeroMatters: false));
        NoNullRet("True",  true      .Coalesce(NullyFalse, NullySpace,                   false));
        NoNullRet("True",  true      .Coalesce(NullyFalse, NullySpace,      zeroMatters       ));
        NoNullRet("True",  true      .Coalesce(NullyFalse, NullySpace,      zeroMatters: true ));
        NoNullRet("True",  true      .Coalesce(NullyFalse, NullySpace,                   true ));
        NoNullRet("True",  true      .Coalesce(NullyFalse, NullyFilledText                    ));
        NoNullRet("True",  true      .Coalesce(NullyFalse, NullyFilledText, zeroMatters: false));
        NoNullRet("True",  true      .Coalesce(NullyFalse, NullyFilledText,              false));
        NoNullRet("True",  true      .Coalesce(NullyFalse, NullyFilledText, zeroMatters       ));
        NoNullRet("True",  true      .Coalesce(NullyFalse, NullyFilledText, zeroMatters: true ));
        NoNullRet("True",  true      .Coalesce(NullyFalse, NullyFilledText,              true ));
    }
}