namespace JJ.Framework.Existence.Core;

/// <inheritdoc cref="_filledin" />
public static class FilledInCollectionExtensions
{
    // FilledIn (Extensions)
    
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T>  ([NotNullWhen(true )] this T[]                                        ? coll)                   => HasArray(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T>  ([NotNullWhen(true )] this IList<T>                                   ? coll)                   => HasCollT(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T>  ([NotNullWhen(true )] this ISet<T>                                    ? coll)                   => HasCollT(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T,U>([NotNullWhen(true )] this IDictionary<T,U>                           ? coll)                   => HasCollT(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T>  ([NotNullWhen(true )] this ICollection<T>                             ? coll)                   => HasCollT(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T,U>([NotNullWhen(true )] this ILookup<T,U>                               ? coll)                   => HasLookup(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T>  ([NotNullWhen(true )] this IEnumerable<T>                             ? coll)                   => HasEnumerable(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T>  ([NotNullWhen(true )] this List<T>                                    ? coll)                   => HasColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T>  ([NotNullWhen(true )] this HashSet<T>                                 ? coll)                   => HasCollT(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T>  ([NotNullWhen(true )] this Stack<T>                                   ? coll)                   => HasColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T>  ([NotNullWhen(true )] this Queue<T>                                   ? coll)                   => HasColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T>  ([NotNullWhen(true )] this LinkedList<T>                              ? coll)                   => HasColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T,U>([NotNullWhen(true )] this SortedList<T,U>                            ? coll) where T : notnull => HasColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T>  ([NotNullWhen(true )] this SortedSet<T>                               ? coll) where T : notnull => HasColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T,U>([NotNullWhen(true )] this Dictionary<T,U>                            ? coll) where T : notnull => HasColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T,U>([NotNullWhen(true )] this Dictionary<T,U>.KeyCollection              ? coll) where T : notnull => HasColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T,U>([NotNullWhen(true )] this Dictionary<T,U>.ValueCollection            ? coll) where T : notnull => HasColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T>  ([NotNullWhen(true )] this IImmutableList<T>                          ? coll)                   => HasReadOnlyColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T>  ([NotNullWhen(true )] this IImmutableSet<T>                           ? coll)                   => HasReadOnlyColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T>  ([NotNullWhen(true )] this IImmutableStack<T>                         ? coll)                   => Has_ImmutableStack(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T>  ([NotNullWhen(true )] this IImmutableQueue<T>                         ? coll)                   => Has_ImmutableQueue(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T,U>([NotNullWhen(true )] this IImmutableDictionary<T,U>                  ? coll)                   => HasReadOnlyColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T>  ([NotNullWhen(true )] this ImmutableArray<T>                            coll)                   => Has_ImmutableArray(ref coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T>  ([NotNullWhen(true )] this ImmutableArray<T>                          ? coll)                   => Has_ImmutableArray(ref coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T>  ([NotNullWhen(true )] this ImmutableArray<T>.Builder                  ? coll)                   => HasCollT(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T>  ([NotNullWhen(true )] this ImmutableList<T>                           ? coll)                   => HasColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T>  ([NotNullWhen(true )] this ImmutableList<T>.Builder                   ? coll)                   => HasColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T>  ([NotNullWhen(true )] this ImmutableHashSet<T>                        ? coll)                   => HasColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T>  ([NotNullWhen(true )] this ImmutableHashSet<T>.Builder                ? coll)                   => HasCollT(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T>  ([NotNullWhen(true )] this ImmutableStack<T>                          ? coll)                   => Has_ImmutableStack(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T>  ([NotNullWhen(true )] this ImmutableQueue<T>                          ? coll)                   => Has_ImmutableQueue(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T,U>([NotNullWhen(true )] this ImmutableDictionary<T,U>                   ? coll) where T : notnull => HasColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T,U>([NotNullWhen(true )] this ImmutableDictionary<T,U>.Builder           ? coll) where T : notnull => HasColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T>  ([NotNullWhen(true )] this ImmutableSortedSet<T>                      ? coll)                   => HasColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T>  ([NotNullWhen(true )] this ImmutableSortedSet<T>.Builder              ? coll)                   => HasColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T,U>([NotNullWhen(true )] this ImmutableSortedDictionary<T,U>             ? coll) where T : notnull => HasColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T,U>([NotNullWhen(true )] this ImmutableSortedDictionary<T,U>.Builder     ? coll) where T : notnull => HasColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T>  ([NotNullWhen(true )] this IReadOnlyCollection<T>                     ? coll)                   => HasReadOnlyColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T>  ([NotNullWhen(true )] this IReadOnlyList<T>                           ? coll)                   => HasReadOnlyColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T,U>([NotNullWhen(true )] this IReadOnlyDictionary<T,U>                   ? coll)                   => HasReadOnlyColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T>  ([NotNullWhen(true )] this ReadOnlyCollection<T>                      ? coll)                   => HasReadOnlyColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T,U>([NotNullWhen(true )] this ReadOnlyDictionary<T,U>                    ? coll) where T : notnull => HasReadOnlyColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T,U>([NotNullWhen(true )] this ReadOnlyDictionary<T,U>.KeyCollection      ? coll) where T : notnull => HasReadOnlyColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T,U>([NotNullWhen(true )] this ReadOnlyDictionary<T,U>.ValueCollection    ? coll) where T : notnull => HasReadOnlyColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T>  ([NotNullWhen(true )] this ArraySegment<T>                              coll)                   => HasCollT   (coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T>  ([NotNullWhen(true )] this ArraySegment<T>                            ? coll)                   => HasCollT<T>(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T>  ([NotNullWhen(true )] this Memory<T>                                    coll)                   => Has_Memory(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T>  ([NotNullWhen(true )] this Memory<T>                                  ? coll)                   => Has_Memory(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T>  ([NotNullWhen(true )] this Span<T>                                      coll)                   => Has_Span(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T>  ([NotNullWhen(true )] this ReadOnlyMemory<T>                            coll)                   => Has_ReadOnlyMemory(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T>  ([NotNullWhen(true )] this ReadOnlyMemory<T>                          ? coll)                   => Has_ReadOnlyMemory(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T>  ([NotNullWhen(true )] this ReadOnlySpan<T>                              coll)                   => Has_ReadOnlySpan(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T>  ([NotNullWhen(true )] this ReadOnlySequence<T>                          coll)                   => Has_ReadOnlySequence(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T>  ([NotNullWhen(true )] this ReadOnlySequence<T>                        ? coll)                   => Has_ReadOnlySequence(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T>  ([NotNullWhen(true )] this ConcurrentBag<T>                           ? coll)                   => HasColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T>  ([NotNullWhen(true )] this ConcurrentQueue<T>                         ? coll)                   => HasColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T>  ([NotNullWhen(true )] this ConcurrentStack<T>                         ? coll)                   => HasColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T,U>([NotNullWhen(true )] this ConcurrentDictionary<T,U>                  ? coll) where T : notnull => HasColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T>  ([NotNullWhen(true )] this BlockingCollection<T>                      ? coll)                   => HasColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T>  ([NotNullWhen(true )] this IProducerConsumerCollection<T>             ? coll)                   => HasColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T,U>([NotNullWhen(true )] this SortedDictionary<T,U>                      ? coll) where T : notnull => HasColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T,U>([NotNullWhen(true )] this SortedDictionary<T,U>.KeyCollection        ? coll) where T : notnull => HasColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T,U>([NotNullWhen(true )] this SortedDictionary<T,U>.ValueCollection      ? coll) where T : notnull => HasColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T>  ([NotNullWhen(true )] this Collection<T>                              ? coll)                   => HasColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T,U>([NotNullWhen(true )] this KeyedCollection<T,U>                       ? coll) where T : notnull => HasColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T>  ([NotNullWhen(true )] this ObservableCollection<T>                    ? coll)                   => HasColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T>  ([NotNullWhen(true )] this ReadOnlyObservableCollection<T>            ? coll)                   => HasColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn     ([NotNullWhen(true )] this ArrayList                                  ? coll)                   => HasColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn     ([NotNullWhen(true )] this BitArray                                   ? coll)                   => HasColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn     ([NotNullWhen(true )] this CollectionBase                             ? coll)                   => HasColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn     ([NotNullWhen(true )] this DictionaryBase                             ? coll)                   => HasColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn     ([NotNullWhen(true )] this Hashtable                                  ? coll)                   => HasColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn     ([NotNullWhen(true )] this Queue                                      ? coll)                   => HasColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn     ([NotNullWhen(true )] this ReadOnlyCollectionBase                     ? coll)                   => HasColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn     ([NotNullWhen(true )] this SortedList                                 ? coll)                   => HasColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn     ([NotNullWhen(true )] this Stack                                      ? coll)                   => HasColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn     ([NotNullWhen(true )] this HybridDictionary                           ? coll)                   => HasColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn     ([NotNullWhen(true )] this ListDictionary                             ? coll)                   => HasColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn     ([NotNullWhen(true )] this NameObjectCollectionBase                   ? coll)                   => HasColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn     ([NotNullWhen(true )] this NameObjectCollectionBase.KeysCollection    ? coll)                   => HasColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn     ([NotNullWhen(true )] this NameValueCollection                        ? coll)                   => HasColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn     ([NotNullWhen(true )] this OrderedDictionary                          ? coll)                   => HasColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn     ([NotNullWhen(true )] this StringCollection                           ? coll)                   => HasColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn     ([NotNullWhen(true )] this StringDictionary                           ? coll)                   => Has_StringDictionary(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn     ([NotNullWhen(true )] this IOrderedDictionary                         ? coll)                   => HasColl(coll);
    #if NET9_0_OR_GREATER
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T,U>([NotNullWhen(true )] this OrderedDictionary<T,U>                     ? coll) where T : notnull => HasColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T,U>([NotNullWhen(true )] this OrderedDictionary<T,U>.KeyCollection       ? coll) where T : notnull => HasColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T,U>([NotNullWhen(true )] this OrderedDictionary<T,U>.ValueCollection     ? coll) where T : notnull => HasColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T>  ([NotNullWhen(true )] this IReadOnlySet<T>                            ? coll)                   => HasReadOnlyColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T>  ([NotNullWhen(true )] this ReadOnlySet<T>                             ? coll)                   => HasReadOnlyColl(coll);
    #endif
    #if NET8_0_OR_GREATER                                                                                 
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T>  ([NotNullWhen(true )] this FrozenSet<T>                               ? coll)                   => HasColl(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T,U>([NotNullWhen(true )] this FrozenDictionary<T, U>                     ? coll) where T : notnull => HasColl(coll);
    #endif                                                                                                                          
    #if NET6_0_OR_GREATER
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T,U>([NotNullWhen(true )] this PriorityQueue<T,U>                         ? coll)                   => Has_PriorityQueue(coll);
    /// <inheritdoc cref="_filledin"/>
    public static bool FilledIn<T,U>([NotNullWhen(true )] this PriorityQueue<T,U>.UnorderedItemsCollection? coll)                   => HasColl(coll);
    #endif
}