namespace JJ.Framework.Existence.Core;

/// <inheritdoc cref="_isnully" />
public static class IsNullyCollectionExtensions
{
    // IsNully (Extensions)
    
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T>  ([NotNullWhen(false)] this T[]                                        ? coll)                   => !HasArray(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T>  ([NotNullWhen(false)] this IList<T>                                   ? coll)                   => !HasCollT(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T>  ([NotNullWhen(false)] this ISet<T>                                    ? coll)                   => !HasCollT(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T,U>([NotNullWhen(false)] this IDictionary<T,U>                           ? coll)                   => !HasCollT(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T>  ([NotNullWhen(false)] this ICollection<T>                             ? coll)                   => !HasCollT(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T,U>([NotNullWhen(false)] this ILookup<T,U>                               ? coll)                   => !HasLookup(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T>  ([NotNullWhen(false)] this IEnumerable<T>                             ? coll)                   => !HasEnumerable(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T>  ([NotNullWhen(false)] this List<T>                                    ? coll)                   => !HasColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T>  ([NotNullWhen(false)] this HashSet<T>                                 ? coll)                   => !HasCollT(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T>  ([NotNullWhen(false)] this Stack<T>                                   ? coll)                   => !HasColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T>  ([NotNullWhen(false)] this Queue<T>                                   ? coll)                   => !HasColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T>  ([NotNullWhen(false)] this LinkedList<T>                              ? coll)                   => !HasColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T,U>([NotNullWhen(false)] this SortedList<T,U>                            ? coll) where T : notnull => !HasColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T>  ([NotNullWhen(false)] this SortedSet<T>                               ? coll) where T : notnull => !HasColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T,U>([NotNullWhen(false)] this Dictionary<T,U>                            ? coll) where T : notnull => !HasColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T,U>([NotNullWhen(false)] this Dictionary<T,U>.KeyCollection              ? coll) where T : notnull => !HasColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T,U>([NotNullWhen(false)] this Dictionary<T,U>.ValueCollection            ? coll) where T : notnull => !HasColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T>  ([NotNullWhen(false)] this IImmutableList<T>                          ? coll)                   => !HasReadOnlyColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T>  ([NotNullWhen(false)] this IImmutableSet<T>                           ? coll)                   => !HasReadOnlyColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T>  ([NotNullWhen(false)] this IImmutableStack<T>                         ? coll)                   => !Has_ImmutableStack(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T>  ([NotNullWhen(false)] this IImmutableQueue<T>                         ? coll)                   => !Has_ImmutableQueue(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T,U>([NotNullWhen(false)] this IImmutableDictionary<T,U>                  ? coll)                   => !HasReadOnlyColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T>  ([NotNullWhen(false)] this ImmutableArray<T>                            coll)                   => !Has_ImmutableArray(ref coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T>  ([NotNullWhen(false)] this ImmutableArray<T>                          ? coll)                   => !Has_ImmutableArray(ref coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T>  ([NotNullWhen(false)] this ImmutableArray<T>.Builder                  ? coll)                   => !HasCollT(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T>  ([NotNullWhen(false)] this ImmutableList<T>                           ? coll)                   => !HasColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T>  ([NotNullWhen(false)] this ImmutableList<T>.Builder                   ? coll)                   => !HasColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T>  ([NotNullWhen(false)] this ImmutableHashSet<T>                        ? coll)                   => !HasColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T>  ([NotNullWhen(false)] this ImmutableHashSet<T>.Builder                ? coll)                   => !HasCollT(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T>  ([NotNullWhen(false)] this ImmutableStack<T>                          ? coll)                   => !Has_ImmutableStack(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T>  ([NotNullWhen(false)] this ImmutableQueue<T>                          ? coll)                   => !Has_ImmutableQueue(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T,U>([NotNullWhen(false)] this ImmutableDictionary<T,U>                   ? coll) where T : notnull => !HasColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T,U>([NotNullWhen(false)] this ImmutableDictionary<T,U>.Builder           ? coll) where T : notnull => !HasColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T>  ([NotNullWhen(false)] this ImmutableSortedSet<T>                      ? coll)                   => !HasColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T>  ([NotNullWhen(false)] this ImmutableSortedSet<T>.Builder              ? coll)                   => !HasColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T,U>([NotNullWhen(false)] this ImmutableSortedDictionary<T,U>             ? coll) where T : notnull => !HasColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T,U>([NotNullWhen(false)] this ImmutableSortedDictionary<T,U>.Builder     ? coll) where T : notnull => !HasColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T>  ([NotNullWhen(false)] this IReadOnlyCollection<T>                     ? coll)                   => !HasReadOnlyColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T>  ([NotNullWhen(false)] this IReadOnlyList<T>                           ? coll)                   => !HasReadOnlyColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T,U>([NotNullWhen(false)] this IReadOnlyDictionary<T,U>                   ? coll)                   => !HasReadOnlyColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T>  ([NotNullWhen(false)] this ReadOnlyCollection<T>                      ? coll)                   => !HasReadOnlyColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T,U>([NotNullWhen(false)] this ReadOnlyDictionary<T,U>                    ? coll) where T : notnull => !HasReadOnlyColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T,U>([NotNullWhen(false)] this ReadOnlyDictionary<T,U>.KeyCollection      ? coll) where T : notnull => !HasReadOnlyColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T,U>([NotNullWhen(false)] this ReadOnlyDictionary<T,U>.ValueCollection    ? coll) where T : notnull => !HasReadOnlyColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T>  ([NotNullWhen(false)] this ArraySegment<T>                              coll)                   => !HasCollT   (coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T>  ([NotNullWhen(false)] this ArraySegment<T>                            ? coll)                   => !HasCollT<T>(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T>  ([NotNullWhen(false)] this Memory<T>                                    coll)                   => !Has_Memory(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T>  ([NotNullWhen(false)] this Memory<T>                                  ? coll)                   => !Has_Memory(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T>  ([NotNullWhen(false)] this Span<T>                                      coll)                   => !Has_Span(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T>  ([NotNullWhen(false)] this ReadOnlyMemory<T>                            coll)                   => !Has_ReadOnlyMemory(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T>  ([NotNullWhen(false)] this ReadOnlyMemory<T>                          ? coll)                   => !Has_ReadOnlyMemory(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T>  ([NotNullWhen(false)] this ReadOnlySpan<T>                              coll)                   => !Has_ReadOnlySpan(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T>  ([NotNullWhen(false)] this ReadOnlySequence<T>                          coll)                   => !Has_ReadOnlySequence(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T>  ([NotNullWhen(false)] this ReadOnlySequence<T>                        ? coll)                   => !Has_ReadOnlySequence(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T>  ([NotNullWhen(false)] this ConcurrentBag<T>                           ? coll)                   => !HasColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T>  ([NotNullWhen(false)] this ConcurrentQueue<T>                         ? coll)                   => !HasColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T>  ([NotNullWhen(false)] this ConcurrentStack<T>                         ? coll)                   => !HasColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T,U>([NotNullWhen(false)] this ConcurrentDictionary<T,U>                  ? coll) where T : notnull => !HasColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T>  ([NotNullWhen(false)] this BlockingCollection<T>                      ? coll)                   => !HasColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T>  ([NotNullWhen(false)] this IProducerConsumerCollection<T>             ? coll)                   => !HasColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T,U>([NotNullWhen(false)] this SortedDictionary<T,U>                      ? coll) where T : notnull => !HasColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T,U>([NotNullWhen(false)] this SortedDictionary<T,U>.KeyCollection        ? coll) where T : notnull => !HasColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T,U>([NotNullWhen(false)] this SortedDictionary<T,U>.ValueCollection      ? coll) where T : notnull => !HasColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T>  ([NotNullWhen(false)] this Collection<T>                              ? coll)                   => !HasColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T,U>([NotNullWhen(false)] this KeyedCollection<T,U>                       ? coll) where T : notnull => !HasColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T>  ([NotNullWhen(false)] this ObservableCollection<T>                    ? coll)                   => !HasColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T>  ([NotNullWhen(false)] this ReadOnlyObservableCollection<T>            ? coll)                   => !HasColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully      ([NotNullWhen(false)] this ArrayList                                  ? coll)                   => !HasColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully      ([NotNullWhen(false)] this BitArray                                   ? coll)                   => !HasColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully      ([NotNullWhen(false)] this CollectionBase                             ? coll)                   => !HasColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully      ([NotNullWhen(false)] this DictionaryBase                             ? coll)                   => !HasColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully      ([NotNullWhen(false)] this Hashtable                                  ? coll)                   => !HasColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully      ([NotNullWhen(false)] this Queue                                      ? coll)                   => !HasColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully      ([NotNullWhen(false)] this ReadOnlyCollectionBase                     ? coll)                   => !HasColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully      ([NotNullWhen(false)] this SortedList                                 ? coll)                   => !HasColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully      ([NotNullWhen(false)] this Stack                                      ? coll)                   => !HasColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully      ([NotNullWhen(false)] this HybridDictionary                           ? coll)                   => !HasColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully      ([NotNullWhen(false)] this ListDictionary                             ? coll)                   => !HasColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully      ([NotNullWhen(false)] this NameObjectCollectionBase                   ? coll)                   => !HasColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully      ([NotNullWhen(false)] this NameObjectCollectionBase.KeysCollection    ? coll)                   => !HasColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully      ([NotNullWhen(false)] this NameValueCollection                        ? coll)                   => !HasColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully      ([NotNullWhen(false)] this OrderedDictionary                          ? coll)                   => !HasColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully      ([NotNullWhen(false)] this StringCollection                           ? coll)                   => !HasColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully      ([NotNullWhen(false)] this StringDictionary                           ? coll)                   => !Has_StringDictionary(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully      ([NotNullWhen(false)] this IOrderedDictionary                         ? coll)                   => !HasColl(coll);
    #if NET9_0_OR_GREATER                                                                                 
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T,U>([NotNullWhen(false)] this OrderedDictionary<T,U>                     ? coll) where T : notnull => !HasColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T,U>([NotNullWhen(false)] this OrderedDictionary<T,U>.KeyCollection       ? coll) where T : notnull => !HasColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T,U>([NotNullWhen(false)] this OrderedDictionary<T,U>.ValueCollection     ? coll) where T : notnull => !HasColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T>  ([NotNullWhen(false)] this IReadOnlySet<T>                            ? coll)                   => !HasReadOnlyColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T>  ([NotNullWhen(false)] this ReadOnlySet<T>                             ? coll)                   => !HasReadOnlyColl(coll);
    #endif
    #if NET8_0_OR_GREATER                                                                                 
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T>  ([NotNullWhen(false)] this FrozenSet<T>                               ? coll)                   => !HasColl(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T,U>([NotNullWhen(false)] this FrozenDictionary<T, U>                     ? coll) where T : notnull => !HasColl(coll);
    #endif                                                                                                                          
    #if NET6_0_OR_GREATER
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T,U>([NotNullWhen(false)] this PriorityQueue<T,U>                         ? coll)                   => !Has_PriorityQueue(coll);
    /// <inheritdoc cref="_isnully"/>
    public static bool IsNully <T,U>([NotNullWhen(false)] this PriorityQueue<T,U>.UnorderedItemsCollection? coll)                   => !HasColl(coll);
    #endif
}