global using System;
global using System.Collections.Generic;
global using System.Diagnostics.CodeAnalysis;
global using JJ.Framework.Existence.Core.Tests.Helpers;
global using JJ.Framework.Existence.Core.Collections.Tests;
global using Microsoft.VisualStudio.TestTools.UnitTesting;
global using static System.String;
global using static System.Console;
global using static System.Environment;
global using static JJ.Framework.Existence.Core.FilledInHelper;
global using static JJ.Framework.Existence.Core.SpaceMatters;
global using static JJ.Framework.Testing.Core.AssertCore;
global using static JJ.Framework.Testing.Core.TestRunner;
