bool success = 
RunTests<Coalesce_1Arg_Tests>() &&
RunTests<Coalesce_2Args_FlagsInBack>() &&
RunTests<Coalesce_2Args_FlagsInFront>() &&
RunTests<Coalesce_2Args_NoFlags>() &&
RunTests<Coalesce_3Args_Objects>() &&
RunTests<Coalesce_3Args_ObjectsToText>() &&
RunTests<Coalesce_3Args_SBs_Extensions_NoFlags>() &&
RunTests<Coalesce_3Args_SBs_ExtensionsSpaceMattersNoExplicit_FlagsInBack>() &&
RunTests<Coalesce_3Args_SBs_ExtensionsSpaceMattersNoExplicit_FlagsInFront>() &&
RunTests<Coalesce_3Args_SBs_ExtensionsSpaceMattersYesExplicitBool_FlagsInBack>() &&
RunTests<Coalesce_3Args_SBs_ExtensionsSpaceMattersYesExplicitBool_FlagsInFront>() &&
RunTests<Coalesce_3Args_SBs_ExtensionsSpaceMattersYesMagicBool_FlagsInBack>() &&
RunTests<Coalesce_3Args_SBs_ExtensionsSpaceMattersYesMagicBool_FlagsInFront>() &&
RunTests<Coalesce_3Args_SBs_Static_NoFlags>() &&
RunTests<Coalesce_3Args_SBs_StaticSpaceMattersNoExplicit_FlagsInBack>() &&
RunTests<Coalesce_3Args_SBs_StaticSpaceMattersNoExplicit_FlagsInFront>() &&
RunTests<Coalesce_3Args_SBs_StaticSpaceMattersYesExplicitBool_FlagsInBack>() &&
RunTests<Coalesce_3Args_SBs_StaticSpaceMattersYesExplicitBool_FlagsInFront>() &&
RunTests<Coalesce_3Args_SBs_StaticSpaceMattersYesMagicBool_FlagsInBack>() &&
RunTests<Coalesce_3Args_SBs_StaticSpaceMattersYesMagicBool_FlagsInFront>() &&
RunTests<Coalesce_3Args_SBTextCombos_Extensions_NoFlags>() &&
RunTests<Coalesce_3Args_SBTextCombos_ExtensionsSpaceMattersNoExplicit_FlagsInBack>() &&
RunTests<Coalesce_3Args_SBTextCombos_ExtensionsSpaceMattersNoExplicit_FlagsInFront>() &&
RunTests<Coalesce_3Args_SBTextCombos_ExtensionsSpaceMattersYesExplicitBool_FlagsInBack>() &&
RunTests<Coalesce_3Args_SBTextCombos_ExtensionsSpaceMattersYesExplicitBool_FlagsInFront>() &&
RunTests<Coalesce_3Args_SBTextCombos_ExtensionsSpaceMattersYesMagicBool_FlagsInBack>() &&
RunTests<Coalesce_3Args_SBTextCombos_ExtensionsSpaceMattersYesMagicBool_FlagsInFront>() &&
RunTests<Coalesce_3Args_SBTextCombos_Static_NoFlags>() &&
RunTests<Coalesce_3Args_SBTextCombos_StaticSpaceMattersNoExplicit_FlagsInBack>() &&
RunTests<Coalesce_3Args_SBTextCombos_StaticSpaceMattersNoExplicit_FlagsInFront>() &&
RunTests<Coalesce_3Args_SBTextCombos_StaticSpaceMattersYesExplicitBool_FlagsInBack>() &&
RunTests<Coalesce_3Args_SBTextCombos_StaticSpaceMattersYesExplicitBool_FlagsInFront>() &&
RunTests<Coalesce_3Args_SBTextCombos_StaticSpaceMattersYesMagicBool_FlagsInBack>() &&
RunTests<Coalesce_3Args_SBTextCombos_StaticSpaceMattersYesMagicBool_FlagsInFront>() &&
RunTests<Coalesce_3Args_SBToText_Extensions_NoFlags>() &&
RunTests<Coalesce_3Args_SBToText_ExtensionsSpaceMattersNoExplicit_FlagsInBack>() &&
RunTests<Coalesce_3Args_SBToText_ExtensionsSpaceMattersNoExplicit_FlagsInFront>() &&
RunTests<Coalesce_3Args_SBToText_ExtensionsSpaceMattersYesExplicitBool_FlagsInBack>() &&
RunTests<Coalesce_3Args_SBToText_ExtensionsSpaceMattersYesExplicitBool_FlagsInFront>() &&
RunTests<Coalesce_3Args_SBToText_ExtensionsSpaceMattersYesMagicBool_FlagsInBack>() &&
RunTests<Coalesce_3Args_SBToText_ExtensionsSpaceMattersYesMagicBool_FlagsInFront>() &&
RunTests<Coalesce_3Args_SBToText_Static_NoFlags>() &&
RunTests<Coalesce_3Args_SBToText_StaticSpaceMattersNoExplicit_FlagsInBack>() &&
RunTests<Coalesce_3Args_SBToText_StaticSpaceMattersNoExplicit_FlagsInFront>() &&
RunTests<Coalesce_3Args_SBToText_StaticSpaceMattersYesExplicitBool_FlagsInBack>() &&
RunTests<Coalesce_3Args_SBToText_StaticSpaceMattersYesExplicitBool_FlagsInFront>() &&
RunTests<Coalesce_3Args_SBToText_StaticSpaceMattersYesMagicBool_FlagsInBack>() &&
RunTests<Coalesce_3Args_SBToText_StaticSpaceMattersYesMagicBool_FlagsInFront>() &&
RunTests<Coalesce_3Args_Text_Extensions_NoFlags>() &&
RunTests<Coalesce_3Args_Text_ExtensionsSpaceMattersNoExplicit_FlagsInBack>() &&
RunTests<Coalesce_3Args_Text_ExtensionsSpaceMattersNoExplicit_FlagsInFront>() &&
RunTests<Coalesce_3Args_Text_ExtensionsSpaceMattersYesExplicitBool_FlagsInBack>() &&
RunTests<Coalesce_3Args_Text_ExtensionsSpaceMattersYesExplicitBool_FlagsInFront>() &&
RunTests<Coalesce_3Args_Text_ExtensionsSpaceMattersYesMagicBool_FlagsInBack>() &&
RunTests<Coalesce_3Args_Text_ExtensionsSpaceMattersYesMagicBool_FlagsInFront>() &&
RunTests<Coalesce_3Args_Text_Static_NoFlags>() &&
RunTests<Coalesce_3Args_Text_StaticSpaceMattersNoExplicit_FlagsInBack>() &&
RunTests<Coalesce_3Args_Text_StaticSpaceMattersNoExplicit_FlagsInFront>() &&
RunTests<Coalesce_3Args_Text_StaticSpaceMattersYesExplicitBool_FlagsInBack>() &&
RunTests<Coalesce_3Args_Text_StaticSpaceMattersYesExplicitBool_FlagsInFront>() &&
RunTests<Coalesce_3Args_Text_StaticSpaceMattersYesMagicBool_FlagsInBack>() &&
RunTests<Coalesce_3Args_Text_StaticSpaceMattersYesMagicBool_FlagsInFront>() &&
RunTests<Coalesce_3Args_Values_Extensions>() &&
RunTests<Coalesce_3Args_Values_ExtensionsZeroMattersFlagsInBack>() &&
RunTests<Coalesce_3Args_Values_ExtensionsZeroMattersFlagsInFront>() &&
RunTests<Coalesce_3Args_Values_Static>() &&
RunTests<Coalesce_3Args_Values_StaticZeroMattersFlagsInBack>() &&
RunTests<Coalesce_3Args_Values_StaticZeroMattersFlagsInFront>() &&
RunTests<Coalesce_3Args_ValuesToText_Examples>() &&
RunTests<Coalesce_3Args_ValuesToText_Extensions>() &&
RunTests<Coalesce_3Args_ValuesToText_ExtensionsZeroMattersFlagsInBack>() &&
RunTests<Coalesce_3Args_ValuesToText_ExtensionsZeroMattersFlagsInFront>() &&
RunTests<Coalesce_3Args_ValuesToText_Static>() &&
RunTests<Coalesce_3Args_ValuesToText_StaticZeroMattersFlagsInBack>() &&
RunTests<Coalesce_3Args_ValuesToText_StaticZeroMattersFlagsInFront>() &&
RunTests<Coalesce_Collections_Misc_Tests>() &&
RunTests<Coalesce_Collections_Extensions_Tests>() &&
RunTests<Coalesce_Collections_Static_Tests>() &&
RunTests<Coalesce_Keywords_Tests>() &&
RunTests<Coalesce_Variadic_Tests>() &&
RunTests<Contains_Nullable_Tests>() &&
RunTests<Contains_Tests>() &&
RunTests<BasicType_Other_Tests>() &&
RunTests<Existence_Bugs>() &&
RunTests<BasicType_Bool_Tests>() &&
RunTests<BasicType_Char_Tests>() &&
RunTests<BasicType_DateTime_Tests>() &&
RunTests<BasicType_Double_Tests>() &&
RunTests<BasicType_Enum_Tests>() &&
RunTests<Existence_Examples>() &&
RunTests<BasicType_Guid_Tests>() &&
RunTests<Existence_NotNullWhen_Tests>() &&
RunTests<RegressionTest_CallToHas_FromGenericContext_TypeInfoLost>() &&
RunTests<FilledIn_Tests>() &&
RunTests<Flex_Prototype>() &&
RunTests<Has_Collection_Misc>() &&
RunTests<Has_Collection_Yes>() &&
RunTests<Has_Collection_No>() &&
RunTests<Has_Tests>() &&
RunTests<In_Tests_ExtensionsCaseOrSpaceMattersNoNo>() &&
RunTests<In_Tests_StaticCaseOrSpaceMattersNoNo>() &&
RunTests<In_Tests_ExtensionsCaseOrSpaceMattersNoYes>() &&
RunTests<In_Tests_StaticCaseOrSpaceMattersNoYes>() &&
RunTests<In_Tests_CaseOrSpaceMattersYesNo>() &&
RunTests<In_Tests_CaseOrSpaceMattersYesYes>() &&
RunTests<In_Tests_CaseMatters>() &&
RunTests<In_Tests_SpaceMatters>() &&
RunTests<In_Tests_Other>() &&
RunTests<Is_Tests_Examples>() &&
RunTests<Is_Tests_ExtensionsFlagsInBack>() &&
RunTests<Is_Tests_ExtensionsFlagsInFront>() &&
RunTests<Is_Tests_StaticFlagsInBack>() &&
RunTests<IsNully_Collection_No_Tests>() &&
RunTests<IsNully_Collection_Yes_Tests>() &&
RunTests<IsNully_Tests>();
WriteLine("Done.");
if (!success) Exit(1);
