bool success = 
RunTests<Coalesce_1Arg_Tests>() &&
RunTests<Coalesce_2Args_NoFlags>() &&
RunTests<Coalesce_2Args_FlagsInBack>() &&
RunTests<Coalesce_3Args_Objects>() &&
RunTests<Coalesce_3Args_ObjectsToText>() &&
RunTests<Coalesce_3Args_SBs_ExtensionsSpaceMattersNoExplicit>() &&
RunTests<Coalesce_3Args_SBs_ExtensionsSpaceMattersNoImplicit>() &&
RunTests<Coalesce_3Args_SBs_ExtensionsSpaceMattersYesExplicitBool>() &&
RunTests<Coalesce_3Args_SBs_ExtensionsSpaceMattersYesMagicBool>() &&
RunTests<Coalesce_3Args_SBs_StaticSpaceMattersNoExplicit>() &&
RunTests<Coalesce_3Args_SBs_StaticSpaceMattersNoImplicit>() &&
RunTests<Coalesce_3Args_SBs_StaticSpaceMattersYesExplicitBool>() &&
RunTests<Coalesce_3Args_SBs_StaticSpaceMattersYesMagicBool>() &&
RunTests<Coalesce_3Args_SBTextCombos_ExtensionsSpaceMattersNoExplicit>() &&
RunTests<Coalesce_3Args_SBTextCombos_ExtensionsSpaceMattersNoImplicit>() &&
RunTests<Coalesce_3Args_SBTextCombos_ExtensionsSpaceMattersYesExplicitBool>() &&
RunTests<Coalesce_3Args_SBTextCombos_ExtensionsSpaceMattersYesMagicBool>() &&
RunTests<Coalesce_3Args_SBTextCombos_StaticSpaceMattersNoExplicit>() &&
RunTests<Coalesce_3Args_SBTextCombos_StaticSpaceMattersNoImplicit>() &&
RunTests<Coalesce_3Args_SBTextCombos_StaticSpaceMattersYesExplicitBool>() &&
RunTests<Coalesce_3Args_SBTextCombos_StaticSpaceMattersYesMagicBool>() &&
RunTests<Coalesce_3Args_SBToText_ExtensionsSpaceMattersNoExplicit>() &&
RunTests<Coalesce_3Args_SBToText_ExtensionsSpaceMattersNoImplicit>() &&
RunTests<Coalesce_3Args_SBToText_ExtensionsSpaceMattersYesExplicitBool>() &&
RunTests<Coalesce_3Args_SBToText_ExtensionsSpaceMattersYesMagicBool>() &&
RunTests<Coalesce_3Args_SBToText_StaticSpaceMattersNoExplicit>() &&
RunTests<Coalesce_3Args_SBToText_StaticSpaceMattersNoImplicit>() &&
RunTests<Coalesce_3Args_SBToText_StaticSpaceMattersYesExplicitBool>() &&
RunTests<Coalesce_3Args_SBToText_StaticSpaceMattersYesMagicBool>() &&
RunTests<Coalesce_3Args_Text_ExtensionsSpaceMattersNoExplicit>() &&
RunTests<Coalesce_3Args_Text_ExtensionsSpaceMattersNoImplicit>() &&
RunTests<Coalesce_3Args_Text_ExtensionsSpaceMattersYesExplicitBool>() &&
RunTests<Coalesce_3Args_Text_ExtensionsSpaceMattersYesMagicBool>() &&
RunTests<Coalesce_3Args_Text_StaticSpaceMattersNoExplicit>() &&
RunTests<Coalesce_3Args_Text_StaticSpaceMattersNoImplicit>() &&
RunTests<Coalesce_3Args_Text_StaticSpaceMattersYesExplicitBool>() &&
RunTests<Coalesce_3Args_Text_StaticSpaceMattersYesMagicBool>() &&
RunTests<Coalesce_3Args_Values_Extensions>() &&
RunTests<Coalesce_3Args_Values_ExtensionsZeroMatters>() &&
RunTests<Coalesce_3Args_Values_Static>() &&
RunTests<Coalesce_3Args_Values_StaticZeroMatters>() &&
RunTests<Coalesce_3Args_ValuesToText_Examples>() &&
RunTests<Coalesce_3Args_ValuesToText_Extensions>() &&
RunTests<Coalesce_3Args_ValuesToText_Static>() &&
RunTests<Coalesce_Collections_Misc_Tests>() &&
RunTests<Coalesce_Collections_Extensions_Tests>() &&
RunTests<Coalesce_Collections_Static_Tests>() &&
RunTests<Coalesce_Keywords_Tests>() &&
RunTests<Coalesce_Variadic_Tests>() &&
RunTests<Existence_BasicType_Tests>() &&
RunTests<Existence_Bugs>() &&
RunTests<Existence_Bool_Tests>() &&
RunTests<Existence_Char_Tests>() &&
RunTests<Existence_DateTime_Tests>() &&
RunTests<Existence_Double_Tests>() &&
RunTests<Existence_Enum_Tests>() &&
RunTests<Existence_Examples>() &&
RunTests<Existence_Guid_Tests>() &&
RunTests<Existence_NotNullWhen_Tests>() &&
RunTests<RegressionTest_CallToHas_FromGenericContext_TypeInfoLost>() &&
RunTests<Flex_Prototype>() &&
RunTests<Has_Collection_Misc>() &&
RunTests<Has_Collection_Yes>() &&
RunTests<Has_Collection_No>() &&
RunTests<Has_Object_Tests>() &&
RunTests<Has_StringBuilder_Tests>() &&
RunTests<Has_Text_Tests>() &&
RunTests<Has_Value_Tests>() &&
RunTests<In_Tests_CaseOrSpaceMattersNoNo>() &&
RunTests<In_Tests_CaseOrSpaceMattersNoYes>() &&
RunTests<In_Tests_CaseOrSpaceMattersYesNo>() &&
RunTests<In_Tests_CaseOrSpaceMattersYesYes>() &&
RunTests<In_Tests_CaseMatters>() &&
RunTests<In_Tests_SpaceMatters>() &&
RunTests<In_Tests_Other>() &&
RunTests<Is_Tests>() &&
RunTests<IsNully_Collection_No_Tests>();
RunTests<IsNully_Collection_Yes_Tests>();
WriteLine("Done.");
if (!success) Exit(1);
