global using System;
global using System.Text;
global using System.Diagnostics.CodeAnalysis;
global using Microsoft.VisualStudio.TestTools.UnitTesting;
global using JJ.Framework.Existence.Core.SBs.Tests;
global using JJ.Framework.Existence.Core.Tests.Helpers;
global using JJ.Framework.Existence.Core.Tests.Helpers.docs;
global using static System.String;
global using static JJ.Framework.Existence.Core.FilledInHelper;
global using static JJ.Framework.Existence.Core.SpaceMatters;
global using static JJ.Framework.Testing.Core.AssertCore;
global using static JJ.Framework.Testing.Core.TestRunner;
global using SB = System.Text.StringBuilder;
