global using Microsoft.VisualStudio.TestTools.UnitTesting;
global using JJ.Framework.Reflection.Core;
global using static JJ.Framework.Testing.Core.AssertCore;
global using static JJ.Framework.Compilation.Core.DotNetCommandEnum;
global using static JJ.Framework.Compilation.Core.Tests.DotNetArgBuilderAccessor;
global using static JJ.Framework.Compilation.Core.Tests.DotNetEnricherAccessor;
global using static JJ.Framework.Compilation.Core.Tests.DotNetLoggerAccessor;
global using static JJ.Framework.Compilation.Core.DotNetVerbosity;
global using static System.Environment;
global using static JJ.Framework.Compilation.Core.DotNet;
