global using System;
global using System.Reflection;
global using System.Diagnostics.CodeAnalysis;
global using Microsoft.VisualStudio.TestTools.UnitTesting;
global using JJ.Framework.PlatformCompatibility.Legacy;
global using JJ.Framework.Common.Legacy;
global using JJ.Framework.Reflection.Core;
global using JJ.Framework.Testing.Legacy;
global using JJ.Framework.Testing.Core;
global using JJ.Framework.PlatformCompatibility.Tests;
global using static System.Console;
global using static System.Reflection.BindingFlags;
global using static System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes;
global using static JJ.Framework.SharedProject.Core.DynamicallyAccessedMemberTypesEx;
global using static JJ.Framework.Testing.Core.TestRunner;
