global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using JJ.Framework.Common;
global using Microsoft.VisualStudio.TestTools.UnitTesting;
global using static System.Array;
global using static JJ.Framework.Testing.AssertHelper;
global using static JJ.Framework.Testing.Core.AssertCore;
global using static JJ.Framework.Testing.Core.DeltaDirectionEnum;
