namespace JJ.Framework.Existence.Core.BoolToText.Tests;

[TestClass]
public class Coalesce_4Args_BoolToText_Extensions : TestBase
{
    [TestMethod]
    public void Coalesce_4Args_BoolToText_Extensions_Batch1()
    {
        NoNullRet("",      NullBool  .Coalesce(NullBool,   NullBool,   NullText       ));
        NoNullRet("",      NullBool  .Coalesce(NullBool,   NullBool,   Empty          ));
        NoNullRet(Text,    NullBool  .Coalesce(NullBool,   NullBool,   Text           ));
        NoNullRet(" ",     NullBool  .Coalesce(NullBool,   NullBool,   NullySpace     ));
        NoNullRet(Text,    NullBool  .Coalesce(NullBool,   NullBool,   NullyFilledText));
        NoNullRet("",      NullBool  .Coalesce(NullBool,   NullyFalse, NullText       ));
        NoNullRet("",      NullBool  .Coalesce(NullBool,   NullyFalse, Empty          ));
        NoNullRet(Text,    NullBool  .Coalesce(NullBool,   NullyFalse, Text           ));
        NoNullRet(" ",     NullBool  .Coalesce(NullBool,   NullyFalse, NullySpace     ));
        NoNullRet(Text,    NullBool  .Coalesce(NullBool,   NullyFalse, NullyFilledText));
        NoNullRet("True",  NullBool  .Coalesce(NullBool,   NullyTrue,  NullText       ));
        NoNullRet("True",  NullBool  .Coalesce(NullBool,   NullyTrue,  Empty          ));
        NoNullRet("True",  NullBool  .Coalesce(NullBool,   NullyTrue,  Text           ));
        NoNullRet("True",  NullBool  .Coalesce(NullBool,   NullyTrue,  NullySpace     ));
        NoNullRet("True",  NullBool  .Coalesce(NullBool,   NullyTrue,  NullyFilledText));
        NoNullRet("",      NullBool  .Coalesce(NullBool,   False,      NullText       ));
        NoNullRet("",      NullBool  .Coalesce(NullBool,   False,      Empty          ));
        NoNullRet(Text,    NullBool  .Coalesce(NullBool,   False,      Text           ));
        NoNullRet(" ",     NullBool  .Coalesce(NullBool,   False,      NullySpace     ));
        NoNullRet(Text,    NullBool  .Coalesce(NullBool,   False,      NullyFilledText));
        NoNullRet("True",  NullBool  .Coalesce(NullBool,   True,       NullText       ));
        NoNullRet("True",  NullBool  .Coalesce(NullBool,   True,       Empty          ));
        NoNullRet("True",  NullBool  .Coalesce(NullBool,   True,       Text           ));
        NoNullRet("True",  NullBool  .Coalesce(NullBool,   True,       NullySpace     ));
        NoNullRet("True",  NullBool  .Coalesce(NullBool,   True,       NullyFilledText));
        NoNullRet("",      NullBool  .Coalesce(NullyFalse, NullBool,   NullText       ));
        NoNullRet("",      NullBool  .Coalesce(NullyFalse, NullBool,   Empty          ));
        NoNullRet(Text,    NullBool  .Coalesce(NullyFalse, NullBool,   Text           ));
        NoNullRet(" ",     NullBool  .Coalesce(NullyFalse, NullBool,   NullySpace     ));
        NoNullRet(Text,    NullBool  .Coalesce(NullyFalse, NullBool,   NullyFilledText));
        NoNullRet("",      NullBool  .Coalesce(NullyFalse, NullyFalse, NullText       ));
        NoNullRet("",      NullBool  .Coalesce(NullyFalse, NullyFalse, Empty          ));
        NoNullRet(Text,    NullBool  .Coalesce(NullyFalse, NullyFalse, Text           ));
        NoNullRet(" ",     NullBool  .Coalesce(NullyFalse, NullyFalse, NullySpace     ));
        NoNullRet(Text,    NullBool  .Coalesce(NullyFalse, NullyFalse, NullyFilledText));
        NoNullRet("True",  NullBool  .Coalesce(NullyFalse, NullyTrue,  NullText       ));
        NoNullRet("True",  NullBool  .Coalesce(NullyFalse, NullyTrue,  Empty          ));
        NoNullRet("True",  NullBool  .Coalesce(NullyFalse, NullyTrue,  Text           ));
        NoNullRet("True",  NullBool  .Coalesce(NullyFalse, NullyTrue,  NullySpace     ));
        NoNullRet("True",  NullBool  .Coalesce(NullyFalse, NullyTrue,  NullyFilledText));
        NoNullRet("",      NullBool  .Coalesce(NullyFalse, False,      NullText       ));
        NoNullRet("",      NullBool  .Coalesce(NullyFalse, False,      Empty          ));
        NoNullRet(Text,    NullBool  .Coalesce(NullyFalse, False,      Text           ));
        NoNullRet(" ",     NullBool  .Coalesce(NullyFalse, False,      NullySpace     ));
        NoNullRet(Text,    NullBool  .Coalesce(NullyFalse, False,      NullyFilledText));
        NoNullRet("True",  NullBool  .Coalesce(NullyFalse, True,       NullText       ));
        NoNullRet("True",  NullBool  .Coalesce(NullyFalse, True,       Empty          ));
        NoNullRet("True",  NullBool  .Coalesce(NullyFalse, True,       Text           ));
        NoNullRet("True",  NullBool  .Coalesce(NullyFalse, True,       NullySpace     ));
        NoNullRet("True",  NullBool  .Coalesce(NullyFalse, True,       NullyFilledText));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  NullBool,   NullText       ));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  NullBool,   Empty          ));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  NullBool,   Text           ));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  NullBool,   NullySpace     ));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  NullBool,   NullyFilledText));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  NullyFalse, NullText       ));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  NullyFalse, Empty          ));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  NullyFalse, Text           ));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  NullyFalse, NullySpace     ));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  NullyFalse, NullyFilledText));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  NullyTrue,  NullText       ));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  NullyTrue,  Empty          ));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  NullyTrue,  Text           ));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  NullyTrue,  NullySpace     ));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  NullyTrue,  NullyFilledText));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  False,      NullText       ));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  False,      Empty          ));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  False,      Text           ));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  False,      NullySpace     ));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  False,      NullyFilledText));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  True,       NullText       ));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  True,       Empty          ));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  True,       Text           ));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  True,       NullySpace     ));
        NoNullRet("True",  NullBool  .Coalesce(NullyTrue,  True,       NullyFilledText));
        NoNullRet("",      NullBool  .Coalesce(False,      NullBool,   NullText       ));
        NoNullRet("",      NullBool  .Coalesce(False,      NullBool,   Empty          ));
        NoNullRet(Text,    NullBool  .Coalesce(False,      NullBool,   Text           ));
        NoNullRet(" ",     NullBool  .Coalesce(False,      NullBool,   NullySpace     ));
        NoNullRet(Text,    NullBool  .Coalesce(False,      NullBool,   NullyFilledText));
        NoNullRet("",      NullBool  .Coalesce(False,      NullyFalse, NullText       ));
        NoNullRet("",      NullBool  .Coalesce(False,      NullyFalse, Empty          ));
        NoNullRet(Text,    NullBool  .Coalesce(False,      NullyFalse, Text           ));
        NoNullRet(" ",     NullBool  .Coalesce(False,      NullyFalse, NullySpace     ));
        NoNullRet(Text,    NullBool  .Coalesce(False,      NullyFalse, NullyFilledText));
        NoNullRet("True",  NullBool  .Coalesce(False,      NullyTrue,  NullText       ));
        NoNullRet("True",  NullBool  .Coalesce(False,      NullyTrue,  Empty          ));
        NoNullRet("True",  NullBool  .Coalesce(False,      NullyTrue,  Text           ));
        NoNullRet("True",  NullBool  .Coalesce(False,      NullyTrue,  NullySpace     ));
        NoNullRet("True",  NullBool  .Coalesce(False,      NullyTrue,  NullyFilledText));
        NoNullRet("",      NullBool  .Coalesce(False,      False,      NullText       ));
        NoNullRet("",      NullBool  .Coalesce(False,      False,      Empty          ));
        NoNullRet(Text,    NullBool  .Coalesce(False,      False,      Text           ));
        NoNullRet(" ",     NullBool  .Coalesce(False,      False,      NullySpace     ));
        NoNullRet(Text,    NullBool  .Coalesce(False,      False,      NullyFilledText));
        NoNullRet("True",  NullBool  .Coalesce(False,      True,       NullText       ));
        NoNullRet("True",  NullBool  .Coalesce(False,      True,       Empty          ));
        NoNullRet("True",  NullBool  .Coalesce(False,      True,       Text           ));
        NoNullRet("True",  NullBool  .Coalesce(False,      True,       NullySpace     ));
        NoNullRet("True",  NullBool  .Coalesce(False,      True,       NullyFilledText));
        NoNullRet("True",  NullBool  .Coalesce(True,       NullBool,   NullText       ));
        NoNullRet("True",  NullBool  .Coalesce(True,       NullBool,   Empty          ));
        NoNullRet("True",  NullBool  .Coalesce(True,       NullBool,   Text           ));
        NoNullRet("True",  NullBool  .Coalesce(True,       NullBool,   NullySpace     ));
        NoNullRet("True",  NullBool  .Coalesce(True,       NullBool,   NullyFilledText));
        NoNullRet("True",  NullBool  .Coalesce(True,       NullyFalse, NullText       ));
        NoNullRet("True",  NullBool  .Coalesce(True,       NullyFalse, Empty          ));
        NoNullRet("True",  NullBool  .Coalesce(True,       NullyFalse, Text           ));
        NoNullRet("True",  NullBool  .Coalesce(True,       NullyFalse, NullySpace     ));
        NoNullRet("True",  NullBool  .Coalesce(True,       NullyFalse, NullyFilledText));
        NoNullRet("True",  NullBool  .Coalesce(True,       NullyTrue,  NullText       ));
        NoNullRet("True",  NullBool  .Coalesce(True,       NullyTrue,  Empty          ));
        NoNullRet("True",  NullBool  .Coalesce(True,       NullyTrue,  Text           ));
        NoNullRet("True",  NullBool  .Coalesce(True,       NullyTrue,  NullySpace     ));
        NoNullRet("True",  NullBool  .Coalesce(True,       NullyTrue,  NullyFilledText));
        NoNullRet("True",  NullBool  .Coalesce(True,       False,      NullText       ));
        NoNullRet("True",  NullBool  .Coalesce(True,       False,      Empty          ));
        NoNullRet("True",  NullBool  .Coalesce(True,       False,      Text           ));
        NoNullRet("True",  NullBool  .Coalesce(True,       False,      NullySpace     ));
        NoNullRet("True",  NullBool  .Coalesce(True,       False,      NullyFilledText));
        NoNullRet("True",  NullBool  .Coalesce(True,       True,       NullText       ));
        NoNullRet("True",  NullBool  .Coalesce(True,       True,       Empty          ));
        NoNullRet("True",  NullBool  .Coalesce(True,       True,       Text           ));
        NoNullRet("True",  NullBool  .Coalesce(True,       True,       NullySpace     ));
        NoNullRet("True",  NullBool  .Coalesce(True,       True,       NullyFilledText));
    }

    [TestMethod]
    public void Coalesce_4Args_BoolToText_Extensions_Batch2()
    {
        NoNullRet("",      NullyFalse.Coalesce(NullBool,   NullBool,   NullText       ));
        NoNullRet("",      NullyFalse.Coalesce(NullBool,   NullBool,   Empty          ));
        NoNullRet(Text,    NullyFalse.Coalesce(NullBool,   NullBool,   Text           ));
        NoNullRet(" ",     NullyFalse.Coalesce(NullBool,   NullBool,   NullySpace     ));
        NoNullRet(Text,    NullyFalse.Coalesce(NullBool,   NullBool,   NullyFilledText));
        NoNullRet("",      NullyFalse.Coalesce(NullBool,   NullyFalse, NullText       ));
        NoNullRet("",      NullyFalse.Coalesce(NullBool,   NullyFalse, Empty          ));
        NoNullRet(Text,    NullyFalse.Coalesce(NullBool,   NullyFalse, Text           ));
        NoNullRet(" ",     NullyFalse.Coalesce(NullBool,   NullyFalse, NullySpace     ));
        NoNullRet(Text,    NullyFalse.Coalesce(NullBool,   NullyFalse, NullyFilledText));
        NoNullRet("True",  NullyFalse.Coalesce(NullBool,   NullyTrue,  NullText       ));
        NoNullRet("True",  NullyFalse.Coalesce(NullBool,   NullyTrue,  Empty          ));
        NoNullRet("True",  NullyFalse.Coalesce(NullBool,   NullyTrue,  Text           ));
        NoNullRet("True",  NullyFalse.Coalesce(NullBool,   NullyTrue,  NullySpace     ));
        NoNullRet("True",  NullyFalse.Coalesce(NullBool,   NullyTrue,  NullyFilledText));
        NoNullRet("",      NullyFalse.Coalesce(NullBool,   False,      NullText       ));
        NoNullRet("",      NullyFalse.Coalesce(NullBool,   False,      Empty          ));
        NoNullRet(Text,    NullyFalse.Coalesce(NullBool,   False,      Text           ));
        NoNullRet(" ",     NullyFalse.Coalesce(NullBool,   False,      NullySpace     ));
        NoNullRet(Text,    NullyFalse.Coalesce(NullBool,   False,      NullyFilledText));
        NoNullRet("True",  NullyFalse.Coalesce(NullBool,   True,       NullText       ));
        NoNullRet("True",  NullyFalse.Coalesce(NullBool,   True,       Empty          ));
        NoNullRet("True",  NullyFalse.Coalesce(NullBool,   True,       Text           ));
        NoNullRet("True",  NullyFalse.Coalesce(NullBool,   True,       NullySpace     ));
        NoNullRet("True",  NullyFalse.Coalesce(NullBool,   True,       NullyFilledText));
        NoNullRet("",      NullyFalse.Coalesce(NullyFalse, NullBool,   NullText       ));
        NoNullRet("",      NullyFalse.Coalesce(NullyFalse, NullBool,   Empty          ));
        NoNullRet(Text,    NullyFalse.Coalesce(NullyFalse, NullBool,   Text           ));
        NoNullRet(" ",     NullyFalse.Coalesce(NullyFalse, NullBool,   NullySpace     ));
        NoNullRet(Text,    NullyFalse.Coalesce(NullyFalse, NullBool,   NullyFilledText));
        NoNullRet("",      NullyFalse.Coalesce(NullyFalse, NullyFalse, NullText       ));
        NoNullRet("",      NullyFalse.Coalesce(NullyFalse, NullyFalse, Empty          ));
        NoNullRet(Text,    NullyFalse.Coalesce(NullyFalse, NullyFalse, Text           ));
        NoNullRet(" ",     NullyFalse.Coalesce(NullyFalse, NullyFalse, NullySpace     ));
        NoNullRet(Text,    NullyFalse.Coalesce(NullyFalse, NullyFalse, NullyFilledText));
        NoNullRet("True",  NullyFalse.Coalesce(NullyFalse, NullyTrue,  NullText       ));
        NoNullRet("True",  NullyFalse.Coalesce(NullyFalse, NullyTrue,  Empty          ));
        NoNullRet("True",  NullyFalse.Coalesce(NullyFalse, NullyTrue,  Text           ));
        NoNullRet("True",  NullyFalse.Coalesce(NullyFalse, NullyTrue,  NullySpace     ));
        NoNullRet("True",  NullyFalse.Coalesce(NullyFalse, NullyTrue,  NullyFilledText));
        NoNullRet("",      NullyFalse.Coalesce(NullyFalse, False,      NullText       ));
        NoNullRet("",      NullyFalse.Coalesce(NullyFalse, False,      Empty          ));
        NoNullRet(Text,    NullyFalse.Coalesce(NullyFalse, False,      Text           ));
        NoNullRet(" ",     NullyFalse.Coalesce(NullyFalse, False,      NullySpace     ));
        NoNullRet(Text,    NullyFalse.Coalesce(NullyFalse, False,      NullyFilledText));
        NoNullRet("True",  NullyFalse.Coalesce(NullyFalse, True,       NullText       ));
        NoNullRet("True",  NullyFalse.Coalesce(NullyFalse, True,       Empty          ));
        NoNullRet("True",  NullyFalse.Coalesce(NullyFalse, True,       Text           ));
        NoNullRet("True",  NullyFalse.Coalesce(NullyFalse, True,       NullySpace     ));
        NoNullRet("True",  NullyFalse.Coalesce(NullyFalse, True,       NullyFilledText));
        NoNullRet("True",  NullyFalse.Coalesce(NullyTrue,  NullBool,   NullText       ));
        NoNullRet("True",  NullyFalse.Coalesce(NullyTrue,  NullBool,   Empty          ));
        NoNullRet("True",  NullyFalse.Coalesce(NullyTrue,  NullBool,   Text           ));
        NoNullRet("True",  NullyFalse.Coalesce(NullyTrue,  NullBool,   NullySpace     ));
        NoNullRet("True",  NullyFalse.Coalesce(NullyTrue,  NullBool,   NullyFilledText));
        NoNullRet("True",  NullyFalse.Coalesce(NullyTrue,  NullyFalse, NullText       ));
        NoNullRet("True",  NullyFalse.Coalesce(NullyTrue,  NullyFalse, Empty          ));
        NoNullRet("True",  NullyFalse.Coalesce(NullyTrue,  NullyFalse, Text           ));
        NoNullRet("True",  NullyFalse.Coalesce(NullyTrue,  NullyFalse, NullySpace     ));
        NoNullRet("True",  NullyFalse.Coalesce(NullyTrue,  NullyFalse, NullyFilledText));
        NoNullRet("True",  NullyFalse.Coalesce(NullyTrue,  NullyTrue,  NullText       ));
        NoNullRet("True",  NullyFalse.Coalesce(NullyTrue,  NullyTrue,  Empty          ));
        NoNullRet("True",  NullyFalse.Coalesce(NullyTrue,  NullyTrue,  Text           ));
        NoNullRet("True",  NullyFalse.Coalesce(NullyTrue,  NullyTrue,  NullySpace     ));
        NoNullRet("True",  NullyFalse.Coalesce(NullyTrue,  NullyTrue,  NullyFilledText));
        NoNullRet("True",  NullyFalse.Coalesce(NullyTrue,  False,      NullText       ));
        NoNullRet("True",  NullyFalse.Coalesce(NullyTrue,  False,      Empty          ));
        NoNullRet("True",  NullyFalse.Coalesce(NullyTrue,  False,      Text           ));
        NoNullRet("True",  NullyFalse.Coalesce(NullyTrue,  False,      NullySpace     ));
        NoNullRet("True",  NullyFalse.Coalesce(NullyTrue,  False,      NullyFilledText));
        NoNullRet("True",  NullyFalse.Coalesce(NullyTrue,  True,       NullText       ));
        NoNullRet("True",  NullyFalse.Coalesce(NullyTrue,  True,       Empty          ));
        NoNullRet("True",  NullyFalse.Coalesce(NullyTrue,  True,       Text           ));
        NoNullRet("True",  NullyFalse.Coalesce(NullyTrue,  True,       NullySpace     ));
        NoNullRet("True",  NullyFalse.Coalesce(NullyTrue,  True,       NullyFilledText));
        NoNullRet("",      NullyFalse.Coalesce(False,      NullBool,   NullText       ));
        NoNullRet("",      NullyFalse.Coalesce(False,      NullBool,   Empty          ));
        NoNullRet(Text,    NullyFalse.Coalesce(False,      NullBool,   Text           ));
        NoNullRet(" ",     NullyFalse.Coalesce(False,      NullBool,   NullySpace     ));
        NoNullRet(Text,    NullyFalse.Coalesce(False,      NullBool,   NullyFilledText));
        NoNullRet("",      NullyFalse.Coalesce(False,      NullyFalse, NullText       ));
        NoNullRet("",      NullyFalse.Coalesce(False,      NullyFalse, Empty          ));
        NoNullRet(Text,    NullyFalse.Coalesce(False,      NullyFalse, Text           ));
        NoNullRet(" ",     NullyFalse.Coalesce(False,      NullyFalse, NullySpace     ));
        NoNullRet(Text,    NullyFalse.Coalesce(False,      NullyFalse, NullyFilledText));
        NoNullRet("True",  NullyFalse.Coalesce(False,      NullyTrue,  NullText       ));
        NoNullRet("True",  NullyFalse.Coalesce(False,      NullyTrue,  Empty          ));
        NoNullRet("True",  NullyFalse.Coalesce(False,      NullyTrue,  Text           ));
        NoNullRet("True",  NullyFalse.Coalesce(False,      NullyTrue,  NullySpace     ));
        NoNullRet("True",  NullyFalse.Coalesce(False,      NullyTrue,  NullyFilledText));
        NoNullRet("",      NullyFalse.Coalesce(False,      False,      NullText       ));
        NoNullRet("",      NullyFalse.Coalesce(False,      False,      Empty          ));
        NoNullRet(Text,    NullyFalse.Coalesce(False,      False,      Text           ));
        NoNullRet(" ",     NullyFalse.Coalesce(False,      False,      NullySpace     ));
        NoNullRet(Text,    NullyFalse.Coalesce(False,      False,      NullyFilledText));
        NoNullRet("True",  NullyFalse.Coalesce(False,      True,       NullText       ));
        NoNullRet("True",  NullyFalse.Coalesce(False,      True,       Empty          ));
        NoNullRet("True",  NullyFalse.Coalesce(False,      True,       Text           ));
        NoNullRet("True",  NullyFalse.Coalesce(False,      True,       NullySpace     ));
        NoNullRet("True",  NullyFalse.Coalesce(False,      True,       NullyFilledText));
        NoNullRet("True",  NullyFalse.Coalesce(True,       NullBool,   NullText       ));
        NoNullRet("True",  NullyFalse.Coalesce(True,       NullBool,   Empty          ));
        NoNullRet("True",  NullyFalse.Coalesce(True,       NullBool,   Text           ));
        NoNullRet("True",  NullyFalse.Coalesce(True,       NullBool,   NullySpace     ));
        NoNullRet("True",  NullyFalse.Coalesce(True,       NullBool,   NullyFilledText));
        NoNullRet("True",  NullyFalse.Coalesce(True,       NullyFalse, NullText       ));
        NoNullRet("True",  NullyFalse.Coalesce(True,       NullyFalse, Empty          ));
        NoNullRet("True",  NullyFalse.Coalesce(True,       NullyFalse, Text           ));
        NoNullRet("True",  NullyFalse.Coalesce(True,       NullyFalse, NullySpace     ));
        NoNullRet("True",  NullyFalse.Coalesce(True,       NullyFalse, NullyFilledText));
        NoNullRet("True",  NullyFalse.Coalesce(True,       NullyTrue,  NullText       ));
        NoNullRet("True",  NullyFalse.Coalesce(True,       NullyTrue,  Empty          ));
        NoNullRet("True",  NullyFalse.Coalesce(True,       NullyTrue,  Text           ));
        NoNullRet("True",  NullyFalse.Coalesce(True,       NullyTrue,  NullySpace     ));
        NoNullRet("True",  NullyFalse.Coalesce(True,       NullyTrue,  NullyFilledText));
        NoNullRet("True",  NullyFalse.Coalesce(True,       False,      NullText       ));
        NoNullRet("True",  NullyFalse.Coalesce(True,       False,      Empty          ));
        NoNullRet("True",  NullyFalse.Coalesce(True,       False,      Text           ));
        NoNullRet("True",  NullyFalse.Coalesce(True,       False,      NullySpace     ));
        NoNullRet("True",  NullyFalse.Coalesce(True,       False,      NullyFilledText));
        NoNullRet("True",  NullyFalse.Coalesce(True,       True,       NullText       ));
        NoNullRet("True",  NullyFalse.Coalesce(True,       True,       Empty          ));
        NoNullRet("True",  NullyFalse.Coalesce(True,       True,       Text           ));
        NoNullRet("True",  NullyFalse.Coalesce(True,       True,       NullySpace     ));
        NoNullRet("True",  NullyFalse.Coalesce(True,       True,       NullyFilledText));
    }

    [TestMethod]
    public void Coalesce_4Args_BoolToText_Extensions_Batch3()
    {
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   NullBool,   NullText       ));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   NullBool,   Empty          ));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   NullBool,   Text           ));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   NullBool,   NullySpace     ));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   NullBool,   NullyFilledText));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   NullyFalse, NullText       ));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   NullyFalse, Empty          ));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   NullyFalse, Text           ));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   NullyFalse, NullySpace     ));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   NullyFalse, NullyFilledText));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   NullyTrue,  NullText       ));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   NullyTrue,  Empty          ));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   NullyTrue,  Text           ));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   NullyTrue,  NullySpace     ));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   NullyTrue,  NullyFilledText));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   False,      NullText       ));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   False,      Empty          ));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   False,      Text           ));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   False,      NullySpace     ));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   False,      NullyFilledText));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   True,       NullText       ));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   True,       Empty          ));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   True,       Text           ));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   True,       NullySpace     ));
        NoNullRet("True",  NullyTrue .Coalesce(NullBool,   True,       NullyFilledText));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, NullBool,   NullText       ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, NullBool,   Empty          ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, NullBool,   Text           ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, NullBool,   NullySpace     ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, NullBool,   NullyFilledText));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, NullyFalse, NullText       ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, NullyFalse, Empty          ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, NullyFalse, Text           ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, NullyFalse, NullySpace     ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, NullyFalse, NullyFilledText));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, NullyTrue,  NullText       ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, NullyTrue,  Empty          ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, NullyTrue,  Text           ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, NullyTrue,  NullySpace     ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, NullyTrue,  NullyFilledText));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, False,      NullText       ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, False,      Empty          ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, False,      Text           ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, False,      NullySpace     ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, False,      NullyFilledText));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, True,       NullText       ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, True,       Empty          ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, True,       Text           ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, True,       NullySpace     ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyFalse, True,       NullyFilledText));
        NoNullRet("True",  NullyTrue .Coalesce(NullyTrue,  NullBool,   NullText       ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyTrue,  NullBool,   Empty          ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyTrue,  NullBool,   Text           ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyTrue,  NullBool,   NullySpace     ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyTrue,  NullBool,   NullyFilledText));
        NoNullRet("True",  NullyTrue .Coalesce(NullyTrue,  NullyFalse, NullText       ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyTrue,  NullyFalse, Empty          ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyTrue,  NullyFalse, Text           ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyTrue,  NullyFalse, NullySpace     ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyTrue,  NullyFalse, NullyFilledText));
        NoNullRet("True",  NullyTrue .Coalesce(NullyTrue,  NullyTrue,  NullText       ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyTrue,  NullyTrue,  Empty          ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyTrue,  NullyTrue,  Text           ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyTrue,  NullyTrue,  NullySpace     ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyTrue,  NullyTrue,  NullyFilledText));
        NoNullRet("True",  NullyTrue .Coalesce(NullyTrue,  False,      NullText       ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyTrue,  False,      Empty          ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyTrue,  False,      Text           ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyTrue,  False,      NullySpace     ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyTrue,  False,      NullyFilledText));
        NoNullRet("True",  NullyTrue .Coalesce(NullyTrue,  True,       NullText       ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyTrue,  True,       Empty          ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyTrue,  True,       Text           ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyTrue,  True,       NullySpace     ));
        NoNullRet("True",  NullyTrue .Coalesce(NullyTrue,  True,       NullyFilledText));
        NoNullRet("True",  NullyTrue .Coalesce(False,      NullBool,   NullText       ));
        NoNullRet("True",  NullyTrue .Coalesce(False,      NullBool,   Empty          ));
        NoNullRet("True",  NullyTrue .Coalesce(False,      NullBool,   Text           ));
        NoNullRet("True",  NullyTrue .Coalesce(False,      NullBool,   NullySpace     ));
        NoNullRet("True",  NullyTrue .Coalesce(False,      NullBool,   NullyFilledText));
        NoNullRet("True",  NullyTrue .Coalesce(False,      NullyFalse, NullText       ));
        NoNullRet("True",  NullyTrue .Coalesce(False,      NullyFalse, Empty          ));
        NoNullRet("True",  NullyTrue .Coalesce(False,      NullyFalse, Text           ));
        NoNullRet("True",  NullyTrue .Coalesce(False,      NullyFalse, NullySpace     ));
        NoNullRet("True",  NullyTrue .Coalesce(False,      NullyFalse, NullyFilledText));
        NoNullRet("True",  NullyTrue .Coalesce(False,      NullyTrue,  NullText       ));
        NoNullRet("True",  NullyTrue .Coalesce(False,      NullyTrue,  Empty          ));
        NoNullRet("True",  NullyTrue .Coalesce(False,      NullyTrue,  Text           ));
        NoNullRet("True",  NullyTrue .Coalesce(False,      NullyTrue,  NullySpace     ));
        NoNullRet("True",  NullyTrue .Coalesce(False,      NullyTrue,  NullyFilledText));
        NoNullRet("True",  NullyTrue .Coalesce(False,      False,      NullText       ));
        NoNullRet("True",  NullyTrue .Coalesce(False,      False,      Empty          ));
        NoNullRet("True",  NullyTrue .Coalesce(False,      False,      Text           ));
        NoNullRet("True",  NullyTrue .Coalesce(False,      False,      NullySpace     ));
        NoNullRet("True",  NullyTrue .Coalesce(False,      False,      NullyFilledText));
        NoNullRet("True",  NullyTrue .Coalesce(False,      True,       NullText       ));
        NoNullRet("True",  NullyTrue .Coalesce(False,      True,       Empty          ));
        NoNullRet("True",  NullyTrue .Coalesce(False,      True,       Text           ));
        NoNullRet("True",  NullyTrue .Coalesce(False,      True,       NullySpace     ));
        NoNullRet("True",  NullyTrue .Coalesce(False,      True,       NullyFilledText));
        NoNullRet("True",  NullyTrue .Coalesce(True,       NullBool,   NullText       ));
        NoNullRet("True",  NullyTrue .Coalesce(True,       NullBool,   Empty          ));
        NoNullRet("True",  NullyTrue .Coalesce(True,       NullBool,   Text           ));
        NoNullRet("True",  NullyTrue .Coalesce(True,       NullBool,   NullySpace     ));
        NoNullRet("True",  NullyTrue .Coalesce(True,       NullBool,   NullyFilledText));
        NoNullRet("True",  NullyTrue .Coalesce(True,       NullyFalse, NullText       ));
        NoNullRet("True",  NullyTrue .Coalesce(True,       NullyFalse, Empty          ));
        NoNullRet("True",  NullyTrue .Coalesce(True,       NullyFalse, Text           ));
        NoNullRet("True",  NullyTrue .Coalesce(True,       NullyFalse, NullySpace     ));
        NoNullRet("True",  NullyTrue .Coalesce(True,       NullyFalse, NullyFilledText));
        NoNullRet("True",  NullyTrue .Coalesce(True,       NullyTrue,  NullText       ));
        NoNullRet("True",  NullyTrue .Coalesce(True,       NullyTrue,  Empty          ));
        NoNullRet("True",  NullyTrue .Coalesce(True,       NullyTrue,  Text           ));
        NoNullRet("True",  NullyTrue .Coalesce(True,       NullyTrue,  NullySpace     ));
        NoNullRet("True",  NullyTrue .Coalesce(True,       NullyTrue,  NullyFilledText));
        NoNullRet("True",  NullyTrue .Coalesce(True,       False,      NullText       ));
        NoNullRet("True",  NullyTrue .Coalesce(True,       False,      Empty          ));
        NoNullRet("True",  NullyTrue .Coalesce(True,       False,      Text           ));
        NoNullRet("True",  NullyTrue .Coalesce(True,       False,      NullySpace     ));
        NoNullRet("True",  NullyTrue .Coalesce(True,       False,      NullyFilledText));
        NoNullRet("True",  NullyTrue .Coalesce(True,       True,       NullText       ));
        NoNullRet("True",  NullyTrue .Coalesce(True,       True,       Empty          ));
        NoNullRet("True",  NullyTrue .Coalesce(True,       True,       Text           ));
        NoNullRet("True",  NullyTrue .Coalesce(True,       True,       NullySpace     ));
        NoNullRet("True",  NullyTrue .Coalesce(True,       True,       NullyFilledText));
    }

    [TestMethod]
    public void Coalesce_4Args_BoolToText_Extensions_Batch4()
    {
        NoNullRet("",      False     .Coalesce(NullBool,   NullBool,   NullText       ));
        NoNullRet("",      False     .Coalesce(NullBool,   NullBool,   Empty          ));
        NoNullRet(Text,    False     .Coalesce(NullBool,   NullBool,   Text           ));
        NoNullRet(" ",     False     .Coalesce(NullBool,   NullBool,   NullySpace     ));
        NoNullRet(Text,    False     .Coalesce(NullBool,   NullBool,   NullyFilledText));
        NoNullRet("",      False     .Coalesce(NullBool,   NullyFalse, NullText       ));
        NoNullRet("",      False     .Coalesce(NullBool,   NullyFalse, Empty          ));
        NoNullRet(Text,    False     .Coalesce(NullBool,   NullyFalse, Text           ));
        NoNullRet(" ",     False     .Coalesce(NullBool,   NullyFalse, NullySpace     ));
        NoNullRet(Text,    False     .Coalesce(NullBool,   NullyFalse, NullyFilledText));
        NoNullRet("True",  False     .Coalesce(NullBool,   NullyTrue,  NullText       ));
        NoNullRet("True",  False     .Coalesce(NullBool,   NullyTrue,  Empty          ));
        NoNullRet("True",  False     .Coalesce(NullBool,   NullyTrue,  Text           ));
        NoNullRet("True",  False     .Coalesce(NullBool,   NullyTrue,  NullySpace     ));
        NoNullRet("True",  False     .Coalesce(NullBool,   NullyTrue,  NullyFilledText));
        NoNullRet("",      False     .Coalesce(NullBool,   False,      NullText       ));
        NoNullRet("",      False     .Coalesce(NullBool,   False,      Empty          ));
        NoNullRet(Text,    False     .Coalesce(NullBool,   False,      Text           ));
        NoNullRet(" ",     False     .Coalesce(NullBool,   False,      NullySpace     ));
        NoNullRet(Text,    False     .Coalesce(NullBool,   False,      NullyFilledText));
        NoNullRet("True",  False     .Coalesce(NullBool,   True,       NullText       ));
        NoNullRet("True",  False     .Coalesce(NullBool,   True,       Empty          ));
        NoNullRet("True",  False     .Coalesce(NullBool,   True,       Text           ));
        NoNullRet("True",  False     .Coalesce(NullBool,   True,       NullySpace     ));
        NoNullRet("True",  False     .Coalesce(NullBool,   True,       NullyFilledText));
        NoNullRet("",      False     .Coalesce(NullyFalse, NullBool,   NullText       ));
        NoNullRet("",      False     .Coalesce(NullyFalse, NullBool,   Empty          ));
        NoNullRet(Text,    False     .Coalesce(NullyFalse, NullBool,   Text           ));
        NoNullRet(" ",     False     .Coalesce(NullyFalse, NullBool,   NullySpace     ));
        NoNullRet(Text,    False     .Coalesce(NullyFalse, NullBool,   NullyFilledText));
        NoNullRet("",      False     .Coalesce(NullyFalse, NullyFalse, NullText       ));
        NoNullRet("",      False     .Coalesce(NullyFalse, NullyFalse, Empty          ));
        NoNullRet(Text,    False     .Coalesce(NullyFalse, NullyFalse, Text           ));
        NoNullRet(" ",     False     .Coalesce(NullyFalse, NullyFalse, NullySpace     ));
        NoNullRet(Text,    False     .Coalesce(NullyFalse, NullyFalse, NullyFilledText));
        NoNullRet("True",  False     .Coalesce(NullyFalse, NullyTrue,  NullText       ));
        NoNullRet("True",  False     .Coalesce(NullyFalse, NullyTrue,  Empty          ));
        NoNullRet("True",  False     .Coalesce(NullyFalse, NullyTrue,  Text           ));
        NoNullRet("True",  False     .Coalesce(NullyFalse, NullyTrue,  NullySpace     ));
        NoNullRet("True",  False     .Coalesce(NullyFalse, NullyTrue,  NullyFilledText));
        NoNullRet("",      False     .Coalesce(NullyFalse, False,      NullText       ));
        NoNullRet("",      False     .Coalesce(NullyFalse, False,      Empty          ));
        NoNullRet(Text,    False     .Coalesce(NullyFalse, False,      Text           ));
        NoNullRet(" ",     False     .Coalesce(NullyFalse, False,      NullySpace     ));
        NoNullRet(Text,    False     .Coalesce(NullyFalse, False,      NullyFilledText));
        NoNullRet("True",  False     .Coalesce(NullyFalse, True,       NullText       ));
        NoNullRet("True",  False     .Coalesce(NullyFalse, True,       Empty          ));
        NoNullRet("True",  False     .Coalesce(NullyFalse, True,       Text           ));
        NoNullRet("True",  False     .Coalesce(NullyFalse, True,       NullySpace     ));
        NoNullRet("True",  False     .Coalesce(NullyFalse, True,       NullyFilledText));
        NoNullRet("True",  False     .Coalesce(NullyTrue,  NullBool,   NullText       ));
        NoNullRet("True",  False     .Coalesce(NullyTrue,  NullBool,   Empty          ));
        NoNullRet("True",  False     .Coalesce(NullyTrue,  NullBool,   Text           ));
        NoNullRet("True",  False     .Coalesce(NullyTrue,  NullBool,   NullySpace     ));
        NoNullRet("True",  False     .Coalesce(NullyTrue,  NullBool,   NullyFilledText));
        NoNullRet("True",  False     .Coalesce(NullyTrue,  NullyFalse, NullText       ));
        NoNullRet("True",  False     .Coalesce(NullyTrue,  NullyFalse, Empty          ));
        NoNullRet("True",  False     .Coalesce(NullyTrue,  NullyFalse, Text           ));
        NoNullRet("True",  False     .Coalesce(NullyTrue,  NullyFalse, NullySpace     ));
        NoNullRet("True",  False     .Coalesce(NullyTrue,  NullyFalse, NullyFilledText));
        NoNullRet("True",  False     .Coalesce(NullyTrue,  NullyTrue,  NullText       ));
        NoNullRet("True",  False     .Coalesce(NullyTrue,  NullyTrue,  Empty          ));
        NoNullRet("True",  False     .Coalesce(NullyTrue,  NullyTrue,  Text           ));
        NoNullRet("True",  False     .Coalesce(NullyTrue,  NullyTrue,  NullySpace     ));
        NoNullRet("True",  False     .Coalesce(NullyTrue,  NullyTrue,  NullyFilledText));
        NoNullRet("True",  False     .Coalesce(NullyTrue,  False,      NullText       ));
        NoNullRet("True",  False     .Coalesce(NullyTrue,  False,      Empty          ));
        NoNullRet("True",  False     .Coalesce(NullyTrue,  False,      Text           ));
        NoNullRet("True",  False     .Coalesce(NullyTrue,  False,      NullySpace     ));
        NoNullRet("True",  False     .Coalesce(NullyTrue,  False,      NullyFilledText));
        NoNullRet("True",  False     .Coalesce(NullyTrue,  True,       NullText       ));
        NoNullRet("True",  False     .Coalesce(NullyTrue,  True,       Empty          ));
        NoNullRet("True",  False     .Coalesce(NullyTrue,  True,       Text           ));
        NoNullRet("True",  False     .Coalesce(NullyTrue,  True,       NullySpace     ));
        NoNullRet("True",  False     .Coalesce(NullyTrue,  True,       NullyFilledText));
        NoNullRet("",      False     .Coalesce(False,      NullBool,   NullText       ));
        NoNullRet("",      False     .Coalesce(False,      NullBool,   Empty          ));
        NoNullRet(Text,    False     .Coalesce(False,      NullBool,   Text           ));
        NoNullRet(" ",     False     .Coalesce(False,      NullBool,   NullySpace     ));
        NoNullRet(Text,    False     .Coalesce(False,      NullBool,   NullyFilledText));
        NoNullRet("",      False     .Coalesce(False,      NullyFalse, NullText       ));
        NoNullRet("",      False     .Coalesce(False,      NullyFalse, Empty          ));
        NoNullRet(Text,    False     .Coalesce(False,      NullyFalse, Text           ));
        NoNullRet(" ",     False     .Coalesce(False,      NullyFalse, NullySpace     ));
        NoNullRet(Text,    False     .Coalesce(False,      NullyFalse, NullyFilledText));
        NoNullRet("True",  False     .Coalesce(False,      NullyTrue,  NullText       ));
        NoNullRet("True",  False     .Coalesce(False,      NullyTrue,  Empty          ));
        NoNullRet("True",  False     .Coalesce(False,      NullyTrue,  Text           ));
        NoNullRet("True",  False     .Coalesce(False,      NullyTrue,  NullySpace     ));
        NoNullRet("True",  False     .Coalesce(False,      NullyTrue,  NullyFilledText));
        NoNullRet("",      False     .Coalesce(False,      False,      NullText       ));
        NoNullRet("",      False     .Coalesce(False,      False,      Empty          ));
        NoNullRet(Text,    False     .Coalesce(False,      False,      Text           ));
        NoNullRet(" ",     False     .Coalesce(False,      False,      NullySpace     ));
        NoNullRet(Text,    False     .Coalesce(False,      False,      NullyFilledText));
        NoNullRet("True",  False     .Coalesce(False,      True,       NullText       ));
        NoNullRet("True",  False     .Coalesce(False,      True,       Empty          ));
        NoNullRet("True",  False     .Coalesce(False,      True,       Text           ));
        NoNullRet("True",  False     .Coalesce(False,      True,       NullySpace     ));
        NoNullRet("True",  False     .Coalesce(False,      True,       NullyFilledText));
        NoNullRet("True",  False     .Coalesce(True,       NullBool,   NullText       ));
        NoNullRet("True",  False     .Coalesce(True,       NullBool,   Empty          ));
        NoNullRet("True",  False     .Coalesce(True,       NullBool,   Text           ));
        NoNullRet("True",  False     .Coalesce(True,       NullBool,   NullySpace     ));
        NoNullRet("True",  False     .Coalesce(True,       NullBool,   NullyFilledText));
        NoNullRet("True",  False     .Coalesce(True,       NullyFalse, NullText       ));
        NoNullRet("True",  False     .Coalesce(True,       NullyFalse, Empty          ));
        NoNullRet("True",  False     .Coalesce(True,       NullyFalse, Text           ));
        NoNullRet("True",  False     .Coalesce(True,       NullyFalse, NullySpace     ));
        NoNullRet("True",  False     .Coalesce(True,       NullyFalse, NullyFilledText));
        NoNullRet("True",  False     .Coalesce(True,       NullyTrue,  NullText       ));
        NoNullRet("True",  False     .Coalesce(True,       NullyTrue,  Empty          ));
        NoNullRet("True",  False     .Coalesce(True,       NullyTrue,  Text           ));
        NoNullRet("True",  False     .Coalesce(True,       NullyTrue,  NullySpace     ));
        NoNullRet("True",  False     .Coalesce(True,       NullyTrue,  NullyFilledText));
        NoNullRet("True",  False     .Coalesce(True,       False,      NullText       ));
        NoNullRet("True",  False     .Coalesce(True,       False,      Empty          ));
        NoNullRet("True",  False     .Coalesce(True,       False,      Text           ));
        NoNullRet("True",  False     .Coalesce(True,       False,      NullySpace     ));
        NoNullRet("True",  False     .Coalesce(True,       False,      NullyFilledText));
        NoNullRet("True",  False     .Coalesce(True,       True,       NullText       ));
        NoNullRet("True",  False     .Coalesce(True,       True,       Empty          ));
        NoNullRet("True",  False     .Coalesce(True,       True,       Text           ));
        NoNullRet("True",  False     .Coalesce(True,       True,       NullySpace     ));
        NoNullRet("True",  False     .Coalesce(True,       True,       NullyFilledText));
    }

    [TestMethod]
    public void Coalesce_4Args_BoolToText_Extensions_Batch5()
    {
        NoNullRet("True",  True      .Coalesce(NullBool,   NullBool,   NullText       ));
        NoNullRet("True",  True      .Coalesce(NullBool,   NullBool,   Empty          ));
        NoNullRet("True",  True      .Coalesce(NullBool,   NullBool,   Text           ));
        NoNullRet("True",  True      .Coalesce(NullBool,   NullBool,   NullySpace     ));
        NoNullRet("True",  True      .Coalesce(NullBool,   NullBool,   NullyFilledText));
        NoNullRet("True",  True      .Coalesce(NullBool,   NullyFalse, NullText       ));
        NoNullRet("True",  True      .Coalesce(NullBool,   NullyFalse, Empty          ));
        NoNullRet("True",  True      .Coalesce(NullBool,   NullyFalse, Text           ));
        NoNullRet("True",  True      .Coalesce(NullBool,   NullyFalse, NullySpace     ));
        NoNullRet("True",  True      .Coalesce(NullBool,   NullyFalse, NullyFilledText));
        NoNullRet("True",  True      .Coalesce(NullBool,   NullyTrue,  NullText       ));
        NoNullRet("True",  True      .Coalesce(NullBool,   NullyTrue,  Empty          ));
        NoNullRet("True",  True      .Coalesce(NullBool,   NullyTrue,  Text           ));
        NoNullRet("True",  True      .Coalesce(NullBool,   NullyTrue,  NullySpace     ));
        NoNullRet("True",  True      .Coalesce(NullBool,   NullyTrue,  NullyFilledText));
        NoNullRet("True",  True      .Coalesce(NullBool,   False,      NullText       ));
        NoNullRet("True",  True      .Coalesce(NullBool,   False,      Empty          ));
        NoNullRet("True",  True      .Coalesce(NullBool,   False,      Text           ));
        NoNullRet("True",  True      .Coalesce(NullBool,   False,      NullySpace     ));
        NoNullRet("True",  True      .Coalesce(NullBool,   False,      NullyFilledText));
        NoNullRet("True",  True      .Coalesce(NullBool,   True,       NullText       ));
        NoNullRet("True",  True      .Coalesce(NullBool,   True,       Empty          ));
        NoNullRet("True",  True      .Coalesce(NullBool,   True,       Text           ));
        NoNullRet("True",  True      .Coalesce(NullBool,   True,       NullySpace     ));
        NoNullRet("True",  True      .Coalesce(NullBool,   True,       NullyFilledText));
        NoNullRet("True",  True      .Coalesce(NullyFalse, NullBool,   NullText       ));
        NoNullRet("True",  True      .Coalesce(NullyFalse, NullBool,   Empty          ));
        NoNullRet("True",  True      .Coalesce(NullyFalse, NullBool,   Text           ));
        NoNullRet("True",  True      .Coalesce(NullyFalse, NullBool,   NullySpace     ));
        NoNullRet("True",  True      .Coalesce(NullyFalse, NullBool,   NullyFilledText));
        NoNullRet("True",  True      .Coalesce(NullyFalse, NullyFalse, NullText       ));
        NoNullRet("True",  True      .Coalesce(NullyFalse, NullyFalse, Empty          ));
        NoNullRet("True",  True      .Coalesce(NullyFalse, NullyFalse, Text           ));
        NoNullRet("True",  True      .Coalesce(NullyFalse, NullyFalse, NullySpace     ));
        NoNullRet("True",  True      .Coalesce(NullyFalse, NullyFalse, NullyFilledText));
        NoNullRet("True",  True      .Coalesce(NullyFalse, NullyTrue,  NullText       ));
        NoNullRet("True",  True      .Coalesce(NullyFalse, NullyTrue,  Empty          ));
        NoNullRet("True",  True      .Coalesce(NullyFalse, NullyTrue,  Text           ));
        NoNullRet("True",  True      .Coalesce(NullyFalse, NullyTrue,  NullySpace     ));
        NoNullRet("True",  True      .Coalesce(NullyFalse, NullyTrue,  NullyFilledText));
        NoNullRet("True",  True      .Coalesce(NullyFalse, False,      NullText       ));
        NoNullRet("True",  True      .Coalesce(NullyFalse, False,      Empty          ));
        NoNullRet("True",  True      .Coalesce(NullyFalse, False,      Text           ));
        NoNullRet("True",  True      .Coalesce(NullyFalse, False,      NullySpace     ));
        NoNullRet("True",  True      .Coalesce(NullyFalse, False,      NullyFilledText));
        NoNullRet("True",  True      .Coalesce(NullyFalse, True,       NullText       ));
        NoNullRet("True",  True      .Coalesce(NullyFalse, True,       Empty          ));
        NoNullRet("True",  True      .Coalesce(NullyFalse, True,       Text           ));
        NoNullRet("True",  True      .Coalesce(NullyFalse, True,       NullySpace     ));
        NoNullRet("True",  True      .Coalesce(NullyFalse, True,       NullyFilledText));
        NoNullRet("True",  True      .Coalesce(NullyTrue,  NullBool,   NullText       ));
        NoNullRet("True",  True      .Coalesce(NullyTrue,  NullBool,   Empty          ));
        NoNullRet("True",  True      .Coalesce(NullyTrue,  NullBool,   Text           ));
        NoNullRet("True",  True      .Coalesce(NullyTrue,  NullBool,   NullySpace     ));
        NoNullRet("True",  True      .Coalesce(NullyTrue,  NullBool,   NullyFilledText));
        NoNullRet("True",  True      .Coalesce(NullyTrue,  NullyFalse, NullText       ));
        NoNullRet("True",  True      .Coalesce(NullyTrue,  NullyFalse, Empty          ));
        NoNullRet("True",  True      .Coalesce(NullyTrue,  NullyFalse, Text           ));
        NoNullRet("True",  True      .Coalesce(NullyTrue,  NullyFalse, NullySpace     ));
        NoNullRet("True",  True      .Coalesce(NullyTrue,  NullyFalse, NullyFilledText));
        NoNullRet("True",  True      .Coalesce(NullyTrue,  NullyTrue,  NullText       ));
        NoNullRet("True",  True      .Coalesce(NullyTrue,  NullyTrue,  Empty          ));
        NoNullRet("True",  True      .Coalesce(NullyTrue,  NullyTrue,  Text           ));
        NoNullRet("True",  True      .Coalesce(NullyTrue,  NullyTrue,  NullySpace     ));
        NoNullRet("True",  True      .Coalesce(NullyTrue,  NullyTrue,  NullyFilledText));
        NoNullRet("True",  True      .Coalesce(NullyTrue,  False,      NullText       ));
        NoNullRet("True",  True      .Coalesce(NullyTrue,  False,      Empty          ));
        NoNullRet("True",  True      .Coalesce(NullyTrue,  False,      Text           ));
        NoNullRet("True",  True      .Coalesce(NullyTrue,  False,      NullySpace     ));
        NoNullRet("True",  True      .Coalesce(NullyTrue,  False,      NullyFilledText));
        NoNullRet("True",  True      .Coalesce(NullyTrue,  True,       NullText       ));
        NoNullRet("True",  True      .Coalesce(NullyTrue,  True,       Empty          ));
        NoNullRet("True",  True      .Coalesce(NullyTrue,  True,       Text           ));
        NoNullRet("True",  True      .Coalesce(NullyTrue,  True,       NullySpace     ));
        NoNullRet("True",  True      .Coalesce(NullyTrue,  True,       NullyFilledText));
        NoNullRet("True",  True      .Coalesce(False,      NullBool,   NullText       ));
        NoNullRet("True",  True      .Coalesce(False,      NullBool,   Empty          ));
        NoNullRet("True",  True      .Coalesce(False,      NullBool,   Text           ));
        NoNullRet("True",  True      .Coalesce(False,      NullBool,   NullySpace     ));
        NoNullRet("True",  True      .Coalesce(False,      NullBool,   NullyFilledText));
        NoNullRet("True",  True      .Coalesce(False,      NullyFalse, NullText       ));
        NoNullRet("True",  True      .Coalesce(False,      NullyFalse, Empty          ));
        NoNullRet("True",  True      .Coalesce(False,      NullyFalse, Text           ));
        NoNullRet("True",  True      .Coalesce(False,      NullyFalse, NullySpace     ));
        NoNullRet("True",  True      .Coalesce(False,      NullyFalse, NullyFilledText));
        NoNullRet("True",  True      .Coalesce(False,      NullyTrue,  NullText       ));
        NoNullRet("True",  True      .Coalesce(False,      NullyTrue,  Empty          ));
        NoNullRet("True",  True      .Coalesce(False,      NullyTrue,  Text           ));
        NoNullRet("True",  True      .Coalesce(False,      NullyTrue,  NullySpace     ));
        NoNullRet("True",  True      .Coalesce(False,      NullyTrue,  NullyFilledText));
        NoNullRet("True",  True      .Coalesce(False,      False,      NullText       ));
        NoNullRet("True",  True      .Coalesce(False,      False,      Empty          ));
        NoNullRet("True",  True      .Coalesce(False,      False,      Text           ));
        NoNullRet("True",  True      .Coalesce(False,      False,      NullySpace     ));
        NoNullRet("True",  True      .Coalesce(False,      False,      NullyFilledText));
        NoNullRet("True",  True      .Coalesce(False,      True,       NullText       ));
        NoNullRet("True",  True      .Coalesce(False,      True,       Empty          ));
        NoNullRet("True",  True      .Coalesce(False,      True,       Text           ));
        NoNullRet("True",  True      .Coalesce(False,      True,       NullySpace     ));
        NoNullRet("True",  True      .Coalesce(False,      True,       NullyFilledText));
        NoNullRet("True",  True      .Coalesce(True,       NullBool,   NullText       ));
        NoNullRet("True",  True      .Coalesce(True,       NullBool,   Empty          ));
        NoNullRet("True",  True      .Coalesce(True,       NullBool,   Text           ));
        NoNullRet("True",  True      .Coalesce(True,       NullBool,   NullySpace     ));
        NoNullRet("True",  True      .Coalesce(True,       NullBool,   NullyFilledText));
        NoNullRet("True",  True      .Coalesce(True,       NullyFalse, NullText       ));
        NoNullRet("True",  True      .Coalesce(True,       NullyFalse, Empty          ));
        NoNullRet("True",  True      .Coalesce(True,       NullyFalse, Text           ));
        NoNullRet("True",  True      .Coalesce(True,       NullyFalse, NullySpace     ));
        NoNullRet("True",  True      .Coalesce(True,       NullyFalse, NullyFilledText));
        NoNullRet("True",  True      .Coalesce(True,       NullyTrue,  NullText       ));
        NoNullRet("True",  True      .Coalesce(True,       NullyTrue,  Empty          ));
        NoNullRet("True",  True      .Coalesce(True,       NullyTrue,  Text           ));
        NoNullRet("True",  True      .Coalesce(True,       NullyTrue,  NullySpace     ));
        NoNullRet("True",  True      .Coalesce(True,       NullyTrue,  NullyFilledText));
        NoNullRet("True",  True      .Coalesce(True,       False,      NullText       ));
        NoNullRet("True",  True      .Coalesce(True,       False,      Empty          ));
        NoNullRet("True",  True      .Coalesce(True,       False,      Text           ));
        NoNullRet("True",  True      .Coalesce(True,       False,      NullySpace     ));
        NoNullRet("True",  True      .Coalesce(True,       False,      NullyFilledText));
        NoNullRet("True",  True      .Coalesce(True,       True,       NullText       ));
        NoNullRet("True",  True      .Coalesce(True,       True,       Empty          ));
        NoNullRet("True",  True      .Coalesce(True,       True,       Text           ));
        NoNullRet("True",  True      .Coalesce(True,       True,       NullySpace     ));
        NoNullRet("True",  True      .Coalesce(True,       True,       NullyFilledText));
    }
}