global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Xml.Serialization;
global using JJ.Framework.Common.Legacy;
global using JJ.Framework.Reflection.Legacy;
global using static System.ArgumentNullException;
global using static JJ.Framework.PlatformCompatibility.Core.ExceptionSupport;
global using static JJ.Framework.SharedProject.Core.NoTrimReasons;