namespace JJ.Framework.Existence.Core.Tests;

/// <inheritdoc cref="_coalesce4argsbool" />
[TestClass]
public class Coalesce_4Args_Bool_Extensions : TestBase
{
    private readonly bool? Null = null;

    [TestMethod]
    public void Coalesce_4Args_Bool_ExtensionsBatch1()
    {
        NoNullRet(false, Null      .Coalesce(Null,       Null,       Null      ));
        NoNullRet(false, Null      .Coalesce(Null,       Null,       False     ));
        NoNullRet(true,  Null      .Coalesce(Null,       Null,       True      ));
        NoNullRet(false, Null      .Coalesce(Null,       Null,       NullyFalse));
        NoNullRet(true,  Null      .Coalesce(Null,       Null,       NullyTrue ));
        NoNullRet(false, Null      .Coalesce(Null,       False,      Null      ));
        NoNullRet(false, Null      .Coalesce(Null,       False,      False     ));
        NoNullRet(true,  Null      .Coalesce(Null,       False,      True      ));
        NoNullRet(false, Null      .Coalesce(Null,       False,      NullyFalse));
        NoNullRet(true,  Null      .Coalesce(Null,       False,      NullyTrue ));
        NoNullRet(true,  Null      .Coalesce(Null,       True,       Null      ));
        NoNullRet(true,  Null      .Coalesce(Null,       True,       False     ));
        NoNullRet(true,  Null      .Coalesce(Null,       True,       True      ));
        NoNullRet(true,  Null      .Coalesce(Null,       True,       NullyFalse));
        NoNullRet(true,  Null      .Coalesce(Null,       True,       NullyTrue ));
        NoNullRet(false, Null      .Coalesce(Null,       NullyFalse, Null      ));
        NoNullRet(false, Null      .Coalesce(Null,       NullyFalse, False     ));
        NoNullRet(true,  Null      .Coalesce(Null,       NullyFalse, True      ));
        NoNullRet(false, Null      .Coalesce(Null,       NullyFalse, NullyFalse));
        NoNullRet(true,  Null      .Coalesce(Null,       NullyFalse, NullyTrue ));
        NoNullRet(true,  Null      .Coalesce(Null,       NullyTrue,  Null      ));
        NoNullRet(true,  Null      .Coalesce(Null,       NullyTrue,  False     ));
        NoNullRet(true,  Null      .Coalesce(Null,       NullyTrue,  True      ));
        NoNullRet(true,  Null      .Coalesce(Null,       NullyTrue,  NullyFalse));
        NoNullRet(true,  Null      .Coalesce(Null,       NullyTrue,  NullyTrue ));
        NoNullRet(false, Null      .Coalesce(False,      Null,       Null      ));
        NoNullRet(false, Null      .Coalesce(False,      Null,       False     ));
        NoNullRet(true,  Null      .Coalesce(False,      Null,       True      ));
        NoNullRet(false, Null      .Coalesce(False,      Null,       NullyFalse));
        NoNullRet(true,  Null      .Coalesce(False,      Null,       NullyTrue ));
        NoNullRet(false, Null      .Coalesce(False,      False,      Null      ));
        NoNullRet(false, Null      .Coalesce(False,      False,      False     ));
        NoNullRet(true,  Null      .Coalesce(False,      False,      True      ));
        NoNullRet(false, Null      .Coalesce(False,      False,      NullyFalse));
        NoNullRet(true,  Null      .Coalesce(False,      False,      NullyTrue ));
        NoNullRet(true,  Null      .Coalesce(False,      True,       Null      ));
        NoNullRet(true,  Null      .Coalesce(False,      True,       False     ));
        NoNullRet(true,  Null      .Coalesce(False,      True,       True      ));
        NoNullRet(true,  Null      .Coalesce(False,      True,       NullyFalse));
        NoNullRet(true,  Null      .Coalesce(False,      True,       NullyTrue ));
        NoNullRet(false, Null      .Coalesce(False,      NullyFalse, Null      ));
        NoNullRet(false, Null      .Coalesce(False,      NullyFalse, False     ));
        NoNullRet(true,  Null      .Coalesce(False,      NullyFalse, True      ));
        NoNullRet(false, Null      .Coalesce(False,      NullyFalse, NullyFalse));
        NoNullRet(true,  Null      .Coalesce(False,      NullyFalse, NullyTrue ));
        NoNullRet(true,  Null      .Coalesce(False,      NullyTrue,  Null      ));
        NoNullRet(true,  Null      .Coalesce(False,      NullyTrue,  False     ));
        NoNullRet(true,  Null      .Coalesce(False,      NullyTrue,  True      ));
        NoNullRet(true,  Null      .Coalesce(False,      NullyTrue,  NullyFalse));
        NoNullRet(true,  Null      .Coalesce(False,      NullyTrue,  NullyTrue ));
        NoNullRet(true,  Null      .Coalesce(True,       Null,       Null      ));
        NoNullRet(true,  Null      .Coalesce(True,       Null,       False     ));
        NoNullRet(true,  Null      .Coalesce(True,       Null,       True      ));
        NoNullRet(true,  Null      .Coalesce(True,       Null,       NullyFalse));
        NoNullRet(true,  Null      .Coalesce(True,       Null,       NullyTrue ));
        NoNullRet(true,  Null      .Coalesce(True,       False,      Null      ));
        NoNullRet(true,  Null      .Coalesce(True,       False,      False     ));
        NoNullRet(true,  Null      .Coalesce(True,       False,      True      ));
        NoNullRet(true,  Null      .Coalesce(True,       False,      NullyFalse));
        NoNullRet(true,  Null      .Coalesce(True,       False,      NullyTrue ));
        NoNullRet(true,  Null      .Coalesce(True,       True,       Null      ));
        NoNullRet(true,  Null      .Coalesce(True,       True,       False     ));
        NoNullRet(true,  Null      .Coalesce(True,       True,       True      ));
        NoNullRet(true,  Null      .Coalesce(True,       True,       NullyFalse));
        NoNullRet(true,  Null      .Coalesce(True,       True,       NullyTrue ));
        NoNullRet(true,  Null      .Coalesce(True,       NullyFalse, Null      ));
        NoNullRet(true,  Null      .Coalesce(True,       NullyFalse, False     ));
        NoNullRet(true,  Null      .Coalesce(True,       NullyFalse, True      ));
        NoNullRet(true,  Null      .Coalesce(True,       NullyFalse, NullyFalse));
        NoNullRet(true,  Null      .Coalesce(True,       NullyFalse, NullyTrue ));
        NoNullRet(true,  Null      .Coalesce(True,       NullyTrue,  Null      ));
        NoNullRet(true,  Null      .Coalesce(True,       NullyTrue,  False     ));
        NoNullRet(true,  Null      .Coalesce(True,       NullyTrue,  True      ));
        NoNullRet(true,  Null      .Coalesce(True,       NullyTrue,  NullyFalse));
        NoNullRet(true,  Null      .Coalesce(True,       NullyTrue,  NullyTrue ));
        NoNullRet(false, Null      .Coalesce(NullyFalse, Null,       Null      ));
        NoNullRet(false, Null      .Coalesce(NullyFalse, Null,       False     ));
        NoNullRet(true,  Null      .Coalesce(NullyFalse, Null,       True      ));
        NoNullRet(false, Null      .Coalesce(NullyFalse, Null,       NullyFalse));
        NoNullRet(true,  Null      .Coalesce(NullyFalse, Null,       NullyTrue ));
        NoNullRet(false, Null      .Coalesce(NullyFalse, False,      Null      ));
        NoNullRet(false, Null      .Coalesce(NullyFalse, False,      False     ));
        NoNullRet(true,  Null      .Coalesce(NullyFalse, False,      True      ));
        NoNullRet(false, Null      .Coalesce(NullyFalse, False,      NullyFalse));
        NoNullRet(true,  Null      .Coalesce(NullyFalse, False,      NullyTrue ));
        NoNullRet(true,  Null      .Coalesce(NullyFalse, True,       Null      ));
        NoNullRet(true,  Null      .Coalesce(NullyFalse, True,       False     ));
        NoNullRet(true,  Null      .Coalesce(NullyFalse, True,       True      ));
        NoNullRet(true,  Null      .Coalesce(NullyFalse, True,       NullyFalse));
        NoNullRet(true,  Null      .Coalesce(NullyFalse, True,       NullyTrue ));
        NoNullRet(false, Null      .Coalesce(NullyFalse, NullyFalse, Null      ));
        NoNullRet(false, Null      .Coalesce(NullyFalse, NullyFalse, False     ));
        NoNullRet(true,  Null      .Coalesce(NullyFalse, NullyFalse, True      ));
        NoNullRet(false, Null      .Coalesce(NullyFalse, NullyFalse, NullyFalse));
        NoNullRet(true,  Null      .Coalesce(NullyFalse, NullyFalse, NullyTrue ));
        NoNullRet(true,  Null      .Coalesce(NullyFalse, NullyTrue,  Null      ));
        NoNullRet(true,  Null      .Coalesce(NullyFalse, NullyTrue,  False     ));
        NoNullRet(true,  Null      .Coalesce(NullyFalse, NullyTrue,  True      ));
        NoNullRet(true,  Null      .Coalesce(NullyFalse, NullyTrue,  NullyFalse));
        NoNullRet(true,  Null      .Coalesce(NullyFalse, NullyTrue,  NullyTrue ));
        NoNullRet(true,  Null      .Coalesce(NullyTrue,  Null,       Null      ));
        NoNullRet(true,  Null      .Coalesce(NullyTrue,  Null,       False     ));
        NoNullRet(true,  Null      .Coalesce(NullyTrue,  Null,       True      ));
        NoNullRet(true,  Null      .Coalesce(NullyTrue,  Null,       NullyFalse));
        NoNullRet(true,  Null      .Coalesce(NullyTrue,  Null,       NullyTrue ));
        NoNullRet(true,  Null      .Coalesce(NullyTrue,  False,      Null      ));
        NoNullRet(true,  Null      .Coalesce(NullyTrue,  False,      False     ));
        NoNullRet(true,  Null      .Coalesce(NullyTrue,  False,      True      ));
        NoNullRet(true,  Null      .Coalesce(NullyTrue,  False,      NullyFalse));
        NoNullRet(true,  Null      .Coalesce(NullyTrue,  False,      NullyTrue ));
        NoNullRet(true,  Null      .Coalesce(NullyTrue,  True,       Null      ));
        NoNullRet(true,  Null      .Coalesce(NullyTrue,  True,       False     ));
        NoNullRet(true,  Null      .Coalesce(NullyTrue,  True,       True      ));
        NoNullRet(true,  Null      .Coalesce(NullyTrue,  True,       NullyFalse));
        NoNullRet(true,  Null      .Coalesce(NullyTrue,  True,       NullyTrue ));
        NoNullRet(true,  Null      .Coalesce(NullyTrue,  NullyFalse, Null      ));
        NoNullRet(true,  Null      .Coalesce(NullyTrue,  NullyFalse, False     ));
        NoNullRet(true,  Null      .Coalesce(NullyTrue,  NullyFalse, True      ));
        NoNullRet(true,  Null      .Coalesce(NullyTrue,  NullyFalse, NullyFalse));
        NoNullRet(true,  Null      .Coalesce(NullyTrue,  NullyFalse, NullyTrue ));
        NoNullRet(true,  Null      .Coalesce(NullyTrue,  NullyTrue,  Null      ));
        NoNullRet(true,  Null      .Coalesce(NullyTrue,  NullyTrue,  False     ));
        NoNullRet(true,  Null      .Coalesce(NullyTrue,  NullyTrue,  True      ));
        NoNullRet(true,  Null      .Coalesce(NullyTrue,  NullyTrue,  NullyFalse));
        NoNullRet(true,  Null      .Coalesce(NullyTrue,  NullyTrue,  NullyTrue ));
    }

    [TestMethod]
    public void Coalesce_4Args_Bool_ExtensionsBatch2()
    {
        NoNullRet(false, False     .Coalesce(Null,       Null,       Null      ));
        NoNullRet(false, False     .Coalesce(Null,       Null,       False     ));
        NoNullRet(true,  False     .Coalesce(Null,       Null,       True      ));
        NoNullRet(false, False     .Coalesce(Null,       Null,       NullyFalse));
        NoNullRet(true,  False     .Coalesce(Null,       Null,       NullyTrue ));
        NoNullRet(false, False     .Coalesce(Null,       False,      Null      ));
        NoNullRet(false, False     .Coalesce(Null,       False,      False     ));
        NoNullRet(true,  False     .Coalesce(Null,       False,      True      ));
        NoNullRet(false, False     .Coalesce(Null,       False,      NullyFalse));
        NoNullRet(true,  False     .Coalesce(Null,       False,      NullyTrue ));
        NoNullRet(true,  False     .Coalesce(Null,       True,       Null      ));
        NoNullRet(true,  False     .Coalesce(Null,       True,       False     ));
        NoNullRet(true,  False     .Coalesce(Null,       True,       True      ));
        NoNullRet(true,  False     .Coalesce(Null,       True,       NullyFalse));
        NoNullRet(true,  False     .Coalesce(Null,       True,       NullyTrue ));
        NoNullRet(false, False     .Coalesce(Null,       NullyFalse, Null      ));
        NoNullRet(false, False     .Coalesce(Null,       NullyFalse, False     ));
        NoNullRet(true,  False     .Coalesce(Null,       NullyFalse, True      ));
        NoNullRet(false, False     .Coalesce(Null,       NullyFalse, NullyFalse));
        NoNullRet(true,  False     .Coalesce(Null,       NullyFalse, NullyTrue ));
        NoNullRet(true,  False     .Coalesce(Null,       NullyTrue,  Null      ));
        NoNullRet(true,  False     .Coalesce(Null,       NullyTrue,  False     ));
        NoNullRet(true,  False     .Coalesce(Null,       NullyTrue,  True      ));
        NoNullRet(true,  False     .Coalesce(Null,       NullyTrue,  NullyFalse));
        NoNullRet(true,  False     .Coalesce(Null,       NullyTrue,  NullyTrue ));
        NoNullRet(false, False     .Coalesce(False,      Null,       Null      ));
        NoNullRet(false, False     .Coalesce(False,      Null,       False     ));
        NoNullRet(true,  False     .Coalesce(False,      Null,       True      ));
        NoNullRet(false, False     .Coalesce(False,      Null,       NullyFalse));
        NoNullRet(true,  False     .Coalesce(False,      Null,       NullyTrue ));
        NoNullRet(false, False     .Coalesce(False,      False,      Null      ));
        NoNullRet(false, False     .Coalesce(False,      False,      False     ));
        NoNullRet(true,  False     .Coalesce(False,      False,      True      ));
        NoNullRet(false, False     .Coalesce(False,      False,      NullyFalse));
        NoNullRet(true,  False     .Coalesce(False,      False,      NullyTrue ));
        NoNullRet(true,  False     .Coalesce(False,      True,       Null      ));
        NoNullRet(true,  False     .Coalesce(False,      True,       False     ));
        NoNullRet(true,  False     .Coalesce(False,      True,       True      ));
        NoNullRet(true,  False     .Coalesce(False,      True,       NullyFalse));
        NoNullRet(true,  False     .Coalesce(False,      True,       NullyTrue ));
        NoNullRet(false, False     .Coalesce(False,      NullyFalse, Null      ));
        NoNullRet(false, False     .Coalesce(False,      NullyFalse, False     ));
        NoNullRet(true,  False     .Coalesce(False,      NullyFalse, True      ));
        NoNullRet(false, False     .Coalesce(False,      NullyFalse, NullyFalse));
        NoNullRet(true,  False     .Coalesce(False,      NullyFalse, NullyTrue ));
        NoNullRet(true,  False     .Coalesce(False,      NullyTrue,  Null      ));
        NoNullRet(true,  False     .Coalesce(False,      NullyTrue,  False     ));
        NoNullRet(true,  False     .Coalesce(False,      NullyTrue,  True      ));
        NoNullRet(true,  False     .Coalesce(False,      NullyTrue,  NullyFalse));
        NoNullRet(true,  False     .Coalesce(False,      NullyTrue,  NullyTrue ));
        NoNullRet(true,  False     .Coalesce(True,       Null,       Null      ));
        NoNullRet(true,  False     .Coalesce(True,       Null,       False     ));
        NoNullRet(true,  False     .Coalesce(True,       Null,       True      ));
        NoNullRet(true,  False     .Coalesce(True,       Null,       NullyFalse));
        NoNullRet(true,  False     .Coalesce(True,       Null,       NullyTrue ));
        NoNullRet(true,  False     .Coalesce(True,       False,      Null      ));
        NoNullRet(true,  False     .Coalesce(True,       False,      False     ));
        NoNullRet(true,  False     .Coalesce(True,       False,      True      ));
        NoNullRet(true,  False     .Coalesce(True,       False,      NullyFalse));
        NoNullRet(true,  False     .Coalesce(True,       False,      NullyTrue ));
        NoNullRet(true,  False     .Coalesce(True,       True,       Null      ));
        NoNullRet(true,  False     .Coalesce(True,       True,       False     ));
        NoNullRet(true,  False     .Coalesce(True,       True,       True      ));
        NoNullRet(true,  False     .Coalesce(True,       True,       NullyFalse));
        NoNullRet(true,  False     .Coalesce(True,       True,       NullyTrue ));
        NoNullRet(true,  False     .Coalesce(True,       NullyFalse, Null      ));
        NoNullRet(true,  False     .Coalesce(True,       NullyFalse, False     ));
        NoNullRet(true,  False     .Coalesce(True,       NullyFalse, True      ));
        NoNullRet(true,  False     .Coalesce(True,       NullyFalse, NullyFalse));
        NoNullRet(true,  False     .Coalesce(True,       NullyFalse, NullyTrue ));
        NoNullRet(true,  False     .Coalesce(True,       NullyTrue,  Null      ));
        NoNullRet(true,  False     .Coalesce(True,       NullyTrue,  False     ));
        NoNullRet(true,  False     .Coalesce(True,       NullyTrue,  True      ));
        NoNullRet(true,  False     .Coalesce(True,       NullyTrue,  NullyFalse));
        NoNullRet(true,  False     .Coalesce(True,       NullyTrue,  NullyTrue ));
        NoNullRet(false, False     .Coalesce(NullyFalse, Null,       Null      ));
        NoNullRet(false, False     .Coalesce(NullyFalse, Null,       False     ));
        NoNullRet(true,  False     .Coalesce(NullyFalse, Null,       True      ));
        NoNullRet(false, False     .Coalesce(NullyFalse, Null,       NullyFalse));
        NoNullRet(true,  False     .Coalesce(NullyFalse, Null,       NullyTrue ));
        NoNullRet(false, False     .Coalesce(NullyFalse, False,      Null      ));
        NoNullRet(false, False     .Coalesce(NullyFalse, False,      False     ));
        NoNullRet(true,  False     .Coalesce(NullyFalse, False,      True      ));
        NoNullRet(false, False     .Coalesce(NullyFalse, False,      NullyFalse));
        NoNullRet(true,  False     .Coalesce(NullyFalse, False,      NullyTrue ));
        NoNullRet(true,  False     .Coalesce(NullyFalse, True,       Null      ));
        NoNullRet(true,  False     .Coalesce(NullyFalse, True,       False     ));
        NoNullRet(true,  False     .Coalesce(NullyFalse, True,       True      ));
        NoNullRet(true,  False     .Coalesce(NullyFalse, True,       NullyFalse));
        NoNullRet(true,  False     .Coalesce(NullyFalse, True,       NullyTrue ));
        NoNullRet(false, False     .Coalesce(NullyFalse, NullyFalse, Null      ));
        NoNullRet(false, False     .Coalesce(NullyFalse, NullyFalse, False     ));
        NoNullRet(true,  False     .Coalesce(NullyFalse, NullyFalse, True      ));
        NoNullRet(false, False     .Coalesce(NullyFalse, NullyFalse, NullyFalse));
        NoNullRet(true,  False     .Coalesce(NullyFalse, NullyFalse, NullyTrue ));
        NoNullRet(true,  False     .Coalesce(NullyFalse, NullyTrue,  Null      ));
        NoNullRet(true,  False     .Coalesce(NullyFalse, NullyTrue,  False     ));
        NoNullRet(true,  False     .Coalesce(NullyFalse, NullyTrue,  True      ));
        NoNullRet(true,  False     .Coalesce(NullyFalse, NullyTrue,  NullyFalse));
        NoNullRet(true,  False     .Coalesce(NullyFalse, NullyTrue,  NullyTrue ));
        NoNullRet(true,  False     .Coalesce(NullyTrue,  Null,       Null      ));
        NoNullRet(true,  False     .Coalesce(NullyTrue,  Null,       False     ));
        NoNullRet(true,  False     .Coalesce(NullyTrue,  Null,       True      ));
        NoNullRet(true,  False     .Coalesce(NullyTrue,  Null,       NullyFalse));
        NoNullRet(true,  False     .Coalesce(NullyTrue,  Null,       NullyTrue ));
        NoNullRet(true,  False     .Coalesce(NullyTrue,  False,      Null      ));
        NoNullRet(true,  False     .Coalesce(NullyTrue,  False,      False     ));
        NoNullRet(true,  False     .Coalesce(NullyTrue,  False,      True      ));
        NoNullRet(true,  False     .Coalesce(NullyTrue,  False,      NullyFalse));
        NoNullRet(true,  False     .Coalesce(NullyTrue,  False,      NullyTrue ));
        NoNullRet(true,  False     .Coalesce(NullyTrue,  True,       Null      ));
        NoNullRet(true,  False     .Coalesce(NullyTrue,  True,       False     ));
        NoNullRet(true,  False     .Coalesce(NullyTrue,  True,       True      ));
        NoNullRet(true,  False     .Coalesce(NullyTrue,  True,       NullyFalse));
        NoNullRet(true,  False     .Coalesce(NullyTrue,  True,       NullyTrue ));
        NoNullRet(true,  False     .Coalesce(NullyTrue,  NullyFalse, Null      ));
        NoNullRet(true,  False     .Coalesce(NullyTrue,  NullyFalse, False     ));
        NoNullRet(true,  False     .Coalesce(NullyTrue,  NullyFalse, True      ));
        NoNullRet(true,  False     .Coalesce(NullyTrue,  NullyFalse, NullyFalse));
        NoNullRet(true,  False     .Coalesce(NullyTrue,  NullyFalse, NullyTrue ));
        NoNullRet(true,  False     .Coalesce(NullyTrue,  NullyTrue,  Null      ));
        NoNullRet(true,  False     .Coalesce(NullyTrue,  NullyTrue,  False     ));
        NoNullRet(true,  False     .Coalesce(NullyTrue,  NullyTrue,  True      ));
        NoNullRet(true,  False     .Coalesce(NullyTrue,  NullyTrue,  NullyFalse));
        NoNullRet(true,  False     .Coalesce(NullyTrue,  NullyTrue,  NullyTrue ));
    }

    [TestMethod]
    public void Coalesce_4Args_Bool_ExtensionsBatch3()
    {
        NoNullRet(true,  True      .Coalesce(Null,       Null,       Null      ));
        NoNullRet(true,  True      .Coalesce(Null,       Null,       False     ));
        NoNullRet(true,  True      .Coalesce(Null,       Null,       True      ));
        NoNullRet(true,  True      .Coalesce(Null,       Null,       NullyFalse));
        NoNullRet(true,  True      .Coalesce(Null,       Null,       NullyTrue ));
        NoNullRet(true,  True      .Coalesce(Null,       False,      Null      ));
        NoNullRet(true,  True      .Coalesce(Null,       False,      False     ));
        NoNullRet(true,  True      .Coalesce(Null,       False,      True      ));
        NoNullRet(true,  True      .Coalesce(Null,       False,      NullyFalse));
        NoNullRet(true,  True      .Coalesce(Null,       False,      NullyTrue ));
        NoNullRet(true,  True      .Coalesce(Null,       True,       Null      ));
        NoNullRet(true,  True      .Coalesce(Null,       True,       False     ));
        NoNullRet(true,  True      .Coalesce(Null,       True,       True      ));
        NoNullRet(true,  True      .Coalesce(Null,       True,       NullyFalse));
        NoNullRet(true,  True      .Coalesce(Null,       True,       NullyTrue ));
        NoNullRet(true,  True      .Coalesce(Null,       NullyFalse, Null      ));
        NoNullRet(true,  True      .Coalesce(Null,       NullyFalse, False     ));
        NoNullRet(true,  True      .Coalesce(Null,       NullyFalse, True      ));
        NoNullRet(true,  True      .Coalesce(Null,       NullyFalse, NullyFalse));
        NoNullRet(true,  True      .Coalesce(Null,       NullyFalse, NullyTrue ));
        NoNullRet(true,  True      .Coalesce(Null,       NullyTrue,  Null      ));
        NoNullRet(true,  True      .Coalesce(Null,       NullyTrue,  False     ));
        NoNullRet(true,  True      .Coalesce(Null,       NullyTrue,  True      ));
        NoNullRet(true,  True      .Coalesce(Null,       NullyTrue,  NullyFalse));
        NoNullRet(true,  True      .Coalesce(Null,       NullyTrue,  NullyTrue ));
        NoNullRet(true,  True      .Coalesce(False,      Null,       Null      ));
        NoNullRet(true,  True      .Coalesce(False,      Null,       False     ));
        NoNullRet(true,  True      .Coalesce(False,      Null,       True      ));
        NoNullRet(true,  True      .Coalesce(False,      Null,       NullyFalse));
        NoNullRet(true,  True      .Coalesce(False,      Null,       NullyTrue ));
        NoNullRet(true,  True      .Coalesce(False,      False,      Null      ));
        NoNullRet(true,  True      .Coalesce(False,      False,      False     ));
        NoNullRet(true,  True      .Coalesce(False,      False,      True      ));
        NoNullRet(true,  True      .Coalesce(False,      False,      NullyFalse));
        NoNullRet(true,  True      .Coalesce(False,      False,      NullyTrue ));
        NoNullRet(true,  True      .Coalesce(False,      True,       Null      ));
        NoNullRet(true,  True      .Coalesce(False,      True,       False     ));
        NoNullRet(true,  True      .Coalesce(False,      True,       True      ));
        NoNullRet(true,  True      .Coalesce(False,      True,       NullyFalse));
        NoNullRet(true,  True      .Coalesce(False,      True,       NullyTrue ));
        NoNullRet(true,  True      .Coalesce(False,      NullyFalse, Null      ));
        NoNullRet(true,  True      .Coalesce(False,      NullyFalse, False     ));
        NoNullRet(true,  True      .Coalesce(False,      NullyFalse, True      ));
        NoNullRet(true,  True      .Coalesce(False,      NullyFalse, NullyFalse));
        NoNullRet(true,  True      .Coalesce(False,      NullyFalse, NullyTrue ));
        NoNullRet(true,  True      .Coalesce(False,      NullyTrue,  Null      ));
        NoNullRet(true,  True      .Coalesce(False,      NullyTrue,  False     ));
        NoNullRet(true,  True      .Coalesce(False,      NullyTrue,  True      ));
        NoNullRet(true,  True      .Coalesce(False,      NullyTrue,  NullyFalse));
        NoNullRet(true,  True      .Coalesce(False,      NullyTrue,  NullyTrue ));
        NoNullRet(true,  True      .Coalesce(True,       Null,       Null      ));
        NoNullRet(true,  True      .Coalesce(True,       Null,       False     ));
        NoNullRet(true,  True      .Coalesce(True,       Null,       True      ));
        NoNullRet(true,  True      .Coalesce(True,       Null,       NullyFalse));
        NoNullRet(true,  True      .Coalesce(True,       Null,       NullyTrue ));
        NoNullRet(true,  True      .Coalesce(True,       False,      Null      ));
        NoNullRet(true,  True      .Coalesce(True,       False,      False     ));
        NoNullRet(true,  True      .Coalesce(True,       False,      True      ));
        NoNullRet(true,  True      .Coalesce(True,       False,      NullyFalse));
        NoNullRet(true,  True      .Coalesce(True,       False,      NullyTrue ));
        NoNullRet(true,  True      .Coalesce(True,       True,       Null      ));
        NoNullRet(true,  True      .Coalesce(True,       True,       False     ));
        NoNullRet(true,  True      .Coalesce(True,       True,       True      ));
        NoNullRet(true,  True      .Coalesce(True,       True,       NullyFalse));
        NoNullRet(true,  True      .Coalesce(True,       True,       NullyTrue ));
        NoNullRet(true,  True      .Coalesce(True,       NullyFalse, Null      ));
        NoNullRet(true,  True      .Coalesce(True,       NullyFalse, False     ));
        NoNullRet(true,  True      .Coalesce(True,       NullyFalse, True      ));
        NoNullRet(true,  True      .Coalesce(True,       NullyFalse, NullyFalse));
        NoNullRet(true,  True      .Coalesce(True,       NullyFalse, NullyTrue ));
        NoNullRet(true,  True      .Coalesce(True,       NullyTrue,  Null      ));
        NoNullRet(true,  True      .Coalesce(True,       NullyTrue,  False     ));
        NoNullRet(true,  True      .Coalesce(True,       NullyTrue,  True      ));
        NoNullRet(true,  True      .Coalesce(True,       NullyTrue,  NullyFalse));
        NoNullRet(true,  True      .Coalesce(True,       NullyTrue,  NullyTrue ));
        NoNullRet(true,  True      .Coalesce(NullyFalse, Null,       Null      ));
        NoNullRet(true,  True      .Coalesce(NullyFalse, Null,       False     ));
        NoNullRet(true,  True      .Coalesce(NullyFalse, Null,       True      ));
        NoNullRet(true,  True      .Coalesce(NullyFalse, Null,       NullyFalse));
        NoNullRet(true,  True      .Coalesce(NullyFalse, Null,       NullyTrue ));
        NoNullRet(true,  True      .Coalesce(NullyFalse, False,      Null      ));
        NoNullRet(true,  True      .Coalesce(NullyFalse, False,      False     ));
        NoNullRet(true,  True      .Coalesce(NullyFalse, False,      True      ));
        NoNullRet(true,  True      .Coalesce(NullyFalse, False,      NullyFalse));
        NoNullRet(true,  True      .Coalesce(NullyFalse, False,      NullyTrue ));
        NoNullRet(true,  True      .Coalesce(NullyFalse, True,       Null      ));
        NoNullRet(true,  True      .Coalesce(NullyFalse, True,       False     ));
        NoNullRet(true,  True      .Coalesce(NullyFalse, True,       True      ));
        NoNullRet(true,  True      .Coalesce(NullyFalse, True,       NullyFalse));
        NoNullRet(true,  True      .Coalesce(NullyFalse, True,       NullyTrue ));
        NoNullRet(true,  True      .Coalesce(NullyFalse, NullyFalse, Null      ));
        NoNullRet(true,  True      .Coalesce(NullyFalse, NullyFalse, False     ));
        NoNullRet(true,  True      .Coalesce(NullyFalse, NullyFalse, True      ));
        NoNullRet(true,  True      .Coalesce(NullyFalse, NullyFalse, NullyFalse));
        NoNullRet(true,  True      .Coalesce(NullyFalse, NullyFalse, NullyTrue ));
        NoNullRet(true,  True      .Coalesce(NullyFalse, NullyTrue,  Null      ));
        NoNullRet(true,  True      .Coalesce(NullyFalse, NullyTrue,  False     ));
        NoNullRet(true,  True      .Coalesce(NullyFalse, NullyTrue,  True      ));
        NoNullRet(true,  True      .Coalesce(NullyFalse, NullyTrue,  NullyFalse));
        NoNullRet(true,  True      .Coalesce(NullyFalse, NullyTrue,  NullyTrue ));
        NoNullRet(true,  True      .Coalesce(NullyTrue,  Null,       Null      ));
        NoNullRet(true,  True      .Coalesce(NullyTrue,  Null,       False     ));
        NoNullRet(true,  True      .Coalesce(NullyTrue,  Null,       True      ));
        NoNullRet(true,  True      .Coalesce(NullyTrue,  Null,       NullyFalse));
        NoNullRet(true,  True      .Coalesce(NullyTrue,  Null,       NullyTrue ));
        NoNullRet(true,  True      .Coalesce(NullyTrue,  False,      Null      ));
        NoNullRet(true,  True      .Coalesce(NullyTrue,  False,      False     ));
        NoNullRet(true,  True      .Coalesce(NullyTrue,  False,      True      ));
        NoNullRet(true,  True      .Coalesce(NullyTrue,  False,      NullyFalse));
        NoNullRet(true,  True      .Coalesce(NullyTrue,  False,      NullyTrue ));
        NoNullRet(true,  True      .Coalesce(NullyTrue,  True,       Null      ));
        NoNullRet(true,  True      .Coalesce(NullyTrue,  True,       False     ));
        NoNullRet(true,  True      .Coalesce(NullyTrue,  True,       True      ));
        NoNullRet(true,  True      .Coalesce(NullyTrue,  True,       NullyFalse));
        NoNullRet(true,  True      .Coalesce(NullyTrue,  True,       NullyTrue ));
        NoNullRet(true,  True      .Coalesce(NullyTrue,  NullyFalse, Null      ));
        NoNullRet(true,  True      .Coalesce(NullyTrue,  NullyFalse, False     ));
        NoNullRet(true,  True      .Coalesce(NullyTrue,  NullyFalse, True      ));
        NoNullRet(true,  True      .Coalesce(NullyTrue,  NullyFalse, NullyFalse));
        NoNullRet(true,  True      .Coalesce(NullyTrue,  NullyFalse, NullyTrue ));
        NoNullRet(true,  True      .Coalesce(NullyTrue,  NullyTrue,  Null      ));
        NoNullRet(true,  True      .Coalesce(NullyTrue,  NullyTrue,  False     ));
        NoNullRet(true,  True      .Coalesce(NullyTrue,  NullyTrue,  True      ));
        NoNullRet(true,  True      .Coalesce(NullyTrue,  NullyTrue,  NullyFalse));
        NoNullRet(true,  True      .Coalesce(NullyTrue,  NullyTrue,  NullyTrue ));
    }

    [TestMethod]
    public void Coalesce_4Args_Bool_ExtensionsBatch4()
    {
        NoNullRet(false, NullyFalse.Coalesce(Null,       Null,       Null      ));
        NoNullRet(false, NullyFalse.Coalesce(Null,       Null,       False     ));
        NoNullRet(true,  NullyFalse.Coalesce(Null,       Null,       True      ));
        NoNullRet(false, NullyFalse.Coalesce(Null,       Null,       NullyFalse));
        NoNullRet(true,  NullyFalse.Coalesce(Null,       Null,       NullyTrue ));
        NoNullRet(false, NullyFalse.Coalesce(Null,       False,      Null      ));
        NoNullRet(false, NullyFalse.Coalesce(Null,       False,      False     ));
        NoNullRet(true,  NullyFalse.Coalesce(Null,       False,      True      ));
        NoNullRet(false, NullyFalse.Coalesce(Null,       False,      NullyFalse));
        NoNullRet(true,  NullyFalse.Coalesce(Null,       False,      NullyTrue ));
        NoNullRet(true,  NullyFalse.Coalesce(Null,       True,       Null      ));
        NoNullRet(true,  NullyFalse.Coalesce(Null,       True,       False     ));
        NoNullRet(true,  NullyFalse.Coalesce(Null,       True,       True      ));
        NoNullRet(true,  NullyFalse.Coalesce(Null,       True,       NullyFalse));
        NoNullRet(true,  NullyFalse.Coalesce(Null,       True,       NullyTrue ));
        NoNullRet(false, NullyFalse.Coalesce(Null,       NullyFalse, Null      ));
        NoNullRet(false, NullyFalse.Coalesce(Null,       NullyFalse, False     ));
        NoNullRet(true,  NullyFalse.Coalesce(Null,       NullyFalse, True      ));
        NoNullRet(false, NullyFalse.Coalesce(Null,       NullyFalse, NullyFalse));
        NoNullRet(true,  NullyFalse.Coalesce(Null,       NullyFalse, NullyTrue ));
        NoNullRet(true,  NullyFalse.Coalesce(Null,       NullyTrue,  Null      ));
        NoNullRet(true,  NullyFalse.Coalesce(Null,       NullyTrue,  False     ));
        NoNullRet(true,  NullyFalse.Coalesce(Null,       NullyTrue,  True      ));
        NoNullRet(true,  NullyFalse.Coalesce(Null,       NullyTrue,  NullyFalse));
        NoNullRet(true,  NullyFalse.Coalesce(Null,       NullyTrue,  NullyTrue ));
        NoNullRet(false, NullyFalse.Coalesce(False,      Null,       Null      ));
        NoNullRet(false, NullyFalse.Coalesce(False,      Null,       False     ));
        NoNullRet(true,  NullyFalse.Coalesce(False,      Null,       True      ));
        NoNullRet(false, NullyFalse.Coalesce(False,      Null,       NullyFalse));
        NoNullRet(true,  NullyFalse.Coalesce(False,      Null,       NullyTrue ));
        NoNullRet(false, NullyFalse.Coalesce(False,      False,      Null      ));
        NoNullRet(false, NullyFalse.Coalesce(False,      False,      False     ));
        NoNullRet(true,  NullyFalse.Coalesce(False,      False,      True      ));
        NoNullRet(false, NullyFalse.Coalesce(False,      False,      NullyFalse));
        NoNullRet(true,  NullyFalse.Coalesce(False,      False,      NullyTrue ));
        NoNullRet(true,  NullyFalse.Coalesce(False,      True,       Null      ));
        NoNullRet(true,  NullyFalse.Coalesce(False,      True,       False     ));
        NoNullRet(true,  NullyFalse.Coalesce(False,      True,       True      ));
        NoNullRet(true,  NullyFalse.Coalesce(False,      True,       NullyFalse));
        NoNullRet(true,  NullyFalse.Coalesce(False,      True,       NullyTrue ));
        NoNullRet(false, NullyFalse.Coalesce(False,      NullyFalse, Null      ));
        NoNullRet(false, NullyFalse.Coalesce(False,      NullyFalse, False     ));
        NoNullRet(true,  NullyFalse.Coalesce(False,      NullyFalse, True      ));
        NoNullRet(false, NullyFalse.Coalesce(False,      NullyFalse, NullyFalse));
        NoNullRet(true,  NullyFalse.Coalesce(False,      NullyFalse, NullyTrue ));
        NoNullRet(true,  NullyFalse.Coalesce(False,      NullyTrue,  Null      ));
        NoNullRet(true,  NullyFalse.Coalesce(False,      NullyTrue,  False     ));
        NoNullRet(true,  NullyFalse.Coalesce(False,      NullyTrue,  True      ));
        NoNullRet(true,  NullyFalse.Coalesce(False,      NullyTrue,  NullyFalse));
        NoNullRet(true,  NullyFalse.Coalesce(False,      NullyTrue,  NullyTrue ));
        NoNullRet(true,  NullyFalse.Coalesce(True,       Null,       Null      ));
        NoNullRet(true,  NullyFalse.Coalesce(True,       Null,       False     ));
        NoNullRet(true,  NullyFalse.Coalesce(True,       Null,       True      ));
        NoNullRet(true,  NullyFalse.Coalesce(True,       Null,       NullyFalse));
        NoNullRet(true,  NullyFalse.Coalesce(True,       Null,       NullyTrue ));
        NoNullRet(true,  NullyFalse.Coalesce(True,       False,      Null      ));
        NoNullRet(true,  NullyFalse.Coalesce(True,       False,      False     ));
        NoNullRet(true,  NullyFalse.Coalesce(True,       False,      True      ));
        NoNullRet(true,  NullyFalse.Coalesce(True,       False,      NullyFalse));
        NoNullRet(true,  NullyFalse.Coalesce(True,       False,      NullyTrue ));
        NoNullRet(true,  NullyFalse.Coalesce(True,       True,       Null      ));
        NoNullRet(true,  NullyFalse.Coalesce(True,       True,       False     ));
        NoNullRet(true,  NullyFalse.Coalesce(True,       True,       True      ));
        NoNullRet(true,  NullyFalse.Coalesce(True,       True,       NullyFalse));
        NoNullRet(true,  NullyFalse.Coalesce(True,       True,       NullyTrue ));
        NoNullRet(true,  NullyFalse.Coalesce(True,       NullyFalse, Null      ));
        NoNullRet(true,  NullyFalse.Coalesce(True,       NullyFalse, False     ));
        NoNullRet(true,  NullyFalse.Coalesce(True,       NullyFalse, True      ));
        NoNullRet(true,  NullyFalse.Coalesce(True,       NullyFalse, NullyFalse));
        NoNullRet(true,  NullyFalse.Coalesce(True,       NullyFalse, NullyTrue ));
        NoNullRet(true,  NullyFalse.Coalesce(True,       NullyTrue,  Null      ));
        NoNullRet(true,  NullyFalse.Coalesce(True,       NullyTrue,  False     ));
        NoNullRet(true,  NullyFalse.Coalesce(True,       NullyTrue,  True      ));
        NoNullRet(true,  NullyFalse.Coalesce(True,       NullyTrue,  NullyFalse));
        NoNullRet(true,  NullyFalse.Coalesce(True,       NullyTrue,  NullyTrue ));
        NoNullRet(false, NullyFalse.Coalesce(NullyFalse, Null,       Null      ));
        NoNullRet(false, NullyFalse.Coalesce(NullyFalse, Null,       False     ));
        NoNullRet(true,  NullyFalse.Coalesce(NullyFalse, Null,       True      ));
        NoNullRet(false, NullyFalse.Coalesce(NullyFalse, Null,       NullyFalse));
        NoNullRet(true,  NullyFalse.Coalesce(NullyFalse, Null,       NullyTrue ));
        NoNullRet(false, NullyFalse.Coalesce(NullyFalse, False,      Null      ));
        NoNullRet(false, NullyFalse.Coalesce(NullyFalse, False,      False     ));
        NoNullRet(true,  NullyFalse.Coalesce(NullyFalse, False,      True      ));
        NoNullRet(false, NullyFalse.Coalesce(NullyFalse, False,      NullyFalse));
        NoNullRet(true,  NullyFalse.Coalesce(NullyFalse, False,      NullyTrue ));
        NoNullRet(true,  NullyFalse.Coalesce(NullyFalse, True,       Null      ));
        NoNullRet(true,  NullyFalse.Coalesce(NullyFalse, True,       False     ));
        NoNullRet(true,  NullyFalse.Coalesce(NullyFalse, True,       True      ));
        NoNullRet(true,  NullyFalse.Coalesce(NullyFalse, True,       NullyFalse));
        NoNullRet(true,  NullyFalse.Coalesce(NullyFalse, True,       NullyTrue ));
        NoNullRet(false, NullyFalse.Coalesce(NullyFalse, NullyFalse, Null      ));
        NoNullRet(false, NullyFalse.Coalesce(NullyFalse, NullyFalse, False     ));
        NoNullRet(true,  NullyFalse.Coalesce(NullyFalse, NullyFalse, True      ));
        NoNullRet(false, NullyFalse.Coalesce(NullyFalse, NullyFalse, NullyFalse));
        NoNullRet(true,  NullyFalse.Coalesce(NullyFalse, NullyFalse, NullyTrue ));
        NoNullRet(true,  NullyFalse.Coalesce(NullyFalse, NullyTrue,  Null      ));
        NoNullRet(true,  NullyFalse.Coalesce(NullyFalse, NullyTrue,  False     ));
        NoNullRet(true,  NullyFalse.Coalesce(NullyFalse, NullyTrue,  True      ));
        NoNullRet(true,  NullyFalse.Coalesce(NullyFalse, NullyTrue,  NullyFalse));
        NoNullRet(true,  NullyFalse.Coalesce(NullyFalse, NullyTrue,  NullyTrue ));
        NoNullRet(true,  NullyFalse.Coalesce(NullyTrue,  Null,       Null      ));
        NoNullRet(true,  NullyFalse.Coalesce(NullyTrue,  Null,       False     ));
        NoNullRet(true,  NullyFalse.Coalesce(NullyTrue,  Null,       True      ));
        NoNullRet(true,  NullyFalse.Coalesce(NullyTrue,  Null,       NullyFalse));
        NoNullRet(true,  NullyFalse.Coalesce(NullyTrue,  Null,       NullyTrue ));
        NoNullRet(true,  NullyFalse.Coalesce(NullyTrue,  False,      Null      ));
        NoNullRet(true,  NullyFalse.Coalesce(NullyTrue,  False,      False     ));
        NoNullRet(true,  NullyFalse.Coalesce(NullyTrue,  False,      True      ));
        NoNullRet(true,  NullyFalse.Coalesce(NullyTrue,  False,      NullyFalse));
        NoNullRet(true,  NullyFalse.Coalesce(NullyTrue,  False,      NullyTrue ));
        NoNullRet(true,  NullyFalse.Coalesce(NullyTrue,  True,       Null      ));
        NoNullRet(true,  NullyFalse.Coalesce(NullyTrue,  True,       False     ));
        NoNullRet(true,  NullyFalse.Coalesce(NullyTrue,  True,       True      ));
        NoNullRet(true,  NullyFalse.Coalesce(NullyTrue,  True,       NullyFalse));
        NoNullRet(true,  NullyFalse.Coalesce(NullyTrue,  True,       NullyTrue ));
        NoNullRet(true,  NullyFalse.Coalesce(NullyTrue,  NullyFalse, Null      ));
        NoNullRet(true,  NullyFalse.Coalesce(NullyTrue,  NullyFalse, False     ));
        NoNullRet(true,  NullyFalse.Coalesce(NullyTrue,  NullyFalse, True      ));
        NoNullRet(true,  NullyFalse.Coalesce(NullyTrue,  NullyFalse, NullyFalse));
        NoNullRet(true,  NullyFalse.Coalesce(NullyTrue,  NullyFalse, NullyTrue ));
        NoNullRet(true,  NullyFalse.Coalesce(NullyTrue,  NullyTrue,  Null      ));
        NoNullRet(true,  NullyFalse.Coalesce(NullyTrue,  NullyTrue,  False     ));
        NoNullRet(true,  NullyFalse.Coalesce(NullyTrue,  NullyTrue,  True      ));
        NoNullRet(true,  NullyFalse.Coalesce(NullyTrue,  NullyTrue,  NullyFalse));
        NoNullRet(true,  NullyFalse.Coalesce(NullyTrue,  NullyTrue,  NullyTrue ));
    }

    [TestMethod]
    public void Coalesce_4Args_Bool_ExtensionsBatch5()
    {
        NoNullRet(true,  NullyTrue .Coalesce(Null,       Null,       Null      ));
        NoNullRet(true,  NullyTrue .Coalesce(Null,       Null,       False     ));
        NoNullRet(true,  NullyTrue .Coalesce(Null,       Null,       True      ));
        NoNullRet(true,  NullyTrue .Coalesce(Null,       Null,       NullyFalse));
        NoNullRet(true,  NullyTrue .Coalesce(Null,       Null,       NullyTrue ));
        NoNullRet(true,  NullyTrue .Coalesce(Null,       False,      Null      ));
        NoNullRet(true,  NullyTrue .Coalesce(Null,       False,      False     ));
        NoNullRet(true,  NullyTrue .Coalesce(Null,       False,      True      ));
        NoNullRet(true,  NullyTrue .Coalesce(Null,       False,      NullyFalse));
        NoNullRet(true,  NullyTrue .Coalesce(Null,       False,      NullyTrue ));
        NoNullRet(true,  NullyTrue .Coalesce(Null,       True,       Null      ));
        NoNullRet(true,  NullyTrue .Coalesce(Null,       True,       False     ));
        NoNullRet(true,  NullyTrue .Coalesce(Null,       True,       True      ));
        NoNullRet(true,  NullyTrue .Coalesce(Null,       True,       NullyFalse));
        NoNullRet(true,  NullyTrue .Coalesce(Null,       True,       NullyTrue ));
        NoNullRet(true,  NullyTrue .Coalesce(Null,       NullyFalse, Null      ));
        NoNullRet(true,  NullyTrue .Coalesce(Null,       NullyFalse, False     ));
        NoNullRet(true,  NullyTrue .Coalesce(Null,       NullyFalse, True      ));
        NoNullRet(true,  NullyTrue .Coalesce(Null,       NullyFalse, NullyFalse));
        NoNullRet(true,  NullyTrue .Coalesce(Null,       NullyFalse, NullyTrue ));
        NoNullRet(true,  NullyTrue .Coalesce(Null,       NullyTrue,  Null      ));
        NoNullRet(true,  NullyTrue .Coalesce(Null,       NullyTrue,  False     ));
        NoNullRet(true,  NullyTrue .Coalesce(Null,       NullyTrue,  True      ));
        NoNullRet(true,  NullyTrue .Coalesce(Null,       NullyTrue,  NullyFalse));
        NoNullRet(true,  NullyTrue .Coalesce(Null,       NullyTrue,  NullyTrue ));
        NoNullRet(true,  NullyTrue .Coalesce(False,      Null,       Null      ));
        NoNullRet(true,  NullyTrue .Coalesce(False,      Null,       False     ));
        NoNullRet(true,  NullyTrue .Coalesce(False,      Null,       True      ));
        NoNullRet(true,  NullyTrue .Coalesce(False,      Null,       NullyFalse));
        NoNullRet(true,  NullyTrue .Coalesce(False,      Null,       NullyTrue ));
        NoNullRet(true,  NullyTrue .Coalesce(False,      False,      Null      ));
        NoNullRet(true,  NullyTrue .Coalesce(False,      False,      False     ));
        NoNullRet(true,  NullyTrue .Coalesce(False,      False,      True      ));
        NoNullRet(true,  NullyTrue .Coalesce(False,      False,      NullyFalse));
        NoNullRet(true,  NullyTrue .Coalesce(False,      False,      NullyTrue ));
        NoNullRet(true,  NullyTrue .Coalesce(False,      True,       Null      ));
        NoNullRet(true,  NullyTrue .Coalesce(False,      True,       False     ));
        NoNullRet(true,  NullyTrue .Coalesce(False,      True,       True      ));
        NoNullRet(true,  NullyTrue .Coalesce(False,      True,       NullyFalse));
        NoNullRet(true,  NullyTrue .Coalesce(False,      True,       NullyTrue ));
        NoNullRet(true,  NullyTrue .Coalesce(False,      NullyFalse, Null      ));
        NoNullRet(true,  NullyTrue .Coalesce(False,      NullyFalse, False     ));
        NoNullRet(true,  NullyTrue .Coalesce(False,      NullyFalse, True      ));
        NoNullRet(true,  NullyTrue .Coalesce(False,      NullyFalse, NullyFalse));
        NoNullRet(true,  NullyTrue .Coalesce(False,      NullyFalse, NullyTrue ));
        NoNullRet(true,  NullyTrue .Coalesce(False,      NullyTrue,  Null      ));
        NoNullRet(true,  NullyTrue .Coalesce(False,      NullyTrue,  False     ));
        NoNullRet(true,  NullyTrue .Coalesce(False,      NullyTrue,  True      ));
        NoNullRet(true,  NullyTrue .Coalesce(False,      NullyTrue,  NullyFalse));
        NoNullRet(true,  NullyTrue .Coalesce(False,      NullyTrue,  NullyTrue ));
        NoNullRet(true,  NullyTrue .Coalesce(True,       Null,       Null      ));
        NoNullRet(true,  NullyTrue .Coalesce(True,       Null,       False     ));
        NoNullRet(true,  NullyTrue .Coalesce(True,       Null,       True      ));
        NoNullRet(true,  NullyTrue .Coalesce(True,       Null,       NullyFalse));
        NoNullRet(true,  NullyTrue .Coalesce(True,       Null,       NullyTrue ));
        NoNullRet(true,  NullyTrue .Coalesce(True,       False,      Null      ));
        NoNullRet(true,  NullyTrue .Coalesce(True,       False,      False     ));
        NoNullRet(true,  NullyTrue .Coalesce(True,       False,      True      ));
        NoNullRet(true,  NullyTrue .Coalesce(True,       False,      NullyFalse));
        NoNullRet(true,  NullyTrue .Coalesce(True,       False,      NullyTrue ));
        NoNullRet(true,  NullyTrue .Coalesce(True,       True,       Null      ));
        NoNullRet(true,  NullyTrue .Coalesce(True,       True,       False     ));
        NoNullRet(true,  NullyTrue .Coalesce(True,       True,       True      ));
        NoNullRet(true,  NullyTrue .Coalesce(True,       True,       NullyFalse));
        NoNullRet(true,  NullyTrue .Coalesce(True,       True,       NullyTrue ));
        NoNullRet(true,  NullyTrue .Coalesce(True,       NullyFalse, Null      ));
        NoNullRet(true,  NullyTrue .Coalesce(True,       NullyFalse, False     ));
        NoNullRet(true,  NullyTrue .Coalesce(True,       NullyFalse, True      ));
        NoNullRet(true,  NullyTrue .Coalesce(True,       NullyFalse, NullyFalse));
        NoNullRet(true,  NullyTrue .Coalesce(True,       NullyFalse, NullyTrue ));
        NoNullRet(true,  NullyTrue .Coalesce(True,       NullyTrue,  Null      ));
        NoNullRet(true,  NullyTrue .Coalesce(True,       NullyTrue,  False     ));
        NoNullRet(true,  NullyTrue .Coalesce(True,       NullyTrue,  True      ));
        NoNullRet(true,  NullyTrue .Coalesce(True,       NullyTrue,  NullyFalse));
        NoNullRet(true,  NullyTrue .Coalesce(True,       NullyTrue,  NullyTrue ));
        NoNullRet(true,  NullyTrue .Coalesce(NullyFalse, Null,       Null      ));
        NoNullRet(true,  NullyTrue .Coalesce(NullyFalse, Null,       False     ));
        NoNullRet(true,  NullyTrue .Coalesce(NullyFalse, Null,       True      ));
        NoNullRet(true,  NullyTrue .Coalesce(NullyFalse, Null,       NullyFalse));
        NoNullRet(true,  NullyTrue .Coalesce(NullyFalse, Null,       NullyTrue ));
        NoNullRet(true,  NullyTrue .Coalesce(NullyFalse, False,      Null      ));
        NoNullRet(true,  NullyTrue .Coalesce(NullyFalse, False,      False     ));
        NoNullRet(true,  NullyTrue .Coalesce(NullyFalse, False,      True      ));
        NoNullRet(true,  NullyTrue .Coalesce(NullyFalse, False,      NullyFalse));
        NoNullRet(true,  NullyTrue .Coalesce(NullyFalse, False,      NullyTrue ));
        NoNullRet(true,  NullyTrue .Coalesce(NullyFalse, True,       Null      ));
        NoNullRet(true,  NullyTrue .Coalesce(NullyFalse, True,       False     ));
        NoNullRet(true,  NullyTrue .Coalesce(NullyFalse, True,       True      ));
        NoNullRet(true,  NullyTrue .Coalesce(NullyFalse, True,       NullyFalse));
        NoNullRet(true,  NullyTrue .Coalesce(NullyFalse, True,       NullyTrue ));
        NoNullRet(true,  NullyTrue .Coalesce(NullyFalse, NullyFalse, Null      ));
        NoNullRet(true,  NullyTrue .Coalesce(NullyFalse, NullyFalse, False     ));
        NoNullRet(true,  NullyTrue .Coalesce(NullyFalse, NullyFalse, True      ));
        NoNullRet(true,  NullyTrue .Coalesce(NullyFalse, NullyFalse, NullyFalse));
        NoNullRet(true,  NullyTrue .Coalesce(NullyFalse, NullyFalse, NullyTrue ));
        NoNullRet(true,  NullyTrue .Coalesce(NullyFalse, NullyTrue,  Null      ));
        NoNullRet(true,  NullyTrue .Coalesce(NullyFalse, NullyTrue,  False     ));
        NoNullRet(true,  NullyTrue .Coalesce(NullyFalse, NullyTrue,  True      ));
        NoNullRet(true,  NullyTrue .Coalesce(NullyFalse, NullyTrue,  NullyFalse));
        NoNullRet(true,  NullyTrue .Coalesce(NullyFalse, NullyTrue,  NullyTrue ));
        NoNullRet(true,  NullyTrue .Coalesce(NullyTrue,  Null,       Null      ));
        NoNullRet(true,  NullyTrue .Coalesce(NullyTrue,  Null,       False     ));
        NoNullRet(true,  NullyTrue .Coalesce(NullyTrue,  Null,       True      ));
        NoNullRet(true,  NullyTrue .Coalesce(NullyTrue,  Null,       NullyFalse));
        NoNullRet(true,  NullyTrue .Coalesce(NullyTrue,  Null,       NullyTrue ));
        NoNullRet(true,  NullyTrue .Coalesce(NullyTrue,  False,      Null      ));
        NoNullRet(true,  NullyTrue .Coalesce(NullyTrue,  False,      False     ));
        NoNullRet(true,  NullyTrue .Coalesce(NullyTrue,  False,      True      ));
        NoNullRet(true,  NullyTrue .Coalesce(NullyTrue,  False,      NullyFalse));
        NoNullRet(true,  NullyTrue .Coalesce(NullyTrue,  False,      NullyTrue ));
        NoNullRet(true,  NullyTrue .Coalesce(NullyTrue,  True,       Null      ));
        NoNullRet(true,  NullyTrue .Coalesce(NullyTrue,  True,       False     ));
        NoNullRet(true,  NullyTrue .Coalesce(NullyTrue,  True,       True      ));
        NoNullRet(true,  NullyTrue .Coalesce(NullyTrue,  True,       NullyFalse));
        NoNullRet(true,  NullyTrue .Coalesce(NullyTrue,  True,       NullyTrue ));
        NoNullRet(true,  NullyTrue .Coalesce(NullyTrue,  NullyFalse, Null      ));
        NoNullRet(true,  NullyTrue .Coalesce(NullyTrue,  NullyFalse, False     ));
        NoNullRet(true,  NullyTrue .Coalesce(NullyTrue,  NullyFalse, True      ));
        NoNullRet(true,  NullyTrue .Coalesce(NullyTrue,  NullyFalse, NullyFalse));
        NoNullRet(true,  NullyTrue .Coalesce(NullyTrue,  NullyFalse, NullyTrue ));
        NoNullRet(true,  NullyTrue .Coalesce(NullyTrue,  NullyTrue,  Null      ));
        NoNullRet(true,  NullyTrue .Coalesce(NullyTrue,  NullyTrue,  False     ));
        NoNullRet(true,  NullyTrue .Coalesce(NullyTrue,  NullyTrue,  True      ));
        NoNullRet(true,  NullyTrue .Coalesce(NullyTrue,  NullyTrue,  NullyFalse));
        NoNullRet(true,  NullyTrue .Coalesce(NullyTrue,  NullyTrue,  NullyTrue ));
    }
}
