namespace JJ.Framework.Existence.Core.Tests;

[TestClass]
public class Coalesce_4Args_BoolToText_Static : TestBase
{
    [TestMethod]
    public void Coalesce_4Args_BoolToText_Static_Batch1()
    {
        NoNullRet("",      Coalesce(NullBool,   NullBool,   NullBool,   NullText       ));
        NoNullRet("",      Coalesce(NullBool,   NullBool,   NullBool,   Empty          ));
        NoNullRet(Text,    Coalesce(NullBool,   NullBool,   NullBool,   Text           ));
        NoNullRet(" ",     Coalesce(NullBool,   NullBool,   NullBool,   NullySpace     ));
        NoNullRet(Text,    Coalesce(NullBool,   NullBool,   NullBool,   NullyFilledText));
        NoNullRet("",      Coalesce(NullBool,   NullBool,   NullyFalse, NullText       ));
        NoNullRet("",      Coalesce(NullBool,   NullBool,   NullyFalse, Empty          ));
        NoNullRet(Text,    Coalesce(NullBool,   NullBool,   NullyFalse, Text           ));
        NoNullRet(" ",     Coalesce(NullBool,   NullBool,   NullyFalse, NullySpace     ));
        NoNullRet(Text,    Coalesce(NullBool,   NullBool,   NullyFalse, NullyFilledText));
        NoNullRet("True",  Coalesce(NullBool,   NullBool,   NullyTrue,  NullText       ));
        NoNullRet("True",  Coalesce(NullBool,   NullBool,   NullyTrue,  Empty          ));
        NoNullRet("True",  Coalesce(NullBool,   NullBool,   NullyTrue,  Text           ));
        NoNullRet("True",  Coalesce(NullBool,   NullBool,   NullyTrue,  NullySpace     ));
        NoNullRet("True",  Coalesce(NullBool,   NullBool,   NullyTrue,  NullyFilledText));
        NoNullRet("",      Coalesce(NullBool,   NullBool,   False,      NullText       ));
        NoNullRet("",      Coalesce(NullBool,   NullBool,   False,      Empty          ));
        NoNullRet(Text,    Coalesce(NullBool,   NullBool,   False,      Text           ));
        NoNullRet(" ",     Coalesce(NullBool,   NullBool,   False,      NullySpace     ));
        NoNullRet(Text,    Coalesce(NullBool,   NullBool,   False,      NullyFilledText));
        NoNullRet("True",  Coalesce(NullBool,   NullBool,   True,       NullText       ));
        NoNullRet("True",  Coalesce(NullBool,   NullBool,   True,       Empty          ));
        NoNullRet("True",  Coalesce(NullBool,   NullBool,   True,       Text           ));
        NoNullRet("True",  Coalesce(NullBool,   NullBool,   True,       NullySpace     ));
        NoNullRet("True",  Coalesce(NullBool,   NullBool,   True,       NullyFilledText));
        NoNullRet("",      Coalesce(NullBool,   NullyFalse, NullBool,   NullText       ));
        NoNullRet("",      Coalesce(NullBool,   NullyFalse, NullBool,   Empty          ));
        NoNullRet(Text,    Coalesce(NullBool,   NullyFalse, NullBool,   Text           ));
        NoNullRet(" ",     Coalesce(NullBool,   NullyFalse, NullBool,   NullySpace     ));
        NoNullRet(Text,    Coalesce(NullBool,   NullyFalse, NullBool,   NullyFilledText));
        NoNullRet("",      Coalesce(NullBool,   NullyFalse, NullyFalse, NullText       ));
        NoNullRet("",      Coalesce(NullBool,   NullyFalse, NullyFalse, Empty          ));
        NoNullRet(Text,    Coalesce(NullBool,   NullyFalse, NullyFalse, Text           ));
        NoNullRet(" ",     Coalesce(NullBool,   NullyFalse, NullyFalse, NullySpace     ));
        NoNullRet(Text,    Coalesce(NullBool,   NullyFalse, NullyFalse, NullyFilledText));
        NoNullRet("True",  Coalesce(NullBool,   NullyFalse, NullyTrue,  NullText       ));
        NoNullRet("True",  Coalesce(NullBool,   NullyFalse, NullyTrue,  Empty          ));
        NoNullRet("True",  Coalesce(NullBool,   NullyFalse, NullyTrue,  Text           ));
        NoNullRet("True",  Coalesce(NullBool,   NullyFalse, NullyTrue,  NullySpace     ));
        NoNullRet("True",  Coalesce(NullBool,   NullyFalse, NullyTrue,  NullyFilledText));
        NoNullRet("",      Coalesce(NullBool,   NullyFalse, False,      NullText       ));
        NoNullRet("",      Coalesce(NullBool,   NullyFalse, False,      Empty          ));
        NoNullRet(Text,    Coalesce(NullBool,   NullyFalse, False,      Text           ));
        NoNullRet(" ",     Coalesce(NullBool,   NullyFalse, False,      NullySpace     ));
        NoNullRet(Text,    Coalesce(NullBool,   NullyFalse, False,      NullyFilledText));
        NoNullRet("True",  Coalesce(NullBool,   NullyFalse, True,       NullText       ));
        NoNullRet("True",  Coalesce(NullBool,   NullyFalse, True,       Empty          ));
        NoNullRet("True",  Coalesce(NullBool,   NullyFalse, True,       Text           ));
        NoNullRet("True",  Coalesce(NullBool,   NullyFalse, True,       NullySpace     ));
        NoNullRet("True",  Coalesce(NullBool,   NullyFalse, True,       NullyFilledText));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  NullBool,   NullText       ));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  NullBool,   Empty          ));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  NullBool,   Text           ));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  NullBool,   NullySpace     ));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  NullBool,   NullyFilledText));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  NullyFalse, NullText       ));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  NullyFalse, Empty          ));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  NullyFalse, Text           ));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  NullyFalse, NullySpace     ));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  NullyFalse, NullyFilledText));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  NullyTrue,  NullText       ));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  NullyTrue,  Empty          ));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  NullyTrue,  Text           ));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  NullyTrue,  NullySpace     ));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  NullyTrue,  NullyFilledText));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  False,      NullText       ));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  False,      Empty          ));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  False,      Text           ));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  False,      NullySpace     ));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  False,      NullyFilledText));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  True,       NullText       ));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  True,       Empty          ));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  True,       Text           ));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  True,       NullySpace     ));
        NoNullRet("True",  Coalesce(NullBool,   NullyTrue,  True,       NullyFilledText));
        NoNullRet("",      Coalesce(NullBool,   False,      NullBool,   NullText       ));
        NoNullRet("",      Coalesce(NullBool,   False,      NullBool,   Empty          ));
        NoNullRet(Text,    Coalesce(NullBool,   False,      NullBool,   Text           ));
        NoNullRet(" ",     Coalesce(NullBool,   False,      NullBool,   NullySpace     ));
        NoNullRet(Text,    Coalesce(NullBool,   False,      NullBool,   NullyFilledText));
        NoNullRet("",      Coalesce(NullBool,   False,      NullyFalse, NullText       ));
        NoNullRet("",      Coalesce(NullBool,   False,      NullyFalse, Empty          ));
        NoNullRet(Text,    Coalesce(NullBool,   False,      NullyFalse, Text           ));
        NoNullRet(" ",     Coalesce(NullBool,   False,      NullyFalse, NullySpace     ));
        NoNullRet(Text,    Coalesce(NullBool,   False,      NullyFalse, NullyFilledText));
        NoNullRet("True",  Coalesce(NullBool,   False,      NullyTrue,  NullText       ));
        NoNullRet("True",  Coalesce(NullBool,   False,      NullyTrue,  Empty          ));
        NoNullRet("True",  Coalesce(NullBool,   False,      NullyTrue,  Text           ));
        NoNullRet("True",  Coalesce(NullBool,   False,      NullyTrue,  NullySpace     ));
        NoNullRet("True",  Coalesce(NullBool,   False,      NullyTrue,  NullyFilledText));
        NoNullRet("",      Coalesce(NullBool,   False,      False,      NullText       ));
        NoNullRet("",      Coalesce(NullBool,   False,      False,      Empty          ));
        NoNullRet(Text,    Coalesce(NullBool,   False,      False,      Text           ));
        NoNullRet(" ",     Coalesce(NullBool,   False,      False,      NullySpace     ));
        NoNullRet(Text,    Coalesce(NullBool,   False,      False,      NullyFilledText));
        NoNullRet("True",  Coalesce(NullBool,   False,      True,       NullText       ));
        NoNullRet("True",  Coalesce(NullBool,   False,      True,       Empty          ));
        NoNullRet("True",  Coalesce(NullBool,   False,      True,       Text           ));
        NoNullRet("True",  Coalesce(NullBool,   False,      True,       NullySpace     ));
        NoNullRet("True",  Coalesce(NullBool,   False,      True,       NullyFilledText));
        NoNullRet("True",  Coalesce(NullBool,   True,       NullBool,   NullText       ));
        NoNullRet("True",  Coalesce(NullBool,   True,       NullBool,   Empty          ));
        NoNullRet("True",  Coalesce(NullBool,   True,       NullBool,   Text           ));
        NoNullRet("True",  Coalesce(NullBool,   True,       NullBool,   NullySpace     ));
        NoNullRet("True",  Coalesce(NullBool,   True,       NullBool,   NullyFilledText));
        NoNullRet("True",  Coalesce(NullBool,   True,       NullyFalse, NullText       ));
        NoNullRet("True",  Coalesce(NullBool,   True,       NullyFalse, Empty          ));
        NoNullRet("True",  Coalesce(NullBool,   True,       NullyFalse, Text           ));
        NoNullRet("True",  Coalesce(NullBool,   True,       NullyFalse, NullySpace     ));
        NoNullRet("True",  Coalesce(NullBool,   True,       NullyFalse, NullyFilledText));
        NoNullRet("True",  Coalesce(NullBool,   True,       NullyTrue,  NullText       ));
        NoNullRet("True",  Coalesce(NullBool,   True,       NullyTrue,  Empty          ));
        NoNullRet("True",  Coalesce(NullBool,   True,       NullyTrue,  Text           ));
        NoNullRet("True",  Coalesce(NullBool,   True,       NullyTrue,  NullySpace     ));
        NoNullRet("True",  Coalesce(NullBool,   True,       NullyTrue,  NullyFilledText));
        NoNullRet("True",  Coalesce(NullBool,   True,       False,      NullText       ));
        NoNullRet("True",  Coalesce(NullBool,   True,       False,      Empty          ));
        NoNullRet("True",  Coalesce(NullBool,   True,       False,      Text           ));
        NoNullRet("True",  Coalesce(NullBool,   True,       False,      NullySpace     ));
        NoNullRet("True",  Coalesce(NullBool,   True,       False,      NullyFilledText));
        NoNullRet("True",  Coalesce(NullBool,   True,       True,       NullText       ));
        NoNullRet("True",  Coalesce(NullBool,   True,       True,       Empty          ));
        NoNullRet("True",  Coalesce(NullBool,   True,       True,       Text           ));
        NoNullRet("True",  Coalesce(NullBool,   True,       True,       NullySpace     ));
        NoNullRet("True",  Coalesce(NullBool,   True,       True,       NullyFilledText));
    }

    [TestMethod]
    public void Coalesce_4Args_BoolToText_Static_Batch2()
    {
        NoNullRet("",      Coalesce(NullyFalse, NullBool,   NullBool,   NullText       ));
        NoNullRet("",      Coalesce(NullyFalse, NullBool,   NullBool,   Empty          ));
        NoNullRet(Text,    Coalesce(NullyFalse, NullBool,   NullBool,   Text           ));
        NoNullRet(" ",     Coalesce(NullyFalse, NullBool,   NullBool,   NullySpace     ));
        NoNullRet(Text,    Coalesce(NullyFalse, NullBool,   NullBool,   NullyFilledText));
        NoNullRet("",      Coalesce(NullyFalse, NullBool,   NullyFalse, NullText       ));
        NoNullRet("",      Coalesce(NullyFalse, NullBool,   NullyFalse, Empty          ));
        NoNullRet(Text,    Coalesce(NullyFalse, NullBool,   NullyFalse, Text           ));
        NoNullRet(" ",     Coalesce(NullyFalse, NullBool,   NullyFalse, NullySpace     ));
        NoNullRet(Text,    Coalesce(NullyFalse, NullBool,   NullyFalse, NullyFilledText));
        NoNullRet("True",  Coalesce(NullyFalse, NullBool,   NullyTrue,  NullText       ));
        NoNullRet("True",  Coalesce(NullyFalse, NullBool,   NullyTrue,  Empty          ));
        NoNullRet("True",  Coalesce(NullyFalse, NullBool,   NullyTrue,  Text           ));
        NoNullRet("True",  Coalesce(NullyFalse, NullBool,   NullyTrue,  NullySpace     ));
        NoNullRet("True",  Coalesce(NullyFalse, NullBool,   NullyTrue,  NullyFilledText));
        NoNullRet("",      Coalesce(NullyFalse, NullBool,   False,      NullText       ));
        NoNullRet("",      Coalesce(NullyFalse, NullBool,   False,      Empty          ));
        NoNullRet(Text,    Coalesce(NullyFalse, NullBool,   False,      Text           ));
        NoNullRet(" ",     Coalesce(NullyFalse, NullBool,   False,      NullySpace     ));
        NoNullRet(Text,    Coalesce(NullyFalse, NullBool,   False,      NullyFilledText));
        NoNullRet("True",  Coalesce(NullyFalse, NullBool,   True,       NullText       ));
        NoNullRet("True",  Coalesce(NullyFalse, NullBool,   True,       Empty          ));
        NoNullRet("True",  Coalesce(NullyFalse, NullBool,   True,       Text           ));
        NoNullRet("True",  Coalesce(NullyFalse, NullBool,   True,       NullySpace     ));
        NoNullRet("True",  Coalesce(NullyFalse, NullBool,   True,       NullyFilledText));
        NoNullRet("",      Coalesce(NullyFalse, NullyFalse, NullBool,   NullText       ));
        NoNullRet("",      Coalesce(NullyFalse, NullyFalse, NullBool,   Empty          ));
        NoNullRet(Text,    Coalesce(NullyFalse, NullyFalse, NullBool,   Text           ));
        NoNullRet(" ",     Coalesce(NullyFalse, NullyFalse, NullBool,   NullySpace     ));
        NoNullRet(Text,    Coalesce(NullyFalse, NullyFalse, NullBool,   NullyFilledText));
        NoNullRet("",      Coalesce(NullyFalse, NullyFalse, NullyFalse, NullText       ));
        NoNullRet("",      Coalesce(NullyFalse, NullyFalse, NullyFalse, Empty          ));
        NoNullRet(Text,    Coalesce(NullyFalse, NullyFalse, NullyFalse, Text           ));
        NoNullRet(" ",     Coalesce(NullyFalse, NullyFalse, NullyFalse, NullySpace     ));
        NoNullRet(Text,    Coalesce(NullyFalse, NullyFalse, NullyFalse, NullyFilledText));
        NoNullRet("True",  Coalesce(NullyFalse, NullyFalse, NullyTrue,  NullText       ));
        NoNullRet("True",  Coalesce(NullyFalse, NullyFalse, NullyTrue,  Empty          ));
        NoNullRet("True",  Coalesce(NullyFalse, NullyFalse, NullyTrue,  Text           ));
        NoNullRet("True",  Coalesce(NullyFalse, NullyFalse, NullyTrue,  NullySpace     ));
        NoNullRet("True",  Coalesce(NullyFalse, NullyFalse, NullyTrue,  NullyFilledText));
        NoNullRet("",      Coalesce(NullyFalse, NullyFalse, False,      NullText       ));
        NoNullRet("",      Coalesce(NullyFalse, NullyFalse, False,      Empty          ));
        NoNullRet(Text,    Coalesce(NullyFalse, NullyFalse, False,      Text           ));
        NoNullRet(" ",     Coalesce(NullyFalse, NullyFalse, False,      NullySpace     ));
        NoNullRet(Text,    Coalesce(NullyFalse, NullyFalse, False,      NullyFilledText));
        NoNullRet("True",  Coalesce(NullyFalse, NullyFalse, True,       NullText       ));
        NoNullRet("True",  Coalesce(NullyFalse, NullyFalse, True,       Empty          ));
        NoNullRet("True",  Coalesce(NullyFalse, NullyFalse, True,       Text           ));
        NoNullRet("True",  Coalesce(NullyFalse, NullyFalse, True,       NullySpace     ));
        NoNullRet("True",  Coalesce(NullyFalse, NullyFalse, True,       NullyFilledText));
        NoNullRet("True",  Coalesce(NullyFalse, NullyTrue,  NullBool,   NullText       ));
        NoNullRet("True",  Coalesce(NullyFalse, NullyTrue,  NullBool,   Empty          ));
        NoNullRet("True",  Coalesce(NullyFalse, NullyTrue,  NullBool,   Text           ));
        NoNullRet("True",  Coalesce(NullyFalse, NullyTrue,  NullBool,   NullySpace     ));
        NoNullRet("True",  Coalesce(NullyFalse, NullyTrue,  NullBool,   NullyFilledText));
        NoNullRet("True",  Coalesce(NullyFalse, NullyTrue,  NullyFalse, NullText       ));
        NoNullRet("True",  Coalesce(NullyFalse, NullyTrue,  NullyFalse, Empty          ));
        NoNullRet("True",  Coalesce(NullyFalse, NullyTrue,  NullyFalse, Text           ));
        NoNullRet("True",  Coalesce(NullyFalse, NullyTrue,  NullyFalse, NullySpace     ));
        NoNullRet("True",  Coalesce(NullyFalse, NullyTrue,  NullyFalse, NullyFilledText));
        NoNullRet("True",  Coalesce(NullyFalse, NullyTrue,  NullyTrue,  NullText       ));
        NoNullRet("True",  Coalesce(NullyFalse, NullyTrue,  NullyTrue,  Empty          ));
        NoNullRet("True",  Coalesce(NullyFalse, NullyTrue,  NullyTrue,  Text           ));
        NoNullRet("True",  Coalesce(NullyFalse, NullyTrue,  NullyTrue,  NullySpace     ));
        NoNullRet("True",  Coalesce(NullyFalse, NullyTrue,  NullyTrue,  NullyFilledText));
        NoNullRet("True",  Coalesce(NullyFalse, NullyTrue,  False,      NullText       ));
        NoNullRet("True",  Coalesce(NullyFalse, NullyTrue,  False,      Empty          ));
        NoNullRet("True",  Coalesce(NullyFalse, NullyTrue,  False,      Text           ));
        NoNullRet("True",  Coalesce(NullyFalse, NullyTrue,  False,      NullySpace     ));
        NoNullRet("True",  Coalesce(NullyFalse, NullyTrue,  False,      NullyFilledText));
        NoNullRet("True",  Coalesce(NullyFalse, NullyTrue,  True,       NullText       ));
        NoNullRet("True",  Coalesce(NullyFalse, NullyTrue,  True,       Empty          ));
        NoNullRet("True",  Coalesce(NullyFalse, NullyTrue,  True,       Text           ));
        NoNullRet("True",  Coalesce(NullyFalse, NullyTrue,  True,       NullySpace     ));
        NoNullRet("True",  Coalesce(NullyFalse, NullyTrue,  True,       NullyFilledText));
        NoNullRet("",      Coalesce(NullyFalse, False,      NullBool,   NullText       ));
        NoNullRet("",      Coalesce(NullyFalse, False,      NullBool,   Empty          ));
        NoNullRet(Text,    Coalesce(NullyFalse, False,      NullBool,   Text           ));
        NoNullRet(" ",     Coalesce(NullyFalse, False,      NullBool,   NullySpace     ));
        NoNullRet(Text,    Coalesce(NullyFalse, False,      NullBool,   NullyFilledText));
        NoNullRet("",      Coalesce(NullyFalse, False,      NullyFalse, NullText       ));
        NoNullRet("",      Coalesce(NullyFalse, False,      NullyFalse, Empty          ));
        NoNullRet(Text,    Coalesce(NullyFalse, False,      NullyFalse, Text           ));
        NoNullRet(" ",     Coalesce(NullyFalse, False,      NullyFalse, NullySpace     ));
        NoNullRet(Text,    Coalesce(NullyFalse, False,      NullyFalse, NullyFilledText));
        NoNullRet("True",  Coalesce(NullyFalse, False,      NullyTrue,  NullText       ));
        NoNullRet("True",  Coalesce(NullyFalse, False,      NullyTrue,  Empty          ));
        NoNullRet("True",  Coalesce(NullyFalse, False,      NullyTrue,  Text           ));
        NoNullRet("True",  Coalesce(NullyFalse, False,      NullyTrue,  NullySpace     ));
        NoNullRet("True",  Coalesce(NullyFalse, False,      NullyTrue,  NullyFilledText));
        NoNullRet("",      Coalesce(NullyFalse, False,      False,      NullText       ));
        NoNullRet("",      Coalesce(NullyFalse, False,      False,      Empty          ));
        NoNullRet(Text,    Coalesce(NullyFalse, False,      False,      Text           ));
        NoNullRet(" ",     Coalesce(NullyFalse, False,      False,      NullySpace     ));
        NoNullRet(Text,    Coalesce(NullyFalse, False,      False,      NullyFilledText));
        NoNullRet("True",  Coalesce(NullyFalse, False,      True,       NullText       ));
        NoNullRet("True",  Coalesce(NullyFalse, False,      True,       Empty          ));
        NoNullRet("True",  Coalesce(NullyFalse, False,      True,       Text           ));
        NoNullRet("True",  Coalesce(NullyFalse, False,      True,       NullySpace     ));
        NoNullRet("True",  Coalesce(NullyFalse, False,      True,       NullyFilledText));
        NoNullRet("True",  Coalesce(NullyFalse, True,       NullBool,   NullText       ));
        NoNullRet("True",  Coalesce(NullyFalse, True,       NullBool,   Empty          ));
        NoNullRet("True",  Coalesce(NullyFalse, True,       NullBool,   Text           ));
        NoNullRet("True",  Coalesce(NullyFalse, True,       NullBool,   NullySpace     ));
        NoNullRet("True",  Coalesce(NullyFalse, True,       NullBool,   NullyFilledText));
        NoNullRet("True",  Coalesce(NullyFalse, True,       NullyFalse, NullText       ));
        NoNullRet("True",  Coalesce(NullyFalse, True,       NullyFalse, Empty          ));
        NoNullRet("True",  Coalesce(NullyFalse, True,       NullyFalse, Text           ));
        NoNullRet("True",  Coalesce(NullyFalse, True,       NullyFalse, NullySpace     ));
        NoNullRet("True",  Coalesce(NullyFalse, True,       NullyFalse, NullyFilledText));
        NoNullRet("True",  Coalesce(NullyFalse, True,       NullyTrue,  NullText       ));
        NoNullRet("True",  Coalesce(NullyFalse, True,       NullyTrue,  Empty          ));
        NoNullRet("True",  Coalesce(NullyFalse, True,       NullyTrue,  Text           ));
        NoNullRet("True",  Coalesce(NullyFalse, True,       NullyTrue,  NullySpace     ));
        NoNullRet("True",  Coalesce(NullyFalse, True,       NullyTrue,  NullyFilledText));
        NoNullRet("True",  Coalesce(NullyFalse, True,       False,      NullText       ));
        NoNullRet("True",  Coalesce(NullyFalse, True,       False,      Empty          ));
        NoNullRet("True",  Coalesce(NullyFalse, True,       False,      Text           ));
        NoNullRet("True",  Coalesce(NullyFalse, True,       False,      NullySpace     ));
        NoNullRet("True",  Coalesce(NullyFalse, True,       False,      NullyFilledText));
        NoNullRet("True",  Coalesce(NullyFalse, True,       True,       NullText       ));
        NoNullRet("True",  Coalesce(NullyFalse, True,       True,       Empty          ));
        NoNullRet("True",  Coalesce(NullyFalse, True,       True,       Text           ));
        NoNullRet("True",  Coalesce(NullyFalse, True,       True,       NullySpace     ));
        NoNullRet("True",  Coalesce(NullyFalse, True,       True,       NullyFilledText));
    }

    [TestMethod]
    public void Coalesce_4Args_BoolToText_Static_Batch3()
    {
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   NullBool,   NullText       ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   NullBool,   Empty          ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   NullBool,   Text           ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   NullBool,   NullySpace     ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   NullBool,   NullyFilledText));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   NullyFalse, NullText       ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   NullyFalse, Empty          ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   NullyFalse, Text           ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   NullyFalse, NullySpace     ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   NullyFalse, NullyFilledText));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   NullyTrue,  NullText       ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   NullyTrue,  Empty          ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   NullyTrue,  Text           ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   NullyTrue,  NullySpace     ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   NullyTrue,  NullyFilledText));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   False,      NullText       ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   False,      Empty          ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   False,      Text           ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   False,      NullySpace     ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   False,      NullyFilledText));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   True,       NullText       ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   True,       Empty          ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   True,       Text           ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   True,       NullySpace     ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullBool,   True,       NullyFilledText));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, NullBool,   NullText       ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, NullBool,   Empty          ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, NullBool,   Text           ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, NullBool,   NullySpace     ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, NullBool,   NullyFilledText));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, NullyFalse, NullText       ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, NullyFalse, Empty          ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, NullyFalse, Text           ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, NullyFalse, NullySpace     ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, NullyFalse, NullyFilledText));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, NullyTrue,  NullText       ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, NullyTrue,  Empty          ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, NullyTrue,  Text           ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, NullyTrue,  NullySpace     ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, NullyTrue,  NullyFilledText));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, False,      NullText       ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, False,      Empty          ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, False,      Text           ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, False,      NullySpace     ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, False,      NullyFilledText));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, True,       NullText       ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, True,       Empty          ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, True,       Text           ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, True,       NullySpace     ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyFalse, True,       NullyFilledText));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyTrue,  NullBool,   NullText       ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyTrue,  NullBool,   Empty          ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyTrue,  NullBool,   Text           ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyTrue,  NullBool,   NullySpace     ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyTrue,  NullBool,   NullyFilledText));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyTrue,  NullyFalse, NullText       ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyTrue,  NullyFalse, Empty          ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyTrue,  NullyFalse, Text           ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyTrue,  NullyFalse, NullySpace     ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyTrue,  NullyFalse, NullyFilledText));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyTrue,  NullyTrue,  NullText       ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyTrue,  NullyTrue,  Empty          ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyTrue,  NullyTrue,  Text           ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyTrue,  NullyTrue,  NullySpace     ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyTrue,  NullyTrue,  NullyFilledText));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyTrue,  False,      NullText       ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyTrue,  False,      Empty          ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyTrue,  False,      Text           ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyTrue,  False,      NullySpace     ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyTrue,  False,      NullyFilledText));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyTrue,  True,       NullText       ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyTrue,  True,       Empty          ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyTrue,  True,       Text           ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyTrue,  True,       NullySpace     ));
        NoNullRet("True",  Coalesce(NullyTrue,  NullyTrue,  True,       NullyFilledText));
        NoNullRet("True",  Coalesce(NullyTrue,  False,      NullBool,   NullText       ));
        NoNullRet("True",  Coalesce(NullyTrue,  False,      NullBool,   Empty          ));
        NoNullRet("True",  Coalesce(NullyTrue,  False,      NullBool,   Text           ));
        NoNullRet("True",  Coalesce(NullyTrue,  False,      NullBool,   NullySpace     ));
        NoNullRet("True",  Coalesce(NullyTrue,  False,      NullBool,   NullyFilledText));
        NoNullRet("True",  Coalesce(NullyTrue,  False,      NullyFalse, NullText       ));
        NoNullRet("True",  Coalesce(NullyTrue,  False,      NullyFalse, Empty          ));
        NoNullRet("True",  Coalesce(NullyTrue,  False,      NullyFalse, Text           ));
        NoNullRet("True",  Coalesce(NullyTrue,  False,      NullyFalse, NullySpace     ));
        NoNullRet("True",  Coalesce(NullyTrue,  False,      NullyFalse, NullyFilledText));
        NoNullRet("True",  Coalesce(NullyTrue,  False,      NullyTrue,  NullText       ));
        NoNullRet("True",  Coalesce(NullyTrue,  False,      NullyTrue,  Empty          ));
        NoNullRet("True",  Coalesce(NullyTrue,  False,      NullyTrue,  Text           ));
        NoNullRet("True",  Coalesce(NullyTrue,  False,      NullyTrue,  NullySpace     ));
        NoNullRet("True",  Coalesce(NullyTrue,  False,      NullyTrue,  NullyFilledText));
        NoNullRet("True",  Coalesce(NullyTrue,  False,      False,      NullText       ));
        NoNullRet("True",  Coalesce(NullyTrue,  False,      False,      Empty          ));
        NoNullRet("True",  Coalesce(NullyTrue,  False,      False,      Text           ));
        NoNullRet("True",  Coalesce(NullyTrue,  False,      False,      NullySpace     ));
        NoNullRet("True",  Coalesce(NullyTrue,  False,      False,      NullyFilledText));
        NoNullRet("True",  Coalesce(NullyTrue,  False,      True,       NullText       ));
        NoNullRet("True",  Coalesce(NullyTrue,  False,      True,       Empty          ));
        NoNullRet("True",  Coalesce(NullyTrue,  False,      True,       Text           ));
        NoNullRet("True",  Coalesce(NullyTrue,  False,      True,       NullySpace     ));
        NoNullRet("True",  Coalesce(NullyTrue,  False,      True,       NullyFilledText));
        NoNullRet("True",  Coalesce(NullyTrue,  True,       NullBool,   NullText       ));
        NoNullRet("True",  Coalesce(NullyTrue,  True,       NullBool,   Empty          ));
        NoNullRet("True",  Coalesce(NullyTrue,  True,       NullBool,   Text           ));
        NoNullRet("True",  Coalesce(NullyTrue,  True,       NullBool,   NullySpace     ));
        NoNullRet("True",  Coalesce(NullyTrue,  True,       NullBool,   NullyFilledText));
        NoNullRet("True",  Coalesce(NullyTrue,  True,       NullyFalse, NullText       ));
        NoNullRet("True",  Coalesce(NullyTrue,  True,       NullyFalse, Empty          ));
        NoNullRet("True",  Coalesce(NullyTrue,  True,       NullyFalse, Text           ));
        NoNullRet("True",  Coalesce(NullyTrue,  True,       NullyFalse, NullySpace     ));
        NoNullRet("True",  Coalesce(NullyTrue,  True,       NullyFalse, NullyFilledText));
        NoNullRet("True",  Coalesce(NullyTrue,  True,       NullyTrue,  NullText       ));
        NoNullRet("True",  Coalesce(NullyTrue,  True,       NullyTrue,  Empty          ));
        NoNullRet("True",  Coalesce(NullyTrue,  True,       NullyTrue,  Text           ));
        NoNullRet("True",  Coalesce(NullyTrue,  True,       NullyTrue,  NullySpace     ));
        NoNullRet("True",  Coalesce(NullyTrue,  True,       NullyTrue,  NullyFilledText));
        NoNullRet("True",  Coalesce(NullyTrue,  True,       False,      NullText       ));
        NoNullRet("True",  Coalesce(NullyTrue,  True,       False,      Empty          ));
        NoNullRet("True",  Coalesce(NullyTrue,  True,       False,      Text           ));
        NoNullRet("True",  Coalesce(NullyTrue,  True,       False,      NullySpace     ));
        NoNullRet("True",  Coalesce(NullyTrue,  True,       False,      NullyFilledText));
        NoNullRet("True",  Coalesce(NullyTrue,  True,       True,       NullText       ));
        NoNullRet("True",  Coalesce(NullyTrue,  True,       True,       Empty          ));
        NoNullRet("True",  Coalesce(NullyTrue,  True,       True,       Text           ));
        NoNullRet("True",  Coalesce(NullyTrue,  True,       True,       NullySpace     ));
        NoNullRet("True",  Coalesce(NullyTrue,  True,       True,       NullyFilledText));
    }

    [TestMethod]
    public void Coalesce_4Args_BoolToText_Static_Batch4()
    {
        NoNullRet("",      Coalesce(False,      NullBool,   NullBool,   NullText       ));
        NoNullRet("",      Coalesce(False,      NullBool,   NullBool,   Empty          ));
        NoNullRet(Text,    Coalesce(False,      NullBool,   NullBool,   Text           ));
        NoNullRet(" ",     Coalesce(False,      NullBool,   NullBool,   NullySpace     ));
        NoNullRet(Text,    Coalesce(False,      NullBool,   NullBool,   NullyFilledText));
        NoNullRet("",      Coalesce(False,      NullBool,   NullyFalse, NullText       ));
        NoNullRet("",      Coalesce(False,      NullBool,   NullyFalse, Empty          ));
        NoNullRet(Text,    Coalesce(False,      NullBool,   NullyFalse, Text           ));
        NoNullRet(" ",     Coalesce(False,      NullBool,   NullyFalse, NullySpace     ));
        NoNullRet(Text,    Coalesce(False,      NullBool,   NullyFalse, NullyFilledText));
        NoNullRet("True",  Coalesce(False,      NullBool,   NullyTrue,  NullText       ));
        NoNullRet("True",  Coalesce(False,      NullBool,   NullyTrue,  Empty          ));
        NoNullRet("True",  Coalesce(False,      NullBool,   NullyTrue,  Text           ));
        NoNullRet("True",  Coalesce(False,      NullBool,   NullyTrue,  NullySpace     ));
        NoNullRet("True",  Coalesce(False,      NullBool,   NullyTrue,  NullyFilledText));
        NoNullRet("",      Coalesce(False,      NullBool,   False,      NullText       ));
        NoNullRet("",      Coalesce(False,      NullBool,   False,      Empty          ));
        NoNullRet(Text,    Coalesce(False,      NullBool,   False,      Text           ));
        NoNullRet(" ",     Coalesce(False,      NullBool,   False,      NullySpace     ));
        NoNullRet(Text,    Coalesce(False,      NullBool,   False,      NullyFilledText));
        NoNullRet("True",  Coalesce(False,      NullBool,   True,       NullText       ));
        NoNullRet("True",  Coalesce(False,      NullBool,   True,       Empty          ));
        NoNullRet("True",  Coalesce(False,      NullBool,   True,       Text           ));
        NoNullRet("True",  Coalesce(False,      NullBool,   True,       NullySpace     ));
        NoNullRet("True",  Coalesce(False,      NullBool,   True,       NullyFilledText));
        NoNullRet("",      Coalesce(False,      NullyFalse, NullBool,   NullText       ));
        NoNullRet("",      Coalesce(False,      NullyFalse, NullBool,   Empty          ));
        NoNullRet(Text,    Coalesce(False,      NullyFalse, NullBool,   Text           ));
        NoNullRet(" ",     Coalesce(False,      NullyFalse, NullBool,   NullySpace     ));
        NoNullRet(Text,    Coalesce(False,      NullyFalse, NullBool,   NullyFilledText));
        NoNullRet("",      Coalesce(False,      NullyFalse, NullyFalse, NullText       ));
        NoNullRet("",      Coalesce(False,      NullyFalse, NullyFalse, Empty          ));
        NoNullRet(Text,    Coalesce(False,      NullyFalse, NullyFalse, Text           ));
        NoNullRet(" ",     Coalesce(False,      NullyFalse, NullyFalse, NullySpace     ));
        NoNullRet(Text,    Coalesce(False,      NullyFalse, NullyFalse, NullyFilledText));
        NoNullRet("True",  Coalesce(False,      NullyFalse, NullyTrue,  NullText       ));
        NoNullRet("True",  Coalesce(False,      NullyFalse, NullyTrue,  Empty          ));
        NoNullRet("True",  Coalesce(False,      NullyFalse, NullyTrue,  Text           ));
        NoNullRet("True",  Coalesce(False,      NullyFalse, NullyTrue,  NullySpace     ));
        NoNullRet("True",  Coalesce(False,      NullyFalse, NullyTrue,  NullyFilledText));
        NoNullRet("",      Coalesce(False,      NullyFalse, False,      NullText       ));
        NoNullRet("",      Coalesce(False,      NullyFalse, False,      Empty          ));
        NoNullRet(Text,    Coalesce(False,      NullyFalse, False,      Text           ));
        NoNullRet(" ",     Coalesce(False,      NullyFalse, False,      NullySpace     ));
        NoNullRet(Text,    Coalesce(False,      NullyFalse, False,      NullyFilledText));
        NoNullRet("True",  Coalesce(False,      NullyFalse, True,       NullText       ));
        NoNullRet("True",  Coalesce(False,      NullyFalse, True,       Empty          ));
        NoNullRet("True",  Coalesce(False,      NullyFalse, True,       Text           ));
        NoNullRet("True",  Coalesce(False,      NullyFalse, True,       NullySpace     ));
        NoNullRet("True",  Coalesce(False,      NullyFalse, True,       NullyFilledText));
        NoNullRet("True",  Coalesce(False,      NullyTrue,  NullBool,   NullText       ));
        NoNullRet("True",  Coalesce(False,      NullyTrue,  NullBool,   Empty          ));
        NoNullRet("True",  Coalesce(False,      NullyTrue,  NullBool,   Text           ));
        NoNullRet("True",  Coalesce(False,      NullyTrue,  NullBool,   NullySpace     ));
        NoNullRet("True",  Coalesce(False,      NullyTrue,  NullBool,   NullyFilledText));
        NoNullRet("True",  Coalesce(False,      NullyTrue,  NullyFalse, NullText       ));
        NoNullRet("True",  Coalesce(False,      NullyTrue,  NullyFalse, Empty          ));
        NoNullRet("True",  Coalesce(False,      NullyTrue,  NullyFalse, Text           ));
        NoNullRet("True",  Coalesce(False,      NullyTrue,  NullyFalse, NullySpace     ));
        NoNullRet("True",  Coalesce(False,      NullyTrue,  NullyFalse, NullyFilledText));
        NoNullRet("True",  Coalesce(False,      NullyTrue,  NullyTrue,  NullText       ));
        NoNullRet("True",  Coalesce(False,      NullyTrue,  NullyTrue,  Empty          ));
        NoNullRet("True",  Coalesce(False,      NullyTrue,  NullyTrue,  Text           ));
        NoNullRet("True",  Coalesce(False,      NullyTrue,  NullyTrue,  NullySpace     ));
        NoNullRet("True",  Coalesce(False,      NullyTrue,  NullyTrue,  NullyFilledText));
        NoNullRet("True",  Coalesce(False,      NullyTrue,  False,      NullText       ));
        NoNullRet("True",  Coalesce(False,      NullyTrue,  False,      Empty          ));
        NoNullRet("True",  Coalesce(False,      NullyTrue,  False,      Text           ));
        NoNullRet("True",  Coalesce(False,      NullyTrue,  False,      NullySpace     ));
        NoNullRet("True",  Coalesce(False,      NullyTrue,  False,      NullyFilledText));
        NoNullRet("True",  Coalesce(False,      NullyTrue,  True,       NullText       ));
        NoNullRet("True",  Coalesce(False,      NullyTrue,  True,       Empty          ));
        NoNullRet("True",  Coalesce(False,      NullyTrue,  True,       Text           ));
        NoNullRet("True",  Coalesce(False,      NullyTrue,  True,       NullySpace     ));
        NoNullRet("True",  Coalesce(False,      NullyTrue,  True,       NullyFilledText));
        NoNullRet("",      Coalesce(False,      False,      NullBool,   NullText       ));
        NoNullRet("",      Coalesce(False,      False,      NullBool,   Empty          ));
        NoNullRet(Text,    Coalesce(False,      False,      NullBool,   Text           ));
        NoNullRet(" ",     Coalesce(False,      False,      NullBool,   NullySpace     ));
        NoNullRet(Text,    Coalesce(False,      False,      NullBool,   NullyFilledText));
        NoNullRet("",      Coalesce(False,      False,      NullyFalse, NullText       ));
        NoNullRet("",      Coalesce(False,      False,      NullyFalse, Empty          ));
        NoNullRet(Text,    Coalesce(False,      False,      NullyFalse, Text           ));
        NoNullRet(" ",     Coalesce(False,      False,      NullyFalse, NullySpace     ));
        NoNullRet(Text,    Coalesce(False,      False,      NullyFalse, NullyFilledText));
        NoNullRet("True",  Coalesce(False,      False,      NullyTrue,  NullText       ));
        NoNullRet("True",  Coalesce(False,      False,      NullyTrue,  Empty          ));
        NoNullRet("True",  Coalesce(False,      False,      NullyTrue,  Text           ));
        NoNullRet("True",  Coalesce(False,      False,      NullyTrue,  NullySpace     ));
        NoNullRet("True",  Coalesce(False,      False,      NullyTrue,  NullyFilledText));
        NoNullRet("",      Coalesce(False,      False,      False,      NullText       ));
        NoNullRet("",      Coalesce(False,      False,      False,      Empty          ));
        NoNullRet(Text,    Coalesce(False,      False,      False,      Text           ));
        NoNullRet(" ",     Coalesce(False,      False,      False,      NullySpace     ));
        NoNullRet(Text,    Coalesce(False,      False,      False,      NullyFilledText));
        NoNullRet("True",  Coalesce(False,      False,      True,       NullText       ));
        NoNullRet("True",  Coalesce(False,      False,      True,       Empty          ));
        NoNullRet("True",  Coalesce(False,      False,      True,       Text           ));
        NoNullRet("True",  Coalesce(False,      False,      True,       NullySpace     ));
        NoNullRet("True",  Coalesce(False,      False,      True,       NullyFilledText));
        NoNullRet("True",  Coalesce(False,      True,       NullBool,   NullText       ));
        NoNullRet("True",  Coalesce(False,      True,       NullBool,   Empty          ));
        NoNullRet("True",  Coalesce(False,      True,       NullBool,   Text           ));
        NoNullRet("True",  Coalesce(False,      True,       NullBool,   NullySpace     ));
        NoNullRet("True",  Coalesce(False,      True,       NullBool,   NullyFilledText));
        NoNullRet("True",  Coalesce(False,      True,       NullyFalse, NullText       ));
        NoNullRet("True",  Coalesce(False,      True,       NullyFalse, Empty          ));
        NoNullRet("True",  Coalesce(False,      True,       NullyFalse, Text           ));
        NoNullRet("True",  Coalesce(False,      True,       NullyFalse, NullySpace     ));
        NoNullRet("True",  Coalesce(False,      True,       NullyFalse, NullyFilledText));
        NoNullRet("True",  Coalesce(False,      True,       NullyTrue,  NullText       ));
        NoNullRet("True",  Coalesce(False,      True,       NullyTrue,  Empty          ));
        NoNullRet("True",  Coalesce(False,      True,       NullyTrue,  Text           ));
        NoNullRet("True",  Coalesce(False,      True,       NullyTrue,  NullySpace     ));
        NoNullRet("True",  Coalesce(False,      True,       NullyTrue,  NullyFilledText));
        NoNullRet("True",  Coalesce(False,      True,       False,      NullText       ));
        NoNullRet("True",  Coalesce(False,      True,       False,      Empty          ));
        NoNullRet("True",  Coalesce(False,      True,       False,      Text           ));
        NoNullRet("True",  Coalesce(False,      True,       False,      NullySpace     ));
        NoNullRet("True",  Coalesce(False,      True,       False,      NullyFilledText));
        NoNullRet("True",  Coalesce(False,      True,       True,       NullText       ));
        NoNullRet("True",  Coalesce(False,      True,       True,       Empty          ));
        NoNullRet("True",  Coalesce(False,      True,       True,       Text           ));
        NoNullRet("True",  Coalesce(False,      True,       True,       NullySpace     ));
        NoNullRet("True",  Coalesce(False,      True,       True,       NullyFilledText));
    }

    [TestMethod]
    public void Coalesce_4Args_BoolToText_Static_Batch5()
    {
        NoNullRet("True",  Coalesce(True,       NullBool,   NullBool,   NullText       ));
        NoNullRet("True",  Coalesce(True,       NullBool,   NullBool,   Empty          ));
        NoNullRet("True",  Coalesce(True,       NullBool,   NullBool,   Text           ));
        NoNullRet("True",  Coalesce(True,       NullBool,   NullBool,   NullySpace     ));
        NoNullRet("True",  Coalesce(True,       NullBool,   NullBool,   NullyFilledText));
        NoNullRet("True",  Coalesce(True,       NullBool,   NullyFalse, NullText       ));
        NoNullRet("True",  Coalesce(True,       NullBool,   NullyFalse, Empty          ));
        NoNullRet("True",  Coalesce(True,       NullBool,   NullyFalse, Text           ));
        NoNullRet("True",  Coalesce(True,       NullBool,   NullyFalse, NullySpace     ));
        NoNullRet("True",  Coalesce(True,       NullBool,   NullyFalse, NullyFilledText));
        NoNullRet("True",  Coalesce(True,       NullBool,   NullyTrue,  NullText       ));
        NoNullRet("True",  Coalesce(True,       NullBool,   NullyTrue,  Empty          ));
        NoNullRet("True",  Coalesce(True,       NullBool,   NullyTrue,  Text           ));
        NoNullRet("True",  Coalesce(True,       NullBool,   NullyTrue,  NullySpace     ));
        NoNullRet("True",  Coalesce(True,       NullBool,   NullyTrue,  NullyFilledText));
        NoNullRet("True",  Coalesce(True,       NullBool,   False,      NullText       ));
        NoNullRet("True",  Coalesce(True,       NullBool,   False,      Empty          ));
        NoNullRet("True",  Coalesce(True,       NullBool,   False,      Text           ));
        NoNullRet("True",  Coalesce(True,       NullBool,   False,      NullySpace     ));
        NoNullRet("True",  Coalesce(True,       NullBool,   False,      NullyFilledText));
        NoNullRet("True",  Coalesce(True,       NullBool,   True,       NullText       ));
        NoNullRet("True",  Coalesce(True,       NullBool,   True,       Empty          ));
        NoNullRet("True",  Coalesce(True,       NullBool,   True,       Text           ));
        NoNullRet("True",  Coalesce(True,       NullBool,   True,       NullySpace     ));
        NoNullRet("True",  Coalesce(True,       NullBool,   True,       NullyFilledText));
        NoNullRet("True",  Coalesce(True,       NullyFalse, NullBool,   NullText       ));
        NoNullRet("True",  Coalesce(True,       NullyFalse, NullBool,   Empty          ));
        NoNullRet("True",  Coalesce(True,       NullyFalse, NullBool,   Text           ));
        NoNullRet("True",  Coalesce(True,       NullyFalse, NullBool,   NullySpace     ));
        NoNullRet("True",  Coalesce(True,       NullyFalse, NullBool,   NullyFilledText));
        NoNullRet("True",  Coalesce(True,       NullyFalse, NullyFalse, NullText       ));
        NoNullRet("True",  Coalesce(True,       NullyFalse, NullyFalse, Empty          ));
        NoNullRet("True",  Coalesce(True,       NullyFalse, NullyFalse, Text           ));
        NoNullRet("True",  Coalesce(True,       NullyFalse, NullyFalse, NullySpace     ));
        NoNullRet("True",  Coalesce(True,       NullyFalse, NullyFalse, NullyFilledText));
        NoNullRet("True",  Coalesce(True,       NullyFalse, NullyTrue,  NullText       ));
        NoNullRet("True",  Coalesce(True,       NullyFalse, NullyTrue,  Empty          ));
        NoNullRet("True",  Coalesce(True,       NullyFalse, NullyTrue,  Text           ));
        NoNullRet("True",  Coalesce(True,       NullyFalse, NullyTrue,  NullySpace     ));
        NoNullRet("True",  Coalesce(True,       NullyFalse, NullyTrue,  NullyFilledText));
        NoNullRet("True",  Coalesce(True,       NullyFalse, False,      NullText       ));
        NoNullRet("True",  Coalesce(True,       NullyFalse, False,      Empty          ));
        NoNullRet("True",  Coalesce(True,       NullyFalse, False,      Text           ));
        NoNullRet("True",  Coalesce(True,       NullyFalse, False,      NullySpace     ));
        NoNullRet("True",  Coalesce(True,       NullyFalse, False,      NullyFilledText));
        NoNullRet("True",  Coalesce(True,       NullyFalse, True,       NullText       ));
        NoNullRet("True",  Coalesce(True,       NullyFalse, True,       Empty          ));
        NoNullRet("True",  Coalesce(True,       NullyFalse, True,       Text           ));
        NoNullRet("True",  Coalesce(True,       NullyFalse, True,       NullySpace     ));
        NoNullRet("True",  Coalesce(True,       NullyFalse, True,       NullyFilledText));
        NoNullRet("True",  Coalesce(True,       NullyTrue,  NullBool,   NullText       ));
        NoNullRet("True",  Coalesce(True,       NullyTrue,  NullBool,   Empty          ));
        NoNullRet("True",  Coalesce(True,       NullyTrue,  NullBool,   Text           ));
        NoNullRet("True",  Coalesce(True,       NullyTrue,  NullBool,   NullySpace     ));
        NoNullRet("True",  Coalesce(True,       NullyTrue,  NullBool,   NullyFilledText));
        NoNullRet("True",  Coalesce(True,       NullyTrue,  NullyFalse, NullText       ));
        NoNullRet("True",  Coalesce(True,       NullyTrue,  NullyFalse, Empty          ));
        NoNullRet("True",  Coalesce(True,       NullyTrue,  NullyFalse, Text           ));
        NoNullRet("True",  Coalesce(True,       NullyTrue,  NullyFalse, NullySpace     ));
        NoNullRet("True",  Coalesce(True,       NullyTrue,  NullyFalse, NullyFilledText));
        NoNullRet("True",  Coalesce(True,       NullyTrue,  NullyTrue,  NullText       ));
        NoNullRet("True",  Coalesce(True,       NullyTrue,  NullyTrue,  Empty          ));
        NoNullRet("True",  Coalesce(True,       NullyTrue,  NullyTrue,  Text           ));
        NoNullRet("True",  Coalesce(True,       NullyTrue,  NullyTrue,  NullySpace     ));
        NoNullRet("True",  Coalesce(True,       NullyTrue,  NullyTrue,  NullyFilledText));
        NoNullRet("True",  Coalesce(True,       NullyTrue,  False,      NullText       ));
        NoNullRet("True",  Coalesce(True,       NullyTrue,  False,      Empty          ));
        NoNullRet("True",  Coalesce(True,       NullyTrue,  False,      Text           ));
        NoNullRet("True",  Coalesce(True,       NullyTrue,  False,      NullySpace     ));
        NoNullRet("True",  Coalesce(True,       NullyTrue,  False,      NullyFilledText));
        NoNullRet("True",  Coalesce(True,       NullyTrue,  True,       NullText       ));
        NoNullRet("True",  Coalesce(True,       NullyTrue,  True,       Empty          ));
        NoNullRet("True",  Coalesce(True,       NullyTrue,  True,       Text           ));
        NoNullRet("True",  Coalesce(True,       NullyTrue,  True,       NullySpace     ));
        NoNullRet("True",  Coalesce(True,       NullyTrue,  True,       NullyFilledText));
        NoNullRet("True",  Coalesce(True,       False,      NullBool,   NullText       ));
        NoNullRet("True",  Coalesce(True,       False,      NullBool,   Empty          ));
        NoNullRet("True",  Coalesce(True,       False,      NullBool,   Text           ));
        NoNullRet("True",  Coalesce(True,       False,      NullBool,   NullySpace     ));
        NoNullRet("True",  Coalesce(True,       False,      NullBool,   NullyFilledText));
        NoNullRet("True",  Coalesce(True,       False,      NullyFalse, NullText       ));
        NoNullRet("True",  Coalesce(True,       False,      NullyFalse, Empty          ));
        NoNullRet("True",  Coalesce(True,       False,      NullyFalse, Text           ));
        NoNullRet("True",  Coalesce(True,       False,      NullyFalse, NullySpace     ));
        NoNullRet("True",  Coalesce(True,       False,      NullyFalse, NullyFilledText));
        NoNullRet("True",  Coalesce(True,       False,      NullyTrue,  NullText       ));
        NoNullRet("True",  Coalesce(True,       False,      NullyTrue,  Empty          ));
        NoNullRet("True",  Coalesce(True,       False,      NullyTrue,  Text           ));
        NoNullRet("True",  Coalesce(True,       False,      NullyTrue,  NullySpace     ));
        NoNullRet("True",  Coalesce(True,       False,      NullyTrue,  NullyFilledText));
        NoNullRet("True",  Coalesce(True,       False,      False,      NullText       ));
        NoNullRet("True",  Coalesce(True,       False,      False,      Empty          ));
        NoNullRet("True",  Coalesce(True,       False,      False,      Text           ));
        NoNullRet("True",  Coalesce(True,       False,      False,      NullySpace     ));
        NoNullRet("True",  Coalesce(True,       False,      False,      NullyFilledText));
        NoNullRet("True",  Coalesce(True,       False,      True,       NullText       ));
        NoNullRet("True",  Coalesce(True,       False,      True,       Empty          ));
        NoNullRet("True",  Coalesce(True,       False,      True,       Text           ));
        NoNullRet("True",  Coalesce(True,       False,      True,       NullySpace     ));
        NoNullRet("True",  Coalesce(True,       False,      True,       NullyFilledText));
        NoNullRet("True",  Coalesce(True,       True,       NullBool,   NullText       ));
        NoNullRet("True",  Coalesce(True,       True,       NullBool,   Empty          ));
        NoNullRet("True",  Coalesce(True,       True,       NullBool,   Text           ));
        NoNullRet("True",  Coalesce(True,       True,       NullBool,   NullySpace     ));
        NoNullRet("True",  Coalesce(True,       True,       NullBool,   NullyFilledText));
        NoNullRet("True",  Coalesce(True,       True,       NullyFalse, NullText       ));
        NoNullRet("True",  Coalesce(True,       True,       NullyFalse, Empty          ));
        NoNullRet("True",  Coalesce(True,       True,       NullyFalse, Text           ));
        NoNullRet("True",  Coalesce(True,       True,       NullyFalse, NullySpace     ));
        NoNullRet("True",  Coalesce(True,       True,       NullyFalse, NullyFilledText));
        NoNullRet("True",  Coalesce(True,       True,       NullyTrue,  NullText       ));
        NoNullRet("True",  Coalesce(True,       True,       NullyTrue,  Empty          ));
        NoNullRet("True",  Coalesce(True,       True,       NullyTrue,  Text           ));
        NoNullRet("True",  Coalesce(True,       True,       NullyTrue,  NullySpace     ));
        NoNullRet("True",  Coalesce(True,       True,       NullyTrue,  NullyFilledText));
        NoNullRet("True",  Coalesce(True,       True,       False,      NullText       ));
        NoNullRet("True",  Coalesce(True,       True,       False,      Empty          ));
        NoNullRet("True",  Coalesce(True,       True,       False,      Text           ));
        NoNullRet("True",  Coalesce(True,       True,       False,      NullySpace     ));
        NoNullRet("True",  Coalesce(True,       True,       False,      NullyFilledText));
        NoNullRet("True",  Coalesce(True,       True,       True,       NullText       ));
        NoNullRet("True",  Coalesce(True,       True,       True,       Empty          ));
        NoNullRet("True",  Coalesce(True,       True,       True,       Text           ));
        NoNullRet("True",  Coalesce(True,       True,       True,       NullySpace     ));
        NoNullRet("True",  Coalesce(True,       True,       True,       NullyFilledText));
    }
}