namespace JJ.Framework.Existence.Core.Tests;

[TestClass]
public class Coalesce_2Args_Values_FlagsInFront : TestBase
{
    // Vals

    [TestMethod]
    public void Coalesce_2Args_Vals_StaticZeroMattersFlagsInBack()
    {
        NoNullRet(0, Coalesce(zeroMatters: false,  Nully0, NullNum));
        NoNullRet(0, Coalesce(             false,  Nully0, NullNum));
        NoNullRet(0, Coalesce(zeroMatters,         Nully0, NullNum));
        NoNullRet(0, Coalesce(zeroMatters: true,   Nully0, NullNum));
        NoNullRet(0, Coalesce(             true,   Nully0, NullNum));
        NoNullRet(1, Coalesce(zeroMatters: false,  Nully1, NullNum));
        NoNullRet(1, Coalesce(             false,  Nully1, NullNum));
        NoNullRet(1, Coalesce(zeroMatters,         Nully1, NullNum));
        NoNullRet(1, Coalesce(zeroMatters: true,   Nully1, NullNum));
        NoNullRet(1, Coalesce(             true,   Nully1, NullNum));
        NoNullRet(0, Coalesce(zeroMatters: false,       0, NullNum));
        NoNullRet(0, Coalesce(             false,       0, NullNum));
        NoNullRet(0, Coalesce(zeroMatters,              0, NullNum));
        NoNullRet(0, Coalesce(zeroMatters: true,        0, NullNum));
        NoNullRet(0, Coalesce(             true,        0, NullNum));
        NoNullRet(1, Coalesce(zeroMatters: false,       1, NullNum));
        NoNullRet(1, Coalesce(             false,       1, NullNum));
        NoNullRet(1, Coalesce(zeroMatters,              1, NullNum));
        NoNullRet(1, Coalesce(zeroMatters: true,        1, NullNum));
        NoNullRet(1, Coalesce(             true,        1, NullNum));
        NoNullRet(0, Coalesce(zeroMatters: false, NullNum,  Nully0));
        NoNullRet(0, Coalesce(             false, NullNum,  Nully0));
        NoNullRet(0, Coalesce(zeroMatters,        NullNum,  Nully0));
        NoNullRet(0, Coalesce(zeroMatters: true,  NullNum,  Nully0));
        NoNullRet(0, Coalesce(             true,  NullNum,  Nully0));
        NoNullRet(1, Coalesce(zeroMatters: false,  Nully1,  Nully0));
        NoNullRet(1, Coalesce(             false,  Nully1,  Nully0));
        NoNullRet(1, Coalesce(zeroMatters,         Nully1,  Nully0));
        NoNullRet(1, Coalesce(zeroMatters: true,   Nully1,  Nully0));
        NoNullRet(1, Coalesce(             true,   Nully1,  Nully0));
        NoNullRet(0, Coalesce(zeroMatters: false,       0,  Nully0));
        NoNullRet(0, Coalesce(             false,       0,  Nully0));
        NoNullRet(0, Coalesce(zeroMatters,              0,  Nully0));
        NoNullRet(0, Coalesce(zeroMatters: true,        0,  Nully0));
        NoNullRet(0, Coalesce(             true,        0,  Nully0));
        NoNullRet(1, Coalesce(zeroMatters: false,       1,  Nully0));
        NoNullRet(1, Coalesce(             false,       1,  Nully0));
        NoNullRet(1, Coalesce(zeroMatters,              1,  Nully0));
        NoNullRet(1, Coalesce(zeroMatters: true,        1,  Nully0));
        NoNullRet(1, Coalesce(             true,        1,  Nully0));
        NoNullRet(1, Coalesce(zeroMatters: false, NullNum,  Nully1));
        NoNullRet(1, Coalesce(             false, NullNum,  Nully1));
        NoNullRet(1, Coalesce(zeroMatters,        NullNum,  Nully1));
        NoNullRet(1, Coalesce(zeroMatters: true,  NullNum,  Nully1));
        NoNullRet(1, Coalesce(             true,  NullNum,  Nully1));
        NoNullRet(1, Coalesce(zeroMatters: false,  Nully0,  Nully1));
        NoNullRet(1, Coalesce(             false,  Nully0,  Nully1));
        NoNullRet(0, Coalesce(zeroMatters,         Nully0,  Nully1));
        NoNullRet(0, Coalesce(zeroMatters: true,   Nully0,  Nully1));
        NoNullRet(0, Coalesce(             true,   Nully0,  Nully1));
        NoNullRet(1, Coalesce(zeroMatters: false,       0,  Nully1));
        NoNullRet(1, Coalesce(             false,       0,  Nully1));
        NoNullRet(0, Coalesce(zeroMatters,              0,  Nully1));
        NoNullRet(0, Coalesce(zeroMatters: true,        0,  Nully1));
        NoNullRet(0, Coalesce(             true,        0,  Nully1));
        NoNullRet(1, Coalesce(zeroMatters: false,       1,  Nully1));
        NoNullRet(1, Coalesce(             false,       1,  Nully1));
        NoNullRet(1, Coalesce(zeroMatters,              1,  Nully1));
        NoNullRet(1, Coalesce(zeroMatters: true,        1,  Nully1));
        NoNullRet(1, Coalesce(             true,        1,  Nully1));
        NoNullRet(0, Coalesce(zeroMatters: false, NullNum,       0));
        NoNullRet(0, Coalesce(             false, NullNum,       0));
        NoNullRet(0, Coalesce(zeroMatters,        NullNum,       0));
        NoNullRet(0, Coalesce(zeroMatters: true,  NullNum,       0));
        NoNullRet(0, Coalesce(             true,  NullNum,       0));
        NoNullRet(0, Coalesce(zeroMatters: false,  Nully0,       0));
        NoNullRet(0, Coalesce(             false,  Nully0,       0));
        NoNullRet(0, Coalesce(zeroMatters,         Nully0,       0));
        NoNullRet(0, Coalesce(zeroMatters: true,   Nully0,       0));
        NoNullRet(0, Coalesce(             true,   Nully0,       0));
        NoNullRet(1, Coalesce(zeroMatters: false,  Nully1,       0));
        NoNullRet(1, Coalesce(             false,  Nully1,       0));
        NoNullRet(1, Coalesce(zeroMatters,         Nully1,       0));
        NoNullRet(1, Coalesce(zeroMatters: true,   Nully1,       0));
        NoNullRet(1, Coalesce(             true,   Nully1,       0));
        NoNullRet(1, Coalesce(zeroMatters: false,       1,       0));
        NoNullRet(1, Coalesce(             false,       1,       0));
        NoNullRet(1, Coalesce(zeroMatters,              1,       0));
        NoNullRet(1, Coalesce(zeroMatters: true,        1,       0));
        NoNullRet(1, Coalesce(             true,        1,       0));
        NoNullRet(1, Coalesce(zeroMatters: false, NullNum,       1));
        NoNullRet(1, Coalesce(             false, NullNum,       1));
        NoNullRet(1, Coalesce(zeroMatters,        NullNum,       1));
        NoNullRet(1, Coalesce(zeroMatters: true,  NullNum,       1));
        NoNullRet(1, Coalesce(             true,  NullNum,       1));
        NoNullRet(1, Coalesce(zeroMatters: false,  Nully0,       1));
        NoNullRet(1, Coalesce(             false,  Nully0,       1));
        NoNullRet(0, Coalesce(zeroMatters,         Nully0,       1));
        NoNullRet(0, Coalesce(zeroMatters: true,   Nully0,       1));
        NoNullRet(0, Coalesce(             true,   Nully0,       1));
        NoNullRet(1, Coalesce(zeroMatters: false,  Nully1,       1));
        NoNullRet(1, Coalesce(             false,  Nully1,       1));
        NoNullRet(1, Coalesce(zeroMatters,         Nully1,       1));
        NoNullRet(1, Coalesce(zeroMatters: true,   Nully1,       1));
        NoNullRet(1, Coalesce(             true,   Nully1,       1));
        NoNullRet(1, Coalesce(zeroMatters: false,       0,       1));
        NoNullRet(1, Coalesce(             false,       0,       1));
        NoNullRet(0, Coalesce(zeroMatters,              0,       1));
        NoNullRet(0, Coalesce(zeroMatters: true,        0,       1));
        NoNullRet(0, Coalesce(             true,        0,       1));
    }

    [TestMethod]
    public void Coalesce_2Args_Vals_ExtensionsZeroMattersFlagsInBack()
    {
        NoNullRet(0,   Nully0.Coalesce(zeroMatters: false, NullNum));
        NoNullRet(0,   Nully0.Coalesce(             false, NullNum));
        NoNullRet(0,   Nully0.Coalesce(zeroMatters,        NullNum));
        NoNullRet(0,   Nully0.Coalesce(zeroMatters: true,  NullNum));
        NoNullRet(0,   Nully0.Coalesce(             true,  NullNum));
        NoNullRet(1,   Nully1.Coalesce(zeroMatters: false, NullNum));
        NoNullRet(1,   Nully1.Coalesce(             false, NullNum));
        NoNullRet(1,   Nully1.Coalesce(zeroMatters,        NullNum));
        NoNullRet(1,   Nully1.Coalesce(zeroMatters: true,  NullNum));
        NoNullRet(1,   Nully1.Coalesce(             true,  NullNum));
        NoNullRet(0,        0.Coalesce(zeroMatters: false, NullNum));
        NoNullRet(0,        0.Coalesce(             false, NullNum));
        NoNullRet(0,        0.Coalesce(zeroMatters,        NullNum));
        NoNullRet(0,        0.Coalesce(zeroMatters: true,  NullNum));
        NoNullRet(0,        0.Coalesce(             true,  NullNum));
        NoNullRet(1,        1.Coalesce(zeroMatters: false, NullNum));
        NoNullRet(1,        1.Coalesce(             false, NullNum));
        NoNullRet(1,        1.Coalesce(zeroMatters,        NullNum));
        NoNullRet(1,        1.Coalesce(zeroMatters: true,  NullNum));
        NoNullRet(1,        1.Coalesce(             true,  NullNum));
        NoNullRet(0,  NullNum.Coalesce(zeroMatters: false,  Nully0));
        NoNullRet(0,  NullNum.Coalesce(             false,  Nully0));
        NoNullRet(0,  NullNum.Coalesce(zeroMatters,         Nully0));
        NoNullRet(0,  NullNum.Coalesce(zeroMatters: true,   Nully0));
        NoNullRet(0,  NullNum.Coalesce(             true,   Nully0));
        NoNullRet(1,   Nully1.Coalesce(zeroMatters: false,  Nully0));
        NoNullRet(1,   Nully1.Coalesce(             false,  Nully0));
        NoNullRet(1,   Nully1.Coalesce(zeroMatters,         Nully0));
        NoNullRet(1,   Nully1.Coalesce(zeroMatters: true,   Nully0));
        NoNullRet(1,   Nully1.Coalesce(             true,   Nully0));
        NoNullRet(0,        0.Coalesce(zeroMatters: false,  Nully0));
        NoNullRet(0,        0.Coalesce(             false,  Nully0));
        NoNullRet(0,        0.Coalesce(zeroMatters,         Nully0));
        NoNullRet(0,        0.Coalesce(zeroMatters: true,   Nully0));
        NoNullRet(0,        0.Coalesce(             true,   Nully0));
        NoNullRet(1,        1.Coalesce(zeroMatters: false,  Nully0));
        NoNullRet(1,        1.Coalesce(             false,  Nully0));
        NoNullRet(1,        1.Coalesce(zeroMatters,         Nully0));
        NoNullRet(1,        1.Coalesce(zeroMatters: true,   Nully0));
        NoNullRet(1,        1.Coalesce(             true,   Nully0));
        NoNullRet(1,  NullNum.Coalesce(zeroMatters: false,  Nully1));
        NoNullRet(1,  NullNum.Coalesce(             false,  Nully1));
        NoNullRet(1,  NullNum.Coalesce(zeroMatters,         Nully1));
        NoNullRet(1,  NullNum.Coalesce(zeroMatters: true,   Nully1));
        NoNullRet(1,  NullNum.Coalesce(             true,   Nully1));
        NoNullRet(1,   Nully0.Coalesce(zeroMatters: false,  Nully1));
        NoNullRet(1,   Nully0.Coalesce(             false,  Nully1));
        NoNullRet(0,   Nully0.Coalesce(zeroMatters,         Nully1));
        NoNullRet(0,   Nully0.Coalesce(zeroMatters: true,   Nully1));
        NoNullRet(0,   Nully0.Coalesce(             true,   Nully1));
        NoNullRet(1,        0.Coalesce(zeroMatters: false,  Nully1));
        NoNullRet(1,        0.Coalesce(             false,  Nully1));
        NoNullRet(0,        0.Coalesce(zeroMatters,         Nully1));
        NoNullRet(0,        0.Coalesce(zeroMatters: true,   Nully1));
        NoNullRet(0,        0.Coalesce(             true,   Nully1));
        NoNullRet(1,        1.Coalesce(zeroMatters: false,  Nully1));
        NoNullRet(1,        1.Coalesce(             false,  Nully1));
        NoNullRet(1,        1.Coalesce(zeroMatters,         Nully1));
        NoNullRet(1,        1.Coalesce(zeroMatters: true,   Nully1));
        NoNullRet(1,        1.Coalesce(             true,   Nully1));
        NoNullRet(0,  NullNum.Coalesce(zeroMatters: false,       0));
        NoNullRet(0,  NullNum.Coalesce(             false,       0));
        NoNullRet(0,  NullNum.Coalesce(zeroMatters,              0));
        NoNullRet(0,  NullNum.Coalesce(zeroMatters: true,        0));
        NoNullRet(0,  NullNum.Coalesce(             true,        0));
        NoNullRet(0,   Nully0.Coalesce(zeroMatters: false,       0));
        NoNullRet(0,   Nully0.Coalesce(             false,       0));
        NoNullRet(0,   Nully0.Coalesce(zeroMatters,              0));
        NoNullRet(0,   Nully0.Coalesce(zeroMatters: true,        0));
        NoNullRet(0,   Nully0.Coalesce(             true,        0));
        NoNullRet(1,   Nully1.Coalesce(zeroMatters: false,       0));
        NoNullRet(1,   Nully1.Coalesce(             false,       0));
        NoNullRet(1,   Nully1.Coalesce(zeroMatters,              0));
        NoNullRet(1,   Nully1.Coalesce(zeroMatters: true,        0));
        NoNullRet(1,   Nully1.Coalesce(             true,        0));
        NoNullRet(1,        1.Coalesce(zeroMatters: false,       0));
        NoNullRet(1,        1.Coalesce(             false,       0));
        NoNullRet(1,        1.Coalesce(zeroMatters,              0));
        NoNullRet(1,        1.Coalesce(zeroMatters: true,        0));
        NoNullRet(1,        1.Coalesce(             true,        0));
        NoNullRet(1,  NullNum.Coalesce(zeroMatters: false,       1));
        NoNullRet(1,  NullNum.Coalesce(             false,       1));
        NoNullRet(1,  NullNum.Coalesce(zeroMatters,              1));
        NoNullRet(1,  NullNum.Coalesce(zeroMatters: true,        1));
        NoNullRet(1,  NullNum.Coalesce(             true,        1));
        NoNullRet(1,   Nully0.Coalesce(zeroMatters: false,       1));
        NoNullRet(1,   Nully0.Coalesce(             false,       1));
        NoNullRet(0,   Nully0.Coalesce(zeroMatters,              1));
        NoNullRet(0,   Nully0.Coalesce(zeroMatters: true,        1));
        NoNullRet(0,   Nully0.Coalesce(             true,        1));
        NoNullRet(1,   Nully1.Coalesce(zeroMatters: false,       1));
        NoNullRet(1,   Nully1.Coalesce(             false,       1));
        NoNullRet(1,   Nully1.Coalesce(zeroMatters,              1));
        NoNullRet(1,   Nully1.Coalesce(zeroMatters: true,        1));
        NoNullRet(1,   Nully1.Coalesce(             true,        1));
        NoNullRet(1,        0.Coalesce(zeroMatters: false,       1));
        NoNullRet(1,        0.Coalesce(             false,       1));
        NoNullRet(0,        0.Coalesce(zeroMatters,              1));
        NoNullRet(0,        0.Coalesce(zeroMatters: true,        1));
        NoNullRet(0,        0.Coalesce(             true,        1));
    }

    // Vals to Text

    [TestMethod]
    public void Coalesce_2Args_ValToText_ZeroMattersNoNulliesFlagsInBack()
    {
        NoNullRet("",           Coalesce(zeroMatters: false, 0,  NullText ));
        NoNullRet("",           Coalesce(             false, 0,  NullText ));
        NoNullRet("0",          Coalesce(zeroMatters,        0,  NullText ));
        NoNullRet("0",          Coalesce(zeroMatters: true,  0,  NullText ));
        NoNullRet("0",          Coalesce(             true,  0,  NullText ));
        NoNullRet("peekaboo",   Coalesce(zeroMatters: false, 0, "peekaboo"));
        NoNullRet("peekaboo",   Coalesce(             false, 0, "peekaboo"));
        NoNullRet("0",          Coalesce(zeroMatters,        0, "peekaboo"));
        NoNullRet("0",          Coalesce(zeroMatters: true,  0, "peekaboo"));
        NoNullRet("0",          Coalesce(             true,  0, "peekaboo"));
        NoNullRet("1",          Coalesce(zeroMatters: false, 1,  NullText ));
        NoNullRet("1",          Coalesce(             false, 1,  NullText ));
        NoNullRet("1",          Coalesce(zeroMatters,        1,  NullText ));
        NoNullRet("1",          Coalesce(zeroMatters: true,  1,  NullText ));
        NoNullRet("1",          Coalesce(             true,  1,  NullText ));
        NoNullRet("1",          Coalesce(zeroMatters: false, 1, "peekaboo"));
        NoNullRet("1",          Coalesce(             false, 1, "peekaboo"));
        NoNullRet("1",          Coalesce(zeroMatters,        1, "peekaboo"));
        NoNullRet("1",          Coalesce(zeroMatters: true,  1, "peekaboo"));
        NoNullRet("1",          Coalesce(             true,  1, "peekaboo"));
        NoNullRet("",         0.Coalesce(zeroMatters: false,     NullText ));
        NoNullRet("",         0.Coalesce(             false,     NullText ));
        NoNullRet("0",        0.Coalesce(zeroMatters,            NullText ));
        NoNullRet("0",        0.Coalesce(zeroMatters: true,      NullText ));
        NoNullRet("0",        0.Coalesce(             true,      NullText ));
        NoNullRet("peekaboo", 0.Coalesce(zeroMatters: false,    "peekaboo"));
        NoNullRet("peekaboo", 0.Coalesce(             false,    "peekaboo"));
        NoNullRet("0",        0.Coalesce(zeroMatters,           "peekaboo"));
        NoNullRet("0",        0.Coalesce(zeroMatters: true,     "peekaboo"));
        NoNullRet("0",        0.Coalesce(             true,     "peekaboo"));
        NoNullRet("1",        1.Coalesce(zeroMatters: false,     NullText ));
        NoNullRet("1",        1.Coalesce(             false,     NullText ));
        NoNullRet("1",        1.Coalesce(zeroMatters,            NullText ));
        NoNullRet("1",        1.Coalesce(zeroMatters: true,      NullText ));
        NoNullRet("1",        1.Coalesce(             true,      NullText ));
        NoNullRet("1",        1.Coalesce(zeroMatters: false,    "peekaboo"));
        NoNullRet("1",        1.Coalesce(             false,    "peekaboo"));
        NoNullRet("1",        1.Coalesce(zeroMatters,           "peekaboo"));
        NoNullRet("1",        1.Coalesce(zeroMatters: true,     "peekaboo"));
        NoNullRet("1",        1.Coalesce(             true,     "peekaboo"));
    }

    [TestMethod]
    public void Coalesce_2Args_ValToText_ZeroMattersWithNulliesFlagsInBack()
    {
        NoNullRet("",    Coalesce(zeroMatters: false, NullNum,   NullText));
        NoNullRet("",    Coalesce(             false, NullNum,   NullText));
        NoNullRet("",    Coalesce(zeroMatters,        NullNum,   NullText));
        NoNullRet("",    Coalesce(zeroMatters: true,  NullNum,   NullText));
        NoNullRet("",    Coalesce(             true,  NullNum,   NullText));
        NoNullRet("boo", Coalesce(zeroMatters: false, NullNum,  "boo"    ));
        NoNullRet("boo", Coalesce(             false, NullNum,  "boo"    ));
        NoNullRet("boo", Coalesce(zeroMatters,        NullNum,  "boo"    ));
        NoNullRet("boo", Coalesce(zeroMatters: true,  NullNum,  "boo"    ));
        NoNullRet("boo", Coalesce(             true,  NullNum,  "boo"    ));
        NoNullRet("",    Coalesce(zeroMatters: false, Nully0,    NullText));
        NoNullRet("",    Coalesce(             false, Nully0,    NullText));
        NoNullRet("0",   Coalesce(zeroMatters,        Nully0,    NullText));
        NoNullRet("0",   Coalesce(zeroMatters: true,  Nully0,    NullText));
        NoNullRet("0",   Coalesce(             true,  Nully0,    NullText));
        NoNullRet("boo", Coalesce(zeroMatters: false, Nully0,   "boo"    ));
        NoNullRet("boo", Coalesce(             false, Nully0,   "boo"    ));
        NoNullRet("0",   Coalesce(zeroMatters,        Nully0,   "boo"    ));
        NoNullRet("0",   Coalesce(zeroMatters: true,  Nully0,   "boo"    ));
        NoNullRet("0",   Coalesce(             true,  Nully0,   "boo"    ));
        NoNullRet("1",   Coalesce(zeroMatters: false, Nully1,    NullText));
        NoNullRet("1",   Coalesce(             false, Nully1,    NullText));
        NoNullRet("1",   Coalesce(zeroMatters,        Nully1,    NullText));
        NoNullRet("1",   Coalesce(zeroMatters: true,  Nully1,    NullText));
        NoNullRet("1",   Coalesce(             true,  Nully1,    NullText));
        NoNullRet("1",   Coalesce(zeroMatters: false, Nully1,   "boo"    ));
        NoNullRet("1",   Coalesce(             false, Nully1,   "boo"    ));
        NoNullRet("1",   Coalesce(zeroMatters,        Nully1,   "boo"    ));
        NoNullRet("1",   Coalesce(zeroMatters: true,  Nully1,   "boo"    ));
        NoNullRet("1",   Coalesce(             true,  Nully1,   "boo"    ));
        NoNullRet("",    NullNum.Coalesce(zeroMatters: false,   NullText ));
        NoNullRet("",    NullNum.Coalesce(             false,   NullText ));
        NoNullRet("",    NullNum.Coalesce(zeroMatters,          NullText ));
        NoNullRet("",    NullNum.Coalesce(zeroMatters: true,    NullText ));
        NoNullRet("",    NullNum.Coalesce(             true,    NullText ));
        NoNullRet("boo", NullNum.Coalesce(zeroMatters: false,  "boo"     ));
        NoNullRet("boo", NullNum.Coalesce(             false,  "boo"     ));
        NoNullRet("boo", NullNum.Coalesce(zeroMatters,         "boo"     ));
        NoNullRet("boo", NullNum.Coalesce(zeroMatters: true,   "boo"     ));
        NoNullRet("boo", NullNum.Coalesce(             true,   "boo"     ));
        NoNullRet("",    Nully0 .Coalesce(zeroMatters: false,   NullText ));
        NoNullRet("",    Nully0 .Coalesce(             false,   NullText ));
        NoNullRet("0",   Nully0 .Coalesce(zeroMatters,          NullText ));
        NoNullRet("0",   Nully0 .Coalesce(zeroMatters: true,    NullText ));
        NoNullRet("0",   Nully0 .Coalesce(             true,    NullText ));
        NoNullRet("boo", Nully0 .Coalesce(zeroMatters: false,  "boo"     ));
        NoNullRet("boo", Nully0 .Coalesce(             false,  "boo"     ));
        NoNullRet("0",   Nully0 .Coalesce(zeroMatters,         "boo"     ));
        NoNullRet("0",   Nully0 .Coalesce(zeroMatters: true,   "boo"     ));
        NoNullRet("0",   Nully0 .Coalesce(             true,   "boo"     ));
        NoNullRet("1",   Nully1 .Coalesce(zeroMatters: false,   NullText ));
        NoNullRet("1",   Nully1 .Coalesce(             false,   NullText ));
        NoNullRet("1",   Nully1 .Coalesce(zeroMatters,          NullText ));
        NoNullRet("1",   Nully1 .Coalesce(zeroMatters: true,    NullText ));
        NoNullRet("1",   Nully1 .Coalesce(             true,    NullText ));
        NoNullRet("1",   Nully1 .Coalesce(zeroMatters: false,  "boo"     ));
        NoNullRet("1",   Nully1 .Coalesce(             false,  "boo"     ));
        NoNullRet("1",   Nully1 .Coalesce(zeroMatters,         "boo"     ));
        NoNullRet("1",   Nully1 .Coalesce(zeroMatters: true,   "boo"     ));
        NoNullRet("1",   Nully1 .Coalesce(             true,   "boo"     ));
    }
}