namespace JJ.Framework.Existence.Core.Tests;

[TestClass]
public class Coalesce_3Args_StringBuilderToText : TestBase
{
    // TODO: Adjust this copied code to StringBuilder handling.
    
    public static StringBuilder? NullSB = null;
    public static StringBuilder  EmptySB = new("");
    public static StringBuilder? NullyEmptySB = EmptySB;
    public static StringBuilder  FilledSB = new("FilledSB");
    public static StringBuilder? NullyFilledSB  = FilledSB;
    
  //public static StringBuilder? NullSB        = null;
  //public static StringBuilder  NewSB         = new();
  //public static StringBuilder? NullyNewSB    = NewSB;
  //public static StringBuilder  EmptySB       = new("");
  //public static StringBuilder? NullyEmptySB  = NullyEmptySB;
    public static StringBuilder  SpaceSB       = new(" ");
    public static StringBuilder? NullySpaceSB  = SpaceSB;
  //public static StringBuilder  FilledSB      = new("FilledSB");
  //public static StringBuilder? NullyFilledSB = FilledSB;

    [TestMethod]
    public void Coalesce_3Args_ValsToString_Static()
    {
        NoNullRet("",   Coalesce(NullSB, NullSB, NullText  ));
        NoNullRet("",   Coalesce(NullSB, NullSB, Empty     ));
        NoNullRet(" ",  Coalesce(NullSB, NullSB, Space     ));
        NoNullRet(Text, Coalesce(NullSB, NullSB, Text      ));
        NoNullRet("",   Coalesce(NullSB, NullSB, NullyEmpty));
        NoNullRet(" ",  Coalesce(NullSB, NullSB, NullySpace));
        NoNullRet(Text, Coalesce(NullSB, NullSB, NullyText ));
        NoNullRet("",   Coalesce(NullSB,  NullyEmptySB, NullText  ));
        NoNullRet("",   Coalesce(NullSB,  NullyEmptySB, Empty     ));
        NoNullRet(" ",  Coalesce(NullSB,  NullyEmptySB, Space     ));
        NoNullRet(Text, Coalesce(NullSB,  NullyEmptySB, Text      ));
        NoNullRet("",   Coalesce(NullSB,  NullyEmptySB, NullyEmpty));
        NoNullRet(" ",  Coalesce(NullSB,  NullyEmptySB, NullySpace));
        NoNullRet(Text, Coalesce(NullSB,  NullyEmptySB, NullyText ));
        NoNullRet("FilledSB",  Coalesce(NullSB,  NullyFilledSB, NullText  ));
        NoNullRet("FilledSB",  Coalesce(NullSB,  NullyFilledSB, Empty     ));
        NoNullRet("FilledSB",  Coalesce(NullSB,  NullyFilledSB, Space     ));
        NoNullRet("FilledSB",  Coalesce(NullSB,  NullyFilledSB, Text      ));
        NoNullRet("FilledSB",  Coalesce(NullSB,  NullyFilledSB, NullyEmpty));
        NoNullRet("FilledSB",  Coalesce(NullSB,  NullyFilledSB, NullySpace));
        NoNullRet("FilledSB",  Coalesce(NullSB,  NullyFilledSB, NullyText ));
        NoNullRet("",   Coalesce(NullSB,       EmptySB, NullText  ));
        NoNullRet("",   Coalesce(NullSB,       EmptySB, Empty     ));
        NoNullRet(" ",  Coalesce(NullSB,       EmptySB, Space     ));
        NoNullRet(Text, Coalesce(NullSB,       EmptySB, Text      ));
        NoNullRet("",   Coalesce(NullSB,       EmptySB, NullyEmpty));
        NoNullRet(" ",  Coalesce(NullSB,       EmptySB, NullySpace));
        NoNullRet(Text, Coalesce(NullSB,       EmptySB, NullyText ));
        NoNullRet("FilledSB",  Coalesce(NullSB,       FilledSB, NullText  ));
        NoNullRet("FilledSB",  Coalesce(NullSB,       FilledSB, Empty     ));
        NoNullRet("FilledSB",  Coalesce(NullSB,       FilledSB, Space     ));
        NoNullRet("FilledSB",  Coalesce(NullSB,       FilledSB, Text      ));
        NoNullRet("FilledSB",  Coalesce(NullSB,       FilledSB, NullyEmpty));
        NoNullRet("FilledSB",  Coalesce(NullSB,       FilledSB, NullySpace));
        NoNullRet("FilledSB",  Coalesce(NullSB,       FilledSB, NullyText ));
        
        NoNullRet("",   Coalesce(NullyEmptySB,  NullSB, NullText  ));
        NoNullRet("",   Coalesce(NullyEmptySB,  NullSB, Empty     ));
        NoNullRet(" ",  Coalesce(NullyEmptySB,  NullSB, Space     ));
        NoNullRet(Text, Coalesce(NullyEmptySB,  NullSB, Text      ));
        NoNullRet("",   Coalesce(NullyEmptySB,  NullSB, NullyEmpty));
        NoNullRet(" ",  Coalesce(NullyEmptySB,  NullSB, NullySpace));
        NoNullRet(Text, Coalesce(NullyEmptySB,  NullSB, NullyText ));
        NoNullRet("",   Coalesce(NullyEmptySB,   NullyEmptySB, NullText  ));
        NoNullRet("",   Coalesce(NullyEmptySB,   NullyEmptySB, Empty     ));
        NoNullRet(" ",  Coalesce(NullyEmptySB,   NullyEmptySB, Space     ));
        NoNullRet(Text, Coalesce(NullyEmptySB,   NullyEmptySB, Text      ));
        NoNullRet("",   Coalesce(NullyEmptySB,   NullyEmptySB, NullyEmpty));
        NoNullRet(" ",  Coalesce(NullyEmptySB,   NullyEmptySB, NullySpace));
        NoNullRet(Text, Coalesce(NullyEmptySB,   NullyEmptySB, NullyText ));
        NoNullRet("FilledSB",  Coalesce(NullyEmptySB,   NullyFilledSB, NullText  ));
        NoNullRet("FilledSB",  Coalesce(NullyEmptySB,   NullyFilledSB, Empty     ));
        NoNullRet("FilledSB",  Coalesce(NullyEmptySB,   NullyFilledSB, Space     ));
        NoNullRet("FilledSB",  Coalesce(NullyEmptySB,   NullyFilledSB, Text      ));
        NoNullRet("FilledSB",  Coalesce(NullyEmptySB,   NullyFilledSB, NullyEmpty));
        NoNullRet("FilledSB",  Coalesce(NullyEmptySB,   NullyFilledSB, NullySpace));
        NoNullRet("FilledSB",  Coalesce(NullyEmptySB,   NullyFilledSB, NullyText ));
        NoNullRet("",   Coalesce(NullyEmptySB,        EmptySB, NullText  ));
        NoNullRet("",   Coalesce(NullyEmptySB,        EmptySB, Empty     ));
        NoNullRet(" ",  Coalesce(NullyEmptySB,        EmptySB, Space     ));
        NoNullRet(Text, Coalesce(NullyEmptySB,        EmptySB, Text      ));
        NoNullRet("",   Coalesce(NullyEmptySB,        EmptySB, NullyEmpty));
        NoNullRet(" ",  Coalesce(NullyEmptySB,        EmptySB, NullySpace));
        NoNullRet(Text, Coalesce(NullyEmptySB,        EmptySB, NullyText ));
        NoNullRet("FilledSB",  Coalesce(NullyEmptySB,        FilledSB, NullText  ));
        NoNullRet("FilledSB",  Coalesce(NullyEmptySB,        FilledSB, Empty     ));
        NoNullRet("FilledSB",  Coalesce(NullyEmptySB,        FilledSB, Space     ));
        NoNullRet("FilledSB",  Coalesce(NullyEmptySB,        FilledSB, Text      ));
        NoNullRet("FilledSB",  Coalesce(NullyEmptySB,        FilledSB, NullyEmpty));
        NoNullRet("FilledSB",  Coalesce(NullyEmptySB,        FilledSB, NullySpace));
        NoNullRet("FilledSB",  Coalesce(NullyEmptySB,        FilledSB, NullyText ));
        
        NoNullRet("FilledSB",  Coalesce(NullyFilledSB,  NullSB, NullText  ));
        NoNullRet("FilledSB",  Coalesce(NullyFilledSB,  NullSB, Empty     ));
        NoNullRet("FilledSB",  Coalesce(NullyFilledSB,  NullSB, Space     ));
        NoNullRet("FilledSB",  Coalesce(NullyFilledSB,  NullSB, Text      ));
        NoNullRet("FilledSB",  Coalesce(NullyFilledSB,  NullSB, NullyEmpty));
        NoNullRet("FilledSB",  Coalesce(NullyFilledSB,  NullSB, NullySpace));
        NoNullRet("FilledSB",  Coalesce(NullyFilledSB,  NullSB, NullyText ));
        NoNullRet("FilledSB",  Coalesce(NullyFilledSB,   NullyEmptySB, NullText  ));
        NoNullRet("FilledSB",  Coalesce(NullyFilledSB,   NullyEmptySB, Empty     ));
        NoNullRet("FilledSB",  Coalesce(NullyFilledSB,   NullyEmptySB, Space     ));
        NoNullRet("FilledSB",  Coalesce(NullyFilledSB,   NullyEmptySB, Text      ));
        NoNullRet("FilledSB",  Coalesce(NullyFilledSB,   NullyEmptySB, NullyEmpty));
        NoNullRet("FilledSB",  Coalesce(NullyFilledSB,   NullyEmptySB, NullySpace));
        NoNullRet("FilledSB",  Coalesce(NullyFilledSB,   NullyEmptySB, NullyText ));
        NoNullRet("FilledSB",  Coalesce(NullyFilledSB,   NullyFilledSB, NullText  ));
        NoNullRet("FilledSB",  Coalesce(NullyFilledSB,   NullyFilledSB, Empty     ));
        NoNullRet("FilledSB",  Coalesce(NullyFilledSB,   NullyFilledSB, Space     ));
        NoNullRet("FilledSB",  Coalesce(NullyFilledSB,   NullyFilledSB, Text      ));
        NoNullRet("FilledSB",  Coalesce(NullyFilledSB,   NullyFilledSB, NullyEmpty));
        NoNullRet("FilledSB",  Coalesce(NullyFilledSB,   NullyFilledSB, NullySpace));
        NoNullRet("FilledSB",  Coalesce(NullyFilledSB,   NullyFilledSB, NullyText ));
        NoNullRet("FilledSB",  Coalesce(NullyFilledSB,        EmptySB, NullText  ));
        NoNullRet("FilledSB",  Coalesce(NullyFilledSB,        EmptySB, Empty     ));
        NoNullRet("FilledSB",  Coalesce(NullyFilledSB,        EmptySB, Space     ));
        NoNullRet("FilledSB",  Coalesce(NullyFilledSB,        EmptySB, Text      ));
        NoNullRet("FilledSB",  Coalesce(NullyFilledSB,        EmptySB, NullyEmpty));
        NoNullRet("FilledSB",  Coalesce(NullyFilledSB,        EmptySB, NullySpace));
        NoNullRet("FilledSB",  Coalesce(NullyFilledSB,        EmptySB, NullyText ));
        NoNullRet("FilledSB",  Coalesce(NullyFilledSB,        FilledSB, NullText  ));
        NoNullRet("FilledSB",  Coalesce(NullyFilledSB,        FilledSB, Empty     ));
        NoNullRet("FilledSB",  Coalesce(NullyFilledSB,        FilledSB, Space     ));
        NoNullRet("FilledSB",  Coalesce(NullyFilledSB,        FilledSB, Text      ));
        NoNullRet("FilledSB",  Coalesce(NullyFilledSB,        FilledSB, NullyEmpty));
        NoNullRet("FilledSB",  Coalesce(NullyFilledSB,        FilledSB, NullySpace));
        NoNullRet("FilledSB",  Coalesce(NullyFilledSB,        FilledSB, NullyText ));
        
        NoNullRet("",   Coalesce(EmptySB,       NullSB, NullText  ));
        NoNullRet("",   Coalesce(EmptySB,       NullSB, Empty     ));
        NoNullRet(" ",  Coalesce(EmptySB,       NullSB, Space     ));
        NoNullRet(Text, Coalesce(EmptySB,       NullSB, Text      ));
        NoNullRet("",   Coalesce(EmptySB,       NullSB, NullyEmpty));
        NoNullRet(" ",  Coalesce(EmptySB,       NullSB, NullySpace));
        NoNullRet(Text, Coalesce(EmptySB,       NullSB, NullyText ));
        NoNullRet("",   Coalesce(EmptySB,        NullyEmptySB, NullText  ));
        NoNullRet("",   Coalesce(EmptySB,        NullyEmptySB, Empty     ));
        NoNullRet(" ",  Coalesce(EmptySB,        NullyEmptySB, Space     ));
        NoNullRet(Text, Coalesce(EmptySB,        NullyEmptySB, Text      ));
        NoNullRet("",   Coalesce(EmptySB,        NullyEmptySB, NullyEmpty));
        NoNullRet(" ",  Coalesce(EmptySB,        NullyEmptySB, NullySpace));
        NoNullRet(Text, Coalesce(EmptySB,        NullyEmptySB, NullyText ));
        NoNullRet("FilledSB",  Coalesce(EmptySB,        NullyFilledSB, NullText  ));
        NoNullRet("FilledSB",  Coalesce(EmptySB,        NullyFilledSB, Empty     ));
        NoNullRet("FilledSB",  Coalesce(EmptySB,        NullyFilledSB, Space     ));
        NoNullRet("FilledSB",  Coalesce(EmptySB,        NullyFilledSB, Text      ));
        NoNullRet("FilledSB",  Coalesce(EmptySB,        NullyFilledSB, NullyEmpty));
        NoNullRet("FilledSB",  Coalesce(EmptySB,        NullyFilledSB, NullySpace));
        NoNullRet("FilledSB",  Coalesce(EmptySB,        NullyFilledSB, NullyText ));
        NoNullRet("",   Coalesce(EmptySB,             EmptySB, NullText  ));
        NoNullRet("",   Coalesce(EmptySB,             EmptySB, Empty     ));
        NoNullRet(" ",  Coalesce(EmptySB,             EmptySB, Space     ));
        NoNullRet(Text, Coalesce(EmptySB,             EmptySB, Text      ));
        NoNullRet("",   Coalesce(EmptySB,             EmptySB, NullyEmpty));
        NoNullRet(" ",  Coalesce(EmptySB,             EmptySB, NullySpace));
        NoNullRet(Text, Coalesce(EmptySB,             EmptySB, NullyText ));
        NoNullRet("FilledSB",  Coalesce(EmptySB,             FilledSB, NullText  ));
        NoNullRet("FilledSB",  Coalesce(EmptySB,             FilledSB, Empty     ));
        NoNullRet("FilledSB",  Coalesce(EmptySB,             FilledSB, Space     ));
        NoNullRet("FilledSB",  Coalesce(EmptySB,             FilledSB, Text      ));
        NoNullRet("FilledSB",  Coalesce(EmptySB,             FilledSB, NullyEmpty));
        NoNullRet("FilledSB",  Coalesce(EmptySB,             FilledSB, NullySpace));
        NoNullRet("FilledSB",  Coalesce(EmptySB,             FilledSB, NullyText ));
        
        NoNullRet("FilledSB",  Coalesce(FilledSB,       NullSB, NullText  ));
        NoNullRet("FilledSB",  Coalesce(FilledSB,       NullSB, Empty     ));
        NoNullRet("FilledSB",  Coalesce(FilledSB,       NullSB, Space     ));
        NoNullRet("FilledSB",  Coalesce(FilledSB,       NullSB, Text      ));
        NoNullRet("FilledSB",  Coalesce(FilledSB,       NullSB, NullyEmpty));
        NoNullRet("FilledSB",  Coalesce(FilledSB,       NullSB, NullySpace));
        NoNullRet("FilledSB",  Coalesce(FilledSB,       NullSB, NullyText ));
        NoNullRet("FilledSB",  Coalesce(FilledSB,        NullyEmptySB, NullText  ));
        NoNullRet("FilledSB",  Coalesce(FilledSB,        NullyEmptySB, Empty     ));
        NoNullRet("FilledSB",  Coalesce(FilledSB,        NullyEmptySB, Space     ));
        NoNullRet("FilledSB",  Coalesce(FilledSB,        NullyEmptySB, Text      ));
        NoNullRet("FilledSB",  Coalesce(FilledSB,        NullyEmptySB, NullyEmpty));
        NoNullRet("FilledSB",  Coalesce(FilledSB,        NullyEmptySB, NullySpace));
        NoNullRet("FilledSB",  Coalesce(FilledSB,        NullyEmptySB, NullyText ));
        NoNullRet("FilledSB",  Coalesce(FilledSB,        NullyFilledSB, NullText  ));
        NoNullRet("FilledSB",  Coalesce(FilledSB,        NullyFilledSB, Empty     ));
        NoNullRet("FilledSB",  Coalesce(FilledSB,        NullyFilledSB, Space     ));
        NoNullRet("FilledSB",  Coalesce(FilledSB,        NullyFilledSB, Text      ));
        NoNullRet("FilledSB",  Coalesce(FilledSB,        NullyFilledSB, NullyEmpty));
        NoNullRet("FilledSB",  Coalesce(FilledSB,        NullyFilledSB, NullySpace));
        NoNullRet("FilledSB",  Coalesce(FilledSB,        NullyFilledSB, NullyText ));
        NoNullRet("FilledSB",  Coalesce(FilledSB,             EmptySB, Empty     ));
        NoNullRet("FilledSB",  Coalesce(FilledSB,             EmptySB, Space     ));
        NoNullRet("FilledSB",  Coalesce(FilledSB,             EmptySB, Text      ));
        NoNullRet("FilledSB",  Coalesce(FilledSB,             EmptySB, NullyEmpty));
        NoNullRet("FilledSB",  Coalesce(FilledSB,             EmptySB, NullySpace));
        NoNullRet("FilledSB",  Coalesce(FilledSB,             EmptySB, NullyText ));
        NoNullRet("FilledSB",  Coalesce(FilledSB,             FilledSB, NullText  ));
        NoNullRet("FilledSB",  Coalesce(FilledSB,             FilledSB, Empty     ));
        NoNullRet("FilledSB",  Coalesce(FilledSB,             FilledSB, Space     ));
        NoNullRet("FilledSB",  Coalesce(FilledSB,             FilledSB, Text      ));
        NoNullRet("FilledSB",  Coalesce(FilledSB,             FilledSB, NullyEmpty));
        NoNullRet("FilledSB",  Coalesce(FilledSB,             FilledSB, NullySpace));
        NoNullRet("FilledSB",  Coalesce(FilledSB,             FilledSB, NullyText ));

    }


    [TestMethod]
    public void Coalesce_3Args_ValsToString_Extensions()
    {
        // Example
        NoNullRet("FilledSB", NullyFilledSB.Coalesce(NullSB, NullText));
        NoNullRet(Text, EmptySB.Coalesce(NullSB, Text));
        
        NoNullRet("",   NullSB.Coalesce(NullSB, NullText  ));
        NoNullRet("",   NullSB.Coalesce(NullSB, Empty     ));
        NoNullRet(" ",  NullSB.Coalesce(NullSB, Space     ));
        NoNullRet(Text, NullSB.Coalesce(NullSB, Text      ));
        NoNullRet("",   NullSB.Coalesce(NullSB, NullyEmpty));
        NoNullRet(" ",  NullSB.Coalesce(NullSB, NullySpace));
        NoNullRet(Text, NullSB.Coalesce(NullSB, NullyText ));
        NoNullRet("",   NullSB.Coalesce( NullyEmptySB, NullText  ));
        NoNullRet("",   NullSB.Coalesce( NullyEmptySB, Empty     ));
        NoNullRet(" ",  NullSB.Coalesce( NullyEmptySB, Space     ));
        NoNullRet(Text, NullSB.Coalesce( NullyEmptySB, Text      ));
        NoNullRet("",   NullSB.Coalesce( NullyEmptySB, NullyEmpty));
        NoNullRet(" ",  NullSB.Coalesce( NullyEmptySB, NullySpace));
        NoNullRet(Text, NullSB.Coalesce( NullyEmptySB, NullyText ));
        NoNullRet("FilledSB",  NullSB.Coalesce( NullyFilledSB, NullText  ));
        NoNullRet("FilledSB",  NullSB.Coalesce( NullyFilledSB, Empty     ));
        NoNullRet("FilledSB",  NullSB.Coalesce( NullyFilledSB, Space     ));
        NoNullRet("FilledSB",  NullSB.Coalesce( NullyFilledSB, Text      ));
        NoNullRet("FilledSB",  NullSB.Coalesce( NullyFilledSB, NullyEmpty));
        NoNullRet("FilledSB",  NullSB.Coalesce( NullyFilledSB, NullySpace));
        NoNullRet("FilledSB",  NullSB.Coalesce( NullyFilledSB, NullyText ));
        NoNullRet("",   NullSB.Coalesce(      EmptySB, NullText  ));
        NoNullRet("",   NullSB.Coalesce(      EmptySB, Empty     ));
        NoNullRet(" ",  NullSB.Coalesce(      EmptySB, Space     ));
        NoNullRet(Text, NullSB.Coalesce(      EmptySB, Text      ));
        NoNullRet("",   NullSB.Coalesce(      EmptySB, NullyEmpty));
        NoNullRet(" ",  NullSB.Coalesce(      EmptySB, NullySpace));
        NoNullRet(Text, NullSB.Coalesce(      EmptySB, NullyText ));
        NoNullRet("FilledSB",  NullSB.Coalesce(      FilledSB, NullText  ));
        NoNullRet("FilledSB",  NullSB.Coalesce(      FilledSB, Empty     ));
        NoNullRet("FilledSB",  NullSB.Coalesce(      FilledSB, Space     ));
        NoNullRet("FilledSB",  NullSB.Coalesce(      FilledSB, Text      ));
        NoNullRet("FilledSB",  NullSB.Coalesce(      FilledSB, NullyEmpty));
        NoNullRet("FilledSB",  NullSB.Coalesce(      FilledSB, NullySpace));
        NoNullRet("FilledSB",  NullSB.Coalesce(      FilledSB, NullyText ));
        
        NoNullRet("",    NullyEmptySB.Coalesce(NullSB, NullText  ));
        NoNullRet("",    NullyEmptySB.Coalesce(NullSB, Empty     ));
        NoNullRet(" ",   NullyEmptySB.Coalesce(NullSB, Space     ));
        NoNullRet(Text,  NullyEmptySB.Coalesce(NullSB, Text      ));
        NoNullRet("",    NullyEmptySB.Coalesce(NullSB, NullyEmpty));
        NoNullRet(" ",   NullyEmptySB.Coalesce(NullSB, NullySpace));
        NoNullRet(Text,  NullyEmptySB.Coalesce(NullSB, NullyText ));
        NoNullRet("",    NullyEmptySB.Coalesce( NullyEmptySB, NullText  ));
        NoNullRet("",    NullyEmptySB.Coalesce( NullyEmptySB, Empty     ));
        NoNullRet(" ",   NullyEmptySB.Coalesce( NullyEmptySB, Space     ));
        NoNullRet(Text,  NullyEmptySB.Coalesce( NullyEmptySB, Text      ));
        NoNullRet("",    NullyEmptySB.Coalesce( NullyEmptySB, NullyEmpty));
        NoNullRet(" ",   NullyEmptySB.Coalesce( NullyEmptySB, NullySpace));
        NoNullRet(Text,  NullyEmptySB.Coalesce( NullyEmptySB, NullyText ));
        NoNullRet("FilledSB",   NullyEmptySB.Coalesce( NullyFilledSB, NullText  ));
        NoNullRet("FilledSB",   NullyEmptySB.Coalesce( NullyFilledSB, Empty     ));
        NoNullRet("FilledSB",   NullyEmptySB.Coalesce( NullyFilledSB, Space     ));
        NoNullRet("FilledSB",   NullyEmptySB.Coalesce( NullyFilledSB, Text      ));
        NoNullRet("FilledSB",   NullyEmptySB.Coalesce( NullyFilledSB, NullyEmpty));
        NoNullRet("FilledSB",   NullyEmptySB.Coalesce( NullyFilledSB, NullySpace));
        NoNullRet("FilledSB",   NullyEmptySB.Coalesce( NullyFilledSB, NullyText ));
        NoNullRet("",    NullyEmptySB.Coalesce(      EmptySB, NullText  ));
        NoNullRet("",    NullyEmptySB.Coalesce(      EmptySB, Empty     ));
        NoNullRet(" ",   NullyEmptySB.Coalesce(      EmptySB, Space     ));
        NoNullRet(Text,  NullyEmptySB.Coalesce(      EmptySB, Text      ));
        NoNullRet("",    NullyEmptySB.Coalesce(      EmptySB, NullyEmpty));
        NoNullRet(" ",   NullyEmptySB.Coalesce(      EmptySB, NullySpace));
        NoNullRet(Text,  NullyEmptySB.Coalesce(      EmptySB, NullyText ));
        NoNullRet("FilledSB",   NullyEmptySB.Coalesce(      FilledSB, NullText  ));
        NoNullRet("FilledSB",   NullyEmptySB.Coalesce(      FilledSB, Empty     ));
        NoNullRet("FilledSB",   NullyEmptySB.Coalesce(      FilledSB, Space     ));
        NoNullRet("FilledSB",   NullyEmptySB.Coalesce(      FilledSB, Text      ));
        NoNullRet("FilledSB",   NullyEmptySB.Coalesce(      FilledSB, NullyEmpty));
        NoNullRet("FilledSB",   NullyEmptySB.Coalesce(      FilledSB, NullySpace));
        NoNullRet("FilledSB",   NullyEmptySB.Coalesce(      FilledSB, NullyText ));
        
        NoNullRet("FilledSB",   NullyFilledSB.Coalesce(NullSB, NullText  ));
        NoNullRet("FilledSB",   NullyFilledSB.Coalesce(NullSB, Empty     ));
        NoNullRet("FilledSB",   NullyFilledSB.Coalesce(NullSB, Space     ));
        NoNullRet("FilledSB",   NullyFilledSB.Coalesce(NullSB, Text      ));
        NoNullRet("FilledSB",   NullyFilledSB.Coalesce(NullSB, NullyEmpty));
        NoNullRet("FilledSB",   NullyFilledSB.Coalesce(NullSB, NullySpace));
        NoNullRet("FilledSB",   NullyFilledSB.Coalesce(NullSB, NullyText ));
        NoNullRet("FilledSB",   NullyFilledSB.Coalesce( NullyEmptySB, NullText  ));
        NoNullRet("FilledSB",   NullyFilledSB.Coalesce( NullyEmptySB, Empty     ));
        NoNullRet("FilledSB",   NullyFilledSB.Coalesce( NullyEmptySB, Space     ));
        NoNullRet("FilledSB",   NullyFilledSB.Coalesce( NullyEmptySB, Text      ));
        NoNullRet("FilledSB",   NullyFilledSB.Coalesce( NullyEmptySB, NullyEmpty));
        NoNullRet("FilledSB",   NullyFilledSB.Coalesce( NullyEmptySB, NullySpace));
        NoNullRet("FilledSB",   NullyFilledSB.Coalesce( NullyEmptySB, NullyText ));
        NoNullRet("FilledSB",   NullyFilledSB.Coalesce( NullyFilledSB, NullText  ));
        NoNullRet("FilledSB",   NullyFilledSB.Coalesce( NullyFilledSB, Empty     ));
        NoNullRet("FilledSB",   NullyFilledSB.Coalesce( NullyFilledSB, Space     ));
        NoNullRet("FilledSB",   NullyFilledSB.Coalesce( NullyFilledSB, Text      ));
        NoNullRet("FilledSB",   NullyFilledSB.Coalesce( NullyFilledSB, NullyEmpty));
        NoNullRet("FilledSB",   NullyFilledSB.Coalesce( NullyFilledSB, NullySpace));
        NoNullRet("FilledSB",   NullyFilledSB.Coalesce( NullyFilledSB, NullyText ));
        NoNullRet("FilledSB",   NullyFilledSB.Coalesce(      EmptySB, NullText  ));
        NoNullRet("FilledSB",   NullyFilledSB.Coalesce(      EmptySB, Empty     ));
        NoNullRet("FilledSB",   NullyFilledSB.Coalesce(      EmptySB, Space     ));
        NoNullRet("FilledSB",   NullyFilledSB.Coalesce(      EmptySB, Text      ));
        NoNullRet("FilledSB",   NullyFilledSB.Coalesce(      EmptySB, NullyEmpty));
        NoNullRet("FilledSB",   NullyFilledSB.Coalesce(      EmptySB, NullySpace));
        NoNullRet("FilledSB",   NullyFilledSB.Coalesce(      EmptySB, NullyText ));
        NoNullRet("FilledSB",   NullyFilledSB.Coalesce(      FilledSB, NullText  ));
        NoNullRet("FilledSB",   NullyFilledSB.Coalesce(      FilledSB, Empty     ));
        NoNullRet("FilledSB",   NullyFilledSB.Coalesce(      FilledSB, Space     ));
        NoNullRet("FilledSB",   NullyFilledSB.Coalesce(      FilledSB, Text      ));
        NoNullRet("FilledSB",   NullyFilledSB.Coalesce(      FilledSB, NullyEmpty));
        NoNullRet("FilledSB",   NullyFilledSB.Coalesce(      FilledSB, NullySpace));
        NoNullRet("FilledSB",   NullyFilledSB.Coalesce(      FilledSB, NullyText ));
        
        NoNullRet("",         EmptySB.Coalesce(NullSB, NullText  ));
        NoNullRet("",         EmptySB.Coalesce(NullSB, Empty     ));
        NoNullRet(" ",        EmptySB.Coalesce(NullSB, Space     ));
        NoNullRet(Text,       EmptySB.Coalesce(NullSB, Text      ));
        NoNullRet("",         EmptySB.Coalesce(NullSB, NullyEmpty));
        NoNullRet(" ",        EmptySB.Coalesce(NullSB, NullySpace));
        NoNullRet(Text,       EmptySB.Coalesce(NullSB, NullyText ));
        NoNullRet("",         EmptySB.Coalesce( NullyEmptySB, NullText  ));
        NoNullRet("",         EmptySB.Coalesce( NullyEmptySB, Empty     ));
        NoNullRet(" ",        EmptySB.Coalesce( NullyEmptySB, Space     ));
        NoNullRet(Text,       EmptySB.Coalesce( NullyEmptySB, Text      ));
        NoNullRet("",         EmptySB.Coalesce( NullyEmptySB, NullyEmpty));
        NoNullRet(" ",        EmptySB.Coalesce( NullyEmptySB, NullySpace));
        NoNullRet(Text,       EmptySB.Coalesce( NullyEmptySB, NullyText ));
        NoNullRet("FilledSB",        EmptySB.Coalesce( NullyFilledSB, NullText  ));
        NoNullRet("FilledSB",        EmptySB.Coalesce( NullyFilledSB, Empty     ));
        NoNullRet("FilledSB",        EmptySB.Coalesce( NullyFilledSB, Space     ));
        NoNullRet("FilledSB",        EmptySB.Coalesce( NullyFilledSB, Text      ));
        NoNullRet("FilledSB",        EmptySB.Coalesce( NullyFilledSB, NullyEmpty));
        NoNullRet("FilledSB",        EmptySB.Coalesce( NullyFilledSB, NullySpace));
        NoNullRet("FilledSB",        EmptySB.Coalesce( NullyFilledSB, NullyText ));
        NoNullRet("",         EmptySB.Coalesce(      EmptySB, NullText  ));
        NoNullRet("",         EmptySB.Coalesce(      EmptySB, Empty     ));
        NoNullRet(" ",        EmptySB.Coalesce(      EmptySB, Space     ));
        NoNullRet(Text,       EmptySB.Coalesce(      EmptySB, Text      ));
        NoNullRet("",         EmptySB.Coalesce(      EmptySB, NullyEmpty));
        NoNullRet(" ",        EmptySB.Coalesce(      EmptySB, NullySpace));
        NoNullRet(Text,       EmptySB.Coalesce(      EmptySB, NullyText ));
        NoNullRet("FilledSB",        EmptySB.Coalesce(      FilledSB, NullText  ));
        NoNullRet("FilledSB",        EmptySB.Coalesce(      FilledSB, Empty     ));
        NoNullRet("FilledSB",        EmptySB.Coalesce(      FilledSB, Space     ));
        NoNullRet("FilledSB",        EmptySB.Coalesce(      FilledSB, Text      ));
        NoNullRet("FilledSB",        EmptySB.Coalesce(      FilledSB, NullyEmpty));
        NoNullRet("FilledSB",        EmptySB.Coalesce(      FilledSB, NullySpace));
        NoNullRet("FilledSB",        EmptySB.Coalesce(      FilledSB, NullyText ));
        
        NoNullRet("FilledSB",        FilledSB.Coalesce(NullSB, NullText  ));
        NoNullRet("FilledSB",        FilledSB.Coalesce(NullSB, Empty     ));
        NoNullRet("FilledSB",        FilledSB.Coalesce(NullSB, Space     ));
        NoNullRet("FilledSB",        FilledSB.Coalesce(NullSB, Text      ));
        NoNullRet("FilledSB",        FilledSB.Coalesce(NullSB, NullyEmpty));
        NoNullRet("FilledSB",        FilledSB.Coalesce(NullSB, NullySpace));
        NoNullRet("FilledSB",        FilledSB.Coalesce(NullSB, NullyText ));
        NoNullRet("FilledSB",        FilledSB.Coalesce( NullyEmptySB, NullText  ));
        NoNullRet("FilledSB",        FilledSB.Coalesce( NullyEmptySB, Empty     ));
        NoNullRet("FilledSB",        FilledSB.Coalesce( NullyEmptySB, Space     ));
        NoNullRet("FilledSB",        FilledSB.Coalesce( NullyEmptySB, Text      ));
        NoNullRet("FilledSB",        FilledSB.Coalesce( NullyEmptySB, NullyEmpty));
        NoNullRet("FilledSB",        FilledSB.Coalesce( NullyEmptySB, NullySpace));
        NoNullRet("FilledSB",        FilledSB.Coalesce( NullyEmptySB, NullyText ));
        NoNullRet("FilledSB",        FilledSB.Coalesce( NullyFilledSB, NullText  ));
        NoNullRet("FilledSB",        FilledSB.Coalesce( NullyFilledSB, Empty     ));
        NoNullRet("FilledSB",        FilledSB.Coalesce( NullyFilledSB, Space     ));
        NoNullRet("FilledSB",        FilledSB.Coalesce( NullyFilledSB, Text      ));
        NoNullRet("FilledSB",        FilledSB.Coalesce( NullyFilledSB, NullyEmpty));
        NoNullRet("FilledSB",        FilledSB.Coalesce( NullyFilledSB, NullySpace));
        NoNullRet("FilledSB",        FilledSB.Coalesce( NullyFilledSB, NullyText ));
        NoNullRet("FilledSB",        FilledSB.Coalesce(      EmptySB, Empty     ));
        NoNullRet("FilledSB",        FilledSB.Coalesce(      EmptySB, Space     ));
        NoNullRet("FilledSB",        FilledSB.Coalesce(      EmptySB, Text      ));
        NoNullRet("FilledSB",        FilledSB.Coalesce(      EmptySB, NullyEmpty));
        NoNullRet("FilledSB",        FilledSB.Coalesce(      EmptySB, NullySpace));
        NoNullRet("FilledSB",        FilledSB.Coalesce(      EmptySB, NullyText ));
        NoNullRet("FilledSB",        FilledSB.Coalesce(      FilledSB, NullText  ));
        NoNullRet("FilledSB",        FilledSB.Coalesce(      FilledSB, Empty     ));
        NoNullRet("FilledSB",        FilledSB.Coalesce(      FilledSB, Space     ));
        NoNullRet("FilledSB",        FilledSB.Coalesce(      FilledSB, Text      ));
        NoNullRet("FilledSB",        FilledSB.Coalesce(      FilledSB, NullyEmpty));
        NoNullRet("FilledSB",        FilledSB.Coalesce(      FilledSB, NullySpace));
        NoNullRet("FilledSB",        FilledSB.Coalesce(      FilledSB, NullyText ));
    }
}