namespace JJ.Framework.Existence.Core.Tests;

// Should check:
// - [x] int
// - [x] int?
// - [x] string
// - [x] string?
// - [x] Reference Types (StringBuilder)
// - [x] Nullable reference types (StringBuilder?)
// - [x] ~ Coalescing from collection to collection
// - [x] Collection types
// - [x] Trim tolerance
// - [x] Static variant
// - [x] Extension variant
// - [ ] Enum
// - [ ] Enum?
// - [ ] double
// - [ ] bool
// - [ ] .. Coalesce arities

[TestClass]
public class CoalesceTests_Arity3
{
    [TestMethod]
    public void Test_Coalesce_Arity3_Text()
    {
        AreEqual("Hi!", Coalesce(" ", null, "Hi!"));
        AreEqual(" ",   Coalesce(" ", null, "Hi!", trimSpace: false));

        NoNullRet(NonNullEmpty, Coalesce(NullText,      NullText,      NullText     ));
        NoNullRet(NonNullEmpty, Coalesce(NullText,      NullText,      NullyEmpty   ));
        NoNullRet(NonNullSpace, Coalesce(NullText,      NullText,      NullySpace   ));
        NoNullRet(NonNullText,  Coalesce(NullText,      NullText,      NullyWithText));
        NoNullRet(NonNullEmpty, Coalesce(NullText,      NullText,      NonNullEmpty ));
        NoNullRet(NonNullSpace, Coalesce(NullText,      NullText,      NonNullSpace ));
        NoNullRet(NonNullText,  Coalesce(NullText,      NullText,      NonNullText  ));

        NoNullRet(null,         Coalesce(NullText,      NullyEmpty,    NullText     ));
        NoNullRet(null,         Coalesce(NullText,      NullyEmpty,    NullyEmpty   ));
        NoNullRet(null,         Coalesce(NullText,      NullyEmpty,    NullySpace   ));
        NoNullRet(null,         Coalesce(NullText,      NullyEmpty,    NullyWithText));
        NoNullRet(null,         Coalesce(NullText,      NullyEmpty,    NonNullEmpty ));
        NoNullRet(null,         Coalesce(NullText,      NullyEmpty,    NonNullSpace ));
        NoNullRet(null,         Coalesce(NullText,      NullyEmpty,    NonNullText  ));
        NoNullRet(null,         Coalesce(NullText,      NullySpace,    NullText     ));
        NoNullRet(null,         Coalesce(NullText,      NullySpace,    NullyEmpty   ));
        NoNullRet(null,         Coalesce(NullText,      NullySpace,    NullySpace   ));
        NoNullRet(null,         Coalesce(NullText,      NullySpace,    NullyWithText));
        NoNullRet(null,         Coalesce(NullText,      NullySpace,    NonNullEmpty ));
        NoNullRet(null,         Coalesce(NullText,      NullySpace,    NonNullSpace ));
        NoNullRet(null,         Coalesce(NullText,      NullySpace,    NonNullText  ));
        NoNullRet(null,         Coalesce(NullText,      NullyWithText, NullText     ));
        NoNullRet(null,         Coalesce(NullText,      NullyWithText, NullyEmpty   ));
        NoNullRet(null,         Coalesce(NullText,      NullyWithText, NullySpace   ));
        NoNullRet(null,         Coalesce(NullText,      NullyWithText, NullyWithText));
        NoNullRet(null,         Coalesce(NullText,      NullyWithText, NonNullEmpty ));
        NoNullRet(null,         Coalesce(NullText,      NullyWithText, NonNullSpace ));
        NoNullRet(null,         Coalesce(NullText,      NullyWithText, NonNullText  ));
        NoNullRet(null,         Coalesce(NullText,      NonNullEmpty,  NullText     ));
        NoNullRet(null,         Coalesce(NullText,      NonNullEmpty,  NullyEmpty   ));
        NoNullRet(null,         Coalesce(NullText,      NonNullEmpty,  NullySpace   ));
        NoNullRet(null,         Coalesce(NullText,      NonNullEmpty,  NullyWithText));
        NoNullRet(null,         Coalesce(NullText,      NonNullEmpty,  NonNullEmpty ));
        NoNullRet(null,         Coalesce(NullText,      NonNullEmpty,  NonNullSpace ));
        NoNullRet(null,         Coalesce(NullText,      NonNullEmpty,  NonNullText  ));
        NoNullRet(null,         Coalesce(NullText,      NonNullSpace,  NullText     ));
        NoNullRet(null,         Coalesce(NullText,      NonNullSpace,  NullyEmpty   ));
        NoNullRet(null,         Coalesce(NullText,      NonNullSpace,  NullySpace   ));
        NoNullRet(null,         Coalesce(NullText,      NonNullSpace,  NullyWithText));
        NoNullRet(null,         Coalesce(NullText,      NonNullSpace,  NonNullEmpty ));
        NoNullRet(null,         Coalesce(NullText,      NonNullSpace,  NonNullSpace ));
        NoNullRet(null,         Coalesce(NullText,      NonNullSpace,  NonNullText  ));
        NoNullRet(null,         Coalesce(NullText,      NonNullText,   NullText     ));
        NoNullRet(null,         Coalesce(NullText,      NonNullText,   NullyEmpty   ));
        NoNullRet(null,         Coalesce(NullText,      NonNullText,   NullySpace   ));
        NoNullRet(null,         Coalesce(NullText,      NonNullText,   NullyWithText));
        NoNullRet(null,         Coalesce(NullText,      NonNullText,   NonNullEmpty ));
        NoNullRet(null,         Coalesce(NullText,      NonNullText,   NonNullSpace ));
        NoNullRet(null,         Coalesce(NullText,      NonNullText,   NonNullText  ));
        
        NoNullRet(null,         Coalesce(NullyEmpty,    NullText,      NullText     ));
        NoNullRet(null,         Coalesce(NullyEmpty,    NullText,      NullyEmpty   ));
        NoNullRet(null,         Coalesce(NullyEmpty,    NullText,      NullySpace   ));
        NoNullRet(null,         Coalesce(NullyEmpty,    NullText,      NullyWithText));
        NoNullRet(null,         Coalesce(NullyEmpty,    NullText,      NonNullEmpty ));
        NoNullRet(null,         Coalesce(NullyEmpty,    NullText,      NonNullSpace ));
        NoNullRet(null,         Coalesce(NullyEmpty,    NullText,      NonNullText  ));
        NoNullRet(null,         Coalesce(NullyEmpty,    NullyEmpty,    NullText     ));
        NoNullRet(null,         Coalesce(NullyEmpty,    NullyEmpty,    NullyEmpty   ));
        NoNullRet(null,         Coalesce(NullyEmpty,    NullyEmpty,    NullySpace   ));
        NoNullRet(null,         Coalesce(NullyEmpty,    NullyEmpty,    NullyWithText));
        NoNullRet(null,         Coalesce(NullyEmpty,    NullyEmpty,    NonNullEmpty ));
        NoNullRet(null,         Coalesce(NullyEmpty,    NullyEmpty,    NonNullSpace ));
        NoNullRet(null,         Coalesce(NullyEmpty,    NullyEmpty,    NonNullText  ));
        NoNullRet(null,         Coalesce(NullyEmpty,    NullySpace,    NullText     ));
        NoNullRet(null,         Coalesce(NullyEmpty,    NullySpace,    NullyEmpty   ));
        NoNullRet(null,         Coalesce(NullyEmpty,    NullySpace,    NullySpace   ));
        NoNullRet(null,         Coalesce(NullyEmpty,    NullySpace,    NullyWithText));
        NoNullRet(null,         Coalesce(NullyEmpty,    NullySpace,    NonNullEmpty ));
        NoNullRet(null,         Coalesce(NullyEmpty,    NullySpace,    NonNullSpace ));
        NoNullRet(null,         Coalesce(NullyEmpty,    NullySpace,    NonNullText  ));
        NoNullRet(null,         Coalesce(NullyEmpty,    NullyWithText, NullText     ));
        NoNullRet(null,         Coalesce(NullyEmpty,    NullyWithText, NullyEmpty   ));
        NoNullRet(null,         Coalesce(NullyEmpty,    NullyWithText, NullySpace   ));
        NoNullRet(null,         Coalesce(NullyEmpty,    NullyWithText, NullyWithText));
        NoNullRet(null,         Coalesce(NullyEmpty,    NullyWithText, NonNullEmpty ));
        NoNullRet(null,         Coalesce(NullyEmpty,    NullyWithText, NonNullSpace ));
        NoNullRet(null,         Coalesce(NullyEmpty,    NullyWithText, NonNullText  ));
        NoNullRet(null,         Coalesce(NullyEmpty,    NonNullEmpty,  NullText     ));
        NoNullRet(null,         Coalesce(NullyEmpty,    NonNullEmpty,  NullyEmpty   ));
        NoNullRet(null,         Coalesce(NullyEmpty,    NonNullEmpty,  NullySpace   ));
        NoNullRet(null,         Coalesce(NullyEmpty,    NonNullEmpty,  NullyWithText));
        NoNullRet(null,         Coalesce(NullyEmpty,    NonNullEmpty,  NonNullEmpty ));
        NoNullRet(null,         Coalesce(NullyEmpty,    NonNullEmpty,  NonNullSpace ));
        NoNullRet(null,         Coalesce(NullyEmpty,    NonNullEmpty,  NonNullText  ));
        NoNullRet(null,         Coalesce(NullyEmpty,    NonNullSpace,  NullText     ));
        NoNullRet(null,         Coalesce(NullyEmpty,    NonNullSpace,  NullyEmpty   ));
        NoNullRet(null,         Coalesce(NullyEmpty,    NonNullSpace,  NullySpace   ));
        NoNullRet(null,         Coalesce(NullyEmpty,    NonNullSpace,  NullyWithText));
        NoNullRet(null,         Coalesce(NullyEmpty,    NonNullSpace,  NonNullEmpty ));
        NoNullRet(null,         Coalesce(NullyEmpty,    NonNullSpace,  NonNullSpace ));
        NoNullRet(null,         Coalesce(NullyEmpty,    NonNullSpace,  NonNullText  ));
        NoNullRet(null,         Coalesce(NullyEmpty,    NonNullText,   NullText     ));
        NoNullRet(null,         Coalesce(NullyEmpty,    NonNullText,   NullyEmpty   ));
        NoNullRet(null,         Coalesce(NullyEmpty,    NonNullText,   NullySpace   ));
        NoNullRet(null,         Coalesce(NullyEmpty,    NonNullText,   NullyWithText));
        NoNullRet(null,         Coalesce(NullyEmpty,    NonNullText,   NonNullEmpty ));
        NoNullRet(null,         Coalesce(NullyEmpty,    NonNullText,   NonNullSpace ));
        NoNullRet(null,         Coalesce(NullyEmpty,    NonNullText,   NonNullText  ));

        NoNullRet(null,         Coalesce(NullySpace,    NullText,      NullText     ));
        NoNullRet(null,         Coalesce(NullySpace,    NullText,      NullyEmpty   ));
        NoNullRet(null,         Coalesce(NullySpace,    NullText,      NullySpace   ));
        NoNullRet(null,         Coalesce(NullySpace,    NullText,      NullyWithText));
        NoNullRet(null,         Coalesce(NullySpace,    NullText,      NonNullEmpty ));
        NoNullRet(null,         Coalesce(NullySpace,    NullText,      NonNullSpace ));
        NoNullRet(null,         Coalesce(NullySpace,    NullText,      NonNullText  ));
        NoNullRet(null,         Coalesce(NullySpace,    NullyEmpty,    NullText     ));
        NoNullRet(null,         Coalesce(NullySpace,    NullyEmpty,    NullyEmpty   ));
        NoNullRet(null,         Coalesce(NullySpace,    NullyEmpty,    NullySpace   ));
        NoNullRet(null,         Coalesce(NullySpace,    NullyEmpty,    NullyWithText));
        NoNullRet(null,         Coalesce(NullySpace,    NullyEmpty,    NonNullEmpty ));
        NoNullRet(null,         Coalesce(NullySpace,    NullyEmpty,    NonNullSpace ));
        NoNullRet(null,         Coalesce(NullySpace,    NullyEmpty,    NonNullText  ));
        NoNullRet(null,         Coalesce(NullySpace,    NullySpace,    NullText     ));
        NoNullRet(null,         Coalesce(NullySpace,    NullySpace,    NullyEmpty   ));
        NoNullRet(null,         Coalesce(NullySpace,    NullySpace,    NullySpace   ));
        NoNullRet(null,         Coalesce(NullySpace,    NullySpace,    NullyWithText));
        NoNullRet(null,         Coalesce(NullySpace,    NullySpace,    NonNullEmpty ));
        NoNullRet(null,         Coalesce(NullySpace,    NullySpace,    NonNullSpace ));
        NoNullRet(null,         Coalesce(NullySpace,    NullySpace,    NonNullText  ));
        NoNullRet(null,         Coalesce(NullySpace,    NullyWithText, NullText     ));
        NoNullRet(null,         Coalesce(NullySpace,    NullyWithText, NullyEmpty   ));
        NoNullRet(null,         Coalesce(NullySpace,    NullyWithText, NullySpace   ));
        NoNullRet(null,         Coalesce(NullySpace,    NullyWithText, NullyWithText));
        NoNullRet(null,         Coalesce(NullySpace,    NullyWithText, NonNullEmpty ));
        NoNullRet(null,         Coalesce(NullySpace,    NullyWithText, NonNullSpace ));
        NoNullRet(null,         Coalesce(NullySpace,    NullyWithText, NonNullText  ));
        NoNullRet(null,         Coalesce(NullySpace,    NonNullEmpty,  NullText     ));
        NoNullRet(null,         Coalesce(NullySpace,    NonNullEmpty,  NullyEmpty   ));
        NoNullRet(null,         Coalesce(NullySpace,    NonNullEmpty,  NullySpace   ));
        NoNullRet(null,         Coalesce(NullySpace,    NonNullEmpty,  NullyWithText));
        NoNullRet(null,         Coalesce(NullySpace,    NonNullEmpty,  NonNullEmpty ));
        NoNullRet(null,         Coalesce(NullySpace,    NonNullEmpty,  NonNullSpace ));
        NoNullRet(null,         Coalesce(NullySpace,    NonNullEmpty,  NonNullText  ));
        NoNullRet(null,         Coalesce(NullySpace,    NonNullSpace,  NullText     ));
        NoNullRet(null,         Coalesce(NullySpace,    NonNullSpace,  NullyEmpty   ));
        NoNullRet(null,         Coalesce(NullySpace,    NonNullSpace,  NullySpace   ));
        NoNullRet(null,         Coalesce(NullySpace,    NonNullSpace,  NullyWithText));
        NoNullRet(null,         Coalesce(NullySpace,    NonNullSpace,  NonNullEmpty ));
        NoNullRet(null,         Coalesce(NullySpace,    NonNullSpace,  NonNullSpace ));
        NoNullRet(null,         Coalesce(NullySpace,    NonNullSpace,  NonNullText  ));
        NoNullRet(null,         Coalesce(NullySpace,    NonNullText,   NullText     ));
        NoNullRet(null,         Coalesce(NullySpace,    NonNullText,   NullyEmpty   ));
        NoNullRet(null,         Coalesce(NullySpace,    NonNullText,   NullySpace   ));
        NoNullRet(null,         Coalesce(NullySpace,    NonNullText,   NullyWithText));
        NoNullRet(null,         Coalesce(NullySpace,    NonNullText,   NonNullEmpty ));
        NoNullRet(null,         Coalesce(NullySpace,    NonNullText,   NonNullSpace ));
        NoNullRet(null,         Coalesce(NullySpace,    NonNullText,   NonNullText  ));

        NoNullRet(null,         Coalesce(NullyWithText, NullText,      NullText     ));
        NoNullRet(null,         Coalesce(NullyWithText, NullText,      NullyEmpty   ));
        NoNullRet(null,         Coalesce(NullyWithText, NullText,      NullySpace   ));
        NoNullRet(null,         Coalesce(NullyWithText, NullText,      NullyWithText));
        NoNullRet(null,         Coalesce(NullyWithText, NullText,      NonNullEmpty ));
        NoNullRet(null,         Coalesce(NullyWithText, NullText,      NonNullSpace ));
        NoNullRet(null,         Coalesce(NullyWithText, NullText,      NonNullText  ));
        NoNullRet(null,         Coalesce(NullyWithText, NullyEmpty,    NullText     ));
        NoNullRet(null,         Coalesce(NullyWithText, NullyEmpty,    NullyEmpty   ));
        NoNullRet(null,         Coalesce(NullyWithText, NullyEmpty,    NullySpace   ));
        NoNullRet(null,         Coalesce(NullyWithText, NullyEmpty,    NullyWithText));
        NoNullRet(null,         Coalesce(NullyWithText, NullyEmpty,    NonNullEmpty ));
        NoNullRet(null,         Coalesce(NullyWithText, NullyEmpty,    NonNullSpace ));
        NoNullRet(null,         Coalesce(NullyWithText, NullyEmpty,    NonNullText  ));
        NoNullRet(null,         Coalesce(NullyWithText, NullySpace,    NullText     ));
        NoNullRet(null,         Coalesce(NullyWithText, NullySpace,    NullyEmpty   ));
        NoNullRet(null,         Coalesce(NullyWithText, NullySpace,    NullySpace   ));
        NoNullRet(null,         Coalesce(NullyWithText, NullySpace,    NullyWithText));
        NoNullRet(null,         Coalesce(NullyWithText, NullySpace,    NonNullEmpty ));
        NoNullRet(null,         Coalesce(NullyWithText, NullySpace,    NonNullSpace ));
        NoNullRet(null,         Coalesce(NullyWithText, NullySpace,    NonNullText  ));
        NoNullRet(null,         Coalesce(NullyWithText, NullyWithText, NullText     ));
        NoNullRet(null,         Coalesce(NullyWithText, NullyWithText, NullyEmpty   ));
        NoNullRet(null,         Coalesce(NullyWithText, NullyWithText, NullySpace   ));
        NoNullRet(null,         Coalesce(NullyWithText, NullyWithText, NullyWithText));
        NoNullRet(null,         Coalesce(NullyWithText, NullyWithText, NonNullEmpty ));
        NoNullRet(null,         Coalesce(NullyWithText, NullyWithText, NonNullSpace ));
        NoNullRet(null,         Coalesce(NullyWithText, NullyWithText, NonNullText  ));
        NoNullRet(null,         Coalesce(NullyWithText, NonNullEmpty,  NullText     ));
        NoNullRet(null,         Coalesce(NullyWithText, NonNullEmpty,  NullyEmpty   ));
        NoNullRet(null,         Coalesce(NullyWithText, NonNullEmpty,  NullySpace   ));
        NoNullRet(null,         Coalesce(NullyWithText, NonNullEmpty,  NullyWithText));
        NoNullRet(null,         Coalesce(NullyWithText, NonNullEmpty,  NonNullEmpty ));
        NoNullRet(null,         Coalesce(NullyWithText, NonNullEmpty,  NonNullSpace ));
        NoNullRet(null,         Coalesce(NullyWithText, NonNullEmpty,  NonNullText  ));
        NoNullRet(null,         Coalesce(NullyWithText, NonNullSpace,  NullText     ));
        NoNullRet(null,         Coalesce(NullyWithText, NonNullSpace,  NullyEmpty   ));
        NoNullRet(null,         Coalesce(NullyWithText, NonNullSpace,  NullySpace   ));
        NoNullRet(null,         Coalesce(NullyWithText, NonNullSpace,  NullyWithText));
        NoNullRet(null,         Coalesce(NullyWithText, NonNullSpace,  NonNullEmpty ));
        NoNullRet(null,         Coalesce(NullyWithText, NonNullSpace,  NonNullSpace ));
        NoNullRet(null,         Coalesce(NullyWithText, NonNullSpace,  NonNullText  ));
        NoNullRet(null,         Coalesce(NullyWithText, NonNullText,   NullText     ));
        NoNullRet(null,         Coalesce(NullyWithText, NonNullText,   NullyEmpty   ));
        NoNullRet(null,         Coalesce(NullyWithText, NonNullText,   NullySpace   ));
        NoNullRet(null,         Coalesce(NullyWithText, NonNullText,   NullyWithText));
        NoNullRet(null,         Coalesce(NullyWithText, NonNullText,   NonNullEmpty ));
        NoNullRet(null,         Coalesce(NullyWithText, NonNullText,   NonNullSpace ));
        NoNullRet(null,         Coalesce(NullyWithText, NonNullText,   NonNullText  ));

        NoNullRet(null,         Coalesce(NonNullEmpty,  NullText,      NullText     ));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NullText,      NullyEmpty   ));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NullText,      NullySpace   ));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NullText,      NullyWithText));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NullText,      NonNullEmpty ));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NullText,      NonNullSpace ));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NullText,      NonNullText  ));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NullyEmpty,    NullText     ));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NullyEmpty,    NullyEmpty   ));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NullyEmpty,    NullySpace   ));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NullyEmpty,    NullyWithText));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NullyEmpty,    NonNullEmpty ));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NullyEmpty,    NonNullSpace ));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NullyEmpty,    NonNullText  ));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NullySpace,    NullText     ));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NullySpace,    NullyEmpty   ));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NullySpace,    NullySpace   ));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NullySpace,    NullyWithText));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NullySpace,    NonNullEmpty ));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NullySpace,    NonNullSpace ));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NullySpace,    NonNullText  ));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NullyWithText, NullText     ));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NullyWithText, NullyEmpty   ));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NullyWithText, NullySpace   ));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NullyWithText, NullyWithText));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NullyWithText, NonNullEmpty ));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NullyWithText, NonNullSpace ));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NullyWithText, NonNullText  ));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NonNullEmpty,  NullText     ));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NonNullEmpty,  NullyEmpty   ));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NonNullEmpty,  NullySpace   ));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NonNullEmpty,  NullyWithText));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NonNullEmpty,  NonNullEmpty ));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NonNullEmpty,  NonNullSpace ));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NonNullEmpty,  NonNullText  ));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NonNullSpace,  NullText     ));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NonNullSpace,  NullyEmpty   ));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NonNullSpace,  NullySpace   ));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NonNullSpace,  NullyWithText));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NonNullSpace,  NonNullEmpty ));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NonNullSpace,  NonNullSpace ));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NonNullSpace,  NonNullText  ));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NonNullText,   NullText     ));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NonNullText,   NullyEmpty   ));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NonNullText,   NullySpace   ));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NonNullText,   NullyWithText));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NonNullText,   NonNullEmpty ));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NonNullText,   NonNullSpace ));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NonNullText,   NonNullText  ));

        NoNullRet(null,         Coalesce(NonNullSpace,  NullText,      NullText     ));
        NoNullRet(null,         Coalesce(NonNullSpace,  NullText,      NullyEmpty   ));
        NoNullRet(null,         Coalesce(NonNullSpace,  NullText,      NullySpace   ));
        NoNullRet(null,         Coalesce(NonNullSpace,  NullText,      NullyWithText));
        NoNullRet(null,         Coalesce(NonNullSpace,  NullText,      NonNullEmpty ));
        NoNullRet(null,         Coalesce(NonNullSpace,  NullText,      NonNullSpace ));
        NoNullRet(null,         Coalesce(NonNullSpace,  NullText,      NonNullText  ));
        NoNullRet(null,         Coalesce(NonNullSpace,  NullyEmpty,    NullText     ));
        NoNullRet(null,         Coalesce(NonNullSpace,  NullyEmpty,    NullyEmpty   ));
        NoNullRet(null,         Coalesce(NonNullSpace,  NullyEmpty,    NullySpace   ));
        NoNullRet(null,         Coalesce(NonNullSpace,  NullyEmpty,    NullyWithText));
        NoNullRet(null,         Coalesce(NonNullSpace,  NullyEmpty,    NonNullEmpty ));
        NoNullRet(null,         Coalesce(NonNullSpace,  NullyEmpty,    NonNullSpace ));
        NoNullRet(null,         Coalesce(NonNullSpace,  NullyEmpty,    NonNullText  ));
        NoNullRet(null,         Coalesce(NonNullSpace,  NullySpace,    NullText     ));
        NoNullRet(null,         Coalesce(NonNullSpace,  NullySpace,    NullyEmpty   ));
        NoNullRet(null,         Coalesce(NonNullSpace,  NullySpace,    NullySpace   ));
        NoNullRet(null,         Coalesce(NonNullSpace,  NullySpace,    NullyWithText));
        NoNullRet(null,         Coalesce(NonNullSpace,  NullySpace,    NonNullEmpty ));
        NoNullRet(null,         Coalesce(NonNullSpace,  NullySpace,    NonNullSpace ));
        NoNullRet(null,         Coalesce(NonNullSpace,  NullySpace,    NonNullText  ));
        NoNullRet(null,         Coalesce(NonNullSpace,  NullyWithText, NullText     ));
        NoNullRet(null,         Coalesce(NonNullSpace,  NullyWithText, NullyEmpty   ));
        NoNullRet(null,         Coalesce(NonNullSpace,  NullyWithText, NullySpace   ));
        NoNullRet(null,         Coalesce(NonNullSpace,  NullyWithText, NullyWithText));
        NoNullRet(null,         Coalesce(NonNullSpace,  NullyWithText, NonNullEmpty ));
        NoNullRet(null,         Coalesce(NonNullSpace,  NullyWithText, NonNullSpace ));
        NoNullRet(null,         Coalesce(NonNullSpace,  NullyWithText, NonNullText  ));
        NoNullRet(null,         Coalesce(NonNullSpace,  NonNullEmpty,  NullText     ));
        NoNullRet(null,         Coalesce(NonNullSpace,  NonNullEmpty,  NullyEmpty   ));
        NoNullRet(null,         Coalesce(NonNullSpace,  NonNullEmpty,  NullySpace   ));
        NoNullRet(null,         Coalesce(NonNullSpace,  NonNullEmpty,  NullyWithText));
        NoNullRet(null,         Coalesce(NonNullSpace,  NonNullEmpty,  NonNullEmpty ));
        NoNullRet(null,         Coalesce(NonNullSpace,  NonNullEmpty,  NonNullSpace ));
        NoNullRet(null,         Coalesce(NonNullSpace,  NonNullEmpty,  NonNullText  ));
        NoNullRet(null,         Coalesce(NonNullSpace,  NonNullSpace,  NullText     ));
        NoNullRet(null,         Coalesce(NonNullSpace,  NonNullSpace,  NullyEmpty   ));
        NoNullRet(null,         Coalesce(NonNullSpace,  NonNullSpace,  NullySpace   ));
        NoNullRet(null,         Coalesce(NonNullSpace,  NonNullSpace,  NullyWithText));
        NoNullRet(null,         Coalesce(NonNullSpace,  NonNullSpace,  NonNullEmpty ));
        NoNullRet(null,         Coalesce(NonNullSpace,  NonNullSpace,  NonNullSpace ));
        NoNullRet(null,         Coalesce(NonNullSpace,  NonNullSpace,  NonNullText  ));
        NoNullRet(null,         Coalesce(NonNullSpace,  NonNullText,   NullText     ));
        NoNullRet(null,         Coalesce(NonNullSpace,  NonNullText,   NullyEmpty   ));
        NoNullRet(null,         Coalesce(NonNullSpace,  NonNullText,   NullySpace   ));
        NoNullRet(null,         Coalesce(NonNullSpace,  NonNullText,   NullyWithText));
        NoNullRet(null,         Coalesce(NonNullSpace,  NonNullText,   NonNullEmpty ));
        NoNullRet(null,         Coalesce(NonNullSpace,  NonNullText,   NonNullSpace ));
        NoNullRet(null,         Coalesce(NonNullSpace,  NonNullText,   NonNullText  ));
        
        NoNullRet(null,         Coalesce(NonNullText,   NullText,      NullText     ));
        NoNullRet(null,         Coalesce(NonNullText,   NullText,      NullyEmpty   ));
        NoNullRet(null,         Coalesce(NonNullText,   NullText,      NullySpace   ));
        NoNullRet(null,         Coalesce(NonNullText,   NullText,      NullyWithText));
        NoNullRet(null,         Coalesce(NonNullText,   NullText,      NonNullEmpty ));
        NoNullRet(null,         Coalesce(NonNullText,   NullText,      NonNullSpace ));
        NoNullRet(null,         Coalesce(NonNullText,   NullText,      NonNullText  ));
        NoNullRet(null,         Coalesce(NonNullText,   NullyEmpty,    NullText     ));
        NoNullRet(null,         Coalesce(NonNullText,   NullyEmpty,    NullyEmpty   ));
        NoNullRet(null,         Coalesce(NonNullText,   NullyEmpty,    NullySpace   ));
        NoNullRet(null,         Coalesce(NonNullText,   NullyEmpty,    NullyWithText));
        NoNullRet(null,         Coalesce(NonNullText,   NullyEmpty,    NonNullEmpty ));
        NoNullRet(null,         Coalesce(NonNullText,   NullyEmpty,    NonNullSpace ));
        NoNullRet(null,         Coalesce(NonNullText,   NullyEmpty,    NonNullText  ));
        NoNullRet(null,         Coalesce(NonNullText,   NullySpace,    NullText     ));
        NoNullRet(null,         Coalesce(NonNullText,   NullySpace,    NullyEmpty   ));
        NoNullRet(null,         Coalesce(NonNullText,   NullySpace,    NullySpace   ));
        NoNullRet(null,         Coalesce(NonNullText,   NullySpace,    NullyWithText));
        NoNullRet(null,         Coalesce(NonNullText,   NullySpace,    NonNullEmpty ));
        NoNullRet(null,         Coalesce(NonNullText,   NullySpace,    NonNullSpace ));
        NoNullRet(null,         Coalesce(NonNullText,   NullySpace,    NonNullText  ));
        NoNullRet(null,         Coalesce(NonNullText,   NullyWithText, NullText     ));
        NoNullRet(null,         Coalesce(NonNullText,   NullyWithText, NullyEmpty   ));
        NoNullRet(null,         Coalesce(NonNullText,   NullyWithText, NullySpace   ));
        NoNullRet(null,         Coalesce(NonNullText,   NullyWithText, NullyWithText));
        NoNullRet(null,         Coalesce(NonNullText,   NullyWithText, NonNullEmpty ));
        NoNullRet(null,         Coalesce(NonNullText,   NullyWithText, NonNullSpace ));
        NoNullRet(null,         Coalesce(NonNullText,   NullyWithText, NonNullText  ));
        NoNullRet(null,         Coalesce(NonNullText,   NonNullEmpty,  NullText     ));
        NoNullRet(null,         Coalesce(NonNullText,   NonNullEmpty,  NullyEmpty   ));
        NoNullRet(null,         Coalesce(NonNullText,   NonNullEmpty,  NullySpace   ));
        NoNullRet(null,         Coalesce(NonNullText,   NonNullEmpty,  NullyWithText));
        NoNullRet(null,         Coalesce(NonNullText,   NonNullEmpty,  NonNullEmpty ));
        NoNullRet(null,         Coalesce(NonNullText,   NonNullEmpty,  NonNullSpace ));
        NoNullRet(null,         Coalesce(NonNullText,   NonNullEmpty,  NonNullText  ));
        NoNullRet(null,         Coalesce(NonNullText,   NonNullSpace,  NullText     ));
        NoNullRet(null,         Coalesce(NonNullText,   NonNullSpace,  NullyEmpty   ));
        NoNullRet(null,         Coalesce(NonNullText,   NonNullSpace,  NullySpace   ));
        NoNullRet(null,         Coalesce(NonNullText,   NonNullSpace,  NullyWithText));
        NoNullRet(null,         Coalesce(NonNullText,   NonNullSpace,  NonNullEmpty ));
        NoNullRet(null,         Coalesce(NonNullText,   NonNullSpace,  NonNullSpace ));
        NoNullRet(null,         Coalesce(NonNullText,   NonNullSpace,  NonNullText  ));
        NoNullRet(null,         Coalesce(NonNullText,   NonNullText,   NullText     ));
        NoNullRet(null,         Coalesce(NonNullText,   NonNullText,   NullyEmpty   ));
        NoNullRet(null,         Coalesce(NonNullText,   NonNullText,   NullySpace   ));
        NoNullRet(null,         Coalesce(NonNullText,   NonNullText,   NullyWithText));
        NoNullRet(null,         Coalesce(NonNullText,   NonNullText,   NonNullEmpty ));
        NoNullRet(null,         Coalesce(NonNullText,   NonNullText,   NonNullSpace ));
        NoNullRet(null,         Coalesce(NonNullText,   NonNullText,   NonNullText  ));

        NoNullRet(null,         Coalesce(NullText,      NullText,      NullText,      trimSpace: false));
        NoNullRet(null,         Coalesce(NullText,      NullText,      NullyEmpty,    trimSpace: false));
        NoNullRet(null,         Coalesce(NullText,      NullText,      NullySpace,    trimSpace: false));
        NoNullRet(null,         Coalesce(NullText,      NullText,      NullyWithText, trimSpace: false));
        NoNullRet(null,         Coalesce(NullText,      NullText,      NonNullEmpty,  trimSpace: false));
        NoNullRet(null,         Coalesce(NullText,      NullText,      NonNullSpace,  trimSpace: false));
        NoNullRet(null,         Coalesce(NullText,      NullText,      NonNullText,   trimSpace: false));
        NoNullRet(null,         Coalesce(NullText,      NullyEmpty,    NullText,      trimSpace: false));
        NoNullRet(null,         Coalesce(NullText,      NullyEmpty,    NullyEmpty,    trimSpace: false));
        NoNullRet(null,         Coalesce(NullText,      NullyEmpty,    NullySpace,    trimSpace: false));
        NoNullRet(null,         Coalesce(NullText,      NullyEmpty,    NullyWithText, trimSpace: false));
        NoNullRet(null,         Coalesce(NullText,      NullyEmpty,    NonNullEmpty,  trimSpace: false));
        NoNullRet(null,         Coalesce(NullText,      NullyEmpty,    NonNullSpace,  trimSpace: false));
        NoNullRet(null,         Coalesce(NullText,      NullyEmpty,    NonNullText,   trimSpace: false));
        NoNullRet(null,         Coalesce(NullText,      NullySpace,    NullText,      trimSpace: false));
        NoNullRet(null,         Coalesce(NullText,      NullySpace,    NullyEmpty,    trimSpace: false));
        NoNullRet(null,         Coalesce(NullText,      NullySpace,    NullySpace,    trimSpace: false));
        NoNullRet(null,         Coalesce(NullText,      NullySpace,    NullyWithText, trimSpace: false));
        NoNullRet(null,         Coalesce(NullText,      NullySpace,    NonNullEmpty,  trimSpace: false));
        NoNullRet(null,         Coalesce(NullText,      NullySpace,    NonNullSpace,  trimSpace: false));
        NoNullRet(null,         Coalesce(NullText,      NullySpace,    NonNullText,   trimSpace: false));
        NoNullRet(null,         Coalesce(NullText,      NullyWithText, NullText,      trimSpace: false));
        NoNullRet(null,         Coalesce(NullText,      NullyWithText, NullyEmpty,    trimSpace: false));
        NoNullRet(null,         Coalesce(NullText,      NullyWithText, NullySpace,    trimSpace: false));
        NoNullRet(null,         Coalesce(NullText,      NullyWithText, NullyWithText, trimSpace: false));
        NoNullRet(null,         Coalesce(NullText,      NullyWithText, NonNullEmpty,  trimSpace: false));
        NoNullRet(null,         Coalesce(NullText,      NullyWithText, NonNullSpace,  trimSpace: false));
        NoNullRet(null,         Coalesce(NullText,      NullyWithText, NonNullText,   trimSpace: false));
        NoNullRet(null,         Coalesce(NullText,      NonNullEmpty,  NullText,      trimSpace: false));
        NoNullRet(null,         Coalesce(NullText,      NonNullEmpty,  NullyEmpty,    trimSpace: false));
        NoNullRet(null,         Coalesce(NullText,      NonNullEmpty,  NullySpace,    trimSpace: false));
        NoNullRet(null,         Coalesce(NullText,      NonNullEmpty,  NullyWithText, trimSpace: false));
        NoNullRet(null,         Coalesce(NullText,      NonNullEmpty,  NonNullEmpty,  trimSpace: false));
        NoNullRet(null,         Coalesce(NullText,      NonNullEmpty,  NonNullSpace,  trimSpace: false));
        NoNullRet(null,         Coalesce(NullText,      NonNullEmpty,  NonNullText,   trimSpace: false));
        NoNullRet(null,         Coalesce(NullText,      NonNullSpace,  NullText,      trimSpace: false));
        NoNullRet(null,         Coalesce(NullText,      NonNullSpace,  NullyEmpty,    trimSpace: false));
        NoNullRet(null,         Coalesce(NullText,      NonNullSpace,  NullySpace,    trimSpace: false));
        NoNullRet(null,         Coalesce(NullText,      NonNullSpace,  NullyWithText, trimSpace: false));
        NoNullRet(null,         Coalesce(NullText,      NonNullSpace,  NonNullEmpty,  trimSpace: false));
        NoNullRet(null,         Coalesce(NullText,      NonNullSpace,  NonNullSpace,  trimSpace: false));
        NoNullRet(null,         Coalesce(NullText,      NonNullSpace,  NonNullText,   trimSpace: false));
        NoNullRet(null,         Coalesce(NullText,      NonNullText,   NullText,      trimSpace: false));
        NoNullRet(null,         Coalesce(NullText,      NonNullText,   NullyEmpty,    trimSpace: false));
        NoNullRet(null,         Coalesce(NullText,      NonNullText,   NullySpace,    trimSpace: false));
        NoNullRet(null,         Coalesce(NullText,      NonNullText,   NullyWithText, trimSpace: false));
        NoNullRet(null,         Coalesce(NullText,      NonNullText,   NonNullEmpty,  trimSpace: false));
        NoNullRet(null,         Coalesce(NullText,      NonNullText,   NonNullSpace,  trimSpace: false));
        NoNullRet(null,         Coalesce(NullText,      NonNullText,   NonNullText,   trimSpace: false));
        
        NoNullRet(null,         Coalesce(NullyEmpty,    NullText,      NullText,      trimSpace: false));
        NoNullRet(null,         Coalesce(NullyEmpty,    NullText,      NullyEmpty,    trimSpace: false));
        NoNullRet(null,         Coalesce(NullyEmpty,    NullText,      NullySpace,    trimSpace: false));
        NoNullRet(null,         Coalesce(NullyEmpty,    NullText,      NullyWithText, trimSpace: false));
        NoNullRet(null,         Coalesce(NullyEmpty,    NullText,      NonNullEmpty,  trimSpace: false));
        NoNullRet(null,         Coalesce(NullyEmpty,    NullText,      NonNullSpace,  trimSpace: false));
        NoNullRet(null,         Coalesce(NullyEmpty,    NullText,      NonNullText,   trimSpace: false));
        NoNullRet(null,         Coalesce(NullyEmpty,    NullyEmpty,    NullText,      trimSpace: false));
        NoNullRet(null,         Coalesce(NullyEmpty,    NullyEmpty,    NullyEmpty,    trimSpace: false));
        NoNullRet(null,         Coalesce(NullyEmpty,    NullyEmpty,    NullySpace,    trimSpace: false));
        NoNullRet(null,         Coalesce(NullyEmpty,    NullyEmpty,    NullyWithText, trimSpace: false));
        NoNullRet(null,         Coalesce(NullyEmpty,    NullyEmpty,    NonNullEmpty,  trimSpace: false));
        NoNullRet(null,         Coalesce(NullyEmpty,    NullyEmpty,    NonNullSpace,  trimSpace: false));
        NoNullRet(null,         Coalesce(NullyEmpty,    NullyEmpty,    NonNullText,   trimSpace: false));
        NoNullRet(null,         Coalesce(NullyEmpty,    NullySpace,    NullText,      trimSpace: false));
        NoNullRet(null,         Coalesce(NullyEmpty,    NullySpace,    NullyEmpty,    trimSpace: false));
        NoNullRet(null,         Coalesce(NullyEmpty,    NullySpace,    NullySpace,    trimSpace: false));
        NoNullRet(null,         Coalesce(NullyEmpty,    NullySpace,    NullyWithText, trimSpace: false));
        NoNullRet(null,         Coalesce(NullyEmpty,    NullySpace,    NonNullEmpty,  trimSpace: false));
        NoNullRet(null,         Coalesce(NullyEmpty,    NullySpace,    NonNullSpace,  trimSpace: false));
        NoNullRet(null,         Coalesce(NullyEmpty,    NullySpace,    NonNullText,   trimSpace: false));
        NoNullRet(null,         Coalesce(NullyEmpty,    NullyWithText, NullText,      trimSpace: false));
        NoNullRet(null,         Coalesce(NullyEmpty,    NullyWithText, NullyEmpty,    trimSpace: false));
        NoNullRet(null,         Coalesce(NullyEmpty,    NullyWithText, NullySpace,    trimSpace: false));
        NoNullRet(null,         Coalesce(NullyEmpty,    NullyWithText, NullyWithText, trimSpace: false));
        NoNullRet(null,         Coalesce(NullyEmpty,    NullyWithText, NonNullEmpty,  trimSpace: false));
        NoNullRet(null,         Coalesce(NullyEmpty,    NullyWithText, NonNullSpace,  trimSpace: false));
        NoNullRet(null,         Coalesce(NullyEmpty,    NullyWithText, NonNullText,   trimSpace: false));
        NoNullRet(null,         Coalesce(NullyEmpty,    NonNullEmpty,  NullText,      trimSpace: false));
        NoNullRet(null,         Coalesce(NullyEmpty,    NonNullEmpty,  NullyEmpty,    trimSpace: false));
        NoNullRet(null,         Coalesce(NullyEmpty,    NonNullEmpty,  NullySpace,    trimSpace: false));
        NoNullRet(null,         Coalesce(NullyEmpty,    NonNullEmpty,  NullyWithText, trimSpace: false));
        NoNullRet(null,         Coalesce(NullyEmpty,    NonNullEmpty,  NonNullEmpty,  trimSpace: false));
        NoNullRet(null,         Coalesce(NullyEmpty,    NonNullEmpty,  NonNullSpace,  trimSpace: false));
        NoNullRet(null,         Coalesce(NullyEmpty,    NonNullEmpty,  NonNullText,   trimSpace: false));
        NoNullRet(null,         Coalesce(NullyEmpty,    NonNullSpace,  NullText,      trimSpace: false));
        NoNullRet(null,         Coalesce(NullyEmpty,    NonNullSpace,  NullyEmpty,    trimSpace: false));
        NoNullRet(null,         Coalesce(NullyEmpty,    NonNullSpace,  NullySpace,    trimSpace: false));
        NoNullRet(null,         Coalesce(NullyEmpty,    NonNullSpace,  NullyWithText, trimSpace: false));
        NoNullRet(null,         Coalesce(NullyEmpty,    NonNullSpace,  NonNullEmpty,  trimSpace: false));
        NoNullRet(null,         Coalesce(NullyEmpty,    NonNullSpace,  NonNullSpace,  trimSpace: false));
        NoNullRet(null,         Coalesce(NullyEmpty,    NonNullSpace,  NonNullText,   trimSpace: false));
        NoNullRet(null,         Coalesce(NullyEmpty,    NonNullText,   NullText,      trimSpace: false));
        NoNullRet(null,         Coalesce(NullyEmpty,    NonNullText,   NullyEmpty,    trimSpace: false));
        NoNullRet(null,         Coalesce(NullyEmpty,    NonNullText,   NullySpace,    trimSpace: false));
        NoNullRet(null,         Coalesce(NullyEmpty,    NonNullText,   NullyWithText, trimSpace: false));
        NoNullRet(null,         Coalesce(NullyEmpty,    NonNullText,   NonNullEmpty,  trimSpace: false));
        NoNullRet(null,         Coalesce(NullyEmpty,    NonNullText,   NonNullSpace,  trimSpace: false));
        NoNullRet(null,         Coalesce(NullyEmpty,    NonNullText,   NonNullText,   trimSpace: false));

        NoNullRet(null,         Coalesce(NullySpace,    NullText,      NullText,      trimSpace: false));
        NoNullRet(null,         Coalesce(NullySpace,    NullText,      NullyEmpty,    trimSpace: false));
        NoNullRet(null,         Coalesce(NullySpace,    NullText,      NullySpace,    trimSpace: false));
        NoNullRet(null,         Coalesce(NullySpace,    NullText,      NullyWithText, trimSpace: false));
        NoNullRet(null,         Coalesce(NullySpace,    NullText,      NonNullEmpty,  trimSpace: false));
        NoNullRet(null,         Coalesce(NullySpace,    NullText,      NonNullSpace,  trimSpace: false));
        NoNullRet(null,         Coalesce(NullySpace,    NullText,      NonNullText,   trimSpace: false));
        NoNullRet(null,         Coalesce(NullySpace,    NullyEmpty,    NullText,      trimSpace: false));
        NoNullRet(null,         Coalesce(NullySpace,    NullyEmpty,    NullyEmpty,    trimSpace: false));
        NoNullRet(null,         Coalesce(NullySpace,    NullyEmpty,    NullySpace,    trimSpace: false));
        NoNullRet(null,         Coalesce(NullySpace,    NullyEmpty,    NullyWithText, trimSpace: false));
        NoNullRet(null,         Coalesce(NullySpace,    NullyEmpty,    NonNullEmpty,  trimSpace: false));
        NoNullRet(null,         Coalesce(NullySpace,    NullyEmpty,    NonNullSpace,  trimSpace: false));
        NoNullRet(null,         Coalesce(NullySpace,    NullyEmpty,    NonNullText,   trimSpace: false));
        NoNullRet(null,         Coalesce(NullySpace,    NullySpace,    NullText,      trimSpace: false));
        NoNullRet(null,         Coalesce(NullySpace,    NullySpace,    NullyEmpty,    trimSpace: false));
        NoNullRet(null,         Coalesce(NullySpace,    NullySpace,    NullySpace,    trimSpace: false));
        NoNullRet(null,         Coalesce(NullySpace,    NullySpace,    NullyWithText, trimSpace: false));
        NoNullRet(null,         Coalesce(NullySpace,    NullySpace,    NonNullEmpty,  trimSpace: false));
        NoNullRet(null,         Coalesce(NullySpace,    NullySpace,    NonNullSpace,  trimSpace: false));
        NoNullRet(null,         Coalesce(NullySpace,    NullySpace,    NonNullText,   trimSpace: false));
        NoNullRet(null,         Coalesce(NullySpace,    NullyWithText, NullText,      trimSpace: false));
        NoNullRet(null,         Coalesce(NullySpace,    NullyWithText, NullyEmpty,    trimSpace: false));
        NoNullRet(null,         Coalesce(NullySpace,    NullyWithText, NullySpace,    trimSpace: false));
        NoNullRet(null,         Coalesce(NullySpace,    NullyWithText, NullyWithText, trimSpace: false));
        NoNullRet(null,         Coalesce(NullySpace,    NullyWithText, NonNullEmpty,  trimSpace: false));
        NoNullRet(null,         Coalesce(NullySpace,    NullyWithText, NonNullSpace,  trimSpace: false));
        NoNullRet(null,         Coalesce(NullySpace,    NullyWithText, NonNullText,   trimSpace: false));
        NoNullRet(null,         Coalesce(NullySpace,    NonNullEmpty,  NullText,      trimSpace: false));
        NoNullRet(null,         Coalesce(NullySpace,    NonNullEmpty,  NullyEmpty,    trimSpace: false));
        NoNullRet(null,         Coalesce(NullySpace,    NonNullEmpty,  NullySpace,    trimSpace: false));
        NoNullRet(null,         Coalesce(NullySpace,    NonNullEmpty,  NullyWithText, trimSpace: false));
        NoNullRet(null,         Coalesce(NullySpace,    NonNullEmpty,  NonNullEmpty,  trimSpace: false));
        NoNullRet(null,         Coalesce(NullySpace,    NonNullEmpty,  NonNullSpace,  trimSpace: false));
        NoNullRet(null,         Coalesce(NullySpace,    NonNullEmpty,  NonNullText,   trimSpace: false));
        NoNullRet(null,         Coalesce(NullySpace,    NonNullSpace,  NullText,      trimSpace: false));
        NoNullRet(null,         Coalesce(NullySpace,    NonNullSpace,  NullyEmpty,    trimSpace: false));
        NoNullRet(null,         Coalesce(NullySpace,    NonNullSpace,  NullySpace,    trimSpace: false));
        NoNullRet(null,         Coalesce(NullySpace,    NonNullSpace,  NullyWithText, trimSpace: false));
        NoNullRet(null,         Coalesce(NullySpace,    NonNullSpace,  NonNullEmpty,  trimSpace: false));
        NoNullRet(null,         Coalesce(NullySpace,    NonNullSpace,  NonNullSpace,  trimSpace: false));
        NoNullRet(null,         Coalesce(NullySpace,    NonNullSpace,  NonNullText,   trimSpace: false));
        NoNullRet(null,         Coalesce(NullySpace,    NonNullText,   NullText,      trimSpace: false));
        NoNullRet(null,         Coalesce(NullySpace,    NonNullText,   NullyEmpty,    trimSpace: false));
        NoNullRet(null,         Coalesce(NullySpace,    NonNullText,   NullySpace,    trimSpace: false));
        NoNullRet(null,         Coalesce(NullySpace,    NonNullText,   NullyWithText, trimSpace: false));
        NoNullRet(null,         Coalesce(NullySpace,    NonNullText,   NonNullEmpty,  trimSpace: false));
        NoNullRet(null,         Coalesce(NullySpace,    NonNullText,   NonNullSpace,  trimSpace: false));
        NoNullRet(null,         Coalesce(NullySpace,    NonNullText,   NonNullText,   trimSpace: false));

        NoNullRet(null,         Coalesce(NullyWithText, NullText,      NullText,      trimSpace: false));
        NoNullRet(null,         Coalesce(NullyWithText, NullText,      NullyEmpty,    trimSpace: false));
        NoNullRet(null,         Coalesce(NullyWithText, NullText,      NullySpace,    trimSpace: false));
        NoNullRet(null,         Coalesce(NullyWithText, NullText,      NullyWithText, trimSpace: false));
        NoNullRet(null,         Coalesce(NullyWithText, NullText,      NonNullEmpty,  trimSpace: false));
        NoNullRet(null,         Coalesce(NullyWithText, NullText,      NonNullSpace,  trimSpace: false));
        NoNullRet(null,         Coalesce(NullyWithText, NullText,      NonNullText,   trimSpace: false));
        NoNullRet(null,         Coalesce(NullyWithText, NullyEmpty,    NullText,      trimSpace: false));
        NoNullRet(null,         Coalesce(NullyWithText, NullyEmpty,    NullyEmpty,    trimSpace: false));
        NoNullRet(null,         Coalesce(NullyWithText, NullyEmpty,    NullySpace,    trimSpace: false));
        NoNullRet(null,         Coalesce(NullyWithText, NullyEmpty,    NullyWithText, trimSpace: false));
        NoNullRet(null,         Coalesce(NullyWithText, NullyEmpty,    NonNullEmpty,  trimSpace: false));
        NoNullRet(null,         Coalesce(NullyWithText, NullyEmpty,    NonNullSpace,  trimSpace: false));
        NoNullRet(null,         Coalesce(NullyWithText, NullyEmpty,    NonNullText,   trimSpace: false));
        NoNullRet(null,         Coalesce(NullyWithText, NullySpace,    NullText,      trimSpace: false));
        NoNullRet(null,         Coalesce(NullyWithText, NullySpace,    NullyEmpty,    trimSpace: false));
        NoNullRet(null,         Coalesce(NullyWithText, NullySpace,    NullySpace,    trimSpace: false));
        NoNullRet(null,         Coalesce(NullyWithText, NullySpace,    NullyWithText, trimSpace: false));
        NoNullRet(null,         Coalesce(NullyWithText, NullySpace,    NonNullEmpty,  trimSpace: false));
        NoNullRet(null,         Coalesce(NullyWithText, NullySpace,    NonNullSpace,  trimSpace: false));
        NoNullRet(null,         Coalesce(NullyWithText, NullySpace,    NonNullText,   trimSpace: false));
        NoNullRet(null,         Coalesce(NullyWithText, NullyWithText, NullText,      trimSpace: false));
        NoNullRet(null,         Coalesce(NullyWithText, NullyWithText, NullyEmpty,    trimSpace: false));
        NoNullRet(null,         Coalesce(NullyWithText, NullyWithText, NullySpace,    trimSpace: false));
        NoNullRet(null,         Coalesce(NullyWithText, NullyWithText, NullyWithText, trimSpace: false));
        NoNullRet(null,         Coalesce(NullyWithText, NullyWithText, NonNullEmpty,  trimSpace: false));
        NoNullRet(null,         Coalesce(NullyWithText, NullyWithText, NonNullSpace,  trimSpace: false));
        NoNullRet(null,         Coalesce(NullyWithText, NullyWithText, NonNullText,   trimSpace: false));
        NoNullRet(null,         Coalesce(NullyWithText, NonNullEmpty,  NullText,      trimSpace: false));
        NoNullRet(null,         Coalesce(NullyWithText, NonNullEmpty,  NullyEmpty,    trimSpace: false));
        NoNullRet(null,         Coalesce(NullyWithText, NonNullEmpty,  NullySpace,    trimSpace: false));
        NoNullRet(null,         Coalesce(NullyWithText, NonNullEmpty,  NullyWithText, trimSpace: false));
        NoNullRet(null,         Coalesce(NullyWithText, NonNullEmpty,  NonNullEmpty,  trimSpace: false));
        NoNullRet(null,         Coalesce(NullyWithText, NonNullEmpty,  NonNullSpace,  trimSpace: false));
        NoNullRet(null,         Coalesce(NullyWithText, NonNullEmpty,  NonNullText,   trimSpace: false));
        NoNullRet(null,         Coalesce(NullyWithText, NonNullSpace,  NullText,      trimSpace: false));
        NoNullRet(null,         Coalesce(NullyWithText, NonNullSpace,  NullyEmpty,    trimSpace: false));
        NoNullRet(null,         Coalesce(NullyWithText, NonNullSpace,  NullySpace,    trimSpace: false));
        NoNullRet(null,         Coalesce(NullyWithText, NonNullSpace,  NullyWithText, trimSpace: false));
        NoNullRet(null,         Coalesce(NullyWithText, NonNullSpace,  NonNullEmpty,  trimSpace: false));
        NoNullRet(null,         Coalesce(NullyWithText, NonNullSpace,  NonNullSpace,  trimSpace: false));
        NoNullRet(null,         Coalesce(NullyWithText, NonNullSpace,  NonNullText,   trimSpace: false));
        NoNullRet(null,         Coalesce(NullyWithText, NonNullText,   NullText,      trimSpace: false));
        NoNullRet(null,         Coalesce(NullyWithText, NonNullText,   NullyEmpty,    trimSpace: false));
        NoNullRet(null,         Coalesce(NullyWithText, NonNullText,   NullySpace,    trimSpace: false));
        NoNullRet(null,         Coalesce(NullyWithText, NonNullText,   NullyWithText, trimSpace: false));
        NoNullRet(null,         Coalesce(NullyWithText, NonNullText,   NonNullEmpty,  trimSpace: false));
        NoNullRet(null,         Coalesce(NullyWithText, NonNullText,   NonNullSpace,  trimSpace: false));
        NoNullRet(null,         Coalesce(NullyWithText, NonNullText,   NonNullText,   trimSpace: false));

        NoNullRet(null,         Coalesce(NonNullEmpty,  NullText,      NullText,      trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NullText,      NullyEmpty,    trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NullText,      NullySpace,    trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NullText,      NullyWithText, trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NullText,      NonNullEmpty,  trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NullText,      NonNullSpace,  trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NullText,      NonNullText,   trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NullyEmpty,    NullText,      trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NullyEmpty,    NullyEmpty,    trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NullyEmpty,    NullySpace,    trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NullyEmpty,    NullyWithText, trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NullyEmpty,    NonNullEmpty,  trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NullyEmpty,    NonNullSpace,  trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NullyEmpty,    NonNullText,   trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NullySpace,    NullText,      trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NullySpace,    NullyEmpty,    trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NullySpace,    NullySpace,    trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NullySpace,    NullyWithText, trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NullySpace,    NonNullEmpty,  trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NullySpace,    NonNullSpace,  trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NullySpace,    NonNullText,   trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NullyWithText, NullText,      trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NullyWithText, NullyEmpty,    trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NullyWithText, NullySpace,    trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NullyWithText, NullyWithText, trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NullyWithText, NonNullEmpty,  trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NullyWithText, NonNullSpace,  trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NullyWithText, NonNullText,   trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NonNullEmpty,  NullText,      trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NonNullEmpty,  NullyEmpty,    trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NonNullEmpty,  NullySpace,    trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NonNullEmpty,  NullyWithText, trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NonNullEmpty,  NonNullEmpty,  trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NonNullEmpty,  NonNullSpace,  trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NonNullEmpty,  NonNullText,   trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NonNullSpace,  NullText,      trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NonNullSpace,  NullyEmpty,    trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NonNullSpace,  NullySpace,    trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NonNullSpace,  NullyWithText, trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NonNullSpace,  NonNullEmpty,  trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NonNullSpace,  NonNullSpace,  trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NonNullSpace,  NonNullText,   trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NonNullText,   NullText,      trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NonNullText,   NullyEmpty,    trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NonNullText,   NullySpace,    trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NonNullText,   NullyWithText, trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NonNullText,   NonNullEmpty,  trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NonNullText,   NonNullSpace,  trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullEmpty,  NonNullText,   NonNullText,   trimSpace: false));

        NoNullRet(null,         Coalesce(NonNullSpace,  NullText,      NullText,      trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullSpace,  NullText,      NullyEmpty,    trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullSpace,  NullText,      NullySpace,    trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullSpace,  NullText,      NullyWithText, trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullSpace,  NullText,      NonNullEmpty,  trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullSpace,  NullText,      NonNullSpace,  trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullSpace,  NullText,      NonNullText,   trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullSpace,  NullyEmpty,    NullText,      trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullSpace,  NullyEmpty,    NullyEmpty,    trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullSpace,  NullyEmpty,    NullySpace,    trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullSpace,  NullyEmpty,    NullyWithText, trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullSpace,  NullyEmpty,    NonNullEmpty,  trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullSpace,  NullyEmpty,    NonNullSpace,  trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullSpace,  NullyEmpty,    NonNullText,   trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullSpace,  NullySpace,    NullText,      trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullSpace,  NullySpace,    NullyEmpty,    trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullSpace,  NullySpace,    NullySpace,    trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullSpace,  NullySpace,    NullyWithText, trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullSpace,  NullySpace,    NonNullEmpty,  trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullSpace,  NullySpace,    NonNullSpace,  trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullSpace,  NullySpace,    NonNullText,   trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullSpace,  NullyWithText, NullText,      trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullSpace,  NullyWithText, NullyEmpty,    trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullSpace,  NullyWithText, NullySpace,    trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullSpace,  NullyWithText, NullyWithText, trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullSpace,  NullyWithText, NonNullEmpty,  trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullSpace,  NullyWithText, NonNullSpace,  trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullSpace,  NullyWithText, NonNullText,   trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullSpace,  NonNullEmpty,  NullText,      trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullSpace,  NonNullEmpty,  NullyEmpty,    trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullSpace,  NonNullEmpty,  NullySpace,    trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullSpace,  NonNullEmpty,  NullyWithText, trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullSpace,  NonNullEmpty,  NonNullEmpty,  trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullSpace,  NonNullEmpty,  NonNullSpace,  trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullSpace,  NonNullEmpty,  NonNullText,   trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullSpace,  NonNullSpace,  NullText,      trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullSpace,  NonNullSpace,  NullyEmpty,    trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullSpace,  NonNullSpace,  NullySpace,    trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullSpace,  NonNullSpace,  NullyWithText, trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullSpace,  NonNullSpace,  NonNullEmpty,  trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullSpace,  NonNullSpace,  NonNullSpace,  trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullSpace,  NonNullSpace,  NonNullText,   trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullSpace,  NonNullText,   NullText,      trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullSpace,  NonNullText,   NullyEmpty,    trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullSpace,  NonNullText,   NullySpace,    trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullSpace,  NonNullText,   NullyWithText, trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullSpace,  NonNullText,   NonNullEmpty,  trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullSpace,  NonNullText,   NonNullSpace,  trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullSpace,  NonNullText,   NonNullText,   trimSpace: false));
        
        NoNullRet(null,         Coalesce(NonNullText,   NullText,      NullText,      trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullText,   NullText,      NullyEmpty,    trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullText,   NullText,      NullySpace,    trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullText,   NullText,      NullyWithText, trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullText,   NullText,      NonNullEmpty,  trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullText,   NullText,      NonNullSpace,  trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullText,   NullText,      NonNullText,   trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullText,   NullyEmpty,    NullText,      trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullText,   NullyEmpty,    NullyEmpty,    trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullText,   NullyEmpty,    NullySpace,    trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullText,   NullyEmpty,    NullyWithText, trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullText,   NullyEmpty,    NonNullEmpty,  trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullText,   NullyEmpty,    NonNullSpace,  trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullText,   NullyEmpty,    NonNullText,   trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullText,   NullySpace,    NullText,      trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullText,   NullySpace,    NullyEmpty,    trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullText,   NullySpace,    NullySpace,    trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullText,   NullySpace,    NullyWithText, trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullText,   NullySpace,    NonNullEmpty,  trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullText,   NullySpace,    NonNullSpace,  trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullText,   NullySpace,    NonNullText,   trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullText,   NullyWithText, NullText,      trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullText,   NullyWithText, NullyEmpty,    trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullText,   NullyWithText, NullySpace,    trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullText,   NullyWithText, NullyWithText, trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullText,   NullyWithText, NonNullEmpty,  trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullText,   NullyWithText, NonNullSpace,  trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullText,   NullyWithText, NonNullText,   trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullText,   NonNullEmpty,  NullText,      trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullText,   NonNullEmpty,  NullyEmpty,    trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullText,   NonNullEmpty,  NullySpace,    trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullText,   NonNullEmpty,  NullyWithText, trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullText,   NonNullEmpty,  NonNullEmpty,  trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullText,   NonNullEmpty,  NonNullSpace,  trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullText,   NonNullEmpty,  NonNullText,   trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullText,   NonNullSpace,  NullText,      trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullText,   NonNullSpace,  NullyEmpty,    trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullText,   NonNullSpace,  NullySpace,    trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullText,   NonNullSpace,  NullyWithText, trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullText,   NonNullSpace,  NonNullEmpty,  trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullText,   NonNullSpace,  NonNullSpace,  trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullText,   NonNullSpace,  NonNullText,   trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullText,   NonNullText,   NullText,      trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullText,   NonNullText,   NullyEmpty,    trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullText,   NonNullText,   NullySpace,    trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullText,   NonNullText,   NullyWithText, trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullText,   NonNullText,   NonNullEmpty,  trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullText,   NonNullText,   NonNullSpace,  trimSpace: false));
        NoNullRet(null,         Coalesce(NonNullText,   NonNullText,   NonNullText,   trimSpace: false));

    }
}