namespace JJ.Framework.Existence.Core.Tests;

// Should check:
// - [x] int
// - [x] int?
// - [x] string
// - [x] string?
// - [x] Reference Types (StringBuilder)
// - [x] Nullable reference types (StringBuilder?)
// - [x] ~ Coalescing from collection to collection
// - [x] Collection types
// - [x] Trim tolerance
// - [x] Static variant
// - [x] Extension variant
// - [ ] Enum
// - [ ] Enum?
// - [ ] double
// - [ ] bool
// - [ ] .. Coalesce arities

[TestClass]
public class CoalesceTests_Arity3
{
    [TestMethod]
    public void Test_Coalesce_Arity3_Text()
    {
        AreEqual("Hi!", Coalesce(" ", null, "Hi!"));
        AreEqual(" ",   Coalesce(" ", null, "Hi!", trimSpace: false));

        NoNullRet(NoNullEmpty, Coalesce(NullText,      NullText,      NullText     ));
        NoNullRet(NoNullEmpty, Coalesce(NullText,      NullText,      NullyEmpty   ));
        NoNullRet(NoNullSpace, Coalesce(NullText,      NullText,      NullySpace   ));
        NoNullRet(NoNullText,  Coalesce(NullText,      NullText,      NullyWithText));
        NoNullRet(NoNullEmpty, Coalesce(NullText,      NullText,      NoNullEmpty  ));
        NoNullRet(NoNullSpace, Coalesce(NullText,      NullText,      NoNullSpace  ));
        NoNullRet(NoNullText,  Coalesce(NullText,      NullText,      NoNullText   ));
        NoNullRet(NoNullEmpty, Coalesce(NullText,      NullyEmpty,    NullText     ));
        NoNullRet(NoNullEmpty, Coalesce(NullText,      NullyEmpty,    NullyEmpty   ));
        NoNullRet(NoNullSpace, Coalesce(NullText,      NullyEmpty,    NullySpace   ));
        NoNullRet(NoNullText,  Coalesce(NullText,      NullyEmpty,    NullyWithText));
        NoNullRet(NoNullEmpty, Coalesce(NullText,      NullyEmpty,    NoNullEmpty  ));
        NoNullRet(NoNullSpace, Coalesce(NullText,      NullyEmpty,    NoNullSpace  ));
        NoNullRet(NoNullText,  Coalesce(NullText,      NullyEmpty,    NoNullText   ));

        NoNullRet(NoNullEmpty, Coalesce(NullText,      NullySpace,    NullText     ));
        NoNullRet(null,        Coalesce(NullText,      NullySpace,    NullyEmpty   ));
        NoNullRet(null,        Coalesce(NullText,      NullySpace,    NullySpace   ));
        NoNullRet(null,        Coalesce(NullText,      NullySpace,    NullyWithText));
        NoNullRet(null,        Coalesce(NullText,      NullySpace,    NoNullEmpty  ));
        NoNullRet(null,        Coalesce(NullText,      NullySpace,    NoNullSpace  ));
        NoNullRet(null,        Coalesce(NullText,      NullySpace,    NoNullText   ));
        NoNullRet(null,        Coalesce(NullText,      NullyWithText, NullText     ));
        NoNullRet(null,        Coalesce(NullText,      NullyWithText, NullyEmpty   ));
        NoNullRet(null,        Coalesce(NullText,      NullyWithText, NullySpace   ));
        NoNullRet(null,        Coalesce(NullText,      NullyWithText, NullyWithText));
        NoNullRet(null,        Coalesce(NullText,      NullyWithText, NoNullEmpty  ));
        NoNullRet(null,        Coalesce(NullText,      NullyWithText, NoNullSpace  ));
        NoNullRet(null,        Coalesce(NullText,      NullyWithText, NoNullText   ));
        NoNullRet(null,        Coalesce(NullText,      NoNullEmpty,   NullText     ));
        NoNullRet(null,        Coalesce(NullText,      NoNullEmpty,   NullyEmpty   ));
        NoNullRet(null,        Coalesce(NullText,      NoNullEmpty,   NullySpace   ));
        NoNullRet(null,        Coalesce(NullText,      NoNullEmpty,   NullyWithText));
        NoNullRet(null,        Coalesce(NullText,      NoNullEmpty,   NoNullEmpty  ));
        NoNullRet(null,        Coalesce(NullText,      NoNullEmpty,   NoNullSpace  ));
        NoNullRet(null,        Coalesce(NullText,      NoNullEmpty,   NoNullText   ));
        NoNullRet(null,        Coalesce(NullText,      NoNullSpace,   NullText     ));
        NoNullRet(null,        Coalesce(NullText,      NoNullSpace,   NullyEmpty   ));
        NoNullRet(null,        Coalesce(NullText,      NoNullSpace,   NullySpace   ));
        NoNullRet(null,        Coalesce(NullText,      NoNullSpace,   NullyWithText));
        NoNullRet(null,        Coalesce(NullText,      NoNullSpace,   NoNullEmpty  ));
        NoNullRet(null,        Coalesce(NullText,      NoNullSpace,   NoNullSpace  ));
        NoNullRet(null,        Coalesce(NullText,      NoNullSpace,   NoNullText   ));
        NoNullRet(null,        Coalesce(NullText,      NoNullText,    NullText     ));
        NoNullRet(null,        Coalesce(NullText,      NoNullText,    NullyEmpty   ));
        NoNullRet(null,        Coalesce(NullText,      NoNullText,    NullySpace   ));
        NoNullRet(null,        Coalesce(NullText,      NoNullText,    NullyWithText));
        NoNullRet(null,        Coalesce(NullText,      NoNullText,    NoNullEmpty  ));
        NoNullRet(null,        Coalesce(NullText,      NoNullText,    NoNullSpace  ));
        NoNullRet(null,        Coalesce(NullText,      NoNullText,    NoNullText   ));
        
        NoNullRet(null,        Coalesce(NullyEmpty,    NullText,      NullText     ));
        NoNullRet(null,        Coalesce(NullyEmpty,    NullText,      NullyEmpty   ));
        NoNullRet(null,        Coalesce(NullyEmpty,    NullText,      NullySpace   ));
        NoNullRet(null,        Coalesce(NullyEmpty,    NullText,      NullyWithText));
        NoNullRet(null,        Coalesce(NullyEmpty,    NullText,      NoNullEmpty  ));
        NoNullRet(null,        Coalesce(NullyEmpty,    NullText,      NoNullSpace  ));
        NoNullRet(null,        Coalesce(NullyEmpty,    NullText,      NoNullText   ));
        NoNullRet(null,        Coalesce(NullyEmpty,    NullyEmpty,    NullText     ));
        NoNullRet(null,        Coalesce(NullyEmpty,    NullyEmpty,    NullyEmpty   ));
        NoNullRet(null,        Coalesce(NullyEmpty,    NullyEmpty,    NullySpace   ));
        NoNullRet(null,        Coalesce(NullyEmpty,    NullyEmpty,    NullyWithText));
        NoNullRet(null,        Coalesce(NullyEmpty,    NullyEmpty,    NoNullEmpty  ));
        NoNullRet(null,        Coalesce(NullyEmpty,    NullyEmpty,    NoNullSpace  ));
        NoNullRet(null,        Coalesce(NullyEmpty,    NullyEmpty,    NoNullText   ));
        NoNullRet(null,        Coalesce(NullyEmpty,    NullySpace,    NullText     ));
        NoNullRet(null,        Coalesce(NullyEmpty,    NullySpace,    NullyEmpty   ));
        NoNullRet(null,        Coalesce(NullyEmpty,    NullySpace,    NullySpace   ));
        NoNullRet(null,        Coalesce(NullyEmpty,    NullySpace,    NullyWithText));
        NoNullRet(null,        Coalesce(NullyEmpty,    NullySpace,    NoNullEmpty  ));
        NoNullRet(null,        Coalesce(NullyEmpty,    NullySpace,    NoNullSpace  ));
        NoNullRet(null,        Coalesce(NullyEmpty,    NullySpace,    NoNullText   ));
        NoNullRet(null,        Coalesce(NullyEmpty,    NullyWithText, NullText     ));
        NoNullRet(null,        Coalesce(NullyEmpty,    NullyWithText, NullyEmpty   ));
        NoNullRet(null,        Coalesce(NullyEmpty,    NullyWithText, NullySpace   ));
        NoNullRet(null,        Coalesce(NullyEmpty,    NullyWithText, NullyWithText));
        NoNullRet(null,        Coalesce(NullyEmpty,    NullyWithText, NoNullEmpty  ));
        NoNullRet(null,        Coalesce(NullyEmpty,    NullyWithText, NoNullSpace  ));
        NoNullRet(null,        Coalesce(NullyEmpty,    NullyWithText, NoNullText   ));
        NoNullRet(null,        Coalesce(NullyEmpty,    NoNullEmpty,   NullText     ));
        NoNullRet(null,        Coalesce(NullyEmpty,    NoNullEmpty,   NullyEmpty   ));
        NoNullRet(null,        Coalesce(NullyEmpty,    NoNullEmpty,   NullySpace   ));
        NoNullRet(null,        Coalesce(NullyEmpty,    NoNullEmpty,   NullyWithText));
        NoNullRet(null,        Coalesce(NullyEmpty,    NoNullEmpty,   NoNullEmpty  ));
        NoNullRet(null,        Coalesce(NullyEmpty,    NoNullEmpty,   NoNullSpace  ));
        NoNullRet(null,        Coalesce(NullyEmpty,    NoNullEmpty,   NoNullText   ));
        NoNullRet(null,        Coalesce(NullyEmpty,    NoNullSpace,   NullText     ));
        NoNullRet(null,        Coalesce(NullyEmpty,    NoNullSpace,   NullyEmpty   ));
        NoNullRet(null,        Coalesce(NullyEmpty,    NoNullSpace,   NullySpace   ));
        NoNullRet(null,        Coalesce(NullyEmpty,    NoNullSpace,   NullyWithText));
        NoNullRet(null,        Coalesce(NullyEmpty,    NoNullSpace,   NoNullEmpty  ));
        NoNullRet(null,        Coalesce(NullyEmpty,    NoNullSpace,   NoNullSpace  ));
        NoNullRet(null,        Coalesce(NullyEmpty,    NoNullSpace,   NoNullText   ));
        NoNullRet(null,        Coalesce(NullyEmpty,    NoNullText,    NullText     ));
        NoNullRet(null,        Coalesce(NullyEmpty,    NoNullText,    NullyEmpty   ));
        NoNullRet(null,        Coalesce(NullyEmpty,    NoNullText,    NullySpace   ));
        NoNullRet(null,        Coalesce(NullyEmpty,    NoNullText,    NullyWithText));
        NoNullRet(null,        Coalesce(NullyEmpty,    NoNullText,    NoNullEmpty  ));
        NoNullRet(null,        Coalesce(NullyEmpty,    NoNullText,    NoNullSpace  ));
        NoNullRet(null,        Coalesce(NullyEmpty,    NoNullText,    NoNullText   ));

        NoNullRet(null,        Coalesce(NullySpace,    NullText,      NullText     ));
        NoNullRet(null,        Coalesce(NullySpace,    NullText,      NullyEmpty   ));
        NoNullRet(null,        Coalesce(NullySpace,    NullText,      NullySpace   ));
        NoNullRet(null,        Coalesce(NullySpace,    NullText,      NullyWithText));
        NoNullRet(null,        Coalesce(NullySpace,    NullText,      NoNullEmpty  ));
        NoNullRet(null,        Coalesce(NullySpace,    NullText,      NoNullSpace  ));
        NoNullRet(null,        Coalesce(NullySpace,    NullText,      NoNullText   ));
        NoNullRet(null,        Coalesce(NullySpace,    NullyEmpty,    NullText     ));
        NoNullRet(null,        Coalesce(NullySpace,    NullyEmpty,    NullyEmpty   ));
        NoNullRet(null,        Coalesce(NullySpace,    NullyEmpty,    NullySpace   ));
        NoNullRet(null,        Coalesce(NullySpace,    NullyEmpty,    NullyWithText));
        NoNullRet(null,        Coalesce(NullySpace,    NullyEmpty,    NoNullEmpty  ));
        NoNullRet(null,        Coalesce(NullySpace,    NullyEmpty,    NoNullSpace  ));
        NoNullRet(null,        Coalesce(NullySpace,    NullyEmpty,    NoNullText   ));
        NoNullRet(null,        Coalesce(NullySpace,    NullySpace,    NullText     ));
        NoNullRet(null,        Coalesce(NullySpace,    NullySpace,    NullyEmpty   ));
        NoNullRet(null,        Coalesce(NullySpace,    NullySpace,    NullySpace   ));
        NoNullRet(null,        Coalesce(NullySpace,    NullySpace,    NullyWithText));
        NoNullRet(null,        Coalesce(NullySpace,    NullySpace,    NoNullEmpty  ));
        NoNullRet(null,        Coalesce(NullySpace,    NullySpace,    NoNullSpace  ));
        NoNullRet(null,        Coalesce(NullySpace,    NullySpace,    NoNullText   ));
        NoNullRet(null,        Coalesce(NullySpace,    NullyWithText, NullText     ));
        NoNullRet(null,        Coalesce(NullySpace,    NullyWithText, NullyEmpty   ));
        NoNullRet(null,        Coalesce(NullySpace,    NullyWithText, NullySpace   ));
        NoNullRet(null,        Coalesce(NullySpace,    NullyWithText, NullyWithText));
        NoNullRet(null,        Coalesce(NullySpace,    NullyWithText, NoNullEmpty  ));
        NoNullRet(null,        Coalesce(NullySpace,    NullyWithText, NoNullSpace  ));
        NoNullRet(null,        Coalesce(NullySpace,    NullyWithText, NoNullText   ));
        NoNullRet(null,        Coalesce(NullySpace,    NoNullEmpty,   NullText     ));
        NoNullRet(null,        Coalesce(NullySpace,    NoNullEmpty,   NullyEmpty   ));
        NoNullRet(null,        Coalesce(NullySpace,    NoNullEmpty,   NullySpace   ));
        NoNullRet(null,        Coalesce(NullySpace,    NoNullEmpty,   NullyWithText));
        NoNullRet(null,        Coalesce(NullySpace,    NoNullEmpty,   NoNullEmpty  ));
        NoNullRet(null,        Coalesce(NullySpace,    NoNullEmpty,   NoNullSpace  ));
        NoNullRet(null,        Coalesce(NullySpace,    NoNullEmpty,   NoNullText   ));
        NoNullRet(null,        Coalesce(NullySpace,    NoNullSpace,   NullText     ));
        NoNullRet(null,        Coalesce(NullySpace,    NoNullSpace,   NullyEmpty   ));
        NoNullRet(null,        Coalesce(NullySpace,    NoNullSpace,   NullySpace   ));
        NoNullRet(null,        Coalesce(NullySpace,    NoNullSpace,   NullyWithText));
        NoNullRet(null,        Coalesce(NullySpace,    NoNullSpace,   NoNullEmpty  ));
        NoNullRet(null,        Coalesce(NullySpace,    NoNullSpace,   NoNullSpace  ));
        NoNullRet(null,        Coalesce(NullySpace,    NoNullSpace,   NoNullText   ));
        NoNullRet(null,        Coalesce(NullySpace,    NoNullText,    NullText     ));
        NoNullRet(null,        Coalesce(NullySpace,    NoNullText,    NullyEmpty   ));
        NoNullRet(null,        Coalesce(NullySpace,    NoNullText,    NullySpace   ));
        NoNullRet(null,        Coalesce(NullySpace,    NoNullText,    NullyWithText));
        NoNullRet(null,        Coalesce(NullySpace,    NoNullText,    NoNullEmpty  ));
        NoNullRet(null,        Coalesce(NullySpace,    NoNullText,    NoNullSpace  ));
        NoNullRet(null,        Coalesce(NullySpace,    NoNullText,    NoNullText   ));

        NoNullRet(null,        Coalesce(NullyWithText, NullText,      NullText     ));
        NoNullRet(null,        Coalesce(NullyWithText, NullText,      NullyEmpty   ));
        NoNullRet(null,        Coalesce(NullyWithText, NullText,      NullySpace   ));
        NoNullRet(null,        Coalesce(NullyWithText, NullText,      NullyWithText));
        NoNullRet(null,        Coalesce(NullyWithText, NullText,      NoNullEmpty  ));
        NoNullRet(null,        Coalesce(NullyWithText, NullText,      NoNullSpace  ));
        NoNullRet(null,        Coalesce(NullyWithText, NullText,      NoNullText   ));
        NoNullRet(null,        Coalesce(NullyWithText, NullyEmpty,    NullText     ));
        NoNullRet(null,        Coalesce(NullyWithText, NullyEmpty,    NullyEmpty   ));
        NoNullRet(null,        Coalesce(NullyWithText, NullyEmpty,    NullySpace   ));
        NoNullRet(null,        Coalesce(NullyWithText, NullyEmpty,    NullyWithText));
        NoNullRet(null,        Coalesce(NullyWithText, NullyEmpty,    NoNullEmpty  ));
        NoNullRet(null,        Coalesce(NullyWithText, NullyEmpty,    NoNullSpace  ));
        NoNullRet(null,        Coalesce(NullyWithText, NullyEmpty,    NoNullText   ));
        NoNullRet(null,        Coalesce(NullyWithText, NullySpace,    NullText     ));
        NoNullRet(null,        Coalesce(NullyWithText, NullySpace,    NullyEmpty   ));
        NoNullRet(null,        Coalesce(NullyWithText, NullySpace,    NullySpace   ));
        NoNullRet(null,        Coalesce(NullyWithText, NullySpace,    NullyWithText));
        NoNullRet(null,        Coalesce(NullyWithText, NullySpace,    NoNullEmpty  ));
        NoNullRet(null,        Coalesce(NullyWithText, NullySpace,    NoNullSpace  ));
        NoNullRet(null,        Coalesce(NullyWithText, NullySpace,    NoNullText   ));
        NoNullRet(null,        Coalesce(NullyWithText, NullyWithText, NullText     ));
        NoNullRet(null,        Coalesce(NullyWithText, NullyWithText, NullyEmpty   ));
        NoNullRet(null,        Coalesce(NullyWithText, NullyWithText, NullySpace   ));
        NoNullRet(null,        Coalesce(NullyWithText, NullyWithText, NullyWithText));
        NoNullRet(null,        Coalesce(NullyWithText, NullyWithText, NoNullEmpty  ));
        NoNullRet(null,        Coalesce(NullyWithText, NullyWithText, NoNullSpace  ));
        NoNullRet(null,        Coalesce(NullyWithText, NullyWithText, NoNullText   ));
        NoNullRet(null,        Coalesce(NullyWithText, NoNullEmpty,   NullText     ));
        NoNullRet(null,        Coalesce(NullyWithText, NoNullEmpty,   NullyEmpty   ));
        NoNullRet(null,        Coalesce(NullyWithText, NoNullEmpty,   NullySpace   ));
        NoNullRet(null,        Coalesce(NullyWithText, NoNullEmpty,   NullyWithText));
        NoNullRet(null,        Coalesce(NullyWithText, NoNullEmpty,   NoNullEmpty  ));
        NoNullRet(null,        Coalesce(NullyWithText, NoNullEmpty,   NoNullSpace  ));
        NoNullRet(null,        Coalesce(NullyWithText, NoNullEmpty,   NoNullText   ));
        NoNullRet(null,        Coalesce(NullyWithText, NoNullSpace,   NullText     ));
        NoNullRet(null,        Coalesce(NullyWithText, NoNullSpace,   NullyEmpty   ));
        NoNullRet(null,        Coalesce(NullyWithText, NoNullSpace,   NullySpace   ));
        NoNullRet(null,        Coalesce(NullyWithText, NoNullSpace,   NullyWithText));
        NoNullRet(null,        Coalesce(NullyWithText, NoNullSpace,   NoNullEmpty  ));
        NoNullRet(null,        Coalesce(NullyWithText, NoNullSpace,   NoNullSpace  ));
        NoNullRet(null,        Coalesce(NullyWithText, NoNullSpace,   NoNullText   ));
        NoNullRet(null,        Coalesce(NullyWithText, NoNullText,    NullText     ));
        NoNullRet(null,        Coalesce(NullyWithText, NoNullText,    NullyEmpty   ));
        NoNullRet(null,        Coalesce(NullyWithText, NoNullText,    NullySpace   ));
        NoNullRet(null,        Coalesce(NullyWithText, NoNullText,    NullyWithText));
        NoNullRet(null,        Coalesce(NullyWithText, NoNullText,    NoNullEmpty  ));
        NoNullRet(null,        Coalesce(NullyWithText, NoNullText,    NoNullSpace  ));
        NoNullRet(null,        Coalesce(NullyWithText, NoNullText,    NoNullText   ));

        NoNullRet(null,        Coalesce(NoNullEmpty,   NullText,      NullText     ));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NullText,      NullyEmpty   ));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NullText,      NullySpace   ));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NullText,      NullyWithText));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NullText,      NoNullEmpty  ));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NullText,      NoNullSpace  ));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NullText,      NoNullText   ));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NullyEmpty,    NullText     ));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NullyEmpty,    NullyEmpty   ));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NullyEmpty,    NullySpace   ));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NullyEmpty,    NullyWithText));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NullyEmpty,    NoNullEmpty  ));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NullyEmpty,    NoNullSpace  ));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NullyEmpty,    NoNullText   ));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NullySpace,    NullText     ));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NullySpace,    NullyEmpty   ));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NullySpace,    NullySpace   ));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NullySpace,    NullyWithText));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NullySpace,    NoNullEmpty  ));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NullySpace,    NoNullSpace  ));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NullySpace,    NoNullText   ));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NullyWithText, NullText     ));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NullyWithText, NullyEmpty   ));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NullyWithText, NullySpace   ));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NullyWithText, NullyWithText));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NullyWithText, NoNullEmpty  ));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NullyWithText, NoNullSpace  ));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NullyWithText, NoNullText   ));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NoNullEmpty,   NullText     ));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NoNullEmpty,   NullyEmpty   ));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NoNullEmpty,   NullySpace   ));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NoNullEmpty,   NullyWithText));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NoNullEmpty,   NoNullEmpty  ));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NoNullEmpty,   NoNullSpace  ));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NoNullEmpty,   NoNullText   ));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NoNullSpace,   NullText     ));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NoNullSpace,   NullyEmpty   ));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NoNullSpace,   NullySpace   ));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NoNullSpace,   NullyWithText));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NoNullSpace,   NoNullEmpty  ));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NoNullSpace,   NoNullSpace  ));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NoNullSpace,   NoNullText   ));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NoNullText,    NullText     ));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NoNullText,    NullyEmpty   ));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NoNullText,    NullySpace   ));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NoNullText,    NullyWithText));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NoNullText,    NoNullEmpty  ));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NoNullText,    NoNullSpace  ));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NoNullText,    NoNullText   ));
                                                       
        NoNullRet(null,        Coalesce(NoNullSpace,   NullText,      NullText     ));
        NoNullRet(null,        Coalesce(NoNullSpace,   NullText,      NullyEmpty   ));
        NoNullRet(null,        Coalesce(NoNullSpace,   NullText,      NullySpace   ));
        NoNullRet(null,        Coalesce(NoNullSpace,   NullText,      NullyWithText));
        NoNullRet(null,        Coalesce(NoNullSpace,   NullText,      NoNullEmpty  ));
        NoNullRet(null,        Coalesce(NoNullSpace,   NullText,      NoNullSpace  ));
        NoNullRet(null,        Coalesce(NoNullSpace,   NullText,      NoNullText   ));
        NoNullRet(null,        Coalesce(NoNullSpace,   NullyEmpty,    NullText     ));
        NoNullRet(null,        Coalesce(NoNullSpace,   NullyEmpty,    NullyEmpty   ));
        NoNullRet(null,        Coalesce(NoNullSpace,   NullyEmpty,    NullySpace   ));
        NoNullRet(null,        Coalesce(NoNullSpace,   NullyEmpty,    NullyWithText));
        NoNullRet(null,        Coalesce(NoNullSpace,   NullyEmpty,    NoNullEmpty  ));
        NoNullRet(null,        Coalesce(NoNullSpace,   NullyEmpty,    NoNullSpace  ));
        NoNullRet(null,        Coalesce(NoNullSpace,   NullyEmpty,    NoNullText   ));
        NoNullRet(null,        Coalesce(NoNullSpace,   NullySpace,    NullText     ));
        NoNullRet(null,        Coalesce(NoNullSpace,   NullySpace,    NullyEmpty   ));
        NoNullRet(null,        Coalesce(NoNullSpace,   NullySpace,    NullySpace   ));
        NoNullRet(null,        Coalesce(NoNullSpace,   NullySpace,    NullyWithText));
        NoNullRet(null,        Coalesce(NoNullSpace,   NullySpace,    NoNullEmpty  ));
        NoNullRet(null,        Coalesce(NoNullSpace,   NullySpace,    NoNullSpace  ));
        NoNullRet(null,        Coalesce(NoNullSpace,   NullySpace,    NoNullText   ));
        NoNullRet(null,        Coalesce(NoNullSpace,   NullyWithText, NullText     ));
        NoNullRet(null,        Coalesce(NoNullSpace,   NullyWithText, NullyEmpty   ));
        NoNullRet(null,        Coalesce(NoNullSpace,   NullyWithText, NullySpace   ));
        NoNullRet(null,        Coalesce(NoNullSpace,   NullyWithText, NullyWithText));
        NoNullRet(null,        Coalesce(NoNullSpace,   NullyWithText, NoNullEmpty  ));
        NoNullRet(null,        Coalesce(NoNullSpace,   NullyWithText, NoNullSpace  ));
        NoNullRet(null,        Coalesce(NoNullSpace,   NullyWithText, NoNullText   ));
        NoNullRet(null,        Coalesce(NoNullSpace,   NoNullEmpty,   NullText     ));
        NoNullRet(null,        Coalesce(NoNullSpace,   NoNullEmpty,   NullyEmpty   ));
        NoNullRet(null,        Coalesce(NoNullSpace,   NoNullEmpty,   NullySpace   ));
        NoNullRet(null,        Coalesce(NoNullSpace,   NoNullEmpty,   NullyWithText));
        NoNullRet(null,        Coalesce(NoNullSpace,   NoNullEmpty,   NoNullEmpty  ));
        NoNullRet(null,        Coalesce(NoNullSpace,   NoNullEmpty,   NoNullSpace  ));
        NoNullRet(null,        Coalesce(NoNullSpace,   NoNullEmpty,   NoNullText   ));
        NoNullRet(null,        Coalesce(NoNullSpace,   NoNullSpace,   NullText     ));
        NoNullRet(null,        Coalesce(NoNullSpace,   NoNullSpace,   NullyEmpty   ));
        NoNullRet(null,        Coalesce(NoNullSpace,   NoNullSpace,   NullySpace   ));
        NoNullRet(null,        Coalesce(NoNullSpace,   NoNullSpace,   NullyWithText));
        NoNullRet(null,        Coalesce(NoNullSpace,   NoNullSpace,   NoNullEmpty  ));
        NoNullRet(null,        Coalesce(NoNullSpace,   NoNullSpace,   NoNullSpace  ));
        NoNullRet(null,        Coalesce(NoNullSpace,   NoNullSpace,   NoNullText   ));
        NoNullRet(null,        Coalesce(NoNullSpace,   NoNullText,    NullText     ));
        NoNullRet(null,        Coalesce(NoNullSpace,   NoNullText,    NullyEmpty   ));
        NoNullRet(null,        Coalesce(NoNullSpace,   NoNullText,    NullySpace   ));
        NoNullRet(null,        Coalesce(NoNullSpace,   NoNullText,    NullyWithText));
        NoNullRet(null,        Coalesce(NoNullSpace,   NoNullText,    NoNullEmpty  ));
        NoNullRet(null,        Coalesce(NoNullSpace,   NoNullText,    NoNullSpace  ));
        NoNullRet(null,        Coalesce(NoNullSpace,   NoNullText,    NoNullText   ));
                                                       
        NoNullRet(null,        Coalesce(NoNullText,    NullText,      NullText     ));
        NoNullRet(null,        Coalesce(NoNullText,    NullText,      NullyEmpty   ));
        NoNullRet(null,        Coalesce(NoNullText,    NullText,      NullySpace   ));
        NoNullRet(null,        Coalesce(NoNullText,    NullText,      NullyWithText));
        NoNullRet(null,        Coalesce(NoNullText,    NullText,      NoNullEmpty  ));
        NoNullRet(null,        Coalesce(NoNullText,    NullText,      NoNullSpace  ));
        NoNullRet(null,        Coalesce(NoNullText,    NullText,      NoNullText   ));
        NoNullRet(null,        Coalesce(NoNullText,    NullyEmpty,    NullText     ));
        NoNullRet(null,        Coalesce(NoNullText,    NullyEmpty,    NullyEmpty   ));
        NoNullRet(null,        Coalesce(NoNullText,    NullyEmpty,    NullySpace   ));
        NoNullRet(null,        Coalesce(NoNullText,    NullyEmpty,    NullyWithText));
        NoNullRet(null,        Coalesce(NoNullText,    NullyEmpty,    NoNullEmpty  ));
        NoNullRet(null,        Coalesce(NoNullText,    NullyEmpty,    NoNullSpace  ));
        NoNullRet(null,        Coalesce(NoNullText,    NullyEmpty,    NoNullText   ));
        NoNullRet(null,        Coalesce(NoNullText,    NullySpace,    NullText     ));
        NoNullRet(null,        Coalesce(NoNullText,    NullySpace,    NullyEmpty   ));
        NoNullRet(null,        Coalesce(NoNullText,    NullySpace,    NullySpace   ));
        NoNullRet(null,        Coalesce(NoNullText,    NullySpace,    NullyWithText));
        NoNullRet(null,        Coalesce(NoNullText,    NullySpace,    NoNullEmpty  ));
        NoNullRet(null,        Coalesce(NoNullText,    NullySpace,    NoNullSpace  ));
        NoNullRet(null,        Coalesce(NoNullText,    NullySpace,    NoNullText   ));
        NoNullRet(null,        Coalesce(NoNullText,    NullyWithText, NullText     ));
        NoNullRet(null,        Coalesce(NoNullText,    NullyWithText, NullyEmpty   ));
        NoNullRet(null,        Coalesce(NoNullText,    NullyWithText, NullySpace   ));
        NoNullRet(null,        Coalesce(NoNullText,    NullyWithText, NullyWithText));
        NoNullRet(null,        Coalesce(NoNullText,    NullyWithText, NoNullEmpty  ));
        NoNullRet(null,        Coalesce(NoNullText,    NullyWithText, NoNullSpace  ));
        NoNullRet(null,        Coalesce(NoNullText,    NullyWithText, NoNullText   ));
        NoNullRet(null,        Coalesce(NoNullText,    NoNullEmpty,   NullText     ));
        NoNullRet(null,        Coalesce(NoNullText,    NoNullEmpty,   NullyEmpty   ));
        NoNullRet(null,        Coalesce(NoNullText,    NoNullEmpty,   NullySpace   ));
        NoNullRet(null,        Coalesce(NoNullText,    NoNullEmpty,   NullyWithText));
        NoNullRet(null,        Coalesce(NoNullText,    NoNullEmpty,   NoNullEmpty  ));
        NoNullRet(null,        Coalesce(NoNullText,    NoNullEmpty,   NoNullSpace  ));
        NoNullRet(null,        Coalesce(NoNullText,    NoNullEmpty,   NoNullText   ));
        NoNullRet(null,        Coalesce(NoNullText,    NoNullSpace,   NullText     ));
        NoNullRet(null,        Coalesce(NoNullText,    NoNullSpace,   NullyEmpty   ));
        NoNullRet(null,        Coalesce(NoNullText,    NoNullSpace,   NullySpace   ));
        NoNullRet(null,        Coalesce(NoNullText,    NoNullSpace,   NullyWithText));
        NoNullRet(null,        Coalesce(NoNullText,    NoNullSpace,   NoNullEmpty  ));
        NoNullRet(null,        Coalesce(NoNullText,    NoNullSpace,   NoNullSpace  ));
        NoNullRet(null,        Coalesce(NoNullText,    NoNullSpace,   NoNullText   ));
        NoNullRet(null,        Coalesce(NoNullText,    NoNullText,    NullText     ));
        NoNullRet(null,        Coalesce(NoNullText,    NoNullText,    NullyEmpty   ));
        NoNullRet(null,        Coalesce(NoNullText,    NoNullText,    NullySpace   ));
        NoNullRet(null,        Coalesce(NoNullText,    NoNullText,    NullyWithText));
        NoNullRet(null,        Coalesce(NoNullText,    NoNullText,    NoNullEmpty  ));
        NoNullRet(null,        Coalesce(NoNullText,    NoNullText,    NoNullSpace  ));
        NoNullRet(null,        Coalesce(NoNullText,    NoNullText,    NoNullText   ));

        NoNullRet(null,        Coalesce(NullText,      NullText,      NullText,      trimSpace: false));
        NoNullRet(null,        Coalesce(NullText,      NullText,      NullyEmpty,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullText,      NullText,      NullySpace,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullText,      NullText,      NullyWithText, trimSpace: false));
        NoNullRet(null,        Coalesce(NullText,      NullText,      NoNullEmpty,   trimSpace: false));
        NoNullRet(null,        Coalesce(NullText,      NullText,      NoNullSpace,   trimSpace: false));
        NoNullRet(null,        Coalesce(NullText,      NullText,      NoNullText,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullText,      NullyEmpty,    NullText,      trimSpace: false));
        NoNullRet(null,        Coalesce(NullText,      NullyEmpty,    NullyEmpty,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullText,      NullyEmpty,    NullySpace,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullText,      NullyEmpty,    NullyWithText, trimSpace: false));
        NoNullRet(null,        Coalesce(NullText,      NullyEmpty,    NoNullEmpty,   trimSpace: false));
        NoNullRet(null,        Coalesce(NullText,      NullyEmpty,    NoNullSpace,   trimSpace: false));
        NoNullRet(null,        Coalesce(NullText,      NullyEmpty,    NoNullText,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullText,      NullySpace,    NullText,      trimSpace: false));
        NoNullRet(null,        Coalesce(NullText,      NullySpace,    NullyEmpty,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullText,      NullySpace,    NullySpace,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullText,      NullySpace,    NullyWithText, trimSpace: false));
        NoNullRet(null,        Coalesce(NullText,      NullySpace,    NoNullEmpty,   trimSpace: false));
        NoNullRet(null,        Coalesce(NullText,      NullySpace,    NoNullSpace,   trimSpace: false));
        NoNullRet(null,        Coalesce(NullText,      NullySpace,    NoNullText,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullText,      NullyWithText, NullText,      trimSpace: false));
        NoNullRet(null,        Coalesce(NullText,      NullyWithText, NullyEmpty,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullText,      NullyWithText, NullySpace,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullText,      NullyWithText, NullyWithText, trimSpace: false));
        NoNullRet(null,        Coalesce(NullText,      NullyWithText, NoNullEmpty,   trimSpace: false));
        NoNullRet(null,        Coalesce(NullText,      NullyWithText, NoNullSpace,   trimSpace: false));
        NoNullRet(null,        Coalesce(NullText,      NullyWithText, NoNullText,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullText,      NoNullEmpty,   NullText,      trimSpace: false));
        NoNullRet(null,        Coalesce(NullText,      NoNullEmpty,   NullyEmpty,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullText,      NoNullEmpty,   NullySpace,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullText,      NoNullEmpty,   NullyWithText, trimSpace: false));
        NoNullRet(null,        Coalesce(NullText,      NoNullEmpty,   NoNullEmpty,   trimSpace: false));
        NoNullRet(null,        Coalesce(NullText,      NoNullEmpty,   NoNullSpace,   trimSpace: false));
        NoNullRet(null,        Coalesce(NullText,      NoNullEmpty,   NoNullText,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullText,      NoNullSpace,   NullText,      trimSpace: false));
        NoNullRet(null,        Coalesce(NullText,      NoNullSpace,   NullyEmpty,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullText,      NoNullSpace,   NullySpace,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullText,      NoNullSpace,   NullyWithText, trimSpace: false));
        NoNullRet(null,        Coalesce(NullText,      NoNullSpace,   NoNullEmpty,   trimSpace: false));
        NoNullRet(null,        Coalesce(NullText,      NoNullSpace,   NoNullSpace,   trimSpace: false));
        NoNullRet(null,        Coalesce(NullText,      NoNullSpace,   NoNullText,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullText,      NoNullText,    NullText,      trimSpace: false));
        NoNullRet(null,        Coalesce(NullText,      NoNullText,    NullyEmpty,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullText,      NoNullText,    NullySpace,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullText,      NoNullText,    NullyWithText, trimSpace: false));
        NoNullRet(null,        Coalesce(NullText,      NoNullText,    NoNullEmpty,   trimSpace: false));
        NoNullRet(null,        Coalesce(NullText,      NoNullText,    NoNullSpace,   trimSpace: false));
        NoNullRet(null,        Coalesce(NullText,      NoNullText,    NoNullText,    trimSpace: false));
        
        NoNullRet(null,        Coalesce(NullyEmpty,    NullText,      NullText,      trimSpace: false));
        NoNullRet(null,        Coalesce(NullyEmpty,    NullText,      NullyEmpty,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullyEmpty,    NullText,      NullySpace,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullyEmpty,    NullText,      NullyWithText, trimSpace: false));
        NoNullRet(null,        Coalesce(NullyEmpty,    NullText,      NoNullEmpty,   trimSpace: false));
        NoNullRet(null,        Coalesce(NullyEmpty,    NullText,      NoNullSpace,   trimSpace: false));
        NoNullRet(null,        Coalesce(NullyEmpty,    NullText,      NoNullText,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullyEmpty,    NullyEmpty,    NullText,      trimSpace: false));
        NoNullRet(null,        Coalesce(NullyEmpty,    NullyEmpty,    NullyEmpty,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullyEmpty,    NullyEmpty,    NullySpace,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullyEmpty,    NullyEmpty,    NullyWithText, trimSpace: false));
        NoNullRet(null,        Coalesce(NullyEmpty,    NullyEmpty,    NoNullEmpty,   trimSpace: false));
        NoNullRet(null,        Coalesce(NullyEmpty,    NullyEmpty,    NoNullSpace,   trimSpace: false));
        NoNullRet(null,        Coalesce(NullyEmpty,    NullyEmpty,    NoNullText,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullyEmpty,    NullySpace,    NullText,      trimSpace: false));
        NoNullRet(null,        Coalesce(NullyEmpty,    NullySpace,    NullyEmpty,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullyEmpty,    NullySpace,    NullySpace,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullyEmpty,    NullySpace,    NullyWithText, trimSpace: false));
        NoNullRet(null,        Coalesce(NullyEmpty,    NullySpace,    NoNullEmpty,   trimSpace: false));
        NoNullRet(null,        Coalesce(NullyEmpty,    NullySpace,    NoNullSpace,   trimSpace: false));
        NoNullRet(null,        Coalesce(NullyEmpty,    NullySpace,    NoNullText,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullyEmpty,    NullyWithText, NullText,      trimSpace: false));
        NoNullRet(null,        Coalesce(NullyEmpty,    NullyWithText, NullyEmpty,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullyEmpty,    NullyWithText, NullySpace,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullyEmpty,    NullyWithText, NullyWithText, trimSpace: false));
        NoNullRet(null,        Coalesce(NullyEmpty,    NullyWithText, NoNullEmpty,   trimSpace: false));
        NoNullRet(null,        Coalesce(NullyEmpty,    NullyWithText, NoNullSpace,   trimSpace: false));
        NoNullRet(null,        Coalesce(NullyEmpty,    NullyWithText, NoNullText,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullyEmpty,    NoNullEmpty,   NullText,      trimSpace: false));
        NoNullRet(null,        Coalesce(NullyEmpty,    NoNullEmpty,   NullyEmpty,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullyEmpty,    NoNullEmpty,   NullySpace,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullyEmpty,    NoNullEmpty,   NullyWithText, trimSpace: false));
        NoNullRet(null,        Coalesce(NullyEmpty,    NoNullEmpty,   NoNullEmpty,   trimSpace: false));
        NoNullRet(null,        Coalesce(NullyEmpty,    NoNullEmpty,   NoNullSpace,   trimSpace: false));
        NoNullRet(null,        Coalesce(NullyEmpty,    NoNullEmpty,   NoNullText,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullyEmpty,    NoNullSpace,   NullText,      trimSpace: false));
        NoNullRet(null,        Coalesce(NullyEmpty,    NoNullSpace,   NullyEmpty,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullyEmpty,    NoNullSpace,   NullySpace,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullyEmpty,    NoNullSpace,   NullyWithText, trimSpace: false));
        NoNullRet(null,        Coalesce(NullyEmpty,    NoNullSpace,   NoNullEmpty,   trimSpace: false));
        NoNullRet(null,        Coalesce(NullyEmpty,    NoNullSpace,   NoNullSpace,   trimSpace: false));
        NoNullRet(null,        Coalesce(NullyEmpty,    NoNullSpace,   NoNullText,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullyEmpty,    NoNullText,    NullText,      trimSpace: false));
        NoNullRet(null,        Coalesce(NullyEmpty,    NoNullText,    NullyEmpty,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullyEmpty,    NoNullText,    NullySpace,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullyEmpty,    NoNullText,    NullyWithText, trimSpace: false));
        NoNullRet(null,        Coalesce(NullyEmpty,    NoNullText,    NoNullEmpty,   trimSpace: false));
        NoNullRet(null,        Coalesce(NullyEmpty,    NoNullText,    NoNullSpace,   trimSpace: false));
        NoNullRet(null,        Coalesce(NullyEmpty,    NoNullText,    NoNullText,    trimSpace: false));

        NoNullRet(null,        Coalesce(NullySpace,    NullText,      NullText,      trimSpace: false));
        NoNullRet(null,        Coalesce(NullySpace,    NullText,      NullyEmpty,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullySpace,    NullText,      NullySpace,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullySpace,    NullText,      NullyWithText, trimSpace: false));
        NoNullRet(null,        Coalesce(NullySpace,    NullText,      NoNullEmpty,   trimSpace: false));
        NoNullRet(null,        Coalesce(NullySpace,    NullText,      NoNullSpace,   trimSpace: false));
        NoNullRet(null,        Coalesce(NullySpace,    NullText,      NoNullText,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullySpace,    NullyEmpty,    NullText,      trimSpace: false));
        NoNullRet(null,        Coalesce(NullySpace,    NullyEmpty,    NullyEmpty,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullySpace,    NullyEmpty,    NullySpace,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullySpace,    NullyEmpty,    NullyWithText, trimSpace: false));
        NoNullRet(null,        Coalesce(NullySpace,    NullyEmpty,    NoNullEmpty,   trimSpace: false));
        NoNullRet(null,        Coalesce(NullySpace,    NullyEmpty,    NoNullSpace,   trimSpace: false));
        NoNullRet(null,        Coalesce(NullySpace,    NullyEmpty,    NoNullText,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullySpace,    NullySpace,    NullText,      trimSpace: false));
        NoNullRet(null,        Coalesce(NullySpace,    NullySpace,    NullyEmpty,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullySpace,    NullySpace,    NullySpace,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullySpace,    NullySpace,    NullyWithText, trimSpace: false));
        NoNullRet(null,        Coalesce(NullySpace,    NullySpace,    NoNullEmpty,   trimSpace: false));
        NoNullRet(null,        Coalesce(NullySpace,    NullySpace,    NoNullSpace,   trimSpace: false));
        NoNullRet(null,        Coalesce(NullySpace,    NullySpace,    NoNullText,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullySpace,    NullyWithText, NullText,      trimSpace: false));
        NoNullRet(null,        Coalesce(NullySpace,    NullyWithText, NullyEmpty,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullySpace,    NullyWithText, NullySpace,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullySpace,    NullyWithText, NullyWithText, trimSpace: false));
        NoNullRet(null,        Coalesce(NullySpace,    NullyWithText, NoNullEmpty,   trimSpace: false));
        NoNullRet(null,        Coalesce(NullySpace,    NullyWithText, NoNullSpace,   trimSpace: false));
        NoNullRet(null,        Coalesce(NullySpace,    NullyWithText, NoNullText,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullySpace,    NoNullEmpty,   NullText,      trimSpace: false));
        NoNullRet(null,        Coalesce(NullySpace,    NoNullEmpty,   NullyEmpty,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullySpace,    NoNullEmpty,   NullySpace,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullySpace,    NoNullEmpty,   NullyWithText, trimSpace: false));
        NoNullRet(null,        Coalesce(NullySpace,    NoNullEmpty,   NoNullEmpty,   trimSpace: false));
        NoNullRet(null,        Coalesce(NullySpace,    NoNullEmpty,   NoNullSpace,   trimSpace: false));
        NoNullRet(null,        Coalesce(NullySpace,    NoNullEmpty,   NoNullText,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullySpace,    NoNullSpace,   NullText,      trimSpace: false));
        NoNullRet(null,        Coalesce(NullySpace,    NoNullSpace,   NullyEmpty,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullySpace,    NoNullSpace,   NullySpace,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullySpace,    NoNullSpace,   NullyWithText, trimSpace: false));
        NoNullRet(null,        Coalesce(NullySpace,    NoNullSpace,   NoNullEmpty,   trimSpace: false));
        NoNullRet(null,        Coalesce(NullySpace,    NoNullSpace,   NoNullSpace,   trimSpace: false));
        NoNullRet(null,        Coalesce(NullySpace,    NoNullSpace,   NoNullText,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullySpace,    NoNullText,    NullText,      trimSpace: false));
        NoNullRet(null,        Coalesce(NullySpace,    NoNullText,    NullyEmpty,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullySpace,    NoNullText,    NullySpace,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullySpace,    NoNullText,    NullyWithText, trimSpace: false));
        NoNullRet(null,        Coalesce(NullySpace,    NoNullText,    NoNullEmpty,   trimSpace: false));
        NoNullRet(null,        Coalesce(NullySpace,    NoNullText,    NoNullSpace,   trimSpace: false));
        NoNullRet(null,        Coalesce(NullySpace,    NoNullText,    NoNullText,    trimSpace: false));

        NoNullRet(null,        Coalesce(NullyWithText, NullText,      NullText,      trimSpace: false));
        NoNullRet(null,        Coalesce(NullyWithText, NullText,      NullyEmpty,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullyWithText, NullText,      NullySpace,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullyWithText, NullText,      NullyWithText, trimSpace: false));
        NoNullRet(null,        Coalesce(NullyWithText, NullText,      NoNullEmpty,   trimSpace: false));
        NoNullRet(null,        Coalesce(NullyWithText, NullText,      NoNullSpace,   trimSpace: false));
        NoNullRet(null,        Coalesce(NullyWithText, NullText,      NoNullText,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullyWithText, NullyEmpty,    NullText,      trimSpace: false));
        NoNullRet(null,        Coalesce(NullyWithText, NullyEmpty,    NullyEmpty,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullyWithText, NullyEmpty,    NullySpace,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullyWithText, NullyEmpty,    NullyWithText, trimSpace: false));
        NoNullRet(null,        Coalesce(NullyWithText, NullyEmpty,    NoNullEmpty,   trimSpace: false));
        NoNullRet(null,        Coalesce(NullyWithText, NullyEmpty,    NoNullSpace,   trimSpace: false));
        NoNullRet(null,        Coalesce(NullyWithText, NullyEmpty,    NoNullText,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullyWithText, NullySpace,    NullText,      trimSpace: false));
        NoNullRet(null,        Coalesce(NullyWithText, NullySpace,    NullyEmpty,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullyWithText, NullySpace,    NullySpace,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullyWithText, NullySpace,    NullyWithText, trimSpace: false));
        NoNullRet(null,        Coalesce(NullyWithText, NullySpace,    NoNullEmpty,   trimSpace: false));
        NoNullRet(null,        Coalesce(NullyWithText, NullySpace,    NoNullSpace,   trimSpace: false));
        NoNullRet(null,        Coalesce(NullyWithText, NullySpace,    NoNullText,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullyWithText, NullyWithText, NullText,      trimSpace: false));
        NoNullRet(null,        Coalesce(NullyWithText, NullyWithText, NullyEmpty,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullyWithText, NullyWithText, NullySpace,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullyWithText, NullyWithText, NullyWithText, trimSpace: false));
        NoNullRet(null,        Coalesce(NullyWithText, NullyWithText, NoNullEmpty,   trimSpace: false));
        NoNullRet(null,        Coalesce(NullyWithText, NullyWithText, NoNullSpace,   trimSpace: false));
        NoNullRet(null,        Coalesce(NullyWithText, NullyWithText, NoNullText,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullyWithText, NoNullEmpty,   NullText,      trimSpace: false));
        NoNullRet(null,        Coalesce(NullyWithText, NoNullEmpty,   NullyEmpty,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullyWithText, NoNullEmpty,   NullySpace,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullyWithText, NoNullEmpty,   NullyWithText, trimSpace: false));
        NoNullRet(null,        Coalesce(NullyWithText, NoNullEmpty,   NoNullEmpty,   trimSpace: false));
        NoNullRet(null,        Coalesce(NullyWithText, NoNullEmpty,   NoNullSpace,   trimSpace: false));
        NoNullRet(null,        Coalesce(NullyWithText, NoNullEmpty,   NoNullText,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullyWithText, NoNullSpace,   NullText,      trimSpace: false));
        NoNullRet(null,        Coalesce(NullyWithText, NoNullSpace,   NullyEmpty,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullyWithText, NoNullSpace,   NullySpace,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullyWithText, NoNullSpace,   NullyWithText, trimSpace: false));
        NoNullRet(null,        Coalesce(NullyWithText, NoNullSpace,   NoNullEmpty,   trimSpace: false));
        NoNullRet(null,        Coalesce(NullyWithText, NoNullSpace,   NoNullSpace,   trimSpace: false));
        NoNullRet(null,        Coalesce(NullyWithText, NoNullSpace,   NoNullText,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullyWithText, NoNullText,    NullText,      trimSpace: false));
        NoNullRet(null,        Coalesce(NullyWithText, NoNullText,    NullyEmpty,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullyWithText, NoNullText,    NullySpace,    trimSpace: false));
        NoNullRet(null,        Coalesce(NullyWithText, NoNullText,    NullyWithText, trimSpace: false));
        NoNullRet(null,        Coalesce(NullyWithText, NoNullText,    NoNullEmpty,   trimSpace: false));
        NoNullRet(null,        Coalesce(NullyWithText, NoNullText,    NoNullSpace,   trimSpace: false));
        NoNullRet(null,        Coalesce(NullyWithText, NoNullText,    NoNullText,    trimSpace: false));

        NoNullRet(null,        Coalesce(NoNullEmpty,   NullText,      NullText,      trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NullText,      NullyEmpty,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NullText,      NullySpace,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NullText,      NullyWithText, trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NullText,      NoNullEmpty,   trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NullText,      NoNullSpace,   trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NullText,      NoNullText,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NullyEmpty,    NullText,      trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NullyEmpty,    NullyEmpty,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NullyEmpty,    NullySpace,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NullyEmpty,    NullyWithText, trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NullyEmpty,    NoNullEmpty,   trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NullyEmpty,    NoNullSpace,   trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NullyEmpty,    NoNullText,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NullySpace,    NullText,      trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NullySpace,    NullyEmpty,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NullySpace,    NullySpace,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NullySpace,    NullyWithText, trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NullySpace,    NoNullEmpty,   trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NullySpace,    NoNullSpace,   trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NullySpace,    NoNullText,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NullyWithText, NullText,      trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NullyWithText, NullyEmpty,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NullyWithText, NullySpace,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NullyWithText, NullyWithText, trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NullyWithText, NoNullEmpty,   trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NullyWithText, NoNullSpace,   trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NullyWithText, NoNullText,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NoNullEmpty,   NullText,      trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NoNullEmpty,   NullyEmpty,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NoNullEmpty,   NullySpace,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NoNullEmpty,   NullyWithText, trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NoNullEmpty,   NoNullEmpty,   trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NoNullEmpty,   NoNullSpace,   trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NoNullEmpty,   NoNullText,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NoNullSpace,   NullText,      trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NoNullSpace,   NullyEmpty,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NoNullSpace,   NullySpace,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NoNullSpace,   NullyWithText, trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NoNullSpace,   NoNullEmpty,   trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NoNullSpace,   NoNullSpace,   trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NoNullSpace,   NoNullText,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NoNullText,    NullText,      trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NoNullText,    NullyEmpty,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NoNullText,    NullySpace,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NoNullText,    NullyWithText, trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NoNullText,    NoNullEmpty,   trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NoNullText,    NoNullSpace,   trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullEmpty,   NoNullText,    NoNullText,    trimSpace: false));
                                                                      
        NoNullRet(null,        Coalesce(NoNullSpace,   NullText,      NullText,      trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullSpace,   NullText,      NullyEmpty,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullSpace,   NullText,      NullySpace,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullSpace,   NullText,      NullyWithText, trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullSpace,   NullText,      NoNullEmpty,   trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullSpace,   NullText,      NoNullSpace,   trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullSpace,   NullText,      NoNullText,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullSpace,   NullyEmpty,    NullText,      trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullSpace,   NullyEmpty,    NullyEmpty,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullSpace,   NullyEmpty,    NullySpace,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullSpace,   NullyEmpty,    NullyWithText, trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullSpace,   NullyEmpty,    NoNullEmpty,   trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullSpace,   NullyEmpty,    NoNullSpace,   trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullSpace,   NullyEmpty,    NoNullText,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullSpace,   NullySpace,    NullText,      trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullSpace,   NullySpace,    NullyEmpty,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullSpace,   NullySpace,    NullySpace,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullSpace,   NullySpace,    NullyWithText, trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullSpace,   NullySpace,    NoNullEmpty,   trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullSpace,   NullySpace,    NoNullSpace,   trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullSpace,   NullySpace,    NoNullText,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullSpace,   NullyWithText, NullText,      trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullSpace,   NullyWithText, NullyEmpty,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullSpace,   NullyWithText, NullySpace,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullSpace,   NullyWithText, NullyWithText, trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullSpace,   NullyWithText, NoNullEmpty,   trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullSpace,   NullyWithText, NoNullSpace,   trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullSpace,   NullyWithText, NoNullText,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullSpace,   NoNullEmpty,   NullText,      trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullSpace,   NoNullEmpty,   NullyEmpty,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullSpace,   NoNullEmpty,   NullySpace,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullSpace,   NoNullEmpty,   NullyWithText, trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullSpace,   NoNullEmpty,   NoNullEmpty,   trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullSpace,   NoNullEmpty,   NoNullSpace,   trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullSpace,   NoNullEmpty,   NoNullText,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullSpace,   NoNullSpace,   NullText,      trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullSpace,   NoNullSpace,   NullyEmpty,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullSpace,   NoNullSpace,   NullySpace,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullSpace,   NoNullSpace,   NullyWithText, trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullSpace,   NoNullSpace,   NoNullEmpty,   trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullSpace,   NoNullSpace,   NoNullSpace,   trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullSpace,   NoNullSpace,   NoNullText,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullSpace,   NoNullText,    NullText,      trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullSpace,   NoNullText,    NullyEmpty,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullSpace,   NoNullText,    NullySpace,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullSpace,   NoNullText,    NullyWithText, trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullSpace,   NoNullText,    NoNullEmpty,   trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullSpace,   NoNullText,    NoNullSpace,   trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullSpace,   NoNullText,    NoNullText,    trimSpace: false));
                                                                      
        NoNullRet(null,        Coalesce(NoNullText,    NullText,      NullText,      trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullText,    NullText,      NullyEmpty,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullText,    NullText,      NullySpace,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullText,    NullText,      NullyWithText, trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullText,    NullText,      NoNullEmpty,   trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullText,    NullText,      NoNullSpace,   trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullText,    NullText,      NoNullText,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullText,    NullyEmpty,    NullText,      trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullText,    NullyEmpty,    NullyEmpty,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullText,    NullyEmpty,    NullySpace,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullText,    NullyEmpty,    NullyWithText, trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullText,    NullyEmpty,    NoNullEmpty,   trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullText,    NullyEmpty,    NoNullSpace,   trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullText,    NullyEmpty,    NoNullText,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullText,    NullySpace,    NullText,      trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullText,    NullySpace,    NullyEmpty,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullText,    NullySpace,    NullySpace,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullText,    NullySpace,    NullyWithText, trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullText,    NullySpace,    NoNullEmpty,   trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullText,    NullySpace,    NoNullSpace,   trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullText,    NullySpace,    NoNullText,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullText,    NullyWithText, NullText,      trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullText,    NullyWithText, NullyEmpty,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullText,    NullyWithText, NullySpace,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullText,    NullyWithText, NullyWithText, trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullText,    NullyWithText, NoNullEmpty,   trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullText,    NullyWithText, NoNullSpace,   trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullText,    NullyWithText, NoNullText,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullText,    NoNullEmpty,   NullText,      trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullText,    NoNullEmpty,   NullyEmpty,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullText,    NoNullEmpty,   NullySpace,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullText,    NoNullEmpty,   NullyWithText, trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullText,    NoNullEmpty,   NoNullEmpty,   trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullText,    NoNullEmpty,   NoNullSpace,   trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullText,    NoNullEmpty,   NoNullText,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullText,    NoNullSpace,   NullText,      trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullText,    NoNullSpace,   NullyEmpty,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullText,    NoNullSpace,   NullySpace,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullText,    NoNullSpace,   NullyWithText, trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullText,    NoNullSpace,   NoNullEmpty,   trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullText,    NoNullSpace,   NoNullSpace,   trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullText,    NoNullSpace,   NoNullText,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullText,    NoNullText,    NullText,      trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullText,    NoNullText,    NullyEmpty,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullText,    NoNullText,    NullySpace,    trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullText,    NoNullText,    NullyWithText, trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullText,    NoNullText,    NoNullEmpty,   trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullText,    NoNullText,    NoNullSpace,   trimSpace: false));
        NoNullRet(null,        Coalesce(NoNullText,    NoNullText,    NoNullText,    trimSpace: false));
    }
}