namespace JJ.Framework.Existence.Core.Tests;

[TestClass]
public class Coalesce_3Args_StringBuilderToText : TestBase
{
    // TODO: Adjust this copied code to StringBuilder handling.
    
    //public static StringBuilder? NullSB = null;
    //public static StringBuilder  SpaceSB = new(" ");
    //public static StringBuilder? NullySpaceSB = SpaceSB;
    //public static StringBuilder  FilledSB = new("FilledSB");
    //public static StringBuilder? NullyFilledSB  = FilledSB;
    
    // TODO: Add these to the test matrix too. They may follow different (optimization) paths.
    public static StringBuilder  EmptySB       = new("");
    public static StringBuilder? NullyEmptySB  = EmptySB;
  
    [TestMethod]
    public void Coalesce_3Args_ValsToString_Static()
    {
        NoNullRet("",         Coalesce(NullSB,        NullSB,        NullText  ));
        NoNullRet("",         Coalesce(NullSB,        NullSB,        Empty     ));
        NoNullRet(" ",        Coalesce(NullSB,        NullSB,        Space     ));
        NoNullRet(Text,       Coalesce(NullSB,        NullSB,        Text      ));
        NoNullRet("",         Coalesce(NullSB,        NullSB,        NullyEmpty));
        NoNullRet(" ",        Coalesce(NullSB,        NullSB,        NullySpace));
        NoNullRet(Text,       Coalesce(NullSB,        NullSB,        NullyText ));
        NoNullRet("",         Coalesce(NullSB,        NullySpaceSB,  NullText  ));
        NoNullRet("",         Coalesce(NullSB,        NullySpaceSB,  Empty     ));
        NoNullRet(" ",        Coalesce(NullSB,        NullySpaceSB,  Space     ));
        NoNullRet(Text,       Coalesce(NullSB,        NullySpaceSB,  Text      ));
        NoNullRet("",         Coalesce(NullSB,        NullySpaceSB,  NullyEmpty));
        NoNullRet(" ",        Coalesce(NullSB,        NullySpaceSB,  NullySpace));
        NoNullRet(Text,       Coalesce(NullSB,        NullySpaceSB,  NullyText ));
        NoNullRet("FilledSB", Coalesce(NullSB,        NullyFilledSB, NullText  ));
        NoNullRet("FilledSB", Coalesce(NullSB,        NullyFilledSB, Empty     ));
        NoNullRet("FilledSB", Coalesce(NullSB,        NullyFilledSB, Space     ));
        NoNullRet("FilledSB", Coalesce(NullSB,        NullyFilledSB, Text      ));
        NoNullRet("FilledSB", Coalesce(NullSB,        NullyFilledSB, NullyEmpty));
        NoNullRet("FilledSB", Coalesce(NullSB,        NullyFilledSB, NullySpace));
        NoNullRet("FilledSB", Coalesce(NullSB,        NullyFilledSB, NullyText ));
        NoNullRet("",         Coalesce(NullSB,        SpaceSB,       NullText  ));
        NoNullRet("",         Coalesce(NullSB,        SpaceSB,       Empty     ));
        NoNullRet(" ",        Coalesce(NullSB,        SpaceSB,       Space     ));
        NoNullRet(Text,       Coalesce(NullSB,        SpaceSB,       Text      ));
        NoNullRet("",         Coalesce(NullSB,        SpaceSB,       NullyEmpty));
        NoNullRet(" ",        Coalesce(NullSB,        SpaceSB,       NullySpace));
        NoNullRet(Text,       Coalesce(NullSB,        SpaceSB,       NullyText ));
        NoNullRet("FilledSB", Coalesce(NullSB,        FilledSB,      NullText  ));
        NoNullRet("FilledSB", Coalesce(NullSB,        FilledSB,      Empty     ));
        NoNullRet("FilledSB", Coalesce(NullSB,        FilledSB,      Space     ));
        NoNullRet("FilledSB", Coalesce(NullSB,        FilledSB,      Text      ));
        NoNullRet("FilledSB", Coalesce(NullSB,        FilledSB,      NullyEmpty));
        NoNullRet("FilledSB", Coalesce(NullSB,        FilledSB,      NullySpace));
        NoNullRet("FilledSB", Coalesce(NullSB,        FilledSB,      NullyText ));
        
        NoNullRet("",         Coalesce(NullySpaceSB,  NullSB,        NullText  ));
        NoNullRet("",         Coalesce(NullySpaceSB,  NullSB,        Empty     ));
        NoNullRet(" ",        Coalesce(NullySpaceSB,  NullSB,        Space     ));
        NoNullRet(Text,       Coalesce(NullySpaceSB,  NullSB,        Text      ));
        NoNullRet("",         Coalesce(NullySpaceSB,  NullSB,        NullyEmpty));
        NoNullRet(" ",        Coalesce(NullySpaceSB,  NullSB,        NullySpace));
        NoNullRet(Text,       Coalesce(NullySpaceSB,  NullSB,        NullyText ));
        NoNullRet("",         Coalesce(NullySpaceSB,  NullySpaceSB,  NullText  ));
        NoNullRet("",         Coalesce(NullySpaceSB,  NullySpaceSB,  Empty     ));
        NoNullRet(" ",        Coalesce(NullySpaceSB,  NullySpaceSB,  Space     ));
        NoNullRet(Text,       Coalesce(NullySpaceSB,  NullySpaceSB,  Text      ));
        NoNullRet("",         Coalesce(NullySpaceSB,  NullySpaceSB,  NullyEmpty));
        NoNullRet(" ",        Coalesce(NullySpaceSB,  NullySpaceSB,  NullySpace));
        NoNullRet(Text,       Coalesce(NullySpaceSB,  NullySpaceSB,  NullyText ));
        NoNullRet("FilledSB", Coalesce(NullySpaceSB,  NullyFilledSB, NullText  ));
        NoNullRet("FilledSB", Coalesce(NullySpaceSB,  NullyFilledSB, Empty     ));
        NoNullRet("FilledSB", Coalesce(NullySpaceSB,  NullyFilledSB, Space     ));
        NoNullRet("FilledSB", Coalesce(NullySpaceSB,  NullyFilledSB, Text      ));
        NoNullRet("FilledSB", Coalesce(NullySpaceSB,  NullyFilledSB, NullyEmpty));
        NoNullRet("FilledSB", Coalesce(NullySpaceSB,  NullyFilledSB, NullySpace));
        NoNullRet("FilledSB", Coalesce(NullySpaceSB,  NullyFilledSB, NullyText ));
        NoNullRet("",         Coalesce(NullySpaceSB,  SpaceSB,       NullText  ));
        NoNullRet("",         Coalesce(NullySpaceSB,  SpaceSB,       Empty     ));
        NoNullRet(" ",        Coalesce(NullySpaceSB,  SpaceSB,       Space     ));
        NoNullRet(Text,       Coalesce(NullySpaceSB,  SpaceSB,       Text      ));
        NoNullRet("",         Coalesce(NullySpaceSB,  SpaceSB,       NullyEmpty));
        NoNullRet(" ",        Coalesce(NullySpaceSB,  SpaceSB,       NullySpace));
        NoNullRet(Text,       Coalesce(NullySpaceSB,  SpaceSB,       NullyText ));
        NoNullRet("FilledSB", Coalesce(NullySpaceSB,  FilledSB,      NullText  ));
        NoNullRet("FilledSB", Coalesce(NullySpaceSB,  FilledSB,      Empty     ));
        NoNullRet("FilledSB", Coalesce(NullySpaceSB,  FilledSB,      Space     ));
        NoNullRet("FilledSB", Coalesce(NullySpaceSB,  FilledSB,      Text      ));
        NoNullRet("FilledSB", Coalesce(NullySpaceSB,  FilledSB,      NullyEmpty));
        NoNullRet("FilledSB", Coalesce(NullySpaceSB,  FilledSB,      NullySpace));
        NoNullRet("FilledSB", Coalesce(NullySpaceSB,  FilledSB,      NullyText ));
        
        NoNullRet("FilledSB", Coalesce(NullyFilledSB, NullSB,        NullText  ));
        NoNullRet("FilledSB", Coalesce(NullyFilledSB, NullSB,        Empty     ));
        NoNullRet("FilledSB", Coalesce(NullyFilledSB, NullSB,        Space     ));
        NoNullRet("FilledSB", Coalesce(NullyFilledSB, NullSB,        Text      ));
        NoNullRet("FilledSB", Coalesce(NullyFilledSB, NullSB,        NullyEmpty));
        NoNullRet("FilledSB", Coalesce(NullyFilledSB, NullSB,        NullySpace));
        NoNullRet("FilledSB", Coalesce(NullyFilledSB, NullSB,        NullyText ));
        NoNullRet("FilledSB", Coalesce(NullyFilledSB, NullySpaceSB,  NullText  ));
        NoNullRet("FilledSB", Coalesce(NullyFilledSB, NullySpaceSB,  Empty     ));
        NoNullRet("FilledSB", Coalesce(NullyFilledSB, NullySpaceSB,  Space     ));
        NoNullRet("FilledSB", Coalesce(NullyFilledSB, NullySpaceSB,  Text      ));
        NoNullRet("FilledSB", Coalesce(NullyFilledSB, NullySpaceSB,  NullyEmpty));
        NoNullRet("FilledSB", Coalesce(NullyFilledSB, NullySpaceSB,  NullySpace));
        NoNullRet("FilledSB", Coalesce(NullyFilledSB, NullySpaceSB,  NullyText ));
        NoNullRet("FilledSB", Coalesce(NullyFilledSB, NullyFilledSB, NullText  ));
        NoNullRet("FilledSB", Coalesce(NullyFilledSB, NullyFilledSB, Empty     ));
        NoNullRet("FilledSB", Coalesce(NullyFilledSB, NullyFilledSB, Space     ));
        NoNullRet("FilledSB", Coalesce(NullyFilledSB, NullyFilledSB, Text      ));
        NoNullRet("FilledSB", Coalesce(NullyFilledSB, NullyFilledSB, NullyEmpty));
        NoNullRet("FilledSB", Coalesce(NullyFilledSB, NullyFilledSB, NullySpace));
        NoNullRet("FilledSB", Coalesce(NullyFilledSB, NullyFilledSB, NullyText ));
        NoNullRet("FilledSB", Coalesce(NullyFilledSB, SpaceSB,       NullText  ));
        NoNullRet("FilledSB", Coalesce(NullyFilledSB, SpaceSB,       Empty     ));
        NoNullRet("FilledSB", Coalesce(NullyFilledSB, SpaceSB,       Space     ));
        NoNullRet("FilledSB", Coalesce(NullyFilledSB, SpaceSB,       Text      ));
        NoNullRet("FilledSB", Coalesce(NullyFilledSB, SpaceSB,       NullyEmpty));
        NoNullRet("FilledSB", Coalesce(NullyFilledSB, SpaceSB,       NullySpace));
        NoNullRet("FilledSB", Coalesce(NullyFilledSB, SpaceSB,       NullyText ));
        NoNullRet("FilledSB", Coalesce(NullyFilledSB, FilledSB,      NullText  ));
        NoNullRet("FilledSB", Coalesce(NullyFilledSB, FilledSB,      Empty     ));
        NoNullRet("FilledSB", Coalesce(NullyFilledSB, FilledSB,      Space     ));
        NoNullRet("FilledSB", Coalesce(NullyFilledSB, FilledSB,      Text      ));
        NoNullRet("FilledSB", Coalesce(NullyFilledSB, FilledSB,      NullyEmpty));
        NoNullRet("FilledSB", Coalesce(NullyFilledSB, FilledSB,      NullySpace));
        NoNullRet("FilledSB", Coalesce(NullyFilledSB, FilledSB,      NullyText ));
        
        NoNullRet("",         Coalesce(SpaceSB,       NullSB,        NullText  ));
        NoNullRet("",         Coalesce(SpaceSB,       NullSB,        Empty     ));
        NoNullRet(" ",        Coalesce(SpaceSB,       NullSB,        Space     ));
        NoNullRet(Text,       Coalesce(SpaceSB,       NullSB,        Text      ));
        NoNullRet("",         Coalesce(SpaceSB,       NullSB,        NullyEmpty));
        NoNullRet(" ",        Coalesce(SpaceSB,       NullSB,        NullySpace));
        NoNullRet(Text,       Coalesce(SpaceSB,       NullSB,        NullyText ));
        NoNullRet("",         Coalesce(SpaceSB,       NullySpaceSB,  NullText  ));
        NoNullRet("",         Coalesce(SpaceSB,       NullySpaceSB,  Empty     ));
        NoNullRet(" ",        Coalesce(SpaceSB,       NullySpaceSB,  Space     ));
        NoNullRet(Text,       Coalesce(SpaceSB,       NullySpaceSB,  Text      ));
        NoNullRet("",         Coalesce(SpaceSB,       NullySpaceSB,  NullyEmpty));
        NoNullRet(" ",        Coalesce(SpaceSB,       NullySpaceSB,  NullySpace));
        NoNullRet(Text,       Coalesce(SpaceSB,       NullySpaceSB,  NullyText ));
        NoNullRet("FilledSB", Coalesce(SpaceSB,       NullyFilledSB, NullText  ));
        NoNullRet("FilledSB", Coalesce(SpaceSB,       NullyFilledSB, Empty     ));
        NoNullRet("FilledSB", Coalesce(SpaceSB,       NullyFilledSB, Space     ));
        NoNullRet("FilledSB", Coalesce(SpaceSB,       NullyFilledSB, Text      ));
        NoNullRet("FilledSB", Coalesce(SpaceSB,       NullyFilledSB, NullyEmpty));
        NoNullRet("FilledSB", Coalesce(SpaceSB,       NullyFilledSB, NullySpace));
        NoNullRet("FilledSB", Coalesce(SpaceSB,       NullyFilledSB, NullyText ));
        NoNullRet("",         Coalesce(SpaceSB,       SpaceSB,       NullText  ));
        NoNullRet("",         Coalesce(SpaceSB,       SpaceSB,       Empty     ));
        NoNullRet(" ",        Coalesce(SpaceSB,       SpaceSB,       Space     ));
        NoNullRet(Text,       Coalesce(SpaceSB,       SpaceSB,       Text      ));
        NoNullRet("",         Coalesce(SpaceSB,       SpaceSB,       NullyEmpty));
        NoNullRet(" ",        Coalesce(SpaceSB,       SpaceSB,       NullySpace));
        NoNullRet(Text,       Coalesce(SpaceSB,       SpaceSB,       NullyText ));
        NoNullRet("FilledSB", Coalesce(SpaceSB,       FilledSB,      NullText  ));
        NoNullRet("FilledSB", Coalesce(SpaceSB,       FilledSB,      Empty     ));
        NoNullRet("FilledSB", Coalesce(SpaceSB,       FilledSB,      Space     ));
        NoNullRet("FilledSB", Coalesce(SpaceSB,       FilledSB,      Text      ));
        NoNullRet("FilledSB", Coalesce(SpaceSB,       FilledSB,      NullyEmpty));
        NoNullRet("FilledSB", Coalesce(SpaceSB,       FilledSB,      NullySpace));
        NoNullRet("FilledSB", Coalesce(SpaceSB,       FilledSB,      NullyText ));
        
        NoNullRet("FilledSB", Coalesce(FilledSB,      NullSB,        NullText  ));
        NoNullRet("FilledSB", Coalesce(FilledSB,      NullSB,        Empty     ));
        NoNullRet("FilledSB", Coalesce(FilledSB,      NullSB,        Space     ));
        NoNullRet("FilledSB", Coalesce(FilledSB,      NullSB,        Text      ));
        NoNullRet("FilledSB", Coalesce(FilledSB,      NullSB,        NullyEmpty));
        NoNullRet("FilledSB", Coalesce(FilledSB,      NullSB,        NullySpace));
        NoNullRet("FilledSB", Coalesce(FilledSB,      NullSB,        NullyText ));
        NoNullRet("FilledSB", Coalesce(FilledSB,      NullySpaceSB,  NullText  ));
        NoNullRet("FilledSB", Coalesce(FilledSB,      NullySpaceSB,  Empty     ));
        NoNullRet("FilledSB", Coalesce(FilledSB,      NullySpaceSB,  Space     ));
        NoNullRet("FilledSB", Coalesce(FilledSB,      NullySpaceSB,  Text      ));
        NoNullRet("FilledSB", Coalesce(FilledSB,      NullySpaceSB,  NullyEmpty));
        NoNullRet("FilledSB", Coalesce(FilledSB,      NullySpaceSB,  NullySpace));
        NoNullRet("FilledSB", Coalesce(FilledSB,      NullySpaceSB,  NullyText ));
        NoNullRet("FilledSB", Coalesce(FilledSB,      NullyFilledSB, NullText  ));
        NoNullRet("FilledSB", Coalesce(FilledSB,      NullyFilledSB, Empty     ));
        NoNullRet("FilledSB", Coalesce(FilledSB,      NullyFilledSB, Space     ));
        NoNullRet("FilledSB", Coalesce(FilledSB,      NullyFilledSB, Text      ));
        NoNullRet("FilledSB", Coalesce(FilledSB,      NullyFilledSB, NullyEmpty));
        NoNullRet("FilledSB", Coalesce(FilledSB,      NullyFilledSB, NullySpace));
        NoNullRet("FilledSB", Coalesce(FilledSB,      NullyFilledSB, NullyText ));
        NoNullRet("FilledSB", Coalesce(FilledSB,      SpaceSB,       Empty     ));
        NoNullRet("FilledSB", Coalesce(FilledSB,      SpaceSB,       Space     ));
        NoNullRet("FilledSB", Coalesce(FilledSB,      SpaceSB,       Text      ));
        NoNullRet("FilledSB", Coalesce(FilledSB,      SpaceSB,       NullyEmpty));
        NoNullRet("FilledSB", Coalesce(FilledSB,      SpaceSB,       NullySpace));
        NoNullRet("FilledSB", Coalesce(FilledSB,      SpaceSB,       NullyText ));
        NoNullRet("FilledSB", Coalesce(FilledSB,      FilledSB,      NullText  ));
        NoNullRet("FilledSB", Coalesce(FilledSB,      FilledSB,      Empty     ));
        NoNullRet("FilledSB", Coalesce(FilledSB,      FilledSB,      Space     ));
        NoNullRet("FilledSB", Coalesce(FilledSB,      FilledSB,      Text      ));
        NoNullRet("FilledSB", Coalesce(FilledSB,      FilledSB,      NullyEmpty));
        NoNullRet("FilledSB", Coalesce(FilledSB,      FilledSB,      NullySpace));
        NoNullRet("FilledSB", Coalesce(FilledSB,      FilledSB,      NullyText ));
    }

    [TestMethod]
    public void Coalesce_3Args_ValsToString_Extensions()
    {
        NoNullRet("",         NullSB       .Coalesce( NullSB,        NullText  ));
        NoNullRet("",         NullSB       .Coalesce( NullSB,        Empty     ));
        NoNullRet(" ",        NullSB       .Coalesce( NullSB,        Space     ));
        NoNullRet(Text,       NullSB       .Coalesce( NullSB,        Text      ));
        NoNullRet("",         NullSB       .Coalesce( NullSB,        NullyEmpty));
        NoNullRet(" ",        NullSB       .Coalesce( NullSB,        NullySpace));
        NoNullRet(Text,       NullSB       .Coalesce( NullSB,        NullyText ));
        NoNullRet("",         NullSB       .Coalesce( NullySpaceSB,  NullText  ));
        NoNullRet("",         NullSB       .Coalesce( NullySpaceSB,  Empty     ));
        NoNullRet(" ",        NullSB       .Coalesce( NullySpaceSB,  Space     ));
        NoNullRet(Text,       NullSB       .Coalesce( NullySpaceSB,  Text      ));
        NoNullRet("",         NullSB       .Coalesce( NullySpaceSB,  NullyEmpty));
        NoNullRet(" ",        NullSB       .Coalesce( NullySpaceSB,  NullySpace));
        NoNullRet(Text,       NullSB       .Coalesce( NullySpaceSB,  NullyText ));
        NoNullRet("FilledSB", NullSB       .Coalesce( NullyFilledSB, NullText  ));
        NoNullRet("FilledSB", NullSB       .Coalesce( NullyFilledSB, Empty     ));
        NoNullRet("FilledSB", NullSB       .Coalesce( NullyFilledSB, Space     ));
        NoNullRet("FilledSB", NullSB       .Coalesce( NullyFilledSB, Text      ));
        NoNullRet("FilledSB", NullSB       .Coalesce( NullyFilledSB, NullyEmpty));
        NoNullRet("FilledSB", NullSB       .Coalesce( NullyFilledSB, NullySpace));
        NoNullRet("FilledSB", NullSB       .Coalesce( NullyFilledSB, NullyText ));
        NoNullRet("",         NullSB       .Coalesce( SpaceSB,       NullText  ));
        NoNullRet("",         NullSB       .Coalesce( SpaceSB,       Empty     ));
        NoNullRet(" ",        NullSB       .Coalesce( SpaceSB,       Space     ));
        NoNullRet(Text,       NullSB       .Coalesce( SpaceSB,       Text      ));
        NoNullRet("",         NullSB       .Coalesce( SpaceSB,       NullyEmpty));
        NoNullRet(" ",        NullSB       .Coalesce( SpaceSB,       NullySpace));
        NoNullRet(Text,       NullSB       .Coalesce( SpaceSB,       NullyText ));
        NoNullRet("FilledSB", NullSB       .Coalesce( FilledSB,      NullText  ));
        NoNullRet("FilledSB", NullSB       .Coalesce( FilledSB,      Empty     ));
        NoNullRet("FilledSB", NullSB       .Coalesce( FilledSB,      Space     ));
        NoNullRet("FilledSB", NullSB       .Coalesce( FilledSB,      Text      ));
        NoNullRet("FilledSB", NullSB       .Coalesce( FilledSB,      NullyEmpty));
        NoNullRet("FilledSB", NullSB       .Coalesce( FilledSB,      NullySpace));
        NoNullRet("FilledSB", NullSB       .Coalesce( FilledSB,      NullyText ));
                                                      
        NoNullRet("",         NullySpaceSB .Coalesce( NullSB,        NullText  ));
        NoNullRet("",         NullySpaceSB .Coalesce( NullSB,        Empty     ));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullSB,        Space     ));
        NoNullRet(Text,       NullySpaceSB .Coalesce( NullSB,        Text      ));
        NoNullRet("",         NullySpaceSB .Coalesce( NullSB,        NullyEmpty));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullSB,        NullySpace));
        NoNullRet(Text,       NullySpaceSB .Coalesce( NullSB,        NullyText ));
        NoNullRet("",         NullySpaceSB .Coalesce( NullySpaceSB,  NullText  ));
        NoNullRet("",         NullySpaceSB .Coalesce( NullySpaceSB,  Empty     ));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullySpaceSB,  Space     ));
        NoNullRet(Text,       NullySpaceSB .Coalesce( NullySpaceSB,  Text      ));
        NoNullRet("",         NullySpaceSB .Coalesce( NullySpaceSB,  NullyEmpty));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullySpaceSB,  NullySpace));
        NoNullRet(Text,       NullySpaceSB .Coalesce( NullySpaceSB,  NullyText ));
        NoNullRet("FilledSB", NullySpaceSB .Coalesce( NullyFilledSB, NullText  ));
        NoNullRet("FilledSB", NullySpaceSB .Coalesce( NullyFilledSB, Empty     ));
        NoNullRet("FilledSB", NullySpaceSB .Coalesce( NullyFilledSB, Space     ));
        NoNullRet("FilledSB", NullySpaceSB .Coalesce( NullyFilledSB, Text      ));
        NoNullRet("FilledSB", NullySpaceSB .Coalesce( NullyFilledSB, NullyEmpty));
        NoNullRet("FilledSB", NullySpaceSB .Coalesce( NullyFilledSB, NullySpace));
        NoNullRet("FilledSB", NullySpaceSB .Coalesce( NullyFilledSB, NullyText ));
        NoNullRet("",         NullySpaceSB .Coalesce( SpaceSB,       NullText  ));
        NoNullRet("",         NullySpaceSB .Coalesce( SpaceSB,       Empty     ));
        NoNullRet(" ",        NullySpaceSB .Coalesce( SpaceSB,       Space     ));
        NoNullRet(Text,       NullySpaceSB .Coalesce( SpaceSB,       Text      ));
        NoNullRet("",         NullySpaceSB .Coalesce( SpaceSB,       NullyEmpty));
        NoNullRet(" ",        NullySpaceSB .Coalesce( SpaceSB,       NullySpace));
        NoNullRet(Text,       NullySpaceSB .Coalesce( SpaceSB,       NullyText ));
        NoNullRet("FilledSB", NullySpaceSB .Coalesce( FilledSB,      NullText  ));
        NoNullRet("FilledSB", NullySpaceSB .Coalesce( FilledSB,      Empty     ));
        NoNullRet("FilledSB", NullySpaceSB .Coalesce( FilledSB,      Space     ));
        NoNullRet("FilledSB", NullySpaceSB .Coalesce( FilledSB,      Text      ));
        NoNullRet("FilledSB", NullySpaceSB .Coalesce( FilledSB,      NullyEmpty));
        NoNullRet("FilledSB", NullySpaceSB .Coalesce( FilledSB,      NullySpace));
        NoNullRet("FilledSB", NullySpaceSB .Coalesce( FilledSB,      NullyText ));
                                                      
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullSB,        NullText  ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullSB,        Empty     ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullSB,        Space     ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullSB,        Text      ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullSB,        NullyEmpty));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullSB,        NullySpace));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullSB,        NullyText ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullySpaceSB,  NullText  ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullySpaceSB,  Empty     ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullySpaceSB,  Space     ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullySpaceSB,  Text      ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullySpaceSB,  NullyEmpty));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullySpaceSB,  NullySpace));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullySpaceSB,  NullyText ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyFilledSB, NullText  ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyFilledSB, Empty     ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyFilledSB, Space     ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyFilledSB, Text      ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyFilledSB, NullyEmpty));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyFilledSB, NullySpace));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyFilledSB, NullyText ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( SpaceSB,       NullText  ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( SpaceSB,       Empty     ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( SpaceSB,       Space     ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( SpaceSB,       Text      ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( SpaceSB,       NullyEmpty));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( SpaceSB,       NullySpace));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( SpaceSB,       NullyText ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( FilledSB,      NullText  ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( FilledSB,      Empty     ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( FilledSB,      Space     ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( FilledSB,      Text      ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( FilledSB,      NullyEmpty));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( FilledSB,      NullySpace));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( FilledSB,      NullyText ));
                                                      
        NoNullRet("",         SpaceSB      .Coalesce( NullSB,        NullText  ));
        NoNullRet("",         SpaceSB      .Coalesce( NullSB,        Empty     ));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullSB,        Space     ));
        NoNullRet(Text,       SpaceSB      .Coalesce( NullSB,        Text      ));
        NoNullRet("",         SpaceSB      .Coalesce( NullSB,        NullyEmpty));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullSB,        NullySpace));
        NoNullRet(Text,       SpaceSB      .Coalesce( NullSB,        NullyText ));
        NoNullRet("",         SpaceSB      .Coalesce( NullySpaceSB,  NullText  ));
        NoNullRet("",         SpaceSB      .Coalesce( NullySpaceSB,  Empty     ));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullySpaceSB,  Space     ));
        NoNullRet(Text,       SpaceSB      .Coalesce( NullySpaceSB,  Text      ));
        NoNullRet("",         SpaceSB      .Coalesce( NullySpaceSB,  NullyEmpty));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullySpaceSB,  NullySpace));
        NoNullRet(Text,       SpaceSB      .Coalesce( NullySpaceSB,  NullyText ));
        NoNullRet("FilledSB", SpaceSB      .Coalesce( NullyFilledSB, NullText  ));
        NoNullRet("FilledSB", SpaceSB      .Coalesce( NullyFilledSB, Empty     ));
        NoNullRet("FilledSB", SpaceSB      .Coalesce( NullyFilledSB, Space     ));
        NoNullRet("FilledSB", SpaceSB      .Coalesce( NullyFilledSB, Text      ));
        NoNullRet("FilledSB", SpaceSB      .Coalesce( NullyFilledSB, NullyEmpty));
        NoNullRet("FilledSB", SpaceSB      .Coalesce( NullyFilledSB, NullySpace));
        NoNullRet("FilledSB", SpaceSB      .Coalesce( NullyFilledSB, NullyText ));
        NoNullRet("",         SpaceSB      .Coalesce( SpaceSB,       NullText  ));
        NoNullRet("",         SpaceSB      .Coalesce( SpaceSB,       Empty     ));
        NoNullRet(" ",        SpaceSB      .Coalesce( SpaceSB,       Space     ));
        NoNullRet(Text,       SpaceSB      .Coalesce( SpaceSB,       Text      ));
        NoNullRet("",         SpaceSB      .Coalesce( SpaceSB,       NullyEmpty));
        NoNullRet(" ",        SpaceSB      .Coalesce( SpaceSB,       NullySpace));
        NoNullRet(Text,       SpaceSB      .Coalesce( SpaceSB,       NullyText ));
        NoNullRet("FilledSB", SpaceSB      .Coalesce( FilledSB,      NullText  ));
        NoNullRet("FilledSB", SpaceSB      .Coalesce( FilledSB,      Empty     ));
        NoNullRet("FilledSB", SpaceSB      .Coalesce( FilledSB,      Space     ));
        NoNullRet("FilledSB", SpaceSB      .Coalesce( FilledSB,      Text      ));
        NoNullRet("FilledSB", SpaceSB      .Coalesce( FilledSB,      NullyEmpty));
        NoNullRet("FilledSB", SpaceSB      .Coalesce( FilledSB,      NullySpace));
        NoNullRet("FilledSB", SpaceSB      .Coalesce( FilledSB,      NullyText ));
                                                      
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullSB,        NullText  ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullSB,        Empty     ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullSB,        Space     ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullSB,        Text      ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullSB,        NullyEmpty));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullSB,        NullySpace));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullSB,        NullyText ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullySpaceSB,  NullText  ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullySpaceSB,  Empty     ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullySpaceSB,  Space     ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullySpaceSB,  Text      ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullySpaceSB,  NullyEmpty));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullySpaceSB,  NullySpace));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullySpaceSB,  NullyText ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyFilledSB, NullText  ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyFilledSB, Empty     ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyFilledSB, Space     ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyFilledSB, Text      ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyFilledSB, NullyEmpty));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyFilledSB, NullySpace));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyFilledSB, NullyText ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( SpaceSB,       Empty     ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( SpaceSB,       Space     ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( SpaceSB,       Text      ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( SpaceSB,       NullyEmpty));
        NoNullRet("FilledSB", FilledSB     .Coalesce( SpaceSB,       NullySpace));
        NoNullRet("FilledSB", FilledSB     .Coalesce( SpaceSB,       NullyText ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( FilledSB,      NullText  ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( FilledSB,      Empty     ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( FilledSB,      Space     ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( FilledSB,      Text      ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( FilledSB,      NullyEmpty));
        NoNullRet("FilledSB", FilledSB     .Coalesce( FilledSB,      NullySpace));
        NoNullRet("FilledSB", FilledSB     .Coalesce( FilledSB,      NullyText ));
    }
}