namespace JJ.Framework.Existence.Core.Tests;

[TestClass]
public class Coalesce_3Args_SBs_ExtensionsSpaceMattersNoExplicit
{
    [TestMethod]
    public void Coalesce_3Args_SBs_ExtensionsSpaceMattersNoExplicit_Batch1()
    {
        NoNullRet(                 NullSB       .Coalesce(NullSB,        NullSB,        spaceMatters: false));
        NoNullRet($"{EmptySB}", $"{NullSB       .Coalesce(NullSB,        NullSB,        spaceMatters: false)}");
        NoNullRet(   EmptySB,      NullSB       .Coalesce(NullSB,        NullyEmptySB,  spaceMatters: false));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(NullSB,        NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(NullSB,        NullyFilledSB, spaceMatters: false));
        NoNullRet(   EmptySB,      NullSB       .Coalesce(NullSB,        EmptySB,       spaceMatters: false));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(NullSB,        SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(NullSB,        FilledSB,      spaceMatters: false));
        NoNullRet(                 NullSB       .Coalesce(NullyEmptySB,  NullSB,        spaceMatters: false));
        NoNullRet($"{EmptySB}", $"{NullSB       .Coalesce(NullyEmptySB,  NullSB,        spaceMatters: false)}");
        NoNullRet(   EmptySB,      NullSB       .Coalesce(NullyEmptySB,  NullyEmptySB,  spaceMatters: false));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(NullyEmptySB,  NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(NullyEmptySB,  NullyFilledSB, spaceMatters: false));
        NoNullRet(   EmptySB,      NullSB       .Coalesce(NullyEmptySB,  EmptySB,       spaceMatters: false));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(NullyEmptySB,  SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(NullyEmptySB,  FilledSB,      spaceMatters: false));
        NoNullRet(                 NullSB       .Coalesce(NullySpaceSB,  NullSB,        spaceMatters: false));
        NoNullRet($"{EmptySB}", $"{NullSB       .Coalesce(NullySpaceSB,  NullSB,        spaceMatters: false)}");
        NoNullRet(   EmptySB,      NullSB       .Coalesce(NullySpaceSB,  NullyEmptySB,  spaceMatters: false));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(NullySpaceSB,  NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(NullySpaceSB,  NullyFilledSB, spaceMatters: false));
        NoNullRet(   EmptySB,      NullSB       .Coalesce(NullySpaceSB,  EmptySB,       spaceMatters: false));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(NullySpaceSB,  SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(NullySpaceSB,  FilledSB,      spaceMatters: false));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(NullyFilledSB, NullSB,        spaceMatters: false));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(NullyFilledSB, NullyEmptySB,  spaceMatters: false));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(NullyFilledSB, NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(NullyFilledSB, NullyFilledSB, spaceMatters: false));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(NullyFilledSB, EmptySB,       spaceMatters: false));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(NullyFilledSB, SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(NullyFilledSB, FilledSB,      spaceMatters: false));
        NoNullRet(                 NullSB       .Coalesce(EmptySB,       NullSB,        spaceMatters: false));
        NoNullRet($"{EmptySB}", $"{NullSB       .Coalesce(EmptySB,       NullSB,        spaceMatters: false)}");
        NoNullRet(   EmptySB,      NullSB       .Coalesce(EmptySB,       NullyEmptySB,  spaceMatters: false));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(EmptySB,       NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(EmptySB,       NullyFilledSB, spaceMatters: false));
        NoNullRet(   EmptySB,      NullSB       .Coalesce(EmptySB,       EmptySB,       spaceMatters: false));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(EmptySB,       SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(EmptySB,       FilledSB,      spaceMatters: false));
        NoNullRet(                 NullSB       .Coalesce(SpaceSB,       NullSB,        spaceMatters: false));
        NoNullRet($"{EmptySB}", $"{NullSB       .Coalesce(SpaceSB,       NullSB,        spaceMatters: false)}");
        NoNullRet(   EmptySB,      NullSB       .Coalesce(SpaceSB,       NullyEmptySB,  spaceMatters: false));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(SpaceSB,       NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(SpaceSB,       NullyFilledSB, spaceMatters: false));
        NoNullRet(   EmptySB,      NullSB       .Coalesce(SpaceSB,       EmptySB,       spaceMatters: false));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(SpaceSB,       SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(SpaceSB,       FilledSB,      spaceMatters: false));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(FilledSB,      NullSB,        spaceMatters: false));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(FilledSB,      NullyEmptySB,  spaceMatters: false));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(FilledSB,      NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(FilledSB,      NullyFilledSB, spaceMatters: false));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(FilledSB,      EmptySB,       spaceMatters: false));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(FilledSB,      SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(FilledSB,      FilledSB,      spaceMatters: false));
    }

    [TestMethod]
    public void Coalesce_3Args_SBs_ExtensionsSpaceMattersNoExplicit_Batch2()
    {
        NoNullRet(                 NullyEmptySB .Coalesce(NullSB,        NullSB,        spaceMatters: false));
        NoNullRet($"{EmptySB}", $"{NullyEmptySB .Coalesce(NullSB,        NullSB,        spaceMatters: false)}");
        NoNullRet(   EmptySB,      NullyEmptySB .Coalesce(NullSB,        NullyEmptySB,  spaceMatters: false));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(NullSB,        NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(NullSB,        NullyFilledSB, spaceMatters: false));
        NoNullRet(   EmptySB,      NullyEmptySB .Coalesce(NullSB,        EmptySB,       spaceMatters: false));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(NullSB,        SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(NullSB,        FilledSB,      spaceMatters: false));
        NoNullRet(                 NullyEmptySB .Coalesce(NullyEmptySB,  NullSB,        spaceMatters: false));
        NoNullRet($"{EmptySB}", $"{NullyEmptySB .Coalesce(NullyEmptySB,  NullSB,        spaceMatters: false)}");
        NoNullRet(   EmptySB,      NullyEmptySB .Coalesce(NullyEmptySB,  NullyEmptySB,  spaceMatters: false));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(NullyEmptySB,  NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(NullyEmptySB,  NullyFilledSB, spaceMatters: false));
        NoNullRet(   EmptySB,      NullyEmptySB .Coalesce(NullyEmptySB,  EmptySB,       spaceMatters: false));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(NullyEmptySB,  SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(NullyEmptySB,  FilledSB,      spaceMatters: false));
        NoNullRet(                 NullyEmptySB .Coalesce(NullySpaceSB,  NullSB,        spaceMatters: false));
        NoNullRet($"{EmptySB}", $"{NullyEmptySB .Coalesce(NullySpaceSB,  NullSB,        spaceMatters: false)}");
        NoNullRet(   EmptySB,      NullyEmptySB .Coalesce(NullySpaceSB,  NullyEmptySB,  spaceMatters: false));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(NullySpaceSB,  NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(NullySpaceSB,  NullyFilledSB, spaceMatters: false));
        NoNullRet(   EmptySB,      NullyEmptySB .Coalesce(NullySpaceSB,  EmptySB,       spaceMatters: false));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(NullySpaceSB,  SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(NullySpaceSB,  FilledSB,      spaceMatters: false));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(NullyFilledSB, NullSB,        spaceMatters: false));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(NullyFilledSB, NullyEmptySB,  spaceMatters: false));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(NullyFilledSB, NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(NullyFilledSB, NullyFilledSB, spaceMatters: false));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(NullyFilledSB, EmptySB,       spaceMatters: false));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(NullyFilledSB, SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(NullyFilledSB, FilledSB,      spaceMatters: false));
        NoNullRet(                 NullyEmptySB .Coalesce(EmptySB,       NullSB,        spaceMatters: false));
        NoNullRet($"{EmptySB}", $"{NullyEmptySB .Coalesce(EmptySB,       NullSB,        spaceMatters: false)}");
        NoNullRet(   EmptySB,      NullyEmptySB .Coalesce(EmptySB,       NullyEmptySB,  spaceMatters: false));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(EmptySB,       NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(EmptySB,       NullyFilledSB, spaceMatters: false));
        NoNullRet(   EmptySB,      NullyEmptySB .Coalesce(EmptySB,       EmptySB,       spaceMatters: false));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(EmptySB,       SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(EmptySB,       FilledSB,      spaceMatters: false));
        NoNullRet(                 NullyEmptySB .Coalesce(SpaceSB,       NullSB,        spaceMatters: false));
        NoNullRet($"{EmptySB}", $"{NullyEmptySB .Coalesce(SpaceSB,       NullSB,        spaceMatters: false)}");
        NoNullRet(   EmptySB,      NullyEmptySB .Coalesce(SpaceSB,       NullyEmptySB,  spaceMatters: false));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(SpaceSB,       NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(SpaceSB,       NullyFilledSB, spaceMatters: false));
        NoNullRet(   EmptySB,      NullyEmptySB .Coalesce(SpaceSB,       EmptySB,       spaceMatters: false));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(SpaceSB,       SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(SpaceSB,       FilledSB,      spaceMatters: false));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(FilledSB,      NullSB,        spaceMatters: false));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(FilledSB,      NullyEmptySB,  spaceMatters: false));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(FilledSB,      NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(FilledSB,      NullyFilledSB, spaceMatters: false));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(FilledSB,      EmptySB,       spaceMatters: false));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(FilledSB,      SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(FilledSB,      FilledSB,      spaceMatters: false));
    }

    [TestMethod]
    public void Coalesce_3Args_SBs_ExtensionsSpaceMattersNoExplicit_Batch3()
    {
        NoNullRet(                 NullySpaceSB .Coalesce(NullSB,        NullSB,        spaceMatters: false));
        NoNullRet($"{EmptySB}", $"{NullySpaceSB .Coalesce(NullSB,        NullSB,        spaceMatters: false)}");
        NoNullRet(   EmptySB,      NullySpaceSB .Coalesce(NullSB,        NullyEmptySB,  spaceMatters: false));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullSB,        NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     NullySpaceSB .Coalesce(NullSB,        NullyFilledSB, spaceMatters: false));
        NoNullRet(   EmptySB,      NullySpaceSB .Coalesce(NullSB,        EmptySB,       spaceMatters: false));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullSB,        SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     NullySpaceSB .Coalesce(NullSB,        FilledSB,      spaceMatters: false));
        NoNullRet(                 NullySpaceSB .Coalesce(NullyEmptySB,  NullSB,        spaceMatters: false));
        NoNullRet($"{EmptySB}", $"{NullySpaceSB. Coalesce(NullyEmptySB,  NullSB,        spaceMatters: false)}");
        NoNullRet(   EmptySB,      NullySpaceSB .Coalesce(NullyEmptySB,  NullyEmptySB,  spaceMatters: false));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullyEmptySB,  NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     NullySpaceSB .Coalesce(NullyEmptySB,  NullyFilledSB, spaceMatters: false));
        NoNullRet(   EmptySB,      NullySpaceSB .Coalesce(NullyEmptySB,  EmptySB,       spaceMatters: false));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullyEmptySB,  SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     NullySpaceSB .Coalesce(NullyEmptySB,  FilledSB,      spaceMatters: false));
        NoNullRet(                 NullySpaceSB .Coalesce(NullySpaceSB,  NullSB,        spaceMatters: false));
        NoNullRet($"{EmptySB}", $"{NullySpaceSB .Coalesce(NullySpaceSB,  NullSB,        spaceMatters: false)}");
        NoNullRet(   EmptySB,      NullySpaceSB .Coalesce(NullySpaceSB,  NullyEmptySB,  spaceMatters: false));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullySpaceSB,  NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     NullySpaceSB .Coalesce(NullySpaceSB,  NullyFilledSB, spaceMatters: false));
        NoNullRet(   EmptySB,      NullySpaceSB .Coalesce(NullySpaceSB,  EmptySB,       spaceMatters: false));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullySpaceSB,  SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     NullySpaceSB .Coalesce(NullySpaceSB,  FilledSB,      spaceMatters: false));
        NoNullRet(   FilledSB,     NullySpaceSB .Coalesce(NullyFilledSB, NullSB,        spaceMatters: false));
        NoNullRet(   FilledSB,     NullySpaceSB .Coalesce(NullyFilledSB, NullyEmptySB,  spaceMatters: false));
        NoNullRet(   FilledSB,     NullySpaceSB .Coalesce(NullyFilledSB, NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     NullySpaceSB .Coalesce(NullyFilledSB, NullyFilledSB, spaceMatters: false));
        NoNullRet(   FilledSB,     NullySpaceSB .Coalesce(NullyFilledSB, EmptySB,       spaceMatters: false));
        NoNullRet(   FilledSB,     NullySpaceSB .Coalesce(NullyFilledSB, SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     NullySpaceSB .Coalesce(NullyFilledSB, FilledSB,      spaceMatters: false));
        NoNullRet(                 NullySpaceSB .Coalesce(EmptySB,       NullSB,        spaceMatters: false));
        NoNullRet($"{EmptySB}", $"{NullySpaceSB .Coalesce(EmptySB,       NullSB,        spaceMatters: false)}");
        NoNullRet(   EmptySB,      NullySpaceSB .Coalesce(EmptySB,       NullyEmptySB,  spaceMatters: false));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(EmptySB,       NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     NullySpaceSB .Coalesce(EmptySB,       NullyFilledSB, spaceMatters: false));
        NoNullRet(   EmptySB,      NullySpaceSB .Coalesce(EmptySB,       EmptySB,       spaceMatters: false));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(EmptySB,       SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     NullySpaceSB .Coalesce(EmptySB,       FilledSB,      spaceMatters: false));
        NoNullRet(                 NullySpaceSB .Coalesce(SpaceSB,       NullSB,        spaceMatters: false));
        NoNullRet($"{EmptySB}", $"{NullySpaceSB .Coalesce(SpaceSB,       NullSB,        spaceMatters: false)}");
        NoNullRet(   EmptySB,      NullySpaceSB .Coalesce(SpaceSB,       NullyEmptySB,  spaceMatters: false));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(SpaceSB,       NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     NullySpaceSB .Coalesce(SpaceSB,       NullyFilledSB, spaceMatters: false));
        NoNullRet(   EmptySB,      NullySpaceSB .Coalesce(SpaceSB,       EmptySB,       spaceMatters: false));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(SpaceSB,       SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     NullySpaceSB .Coalesce(SpaceSB,       FilledSB,      spaceMatters: false));
        NoNullRet(   FilledSB,     NullySpaceSB .Coalesce(FilledSB,      NullSB,        spaceMatters: false));
        NoNullRet(   FilledSB,     NullySpaceSB .Coalesce(FilledSB,      NullyEmptySB,  spaceMatters: false));
        NoNullRet(   FilledSB,     NullySpaceSB .Coalesce(FilledSB,      NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     NullySpaceSB .Coalesce(FilledSB,      NullyFilledSB, spaceMatters: false));
        NoNullRet(   FilledSB,     NullySpaceSB .Coalesce(FilledSB,      EmptySB,       spaceMatters: false));
        NoNullRet(   FilledSB,     NullySpaceSB .Coalesce(FilledSB,      SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     NullySpaceSB .Coalesce(FilledSB,      FilledSB,      spaceMatters: false));
    }

    [TestMethod]
    public void Coalesce_3Args_SBs_ExtensionsSpaceMattersNoExplicit_Batch4()
    {
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullSB,        NullSB,        spaceMatters: false));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullSB,        NullyEmptySB,  spaceMatters: false));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullSB,        NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullSB,        NullyFilledSB, spaceMatters: false));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullSB,        EmptySB,       spaceMatters: false));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullSB,        SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullSB,        FilledSB,      spaceMatters: false));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullyEmptySB,  NullSB,        spaceMatters: false));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullyEmptySB,  NullyEmptySB,  spaceMatters: false));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullyEmptySB,  NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullyEmptySB,  NullyFilledSB, spaceMatters: false));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullyEmptySB,  EmptySB,       spaceMatters: false));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullyEmptySB,  SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullyEmptySB,  FilledSB,      spaceMatters: false));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullySpaceSB,  NullSB,        spaceMatters: false));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullySpaceSB,  NullyEmptySB,  spaceMatters: false));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullySpaceSB,  NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullySpaceSB,  NullyFilledSB, spaceMatters: false));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullySpaceSB,  EmptySB,       spaceMatters: false));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullySpaceSB,  SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullySpaceSB,  FilledSB,      spaceMatters: false));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullyFilledSB, NullSB,        spaceMatters: false));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullyFilledSB, NullyEmptySB,  spaceMatters: false));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullyFilledSB, NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullyFilledSB, NullyFilledSB, spaceMatters: false));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullyFilledSB, EmptySB,       spaceMatters: false));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullyFilledSB, SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullyFilledSB, FilledSB,      spaceMatters: false));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(EmptySB,       NullSB,        spaceMatters: false));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(EmptySB,       NullyEmptySB,  spaceMatters: false));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(EmptySB,       NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(EmptySB,       NullyFilledSB, spaceMatters: false));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(EmptySB,       EmptySB,       spaceMatters: false));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(EmptySB,       SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(EmptySB,       FilledSB,      spaceMatters: false));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(SpaceSB,       NullSB,        spaceMatters: false));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(SpaceSB,       NullyEmptySB,  spaceMatters: false));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(SpaceSB,       NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(SpaceSB,       NullyFilledSB, spaceMatters: false));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(SpaceSB,       EmptySB,       spaceMatters: false));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(SpaceSB,       SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(SpaceSB,       FilledSB,      spaceMatters: false));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(FilledSB,      NullSB,        spaceMatters: false));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(FilledSB,      NullyEmptySB,  spaceMatters: false));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(FilledSB,      NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(FilledSB,      NullyFilledSB, spaceMatters: false));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(FilledSB,      EmptySB,       spaceMatters: false));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(FilledSB,      SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(FilledSB,      FilledSB,      spaceMatters: false));
    }

    [TestMethod]
    public void Coalesce_3Args_SBs_ExtensionsSpaceMattersNoExplicit_Batch5()
    {
        NoNullRet(                 EmptySB      .Coalesce(NullSB,        NullSB,        spaceMatters: false));
        NoNullRet($"{EmptySB}", $"{EmptySB      .Coalesce(NullSB,        NullSB,        spaceMatters: false)}");
        NoNullRet(   EmptySB,      EmptySB      .Coalesce(NullSB,        NullyEmptySB,  spaceMatters: false));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(NullSB,        NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(NullSB,        NullyFilledSB, spaceMatters: false));
        NoNullRet(   EmptySB,      EmptySB      .Coalesce(NullSB,        EmptySB,       spaceMatters: false));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(NullSB,        SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(NullSB,        FilledSB,      spaceMatters: false));
        NoNullRet(                 EmptySB      .Coalesce(NullyEmptySB,  NullSB,        spaceMatters: false));
        NoNullRet($"{EmptySB}", $"{EmptySB      .Coalesce(NullyEmptySB,  NullSB,        spaceMatters: false)}");
        NoNullRet(   EmptySB,      EmptySB      .Coalesce(NullyEmptySB,  NullyEmptySB,  spaceMatters: false));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(NullyEmptySB,  NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(NullyEmptySB,  NullyFilledSB, spaceMatters: false));
        NoNullRet(   EmptySB,      EmptySB      .Coalesce(NullyEmptySB,  EmptySB,       spaceMatters: false));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(NullyEmptySB,  SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(NullyEmptySB,  FilledSB,      spaceMatters: false));
        NoNullRet(                 EmptySB      .Coalesce(NullySpaceSB,  NullSB,        spaceMatters: false));
        NoNullRet($"{EmptySB}", $"{EmptySB      .Coalesce(NullySpaceSB,  NullSB,        spaceMatters: false)}");
        NoNullRet(   EmptySB,      EmptySB      .Coalesce(NullySpaceSB,  NullyEmptySB,  spaceMatters: false));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(NullySpaceSB,  NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(NullySpaceSB,  NullyFilledSB, spaceMatters: false));
        NoNullRet(   EmptySB,      EmptySB      .Coalesce(NullySpaceSB,  EmptySB,       spaceMatters: false));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(NullySpaceSB,  SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(NullySpaceSB,  FilledSB,      spaceMatters: false));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(NullyFilledSB, NullSB,        spaceMatters: false));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(NullyFilledSB, NullyEmptySB,  spaceMatters: false));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(NullyFilledSB, NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(NullyFilledSB, NullyFilledSB, spaceMatters: false));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(NullyFilledSB, EmptySB,       spaceMatters: false));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(NullyFilledSB, SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(NullyFilledSB, FilledSB,      spaceMatters: false));
        NoNullRet(                 EmptySB      .Coalesce(EmptySB,       NullSB,        spaceMatters: false));
        NoNullRet($"{EmptySB}", $"{EmptySB      .Coalesce(EmptySB,       NullSB,        spaceMatters: false)}");
        NoNullRet(   EmptySB,      EmptySB      .Coalesce(EmptySB,       NullyEmptySB,  spaceMatters: false));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(EmptySB,       NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(EmptySB,       NullyFilledSB, spaceMatters: false));
        NoNullRet(   EmptySB,      EmptySB      .Coalesce(EmptySB,       EmptySB,       spaceMatters: false));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(EmptySB,       SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(EmptySB,       FilledSB,      spaceMatters: false));
        NoNullRet(                 EmptySB      .Coalesce(SpaceSB,       NullSB,        spaceMatters: false));
        NoNullRet($"{EmptySB}", $"{EmptySB      .Coalesce(SpaceSB,       NullSB,        spaceMatters: false)}");
        NoNullRet(   EmptySB,      EmptySB      .Coalesce(SpaceSB,       NullyEmptySB,  spaceMatters: false));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(SpaceSB,       NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(SpaceSB,       NullyFilledSB, spaceMatters: false));
        NoNullRet(   EmptySB,      EmptySB      .Coalesce(SpaceSB,       EmptySB,       spaceMatters: false));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(SpaceSB,       SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(SpaceSB,       FilledSB,      spaceMatters: false));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(FilledSB,      NullSB,        spaceMatters: false));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(FilledSB,      NullyEmptySB,  spaceMatters: false));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(FilledSB,      NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(FilledSB,      NullyFilledSB, spaceMatters: false));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(FilledSB,      EmptySB,       spaceMatters: false));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(FilledSB,      SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(FilledSB,      FilledSB,      spaceMatters: false));
    }

    [TestMethod]
    public void Coalesce_3Args_SBs_ExtensionsSpaceMattersNoExplicit_Batch6()
    {
        NoNullRet(                 SpaceSB      .Coalesce(NullSB,        NullSB,        spaceMatters: false));
        NoNullRet($"{EmptySB}", $"{SpaceSB      .Coalesce(NullSB,        NullSB,        spaceMatters: false)}");
        NoNullRet(   EmptySB,      SpaceSB      .Coalesce(NullSB,        NullyEmptySB,  spaceMatters: false));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullSB,        NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     SpaceSB      .Coalesce(NullSB,        NullyFilledSB, spaceMatters: false));
        NoNullRet(   EmptySB,      SpaceSB      .Coalesce(NullSB,        EmptySB,       spaceMatters: false));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullSB,        SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     SpaceSB      .Coalesce(NullSB,        FilledSB,      spaceMatters: false));
        NoNullRet(                 SpaceSB      .Coalesce(NullyEmptySB,  NullSB,        spaceMatters: false));
        NoNullRet($"{EmptySB}", $"{SpaceSB      .Coalesce(NullyEmptySB,  NullSB,        spaceMatters: false)}");
        NoNullRet(   EmptySB,      SpaceSB      .Coalesce(NullyEmptySB,  NullyEmptySB,  spaceMatters: false));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullyEmptySB,  NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     SpaceSB      .Coalesce(NullyEmptySB,  NullyFilledSB, spaceMatters: false));
        NoNullRet(   EmptySB,      SpaceSB      .Coalesce(NullyEmptySB,  EmptySB,       spaceMatters: false));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullyEmptySB,  SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     SpaceSB      .Coalesce(NullyEmptySB,  FilledSB,      spaceMatters: false));
        NoNullRet(                 SpaceSB      .Coalesce(NullySpaceSB,  NullSB,        spaceMatters: false));
        NoNullRet($"{EmptySB}", $"{SpaceSB      .Coalesce(NullySpaceSB,  NullSB,        spaceMatters: false)}");
        NoNullRet(   EmptySB,      SpaceSB      .Coalesce(NullySpaceSB,  NullyEmptySB,  spaceMatters: false));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullySpaceSB,  NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     SpaceSB      .Coalesce(NullySpaceSB,  NullyFilledSB, spaceMatters: false));
        NoNullRet(   EmptySB,      SpaceSB      .Coalesce(NullySpaceSB,  EmptySB,       spaceMatters: false));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullySpaceSB,  SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     SpaceSB      .Coalesce(NullySpaceSB,  FilledSB,      spaceMatters: false));
        NoNullRet(   FilledSB,     SpaceSB      .Coalesce(NullyFilledSB, NullSB,        spaceMatters: false));
        NoNullRet(   FilledSB,     SpaceSB      .Coalesce(NullyFilledSB, NullyEmptySB,  spaceMatters: false));
        NoNullRet(   FilledSB,     SpaceSB      .Coalesce(NullyFilledSB, NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     SpaceSB      .Coalesce(NullyFilledSB, NullyFilledSB, spaceMatters: false));
        NoNullRet(   FilledSB,     SpaceSB      .Coalesce(NullyFilledSB, EmptySB,       spaceMatters: false));
        NoNullRet(   FilledSB,     SpaceSB      .Coalesce(NullyFilledSB, SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     SpaceSB      .Coalesce(NullyFilledSB, FilledSB,      spaceMatters: false));
        NoNullRet(                 SpaceSB      .Coalesce(EmptySB,       NullSB,        spaceMatters: false));
        NoNullRet($"{EmptySB}", $"{SpaceSB      .Coalesce(EmptySB,       NullSB,        spaceMatters: false)}");
        NoNullRet(   EmptySB,      SpaceSB      .Coalesce(EmptySB,       NullyEmptySB,  spaceMatters: false));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(EmptySB,       NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     SpaceSB      .Coalesce(EmptySB,       NullyFilledSB, spaceMatters: false));
        NoNullRet(   EmptySB,      SpaceSB      .Coalesce(EmptySB,       EmptySB,       spaceMatters: false));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(EmptySB,       SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     SpaceSB      .Coalesce(EmptySB,       FilledSB,      spaceMatters: false));
        NoNullRet(                 SpaceSB      .Coalesce(SpaceSB,       NullSB,        spaceMatters: false));
        NoNullRet($"{EmptySB}", $"{SpaceSB      .Coalesce(SpaceSB,       NullSB,        spaceMatters: false)}");
        NoNullRet(   EmptySB,      SpaceSB      .Coalesce(SpaceSB,       NullyEmptySB,  spaceMatters: false));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(SpaceSB,       NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     SpaceSB      .Coalesce(SpaceSB,       NullyFilledSB, spaceMatters: false));
        NoNullRet(   EmptySB,      SpaceSB      .Coalesce(SpaceSB,       EmptySB,       spaceMatters: false));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(SpaceSB,       SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     SpaceSB      .Coalesce(SpaceSB,       FilledSB,      spaceMatters: false));
        NoNullRet(   FilledSB,     SpaceSB      .Coalesce(FilledSB,      NullSB,        spaceMatters: false));
        NoNullRet(   FilledSB,     SpaceSB      .Coalesce(FilledSB,      NullyEmptySB,  spaceMatters: false));
        NoNullRet(   FilledSB,     SpaceSB      .Coalesce(FilledSB,      NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     SpaceSB      .Coalesce(FilledSB,      NullyFilledSB, spaceMatters: false));
        NoNullRet(   FilledSB,     SpaceSB      .Coalesce(FilledSB,      EmptySB,       spaceMatters: false));
        NoNullRet(   FilledSB,     SpaceSB      .Coalesce(FilledSB,      SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     SpaceSB      .Coalesce(FilledSB,      FilledSB,      spaceMatters: false));
    }

    [TestMethod]
    public void Coalesce_3Args_SBs_ExtensionsSpaceMattersNoExplicit_Batch7()
    {
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullSB,        NullSB,        spaceMatters: false));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullSB,        NullyEmptySB,  spaceMatters: false));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullSB,        NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullSB,        NullyFilledSB, spaceMatters: false));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullSB,        EmptySB,       spaceMatters: false));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullSB,        SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullSB,        FilledSB,      spaceMatters: false));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullyEmptySB,  NullSB,        spaceMatters: false));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullyEmptySB,  NullyEmptySB,  spaceMatters: false));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullyEmptySB,  NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullyEmptySB,  NullyFilledSB, spaceMatters: false));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullyEmptySB,  EmptySB,       spaceMatters: false));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullyEmptySB,  SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullyEmptySB,  FilledSB,      spaceMatters: false));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullySpaceSB,  NullSB,        spaceMatters: false));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullySpaceSB,  NullyEmptySB,  spaceMatters: false));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullySpaceSB,  NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullySpaceSB,  NullyFilledSB, spaceMatters: false));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullySpaceSB,  EmptySB,       spaceMatters: false));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullySpaceSB,  SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullySpaceSB,  FilledSB,      spaceMatters: false));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullyFilledSB, NullSB,        spaceMatters: false));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullyFilledSB, NullyEmptySB,  spaceMatters: false));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullyFilledSB, NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullyFilledSB, NullyFilledSB, spaceMatters: false));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullyFilledSB, EmptySB,       spaceMatters: false));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullyFilledSB, SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullyFilledSB, FilledSB,      spaceMatters: false));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(EmptySB,       NullSB,        spaceMatters: false));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(EmptySB,       NullyEmptySB,  spaceMatters: false));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(EmptySB,       NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(EmptySB,       NullyFilledSB, spaceMatters: false));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(EmptySB,       EmptySB,       spaceMatters: false));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(EmptySB,       SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(EmptySB,       FilledSB,      spaceMatters: false));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(SpaceSB,       NullSB,        spaceMatters: false));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(SpaceSB,       NullyEmptySB,  spaceMatters: false));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(SpaceSB,       NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(SpaceSB,       NullyFilledSB, spaceMatters: false));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(SpaceSB,       EmptySB,       spaceMatters: false));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(SpaceSB,       SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(SpaceSB,       FilledSB,      spaceMatters: false));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(FilledSB,      NullSB,        spaceMatters: false));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(FilledSB,      NullyEmptySB,  spaceMatters: false));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(FilledSB,      NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(FilledSB,      NullyFilledSB, spaceMatters: false));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(FilledSB,      EmptySB,       spaceMatters: false));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(FilledSB,      SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(FilledSB,      FilledSB,      spaceMatters: false));
    }
}