namespace JJ.Framework.Existence.Core.Tests;

[TestClass]
public class Coalesce_3Args_SBs_ExtensionsSpaceMattersYes
{
    [TestMethod]
    public void Coalesce_3Args_SBs_ExtensionsSpaceMattersYes_MagicBool()
    {
        NoNullRet(                 NullSB       .Coalesce(NullSB,        NullSB,        spaceMatters));
        NoNullRet($"{EmptySB}", $"{NullSB       .Coalesce(NullSB,        NullSB,        spaceMatters)}");
        NoNullRet(   EmptySB,      NullSB       .Coalesce(NullSB,        NullyEmptySB,  spaceMatters));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(NullSB,        NullySpaceSB,  spaceMatters));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(NullSB,        NullyFilledSB, spaceMatters));
        NoNullRet(   EmptySB,      NullSB       .Coalesce(NullSB,        EmptySB,       spaceMatters));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(NullSB,        SpaceSB,       spaceMatters));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(NullSB,        FilledSB,      spaceMatters));
        NoNullRet(                 NullSB       .Coalesce(NullyEmptySB,  NullSB,        spaceMatters));
        NoNullRet($"{EmptySB}", $"{NullSB       .Coalesce(NullyEmptySB,  NullSB,        spaceMatters)}");
        NoNullRet(   EmptySB,      NullSB       .Coalesce(NullyEmptySB,  NullyEmptySB,  spaceMatters));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(NullyEmptySB,  NullySpaceSB,  spaceMatters));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(NullyEmptySB,  NullyFilledSB, spaceMatters));
        NoNullRet(   EmptySB,      NullSB       .Coalesce(NullyEmptySB,  EmptySB,       spaceMatters));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(NullyEmptySB,  SpaceSB,       spaceMatters));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(NullyEmptySB,  FilledSB,      spaceMatters));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(NullySpaceSB,  NullSB,        spaceMatters));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(NullySpaceSB,  NullyEmptySB,  spaceMatters));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(NullySpaceSB,  NullySpaceSB,  spaceMatters));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(NullySpaceSB,  NullyFilledSB, spaceMatters));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(NullySpaceSB,  EmptySB,       spaceMatters));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(NullySpaceSB,  SpaceSB,       spaceMatters));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(NullySpaceSB,  FilledSB,      spaceMatters));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(NullyFilledSB, NullSB,        spaceMatters));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(NullyFilledSB, NullyEmptySB,  spaceMatters));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(NullyFilledSB, NullySpaceSB,  spaceMatters));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(NullyFilledSB, NullyFilledSB, spaceMatters));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(NullyFilledSB, EmptySB,       spaceMatters));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(NullyFilledSB, SpaceSB,       spaceMatters));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(NullyFilledSB, FilledSB,      spaceMatters));
        NoNullRet(                 NullSB       .Coalesce(EmptySB,       NullSB,        spaceMatters));
        NoNullRet($"{EmptySB}", $"{NullSB       .Coalesce(EmptySB,       NullSB,        spaceMatters)}");
        NoNullRet(   EmptySB,      NullSB       .Coalesce(EmptySB,       NullyEmptySB,  spaceMatters));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(EmptySB,       NullySpaceSB,  spaceMatters));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(EmptySB,       NullyFilledSB, spaceMatters));
        NoNullRet(   EmptySB,      NullSB       .Coalesce(EmptySB,       EmptySB,       spaceMatters));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(EmptySB,       SpaceSB,       spaceMatters));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(EmptySB,       FilledSB,      spaceMatters));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(SpaceSB,       NullSB,        spaceMatters));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(SpaceSB,       NullyEmptySB,  spaceMatters));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(SpaceSB,       NullySpaceSB,  spaceMatters));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(SpaceSB,       NullyFilledSB, spaceMatters));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(SpaceSB,       EmptySB,       spaceMatters));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(SpaceSB,       SpaceSB,       spaceMatters));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(SpaceSB,       FilledSB,      spaceMatters));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(FilledSB,      NullSB,        spaceMatters));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(FilledSB,      NullyEmptySB,  spaceMatters));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(FilledSB,      NullySpaceSB,  spaceMatters));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(FilledSB,      NullyFilledSB, spaceMatters));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(FilledSB,      EmptySB,       spaceMatters));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(FilledSB,      SpaceSB,       spaceMatters));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(FilledSB,      FilledSB,      spaceMatters));
        
        NoNullRet(                 NullyEmptySB .Coalesce(NullSB,        NullSB,        spaceMatters));
        NoNullRet($"{EmptySB}", $"{NullyEmptySB .Coalesce(NullSB,        NullSB,        spaceMatters)}");
        NoNullRet(   EmptySB,      NullyEmptySB .Coalesce(NullSB,        NullyEmptySB,  spaceMatters));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(NullSB,        NullySpaceSB,  spaceMatters));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(NullSB,        NullyFilledSB, spaceMatters));
        NoNullRet(   EmptySB,      NullyEmptySB .Coalesce(NullSB,        EmptySB,       spaceMatters));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(NullSB,        SpaceSB,       spaceMatters));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(NullSB,        FilledSB,      spaceMatters));
        NoNullRet(                 NullyEmptySB .Coalesce(NullyEmptySB,  NullSB,        spaceMatters));
        NoNullRet($"{EmptySB}", $"{NullyEmptySB .Coalesce(NullyEmptySB,  NullSB,        spaceMatters)}");
        NoNullRet(   EmptySB,      NullyEmptySB .Coalesce(NullyEmptySB,  NullyEmptySB,  spaceMatters));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(NullyEmptySB,  NullySpaceSB,  spaceMatters));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(NullyEmptySB,  NullyFilledSB, spaceMatters));
        NoNullRet(   EmptySB,      NullyEmptySB .Coalesce(NullyEmptySB,  EmptySB,       spaceMatters));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(NullyEmptySB,  SpaceSB,       spaceMatters));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(NullyEmptySB,  FilledSB,      spaceMatters));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(NullySpaceSB,  NullSB,        spaceMatters));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(NullySpaceSB,  NullyEmptySB,  spaceMatters));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(NullySpaceSB,  NullySpaceSB,  spaceMatters));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(NullySpaceSB,  NullyFilledSB, spaceMatters));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(NullySpaceSB,  EmptySB,       spaceMatters));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(NullySpaceSB,  SpaceSB,       spaceMatters));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(NullySpaceSB,  FilledSB,      spaceMatters));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(NullyFilledSB, NullSB,        spaceMatters));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(NullyFilledSB, NullyEmptySB,  spaceMatters));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(NullyFilledSB, NullySpaceSB,  spaceMatters));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(NullyFilledSB, NullyFilledSB, spaceMatters));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(NullyFilledSB, EmptySB,       spaceMatters));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(NullyFilledSB, SpaceSB,       spaceMatters));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(NullyFilledSB, FilledSB,      spaceMatters));
        NoNullRet(                 NullyEmptySB .Coalesce(EmptySB,       NullSB,        spaceMatters));
        NoNullRet($"{EmptySB}", $"{NullyEmptySB .Coalesce(EmptySB,       NullSB,        spaceMatters)}");
        NoNullRet(   EmptySB,      NullyEmptySB .Coalesce(EmptySB,       NullyEmptySB,  spaceMatters));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(EmptySB,       NullySpaceSB,  spaceMatters));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(EmptySB,       NullyFilledSB, spaceMatters));
        NoNullRet(   EmptySB,      NullyEmptySB .Coalesce(EmptySB,       EmptySB,       spaceMatters));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(EmptySB,       SpaceSB,       spaceMatters));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(EmptySB,       FilledSB,      spaceMatters));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(SpaceSB,       NullSB,        spaceMatters));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(SpaceSB,       NullyEmptySB,  spaceMatters));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(SpaceSB,       NullySpaceSB,  spaceMatters));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(SpaceSB,       NullyFilledSB, spaceMatters));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(SpaceSB,       EmptySB,       spaceMatters));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(SpaceSB,       SpaceSB,       spaceMatters));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(SpaceSB,       FilledSB,      spaceMatters));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(FilledSB,      NullSB,        spaceMatters));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(FilledSB,      NullyEmptySB,  spaceMatters));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(FilledSB,      NullySpaceSB,  spaceMatters));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(FilledSB,      NullyFilledSB, spaceMatters));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(FilledSB,      EmptySB,       spaceMatters));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(FilledSB,      SpaceSB,       spaceMatters));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(FilledSB,      FilledSB,      spaceMatters));

        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullSB,        NullSB,        spaceMatters));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullSB,        NullyEmptySB,  spaceMatters));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullSB,        NullySpaceSB,  spaceMatters));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullSB,        NullyFilledSB, spaceMatters));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullSB,        EmptySB,       spaceMatters));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullSB,        SpaceSB,       spaceMatters));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullSB,        FilledSB,      spaceMatters));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullyEmptySB,  NullSB,        spaceMatters));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullyEmptySB,  NullyEmptySB,  spaceMatters));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullyEmptySB,  NullySpaceSB,  spaceMatters));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullyEmptySB,  NullyFilledSB, spaceMatters));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullyEmptySB,  EmptySB,       spaceMatters));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullyEmptySB,  SpaceSB,       spaceMatters));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullyEmptySB,  FilledSB,      spaceMatters));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullySpaceSB,  NullSB,        spaceMatters));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullySpaceSB,  NullyEmptySB,  spaceMatters));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullySpaceSB,  NullySpaceSB,  spaceMatters));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullySpaceSB,  NullyFilledSB, spaceMatters));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullySpaceSB,  EmptySB,       spaceMatters));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullySpaceSB,  SpaceSB,       spaceMatters));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullySpaceSB,  FilledSB,      spaceMatters));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullyFilledSB, NullSB,        spaceMatters));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullyFilledSB, NullyEmptySB,  spaceMatters));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullyFilledSB, NullySpaceSB,  spaceMatters));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullyFilledSB, NullyFilledSB, spaceMatters));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullyFilledSB, EmptySB,       spaceMatters));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullyFilledSB, SpaceSB,       spaceMatters));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullyFilledSB, FilledSB,      spaceMatters));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(EmptySB,       NullSB,        spaceMatters));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(EmptySB,       NullyEmptySB,  spaceMatters));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(EmptySB,       NullySpaceSB,  spaceMatters));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(EmptySB,       NullyFilledSB, spaceMatters));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(EmptySB,       EmptySB,       spaceMatters));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(EmptySB,       SpaceSB,       spaceMatters));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(EmptySB,       FilledSB,      spaceMatters));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(SpaceSB,       NullSB,        spaceMatters));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(SpaceSB,       NullyEmptySB,  spaceMatters));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(SpaceSB,       NullySpaceSB,  spaceMatters));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(SpaceSB,       NullyFilledSB, spaceMatters));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(SpaceSB,       EmptySB,       spaceMatters));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(SpaceSB,       SpaceSB,       spaceMatters));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(SpaceSB,       FilledSB,      spaceMatters));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(FilledSB,      NullSB,        spaceMatters));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(FilledSB,      NullyEmptySB,  spaceMatters));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(FilledSB,      NullySpaceSB,  spaceMatters));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(FilledSB,      NullyFilledSB, spaceMatters));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(FilledSB,      EmptySB,       spaceMatters));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(FilledSB,      SpaceSB,       spaceMatters));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(FilledSB,      FilledSB,      spaceMatters));

        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullSB,        NullSB,        spaceMatters));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullSB,        NullyEmptySB,  spaceMatters));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullSB,        NullySpaceSB,  spaceMatters));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullSB,        NullyFilledSB, spaceMatters));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullSB,        EmptySB,       spaceMatters));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullSB,        SpaceSB,       spaceMatters));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullSB,        FilledSB,      spaceMatters));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullyEmptySB,  NullSB,        spaceMatters));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullyEmptySB,  NullyEmptySB,  spaceMatters));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullyEmptySB,  NullySpaceSB,  spaceMatters));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullyEmptySB,  NullyFilledSB, spaceMatters));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullyEmptySB,  EmptySB,       spaceMatters));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullyEmptySB,  SpaceSB,       spaceMatters));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullyEmptySB,  FilledSB,      spaceMatters));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullySpaceSB,  NullSB,        spaceMatters));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullySpaceSB,  NullyEmptySB,  spaceMatters));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullySpaceSB,  NullySpaceSB,  spaceMatters));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullySpaceSB,  NullyFilledSB, spaceMatters));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullySpaceSB,  EmptySB,       spaceMatters));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullySpaceSB,  SpaceSB,       spaceMatters));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullySpaceSB,  FilledSB,      spaceMatters));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullyFilledSB, NullSB,        spaceMatters));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullyFilledSB, NullyEmptySB,  spaceMatters));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullyFilledSB, NullySpaceSB,  spaceMatters));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullyFilledSB, NullyFilledSB, spaceMatters));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullyFilledSB, EmptySB,       spaceMatters));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullyFilledSB, SpaceSB,       spaceMatters));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullyFilledSB, FilledSB,      spaceMatters));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(EmptySB,       NullSB,        spaceMatters));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(EmptySB,       NullyEmptySB,  spaceMatters));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(EmptySB,       NullySpaceSB,  spaceMatters));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(EmptySB,       NullyFilledSB, spaceMatters));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(EmptySB,       EmptySB,       spaceMatters));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(EmptySB,       SpaceSB,       spaceMatters));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(EmptySB,       FilledSB,      spaceMatters));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(SpaceSB,       NullSB,        spaceMatters));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(SpaceSB,       NullyEmptySB,  spaceMatters));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(SpaceSB,       NullySpaceSB,  spaceMatters));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(SpaceSB,       NullyFilledSB, spaceMatters));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(SpaceSB,       EmptySB,       spaceMatters));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(SpaceSB,       SpaceSB,       spaceMatters));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(SpaceSB,       FilledSB,      spaceMatters));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(FilledSB,      NullSB,        spaceMatters));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(FilledSB,      NullyEmptySB,  spaceMatters));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(FilledSB,      NullySpaceSB,  spaceMatters));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(FilledSB,      NullyFilledSB, spaceMatters));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(FilledSB,      EmptySB,       spaceMatters));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(FilledSB,      SpaceSB,       spaceMatters));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(FilledSB,      FilledSB,      spaceMatters));

        NoNullRet(                 EmptySB      .Coalesce(NullSB,        NullSB,        spaceMatters));
        NoNullRet($"{EmptySB}", $"{EmptySB      .Coalesce(NullSB,        NullSB,        spaceMatters)}");
        NoNullRet(   EmptySB,      EmptySB      .Coalesce(NullSB,        NullyEmptySB,  spaceMatters));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(NullSB,        NullySpaceSB,  spaceMatters));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(NullSB,        NullyFilledSB, spaceMatters));
        NoNullRet(   EmptySB,      EmptySB      .Coalesce(NullSB,        EmptySB,       spaceMatters));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(NullSB,        SpaceSB,       spaceMatters));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(NullSB,        FilledSB,      spaceMatters));
        NoNullRet(                 EmptySB      .Coalesce(NullyEmptySB,  NullSB,        spaceMatters));
        NoNullRet($"{EmptySB}", $"{EmptySB      .Coalesce(NullyEmptySB,  NullSB,        spaceMatters)}");
        NoNullRet(   EmptySB,      EmptySB      .Coalesce(NullyEmptySB,  NullyEmptySB,  spaceMatters));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(NullyEmptySB,  NullySpaceSB,  spaceMatters));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(NullyEmptySB,  NullyFilledSB, spaceMatters));
        NoNullRet(   EmptySB,      EmptySB      .Coalesce(NullyEmptySB,  EmptySB,       spaceMatters));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(NullyEmptySB,  SpaceSB,       spaceMatters));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(NullyEmptySB,  FilledSB,      spaceMatters));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(NullySpaceSB,  NullSB,        spaceMatters));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(NullySpaceSB,  NullyEmptySB,  spaceMatters));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(NullySpaceSB,  NullySpaceSB,  spaceMatters));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(NullySpaceSB,  NullyFilledSB, spaceMatters));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(NullySpaceSB,  EmptySB,       spaceMatters));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(NullySpaceSB,  SpaceSB,       spaceMatters));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(NullySpaceSB,  FilledSB,      spaceMatters));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(NullyFilledSB, NullSB,        spaceMatters));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(NullyFilledSB, NullyEmptySB,  spaceMatters));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(NullyFilledSB, NullySpaceSB,  spaceMatters));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(NullyFilledSB, NullyFilledSB, spaceMatters));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(NullyFilledSB, EmptySB,       spaceMatters));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(NullyFilledSB, SpaceSB,       spaceMatters));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(NullyFilledSB, FilledSB,      spaceMatters));
        NoNullRet(                 EmptySB      .Coalesce(EmptySB,       NullSB,        spaceMatters));
        NoNullRet($"{EmptySB}", $"{EmptySB      .Coalesce(EmptySB,       NullSB,        spaceMatters)}");
        NoNullRet(   EmptySB,      EmptySB      .Coalesce(EmptySB,       NullyEmptySB,  spaceMatters));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(EmptySB,       NullySpaceSB,  spaceMatters));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(EmptySB,       NullyFilledSB, spaceMatters));
        NoNullRet(   EmptySB,      EmptySB      .Coalesce(EmptySB,       EmptySB,       spaceMatters));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(EmptySB,       SpaceSB,       spaceMatters));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(EmptySB,       FilledSB,      spaceMatters));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(SpaceSB,       NullSB,        spaceMatters));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(SpaceSB,       NullyEmptySB,  spaceMatters));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(SpaceSB,       NullySpaceSB,  spaceMatters));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(SpaceSB,       NullyFilledSB, spaceMatters));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(SpaceSB,       EmptySB,       spaceMatters));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(SpaceSB,       SpaceSB,       spaceMatters));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(SpaceSB,       FilledSB,      spaceMatters));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(FilledSB,      NullSB,        spaceMatters));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(FilledSB,      NullyEmptySB,  spaceMatters));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(FilledSB,      NullySpaceSB,  spaceMatters));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(FilledSB,      NullyFilledSB, spaceMatters));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(FilledSB,      EmptySB,       spaceMatters));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(FilledSB,      SpaceSB,       spaceMatters));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(FilledSB,      FilledSB,      spaceMatters));
                                                                
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullSB,        NullSB,        spaceMatters));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullSB,        NullyEmptySB,  spaceMatters));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullSB,        NullySpaceSB,  spaceMatters));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullSB,        NullyFilledSB, spaceMatters));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullSB,        EmptySB,       spaceMatters));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullSB,        SpaceSB,       spaceMatters));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullSB,        FilledSB,      spaceMatters));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullyEmptySB,  NullSB,        spaceMatters));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullyEmptySB,  NullyEmptySB,  spaceMatters));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullyEmptySB,  NullySpaceSB,  spaceMatters));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullyEmptySB,  NullyFilledSB, spaceMatters));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullyEmptySB,  EmptySB,       spaceMatters));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullyEmptySB,  SpaceSB,       spaceMatters));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullyEmptySB,  FilledSB,      spaceMatters));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullySpaceSB,  NullSB,        spaceMatters));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullySpaceSB,  NullyEmptySB,  spaceMatters));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullySpaceSB,  NullySpaceSB,  spaceMatters));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullySpaceSB,  NullyFilledSB, spaceMatters));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullySpaceSB,  EmptySB,       spaceMatters));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullySpaceSB,  SpaceSB,       spaceMatters));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullySpaceSB,  FilledSB,      spaceMatters));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullyFilledSB, NullSB,        spaceMatters));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullyFilledSB, NullyEmptySB,  spaceMatters));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullyFilledSB, NullySpaceSB,  spaceMatters));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullyFilledSB, NullyFilledSB, spaceMatters));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullyFilledSB, EmptySB,       spaceMatters));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullyFilledSB, SpaceSB,       spaceMatters));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullyFilledSB, FilledSB,      spaceMatters));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(EmptySB,       NullSB,        spaceMatters));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(EmptySB,       NullyEmptySB,  spaceMatters));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(EmptySB,       NullySpaceSB,  spaceMatters));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(EmptySB,       NullyFilledSB, spaceMatters));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(EmptySB,       EmptySB,       spaceMatters));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(EmptySB,       SpaceSB,       spaceMatters));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(EmptySB,       FilledSB,      spaceMatters));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(SpaceSB,       NullSB,        spaceMatters));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(SpaceSB,       NullyEmptySB,  spaceMatters));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(SpaceSB,       NullySpaceSB,  spaceMatters));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(SpaceSB,       NullyFilledSB, spaceMatters));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(SpaceSB,       EmptySB,       spaceMatters));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(SpaceSB,       SpaceSB,       spaceMatters));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(SpaceSB,       FilledSB,      spaceMatters));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(FilledSB,      NullSB,        spaceMatters));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(FilledSB,      NullyEmptySB,  spaceMatters));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(FilledSB,      NullySpaceSB,  spaceMatters));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(FilledSB,      NullyFilledSB, spaceMatters));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(FilledSB,      EmptySB,       spaceMatters));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(FilledSB,      SpaceSB,       spaceMatters));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(FilledSB,      FilledSB,      spaceMatters));
                                                                
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullSB,        NullSB,        spaceMatters));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullSB,        NullyEmptySB,  spaceMatters));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullSB,        NullySpaceSB,  spaceMatters));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullSB,        NullyFilledSB, spaceMatters));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullSB,        EmptySB,       spaceMatters));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullSB,        SpaceSB,       spaceMatters));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullSB,        FilledSB,      spaceMatters));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullyEmptySB,  NullSB,        spaceMatters));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullyEmptySB,  NullyEmptySB,  spaceMatters));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullyEmptySB,  NullySpaceSB,  spaceMatters));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullyEmptySB,  NullyFilledSB, spaceMatters));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullyEmptySB,  EmptySB,       spaceMatters));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullyEmptySB,  SpaceSB,       spaceMatters));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullyEmptySB,  FilledSB,      spaceMatters));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullySpaceSB,  NullSB,        spaceMatters));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullySpaceSB,  NullyEmptySB,  spaceMatters));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullySpaceSB,  NullySpaceSB,  spaceMatters));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullySpaceSB,  NullyFilledSB, spaceMatters));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullySpaceSB,  EmptySB,       spaceMatters));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullySpaceSB,  SpaceSB,       spaceMatters));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullySpaceSB,  FilledSB,      spaceMatters));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullyFilledSB, NullSB,        spaceMatters));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullyFilledSB, NullyEmptySB,  spaceMatters));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullyFilledSB, NullySpaceSB,  spaceMatters));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullyFilledSB, NullyFilledSB, spaceMatters));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullyFilledSB, EmptySB,       spaceMatters));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullyFilledSB, SpaceSB,       spaceMatters));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullyFilledSB, FilledSB,      spaceMatters));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(EmptySB,       NullSB,        spaceMatters));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(EmptySB,       NullyEmptySB,  spaceMatters));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(EmptySB,       NullySpaceSB,  spaceMatters));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(EmptySB,       NullyFilledSB, spaceMatters));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(EmptySB,       EmptySB,       spaceMatters));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(EmptySB,       SpaceSB,       spaceMatters));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(EmptySB,       FilledSB,      spaceMatters));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(SpaceSB,       NullSB,        spaceMatters));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(SpaceSB,       NullyEmptySB,  spaceMatters));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(SpaceSB,       NullySpaceSB,  spaceMatters));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(SpaceSB,       NullyFilledSB, spaceMatters));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(SpaceSB,       EmptySB,       spaceMatters));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(SpaceSB,       SpaceSB,       spaceMatters));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(SpaceSB,       FilledSB,      spaceMatters));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(FilledSB,      NullSB,        spaceMatters));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(FilledSB,      NullyEmptySB,  spaceMatters));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(FilledSB,      NullySpaceSB,  spaceMatters));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(FilledSB,      NullyFilledSB, spaceMatters));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(FilledSB,      EmptySB,       spaceMatters));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(FilledSB,      SpaceSB,       spaceMatters));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(FilledSB,      FilledSB,      spaceMatters));
    }
    
    [TestMethod]
    public void Coalesce_3Args_SBs_ExtensionsSpaceMattersYes_ExplicitBool()
    {
        NoNullRet(                 NullSB       .Coalesce(NullSB,        NullSB,        spaceMatters: true));
        NoNullRet($"{EmptySB}", $"{NullSB       .Coalesce(NullSB,        NullSB,        spaceMatters: true)}");
        NoNullRet(   EmptySB,      NullSB       .Coalesce(NullSB,        NullyEmptySB,  spaceMatters: true));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(NullSB,        NullySpaceSB,  spaceMatters: true));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(NullSB,        NullyFilledSB, spaceMatters: true));
        NoNullRet(   EmptySB,      NullSB       .Coalesce(NullSB,        EmptySB,       spaceMatters: true));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(NullSB,        SpaceSB,       spaceMatters: true));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(NullSB,        FilledSB,      spaceMatters: true));
        NoNullRet(                 NullSB       .Coalesce(NullyEmptySB,  NullSB,        spaceMatters: true));
        NoNullRet($"{EmptySB}", $"{NullSB       .Coalesce(NullyEmptySB,  NullSB,        spaceMatters: true)}");
        NoNullRet(   EmptySB,      NullSB       .Coalesce(NullyEmptySB,  NullyEmptySB,  spaceMatters: true));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(NullyEmptySB,  NullySpaceSB,  spaceMatters: true));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(NullyEmptySB,  NullyFilledSB, spaceMatters: true));
        NoNullRet(   EmptySB,      NullSB       .Coalesce(NullyEmptySB,  EmptySB,       spaceMatters: true));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(NullyEmptySB,  SpaceSB,       spaceMatters: true));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(NullyEmptySB,  FilledSB,      spaceMatters: true));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(NullySpaceSB,  NullSB,        spaceMatters: true));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(NullySpaceSB,  NullyEmptySB,  spaceMatters: true));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(NullySpaceSB,  NullySpaceSB,  spaceMatters: true));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(NullySpaceSB,  NullyFilledSB, spaceMatters: true));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(NullySpaceSB,  EmptySB,       spaceMatters: true));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(NullySpaceSB,  SpaceSB,       spaceMatters: true));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(NullySpaceSB,  FilledSB,      spaceMatters: true));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(NullyFilledSB, NullSB,        spaceMatters: true));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(NullyFilledSB, NullyEmptySB,  spaceMatters: true));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(NullyFilledSB, NullySpaceSB,  spaceMatters: true));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(NullyFilledSB, NullyFilledSB, spaceMatters: true));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(NullyFilledSB, EmptySB,       spaceMatters: true));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(NullyFilledSB, SpaceSB,       spaceMatters: true));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(NullyFilledSB, FilledSB,      spaceMatters: true));
        NoNullRet(                 NullSB       .Coalesce(EmptySB,       NullSB,        spaceMatters: true));
        NoNullRet($"{EmptySB}", $"{NullSB       .Coalesce(EmptySB,       NullSB,        spaceMatters: true)}");
        NoNullRet(   EmptySB,      NullSB       .Coalesce(EmptySB,       NullyEmptySB,  spaceMatters: true));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(EmptySB,       NullySpaceSB,  spaceMatters: true));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(EmptySB,       NullyFilledSB, spaceMatters: true));
        NoNullRet(   EmptySB,      NullSB       .Coalesce(EmptySB,       EmptySB,       spaceMatters: true));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(EmptySB,       SpaceSB,       spaceMatters: true));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(EmptySB,       FilledSB,      spaceMatters: true));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(SpaceSB,       NullSB,        spaceMatters: true));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(SpaceSB,       NullyEmptySB,  spaceMatters: true));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(SpaceSB,       NullySpaceSB,  spaceMatters: true));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(SpaceSB,       NullyFilledSB, spaceMatters: true));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(SpaceSB,       EmptySB,       spaceMatters: true));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(SpaceSB,       SpaceSB,       spaceMatters: true));
        NoNullRet(   SpaceSB,      NullSB       .Coalesce(SpaceSB,       FilledSB,      spaceMatters: true));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(FilledSB,      NullSB,        spaceMatters: true));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(FilledSB,      NullyEmptySB,  spaceMatters: true));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(FilledSB,      NullySpaceSB,  spaceMatters: true));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(FilledSB,      NullyFilledSB, spaceMatters: true));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(FilledSB,      EmptySB,       spaceMatters: true));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(FilledSB,      SpaceSB,       spaceMatters: true));
        NoNullRet(   FilledSB,     NullSB       .Coalesce(FilledSB,      FilledSB,      spaceMatters: true));
        
        NoNullRet(                 NullyEmptySB .Coalesce(NullSB,        NullSB,        spaceMatters: true));
        NoNullRet($"{EmptySB}", $"{NullyEmptySB .Coalesce(NullSB,        NullSB,        spaceMatters: true)}");
        NoNullRet(   EmptySB,      NullyEmptySB .Coalesce(NullSB,        NullyEmptySB,  spaceMatters: true));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(NullSB,        NullySpaceSB,  spaceMatters: true));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(NullSB,        NullyFilledSB, spaceMatters: true));
        NoNullRet(   EmptySB,      NullyEmptySB .Coalesce(NullSB,        EmptySB,       spaceMatters: true));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(NullSB,        SpaceSB,       spaceMatters: true));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(NullSB,        FilledSB,      spaceMatters: true));
        NoNullRet(                 NullyEmptySB .Coalesce(NullyEmptySB,  NullSB,        spaceMatters: true));
        NoNullRet($"{EmptySB}", $"{NullyEmptySB .Coalesce(NullyEmptySB,  NullSB,        spaceMatters: true)}");
        NoNullRet(   EmptySB,      NullyEmptySB .Coalesce(NullyEmptySB,  NullyEmptySB,  spaceMatters: true));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(NullyEmptySB,  NullySpaceSB,  spaceMatters: true));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(NullyEmptySB,  NullyFilledSB, spaceMatters: true));
        NoNullRet(   EmptySB,      NullyEmptySB .Coalesce(NullyEmptySB,  EmptySB,       spaceMatters: true));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(NullyEmptySB,  SpaceSB,       spaceMatters: true));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(NullyEmptySB,  FilledSB,      spaceMatters: true));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(NullySpaceSB,  NullSB,        spaceMatters: true));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(NullySpaceSB,  NullyEmptySB,  spaceMatters: true));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(NullySpaceSB,  NullySpaceSB,  spaceMatters: true));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(NullySpaceSB,  NullyFilledSB, spaceMatters: true));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(NullySpaceSB,  EmptySB,       spaceMatters: true));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(NullySpaceSB,  SpaceSB,       spaceMatters: true));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(NullySpaceSB,  FilledSB,      spaceMatters: true));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(NullyFilledSB, NullSB,        spaceMatters: true));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(NullyFilledSB, NullyEmptySB,  spaceMatters: true));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(NullyFilledSB, NullySpaceSB,  spaceMatters: true));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(NullyFilledSB, NullyFilledSB, spaceMatters: true));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(NullyFilledSB, EmptySB,       spaceMatters: true));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(NullyFilledSB, SpaceSB,       spaceMatters: true));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(NullyFilledSB, FilledSB,      spaceMatters: true));
        NoNullRet(                 NullyEmptySB .Coalesce(EmptySB,       NullSB,        spaceMatters: true));
        NoNullRet($"{EmptySB}", $"{NullyEmptySB .Coalesce(EmptySB,       NullSB,        spaceMatters: true)}");
        NoNullRet(   EmptySB,      NullyEmptySB .Coalesce(EmptySB,       NullyEmptySB,  spaceMatters: true));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(EmptySB,       NullySpaceSB,  spaceMatters: true));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(EmptySB,       NullyFilledSB, spaceMatters: true));
        NoNullRet(   EmptySB,      NullyEmptySB .Coalesce(EmptySB,       EmptySB,       spaceMatters: true));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(EmptySB,       SpaceSB,       spaceMatters: true));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(EmptySB,       FilledSB,      spaceMatters: true));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(SpaceSB,       NullSB,        spaceMatters: true));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(SpaceSB,       NullyEmptySB,  spaceMatters: true));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(SpaceSB,       NullySpaceSB,  spaceMatters: true));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(SpaceSB,       NullyFilledSB, spaceMatters: true));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(SpaceSB,       EmptySB,       spaceMatters: true));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(SpaceSB,       SpaceSB,       spaceMatters: true));
        NoNullRet(   SpaceSB,      NullyEmptySB .Coalesce(SpaceSB,       FilledSB,      spaceMatters: true));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(FilledSB,      NullSB,        spaceMatters: true));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(FilledSB,      NullyEmptySB,  spaceMatters: true));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(FilledSB,      NullySpaceSB,  spaceMatters: true));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(FilledSB,      NullyFilledSB, spaceMatters: true));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(FilledSB,      EmptySB,       spaceMatters: true));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(FilledSB,      SpaceSB,       spaceMatters: true));
        NoNullRet(   FilledSB,     NullyEmptySB .Coalesce(FilledSB,      FilledSB,      spaceMatters: true));

        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullSB,        NullSB,        spaceMatters: true));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullSB,        NullyEmptySB,  spaceMatters: true));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullSB,        NullySpaceSB,  spaceMatters: true));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullSB,        NullyFilledSB, spaceMatters: true));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullSB,        EmptySB,       spaceMatters: true));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullSB,        SpaceSB,       spaceMatters: true));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullSB,        FilledSB,      spaceMatters: true));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullyEmptySB,  NullSB,        spaceMatters: true));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullyEmptySB,  NullyEmptySB,  spaceMatters: true));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullyEmptySB,  NullySpaceSB,  spaceMatters: true));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullyEmptySB,  NullyFilledSB, spaceMatters: true));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullyEmptySB,  EmptySB,       spaceMatters: true));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullyEmptySB,  SpaceSB,       spaceMatters: true));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullyEmptySB,  FilledSB,      spaceMatters: true));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullySpaceSB,  NullSB,        spaceMatters: true));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullySpaceSB,  NullyEmptySB,  spaceMatters: true));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullySpaceSB,  NullySpaceSB,  spaceMatters: true));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullySpaceSB,  NullyFilledSB, spaceMatters: true));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullySpaceSB,  EmptySB,       spaceMatters: true));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullySpaceSB,  SpaceSB,       spaceMatters: true));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullySpaceSB,  FilledSB,      spaceMatters: true));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullyFilledSB, NullSB,        spaceMatters: true));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullyFilledSB, NullyEmptySB,  spaceMatters: true));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullyFilledSB, NullySpaceSB,  spaceMatters: true));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullyFilledSB, NullyFilledSB, spaceMatters: true));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullyFilledSB, EmptySB,       spaceMatters: true));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullyFilledSB, SpaceSB,       spaceMatters: true));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(NullyFilledSB, FilledSB,      spaceMatters: true));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(EmptySB,       NullSB,        spaceMatters: true));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(EmptySB,       NullyEmptySB,  spaceMatters: true));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(EmptySB,       NullySpaceSB,  spaceMatters: true));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(EmptySB,       NullyFilledSB, spaceMatters: true));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(EmptySB,       EmptySB,       spaceMatters: true));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(EmptySB,       SpaceSB,       spaceMatters: true));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(EmptySB,       FilledSB,      spaceMatters: true));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(SpaceSB,       NullSB,        spaceMatters: true));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(SpaceSB,       NullyEmptySB,  spaceMatters: true));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(SpaceSB,       NullySpaceSB,  spaceMatters: true));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(SpaceSB,       NullyFilledSB, spaceMatters: true));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(SpaceSB,       EmptySB,       spaceMatters: true));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(SpaceSB,       SpaceSB,       spaceMatters: true));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(SpaceSB,       FilledSB,      spaceMatters: true));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(FilledSB,      NullSB,        spaceMatters: true));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(FilledSB,      NullyEmptySB,  spaceMatters: true));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(FilledSB,      NullySpaceSB,  spaceMatters: true));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(FilledSB,      NullyFilledSB, spaceMatters: true));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(FilledSB,      EmptySB,       spaceMatters: true));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(FilledSB,      SpaceSB,       spaceMatters: true));
        NoNullRet(   SpaceSB,      NullySpaceSB .Coalesce(FilledSB,      FilledSB,      spaceMatters: true));

        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullSB,        NullSB,        spaceMatters: true));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullSB,        NullyEmptySB,  spaceMatters: true));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullSB,        NullySpaceSB,  spaceMatters: true));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullSB,        NullyFilledSB, spaceMatters: true));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullSB,        EmptySB,       spaceMatters: true));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullSB,        SpaceSB,       spaceMatters: true));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullSB,        FilledSB,      spaceMatters: true));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullyEmptySB,  NullSB,        spaceMatters: true));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullyEmptySB,  NullyEmptySB,  spaceMatters: true));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullyEmptySB,  NullySpaceSB,  spaceMatters: true));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullyEmptySB,  NullyFilledSB, spaceMatters: true));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullyEmptySB,  EmptySB,       spaceMatters: true));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullyEmptySB,  SpaceSB,       spaceMatters: true));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullyEmptySB,  FilledSB,      spaceMatters: true));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullySpaceSB,  NullSB,        spaceMatters: true));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullySpaceSB,  NullyEmptySB,  spaceMatters: true));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullySpaceSB,  NullySpaceSB,  spaceMatters: true));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullySpaceSB,  NullyFilledSB, spaceMatters: true));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullySpaceSB,  EmptySB,       spaceMatters: true));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullySpaceSB,  SpaceSB,       spaceMatters: true));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullySpaceSB,  FilledSB,      spaceMatters: true));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullyFilledSB, NullSB,        spaceMatters: true));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullyFilledSB, NullyEmptySB,  spaceMatters: true));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullyFilledSB, NullySpaceSB,  spaceMatters: true));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullyFilledSB, NullyFilledSB, spaceMatters: true));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullyFilledSB, EmptySB,       spaceMatters: true));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullyFilledSB, SpaceSB,       spaceMatters: true));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(NullyFilledSB, FilledSB,      spaceMatters: true));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(EmptySB,       NullSB,        spaceMatters: true));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(EmptySB,       NullyEmptySB,  spaceMatters: true));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(EmptySB,       NullySpaceSB,  spaceMatters: true));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(EmptySB,       NullyFilledSB, spaceMatters: true));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(EmptySB,       EmptySB,       spaceMatters: true));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(EmptySB,       SpaceSB,       spaceMatters: true));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(EmptySB,       FilledSB,      spaceMatters: true));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(SpaceSB,       NullSB,        spaceMatters: true));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(SpaceSB,       NullyEmptySB,  spaceMatters: true));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(SpaceSB,       NullySpaceSB,  spaceMatters: true));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(SpaceSB,       NullyFilledSB, spaceMatters: true));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(SpaceSB,       EmptySB,       spaceMatters: true));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(SpaceSB,       SpaceSB,       spaceMatters: true));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(SpaceSB,       FilledSB,      spaceMatters: true));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(FilledSB,      NullSB,        spaceMatters: true));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(FilledSB,      NullyEmptySB,  spaceMatters: true));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(FilledSB,      NullySpaceSB,  spaceMatters: true));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(FilledSB,      NullyFilledSB, spaceMatters: true));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(FilledSB,      EmptySB,       spaceMatters: true));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(FilledSB,      SpaceSB,       spaceMatters: true));
        NoNullRet(   FilledSB,     NullyFilledSB.Coalesce(FilledSB,      FilledSB,      spaceMatters: true));

        NoNullRet(                 EmptySB      .Coalesce(NullSB,        NullSB,        spaceMatters: true));
        NoNullRet($"{EmptySB}", $"{EmptySB      .Coalesce(NullSB,        NullSB,        spaceMatters: true)}");
        NoNullRet(   EmptySB,      EmptySB      .Coalesce(NullSB,        NullyEmptySB,  spaceMatters: true));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(NullSB,        NullySpaceSB,  spaceMatters: true));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(NullSB,        NullyFilledSB, spaceMatters: true));
        NoNullRet(   EmptySB,      EmptySB      .Coalesce(NullSB,        EmptySB,       spaceMatters: true));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(NullSB,        SpaceSB,       spaceMatters: true));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(NullSB,        FilledSB,      spaceMatters: true));
        NoNullRet(                 EmptySB      .Coalesce(NullyEmptySB,  NullSB,        spaceMatters: true));
        NoNullRet($"{EmptySB}", $"{EmptySB      .Coalesce(NullyEmptySB,  NullSB,        spaceMatters: true)}");
        NoNullRet(   EmptySB,      EmptySB      .Coalesce(NullyEmptySB,  NullyEmptySB,  spaceMatters: true));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(NullyEmptySB,  NullySpaceSB,  spaceMatters: true));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(NullyEmptySB,  NullyFilledSB, spaceMatters: true));
        NoNullRet(   EmptySB,      EmptySB      .Coalesce(NullyEmptySB,  EmptySB,       spaceMatters: true));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(NullyEmptySB,  SpaceSB,       spaceMatters: true));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(NullyEmptySB,  FilledSB,      spaceMatters: true));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(NullySpaceSB,  NullSB,        spaceMatters: true));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(NullySpaceSB,  NullyEmptySB,  spaceMatters: true));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(NullySpaceSB,  NullySpaceSB,  spaceMatters: true));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(NullySpaceSB,  NullyFilledSB, spaceMatters: true));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(NullySpaceSB,  EmptySB,       spaceMatters: true));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(NullySpaceSB,  SpaceSB,       spaceMatters: true));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(NullySpaceSB,  FilledSB,      spaceMatters: true));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(NullyFilledSB, NullSB,        spaceMatters: true));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(NullyFilledSB, NullyEmptySB,  spaceMatters: true));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(NullyFilledSB, NullySpaceSB,  spaceMatters: true));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(NullyFilledSB, NullyFilledSB, spaceMatters: true));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(NullyFilledSB, EmptySB,       spaceMatters: true));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(NullyFilledSB, SpaceSB,       spaceMatters: true));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(NullyFilledSB, FilledSB,      spaceMatters: true));
        NoNullRet(                 EmptySB      .Coalesce(EmptySB,       NullSB,        spaceMatters: true));
        NoNullRet($"{EmptySB}", $"{EmptySB      .Coalesce(EmptySB,       NullSB,        spaceMatters: true)}");
        NoNullRet(   EmptySB,      EmptySB      .Coalesce(EmptySB,       NullyEmptySB,  spaceMatters: true));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(EmptySB,       NullySpaceSB,  spaceMatters: true));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(EmptySB,       NullyFilledSB, spaceMatters: true));
        NoNullRet(   EmptySB,      EmptySB      .Coalesce(EmptySB,       EmptySB,       spaceMatters: true));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(EmptySB,       SpaceSB,       spaceMatters: true));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(EmptySB,       FilledSB,      spaceMatters: true));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(SpaceSB,       NullSB,        spaceMatters: true));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(SpaceSB,       NullyEmptySB,  spaceMatters: true));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(SpaceSB,       NullySpaceSB,  spaceMatters: true));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(SpaceSB,       NullyFilledSB, spaceMatters: true));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(SpaceSB,       EmptySB,       spaceMatters: true));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(SpaceSB,       SpaceSB,       spaceMatters: true));
        NoNullRet(   SpaceSB,      EmptySB      .Coalesce(SpaceSB,       FilledSB,      spaceMatters: true));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(FilledSB,      NullSB,        spaceMatters: true));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(FilledSB,      NullyEmptySB,  spaceMatters: true));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(FilledSB,      NullySpaceSB,  spaceMatters: true));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(FilledSB,      NullyFilledSB, spaceMatters: true));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(FilledSB,      EmptySB,       spaceMatters: true));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(FilledSB,      SpaceSB,       spaceMatters: true));
        NoNullRet(   FilledSB,     EmptySB      .Coalesce(FilledSB,      FilledSB,      spaceMatters: true));
                                                                
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullSB,        NullSB,        spaceMatters: true));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullSB,        NullyEmptySB,  spaceMatters: true));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullSB,        NullySpaceSB,  spaceMatters: true));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullSB,        NullyFilledSB, spaceMatters: true));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullSB,        EmptySB,       spaceMatters: true));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullSB,        SpaceSB,       spaceMatters: true));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullSB,        FilledSB,      spaceMatters: true));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullyEmptySB,  NullSB,        spaceMatters: true));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullyEmptySB,  NullyEmptySB,  spaceMatters: true));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullyEmptySB,  NullySpaceSB,  spaceMatters: true));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullyEmptySB,  NullyFilledSB, spaceMatters: true));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullyEmptySB,  EmptySB,       spaceMatters: true));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullyEmptySB,  SpaceSB,       spaceMatters: true));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullyEmptySB,  FilledSB,      spaceMatters: true));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullySpaceSB,  NullSB,        spaceMatters: true));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullySpaceSB,  NullyEmptySB,  spaceMatters: true));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullySpaceSB,  NullySpaceSB,  spaceMatters: true));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullySpaceSB,  NullyFilledSB, spaceMatters: true));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullySpaceSB,  EmptySB,       spaceMatters: true));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullySpaceSB,  SpaceSB,       spaceMatters: true));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullySpaceSB,  FilledSB,      spaceMatters: true));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullyFilledSB, NullSB,        spaceMatters: true));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullyFilledSB, NullyEmptySB,  spaceMatters: true));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullyFilledSB, NullySpaceSB,  spaceMatters: true));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullyFilledSB, NullyFilledSB, spaceMatters: true));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullyFilledSB, EmptySB,       spaceMatters: true));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullyFilledSB, SpaceSB,       spaceMatters: true));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(NullyFilledSB, FilledSB,      spaceMatters: true));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(EmptySB,       NullSB,        spaceMatters: true));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(EmptySB,       NullyEmptySB,  spaceMatters: true));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(EmptySB,       NullySpaceSB,  spaceMatters: true));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(EmptySB,       NullyFilledSB, spaceMatters: true));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(EmptySB,       EmptySB,       spaceMatters: true));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(EmptySB,       SpaceSB,       spaceMatters: true));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(EmptySB,       FilledSB,      spaceMatters: true));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(SpaceSB,       NullSB,        spaceMatters: true));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(SpaceSB,       NullyEmptySB,  spaceMatters: true));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(SpaceSB,       NullySpaceSB,  spaceMatters: true));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(SpaceSB,       NullyFilledSB, spaceMatters: true));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(SpaceSB,       EmptySB,       spaceMatters: true));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(SpaceSB,       SpaceSB,       spaceMatters: true));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(SpaceSB,       FilledSB,      spaceMatters: true));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(FilledSB,      NullSB,        spaceMatters: true));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(FilledSB,      NullyEmptySB,  spaceMatters: true));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(FilledSB,      NullySpaceSB,  spaceMatters: true));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(FilledSB,      NullyFilledSB, spaceMatters: true));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(FilledSB,      EmptySB,       spaceMatters: true));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(FilledSB,      SpaceSB,       spaceMatters: true));
        NoNullRet(   SpaceSB,      SpaceSB      .Coalesce(FilledSB,      FilledSB,      spaceMatters: true));
                                                                
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullSB,        NullSB,        spaceMatters: true));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullSB,        NullyEmptySB,  spaceMatters: true));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullSB,        NullySpaceSB,  spaceMatters: true));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullSB,        NullyFilledSB, spaceMatters: true));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullSB,        EmptySB,       spaceMatters: true));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullSB,        SpaceSB,       spaceMatters: true));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullSB,        FilledSB,      spaceMatters: true));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullyEmptySB,  NullSB,        spaceMatters: true));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullyEmptySB,  NullyEmptySB,  spaceMatters: true));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullyEmptySB,  NullySpaceSB,  spaceMatters: true));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullyEmptySB,  NullyFilledSB, spaceMatters: true));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullyEmptySB,  EmptySB,       spaceMatters: true));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullyEmptySB,  SpaceSB,       spaceMatters: true));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullyEmptySB,  FilledSB,      spaceMatters: true));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullySpaceSB,  NullSB,        spaceMatters: true));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullySpaceSB,  NullyEmptySB,  spaceMatters: true));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullySpaceSB,  NullySpaceSB,  spaceMatters: true));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullySpaceSB,  NullyFilledSB, spaceMatters: true));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullySpaceSB,  EmptySB,       spaceMatters: true));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullySpaceSB,  SpaceSB,       spaceMatters: true));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullySpaceSB,  FilledSB,      spaceMatters: true));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullyFilledSB, NullSB,        spaceMatters: true));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullyFilledSB, NullyEmptySB,  spaceMatters: true));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullyFilledSB, NullySpaceSB,  spaceMatters: true));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullyFilledSB, NullyFilledSB, spaceMatters: true));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullyFilledSB, EmptySB,       spaceMatters: true));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullyFilledSB, SpaceSB,       spaceMatters: true));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(NullyFilledSB, FilledSB,      spaceMatters: true));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(EmptySB,       NullSB,        spaceMatters: true));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(EmptySB,       NullyEmptySB,  spaceMatters: true));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(EmptySB,       NullySpaceSB,  spaceMatters: true));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(EmptySB,       NullyFilledSB, spaceMatters: true));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(EmptySB,       EmptySB,       spaceMatters: true));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(EmptySB,       SpaceSB,       spaceMatters: true));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(EmptySB,       FilledSB,      spaceMatters: true));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(SpaceSB,       NullSB,        spaceMatters: true));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(SpaceSB,       NullyEmptySB,  spaceMatters: true));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(SpaceSB,       NullySpaceSB,  spaceMatters: true));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(SpaceSB,       NullyFilledSB, spaceMatters: true));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(SpaceSB,       EmptySB,       spaceMatters: true));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(SpaceSB,       SpaceSB,       spaceMatters: true));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(SpaceSB,       FilledSB,      spaceMatters: true));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(FilledSB,      NullSB,        spaceMatters: true));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(FilledSB,      NullyEmptySB,  spaceMatters: true));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(FilledSB,      NullySpaceSB,  spaceMatters: true));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(FilledSB,      NullyFilledSB, spaceMatters: true));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(FilledSB,      EmptySB,       spaceMatters: true));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(FilledSB,      SpaceSB,       spaceMatters: true));
        NoNullRet(   FilledSB,     FilledSB     .Coalesce(FilledSB,      FilledSB,      spaceMatters: true));
    }
}