namespace JJ.Framework.Existence.Core.Tests;

/// <inheritdoc cref="_coalesce3argssbtotext" />
[TestClass]
public class Coalesce_3Args_SBToText_ExtensionsSpaceMattersNoExplicit : TestBase
{
    private const string? NullyFilled = NullyFilledText;
    private const string? Null = NullText;
    
    /// <inheritdoc cref="_coalesce3argssbtotext" />
    [TestMethod]
    public void Coalesce_3Args_SBToText_ExtensionsSpaceMattersNo_Explicit()
    {
        NoNullRet("",         NullSB       .Coalesce( NullSB,        Null,        spaceMatters: false));
        NoNullRet("",         NullSB       .Coalesce( NullSB,        Empty,       spaceMatters: false));
        NoNullRet(" ",        NullSB       .Coalesce( NullSB,        Space,       spaceMatters: false));
        NoNullRet(Text,       NullSB       .Coalesce( NullSB,        Text,        spaceMatters: false));
        NoNullRet("",         NullSB       .Coalesce( NullSB,        NullyEmpty,  spaceMatters: false));
        NoNullRet(" ",        NullSB       .Coalesce( NullSB,        NullySpace,  spaceMatters: false));
        NoNullRet(Text,       NullSB       .Coalesce( NullSB,        NullyFilled, spaceMatters: false));
        NoNullRet("",         NullSB       .Coalesce( NullyEmptySB,  Null,        spaceMatters: false));
        NoNullRet("",         NullSB       .Coalesce( NullyEmptySB,  Empty,       spaceMatters: false));
        NoNullRet(" ",        NullSB       .Coalesce( NullyEmptySB,  Space,       spaceMatters: false));
        NoNullRet(Text,       NullSB       .Coalesce( NullyEmptySB,  Text,        spaceMatters: false));
        NoNullRet("",         NullSB       .Coalesce( NullyEmptySB,  NullyEmpty,  spaceMatters: false));
        NoNullRet(" ",        NullSB       .Coalesce( NullyEmptySB,  NullySpace,  spaceMatters: false));
        NoNullRet(Text,       NullSB       .Coalesce( NullyEmptySB,  NullyFilled, spaceMatters: false));
        NoNullRet("",         NullSB       .Coalesce( NullySpaceSB,  Null,        spaceMatters: false));
        NoNullRet("",         NullSB       .Coalesce( NullySpaceSB,  Empty,       spaceMatters: false));
        NoNullRet(" ",        NullSB       .Coalesce( NullySpaceSB,  Space,       spaceMatters: false));
        NoNullRet(Text,       NullSB       .Coalesce( NullySpaceSB,  Text,        spaceMatters: false));
        NoNullRet("",         NullSB       .Coalesce( NullySpaceSB,  NullyEmpty,  spaceMatters: false));
        NoNullRet(" ",        NullSB       .Coalesce( NullySpaceSB,  NullySpace,  spaceMatters: false));
        NoNullRet(Text,       NullSB       .Coalesce( NullySpaceSB,  NullyFilled, spaceMatters: false));
        NoNullRet("FilledSB", NullSB       .Coalesce( NullyFilledSB, Null,        spaceMatters: false));
        NoNullRet("FilledSB", NullSB       .Coalesce( NullyFilledSB, Empty,       spaceMatters: false));
        NoNullRet("FilledSB", NullSB       .Coalesce( NullyFilledSB, Space,       spaceMatters: false));
        NoNullRet("FilledSB", NullSB       .Coalesce( NullyFilledSB, Text,        spaceMatters: false));
        NoNullRet("FilledSB", NullSB       .Coalesce( NullyFilledSB, NullyEmpty,  spaceMatters: false));
        NoNullRet("FilledSB", NullSB       .Coalesce( NullyFilledSB, NullySpace,  spaceMatters: false));
        NoNullRet("FilledSB", NullSB       .Coalesce( NullyFilledSB, NullyFilled, spaceMatters: false));
        NoNullRet("",         NullSB       .Coalesce( EmptySB,       Null,        spaceMatters: false));
        NoNullRet("",         NullSB       .Coalesce( EmptySB,       Empty,       spaceMatters: false));
        NoNullRet(" ",        NullSB       .Coalesce( EmptySB,       Space,       spaceMatters: false));
        NoNullRet(Text,       NullSB       .Coalesce( EmptySB,       Text,        spaceMatters: false));
        NoNullRet("",         NullSB       .Coalesce( EmptySB,       NullyEmpty,  spaceMatters: false));
        NoNullRet(" ",        NullSB       .Coalesce( EmptySB,       NullySpace,  spaceMatters: false));
        NoNullRet(Text,       NullSB       .Coalesce( EmptySB,       NullyFilled, spaceMatters: false));
        NoNullRet("",         NullSB       .Coalesce( SpaceSB,       Null,        spaceMatters: false));
        NoNullRet("",         NullSB       .Coalesce( SpaceSB,       Empty,       spaceMatters: false));
        NoNullRet(" ",        NullSB       .Coalesce( SpaceSB,       Space,       spaceMatters: false));
        NoNullRet(Text,       NullSB       .Coalesce( SpaceSB,       Text,        spaceMatters: false));
        NoNullRet("",         NullSB       .Coalesce( SpaceSB,       NullyEmpty,  spaceMatters: false));
        NoNullRet(" ",        NullSB       .Coalesce( SpaceSB,       NullySpace,  spaceMatters: false));
        NoNullRet(Text,       NullSB       .Coalesce( SpaceSB,       NullyFilled, spaceMatters: false));
        NoNullRet("FilledSB", NullSB       .Coalesce( FilledSB,      Null,        spaceMatters: false));
        NoNullRet("FilledSB", NullSB       .Coalesce( FilledSB,      Empty,       spaceMatters: false));
        NoNullRet("FilledSB", NullSB       .Coalesce( FilledSB,      Space,       spaceMatters: false));
        NoNullRet("FilledSB", NullSB       .Coalesce( FilledSB,      Text,        spaceMatters: false));
        NoNullRet("FilledSB", NullSB       .Coalesce( FilledSB,      NullyEmpty,  spaceMatters: false));
        NoNullRet("FilledSB", NullSB       .Coalesce( FilledSB,      NullySpace,  spaceMatters: false));
        NoNullRet("FilledSB", NullSB       .Coalesce( FilledSB,      NullyFilled, spaceMatters: false));
                                                      
        NoNullRet("",         NullyEmptySB .Coalesce( NullSB,        Null,        spaceMatters: false));
        NoNullRet("",         NullyEmptySB .Coalesce( NullSB,        Empty,       spaceMatters: false));
        NoNullRet(" ",        NullyEmptySB .Coalesce( NullSB,        Space,       spaceMatters: false));
        NoNullRet(Text,       NullyEmptySB .Coalesce( NullSB,        Text,        spaceMatters: false));
        NoNullRet("",         NullyEmptySB .Coalesce( NullSB,        NullyEmpty,  spaceMatters: false));
        NoNullRet(" ",        NullyEmptySB .Coalesce( NullSB,        NullySpace,  spaceMatters: false));
        NoNullRet(Text,       NullyEmptySB .Coalesce( NullSB,        NullyFilled, spaceMatters: false));
        NoNullRet("",         NullyEmptySB .Coalesce( NullyEmptySB,  Null,        spaceMatters: false));
        NoNullRet("",         NullyEmptySB .Coalesce( NullyEmptySB,  Empty,       spaceMatters: false));
        NoNullRet(" ",        NullyEmptySB .Coalesce( NullyEmptySB,  Space,       spaceMatters: false));
        NoNullRet(Text,       NullyEmptySB .Coalesce( NullyEmptySB,  Text,        spaceMatters: false));
        NoNullRet("",         NullyEmptySB .Coalesce( NullyEmptySB,  NullyEmpty,  spaceMatters: false));
        NoNullRet(" ",        NullyEmptySB .Coalesce( NullyEmptySB,  NullySpace,  spaceMatters: false));
        NoNullRet(Text,       NullyEmptySB .Coalesce( NullyEmptySB,  NullyFilled, spaceMatters: false));
        NoNullRet("",         NullyEmptySB .Coalesce( NullySpaceSB,  Null,        spaceMatters: false));
        NoNullRet("",         NullyEmptySB .Coalesce( NullySpaceSB,  Empty,       spaceMatters: false));
        NoNullRet(" ",        NullyEmptySB .Coalesce( NullySpaceSB,  Space,       spaceMatters: false));
        NoNullRet(Text,       NullyEmptySB .Coalesce( NullySpaceSB,  Text,        spaceMatters: false));
        NoNullRet("",         NullyEmptySB .Coalesce( NullySpaceSB,  NullyEmpty,  spaceMatters: false));
        NoNullRet(" ",        NullyEmptySB .Coalesce( NullySpaceSB,  NullySpace,  spaceMatters: false));
        NoNullRet(Text,       NullyEmptySB .Coalesce( NullySpaceSB,  NullyFilled, spaceMatters: false));
        NoNullRet("FilledSB", NullyEmptySB .Coalesce( NullyFilledSB, Null,        spaceMatters: false));
        NoNullRet("FilledSB", NullyEmptySB .Coalesce( NullyFilledSB, Empty,       spaceMatters: false));
        NoNullRet("FilledSB", NullyEmptySB .Coalesce( NullyFilledSB, Space,       spaceMatters: false));
        NoNullRet("FilledSB", NullyEmptySB .Coalesce( NullyFilledSB, Text,        spaceMatters: false));
        NoNullRet("FilledSB", NullyEmptySB .Coalesce( NullyFilledSB, NullyEmpty,  spaceMatters: false));
        NoNullRet("FilledSB", NullyEmptySB .Coalesce( NullyFilledSB, NullySpace,  spaceMatters: false));
        NoNullRet("FilledSB", NullyEmptySB .Coalesce( NullyFilledSB, NullyFilled, spaceMatters: false));
        NoNullRet("",         NullyEmptySB .Coalesce( EmptySB,       Null,        spaceMatters: false));
        NoNullRet("",         NullyEmptySB .Coalesce( EmptySB,       Empty,       spaceMatters: false));
        NoNullRet(" ",        NullyEmptySB .Coalesce( EmptySB,       Space,       spaceMatters: false));
        NoNullRet(Text,       NullyEmptySB .Coalesce( EmptySB,       Text,        spaceMatters: false));
        NoNullRet("",         NullyEmptySB .Coalesce( EmptySB,       NullyEmpty,  spaceMatters: false));
        NoNullRet(" ",        NullyEmptySB .Coalesce( EmptySB,       NullySpace,  spaceMatters: false));
        NoNullRet(Text,       NullyEmptySB .Coalesce( EmptySB,       NullyFilled, spaceMatters: false));
        NoNullRet("",         NullyEmptySB .Coalesce( SpaceSB,       Null,        spaceMatters: false));
        NoNullRet("",         NullyEmptySB .Coalesce( SpaceSB,       Empty,       spaceMatters: false));
        NoNullRet(" ",        NullyEmptySB .Coalesce( SpaceSB,       Space,       spaceMatters: false));
        NoNullRet(Text,       NullyEmptySB .Coalesce( SpaceSB,       Text,        spaceMatters: false));
        NoNullRet("",         NullyEmptySB .Coalesce( SpaceSB,       NullyEmpty,  spaceMatters: false));
        NoNullRet(" ",        NullyEmptySB .Coalesce( SpaceSB,       NullySpace,  spaceMatters: false));
        NoNullRet(Text,       NullyEmptySB .Coalesce( SpaceSB,       NullyFilled, spaceMatters: false));
        NoNullRet("FilledSB", NullyEmptySB .Coalesce( FilledSB,      Null,        spaceMatters: false));
        NoNullRet("FilledSB", NullyEmptySB .Coalesce( FilledSB,      Empty,       spaceMatters: false));
        NoNullRet("FilledSB", NullyEmptySB .Coalesce( FilledSB,      Space,       spaceMatters: false));
        NoNullRet("FilledSB", NullyEmptySB .Coalesce( FilledSB,      Text,        spaceMatters: false));
        NoNullRet("FilledSB", NullyEmptySB .Coalesce( FilledSB,      NullyEmpty,  spaceMatters: false));
        NoNullRet("FilledSB", NullyEmptySB .Coalesce( FilledSB,      NullySpace,  spaceMatters: false));
        NoNullRet("FilledSB", NullyEmptySB .Coalesce( FilledSB,      NullyFilled, spaceMatters: false));
                                                      
        NoNullRet("",         NullySpaceSB .Coalesce( NullSB,        Null,        spaceMatters: false));
        NoNullRet("",         NullySpaceSB .Coalesce( NullSB,        Empty,       spaceMatters: false));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullSB,        Space,       spaceMatters: false));
        NoNullRet(Text,       NullySpaceSB .Coalesce( NullSB,        Text,        spaceMatters: false));
        NoNullRet("",         NullySpaceSB .Coalesce( NullSB,        NullyEmpty,  spaceMatters: false));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullSB,        NullySpace,  spaceMatters: false));
        NoNullRet(Text,       NullySpaceSB .Coalesce( NullSB,        NullyFilled, spaceMatters: false));
        NoNullRet("",         NullySpaceSB .Coalesce( NullyEmptySB,  Null,        spaceMatters: false));
        NoNullRet("",         NullySpaceSB .Coalesce( NullyEmptySB,  Empty,       spaceMatters: false));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullyEmptySB,  Space,       spaceMatters: false));
        NoNullRet(Text,       NullySpaceSB .Coalesce( NullyEmptySB,  Text,        spaceMatters: false));
        NoNullRet("",         NullySpaceSB .Coalesce( NullyEmptySB,  NullyEmpty,  spaceMatters: false));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullyEmptySB,  NullySpace,  spaceMatters: false));
        NoNullRet(Text,       NullySpaceSB .Coalesce( NullyEmptySB,  NullyFilled, spaceMatters: false));
        NoNullRet("",         NullySpaceSB .Coalesce( NullySpaceSB,  Null,        spaceMatters: false));
        NoNullRet("",         NullySpaceSB .Coalesce( NullySpaceSB,  Empty,       spaceMatters: false));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullySpaceSB,  Space,       spaceMatters: false));
        NoNullRet(Text,       NullySpaceSB .Coalesce( NullySpaceSB,  Text,        spaceMatters: false));
        NoNullRet("",         NullySpaceSB .Coalesce( NullySpaceSB,  NullyEmpty,  spaceMatters: false));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullySpaceSB,  NullySpace,  spaceMatters: false));
        NoNullRet(Text,       NullySpaceSB .Coalesce( NullySpaceSB,  NullyFilled, spaceMatters: false));
        NoNullRet("FilledSB", NullySpaceSB .Coalesce( NullyFilledSB, Null,        spaceMatters: false));
        NoNullRet("FilledSB", NullySpaceSB .Coalesce( NullyFilledSB, Empty,       spaceMatters: false));
        NoNullRet("FilledSB", NullySpaceSB .Coalesce( NullyFilledSB, Space,       spaceMatters: false));
        NoNullRet("FilledSB", NullySpaceSB .Coalesce( NullyFilledSB, Text,        spaceMatters: false));
        NoNullRet("FilledSB", NullySpaceSB .Coalesce( NullyFilledSB, NullyEmpty,  spaceMatters: false));
        NoNullRet("FilledSB", NullySpaceSB .Coalesce( NullyFilledSB, NullySpace,  spaceMatters: false));
        NoNullRet("FilledSB", NullySpaceSB .Coalesce( NullyFilledSB, NullyFilled, spaceMatters: false));
        NoNullRet("",         NullySpaceSB .Coalesce( EmptySB,       Null,        spaceMatters: false));
        NoNullRet("",         NullySpaceSB .Coalesce( EmptySB,       Empty,       spaceMatters: false));
        NoNullRet(" ",        NullySpaceSB .Coalesce( EmptySB,       Space,       spaceMatters: false));
        NoNullRet(Text,       NullySpaceSB .Coalesce( EmptySB,       Text,        spaceMatters: false));
        NoNullRet("",         NullySpaceSB .Coalesce( EmptySB,       NullyEmpty,  spaceMatters: false));
        NoNullRet(" ",        NullySpaceSB .Coalesce( EmptySB,       NullySpace,  spaceMatters: false));
        NoNullRet(Text,       NullySpaceSB .Coalesce( EmptySB,       NullyFilled, spaceMatters: false));
        NoNullRet("",         NullySpaceSB .Coalesce( SpaceSB,       Null,        spaceMatters: false));
        NoNullRet("",         NullySpaceSB .Coalesce( SpaceSB,       Empty,       spaceMatters: false));
        NoNullRet(" ",        NullySpaceSB .Coalesce( SpaceSB,       Space,       spaceMatters: false));
        NoNullRet(Text,       NullySpaceSB .Coalesce( SpaceSB,       Text,        spaceMatters: false));
        NoNullRet("",         NullySpaceSB .Coalesce( SpaceSB,       NullyEmpty,  spaceMatters: false));
        NoNullRet(" ",        NullySpaceSB .Coalesce( SpaceSB,       NullySpace,  spaceMatters: false));
        NoNullRet(Text,       NullySpaceSB .Coalesce( SpaceSB,       NullyFilled, spaceMatters: false));
        NoNullRet("FilledSB", NullySpaceSB .Coalesce( FilledSB,      Null,        spaceMatters: false));
        NoNullRet("FilledSB", NullySpaceSB .Coalesce( FilledSB,      Empty,       spaceMatters: false));
        NoNullRet("FilledSB", NullySpaceSB .Coalesce( FilledSB,      Space,       spaceMatters: false));
        NoNullRet("FilledSB", NullySpaceSB .Coalesce( FilledSB,      Text,        spaceMatters: false));
        NoNullRet("FilledSB", NullySpaceSB .Coalesce( FilledSB,      NullyEmpty,  spaceMatters: false));
        NoNullRet("FilledSB", NullySpaceSB .Coalesce( FilledSB,      NullySpace,  spaceMatters: false));
        NoNullRet("FilledSB", NullySpaceSB .Coalesce( FilledSB,      NullyFilled, spaceMatters: false));
                                                      
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullSB,        Null,        spaceMatters: false));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullSB,        Empty,       spaceMatters: false));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullSB,        Space,       spaceMatters: false));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullSB,        Text,        spaceMatters: false));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullSB,        NullyEmpty,  spaceMatters: false));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullSB,        NullySpace,  spaceMatters: false));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullSB,        NullyFilled, spaceMatters: false));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyEmptySB,  Null,        spaceMatters: false));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyEmptySB,  Empty,       spaceMatters: false));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyEmptySB,  Space,       spaceMatters: false));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyEmptySB,  Text,        spaceMatters: false));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyEmptySB,  NullyEmpty,  spaceMatters: false));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyEmptySB,  NullySpace,  spaceMatters: false));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyEmptySB,  NullyFilled, spaceMatters: false));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullySpaceSB,  Null,        spaceMatters: false));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullySpaceSB,  Empty,       spaceMatters: false));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullySpaceSB,  Space,       spaceMatters: false));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullySpaceSB,  Text,        spaceMatters: false));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullySpaceSB,  NullyEmpty,  spaceMatters: false));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullySpaceSB,  NullySpace,  spaceMatters: false));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullySpaceSB,  NullyFilled, spaceMatters: false));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyFilledSB, Null,        spaceMatters: false));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyFilledSB, Empty,       spaceMatters: false));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyFilledSB, Space,       spaceMatters: false));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyFilledSB, Text,        spaceMatters: false));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyFilledSB, NullyEmpty,  spaceMatters: false));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyFilledSB, NullySpace,  spaceMatters: false));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyFilledSB, NullyFilled, spaceMatters: false));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( EmptySB,       Null,        spaceMatters: false));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( EmptySB,       Empty,       spaceMatters: false));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( EmptySB,       Space,       spaceMatters: false));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( EmptySB,       Text,        spaceMatters: false));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( EmptySB,       NullyEmpty,  spaceMatters: false));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( EmptySB,       NullySpace,  spaceMatters: false));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( EmptySB,       NullyFilled, spaceMatters: false));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( SpaceSB,       Null,        spaceMatters: false));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( SpaceSB,       Empty,       spaceMatters: false));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( SpaceSB,       Space,       spaceMatters: false));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( SpaceSB,       Text,        spaceMatters: false));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( SpaceSB,       NullyEmpty,  spaceMatters: false));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( SpaceSB,       NullySpace,  spaceMatters: false));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( SpaceSB,       NullyFilled, spaceMatters: false));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( FilledSB,      Null,        spaceMatters: false));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( FilledSB,      Empty,       spaceMatters: false));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( FilledSB,      Space,       spaceMatters: false));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( FilledSB,      Text,        spaceMatters: false));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( FilledSB,      NullyEmpty,  spaceMatters: false));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( FilledSB,      NullySpace,  spaceMatters: false));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( FilledSB,      NullyFilled, spaceMatters: false));
                                                      
        NoNullRet("",         EmptySB      .Coalesce( NullSB,        Null,        spaceMatters: false));
        NoNullRet("",         EmptySB      .Coalesce( NullSB,        Empty,       spaceMatters: false));
        NoNullRet(" ",        EmptySB      .Coalesce( NullSB,        Space,       spaceMatters: false));
        NoNullRet(Text,       EmptySB      .Coalesce( NullSB,        Text,        spaceMatters: false));
        NoNullRet("",         EmptySB      .Coalesce( NullSB,        NullyEmpty,  spaceMatters: false));
        NoNullRet(" ",        EmptySB      .Coalesce( NullSB,        NullySpace,  spaceMatters: false));
        NoNullRet(Text,       EmptySB      .Coalesce( NullSB,        NullyFilled, spaceMatters: false));
        NoNullRet("",         EmptySB      .Coalesce( NullyEmptySB,  Null,        spaceMatters: false));
        NoNullRet("",         EmptySB      .Coalesce( NullyEmptySB,  Empty,       spaceMatters: false));
        NoNullRet(" ",        EmptySB      .Coalesce( NullyEmptySB,  Space,       spaceMatters: false));
        NoNullRet(Text,       EmptySB      .Coalesce( NullyEmptySB,  Text,        spaceMatters: false));
        NoNullRet("",         EmptySB      .Coalesce( NullyEmptySB,  NullyEmpty,  spaceMatters: false));
        NoNullRet(" ",        EmptySB      .Coalesce( NullyEmptySB,  NullySpace,  spaceMatters: false));
        NoNullRet(Text,       EmptySB      .Coalesce( NullyEmptySB,  NullyFilled, spaceMatters: false));
        NoNullRet("",         EmptySB      .Coalesce( NullySpaceSB,  Null,        spaceMatters: false));
        NoNullRet("",         EmptySB      .Coalesce( NullySpaceSB,  Empty,       spaceMatters: false));
        NoNullRet(" ",        EmptySB      .Coalesce( NullySpaceSB,  Space,       spaceMatters: false));
        NoNullRet(Text,       EmptySB      .Coalesce( NullySpaceSB,  Text,        spaceMatters: false));
        NoNullRet("",         EmptySB      .Coalesce( NullySpaceSB,  NullyEmpty,  spaceMatters: false));
        NoNullRet(" ",        EmptySB      .Coalesce( NullySpaceSB,  NullySpace,  spaceMatters: false));
        NoNullRet(Text,       EmptySB      .Coalesce( NullySpaceSB,  NullyFilled, spaceMatters: false));
        NoNullRet("FilledSB", EmptySB      .Coalesce( NullyFilledSB, Null,        spaceMatters: false));
        NoNullRet("FilledSB", EmptySB      .Coalesce( NullyFilledSB, Empty,       spaceMatters: false));
        NoNullRet("FilledSB", EmptySB      .Coalesce( NullyFilledSB, Space,       spaceMatters: false));
        NoNullRet("FilledSB", EmptySB      .Coalesce( NullyFilledSB, Text,        spaceMatters: false));
        NoNullRet("FilledSB", EmptySB      .Coalesce( NullyFilledSB, NullyEmpty,  spaceMatters: false));
        NoNullRet("FilledSB", EmptySB      .Coalesce( NullyFilledSB, NullySpace,  spaceMatters: false));
        NoNullRet("FilledSB", EmptySB      .Coalesce( NullyFilledSB, NullyFilled, spaceMatters: false));
        NoNullRet("",         EmptySB      .Coalesce( EmptySB,       Null,        spaceMatters: false));
        NoNullRet("",         EmptySB      .Coalesce( EmptySB,       Empty,       spaceMatters: false));
        NoNullRet(" ",        EmptySB      .Coalesce( EmptySB,       Space,       spaceMatters: false));
        NoNullRet(Text,       EmptySB      .Coalesce( EmptySB,       Text,        spaceMatters: false));
        NoNullRet("",         EmptySB      .Coalesce( EmptySB,       NullyEmpty,  spaceMatters: false));
        NoNullRet(" ",        EmptySB      .Coalesce( EmptySB,       NullySpace,  spaceMatters: false));
        NoNullRet(Text,       EmptySB      .Coalesce( EmptySB,       NullyFilled, spaceMatters: false));
        NoNullRet("",         EmptySB      .Coalesce( SpaceSB,       Null,        spaceMatters: false));
        NoNullRet("",         EmptySB      .Coalesce( SpaceSB,       Empty,       spaceMatters: false));
        NoNullRet(" ",        EmptySB      .Coalesce( SpaceSB,       Space,       spaceMatters: false));
        NoNullRet(Text,       EmptySB      .Coalesce( SpaceSB,       Text,        spaceMatters: false));
        NoNullRet("",         EmptySB      .Coalesce( SpaceSB,       NullyEmpty,  spaceMatters: false));
        NoNullRet(" ",        EmptySB      .Coalesce( SpaceSB,       NullySpace,  spaceMatters: false));
        NoNullRet(Text,       EmptySB      .Coalesce( SpaceSB,       NullyFilled, spaceMatters: false));
        NoNullRet("FilledSB", EmptySB      .Coalesce( FilledSB,      Null,        spaceMatters: false));
        NoNullRet("FilledSB", EmptySB      .Coalesce( FilledSB,      Empty,       spaceMatters: false));
        NoNullRet("FilledSB", EmptySB      .Coalesce( FilledSB,      Space,       spaceMatters: false));
        NoNullRet("FilledSB", EmptySB      .Coalesce( FilledSB,      Text,        spaceMatters: false));
        NoNullRet("FilledSB", EmptySB      .Coalesce( FilledSB,      NullyEmpty,  spaceMatters: false));
        NoNullRet("FilledSB", EmptySB      .Coalesce( FilledSB,      NullySpace,  spaceMatters: false));
        NoNullRet("FilledSB", EmptySB      .Coalesce( FilledSB,      NullyFilled, spaceMatters: false));
        
        NoNullRet("",         SpaceSB      .Coalesce( NullSB,        Null,        spaceMatters: false));
        NoNullRet("",         SpaceSB      .Coalesce( NullSB,        Empty,       spaceMatters: false));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullSB,        Space,       spaceMatters: false));
        NoNullRet(Text,       SpaceSB      .Coalesce( NullSB,        Text,        spaceMatters: false));
        NoNullRet("",         SpaceSB      .Coalesce( NullSB,        NullyEmpty,  spaceMatters: false));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullSB,        NullySpace,  spaceMatters: false));
        NoNullRet(Text,       SpaceSB      .Coalesce( NullSB,        NullyFilled, spaceMatters: false));
        NoNullRet("",         SpaceSB      .Coalesce( NullyEmptySB,  Null,        spaceMatters: false));
        NoNullRet("",         SpaceSB      .Coalesce( NullyEmptySB,  Empty,       spaceMatters: false));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullyEmptySB,  Space,       spaceMatters: false));
        NoNullRet(Text,       SpaceSB      .Coalesce( NullyEmptySB,  Text,        spaceMatters: false));
        NoNullRet("",         SpaceSB      .Coalesce( NullyEmptySB,  NullyEmpty,  spaceMatters: false));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullyEmptySB,  NullySpace,  spaceMatters: false));
        NoNullRet(Text,       SpaceSB      .Coalesce( NullyEmptySB,  NullyFilled, spaceMatters: false));
        NoNullRet("",         SpaceSB      .Coalesce( NullySpaceSB,  Null,        spaceMatters: false));
        NoNullRet("",         SpaceSB      .Coalesce( NullySpaceSB,  Empty,       spaceMatters: false));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullySpaceSB,  Space,       spaceMatters: false));
        NoNullRet(Text,       SpaceSB      .Coalesce( NullySpaceSB,  Text,        spaceMatters: false));
        NoNullRet("",         SpaceSB      .Coalesce( NullySpaceSB,  NullyEmpty,  spaceMatters: false));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullySpaceSB,  NullySpace,  spaceMatters: false));
        NoNullRet(Text,       SpaceSB      .Coalesce( NullySpaceSB,  NullyFilled, spaceMatters: false));
        NoNullRet("FilledSB", SpaceSB      .Coalesce( NullyFilledSB, Null,        spaceMatters: false));
        NoNullRet("FilledSB", SpaceSB      .Coalesce( NullyFilledSB, Empty,       spaceMatters: false));
        NoNullRet("FilledSB", SpaceSB      .Coalesce( NullyFilledSB, Space,       spaceMatters: false));
        NoNullRet("FilledSB", SpaceSB      .Coalesce( NullyFilledSB, Text,        spaceMatters: false));
        NoNullRet("FilledSB", SpaceSB      .Coalesce( NullyFilledSB, NullyEmpty,  spaceMatters: false));
        NoNullRet("FilledSB", SpaceSB      .Coalesce( NullyFilledSB, NullySpace,  spaceMatters: false));
        NoNullRet("FilledSB", SpaceSB      .Coalesce( NullyFilledSB, NullyFilled, spaceMatters: false));
        NoNullRet("",         SpaceSB      .Coalesce( EmptySB,       Null,        spaceMatters: false));
        NoNullRet("",         SpaceSB      .Coalesce( EmptySB,       Empty,       spaceMatters: false));
        NoNullRet(" ",        SpaceSB      .Coalesce( EmptySB,       Space,       spaceMatters: false));
        NoNullRet(Text,       SpaceSB      .Coalesce( EmptySB,       Text,        spaceMatters: false));
        NoNullRet("",         SpaceSB      .Coalesce( EmptySB,       NullyEmpty,  spaceMatters: false));
        NoNullRet(" ",        SpaceSB      .Coalesce( EmptySB,       NullySpace,  spaceMatters: false));
        NoNullRet(Text,       SpaceSB      .Coalesce( EmptySB,       NullyFilled, spaceMatters: false));
        NoNullRet("",         SpaceSB      .Coalesce( SpaceSB,       Null,        spaceMatters: false));
        NoNullRet("",         SpaceSB      .Coalesce( SpaceSB,       Empty,       spaceMatters: false));
        NoNullRet(" ",        SpaceSB      .Coalesce( SpaceSB,       Space,       spaceMatters: false));
        NoNullRet(Text,       SpaceSB      .Coalesce( SpaceSB,       Text,        spaceMatters: false));
        NoNullRet("",         SpaceSB      .Coalesce( SpaceSB,       NullyEmpty,  spaceMatters: false));
        NoNullRet(" ",        SpaceSB      .Coalesce( SpaceSB,       NullySpace,  spaceMatters: false));
        NoNullRet(Text,       SpaceSB      .Coalesce( SpaceSB,       NullyFilled, spaceMatters: false));
        NoNullRet("FilledSB", SpaceSB      .Coalesce( FilledSB,      Null,        spaceMatters: false));
        NoNullRet("FilledSB", SpaceSB      .Coalesce( FilledSB,      Empty,       spaceMatters: false));
        NoNullRet("FilledSB", SpaceSB      .Coalesce( FilledSB,      Space,       spaceMatters: false));
        NoNullRet("FilledSB", SpaceSB      .Coalesce( FilledSB,      Text,        spaceMatters: false));
        NoNullRet("FilledSB", SpaceSB      .Coalesce( FilledSB,      NullyEmpty,  spaceMatters: false));
        NoNullRet("FilledSB", SpaceSB      .Coalesce( FilledSB,      NullySpace,  spaceMatters: false));
        NoNullRet("FilledSB", SpaceSB      .Coalesce( FilledSB,      NullyFilled, spaceMatters: false));
                                                      
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullSB,        Null,        spaceMatters: false));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullSB,        Empty,       spaceMatters: false));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullSB,        Space,       spaceMatters: false));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullSB,        Text,        spaceMatters: false));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullSB,        NullyEmpty,  spaceMatters: false));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullSB,        NullySpace,  spaceMatters: false));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullSB,        NullyFilled, spaceMatters: false));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyEmptySB,  Null,        spaceMatters: false));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyEmptySB,  Empty,       spaceMatters: false));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyEmptySB,  Space,       spaceMatters: false));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyEmptySB,  Text,        spaceMatters: false));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyEmptySB,  NullyEmpty,  spaceMatters: false));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyEmptySB,  NullySpace,  spaceMatters: false));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyEmptySB,  NullyFilled, spaceMatters: false));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullySpaceSB,  Null,        spaceMatters: false));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullySpaceSB,  Empty,       spaceMatters: false));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullySpaceSB,  Space,       spaceMatters: false));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullySpaceSB,  Text,        spaceMatters: false));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullySpaceSB,  NullyEmpty,  spaceMatters: false));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullySpaceSB,  NullySpace,  spaceMatters: false));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullySpaceSB,  NullyFilled, spaceMatters: false));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyFilledSB, Null,        spaceMatters: false));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyFilledSB, Empty,       spaceMatters: false));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyFilledSB, Space,       spaceMatters: false));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyFilledSB, Text,        spaceMatters: false));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyFilledSB, NullyEmpty,  spaceMatters: false));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyFilledSB, NullySpace,  spaceMatters: false));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyFilledSB, NullyFilled, spaceMatters: false));
        NoNullRet("FilledSB", FilledSB     .Coalesce( EmptySB,       Null,        spaceMatters: false));
        NoNullRet("FilledSB", FilledSB     .Coalesce( EmptySB,       Empty,       spaceMatters: false));
        NoNullRet("FilledSB", FilledSB     .Coalesce( EmptySB,       Space,       spaceMatters: false));
        NoNullRet("FilledSB", FilledSB     .Coalesce( EmptySB,       Text,        spaceMatters: false));
        NoNullRet("FilledSB", FilledSB     .Coalesce( EmptySB,       NullyEmpty,  spaceMatters: false));
        NoNullRet("FilledSB", FilledSB     .Coalesce( EmptySB,       NullySpace,  spaceMatters: false));
        NoNullRet("FilledSB", FilledSB     .Coalesce( EmptySB,       NullyFilled, spaceMatters: false));
        NoNullRet("FilledSB", FilledSB     .Coalesce( SpaceSB,       Null,        spaceMatters: false));
        NoNullRet("FilledSB", FilledSB     .Coalesce( SpaceSB,       Empty,       spaceMatters: false));
        NoNullRet("FilledSB", FilledSB     .Coalesce( SpaceSB,       Space,       spaceMatters: false));
        NoNullRet("FilledSB", FilledSB     .Coalesce( SpaceSB,       Text,        spaceMatters: false));
        NoNullRet("FilledSB", FilledSB     .Coalesce( SpaceSB,       NullyEmpty,  spaceMatters: false));
        NoNullRet("FilledSB", FilledSB     .Coalesce( SpaceSB,       NullySpace,  spaceMatters: false));
        NoNullRet("FilledSB", FilledSB     .Coalesce( SpaceSB,       NullyFilled, spaceMatters: false));
        NoNullRet("FilledSB", FilledSB     .Coalesce( FilledSB,      Null,        spaceMatters: false));
        NoNullRet("FilledSB", FilledSB     .Coalesce( FilledSB,      Empty,       spaceMatters: false));
        NoNullRet("FilledSB", FilledSB     .Coalesce( FilledSB,      Space,       spaceMatters: false));
        NoNullRet("FilledSB", FilledSB     .Coalesce( FilledSB,      Text,        spaceMatters: false));
        NoNullRet("FilledSB", FilledSB     .Coalesce( FilledSB,      NullyEmpty,  spaceMatters: false));
        NoNullRet("FilledSB", FilledSB     .Coalesce( FilledSB,      NullySpace,  spaceMatters: false));
        NoNullRet("FilledSB", FilledSB     .Coalesce( FilledSB,      NullyFilled, spaceMatters: false));
    }
}