namespace JJ.Framework.Existence.Core.Tests;

[TestClass]
public class Coalesce_3Args_Text_Extensions : TestBase
{
    const string? Null = NullText;
    const string? NullyFilled = NullyFilledText;

    [TestMethod]
    public void Coalesce_3Args_Text_ExtensionsSpaceMattersNo()
    {
        AreEqual("Hi!", " ".Coalesce(null, "Hi!"));

        NoNullRet(Empty, Null       .Coalesce(Null,        Null       ));
        NoNullRet(Empty, Null       .Coalesce(Null,        NullyEmpty ));
        NoNullRet(Space, Null       .Coalesce(Null,        NullySpace ));
        NoNullRet(Text,  Null       .Coalesce(Null,        NullyFilled));
        NoNullRet(Empty, Null       .Coalesce(Null,        Empty      ));
        NoNullRet(Space, Null       .Coalesce(Null,        Space      ));
        NoNullRet(Text,  Null       .Coalesce(Null,        Text       ));
        NoNullRet(Empty, Null       .Coalesce(NullyEmpty,  Null       ));
        NoNullRet(Empty, Null       .Coalesce(NullyEmpty,  NullyEmpty ));
        NoNullRet(Space, Null       .Coalesce(NullyEmpty,  NullySpace ));
        NoNullRet(Text,  Null       .Coalesce(NullyEmpty,  NullyFilled));
        NoNullRet(Empty, Null       .Coalesce(NullyEmpty,  Empty      ));
        NoNullRet(Space, Null       .Coalesce(NullyEmpty,  Space      ));
        NoNullRet(Text,  Null       .Coalesce(NullyEmpty,  Text       ));
        NoNullRet(Empty, Null       .Coalesce(NullySpace,  Null       ));
        NoNullRet(Empty, Null       .Coalesce(NullySpace,  NullyEmpty ));
        NoNullRet(Space, Null       .Coalesce(NullySpace,  NullySpace ));
        NoNullRet(Text,  Null       .Coalesce(NullySpace,  NullyFilled));
        NoNullRet(Empty, Null       .Coalesce(NullySpace,  Empty      ));
        NoNullRet(Space, Null       .Coalesce(NullySpace,  Space      ));
        NoNullRet(Text,  Null       .Coalesce(NullySpace,  Text       ));
        NoNullRet(Text,  Null       .Coalesce(NullyFilled, Null       ));
        NoNullRet(Text,  Null       .Coalesce(NullyFilled, NullyEmpty ));
        NoNullRet(Text,  Null       .Coalesce(NullyFilled, NullySpace ));
        NoNullRet(Text,  Null       .Coalesce(NullyFilled, NullyFilled));
        NoNullRet(Text,  Null       .Coalesce(NullyFilled, Empty      ));
        NoNullRet(Text,  Null       .Coalesce(NullyFilled, Space      ));
        NoNullRet(Text,  Null       .Coalesce(NullyFilled, Text       ));
        NoNullRet(Empty, Null       .Coalesce(Empty,       Null       ));
        NoNullRet(Empty, Null       .Coalesce(Empty,       NullyEmpty ));
        NoNullRet(Space, Null       .Coalesce(Empty,       NullySpace ));
        NoNullRet(Text,  Null       .Coalesce(Empty,       NullyFilled));
        NoNullRet(Empty, Null       .Coalesce(Empty,       Empty      ));
        NoNullRet(Space, Null       .Coalesce(Empty,       Space      ));
        NoNullRet(Text,  Null       .Coalesce(Empty,       Text       ));
        NoNullRet(Empty, Null       .Coalesce(Space,       Null       ));
        NoNullRet(Empty, Null       .Coalesce(Space,       NullyEmpty ));
        NoNullRet(Space, Null       .Coalesce(Space,       NullySpace ));
        NoNullRet(Text,  Null       .Coalesce(Space,       NullyFilled));
        NoNullRet(Empty, Null       .Coalesce(Space,       Empty      ));
        NoNullRet(Space, Null       .Coalesce(Space,       Space      ));
        NoNullRet(Text,  Null       .Coalesce(Space,       Text       ));
        NoNullRet(Text,  Null       .Coalesce(Text,        Null       ));
        NoNullRet(Text,  Null       .Coalesce(Text,        NullyEmpty ));
        NoNullRet(Text,  Null       .Coalesce(Text,        NullySpace ));
        NoNullRet(Text,  Null       .Coalesce(Text,        NullyFilled));
        NoNullRet(Text,  Null       .Coalesce(Text,        Empty      ));
        NoNullRet(Text,  Null       .Coalesce(Text,        Space      ));
        NoNullRet(Text,  Null       .Coalesce(Text,        Text       ));
        
        NoNullRet(Empty, NullyEmpty .Coalesce(Null,        Null       ));
        NoNullRet(Empty, NullyEmpty .Coalesce(Null,        NullyEmpty ));
        NoNullRet(Space, NullyEmpty .Coalesce(Null,        NullySpace ));
        NoNullRet(Text,  NullyEmpty .Coalesce(Null,        NullyFilled));
        NoNullRet(Empty, NullyEmpty .Coalesce(Null,        Empty      ));
        NoNullRet(Space, NullyEmpty .Coalesce(Null,        Space      ));
        NoNullRet(Text,  NullyEmpty .Coalesce(Null,        Text       ));
        NoNullRet(Empty, NullyEmpty .Coalesce(NullyEmpty,  Null       ));
        NoNullRet(Empty, NullyEmpty .Coalesce(NullyEmpty,  NullyEmpty ));
        NoNullRet(Space, NullyEmpty .Coalesce(NullyEmpty,  NullySpace ));
        NoNullRet(Text,  NullyEmpty .Coalesce(NullyEmpty,  NullyFilled));
        NoNullRet(Empty, NullyEmpty .Coalesce(NullyEmpty,  Empty      ));
        NoNullRet(Space, NullyEmpty .Coalesce(NullyEmpty,  Space      ));
        NoNullRet(Text,  NullyEmpty .Coalesce(NullyEmpty,  Text       ));
        NoNullRet(Empty, NullyEmpty .Coalesce(NullySpace,  Null       ));
        NoNullRet(Empty, NullyEmpty .Coalesce(NullySpace,  NullyEmpty ));
        NoNullRet(Space, NullyEmpty .Coalesce(NullySpace,  NullySpace ));
        NoNullRet(Text,  NullyEmpty .Coalesce(NullySpace,  NullyFilled));
        NoNullRet(Empty, NullyEmpty .Coalesce(NullySpace,  Empty      ));
        NoNullRet(Space, NullyEmpty .Coalesce(NullySpace,  Space      ));
        NoNullRet(Text,  NullyEmpty .Coalesce(NullySpace,  Text       ));
        NoNullRet(Text,  NullyEmpty .Coalesce(NullyFilled, Null       ));
        NoNullRet(Text,  NullyEmpty .Coalesce(NullyFilled, NullyEmpty ));
        NoNullRet(Text,  NullyEmpty .Coalesce(NullyFilled, NullySpace ));
        NoNullRet(Text,  NullyEmpty .Coalesce(NullyFilled, NullyFilled));
        NoNullRet(Text,  NullyEmpty .Coalesce(NullyFilled, Empty      ));
        NoNullRet(Text,  NullyEmpty .Coalesce(NullyFilled, Space      ));
        NoNullRet(Text,  NullyEmpty .Coalesce(NullyFilled, Text       ));
        NoNullRet(Empty, NullyEmpty .Coalesce(Empty,       Null       ));
        NoNullRet(Empty, NullyEmpty .Coalesce(Empty,       NullyEmpty ));
        NoNullRet(Space, NullyEmpty .Coalesce(Empty,       NullySpace ));
        NoNullRet(Text,  NullyEmpty .Coalesce(Empty,       NullyFilled));
        NoNullRet(Empty, NullyEmpty .Coalesce(Empty,       Empty      ));
        NoNullRet(Space, NullyEmpty .Coalesce(Empty,       Space      ));
        NoNullRet(Text,  NullyEmpty .Coalesce(Empty,       Text       ));
        NoNullRet(Empty, NullyEmpty .Coalesce(Space,       Null       ));
        NoNullRet(Empty, NullyEmpty .Coalesce(Space,       NullyEmpty ));
        NoNullRet(Space, NullyEmpty .Coalesce(Space,       NullySpace ));
        NoNullRet(Text,  NullyEmpty .Coalesce(Space,       NullyFilled));
        NoNullRet(Empty, NullyEmpty .Coalesce(Space,       Empty      ));
        NoNullRet(Space, NullyEmpty .Coalesce(Space,       Space      ));
        NoNullRet(Text,  NullyEmpty .Coalesce(Space,       Text       ));
        NoNullRet(Text,  NullyEmpty .Coalesce(Text,        Null       ));
        NoNullRet(Text,  NullyEmpty .Coalesce(Text,        NullyEmpty ));
        NoNullRet(Text,  NullyEmpty .Coalesce(Text,        NullySpace ));
        NoNullRet(Text,  NullyEmpty .Coalesce(Text,        NullyFilled));
        NoNullRet(Text,  NullyEmpty .Coalesce(Text,        Empty      ));
        NoNullRet(Text,  NullyEmpty .Coalesce(Text,        Space      ));
        NoNullRet(Text,  NullyEmpty .Coalesce(Text,        Text       ));

        NoNullRet(Empty, NullySpace .Coalesce(Null,        Null       ));
        NoNullRet(Empty, NullySpace .Coalesce(Null,        NullyEmpty ));
        NoNullRet(Space, NullySpace .Coalesce(Null,        NullySpace ));
        NoNullRet(Text,  NullySpace .Coalesce(Null,        NullyFilled));
        NoNullRet(Empty, NullySpace .Coalesce(Null,        Empty      ));
        NoNullRet(Space, NullySpace .Coalesce(Null,        Space      ));
        NoNullRet(Text,  NullySpace .Coalesce(Null,        Text       ));
        NoNullRet(Empty, NullySpace .Coalesce(NullyEmpty,  Null       ));
        NoNullRet(Empty, NullySpace .Coalesce(NullyEmpty,  NullyEmpty ));
        NoNullRet(Space, NullySpace .Coalesce(NullyEmpty,  NullySpace ));
        NoNullRet(Text,  NullySpace .Coalesce(NullyEmpty,  NullyFilled));
        NoNullRet(Empty, NullySpace .Coalesce(NullyEmpty,  Empty      ));
        NoNullRet(Space, NullySpace .Coalesce(NullyEmpty,  Space      ));
        NoNullRet(Text,  NullySpace .Coalesce(NullyEmpty,  Text       ));
        NoNullRet(Empty, NullySpace .Coalesce(NullySpace,  Null       ));
        NoNullRet(Empty, NullySpace .Coalesce(NullySpace,  NullyEmpty ));
        NoNullRet(Space, NullySpace .Coalesce(NullySpace,  NullySpace ));
        NoNullRet(Text,  NullySpace .Coalesce(NullySpace,  NullyFilled));
        NoNullRet(Empty, NullySpace .Coalesce(NullySpace,  Empty      ));
        NoNullRet(Space, NullySpace .Coalesce(NullySpace,  Space      ));
        NoNullRet(Text,  NullySpace .Coalesce(NullySpace,  Text       ));
        NoNullRet(Text,  NullySpace .Coalesce(NullyFilled, Null       ));
        NoNullRet(Text,  NullySpace .Coalesce(NullyFilled, NullyEmpty ));
        NoNullRet(Text,  NullySpace .Coalesce(NullyFilled, NullySpace ));
        NoNullRet(Text,  NullySpace .Coalesce(NullyFilled, NullyFilled));
        NoNullRet(Text,  NullySpace .Coalesce(NullyFilled, Empty      ));
        NoNullRet(Text,  NullySpace .Coalesce(NullyFilled, Space      ));
        NoNullRet(Text,  NullySpace .Coalesce(NullyFilled, Text       ));
        NoNullRet(Empty, NullySpace .Coalesce(Empty,       Null       ));
        NoNullRet(Empty, NullySpace .Coalesce(Empty,       NullyEmpty ));
        NoNullRet(Space, NullySpace .Coalesce(Empty,       NullySpace ));
        NoNullRet(Text,  NullySpace .Coalesce(Empty,       NullyFilled));
        NoNullRet(Empty, NullySpace .Coalesce(Empty,       Empty      ));
        NoNullRet(Space, NullySpace .Coalesce(Empty,       Space      ));
        NoNullRet(Text,  NullySpace .Coalesce(Empty,       Text       ));
        NoNullRet(Empty, NullySpace .Coalesce(Space,       Null       ));
        NoNullRet(Empty, NullySpace .Coalesce(Space,       NullyEmpty ));
        NoNullRet(Space, NullySpace .Coalesce(Space,       NullySpace ));
        NoNullRet(Text,  NullySpace .Coalesce(Space,       NullyFilled));
        NoNullRet(Empty, NullySpace .Coalesce(Space,       Empty      ));
        NoNullRet(Space, NullySpace .Coalesce(Space,       Space      ));
        NoNullRet(Text,  NullySpace .Coalesce(Space,       Text       ));
        NoNullRet(Text,  NullySpace .Coalesce(Text,        Null       ));
        NoNullRet(Text,  NullySpace .Coalesce(Text,        NullyEmpty ));
        NoNullRet(Text,  NullySpace .Coalesce(Text,        NullySpace ));
        NoNullRet(Text,  NullySpace .Coalesce(Text,        NullyFilled));
        NoNullRet(Text,  NullySpace .Coalesce(Text,        Empty      ));
        NoNullRet(Text,  NullySpace .Coalesce(Text,        Space      ));
        NoNullRet(Text,  NullySpace .Coalesce(Text,        Text       ));

        NoNullRet(Text,  NullyFilled.Coalesce(Null,        Null       ));
        NoNullRet(Text,  NullyFilled.Coalesce(Null,        NullyEmpty ));
        NoNullRet(Text,  NullyFilled.Coalesce(Null,        NullySpace ));
        NoNullRet(Text,  NullyFilled.Coalesce(Null,        NullyFilled));
        NoNullRet(Text,  NullyFilled.Coalesce(Null,        Empty      ));
        NoNullRet(Text,  NullyFilled.Coalesce(Null,        Space      ));
        NoNullRet(Text,  NullyFilled.Coalesce(Null,        Text       ));
        NoNullRet(Text,  NullyFilled.Coalesce(NullyEmpty,  Null       ));
        NoNullRet(Text,  NullyFilled.Coalesce(NullyEmpty,  NullyEmpty ));
        NoNullRet(Text,  NullyFilled.Coalesce(NullyEmpty,  NullySpace ));
        NoNullRet(Text,  NullyFilled.Coalesce(NullyEmpty,  NullyFilled));
        NoNullRet(Text,  NullyFilled.Coalesce(NullyEmpty,  Empty      ));
        NoNullRet(Text,  NullyFilled.Coalesce(NullyEmpty,  Space      ));
        NoNullRet(Text,  NullyFilled.Coalesce(NullyEmpty,  Text       ));
        NoNullRet(Text,  NullyFilled.Coalesce(NullySpace,  Null       ));
        NoNullRet(Text,  NullyFilled.Coalesce(NullySpace,  NullyEmpty ));
        NoNullRet(Text,  NullyFilled.Coalesce(NullySpace,  NullySpace ));
        NoNullRet(Text,  NullyFilled.Coalesce(NullySpace,  NullyFilled));
        NoNullRet(Text,  NullyFilled.Coalesce(NullySpace,  Empty      ));
        NoNullRet(Text,  NullyFilled.Coalesce(NullySpace,  Space      ));
        NoNullRet(Text,  NullyFilled.Coalesce(NullySpace,  Text       ));
        NoNullRet(Text,  NullyFilled.Coalesce(NullyFilled, Null       ));
        NoNullRet(Text,  NullyFilled.Coalesce(NullyFilled, NullyEmpty ));
        NoNullRet(Text,  NullyFilled.Coalesce(NullyFilled, NullySpace ));
        NoNullRet(Text,  NullyFilled.Coalesce(NullyFilled, NullyFilled));
        NoNullRet(Text,  NullyFilled.Coalesce(NullyFilled, Empty      ));
        NoNullRet(Text,  NullyFilled.Coalesce(NullyFilled, Space      ));
        NoNullRet(Text,  NullyFilled.Coalesce(NullyFilled, Text       ));
        NoNullRet(Text,  NullyFilled.Coalesce(Empty,       Null       ));
        NoNullRet(Text,  NullyFilled.Coalesce(Empty,       NullyEmpty ));
        NoNullRet(Text,  NullyFilled.Coalesce(Empty,       NullySpace ));
        NoNullRet(Text,  NullyFilled.Coalesce(Empty,       NullyFilled));
        NoNullRet(Text,  NullyFilled.Coalesce(Empty,       Empty      ));
        NoNullRet(Text,  NullyFilled.Coalesce(Empty,       Space      ));
        NoNullRet(Text,  NullyFilled.Coalesce(Empty,       Text       ));
        NoNullRet(Text,  NullyFilled.Coalesce(Space,       Null       ));
        NoNullRet(Text,  NullyFilled.Coalesce(Space,       NullyEmpty ));
        NoNullRet(Text,  NullyFilled.Coalesce(Space,       NullySpace ));
        NoNullRet(Text,  NullyFilled.Coalesce(Space,       NullyFilled));
        NoNullRet(Text,  NullyFilled.Coalesce(Space,       Empty      ));
        NoNullRet(Text,  NullyFilled.Coalesce(Space,       Space      ));
        NoNullRet(Text,  NullyFilled.Coalesce(Space,       Text       ));
        NoNullRet(Text,  NullyFilled.Coalesce(Text,        Null       ));
        NoNullRet(Text,  NullyFilled.Coalesce(Text,        NullyEmpty ));
        NoNullRet(Text,  NullyFilled.Coalesce(Text,        NullySpace ));
        NoNullRet(Text,  NullyFilled.Coalesce(Text,        NullyFilled));
        NoNullRet(Text,  NullyFilled.Coalesce(Text,        Empty      ));
        NoNullRet(Text,  NullyFilled.Coalesce(Text,        Space      ));
        NoNullRet(Text,  NullyFilled.Coalesce(Text,        Text       ));

        NoNullRet(Empty, Empty      .Coalesce(Null,        Null       ));
        NoNullRet(Empty, Empty      .Coalesce(Null,        NullyEmpty ));
        NoNullRet(Space, Empty      .Coalesce(Null,        NullySpace ));
        NoNullRet(Text,  Empty      .Coalesce(Null,        NullyFilled));
        NoNullRet(Empty, Empty      .Coalesce(Null,        Empty      ));
        NoNullRet(Space, Empty      .Coalesce(Null,        Space      ));
        NoNullRet(Text,  Empty      .Coalesce(Null,        Text       ));
        NoNullRet(Empty, Empty      .Coalesce(NullyEmpty,  Null       ));
        NoNullRet(Empty, Empty      .Coalesce(NullyEmpty,  NullyEmpty ));
        NoNullRet(Space, Empty      .Coalesce(NullyEmpty,  NullySpace ));
        NoNullRet(Text,  Empty      .Coalesce(NullyEmpty,  NullyFilled));
        NoNullRet(Empty, Empty      .Coalesce(NullyEmpty,  Empty      ));
        NoNullRet(Space, Empty      .Coalesce(NullyEmpty,  Space      ));
        NoNullRet(Text,  Empty      .Coalesce(NullyEmpty,  Text       ));
        NoNullRet(Empty, Empty      .Coalesce(NullySpace,  Null       ));
        NoNullRet(Empty, Empty      .Coalesce(NullySpace,  NullyEmpty ));
        NoNullRet(Space, Empty      .Coalesce(NullySpace,  NullySpace ));
        NoNullRet(Text,  Empty      .Coalesce(NullySpace,  NullyFilled));
        NoNullRet(Empty, Empty      .Coalesce(NullySpace,  Empty      ));
        NoNullRet(Space, Empty      .Coalesce(NullySpace,  Space      ));
        NoNullRet(Text,  Empty      .Coalesce(NullySpace,  Text       ));
        NoNullRet(Text,  Empty      .Coalesce(NullyFilled, Null       ));
        NoNullRet(Text,  Empty      .Coalesce(NullyFilled, NullyEmpty ));
        NoNullRet(Text,  Empty      .Coalesce(NullyFilled, NullySpace ));
        NoNullRet(Text,  Empty      .Coalesce(NullyFilled, NullyFilled));
        NoNullRet(Text,  Empty      .Coalesce(NullyFilled, Empty      ));
        NoNullRet(Text,  Empty      .Coalesce(NullyFilled, Space      ));
        NoNullRet(Text,  Empty      .Coalesce(NullyFilled, Text       ));
        NoNullRet(Empty, Empty      .Coalesce(Empty,       Null       ));
        NoNullRet(Empty, Empty      .Coalesce(Empty,       NullyEmpty ));
        NoNullRet(Space, Empty      .Coalesce(Empty,       NullySpace ));
        NoNullRet(Text,  Empty      .Coalesce(Empty,       NullyFilled));
        NoNullRet(Empty, Empty      .Coalesce(Empty,       Empty      ));
        NoNullRet(Space, Empty      .Coalesce(Empty,       Space      ));
        NoNullRet(Text,  Empty      .Coalesce(Empty,       Text       ));
        NoNullRet(Empty, Empty      .Coalesce(Space,       Null       ));
        NoNullRet(Empty, Empty      .Coalesce(Space,       NullyEmpty ));
        NoNullRet(Space, Empty      .Coalesce(Space,       NullySpace ));
        NoNullRet(Text,  Empty      .Coalesce(Space,       NullyFilled));
        NoNullRet(Empty, Empty      .Coalesce(Space,       Empty      ));
        NoNullRet(Space, Empty      .Coalesce(Space,       Space      ));
        NoNullRet(Text,  Empty      .Coalesce(Space,       Text       ));
        NoNullRet(Text,  Empty      .Coalesce(Text,        Null       ));
        NoNullRet(Text,  Empty      .Coalesce(Text,        NullyEmpty ));
        NoNullRet(Text,  Empty      .Coalesce(Text,        NullySpace ));
        NoNullRet(Text,  Empty      .Coalesce(Text,        NullyFilled));
        NoNullRet(Text,  Empty      .Coalesce(Text,        Empty      ));
        NoNullRet(Text,  Empty      .Coalesce(Text,        Space      ));
        NoNullRet(Text,  Empty      .Coalesce(Text,        Text       ));
                                             
        NoNullRet(Empty, Space      .Coalesce(Null,        Null       ));
        NoNullRet(Empty, Space      .Coalesce(Null,        NullyEmpty ));
        NoNullRet(Space, Space      .Coalesce(Null,        NullySpace ));
        NoNullRet(Text,  Space      .Coalesce(Null,        NullyFilled));
        NoNullRet(Empty, Space      .Coalesce(Null,        Empty      ));
        NoNullRet(Space, Space      .Coalesce(Null,        Space      ));
        NoNullRet(Text,  Space      .Coalesce(Null,        Text       ));
        NoNullRet(Empty, Space      .Coalesce(NullyEmpty,  Null       ));
        NoNullRet(Empty, Space      .Coalesce(NullyEmpty,  NullyEmpty ));
        NoNullRet(Space, Space      .Coalesce(NullyEmpty,  NullySpace ));
        NoNullRet(Text,  Space      .Coalesce(NullyEmpty,  NullyFilled));
        NoNullRet(Empty, Space      .Coalesce(NullyEmpty,  Empty      ));
        NoNullRet(Space, Space      .Coalesce(NullyEmpty,  Space      ));
        NoNullRet(Text,  Space      .Coalesce(NullyEmpty,  Text       ));
        NoNullRet(Empty, Space      .Coalesce(NullySpace,  Null       ));
        NoNullRet(Empty, Space      .Coalesce(NullySpace,  NullyEmpty ));
        NoNullRet(Space, Space      .Coalesce(NullySpace,  NullySpace ));
        NoNullRet(Text,  Space      .Coalesce(NullySpace,  NullyFilled));
        NoNullRet(Empty, Space      .Coalesce(NullySpace,  Empty      ));
        NoNullRet(Space, Space      .Coalesce(NullySpace,  Space      ));
        NoNullRet(Text,  Space      .Coalesce(NullySpace,  Text       ));
        NoNullRet(Text,  Space      .Coalesce(NullyFilled, Null       ));
        NoNullRet(Text,  Space      .Coalesce(NullyFilled, NullyEmpty ));
        NoNullRet(Text,  Space      .Coalesce(NullyFilled, NullySpace ));
        NoNullRet(Text,  Space      .Coalesce(NullyFilled, NullyFilled));
        NoNullRet(Text,  Space      .Coalesce(NullyFilled, Empty      ));
        NoNullRet(Text,  Space      .Coalesce(NullyFilled, Space      ));
        NoNullRet(Text,  Space      .Coalesce(NullyFilled, Text       ));
        NoNullRet(Empty, Space      .Coalesce(Empty,       Null       ));
        NoNullRet(Empty, Space      .Coalesce(Empty,       NullyEmpty ));
        NoNullRet(Space, Space      .Coalesce(Empty,       NullySpace ));
        NoNullRet(Text,  Space      .Coalesce(Empty,       NullyFilled));
        NoNullRet(Empty, Space      .Coalesce(Empty,       Empty      ));
        NoNullRet(Space, Space      .Coalesce(Empty,       Space      ));
        NoNullRet(Text,  Space      .Coalesce(Empty,       Text       ));
        NoNullRet(Empty, Space      .Coalesce(Space,       Null       ));
        NoNullRet(Empty, Space      .Coalesce(Space,       NullyEmpty ));
        NoNullRet(Space, Space      .Coalesce(Space,       NullySpace ));
        NoNullRet(Text,  Space      .Coalesce(Space,       NullyFilled));
        NoNullRet(Empty, Space      .Coalesce(Space,       Empty      ));
        NoNullRet(Space, Space      .Coalesce(Space,       Space      ));
        NoNullRet(Text,  Space      .Coalesce(Space,       Text       ));
        NoNullRet(Text,  Space      .Coalesce(Text,        Null       ));
        NoNullRet(Text,  Space      .Coalesce(Text,        NullyEmpty ));
        NoNullRet(Text,  Space      .Coalesce(Text,        NullySpace ));
        NoNullRet(Text,  Space      .Coalesce(Text,        NullyFilled));
        NoNullRet(Text,  Space      .Coalesce(Text,        Empty      ));
        NoNullRet(Text,  Space      .Coalesce(Text,        Space      ));
        NoNullRet(Text,  Space      .Coalesce(Text,        Text       ));
                                             
        NoNullRet(Text,  Text       .Coalesce(Null,        Null       ));
        NoNullRet(Text,  Text       .Coalesce(Null,        NullyEmpty ));
        NoNullRet(Text,  Text       .Coalesce(Null,        NullySpace ));
        NoNullRet(Text,  Text       .Coalesce(Null,        NullyFilled));
        NoNullRet(Text,  Text       .Coalesce(Null,        Empty      ));
        NoNullRet(Text,  Text       .Coalesce(Null,        Space      ));
        NoNullRet(Text,  Text       .Coalesce(Null,        Text       ));
        NoNullRet(Text,  Text       .Coalesce(NullyEmpty,  Null       ));
        NoNullRet(Text,  Text       .Coalesce(NullyEmpty,  NullyEmpty ));
        NoNullRet(Text,  Text       .Coalesce(NullyEmpty,  NullySpace ));
        NoNullRet(Text,  Text       .Coalesce(NullyEmpty,  NullyFilled));
        NoNullRet(Text,  Text       .Coalesce(NullyEmpty,  Empty      ));
        NoNullRet(Text,  Text       .Coalesce(NullyEmpty,  Space      ));
        NoNullRet(Text,  Text       .Coalesce(NullyEmpty,  Text       ));
        NoNullRet(Text,  Text       .Coalesce(NullySpace,  Null       ));
        NoNullRet(Text,  Text       .Coalesce(NullySpace,  NullyEmpty ));
        NoNullRet(Text,  Text       .Coalesce(NullySpace,  NullySpace ));
        NoNullRet(Text,  Text       .Coalesce(NullySpace,  NullyFilled));
        NoNullRet(Text,  Text       .Coalesce(NullySpace,  Empty      ));
        NoNullRet(Text,  Text       .Coalesce(NullySpace,  Space      ));
        NoNullRet(Text,  Text       .Coalesce(NullySpace,  Text       ));
        NoNullRet(Text,  Text       .Coalesce(NullyFilled, Null       ));
        NoNullRet(Text,  Text       .Coalesce(NullyFilled, NullyEmpty ));
        NoNullRet(Text,  Text       .Coalesce(NullyFilled, NullySpace ));
        NoNullRet(Text,  Text       .Coalesce(NullyFilled, NullyFilled));
        NoNullRet(Text,  Text       .Coalesce(NullyFilled, Empty      ));
        NoNullRet(Text,  Text       .Coalesce(NullyFilled, Space      ));
        NoNullRet(Text,  Text       .Coalesce(NullyFilled, Text       ));
        NoNullRet(Text,  Text       .Coalesce(Empty,       Null       ));
        NoNullRet(Text,  Text       .Coalesce(Empty,       NullyEmpty ));
        NoNullRet(Text,  Text       .Coalesce(Empty,       NullySpace ));
        NoNullRet(Text,  Text       .Coalesce(Empty,       NullyFilled));
        NoNullRet(Text,  Text       .Coalesce(Empty,       Empty      ));
        NoNullRet(Text,  Text       .Coalesce(Empty,       Space      ));
        NoNullRet(Text,  Text       .Coalesce(Empty,       Text       ));
        NoNullRet(Text,  Text       .Coalesce(Space,       Null       ));
        NoNullRet(Text,  Text       .Coalesce(Space,       NullyEmpty ));
        NoNullRet(Text,  Text       .Coalesce(Space,       NullySpace ));
        NoNullRet(Text,  Text       .Coalesce(Space,       NullyFilled));
        NoNullRet(Text,  Text       .Coalesce(Space,       Empty      ));
        NoNullRet(Text,  Text       .Coalesce(Space,       Space      ));
        NoNullRet(Text,  Text       .Coalesce(Space,       Text       ));
        NoNullRet(Text,  Text       .Coalesce(Text,        Null       ));
        NoNullRet(Text,  Text       .Coalesce(Text,        NullyEmpty ));
        NoNullRet(Text,  Text       .Coalesce(Text,        NullySpace ));
        NoNullRet(Text,  Text       .Coalesce(Text,        NullyFilled));
        NoNullRet(Text,  Text       .Coalesce(Text,        Empty      ));
        NoNullRet(Text,  Text       .Coalesce(Text,        Space      ));
        NoNullRet(Text,  Text       .Coalesce(Text,        Text       ));
    }
    
    [TestMethod]
    public void Coalesce_3Args_Text_ExtensionsSpaceMattersYes_MagicBool()
    {
        AreEqual(" ",   " ".Coalesce(null, "Hi!", spaceMatters: true));

        NoNullRet(Empty, Null       .Coalesce(Null,        Null,        spaceMatters));
        NoNullRet(Empty, Null       .Coalesce(Null,        NullyEmpty,  spaceMatters));
        NoNullRet(Space, Null       .Coalesce(Null,        NullySpace,  spaceMatters));
        NoNullRet(Text,  Null       .Coalesce(Null,        NullyFilled, spaceMatters));
        NoNullRet(Empty, Null       .Coalesce(Null,        Empty,       spaceMatters));
        NoNullRet(Space, Null       .Coalesce(Null,        Space,       spaceMatters));
        NoNullRet(Text,  Null       .Coalesce(Null,        Text,        spaceMatters));
        NoNullRet(Empty, Null       .Coalesce(NullyEmpty,  Null,        spaceMatters));
        NoNullRet(Empty, Null       .Coalesce(NullyEmpty,  NullyEmpty,  spaceMatters));
        NoNullRet(Space, Null       .Coalesce(NullyEmpty,  NullySpace,  spaceMatters));
        NoNullRet(Text,  Null       .Coalesce(NullyEmpty,  NullyFilled, spaceMatters));
        NoNullRet(Empty, Null       .Coalesce(NullyEmpty,  Empty,       spaceMatters));
        NoNullRet(Space, Null       .Coalesce(NullyEmpty,  Space,       spaceMatters));
        NoNullRet(Text,  Null       .Coalesce(NullyEmpty,  Text,        spaceMatters));
        NoNullRet(Space, Null       .Coalesce(NullySpace,  Null,        spaceMatters));
        NoNullRet(Space, Null       .Coalesce(NullySpace,  NullyEmpty,  spaceMatters));
        NoNullRet(Space, Null       .Coalesce(NullySpace,  NullySpace,  spaceMatters));
        NoNullRet(Space, Null       .Coalesce(NullySpace,  NullyFilled, spaceMatters));
        NoNullRet(Space, Null       .Coalesce(NullySpace,  Empty,       spaceMatters));
        NoNullRet(Space, Null       .Coalesce(NullySpace,  Space,       spaceMatters));
        NoNullRet(Space, Null       .Coalesce(NullySpace,  Text,        spaceMatters));
        NoNullRet(Text,  Null       .Coalesce(NullyFilled, Null,        spaceMatters));
        NoNullRet(Text,  Null       .Coalesce(NullyFilled, NullyEmpty,  spaceMatters));
        NoNullRet(Text,  Null       .Coalesce(NullyFilled, NullySpace,  spaceMatters));
        NoNullRet(Text,  Null       .Coalesce(NullyFilled, NullyFilled, spaceMatters));
        NoNullRet(Text,  Null       .Coalesce(NullyFilled, Empty,       spaceMatters));
        NoNullRet(Text,  Null       .Coalesce(NullyFilled, Space,       spaceMatters));
        NoNullRet(Text,  Null       .Coalesce(NullyFilled, Text,        spaceMatters));
        NoNullRet(Empty, Null       .Coalesce(Empty,       Null,        spaceMatters));
        NoNullRet(Empty, Null       .Coalesce(Empty,       NullyEmpty,  spaceMatters));
        NoNullRet(Space, Null       .Coalesce(Empty,       NullySpace,  spaceMatters));
        NoNullRet(Text,  Null       .Coalesce(Empty,       NullyFilled, spaceMatters));
        NoNullRet(Empty, Null       .Coalesce(Empty,       Empty,       spaceMatters));
        NoNullRet(Space, Null       .Coalesce(Empty,       Space,       spaceMatters));
        NoNullRet(Text,  Null       .Coalesce(Empty,       Text,        spaceMatters));
        NoNullRet(Space, Null       .Coalesce(Space,       Null,        spaceMatters));
        NoNullRet(Space, Null       .Coalesce(Space,       NullyEmpty,  spaceMatters));
        NoNullRet(Space, Null       .Coalesce(Space,       NullySpace,  spaceMatters));
        NoNullRet(Space, Null       .Coalesce(Space,       NullyFilled, spaceMatters));
        NoNullRet(Space, Null       .Coalesce(Space,       Empty,       spaceMatters));
        NoNullRet(Space, Null       .Coalesce(Space,       Space,       spaceMatters));
        NoNullRet(Space, Null       .Coalesce(Space,       Text,        spaceMatters));
        NoNullRet(Text,  Null       .Coalesce(Text,        Null,        spaceMatters));
        NoNullRet(Text,  Null       .Coalesce(Text,        NullyEmpty,  spaceMatters));
        NoNullRet(Text,  Null       .Coalesce(Text,        NullySpace,  spaceMatters));
        NoNullRet(Text,  Null       .Coalesce(Text,        NullyFilled, spaceMatters));
        NoNullRet(Text,  Null       .Coalesce(Text,        Empty,       spaceMatters));
        NoNullRet(Text,  Null       .Coalesce(Text,        Space,       spaceMatters));
        NoNullRet(Text,  Null       .Coalesce(Text,        Text,        spaceMatters));
        
        NoNullRet(Empty, NullyEmpty .Coalesce(Null,        Null,        spaceMatters));
        NoNullRet(Empty, NullyEmpty .Coalesce(Null,        NullyEmpty,  spaceMatters));
        NoNullRet(Space, NullyEmpty .Coalesce(Null,        NullySpace,  spaceMatters));
        NoNullRet(Text,  NullyEmpty .Coalesce(Null,        NullyFilled, spaceMatters));
        NoNullRet(Empty, NullyEmpty .Coalesce(Null,        Empty,       spaceMatters));
        NoNullRet(Space, NullyEmpty .Coalesce(Null,        Space,       spaceMatters));
        NoNullRet(Text,  NullyEmpty .Coalesce(Null,        Text,        spaceMatters));
        NoNullRet(Empty, NullyEmpty .Coalesce(NullyEmpty,  Null,        spaceMatters));
        NoNullRet(Empty, NullyEmpty .Coalesce(NullyEmpty,  NullyEmpty,  spaceMatters));
        NoNullRet(Space, NullyEmpty .Coalesce(NullyEmpty,  NullySpace,  spaceMatters));
        NoNullRet(Text,  NullyEmpty .Coalesce(NullyEmpty,  NullyFilled, spaceMatters));
        NoNullRet(Empty, NullyEmpty .Coalesce(NullyEmpty,  Empty,       spaceMatters));
        NoNullRet(Space, NullyEmpty .Coalesce(NullyEmpty,  Space,       spaceMatters));
        NoNullRet(Text,  NullyEmpty .Coalesce(NullyEmpty,  Text,        spaceMatters));
        NoNullRet(Space, NullyEmpty .Coalesce(NullySpace,  Null,        spaceMatters));
        NoNullRet(Space, NullyEmpty .Coalesce(NullySpace,  NullyEmpty,  spaceMatters));
        NoNullRet(Space, NullyEmpty .Coalesce(NullySpace,  NullySpace,  spaceMatters));
        NoNullRet(Space, NullyEmpty .Coalesce(NullySpace,  NullyFilled, spaceMatters));
        NoNullRet(Space, NullyEmpty .Coalesce(NullySpace,  Empty,       spaceMatters));
        NoNullRet(Space, NullyEmpty .Coalesce(NullySpace,  Space,       spaceMatters));
        NoNullRet(Space, NullyEmpty .Coalesce(NullySpace,  Text,        spaceMatters));
        NoNullRet(Text,  NullyEmpty .Coalesce(NullyFilled, Null,        spaceMatters));
        NoNullRet(Text,  NullyEmpty .Coalesce(NullyFilled, NullyEmpty,  spaceMatters));
        NoNullRet(Text,  NullyEmpty .Coalesce(NullyFilled, NullySpace,  spaceMatters));
        NoNullRet(Text,  NullyEmpty .Coalesce(NullyFilled, NullyFilled, spaceMatters));
        NoNullRet(Text,  NullyEmpty .Coalesce(NullyFilled, Empty,       spaceMatters));
        NoNullRet(Text,  NullyEmpty .Coalesce(NullyFilled, Space,       spaceMatters));
        NoNullRet(Text,  NullyEmpty .Coalesce(NullyFilled, Text,        spaceMatters));
        NoNullRet(Empty, NullyEmpty .Coalesce(Empty,       Null,        spaceMatters));
        NoNullRet(Empty, NullyEmpty .Coalesce(Empty,       NullyEmpty,  spaceMatters));
        NoNullRet(Space, NullyEmpty .Coalesce(Empty,       NullySpace,  spaceMatters));
        NoNullRet(Text,  NullyEmpty .Coalesce(Empty,       NullyFilled, spaceMatters));
        NoNullRet(Empty, NullyEmpty .Coalesce(Empty,       Empty,       spaceMatters));
        NoNullRet(Space, NullyEmpty .Coalesce(Empty,       Space,       spaceMatters));
        NoNullRet(Text,  NullyEmpty .Coalesce(Empty,       Text,        spaceMatters));
        NoNullRet(Space, NullyEmpty .Coalesce(Space,       Null,        spaceMatters));
        NoNullRet(Space, NullyEmpty .Coalesce(Space,       NullyEmpty,  spaceMatters));
        NoNullRet(Space, NullyEmpty .Coalesce(Space,       NullySpace,  spaceMatters));
        NoNullRet(Space, NullyEmpty .Coalesce(Space,       NullyFilled, spaceMatters));
        NoNullRet(Space, NullyEmpty .Coalesce(Space,       Empty,       spaceMatters));
        NoNullRet(Space, NullyEmpty .Coalesce(Space,       Space,       spaceMatters));
        NoNullRet(Space, NullyEmpty .Coalesce(Space,       Text,        spaceMatters));
        NoNullRet(Text,  NullyEmpty .Coalesce(Text,        Null,        spaceMatters));
        NoNullRet(Text,  NullyEmpty .Coalesce(Text,        NullyEmpty,  spaceMatters));
        NoNullRet(Text,  NullyEmpty .Coalesce(Text,        NullySpace,  spaceMatters));
        NoNullRet(Text,  NullyEmpty .Coalesce(Text,        NullyFilled, spaceMatters));
        NoNullRet(Text,  NullyEmpty .Coalesce(Text,        Empty,       spaceMatters));
        NoNullRet(Text,  NullyEmpty .Coalesce(Text,        Space,       spaceMatters));
        NoNullRet(Text,  NullyEmpty .Coalesce(Text,        Text,        spaceMatters));

        NoNullRet(Space, NullySpace .Coalesce(Null,        Null,        spaceMatters));
        NoNullRet(Space, NullySpace .Coalesce(Null,        NullyEmpty,  spaceMatters));
        NoNullRet(Space, NullySpace .Coalesce(Null,        NullySpace,  spaceMatters));
        NoNullRet(Space, NullySpace .Coalesce(Null,        NullyFilled, spaceMatters));
        NoNullRet(Space, NullySpace .Coalesce(Null,        Empty,       spaceMatters));
        NoNullRet(Space, NullySpace .Coalesce(Null,        Space,       spaceMatters));
        NoNullRet(Space, NullySpace .Coalesce(Null,        Text,        spaceMatters));
        NoNullRet(Space, NullySpace .Coalesce(NullyEmpty,  Null,        spaceMatters));
        NoNullRet(Space, NullySpace .Coalesce(NullyEmpty,  NullyEmpty,  spaceMatters));
        NoNullRet(Space, NullySpace .Coalesce(NullyEmpty,  NullySpace,  spaceMatters));
        NoNullRet(Space, NullySpace .Coalesce(NullyEmpty,  NullyFilled, spaceMatters));
        NoNullRet(Space, NullySpace .Coalesce(NullyEmpty,  Empty,       spaceMatters));
        NoNullRet(Space, NullySpace .Coalesce(NullyEmpty,  Space,       spaceMatters));
        NoNullRet(Space, NullySpace .Coalesce(NullyEmpty,  Text,        spaceMatters));
        NoNullRet(Space, NullySpace .Coalesce(NullySpace,  Null,        spaceMatters));
        NoNullRet(Space, NullySpace .Coalesce(NullySpace,  NullyEmpty,  spaceMatters));
        NoNullRet(Space, NullySpace .Coalesce(NullySpace,  NullySpace,  spaceMatters));
        NoNullRet(Space, NullySpace .Coalesce(NullySpace,  NullyFilled, spaceMatters));
        NoNullRet(Space, NullySpace .Coalesce(NullySpace,  Empty,       spaceMatters));
        NoNullRet(Space, NullySpace .Coalesce(NullySpace,  Space,       spaceMatters));
        NoNullRet(Space, NullySpace .Coalesce(NullySpace,  Text,        spaceMatters));
        NoNullRet(Space, NullySpace .Coalesce(NullyFilled, Null,        spaceMatters));
        NoNullRet(Space, NullySpace .Coalesce(NullyFilled, NullyEmpty,  spaceMatters));
        NoNullRet(Space, NullySpace .Coalesce(NullyFilled, NullySpace,  spaceMatters));
        NoNullRet(Space, NullySpace .Coalesce(NullyFilled, NullyFilled, spaceMatters));
        NoNullRet(Space, NullySpace .Coalesce(NullyFilled, Empty,       spaceMatters));
        NoNullRet(Space, NullySpace .Coalesce(NullyFilled, Space,       spaceMatters));
        NoNullRet(Space, NullySpace .Coalesce(NullyFilled, Text,        spaceMatters));
        NoNullRet(Space, NullySpace .Coalesce(Empty,       Null,        spaceMatters));
        NoNullRet(Space, NullySpace .Coalesce(Empty,       NullyEmpty,  spaceMatters));
        NoNullRet(Space, NullySpace .Coalesce(Empty,       NullySpace,  spaceMatters));
        NoNullRet(Space, NullySpace .Coalesce(Empty,       NullyFilled, spaceMatters));
        NoNullRet(Space, NullySpace .Coalesce(Empty,       Empty,       spaceMatters));
        NoNullRet(Space, NullySpace .Coalesce(Empty,       Space,       spaceMatters));
        NoNullRet(Space, NullySpace .Coalesce(Empty,       Text,        spaceMatters));
        NoNullRet(Space, NullySpace .Coalesce(Space,       Null,        spaceMatters));
        NoNullRet(Space, NullySpace .Coalesce(Space,       NullyEmpty,  spaceMatters));
        NoNullRet(Space, NullySpace .Coalesce(Space,       NullySpace,  spaceMatters));
        NoNullRet(Space, NullySpace .Coalesce(Space,       NullyFilled, spaceMatters));
        NoNullRet(Space, NullySpace .Coalesce(Space,       Empty,       spaceMatters));
        NoNullRet(Space, NullySpace .Coalesce(Space,       Space,       spaceMatters));
        NoNullRet(Space, NullySpace .Coalesce(Space,       Text,        spaceMatters));
        NoNullRet(Space, NullySpace .Coalesce(Text,        Null,        spaceMatters));
        NoNullRet(Space, NullySpace .Coalesce(Text,        NullyEmpty,  spaceMatters));
        NoNullRet(Space, NullySpace .Coalesce(Text,        NullySpace,  spaceMatters));
        NoNullRet(Space, NullySpace .Coalesce(Text,        NullyFilled, spaceMatters));
        NoNullRet(Space, NullySpace .Coalesce(Text,        Empty,       spaceMatters));
        NoNullRet(Space, NullySpace .Coalesce(Text,        Space,       spaceMatters));
        NoNullRet(Space, NullySpace .Coalesce(Text,        Text,        spaceMatters));

        NoNullRet(Text,  NullyFilled.Coalesce(Null,        Null,        spaceMatters));
        NoNullRet(Text,  NullyFilled.Coalesce(Null,        NullyEmpty,  spaceMatters));
        NoNullRet(Text,  NullyFilled.Coalesce(Null,        NullySpace,  spaceMatters));
        NoNullRet(Text,  NullyFilled.Coalesce(Null,        NullyFilled, spaceMatters));
        NoNullRet(Text,  NullyFilled.Coalesce(Null,        Empty,       spaceMatters));
        NoNullRet(Text,  NullyFilled.Coalesce(Null,        Space,       spaceMatters));
        NoNullRet(Text,  NullyFilled.Coalesce(Null,        Text,        spaceMatters));
        NoNullRet(Text,  NullyFilled.Coalesce(NullyEmpty,  Null,        spaceMatters));
        NoNullRet(Text,  NullyFilled.Coalesce(NullyEmpty,  NullyEmpty,  spaceMatters));
        NoNullRet(Text,  NullyFilled.Coalesce(NullyEmpty,  NullySpace,  spaceMatters));
        NoNullRet(Text,  NullyFilled.Coalesce(NullyEmpty,  NullyFilled, spaceMatters));
        NoNullRet(Text,  NullyFilled.Coalesce(NullyEmpty,  Empty,       spaceMatters));
        NoNullRet(Text,  NullyFilled.Coalesce(NullyEmpty,  Space,       spaceMatters));
        NoNullRet(Text,  NullyFilled.Coalesce(NullyEmpty,  Text,        spaceMatters));
        NoNullRet(Text,  NullyFilled.Coalesce(NullySpace,  Null,        spaceMatters));
        NoNullRet(Text,  NullyFilled.Coalesce(NullySpace,  NullyEmpty,  spaceMatters));
        NoNullRet(Text,  NullyFilled.Coalesce(NullySpace,  NullySpace,  spaceMatters));
        NoNullRet(Text,  NullyFilled.Coalesce(NullySpace,  NullyFilled, spaceMatters));
        NoNullRet(Text,  NullyFilled.Coalesce(NullySpace,  Empty,       spaceMatters));
        NoNullRet(Text,  NullyFilled.Coalesce(NullySpace,  Space,       spaceMatters));
        NoNullRet(Text,  NullyFilled.Coalesce(NullySpace,  Text,        spaceMatters));
        NoNullRet(Text,  NullyFilled.Coalesce(NullyFilled, Null,        spaceMatters));
        NoNullRet(Text,  NullyFilled.Coalesce(NullyFilled, NullyEmpty,  spaceMatters));
        NoNullRet(Text,  NullyFilled.Coalesce(NullyFilled, NullySpace,  spaceMatters));
        NoNullRet(Text,  NullyFilled.Coalesce(NullyFilled, NullyFilled, spaceMatters));
        NoNullRet(Text,  NullyFilled.Coalesce(NullyFilled, Empty,       spaceMatters));
        NoNullRet(Text,  NullyFilled.Coalesce(NullyFilled, Space,       spaceMatters));
        NoNullRet(Text,  NullyFilled.Coalesce(NullyFilled, Text,        spaceMatters));
        NoNullRet(Text,  NullyFilled.Coalesce(Empty,       Null,        spaceMatters));
        NoNullRet(Text,  NullyFilled.Coalesce(Empty,       NullyEmpty,  spaceMatters));
        NoNullRet(Text,  NullyFilled.Coalesce(Empty,       NullySpace,  spaceMatters));
        NoNullRet(Text,  NullyFilled.Coalesce(Empty,       NullyFilled, spaceMatters));
        NoNullRet(Text,  NullyFilled.Coalesce(Empty,       Empty,       spaceMatters));
        NoNullRet(Text,  NullyFilled.Coalesce(Empty,       Space,       spaceMatters));
        NoNullRet(Text,  NullyFilled.Coalesce(Empty,       Text,        spaceMatters));
        NoNullRet(Text,  NullyFilled.Coalesce(Space,       Null,        spaceMatters));
        NoNullRet(Text,  NullyFilled.Coalesce(Space,       NullyEmpty,  spaceMatters));
        NoNullRet(Text,  NullyFilled.Coalesce(Space,       NullySpace,  spaceMatters));
        NoNullRet(Text,  NullyFilled.Coalesce(Space,       NullyFilled, spaceMatters));
        NoNullRet(Text,  NullyFilled.Coalesce(Space,       Empty,       spaceMatters));
        NoNullRet(Text,  NullyFilled.Coalesce(Space,       Space,       spaceMatters));
        NoNullRet(Text,  NullyFilled.Coalesce(Space,       Text,        spaceMatters));
        NoNullRet(Text,  NullyFilled.Coalesce(Text,        Null,        spaceMatters));
        NoNullRet(Text,  NullyFilled.Coalesce(Text,        NullyEmpty,  spaceMatters));
        NoNullRet(Text,  NullyFilled.Coalesce(Text,        NullySpace,  spaceMatters));
        NoNullRet(Text,  NullyFilled.Coalesce(Text,        NullyFilled, spaceMatters));
        NoNullRet(Text,  NullyFilled.Coalesce(Text,        Empty,       spaceMatters));
        NoNullRet(Text,  NullyFilled.Coalesce(Text,        Space,       spaceMatters));
        NoNullRet(Text,  NullyFilled.Coalesce(Text,        Text,        spaceMatters));

        NoNullRet(Empty, Empty      .Coalesce(Null,        Null,        spaceMatters));
        NoNullRet(Empty, Empty      .Coalesce(Null,        NullyEmpty,  spaceMatters));
        NoNullRet(Space, Empty      .Coalesce(Null,        NullySpace,  spaceMatters));
        NoNullRet(Text,  Empty      .Coalesce(Null,        NullyFilled, spaceMatters));
        NoNullRet(Empty, Empty      .Coalesce(Null,        Empty,       spaceMatters));
        NoNullRet(Space, Empty      .Coalesce(Null,        Space,       spaceMatters));
        NoNullRet(Text,  Empty      .Coalesce(Null,        Text,        spaceMatters));
        NoNullRet(Empty, Empty      .Coalesce(NullyEmpty,  Null,        spaceMatters));
        NoNullRet(Empty, Empty      .Coalesce(NullyEmpty,  NullyEmpty,  spaceMatters));
        NoNullRet(Space, Empty      .Coalesce(NullyEmpty,  NullySpace,  spaceMatters));
        NoNullRet(Text,  Empty      .Coalesce(NullyEmpty,  NullyFilled, spaceMatters));
        NoNullRet(Empty, Empty      .Coalesce(NullyEmpty,  Empty,       spaceMatters));
        NoNullRet(Space, Empty      .Coalesce(NullyEmpty,  Space,       spaceMatters));
        NoNullRet(Text,  Empty      .Coalesce(NullyEmpty,  Text,        spaceMatters));
        NoNullRet(Space, Empty      .Coalesce(NullySpace,  Null,        spaceMatters));
        NoNullRet(Space, Empty      .Coalesce(NullySpace,  NullyEmpty,  spaceMatters));
        NoNullRet(Space, Empty      .Coalesce(NullySpace,  NullySpace,  spaceMatters));
        NoNullRet(Space, Empty      .Coalesce(NullySpace,  NullyFilled, spaceMatters));
        NoNullRet(Space, Empty      .Coalesce(NullySpace,  Empty,       spaceMatters));
        NoNullRet(Space, Empty      .Coalesce(NullySpace,  Space,       spaceMatters));
        NoNullRet(Space, Empty      .Coalesce(NullySpace,  Text,        spaceMatters));
        NoNullRet(Text,  Empty      .Coalesce(NullyFilled, Null,        spaceMatters));
        NoNullRet(Text,  Empty      .Coalesce(NullyFilled, NullyEmpty,  spaceMatters));
        NoNullRet(Text,  Empty      .Coalesce(NullyFilled, NullySpace,  spaceMatters));
        NoNullRet(Text,  Empty      .Coalesce(NullyFilled, NullyFilled, spaceMatters));
        NoNullRet(Text,  Empty      .Coalesce(NullyFilled, Empty,       spaceMatters));
        NoNullRet(Text,  Empty      .Coalesce(NullyFilled, Space,       spaceMatters));
        NoNullRet(Text,  Empty      .Coalesce(NullyFilled, Text,        spaceMatters));
        NoNullRet(Empty, Empty      .Coalesce(Empty,       Null,        spaceMatters));
        NoNullRet(Empty, Empty      .Coalesce(Empty,       NullyEmpty,  spaceMatters));
        NoNullRet(Space, Empty      .Coalesce(Empty,       NullySpace,  spaceMatters));
        NoNullRet(Text,  Empty      .Coalesce(Empty,       NullyFilled, spaceMatters));
        NoNullRet(Empty, Empty      .Coalesce(Empty,       Empty,       spaceMatters));
        NoNullRet(Space, Empty      .Coalesce(Empty,       Space,       spaceMatters));
        NoNullRet(Text,  Empty      .Coalesce(Empty,       Text,        spaceMatters));
        NoNullRet(Space, Empty      .Coalesce(Space,       Null,        spaceMatters));
        NoNullRet(Space, Empty      .Coalesce(Space,       NullyEmpty,  spaceMatters));
        NoNullRet(Space, Empty      .Coalesce(Space,       NullySpace,  spaceMatters));
        NoNullRet(Space, Empty      .Coalesce(Space,       NullyFilled, spaceMatters));
        NoNullRet(Space, Empty      .Coalesce(Space,       Empty,       spaceMatters));
        NoNullRet(Space, Empty      .Coalesce(Space,       Space,       spaceMatters));
        NoNullRet(Space, Empty      .Coalesce(Space,       Text,        spaceMatters));
        NoNullRet(Text,  Empty      .Coalesce(Text,        Null,        spaceMatters));
        NoNullRet(Text,  Empty      .Coalesce(Text,        NullyEmpty,  spaceMatters));
        NoNullRet(Text,  Empty      .Coalesce(Text,        NullySpace,  spaceMatters));
        NoNullRet(Text,  Empty      .Coalesce(Text,        NullyFilled, spaceMatters));
        NoNullRet(Text,  Empty      .Coalesce(Text,        Empty,       spaceMatters));
        NoNullRet(Text,  Empty      .Coalesce(Text,        Space,       spaceMatters));
        NoNullRet(Text,  Empty      .Coalesce(Text,        Text,        spaceMatters));
                                                                
        NoNullRet(Space, Space      .Coalesce(Null,        Null,        spaceMatters));
        NoNullRet(Space, Space      .Coalesce(Null,        NullyEmpty,  spaceMatters));
        NoNullRet(Space, Space      .Coalesce(Null,        NullySpace,  spaceMatters));
        NoNullRet(Space, Space      .Coalesce(Null,        NullyFilled, spaceMatters));
        NoNullRet(Space, Space      .Coalesce(Null,        Empty,       spaceMatters));
        NoNullRet(Space, Space      .Coalesce(Null,        Space,       spaceMatters));
        NoNullRet(Space, Space      .Coalesce(Null,        Text,        spaceMatters));
        NoNullRet(Space, Space      .Coalesce(NullyEmpty,  Null,        spaceMatters));
        NoNullRet(Space, Space      .Coalesce(NullyEmpty,  NullyEmpty,  spaceMatters));
        NoNullRet(Space, Space      .Coalesce(NullyEmpty,  NullySpace,  spaceMatters));
        NoNullRet(Space, Space      .Coalesce(NullyEmpty,  NullyFilled, spaceMatters));
        NoNullRet(Space, Space      .Coalesce(NullyEmpty,  Empty,       spaceMatters));
        NoNullRet(Space, Space      .Coalesce(NullyEmpty,  Space,       spaceMatters));
        NoNullRet(Space, Space      .Coalesce(NullyEmpty,  Text,        spaceMatters));
        NoNullRet(Space, Space      .Coalesce(NullySpace,  Null,        spaceMatters));
        NoNullRet(Space, Space      .Coalesce(NullySpace,  NullyEmpty,  spaceMatters));
        NoNullRet(Space, Space      .Coalesce(NullySpace,  NullySpace,  spaceMatters));
        NoNullRet(Space, Space      .Coalesce(NullySpace,  NullyFilled, spaceMatters));
        NoNullRet(Space, Space      .Coalesce(NullySpace,  Empty,       spaceMatters));
        NoNullRet(Space, Space      .Coalesce(NullySpace,  Space,       spaceMatters));
        NoNullRet(Space, Space      .Coalesce(NullySpace,  Text,        spaceMatters));
        NoNullRet(Space, Space      .Coalesce(NullyFilled, Null,        spaceMatters));
        NoNullRet(Space, Space      .Coalesce(NullyFilled, NullyEmpty,  spaceMatters));
        NoNullRet(Space, Space      .Coalesce(NullyFilled, NullySpace,  spaceMatters));
        NoNullRet(Space, Space      .Coalesce(NullyFilled, NullyFilled, spaceMatters));
        NoNullRet(Space, Space      .Coalesce(NullyFilled, Empty,       spaceMatters));
        NoNullRet(Space, Space      .Coalesce(NullyFilled, Space,       spaceMatters));
        NoNullRet(Space, Space      .Coalesce(NullyFilled, Text,        spaceMatters));
        NoNullRet(Space, Space      .Coalesce(Empty,       Null,        spaceMatters));
        NoNullRet(Space, Space      .Coalesce(Empty,       NullyEmpty,  spaceMatters));
        NoNullRet(Space, Space      .Coalesce(Empty,       NullySpace,  spaceMatters));
        NoNullRet(Space, Space      .Coalesce(Empty,       NullyFilled, spaceMatters));
        NoNullRet(Space, Space      .Coalesce(Empty,       Empty,       spaceMatters));
        NoNullRet(Space, Space      .Coalesce(Empty,       Space,       spaceMatters));
        NoNullRet(Space, Space      .Coalesce(Empty,       Text,        spaceMatters));
        NoNullRet(Space, Space      .Coalesce(Space,       Null,        spaceMatters));
        NoNullRet(Space, Space      .Coalesce(Space,       NullyEmpty,  spaceMatters));
        NoNullRet(Space, Space      .Coalesce(Space,       NullySpace,  spaceMatters));
        NoNullRet(Space, Space      .Coalesce(Space,       NullyFilled, spaceMatters));
        NoNullRet(Space, Space      .Coalesce(Space,       Empty,       spaceMatters));
        NoNullRet(Space, Space      .Coalesce(Space,       Space,       spaceMatters));
        NoNullRet(Space, Space      .Coalesce(Space,       Text,        spaceMatters));
        NoNullRet(Space, Space      .Coalesce(Text,        Null,        spaceMatters));
        NoNullRet(Space, Space      .Coalesce(Text,        NullyEmpty,  spaceMatters));
        NoNullRet(Space, Space      .Coalesce(Text,        NullySpace,  spaceMatters));
        NoNullRet(Space, Space      .Coalesce(Text,        NullyFilled, spaceMatters));
        NoNullRet(Space, Space      .Coalesce(Text,        Empty,       spaceMatters));
        NoNullRet(Space, Space      .Coalesce(Text,        Space,       spaceMatters));
        NoNullRet(Space, Space      .Coalesce(Text,        Text,        spaceMatters));
                                                                
        NoNullRet(Text,  Text       .Coalesce(Null,        Null,        spaceMatters));
        NoNullRet(Text,  Text       .Coalesce(Null,        NullyEmpty,  spaceMatters));
        NoNullRet(Text,  Text       .Coalesce(Null,        NullySpace,  spaceMatters));
        NoNullRet(Text,  Text       .Coalesce(Null,        NullyFilled, spaceMatters));
        NoNullRet(Text,  Text       .Coalesce(Null,        Empty,       spaceMatters));
        NoNullRet(Text,  Text       .Coalesce(Null,        Space,       spaceMatters));
        NoNullRet(Text,  Text       .Coalesce(Null,        Text,        spaceMatters));
        NoNullRet(Text,  Text       .Coalesce(NullyEmpty,  Null,        spaceMatters));
        NoNullRet(Text,  Text       .Coalesce(NullyEmpty,  NullyEmpty,  spaceMatters));
        NoNullRet(Text,  Text       .Coalesce(NullyEmpty,  NullySpace,  spaceMatters));
        NoNullRet(Text,  Text       .Coalesce(NullyEmpty,  NullyFilled, spaceMatters));
        NoNullRet(Text,  Text       .Coalesce(NullyEmpty,  Empty,       spaceMatters));
        NoNullRet(Text,  Text       .Coalesce(NullyEmpty,  Space,       spaceMatters));
        NoNullRet(Text,  Text       .Coalesce(NullyEmpty,  Text,        spaceMatters));
        NoNullRet(Text,  Text       .Coalesce(NullySpace,  Null,        spaceMatters));
        NoNullRet(Text,  Text       .Coalesce(NullySpace,  NullyEmpty,  spaceMatters));
        NoNullRet(Text,  Text       .Coalesce(NullySpace,  NullySpace,  spaceMatters));
        NoNullRet(Text,  Text       .Coalesce(NullySpace,  NullyFilled, spaceMatters));
        NoNullRet(Text,  Text       .Coalesce(NullySpace,  Empty,       spaceMatters));
        NoNullRet(Text,  Text       .Coalesce(NullySpace,  Space,       spaceMatters));
        NoNullRet(Text,  Text       .Coalesce(NullySpace,  Text,        spaceMatters));
        NoNullRet(Text,  Text       .Coalesce(NullyFilled, Null,        spaceMatters));
        NoNullRet(Text,  Text       .Coalesce(NullyFilled, NullyEmpty,  spaceMatters));
        NoNullRet(Text,  Text       .Coalesce(NullyFilled, NullySpace,  spaceMatters));
        NoNullRet(Text,  Text       .Coalesce(NullyFilled, NullyFilled, spaceMatters));
        NoNullRet(Text,  Text       .Coalesce(NullyFilled, Empty,       spaceMatters));
        NoNullRet(Text,  Text       .Coalesce(NullyFilled, Space,       spaceMatters));
        NoNullRet(Text,  Text       .Coalesce(NullyFilled, Text,        spaceMatters));
        NoNullRet(Text,  Text       .Coalesce(Empty,       Null,        spaceMatters));
        NoNullRet(Text,  Text       .Coalesce(Empty,       NullyEmpty,  spaceMatters));
        NoNullRet(Text,  Text       .Coalesce(Empty,       NullySpace,  spaceMatters));
        NoNullRet(Text,  Text       .Coalesce(Empty,       NullyFilled, spaceMatters));
        NoNullRet(Text,  Text       .Coalesce(Empty,       Empty,       spaceMatters));
        NoNullRet(Text,  Text       .Coalesce(Empty,       Space,       spaceMatters));
        NoNullRet(Text,  Text       .Coalesce(Empty,       Text,        spaceMatters));
        NoNullRet(Text,  Text       .Coalesce(Space,       Null,        spaceMatters));
        NoNullRet(Text,  Text       .Coalesce(Space,       NullyEmpty,  spaceMatters));
        NoNullRet(Text,  Text       .Coalesce(Space,       NullySpace,  spaceMatters));
        NoNullRet(Text,  Text       .Coalesce(Space,       NullyFilled, spaceMatters));
        NoNullRet(Text,  Text       .Coalesce(Space,       Empty,       spaceMatters));
        NoNullRet(Text,  Text       .Coalesce(Space,       Space,       spaceMatters));
        NoNullRet(Text,  Text       .Coalesce(Space,       Text,        spaceMatters));
        NoNullRet(Text,  Text       .Coalesce(Text,        Null,        spaceMatters));
        NoNullRet(Text,  Text       .Coalesce(Text,        NullyEmpty,  spaceMatters));
        NoNullRet(Text,  Text       .Coalesce(Text,        NullySpace,  spaceMatters));
        NoNullRet(Text,  Text       .Coalesce(Text,        NullyFilled, spaceMatters));
        NoNullRet(Text,  Text       .Coalesce(Text,        Empty,       spaceMatters));
        NoNullRet(Text,  Text       .Coalesce(Text,        Space,       spaceMatters));
        NoNullRet(Text,  Text       .Coalesce(Text,        Text,        spaceMatters));
    }
    
    [TestMethod]
    public void Coalesce_3Args_Text_ExtensionsSpaceMattersYes_ExplicitBool()
    {
        AreEqual(" ",   " ".Coalesce(null, "Hi!", spaceMatters: true));

        NoNullRet(Empty, Null       .Coalesce(Null,        Null,        spaceMatters: true));
        NoNullRet(Empty, Null       .Coalesce(Null,        NullyEmpty,  spaceMatters: true));
        NoNullRet(Space, Null       .Coalesce(Null,        NullySpace,  spaceMatters: true));
        NoNullRet(Text,  Null       .Coalesce(Null,        NullyFilled, spaceMatters: true));
        NoNullRet(Empty, Null       .Coalesce(Null,        Empty,       spaceMatters: true));
        NoNullRet(Space, Null       .Coalesce(Null,        Space,       spaceMatters: true));
        NoNullRet(Text,  Null       .Coalesce(Null,        Text,        spaceMatters: true));
        NoNullRet(Empty, Null       .Coalesce(NullyEmpty,  Null,        spaceMatters: true));
        NoNullRet(Empty, Null       .Coalesce(NullyEmpty,  NullyEmpty,  spaceMatters: true));
        NoNullRet(Space, Null       .Coalesce(NullyEmpty,  NullySpace,  spaceMatters: true));
        NoNullRet(Text,  Null       .Coalesce(NullyEmpty,  NullyFilled, spaceMatters: true));
        NoNullRet(Empty, Null       .Coalesce(NullyEmpty,  Empty,       spaceMatters: true));
        NoNullRet(Space, Null       .Coalesce(NullyEmpty,  Space,       spaceMatters: true));
        NoNullRet(Text,  Null       .Coalesce(NullyEmpty,  Text,        spaceMatters: true));
        NoNullRet(Space, Null       .Coalesce(NullySpace,  Null,        spaceMatters: true));
        NoNullRet(Space, Null       .Coalesce(NullySpace,  NullyEmpty,  spaceMatters: true));
        NoNullRet(Space, Null       .Coalesce(NullySpace,  NullySpace,  spaceMatters: true));
        NoNullRet(Space, Null       .Coalesce(NullySpace,  NullyFilled, spaceMatters: true));
        NoNullRet(Space, Null       .Coalesce(NullySpace,  Empty,       spaceMatters: true));
        NoNullRet(Space, Null       .Coalesce(NullySpace,  Space,       spaceMatters: true));
        NoNullRet(Space, Null       .Coalesce(NullySpace,  Text,        spaceMatters: true));
        NoNullRet(Text,  Null       .Coalesce(NullyFilled, Null,        spaceMatters: true));
        NoNullRet(Text,  Null       .Coalesce(NullyFilled, NullyEmpty,  spaceMatters: true));
        NoNullRet(Text,  Null       .Coalesce(NullyFilled, NullySpace,  spaceMatters: true));
        NoNullRet(Text,  Null       .Coalesce(NullyFilled, NullyFilled, spaceMatters: true));
        NoNullRet(Text,  Null       .Coalesce(NullyFilled, Empty,       spaceMatters: true));
        NoNullRet(Text,  Null       .Coalesce(NullyFilled, Space,       spaceMatters: true));
        NoNullRet(Text,  Null       .Coalesce(NullyFilled, Text,        spaceMatters: true));
        NoNullRet(Empty, Null       .Coalesce(Empty,       Null,        spaceMatters: true));
        NoNullRet(Empty, Null       .Coalesce(Empty,       NullyEmpty,  spaceMatters: true));
        NoNullRet(Space, Null       .Coalesce(Empty,       NullySpace,  spaceMatters: true));
        NoNullRet(Text,  Null       .Coalesce(Empty,       NullyFilled, spaceMatters: true));
        NoNullRet(Empty, Null       .Coalesce(Empty,       Empty,       spaceMatters: true));
        NoNullRet(Space, Null       .Coalesce(Empty,       Space,       spaceMatters: true));
        NoNullRet(Text,  Null       .Coalesce(Empty,       Text,        spaceMatters: true));
        NoNullRet(Space, Null       .Coalesce(Space,       Null,        spaceMatters: true));
        NoNullRet(Space, Null       .Coalesce(Space,       NullyEmpty,  spaceMatters: true));
        NoNullRet(Space, Null       .Coalesce(Space,       NullySpace,  spaceMatters: true));
        NoNullRet(Space, Null       .Coalesce(Space,       NullyFilled, spaceMatters: true));
        NoNullRet(Space, Null       .Coalesce(Space,       Empty,       spaceMatters: true));
        NoNullRet(Space, Null       .Coalesce(Space,       Space,       spaceMatters: true));
        NoNullRet(Space, Null       .Coalesce(Space,       Text,        spaceMatters: true));
        NoNullRet(Text,  Null       .Coalesce(Text,        Null,        spaceMatters: true));
        NoNullRet(Text,  Null       .Coalesce(Text,        NullyEmpty,  spaceMatters: true));
        NoNullRet(Text,  Null       .Coalesce(Text,        NullySpace,  spaceMatters: true));
        NoNullRet(Text,  Null       .Coalesce(Text,        NullyFilled, spaceMatters: true));
        NoNullRet(Text,  Null       .Coalesce(Text,        Empty,       spaceMatters: true));
        NoNullRet(Text,  Null       .Coalesce(Text,        Space,       spaceMatters: true));
        NoNullRet(Text,  Null       .Coalesce(Text,        Text,        spaceMatters: true));
        
        NoNullRet(Empty, NullyEmpty .Coalesce(Null,        Null,        spaceMatters: true));
        NoNullRet(Empty, NullyEmpty .Coalesce(Null,        NullyEmpty,  spaceMatters: true));
        NoNullRet(Space, NullyEmpty .Coalesce(Null,        NullySpace,  spaceMatters: true));
        NoNullRet(Text,  NullyEmpty .Coalesce(Null,        NullyFilled, spaceMatters: true));
        NoNullRet(Empty, NullyEmpty .Coalesce(Null,        Empty,       spaceMatters: true));
        NoNullRet(Space, NullyEmpty .Coalesce(Null,        Space,       spaceMatters: true));
        NoNullRet(Text,  NullyEmpty .Coalesce(Null,        Text,        spaceMatters: true));
        NoNullRet(Empty, NullyEmpty .Coalesce(NullyEmpty,  Null,        spaceMatters: true));
        NoNullRet(Empty, NullyEmpty .Coalesce(NullyEmpty,  NullyEmpty,  spaceMatters: true));
        NoNullRet(Space, NullyEmpty .Coalesce(NullyEmpty,  NullySpace,  spaceMatters: true));
        NoNullRet(Text,  NullyEmpty .Coalesce(NullyEmpty,  NullyFilled, spaceMatters: true));
        NoNullRet(Empty, NullyEmpty .Coalesce(NullyEmpty,  Empty,       spaceMatters: true));
        NoNullRet(Space, NullyEmpty .Coalesce(NullyEmpty,  Space,       spaceMatters: true));
        NoNullRet(Text,  NullyEmpty .Coalesce(NullyEmpty,  Text,        spaceMatters: true));
        NoNullRet(Space, NullyEmpty .Coalesce(NullySpace,  Null,        spaceMatters: true));
        NoNullRet(Space, NullyEmpty .Coalesce(NullySpace,  NullyEmpty,  spaceMatters: true));
        NoNullRet(Space, NullyEmpty .Coalesce(NullySpace,  NullySpace,  spaceMatters: true));
        NoNullRet(Space, NullyEmpty .Coalesce(NullySpace,  NullyFilled, spaceMatters: true));
        NoNullRet(Space, NullyEmpty .Coalesce(NullySpace,  Empty,       spaceMatters: true));
        NoNullRet(Space, NullyEmpty .Coalesce(NullySpace,  Space,       spaceMatters: true));
        NoNullRet(Space, NullyEmpty .Coalesce(NullySpace,  Text,        spaceMatters: true));
        NoNullRet(Text,  NullyEmpty .Coalesce(NullyFilled, Null,        spaceMatters: true));
        NoNullRet(Text,  NullyEmpty .Coalesce(NullyFilled, NullyEmpty,  spaceMatters: true));
        NoNullRet(Text,  NullyEmpty .Coalesce(NullyFilled, NullySpace,  spaceMatters: true));
        NoNullRet(Text,  NullyEmpty .Coalesce(NullyFilled, NullyFilled, spaceMatters: true));
        NoNullRet(Text,  NullyEmpty .Coalesce(NullyFilled, Empty,       spaceMatters: true));
        NoNullRet(Text,  NullyEmpty .Coalesce(NullyFilled, Space,       spaceMatters: true));
        NoNullRet(Text,  NullyEmpty .Coalesce(NullyFilled, Text,        spaceMatters: true));
        NoNullRet(Empty, NullyEmpty .Coalesce(Empty,       Null,        spaceMatters: true));
        NoNullRet(Empty, NullyEmpty .Coalesce(Empty,       NullyEmpty,  spaceMatters: true));
        NoNullRet(Space, NullyEmpty .Coalesce(Empty,       NullySpace,  spaceMatters: true));
        NoNullRet(Text,  NullyEmpty .Coalesce(Empty,       NullyFilled, spaceMatters: true));
        NoNullRet(Empty, NullyEmpty .Coalesce(Empty,       Empty,       spaceMatters: true));
        NoNullRet(Space, NullyEmpty .Coalesce(Empty,       Space,       spaceMatters: true));
        NoNullRet(Text,  NullyEmpty .Coalesce(Empty,       Text,        spaceMatters: true));
        NoNullRet(Space, NullyEmpty .Coalesce(Space,       Null,        spaceMatters: true));
        NoNullRet(Space, NullyEmpty .Coalesce(Space,       NullyEmpty,  spaceMatters: true));
        NoNullRet(Space, NullyEmpty .Coalesce(Space,       NullySpace,  spaceMatters: true));
        NoNullRet(Space, NullyEmpty .Coalesce(Space,       NullyFilled, spaceMatters: true));
        NoNullRet(Space, NullyEmpty .Coalesce(Space,       Empty,       spaceMatters: true));
        NoNullRet(Space, NullyEmpty .Coalesce(Space,       Space,       spaceMatters: true));
        NoNullRet(Space, NullyEmpty .Coalesce(Space,       Text,        spaceMatters: true));
        NoNullRet(Text,  NullyEmpty .Coalesce(Text,        Null,        spaceMatters: true));
        NoNullRet(Text,  NullyEmpty .Coalesce(Text,        NullyEmpty,  spaceMatters: true));
        NoNullRet(Text,  NullyEmpty .Coalesce(Text,        NullySpace,  spaceMatters: true));
        NoNullRet(Text,  NullyEmpty .Coalesce(Text,        NullyFilled, spaceMatters: true));
        NoNullRet(Text,  NullyEmpty .Coalesce(Text,        Empty,       spaceMatters: true));
        NoNullRet(Text,  NullyEmpty .Coalesce(Text,        Space,       spaceMatters: true));
        NoNullRet(Text,  NullyEmpty .Coalesce(Text,        Text,        spaceMatters: true));

        NoNullRet(Space, NullySpace .Coalesce(Null,        Null,        spaceMatters: true));
        NoNullRet(Space, NullySpace .Coalesce(Null,        NullyEmpty,  spaceMatters: true));
        NoNullRet(Space, NullySpace .Coalesce(Null,        NullySpace,  spaceMatters: true));
        NoNullRet(Space, NullySpace .Coalesce(Null,        NullyFilled, spaceMatters: true));
        NoNullRet(Space, NullySpace .Coalesce(Null,        Empty,       spaceMatters: true));
        NoNullRet(Space, NullySpace .Coalesce(Null,        Space,       spaceMatters: true));
        NoNullRet(Space, NullySpace .Coalesce(Null,        Text,        spaceMatters: true));
        NoNullRet(Space, NullySpace .Coalesce(NullyEmpty,  Null,        spaceMatters: true));
        NoNullRet(Space, NullySpace .Coalesce(NullyEmpty,  NullyEmpty,  spaceMatters: true));
        NoNullRet(Space, NullySpace .Coalesce(NullyEmpty,  NullySpace,  spaceMatters: true));
        NoNullRet(Space, NullySpace .Coalesce(NullyEmpty,  NullyFilled, spaceMatters: true));
        NoNullRet(Space, NullySpace .Coalesce(NullyEmpty,  Empty,       spaceMatters: true));
        NoNullRet(Space, NullySpace .Coalesce(NullyEmpty,  Space,       spaceMatters: true));
        NoNullRet(Space, NullySpace .Coalesce(NullyEmpty,  Text,        spaceMatters: true));
        NoNullRet(Space, NullySpace .Coalesce(NullySpace,  Null,        spaceMatters: true));
        NoNullRet(Space, NullySpace .Coalesce(NullySpace,  NullyEmpty,  spaceMatters: true));
        NoNullRet(Space, NullySpace .Coalesce(NullySpace,  NullySpace,  spaceMatters: true));
        NoNullRet(Space, NullySpace .Coalesce(NullySpace,  NullyFilled, spaceMatters: true));
        NoNullRet(Space, NullySpace .Coalesce(NullySpace,  Empty,       spaceMatters: true));
        NoNullRet(Space, NullySpace .Coalesce(NullySpace,  Space,       spaceMatters: true));
        NoNullRet(Space, NullySpace .Coalesce(NullySpace,  Text,        spaceMatters: true));
        NoNullRet(Space, NullySpace .Coalesce(NullyFilled, Null,        spaceMatters: true));
        NoNullRet(Space, NullySpace .Coalesce(NullyFilled, NullyEmpty,  spaceMatters: true));
        NoNullRet(Space, NullySpace .Coalesce(NullyFilled, NullySpace,  spaceMatters: true));
        NoNullRet(Space, NullySpace .Coalesce(NullyFilled, NullyFilled, spaceMatters: true));
        NoNullRet(Space, NullySpace .Coalesce(NullyFilled, Empty,       spaceMatters: true));
        NoNullRet(Space, NullySpace .Coalesce(NullyFilled, Space,       spaceMatters: true));
        NoNullRet(Space, NullySpace .Coalesce(NullyFilled, Text,        spaceMatters: true));
        NoNullRet(Space, NullySpace .Coalesce(Empty,       Null,        spaceMatters: true));
        NoNullRet(Space, NullySpace .Coalesce(Empty,       NullyEmpty,  spaceMatters: true));
        NoNullRet(Space, NullySpace .Coalesce(Empty,       NullySpace,  spaceMatters: true));
        NoNullRet(Space, NullySpace .Coalesce(Empty,       NullyFilled, spaceMatters: true));
        NoNullRet(Space, NullySpace .Coalesce(Empty,       Empty,       spaceMatters: true));
        NoNullRet(Space, NullySpace .Coalesce(Empty,       Space,       spaceMatters: true));
        NoNullRet(Space, NullySpace .Coalesce(Empty,       Text,        spaceMatters: true));
        NoNullRet(Space, NullySpace .Coalesce(Space,       Null,        spaceMatters: true));
        NoNullRet(Space, NullySpace .Coalesce(Space,       NullyEmpty,  spaceMatters: true));
        NoNullRet(Space, NullySpace .Coalesce(Space,       NullySpace,  spaceMatters: true));
        NoNullRet(Space, NullySpace .Coalesce(Space,       NullyFilled, spaceMatters: true));
        NoNullRet(Space, NullySpace .Coalesce(Space,       Empty,       spaceMatters: true));
        NoNullRet(Space, NullySpace .Coalesce(Space,       Space,       spaceMatters: true));
        NoNullRet(Space, NullySpace .Coalesce(Space,       Text,        spaceMatters: true));
        NoNullRet(Space, NullySpace .Coalesce(Text,        Null,        spaceMatters: true));
        NoNullRet(Space, NullySpace .Coalesce(Text,        NullyEmpty,  spaceMatters: true));
        NoNullRet(Space, NullySpace .Coalesce(Text,        NullySpace,  spaceMatters: true));
        NoNullRet(Space, NullySpace .Coalesce(Text,        NullyFilled, spaceMatters: true));
        NoNullRet(Space, NullySpace .Coalesce(Text,        Empty,       spaceMatters: true));
        NoNullRet(Space, NullySpace .Coalesce(Text,        Space,       spaceMatters: true));
        NoNullRet(Space, NullySpace .Coalesce(Text,        Text,        spaceMatters: true));

        NoNullRet(Text,  NullyFilled.Coalesce(Null,        Null,        spaceMatters: true));
        NoNullRet(Text,  NullyFilled.Coalesce(Null,        NullyEmpty,  spaceMatters: true));
        NoNullRet(Text,  NullyFilled.Coalesce(Null,        NullySpace,  spaceMatters: true));
        NoNullRet(Text,  NullyFilled.Coalesce(Null,        NullyFilled, spaceMatters: true));
        NoNullRet(Text,  NullyFilled.Coalesce(Null,        Empty,       spaceMatters: true));
        NoNullRet(Text,  NullyFilled.Coalesce(Null,        Space,       spaceMatters: true));
        NoNullRet(Text,  NullyFilled.Coalesce(Null,        Text,        spaceMatters: true));
        NoNullRet(Text,  NullyFilled.Coalesce(NullyEmpty,  Null,        spaceMatters: true));
        NoNullRet(Text,  NullyFilled.Coalesce(NullyEmpty,  NullyEmpty,  spaceMatters: true));
        NoNullRet(Text,  NullyFilled.Coalesce(NullyEmpty,  NullySpace,  spaceMatters: true));
        NoNullRet(Text,  NullyFilled.Coalesce(NullyEmpty,  NullyFilled, spaceMatters: true));
        NoNullRet(Text,  NullyFilled.Coalesce(NullyEmpty,  Empty,       spaceMatters: true));
        NoNullRet(Text,  NullyFilled.Coalesce(NullyEmpty,  Space,       spaceMatters: true));
        NoNullRet(Text,  NullyFilled.Coalesce(NullyEmpty,  Text,        spaceMatters: true));
        NoNullRet(Text,  NullyFilled.Coalesce(NullySpace,  Null,        spaceMatters: true));
        NoNullRet(Text,  NullyFilled.Coalesce(NullySpace,  NullyEmpty,  spaceMatters: true));
        NoNullRet(Text,  NullyFilled.Coalesce(NullySpace,  NullySpace,  spaceMatters: true));
        NoNullRet(Text,  NullyFilled.Coalesce(NullySpace,  NullyFilled, spaceMatters: true));
        NoNullRet(Text,  NullyFilled.Coalesce(NullySpace,  Empty,       spaceMatters: true));
        NoNullRet(Text,  NullyFilled.Coalesce(NullySpace,  Space,       spaceMatters: true));
        NoNullRet(Text,  NullyFilled.Coalesce(NullySpace,  Text,        spaceMatters: true));
        NoNullRet(Text,  NullyFilled.Coalesce(NullyFilled, Null,        spaceMatters: true));
        NoNullRet(Text,  NullyFilled.Coalesce(NullyFilled, NullyEmpty,  spaceMatters: true));
        NoNullRet(Text,  NullyFilled.Coalesce(NullyFilled, NullySpace,  spaceMatters: true));
        NoNullRet(Text,  NullyFilled.Coalesce(NullyFilled, NullyFilled, spaceMatters: true));
        NoNullRet(Text,  NullyFilled.Coalesce(NullyFilled, Empty,       spaceMatters: true));
        NoNullRet(Text,  NullyFilled.Coalesce(NullyFilled, Space,       spaceMatters: true));
        NoNullRet(Text,  NullyFilled.Coalesce(NullyFilled, Text,        spaceMatters: true));
        NoNullRet(Text,  NullyFilled.Coalesce(Empty,       Null,        spaceMatters: true));
        NoNullRet(Text,  NullyFilled.Coalesce(Empty,       NullyEmpty,  spaceMatters: true));
        NoNullRet(Text,  NullyFilled.Coalesce(Empty,       NullySpace,  spaceMatters: true));
        NoNullRet(Text,  NullyFilled.Coalesce(Empty,       NullyFilled, spaceMatters: true));
        NoNullRet(Text,  NullyFilled.Coalesce(Empty,       Empty,       spaceMatters: true));
        NoNullRet(Text,  NullyFilled.Coalesce(Empty,       Space,       spaceMatters: true));
        NoNullRet(Text,  NullyFilled.Coalesce(Empty,       Text,        spaceMatters: true));
        NoNullRet(Text,  NullyFilled.Coalesce(Space,       Null,        spaceMatters: true));
        NoNullRet(Text,  NullyFilled.Coalesce(Space,       NullyEmpty,  spaceMatters: true));
        NoNullRet(Text,  NullyFilled.Coalesce(Space,       NullySpace,  spaceMatters: true));
        NoNullRet(Text,  NullyFilled.Coalesce(Space,       NullyFilled, spaceMatters: true));
        NoNullRet(Text,  NullyFilled.Coalesce(Space,       Empty,       spaceMatters: true));
        NoNullRet(Text,  NullyFilled.Coalesce(Space,       Space,       spaceMatters: true));
        NoNullRet(Text,  NullyFilled.Coalesce(Space,       Text,        spaceMatters: true));
        NoNullRet(Text,  NullyFilled.Coalesce(Text,        Null,        spaceMatters: true));
        NoNullRet(Text,  NullyFilled.Coalesce(Text,        NullyEmpty,  spaceMatters: true));
        NoNullRet(Text,  NullyFilled.Coalesce(Text,        NullySpace,  spaceMatters: true));
        NoNullRet(Text,  NullyFilled.Coalesce(Text,        NullyFilled, spaceMatters: true));
        NoNullRet(Text,  NullyFilled.Coalesce(Text,        Empty,       spaceMatters: true));
        NoNullRet(Text,  NullyFilled.Coalesce(Text,        Space,       spaceMatters: true));
        NoNullRet(Text,  NullyFilled.Coalesce(Text,        Text,        spaceMatters: true));

        NoNullRet(Empty, Empty      .Coalesce(Null,        Null,        spaceMatters: true));
        NoNullRet(Empty, Empty      .Coalesce(Null,        NullyEmpty,  spaceMatters: true));
        NoNullRet(Space, Empty      .Coalesce(Null,        NullySpace,  spaceMatters: true));
        NoNullRet(Text,  Empty      .Coalesce(Null,        NullyFilled, spaceMatters: true));
        NoNullRet(Empty, Empty      .Coalesce(Null,        Empty,       spaceMatters: true));
        NoNullRet(Space, Empty      .Coalesce(Null,        Space,       spaceMatters: true));
        NoNullRet(Text,  Empty      .Coalesce(Null,        Text,        spaceMatters: true));
        NoNullRet(Empty, Empty      .Coalesce(NullyEmpty,  Null,        spaceMatters: true));
        NoNullRet(Empty, Empty      .Coalesce(NullyEmpty,  NullyEmpty,  spaceMatters: true));
        NoNullRet(Space, Empty      .Coalesce(NullyEmpty,  NullySpace,  spaceMatters: true));
        NoNullRet(Text,  Empty      .Coalesce(NullyEmpty,  NullyFilled, spaceMatters: true));
        NoNullRet(Empty, Empty      .Coalesce(NullyEmpty,  Empty,       spaceMatters: true));
        NoNullRet(Space, Empty      .Coalesce(NullyEmpty,  Space,       spaceMatters: true));
        NoNullRet(Text,  Empty      .Coalesce(NullyEmpty,  Text,        spaceMatters: true));
        NoNullRet(Space, Empty      .Coalesce(NullySpace,  Null,        spaceMatters: true));
        NoNullRet(Space, Empty      .Coalesce(NullySpace,  NullyEmpty,  spaceMatters: true));
        NoNullRet(Space, Empty      .Coalesce(NullySpace,  NullySpace,  spaceMatters: true));
        NoNullRet(Space, Empty      .Coalesce(NullySpace,  NullyFilled, spaceMatters: true));
        NoNullRet(Space, Empty      .Coalesce(NullySpace,  Empty,       spaceMatters: true));
        NoNullRet(Space, Empty      .Coalesce(NullySpace,  Space,       spaceMatters: true));
        NoNullRet(Space, Empty      .Coalesce(NullySpace,  Text,        spaceMatters: true));
        NoNullRet(Text,  Empty      .Coalesce(NullyFilled, Null,        spaceMatters: true));
        NoNullRet(Text,  Empty      .Coalesce(NullyFilled, NullyEmpty,  spaceMatters: true));
        NoNullRet(Text,  Empty      .Coalesce(NullyFilled, NullySpace,  spaceMatters: true));
        NoNullRet(Text,  Empty      .Coalesce(NullyFilled, NullyFilled, spaceMatters: true));
        NoNullRet(Text,  Empty      .Coalesce(NullyFilled, Empty,       spaceMatters: true));
        NoNullRet(Text,  Empty      .Coalesce(NullyFilled, Space,       spaceMatters: true));
        NoNullRet(Text,  Empty      .Coalesce(NullyFilled, Text,        spaceMatters: true));
        NoNullRet(Empty, Empty      .Coalesce(Empty,       Null,        spaceMatters: true));
        NoNullRet(Empty, Empty      .Coalesce(Empty,       NullyEmpty,  spaceMatters: true));
        NoNullRet(Space, Empty      .Coalesce(Empty,       NullySpace,  spaceMatters: true));
        NoNullRet(Text,  Empty      .Coalesce(Empty,       NullyFilled, spaceMatters: true));
        NoNullRet(Empty, Empty      .Coalesce(Empty,       Empty,       spaceMatters: true));
        NoNullRet(Space, Empty      .Coalesce(Empty,       Space,       spaceMatters: true));
        NoNullRet(Text,  Empty      .Coalesce(Empty,       Text,        spaceMatters: true));
        NoNullRet(Space, Empty      .Coalesce(Space,       Null,        spaceMatters: true));
        NoNullRet(Space, Empty      .Coalesce(Space,       NullyEmpty,  spaceMatters: true));
        NoNullRet(Space, Empty      .Coalesce(Space,       NullySpace,  spaceMatters: true));
        NoNullRet(Space, Empty      .Coalesce(Space,       NullyFilled, spaceMatters: true));
        NoNullRet(Space, Empty      .Coalesce(Space,       Empty,       spaceMatters: true));
        NoNullRet(Space, Empty      .Coalesce(Space,       Space,       spaceMatters: true));
        NoNullRet(Space, Empty      .Coalesce(Space,       Text,        spaceMatters: true));
        NoNullRet(Text,  Empty      .Coalesce(Text,        Null,        spaceMatters: true));
        NoNullRet(Text,  Empty      .Coalesce(Text,        NullyEmpty,  spaceMatters: true));
        NoNullRet(Text,  Empty      .Coalesce(Text,        NullySpace,  spaceMatters: true));
        NoNullRet(Text,  Empty      .Coalesce(Text,        NullyFilled, spaceMatters: true));
        NoNullRet(Text,  Empty      .Coalesce(Text,        Empty,       spaceMatters: true));
        NoNullRet(Text,  Empty      .Coalesce(Text,        Space,       spaceMatters: true));
        NoNullRet(Text,  Empty      .Coalesce(Text,        Text,        spaceMatters: true));
                                                                
        NoNullRet(Space, Space      .Coalesce(Null,        Null,        spaceMatters: true));
        NoNullRet(Space, Space      .Coalesce(Null,        NullyEmpty,  spaceMatters: true));
        NoNullRet(Space, Space      .Coalesce(Null,        NullySpace,  spaceMatters: true));
        NoNullRet(Space, Space      .Coalesce(Null,        NullyFilled, spaceMatters: true));
        NoNullRet(Space, Space      .Coalesce(Null,        Empty,       spaceMatters: true));
        NoNullRet(Space, Space      .Coalesce(Null,        Space,       spaceMatters: true));
        NoNullRet(Space, Space      .Coalesce(Null,        Text,        spaceMatters: true));
        NoNullRet(Space, Space      .Coalesce(NullyEmpty,  Null,        spaceMatters: true));
        NoNullRet(Space, Space      .Coalesce(NullyEmpty,  NullyEmpty,  spaceMatters: true));
        NoNullRet(Space, Space      .Coalesce(NullyEmpty,  NullySpace,  spaceMatters: true));
        NoNullRet(Space, Space      .Coalesce(NullyEmpty,  NullyFilled, spaceMatters: true));
        NoNullRet(Space, Space      .Coalesce(NullyEmpty,  Empty,       spaceMatters: true));
        NoNullRet(Space, Space      .Coalesce(NullyEmpty,  Space,       spaceMatters: true));
        NoNullRet(Space, Space      .Coalesce(NullyEmpty,  Text,        spaceMatters: true));
        NoNullRet(Space, Space      .Coalesce(NullySpace,  Null,        spaceMatters: true));
        NoNullRet(Space, Space      .Coalesce(NullySpace,  NullyEmpty,  spaceMatters: true));
        NoNullRet(Space, Space      .Coalesce(NullySpace,  NullySpace,  spaceMatters: true));
        NoNullRet(Space, Space      .Coalesce(NullySpace,  NullyFilled, spaceMatters: true));
        NoNullRet(Space, Space      .Coalesce(NullySpace,  Empty,       spaceMatters: true));
        NoNullRet(Space, Space      .Coalesce(NullySpace,  Space,       spaceMatters: true));
        NoNullRet(Space, Space      .Coalesce(NullySpace,  Text,        spaceMatters: true));
        NoNullRet(Space, Space      .Coalesce(NullyFilled, Null,        spaceMatters: true));
        NoNullRet(Space, Space      .Coalesce(NullyFilled, NullyEmpty,  spaceMatters: true));
        NoNullRet(Space, Space      .Coalesce(NullyFilled, NullySpace,  spaceMatters: true));
        NoNullRet(Space, Space      .Coalesce(NullyFilled, NullyFilled, spaceMatters: true));
        NoNullRet(Space, Space      .Coalesce(NullyFilled, Empty,       spaceMatters: true));
        NoNullRet(Space, Space      .Coalesce(NullyFilled, Space,       spaceMatters: true));
        NoNullRet(Space, Space      .Coalesce(NullyFilled, Text,        spaceMatters: true));
        NoNullRet(Space, Space      .Coalesce(Empty,       Null,        spaceMatters: true));
        NoNullRet(Space, Space      .Coalesce(Empty,       NullyEmpty,  spaceMatters: true));
        NoNullRet(Space, Space      .Coalesce(Empty,       NullySpace,  spaceMatters: true));
        NoNullRet(Space, Space      .Coalesce(Empty,       NullyFilled, spaceMatters: true));
        NoNullRet(Space, Space      .Coalesce(Empty,       Empty,       spaceMatters: true));
        NoNullRet(Space, Space      .Coalesce(Empty,       Space,       spaceMatters: true));
        NoNullRet(Space, Space      .Coalesce(Empty,       Text,        spaceMatters: true));
        NoNullRet(Space, Space      .Coalesce(Space,       Null,        spaceMatters: true));
        NoNullRet(Space, Space      .Coalesce(Space,       NullyEmpty,  spaceMatters: true));
        NoNullRet(Space, Space      .Coalesce(Space,       NullySpace,  spaceMatters: true));
        NoNullRet(Space, Space      .Coalesce(Space,       NullyFilled, spaceMatters: true));
        NoNullRet(Space, Space      .Coalesce(Space,       Empty,       spaceMatters: true));
        NoNullRet(Space, Space      .Coalesce(Space,       Space,       spaceMatters: true));
        NoNullRet(Space, Space      .Coalesce(Space,       Text,        spaceMatters: true));
        NoNullRet(Space, Space      .Coalesce(Text,        Null,        spaceMatters: true));
        NoNullRet(Space, Space      .Coalesce(Text,        NullyEmpty,  spaceMatters: true));
        NoNullRet(Space, Space      .Coalesce(Text,        NullySpace,  spaceMatters: true));
        NoNullRet(Space, Space      .Coalesce(Text,        NullyFilled, spaceMatters: true));
        NoNullRet(Space, Space      .Coalesce(Text,        Empty,       spaceMatters: true));
        NoNullRet(Space, Space      .Coalesce(Text,        Space,       spaceMatters: true));
        NoNullRet(Space, Space      .Coalesce(Text,        Text,        spaceMatters: true));
                                                                
        NoNullRet(Text,  Text       .Coalesce(Null,        Null,        spaceMatters: true));
        NoNullRet(Text,  Text       .Coalesce(Null,        NullyEmpty,  spaceMatters: true));
        NoNullRet(Text,  Text       .Coalesce(Null,        NullySpace,  spaceMatters: true));
        NoNullRet(Text,  Text       .Coalesce(Null,        NullyFilled, spaceMatters: true));
        NoNullRet(Text,  Text       .Coalesce(Null,        Empty,       spaceMatters: true));
        NoNullRet(Text,  Text       .Coalesce(Null,        Space,       spaceMatters: true));
        NoNullRet(Text,  Text       .Coalesce(Null,        Text,        spaceMatters: true));
        NoNullRet(Text,  Text       .Coalesce(NullyEmpty,  Null,        spaceMatters: true));
        NoNullRet(Text,  Text       .Coalesce(NullyEmpty,  NullyEmpty,  spaceMatters: true));
        NoNullRet(Text,  Text       .Coalesce(NullyEmpty,  NullySpace,  spaceMatters: true));
        NoNullRet(Text,  Text       .Coalesce(NullyEmpty,  NullyFilled, spaceMatters: true));
        NoNullRet(Text,  Text       .Coalesce(NullyEmpty,  Empty,       spaceMatters: true));
        NoNullRet(Text,  Text       .Coalesce(NullyEmpty,  Space,       spaceMatters: true));
        NoNullRet(Text,  Text       .Coalesce(NullyEmpty,  Text,        spaceMatters: true));
        NoNullRet(Text,  Text       .Coalesce(NullySpace,  Null,        spaceMatters: true));
        NoNullRet(Text,  Text       .Coalesce(NullySpace,  NullyEmpty,  spaceMatters: true));
        NoNullRet(Text,  Text       .Coalesce(NullySpace,  NullySpace,  spaceMatters: true));
        NoNullRet(Text,  Text       .Coalesce(NullySpace,  NullyFilled, spaceMatters: true));
        NoNullRet(Text,  Text       .Coalesce(NullySpace,  Empty,       spaceMatters: true));
        NoNullRet(Text,  Text       .Coalesce(NullySpace,  Space,       spaceMatters: true));
        NoNullRet(Text,  Text       .Coalesce(NullySpace,  Text,        spaceMatters: true));
        NoNullRet(Text,  Text       .Coalesce(NullyFilled, Null,        spaceMatters: true));
        NoNullRet(Text,  Text       .Coalesce(NullyFilled, NullyEmpty,  spaceMatters: true));
        NoNullRet(Text,  Text       .Coalesce(NullyFilled, NullySpace,  spaceMatters: true));
        NoNullRet(Text,  Text       .Coalesce(NullyFilled, NullyFilled, spaceMatters: true));
        NoNullRet(Text,  Text       .Coalesce(NullyFilled, Empty,       spaceMatters: true));
        NoNullRet(Text,  Text       .Coalesce(NullyFilled, Space,       spaceMatters: true));
        NoNullRet(Text,  Text       .Coalesce(NullyFilled, Text,        spaceMatters: true));
        NoNullRet(Text,  Text       .Coalesce(Empty,       Null,        spaceMatters: true));
        NoNullRet(Text,  Text       .Coalesce(Empty,       NullyEmpty,  spaceMatters: true));
        NoNullRet(Text,  Text       .Coalesce(Empty,       NullySpace,  spaceMatters: true));
        NoNullRet(Text,  Text       .Coalesce(Empty,       NullyFilled, spaceMatters: true));
        NoNullRet(Text,  Text       .Coalesce(Empty,       Empty,       spaceMatters: true));
        NoNullRet(Text,  Text       .Coalesce(Empty,       Space,       spaceMatters: true));
        NoNullRet(Text,  Text       .Coalesce(Empty,       Text,        spaceMatters: true));
        NoNullRet(Text,  Text       .Coalesce(Space,       Null,        spaceMatters: true));
        NoNullRet(Text,  Text       .Coalesce(Space,       NullyEmpty,  spaceMatters: true));
        NoNullRet(Text,  Text       .Coalesce(Space,       NullySpace,  spaceMatters: true));
        NoNullRet(Text,  Text       .Coalesce(Space,       NullyFilled, spaceMatters: true));
        NoNullRet(Text,  Text       .Coalesce(Space,       Empty,       spaceMatters: true));
        NoNullRet(Text,  Text       .Coalesce(Space,       Space,       spaceMatters: true));
        NoNullRet(Text,  Text       .Coalesce(Space,       Text,        spaceMatters: true));
        NoNullRet(Text,  Text       .Coalesce(Text,        Null,        spaceMatters: true));
        NoNullRet(Text,  Text       .Coalesce(Text,        NullyEmpty,  spaceMatters: true));
        NoNullRet(Text,  Text       .Coalesce(Text,        NullySpace,  spaceMatters: true));
        NoNullRet(Text,  Text       .Coalesce(Text,        NullyFilled, spaceMatters: true));
        NoNullRet(Text,  Text       .Coalesce(Text,        Empty,       spaceMatters: true));
        NoNullRet(Text,  Text       .Coalesce(Text,        Space,       spaceMatters: true));
        NoNullRet(Text,  Text       .Coalesce(Text,        Text,        spaceMatters: true));
    }
}