namespace JJ.Framework.Existence.Core.Tests;

/// <inheritdoc cref="_coalesce3argssbtotext" />
[TestClass]
public class Coalesce_3Args_SBToText_Extensions : TestBase
{
    private const string? NullyFilled = NullyFilledText;
    private const string? Null = NullText;
    
    /// <inheritdoc cref="_coalesce3argssbtotext" />
    [TestMethod]
    public void Coalesce_3Args_SBToString_Extensions()
    {
        NoNullRet("",         NullSB       .Coalesce( NullSB,        Null       ));
        NoNullRet("",         NullSB       .Coalesce( NullSB,        Empty      ));
        NoNullRet(" ",        NullSB       .Coalesce( NullSB,        Space      ));
        NoNullRet(Text,       NullSB       .Coalesce( NullSB,        Text       ));
        NoNullRet("",         NullSB       .Coalesce( NullSB,        NullyEmpty ));
        NoNullRet(" ",        NullSB       .Coalesce( NullSB,        NullySpace ));
        NoNullRet(Text,       NullSB       .Coalesce( NullSB,        NullyFilled));
        NoNullRet("",         NullSB       .Coalesce( NullyEmptySB,  Null       ));
        NoNullRet("",         NullSB       .Coalesce( NullyEmptySB,  Empty      ));
        NoNullRet(" ",        NullSB       .Coalesce( NullyEmptySB,  Space      ));
        NoNullRet(Text,       NullSB       .Coalesce( NullyEmptySB,  Text       ));
        NoNullRet("",         NullSB       .Coalesce( NullyEmptySB,  NullyEmpty ));
        NoNullRet(" ",        NullSB       .Coalesce( NullyEmptySB,  NullySpace ));
        NoNullRet(Text,       NullSB       .Coalesce( NullyEmptySB,  NullyFilled));
        NoNullRet("",         NullSB       .Coalesce( NullySpaceSB,  Null       ));
        NoNullRet("",         NullSB       .Coalesce( NullySpaceSB,  Empty      ));
        NoNullRet(" ",        NullSB       .Coalesce( NullySpaceSB,  Space      ));
        NoNullRet(Text,       NullSB       .Coalesce( NullySpaceSB,  Text       ));
        NoNullRet("",         NullSB       .Coalesce( NullySpaceSB,  NullyEmpty ));
        NoNullRet(" ",        NullSB       .Coalesce( NullySpaceSB,  NullySpace ));
        NoNullRet(Text,       NullSB       .Coalesce( NullySpaceSB,  NullyFilled));
        NoNullRet("FilledSB", NullSB       .Coalesce( NullyFilledSB, Null       ));
        NoNullRet("FilledSB", NullSB       .Coalesce( NullyFilledSB, Empty      ));
        NoNullRet("FilledSB", NullSB       .Coalesce( NullyFilledSB, Space      ));
        NoNullRet("FilledSB", NullSB       .Coalesce( NullyFilledSB, Text       ));
        NoNullRet("FilledSB", NullSB       .Coalesce( NullyFilledSB, NullyEmpty ));
        NoNullRet("FilledSB", NullSB       .Coalesce( NullyFilledSB, NullySpace ));
        NoNullRet("FilledSB", NullSB       .Coalesce( NullyFilledSB, NullyFilled));
        NoNullRet("",         NullSB       .Coalesce( EmptySB,       Null       ));
        NoNullRet("",         NullSB       .Coalesce( EmptySB,       Empty      ));
        NoNullRet(" ",        NullSB       .Coalesce( EmptySB,       Space      ));
        NoNullRet(Text,       NullSB       .Coalesce( EmptySB,       Text       ));
        NoNullRet("",         NullSB       .Coalesce( EmptySB,       NullyEmpty ));
        NoNullRet(" ",        NullSB       .Coalesce( EmptySB,       NullySpace ));
        NoNullRet(Text,       NullSB       .Coalesce( EmptySB,       NullyFilled));
        NoNullRet("",         NullSB       .Coalesce( SpaceSB,       Null       ));
        NoNullRet("",         NullSB       .Coalesce( SpaceSB,       Empty      ));
        NoNullRet(" ",        NullSB       .Coalesce( SpaceSB,       Space      ));
        NoNullRet(Text,       NullSB       .Coalesce( SpaceSB,       Text       ));
        NoNullRet("",         NullSB       .Coalesce( SpaceSB,       NullyEmpty ));
        NoNullRet(" ",        NullSB       .Coalesce( SpaceSB,       NullySpace ));
        NoNullRet(Text,       NullSB       .Coalesce( SpaceSB,       NullyFilled));
        NoNullRet("FilledSB", NullSB       .Coalesce( FilledSB,      Null       ));
        NoNullRet("FilledSB", NullSB       .Coalesce( FilledSB,      Empty      ));
        NoNullRet("FilledSB", NullSB       .Coalesce( FilledSB,      Space      ));
        NoNullRet("FilledSB", NullSB       .Coalesce( FilledSB,      Text       ));
        NoNullRet("FilledSB", NullSB       .Coalesce( FilledSB,      NullyEmpty ));
        NoNullRet("FilledSB", NullSB       .Coalesce( FilledSB,      NullySpace ));
        NoNullRet("FilledSB", NullSB       .Coalesce( FilledSB,      NullyFilled));
                                                      
        NoNullRet("",         NullyEmptySB .Coalesce( NullSB,        Null       ));
        NoNullRet("",         NullyEmptySB .Coalesce( NullSB,        Empty      ));
        NoNullRet(" ",        NullyEmptySB .Coalesce( NullSB,        Space      ));
        NoNullRet(Text,       NullyEmptySB .Coalesce( NullSB,        Text       ));
        NoNullRet("",         NullyEmptySB .Coalesce( NullSB,        NullyEmpty ));
        NoNullRet(" ",        NullyEmptySB .Coalesce( NullSB,        NullySpace ));
        NoNullRet(Text,       NullyEmptySB .Coalesce( NullSB,        NullyFilled));
        NoNullRet("",         NullyEmptySB .Coalesce( NullyEmptySB,  Null       ));
        NoNullRet("",         NullyEmptySB .Coalesce( NullyEmptySB,  Empty      ));
        NoNullRet(" ",        NullyEmptySB .Coalesce( NullyEmptySB,  Space      ));
        NoNullRet(Text,       NullyEmptySB .Coalesce( NullyEmptySB,  Text       ));
        NoNullRet("",         NullyEmptySB .Coalesce( NullyEmptySB,  NullyEmpty ));
        NoNullRet(" ",        NullyEmptySB .Coalesce( NullyEmptySB,  NullySpace ));
        NoNullRet(Text,       NullyEmptySB .Coalesce( NullyEmptySB,  NullyFilled));
        NoNullRet("",         NullyEmptySB .Coalesce( NullySpaceSB,  Null       ));
        NoNullRet("",         NullyEmptySB .Coalesce( NullySpaceSB,  Empty      ));
        NoNullRet(" ",        NullyEmptySB .Coalesce( NullySpaceSB,  Space      ));
        NoNullRet(Text,       NullyEmptySB .Coalesce( NullySpaceSB,  Text       ));
        NoNullRet("",         NullyEmptySB .Coalesce( NullySpaceSB,  NullyEmpty ));
        NoNullRet(" ",        NullyEmptySB .Coalesce( NullySpaceSB,  NullySpace ));
        NoNullRet(Text,       NullyEmptySB .Coalesce( NullySpaceSB,  NullyFilled));
        NoNullRet("FilledSB", NullyEmptySB .Coalesce( NullyFilledSB, Null       ));
        NoNullRet("FilledSB", NullyEmptySB .Coalesce( NullyFilledSB, Empty      ));
        NoNullRet("FilledSB", NullyEmptySB .Coalesce( NullyFilledSB, Space      ));
        NoNullRet("FilledSB", NullyEmptySB .Coalesce( NullyFilledSB, Text       ));
        NoNullRet("FilledSB", NullyEmptySB .Coalesce( NullyFilledSB, NullyEmpty ));
        NoNullRet("FilledSB", NullyEmptySB .Coalesce( NullyFilledSB, NullySpace ));
        NoNullRet("FilledSB", NullyEmptySB .Coalesce( NullyFilledSB, NullyFilled));
        NoNullRet("",         NullyEmptySB .Coalesce( EmptySB,       Null       ));
        NoNullRet("",         NullyEmptySB .Coalesce( EmptySB,       Empty      ));
        NoNullRet(" ",        NullyEmptySB .Coalesce( EmptySB,       Space      ));
        NoNullRet(Text,       NullyEmptySB .Coalesce( EmptySB,       Text       ));
        NoNullRet("",         NullyEmptySB .Coalesce( EmptySB,       NullyEmpty ));
        NoNullRet(" ",        NullyEmptySB .Coalesce( EmptySB,       NullySpace ));
        NoNullRet(Text,       NullyEmptySB .Coalesce( EmptySB,       NullyFilled));
        NoNullRet("",         NullyEmptySB .Coalesce( SpaceSB,       Null       ));
        NoNullRet("",         NullyEmptySB .Coalesce( SpaceSB,       Empty      ));
        NoNullRet(" ",        NullyEmptySB .Coalesce( SpaceSB,       Space      ));
        NoNullRet(Text,       NullyEmptySB .Coalesce( SpaceSB,       Text       ));
        NoNullRet("",         NullyEmptySB .Coalesce( SpaceSB,       NullyEmpty ));
        NoNullRet(" ",        NullyEmptySB .Coalesce( SpaceSB,       NullySpace ));
        NoNullRet(Text,       NullyEmptySB .Coalesce( SpaceSB,       NullyFilled));
        NoNullRet("FilledSB", NullyEmptySB .Coalesce( FilledSB,      Null       ));
        NoNullRet("FilledSB", NullyEmptySB .Coalesce( FilledSB,      Empty      ));
        NoNullRet("FilledSB", NullyEmptySB .Coalesce( FilledSB,      Space      ));
        NoNullRet("FilledSB", NullyEmptySB .Coalesce( FilledSB,      Text       ));
        NoNullRet("FilledSB", NullyEmptySB .Coalesce( FilledSB,      NullyEmpty ));
        NoNullRet("FilledSB", NullyEmptySB .Coalesce( FilledSB,      NullySpace ));
        NoNullRet("FilledSB", NullyEmptySB .Coalesce( FilledSB,      NullyFilled));
                                                      
        NoNullRet("",         NullySpaceSB .Coalesce( NullSB,        Null       ));
        NoNullRet("",         NullySpaceSB .Coalesce( NullSB,        Empty      ));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullSB,        Space      ));
        NoNullRet(Text,       NullySpaceSB .Coalesce( NullSB,        Text       ));
        NoNullRet("",         NullySpaceSB .Coalesce( NullSB,        NullyEmpty ));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullSB,        NullySpace ));
        NoNullRet(Text,       NullySpaceSB .Coalesce( NullSB,        NullyFilled));
        NoNullRet("",         NullySpaceSB .Coalesce( NullyEmptySB,  Null       ));
        NoNullRet("",         NullySpaceSB .Coalesce( NullyEmptySB,  Empty      ));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullyEmptySB,  Space      ));
        NoNullRet(Text,       NullySpaceSB .Coalesce( NullyEmptySB,  Text       ));
        NoNullRet("",         NullySpaceSB .Coalesce( NullyEmptySB,  NullyEmpty ));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullyEmptySB,  NullySpace ));
        NoNullRet(Text,       NullySpaceSB .Coalesce( NullyEmptySB,  NullyFilled));
        NoNullRet("",         NullySpaceSB .Coalesce( NullySpaceSB,  Null       ));
        NoNullRet("",         NullySpaceSB .Coalesce( NullySpaceSB,  Empty      ));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullySpaceSB,  Space      ));
        NoNullRet(Text,       NullySpaceSB .Coalesce( NullySpaceSB,  Text       ));
        NoNullRet("",         NullySpaceSB .Coalesce( NullySpaceSB,  NullyEmpty ));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullySpaceSB,  NullySpace ));
        NoNullRet(Text,       NullySpaceSB .Coalesce( NullySpaceSB,  NullyFilled));
        NoNullRet("FilledSB", NullySpaceSB .Coalesce( NullyFilledSB, Null       ));
        NoNullRet("FilledSB", NullySpaceSB .Coalesce( NullyFilledSB, Empty      ));
        NoNullRet("FilledSB", NullySpaceSB .Coalesce( NullyFilledSB, Space      ));
        NoNullRet("FilledSB", NullySpaceSB .Coalesce( NullyFilledSB, Text       ));
        NoNullRet("FilledSB", NullySpaceSB .Coalesce( NullyFilledSB, NullyEmpty ));
        NoNullRet("FilledSB", NullySpaceSB .Coalesce( NullyFilledSB, NullySpace ));
        NoNullRet("FilledSB", NullySpaceSB .Coalesce( NullyFilledSB, NullyFilled));
        NoNullRet("",         NullySpaceSB .Coalesce( EmptySB,       Null       ));
        NoNullRet("",         NullySpaceSB .Coalesce( EmptySB,       Empty      ));
        NoNullRet(" ",        NullySpaceSB .Coalesce( EmptySB,       Space      ));
        NoNullRet(Text,       NullySpaceSB .Coalesce( EmptySB,       Text       ));
        NoNullRet("",         NullySpaceSB .Coalesce( EmptySB,       NullyEmpty ));
        NoNullRet(" ",        NullySpaceSB .Coalesce( EmptySB,       NullySpace ));
        NoNullRet(Text,       NullySpaceSB .Coalesce( EmptySB,       NullyFilled));
        NoNullRet("",         NullySpaceSB .Coalesce( SpaceSB,       Null       ));
        NoNullRet("",         NullySpaceSB .Coalesce( SpaceSB,       Empty      ));
        NoNullRet(" ",        NullySpaceSB .Coalesce( SpaceSB,       Space      ));
        NoNullRet(Text,       NullySpaceSB .Coalesce( SpaceSB,       Text       ));
        NoNullRet("",         NullySpaceSB .Coalesce( SpaceSB,       NullyEmpty ));
        NoNullRet(" ",        NullySpaceSB .Coalesce( SpaceSB,       NullySpace ));
        NoNullRet(Text,       NullySpaceSB .Coalesce( SpaceSB,       NullyFilled));
        NoNullRet("FilledSB", NullySpaceSB .Coalesce( FilledSB,      Null       ));
        NoNullRet("FilledSB", NullySpaceSB .Coalesce( FilledSB,      Empty      ));
        NoNullRet("FilledSB", NullySpaceSB .Coalesce( FilledSB,      Space      ));
        NoNullRet("FilledSB", NullySpaceSB .Coalesce( FilledSB,      Text       ));
        NoNullRet("FilledSB", NullySpaceSB .Coalesce( FilledSB,      NullyEmpty ));
        NoNullRet("FilledSB", NullySpaceSB .Coalesce( FilledSB,      NullySpace ));
        NoNullRet("FilledSB", NullySpaceSB .Coalesce( FilledSB,      NullyFilled));
                                                      
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullSB,        Null       ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullSB,        Empty      ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullSB,        Space      ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullSB,        Text       ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullSB,        NullyEmpty ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullSB,        NullySpace ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullSB,        NullyFilled));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyEmptySB,  Null       ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyEmptySB,  Empty      ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyEmptySB,  Space      ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyEmptySB,  Text       ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyEmptySB,  NullyEmpty ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyEmptySB,  NullySpace ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyEmptySB,  NullyFilled));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullySpaceSB,  Null       ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullySpaceSB,  Empty      ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullySpaceSB,  Space      ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullySpaceSB,  Text       ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullySpaceSB,  NullyEmpty ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullySpaceSB,  NullySpace ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullySpaceSB,  NullyFilled));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyFilledSB, Null       ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyFilledSB, Empty      ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyFilledSB, Space      ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyFilledSB, Text       ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyFilledSB, NullyEmpty ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyFilledSB, NullySpace ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyFilledSB, NullyFilled));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( EmptySB,       Null       ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( EmptySB,       Empty      ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( EmptySB,       Space      ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( EmptySB,       Text       ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( EmptySB,       NullyEmpty ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( EmptySB,       NullySpace ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( EmptySB,       NullyFilled));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( SpaceSB,       Null       ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( SpaceSB,       Empty      ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( SpaceSB,       Space      ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( SpaceSB,       Text       ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( SpaceSB,       NullyEmpty ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( SpaceSB,       NullySpace ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( SpaceSB,       NullyFilled));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( FilledSB,      Null       ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( FilledSB,      Empty      ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( FilledSB,      Space      ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( FilledSB,      Text       ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( FilledSB,      NullyEmpty ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( FilledSB,      NullySpace ));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( FilledSB,      NullyFilled));
                                                      
        NoNullRet("",         EmptySB      .Coalesce( NullSB,        Null       ));
        NoNullRet("",         EmptySB      .Coalesce( NullSB,        Empty      ));
        NoNullRet(" ",        EmptySB      .Coalesce( NullSB,        Space      ));
        NoNullRet(Text,       EmptySB      .Coalesce( NullSB,        Text       ));
        NoNullRet("",         EmptySB      .Coalesce( NullSB,        NullyEmpty ));
        NoNullRet(" ",        EmptySB      .Coalesce( NullSB,        NullySpace ));
        NoNullRet(Text,       EmptySB      .Coalesce( NullSB,        NullyFilled));
        NoNullRet("",         EmptySB      .Coalesce( NullyEmptySB,  Null       ));
        NoNullRet("",         EmptySB      .Coalesce( NullyEmptySB,  Empty      ));
        NoNullRet(" ",        EmptySB      .Coalesce( NullyEmptySB,  Space      ));
        NoNullRet(Text,       EmptySB      .Coalesce( NullyEmptySB,  Text       ));
        NoNullRet("",         EmptySB      .Coalesce( NullyEmptySB,  NullyEmpty ));
        NoNullRet(" ",        EmptySB      .Coalesce( NullyEmptySB,  NullySpace ));
        NoNullRet(Text,       EmptySB      .Coalesce( NullyEmptySB,  NullyFilled));
        NoNullRet("",         EmptySB      .Coalesce( NullySpaceSB,  Null       ));
        NoNullRet("",         EmptySB      .Coalesce( NullySpaceSB,  Empty      ));
        NoNullRet(" ",        EmptySB      .Coalesce( NullySpaceSB,  Space      ));
        NoNullRet(Text,       EmptySB      .Coalesce( NullySpaceSB,  Text       ));
        NoNullRet("",         EmptySB      .Coalesce( NullySpaceSB,  NullyEmpty ));
        NoNullRet(" ",        EmptySB      .Coalesce( NullySpaceSB,  NullySpace ));
        NoNullRet(Text,       EmptySB      .Coalesce( NullySpaceSB,  NullyFilled));
        NoNullRet("FilledSB", EmptySB      .Coalesce( NullyFilledSB, Null       ));
        NoNullRet("FilledSB", EmptySB      .Coalesce( NullyFilledSB, Empty      ));
        NoNullRet("FilledSB", EmptySB      .Coalesce( NullyFilledSB, Space      ));
        NoNullRet("FilledSB", EmptySB      .Coalesce( NullyFilledSB, Text       ));
        NoNullRet("FilledSB", EmptySB      .Coalesce( NullyFilledSB, NullyEmpty ));
        NoNullRet("FilledSB", EmptySB      .Coalesce( NullyFilledSB, NullySpace ));
        NoNullRet("FilledSB", EmptySB      .Coalesce( NullyFilledSB, NullyFilled));
        NoNullRet("",         EmptySB      .Coalesce( EmptySB,       Null       ));
        NoNullRet("",         EmptySB      .Coalesce( EmptySB,       Empty      ));
        NoNullRet(" ",        EmptySB      .Coalesce( EmptySB,       Space      ));
        NoNullRet(Text,       EmptySB      .Coalesce( EmptySB,       Text       ));
        NoNullRet("",         EmptySB      .Coalesce( EmptySB,       NullyEmpty ));
        NoNullRet(" ",        EmptySB      .Coalesce( EmptySB,       NullySpace ));
        NoNullRet(Text,       EmptySB      .Coalesce( EmptySB,       NullyFilled));
        NoNullRet("",         EmptySB      .Coalesce( SpaceSB,       Null       ));
        NoNullRet("",         EmptySB      .Coalesce( SpaceSB,       Empty      ));
        NoNullRet(" ",        EmptySB      .Coalesce( SpaceSB,       Space      ));
        NoNullRet(Text,       EmptySB      .Coalesce( SpaceSB,       Text       ));
        NoNullRet("",         EmptySB      .Coalesce( SpaceSB,       NullyEmpty ));
        NoNullRet(" ",        EmptySB      .Coalesce( SpaceSB,       NullySpace ));
        NoNullRet(Text,       EmptySB      .Coalesce( SpaceSB,       NullyFilled));
        NoNullRet("FilledSB", EmptySB      .Coalesce( FilledSB,      Null       ));
        NoNullRet("FilledSB", EmptySB      .Coalesce( FilledSB,      Empty      ));
        NoNullRet("FilledSB", EmptySB      .Coalesce( FilledSB,      Space      ));
        NoNullRet("FilledSB", EmptySB      .Coalesce( FilledSB,      Text       ));
        NoNullRet("FilledSB", EmptySB      .Coalesce( FilledSB,      NullyEmpty ));
        NoNullRet("FilledSB", EmptySB      .Coalesce( FilledSB,      NullySpace ));
        NoNullRet("FilledSB", EmptySB      .Coalesce( FilledSB,      NullyFilled));
        
        NoNullRet("",         SpaceSB      .Coalesce( NullSB,        Null       ));
        NoNullRet("",         SpaceSB      .Coalesce( NullSB,        Empty      ));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullSB,        Space      ));
        NoNullRet(Text,       SpaceSB      .Coalesce( NullSB,        Text       ));
        NoNullRet("",         SpaceSB      .Coalesce( NullSB,        NullyEmpty ));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullSB,        NullySpace ));
        NoNullRet(Text,       SpaceSB      .Coalesce( NullSB,        NullyFilled));
        NoNullRet("",         SpaceSB      .Coalesce( NullyEmptySB,  Null       ));
        NoNullRet("",         SpaceSB      .Coalesce( NullyEmptySB,  Empty      ));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullyEmptySB,  Space      ));
        NoNullRet(Text,       SpaceSB      .Coalesce( NullyEmptySB,  Text       ));
        NoNullRet("",         SpaceSB      .Coalesce( NullyEmptySB,  NullyEmpty ));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullyEmptySB,  NullySpace ));
        NoNullRet(Text,       SpaceSB      .Coalesce( NullyEmptySB,  NullyFilled));
        NoNullRet("",         SpaceSB      .Coalesce( NullySpaceSB,  Null       ));
        NoNullRet("",         SpaceSB      .Coalesce( NullySpaceSB,  Empty      ));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullySpaceSB,  Space      ));
        NoNullRet(Text,       SpaceSB      .Coalesce( NullySpaceSB,  Text       ));
        NoNullRet("",         SpaceSB      .Coalesce( NullySpaceSB,  NullyEmpty ));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullySpaceSB,  NullySpace ));
        NoNullRet(Text,       SpaceSB      .Coalesce( NullySpaceSB,  NullyFilled));
        NoNullRet("FilledSB", SpaceSB      .Coalesce( NullyFilledSB, Null       ));
        NoNullRet("FilledSB", SpaceSB      .Coalesce( NullyFilledSB, Empty      ));
        NoNullRet("FilledSB", SpaceSB      .Coalesce( NullyFilledSB, Space      ));
        NoNullRet("FilledSB", SpaceSB      .Coalesce( NullyFilledSB, Text       ));
        NoNullRet("FilledSB", SpaceSB      .Coalesce( NullyFilledSB, NullyEmpty ));
        NoNullRet("FilledSB", SpaceSB      .Coalesce( NullyFilledSB, NullySpace ));
        NoNullRet("FilledSB", SpaceSB      .Coalesce( NullyFilledSB, NullyFilled));
        NoNullRet("",         SpaceSB      .Coalesce( EmptySB,       Null       ));
        NoNullRet("",         SpaceSB      .Coalesce( EmptySB,       Empty      ));
        NoNullRet(" ",        SpaceSB      .Coalesce( EmptySB,       Space      ));
        NoNullRet(Text,       SpaceSB      .Coalesce( EmptySB,       Text       ));
        NoNullRet("",         SpaceSB      .Coalesce( EmptySB,       NullyEmpty ));
        NoNullRet(" ",        SpaceSB      .Coalesce( EmptySB,       NullySpace ));
        NoNullRet(Text,       SpaceSB      .Coalesce( EmptySB,       NullyFilled));
        NoNullRet("",         SpaceSB      .Coalesce( SpaceSB,       Null       ));
        NoNullRet("",         SpaceSB      .Coalesce( SpaceSB,       Empty      ));
        NoNullRet(" ",        SpaceSB      .Coalesce( SpaceSB,       Space      ));
        NoNullRet(Text,       SpaceSB      .Coalesce( SpaceSB,       Text       ));
        NoNullRet("",         SpaceSB      .Coalesce( SpaceSB,       NullyEmpty ));
        NoNullRet(" ",        SpaceSB      .Coalesce( SpaceSB,       NullySpace ));
        NoNullRet(Text,       SpaceSB      .Coalesce( SpaceSB,       NullyFilled));
        NoNullRet("FilledSB", SpaceSB      .Coalesce( FilledSB,      Null       ));
        NoNullRet("FilledSB", SpaceSB      .Coalesce( FilledSB,      Empty      ));
        NoNullRet("FilledSB", SpaceSB      .Coalesce( FilledSB,      Space      ));
        NoNullRet("FilledSB", SpaceSB      .Coalesce( FilledSB,      Text       ));
        NoNullRet("FilledSB", SpaceSB      .Coalesce( FilledSB,      NullyEmpty ));
        NoNullRet("FilledSB", SpaceSB      .Coalesce( FilledSB,      NullySpace ));
        NoNullRet("FilledSB", SpaceSB      .Coalesce( FilledSB,      NullyFilled));
                                                      
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullSB,        Null       ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullSB,        Empty      ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullSB,        Space      ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullSB,        Text       ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullSB,        NullyEmpty ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullSB,        NullySpace ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullSB,        NullyFilled));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyEmptySB,  Null       ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyEmptySB,  Empty      ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyEmptySB,  Space      ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyEmptySB,  Text       ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyEmptySB,  NullyEmpty ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyEmptySB,  NullySpace ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyEmptySB,  NullyFilled));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullySpaceSB,  Null       ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullySpaceSB,  Empty      ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullySpaceSB,  Space      ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullySpaceSB,  Text       ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullySpaceSB,  NullyEmpty ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullySpaceSB,  NullySpace ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullySpaceSB,  NullyFilled));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyFilledSB, Null       ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyFilledSB, Empty      ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyFilledSB, Space      ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyFilledSB, Text       ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyFilledSB, NullyEmpty ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyFilledSB, NullySpace ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyFilledSB, NullyFilled));
        NoNullRet("FilledSB", FilledSB     .Coalesce( EmptySB,       Empty      ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( EmptySB,       Space      ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( EmptySB,       Text       ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( EmptySB,       NullyEmpty ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( EmptySB,       NullySpace ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( EmptySB,       NullyFilled));
        NoNullRet("FilledSB", FilledSB     .Coalesce( SpaceSB,       Empty      ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( SpaceSB,       Space      ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( SpaceSB,       Text       ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( SpaceSB,       NullyEmpty ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( SpaceSB,       NullySpace ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( SpaceSB,       NullyFilled));
        NoNullRet("FilledSB", FilledSB     .Coalesce( FilledSB,      Null       ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( FilledSB,      Empty      ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( FilledSB,      Space      ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( FilledSB,      Text       ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( FilledSB,      NullyEmpty ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( FilledSB,      NullySpace ));
        NoNullRet("FilledSB", FilledSB     .Coalesce( FilledSB,      NullyFilled));
    }

    /// <inheritdoc cref="_coalesce3argssbtotext" />
    [TestMethod]
    public void Coalesce_3Args_SBToString_Extensions_SpaceMatters_MagicBool()
    {
        NoNullRet("",         NullSB       .Coalesce( NullSB,        Null,        spaceMatters));
        NoNullRet("",         NullSB       .Coalesce( NullSB,        Empty,       spaceMatters));
        NoNullRet(" ",        NullSB       .Coalesce( NullSB,        Space,       spaceMatters));
        NoNullRet(Text,       NullSB       .Coalesce( NullSB,        Text,        spaceMatters));
        NoNullRet("",         NullSB       .Coalesce( NullSB,        NullyEmpty,  spaceMatters));
        NoNullRet(" ",        NullSB       .Coalesce( NullSB,        NullySpace,  spaceMatters));
        NoNullRet(Text,       NullSB       .Coalesce( NullSB,        NullyFilled, spaceMatters));
        NoNullRet("",         NullSB       .Coalesce( NullyEmptySB,  Null,        spaceMatters));
        NoNullRet("",         NullSB       .Coalesce( NullyEmptySB,  Empty,       spaceMatters));
        NoNullRet(" ",        NullSB       .Coalesce( NullyEmptySB,  Space,       spaceMatters));
        NoNullRet(Text,       NullSB       .Coalesce( NullyEmptySB,  Text,        spaceMatters));
        NoNullRet("",         NullSB       .Coalesce( NullyEmptySB,  NullyEmpty,  spaceMatters));
        NoNullRet(" ",        NullSB       .Coalesce( NullyEmptySB,  NullySpace,  spaceMatters));
        NoNullRet(Text,       NullSB       .Coalesce( NullyEmptySB,  NullyFilled, spaceMatters));
        NoNullRet(" ",        NullSB       .Coalesce( NullySpaceSB,  Null,        spaceMatters));
        NoNullRet(" ",        NullSB       .Coalesce( NullySpaceSB,  Empty,       spaceMatters));
        NoNullRet(" ",        NullSB       .Coalesce( NullySpaceSB,  Space,       spaceMatters));
        NoNullRet(" ",        NullSB       .Coalesce( NullySpaceSB,  Text,        spaceMatters));
        NoNullRet(" ",        NullSB       .Coalesce( NullySpaceSB,  NullyEmpty,  spaceMatters));
        NoNullRet(" ",        NullSB       .Coalesce( NullySpaceSB,  NullySpace,  spaceMatters));
        NoNullRet(" ",        NullSB       .Coalesce( NullySpaceSB,  NullyFilled, spaceMatters));
        NoNullRet("FilledSB", NullSB       .Coalesce( NullyFilledSB, Null,        spaceMatters));
        NoNullRet("FilledSB", NullSB       .Coalesce( NullyFilledSB, Empty,       spaceMatters));
        NoNullRet("FilledSB", NullSB       .Coalesce( NullyFilledSB, Space,       spaceMatters));
        NoNullRet("FilledSB", NullSB       .Coalesce( NullyFilledSB, Text,        spaceMatters));
        NoNullRet("FilledSB", NullSB       .Coalesce( NullyFilledSB, NullyEmpty,  spaceMatters));
        NoNullRet("FilledSB", NullSB       .Coalesce( NullyFilledSB, NullySpace,  spaceMatters));
        NoNullRet("FilledSB", NullSB       .Coalesce( NullyFilledSB, NullyFilled, spaceMatters));
        NoNullRet("",         NullSB       .Coalesce( EmptySB,       Null,        spaceMatters));
        NoNullRet("",         NullSB       .Coalesce( EmptySB,       Empty,       spaceMatters));
        NoNullRet(" ",        NullSB       .Coalesce( EmptySB,       Space,       spaceMatters));
        NoNullRet(Text,       NullSB       .Coalesce( EmptySB,       Text,        spaceMatters));
        NoNullRet("",         NullSB       .Coalesce( EmptySB,       NullyEmpty,  spaceMatters));
        NoNullRet(" ",        NullSB       .Coalesce( EmptySB,       NullySpace,  spaceMatters));
        NoNullRet(Text,       NullSB       .Coalesce( EmptySB,       NullyFilled, spaceMatters));
        NoNullRet(" ",        NullSB       .Coalesce( SpaceSB,       Null,        spaceMatters));
        NoNullRet(" ",        NullSB       .Coalesce( SpaceSB,       Empty,       spaceMatters));
        NoNullRet(" ",        NullSB       .Coalesce( SpaceSB,       Space,       spaceMatters));
        NoNullRet(" ",        NullSB       .Coalesce( SpaceSB,       Text,        spaceMatters));
        NoNullRet(" ",        NullSB       .Coalesce( SpaceSB,       NullyEmpty,  spaceMatters));
        NoNullRet(" ",        NullSB       .Coalesce( SpaceSB,       NullySpace,  spaceMatters));
        NoNullRet(" ",        NullSB       .Coalesce( SpaceSB,       NullyFilled, spaceMatters));
        NoNullRet("FilledSB", NullSB       .Coalesce( FilledSB,      Null,        spaceMatters));
        NoNullRet("FilledSB", NullSB       .Coalesce( FilledSB,      Empty,       spaceMatters));
        NoNullRet("FilledSB", NullSB       .Coalesce( FilledSB,      Space,       spaceMatters));
        NoNullRet("FilledSB", NullSB       .Coalesce( FilledSB,      Text,        spaceMatters));
        NoNullRet("FilledSB", NullSB       .Coalesce( FilledSB,      NullyEmpty,  spaceMatters));
        NoNullRet("FilledSB", NullSB       .Coalesce( FilledSB,      NullySpace,  spaceMatters));
        NoNullRet("FilledSB", NullSB       .Coalesce( FilledSB,      NullyFilled, spaceMatters));
                                                      
        NoNullRet("",         NullyEmptySB .Coalesce( NullSB,        Null,        spaceMatters));
        NoNullRet("",         NullyEmptySB .Coalesce( NullSB,        Empty,       spaceMatters));
        NoNullRet(" ",        NullyEmptySB .Coalesce( NullSB,        Space,       spaceMatters));
        NoNullRet(Text,       NullyEmptySB .Coalesce( NullSB,        Text,        spaceMatters));
        NoNullRet("",         NullyEmptySB .Coalesce( NullSB,        NullyEmpty,  spaceMatters));
        NoNullRet(" ",        NullyEmptySB .Coalesce( NullSB,        NullySpace,  spaceMatters));
        NoNullRet(Text,       NullyEmptySB .Coalesce( NullSB,        NullyFilled, spaceMatters));
        NoNullRet("",         NullyEmptySB .Coalesce( NullyEmptySB,  Null,        spaceMatters));
        NoNullRet("",         NullyEmptySB .Coalesce( NullyEmptySB,  Empty,       spaceMatters));
        NoNullRet(" ",        NullyEmptySB .Coalesce( NullyEmptySB,  Space,       spaceMatters));
        NoNullRet(Text,       NullyEmptySB .Coalesce( NullyEmptySB,  Text,        spaceMatters));
        NoNullRet("",         NullyEmptySB .Coalesce( NullyEmptySB,  NullyEmpty,  spaceMatters));
        NoNullRet(" ",        NullyEmptySB .Coalesce( NullyEmptySB,  NullySpace,  spaceMatters));
        NoNullRet(Text,       NullyEmptySB .Coalesce( NullyEmptySB,  NullyFilled, spaceMatters));
        NoNullRet(" ",        NullyEmptySB .Coalesce( NullySpaceSB,  Null,        spaceMatters));
        NoNullRet(" ",        NullyEmptySB .Coalesce( NullySpaceSB,  Empty,       spaceMatters));
        NoNullRet(" ",        NullyEmptySB .Coalesce( NullySpaceSB,  Space,       spaceMatters));
        NoNullRet(" ",        NullyEmptySB .Coalesce( NullySpaceSB,  Text,        spaceMatters));
        NoNullRet(" ",        NullyEmptySB .Coalesce( NullySpaceSB,  NullyEmpty,  spaceMatters));
        NoNullRet(" ",        NullyEmptySB .Coalesce( NullySpaceSB,  NullySpace,  spaceMatters));
        NoNullRet(" ",        NullyEmptySB .Coalesce( NullySpaceSB,  NullyFilled, spaceMatters));
        NoNullRet("FilledSB", NullyEmptySB .Coalesce( NullyFilledSB, Null,        spaceMatters));
        NoNullRet("FilledSB", NullyEmptySB .Coalesce( NullyFilledSB, Empty,       spaceMatters));
        NoNullRet("FilledSB", NullyEmptySB .Coalesce( NullyFilledSB, Space,       spaceMatters));
        NoNullRet("FilledSB", NullyEmptySB .Coalesce( NullyFilledSB, Text,        spaceMatters));
        NoNullRet("FilledSB", NullyEmptySB .Coalesce( NullyFilledSB, NullyEmpty,  spaceMatters));
        NoNullRet("FilledSB", NullyEmptySB .Coalesce( NullyFilledSB, NullySpace,  spaceMatters));
        NoNullRet("FilledSB", NullyEmptySB .Coalesce( NullyFilledSB, NullyFilled, spaceMatters));
        NoNullRet("",         NullyEmptySB .Coalesce( EmptySB,       Null,        spaceMatters));
        NoNullRet("",         NullyEmptySB .Coalesce( EmptySB,       Empty,       spaceMatters));
        NoNullRet(" ",        NullyEmptySB .Coalesce( EmptySB,       Space,       spaceMatters));
        NoNullRet(Text,       NullyEmptySB .Coalesce( EmptySB,       Text,        spaceMatters));
        NoNullRet("",         NullyEmptySB .Coalesce( EmptySB,       NullyEmpty,  spaceMatters));
        NoNullRet(" ",        NullyEmptySB .Coalesce( EmptySB,       NullySpace,  spaceMatters));
        NoNullRet(Text,       NullyEmptySB .Coalesce( EmptySB,       NullyFilled, spaceMatters));
        NoNullRet(" ",        NullyEmptySB .Coalesce( SpaceSB,       Null,        spaceMatters));
        NoNullRet(" ",        NullyEmptySB .Coalesce( SpaceSB,       Empty,       spaceMatters));
        NoNullRet(" ",        NullyEmptySB .Coalesce( SpaceSB,       Space,       spaceMatters));
        NoNullRet(" ",        NullyEmptySB .Coalesce( SpaceSB,       Text,        spaceMatters));
        NoNullRet(" ",        NullyEmptySB .Coalesce( SpaceSB,       NullyEmpty,  spaceMatters));
        NoNullRet(" ",        NullyEmptySB .Coalesce( SpaceSB,       NullySpace,  spaceMatters));
        NoNullRet(" ",        NullyEmptySB .Coalesce( SpaceSB,       NullyFilled, spaceMatters));
        NoNullRet("FilledSB", NullyEmptySB .Coalesce( FilledSB,      Null,        spaceMatters));
        NoNullRet("FilledSB", NullyEmptySB .Coalesce( FilledSB,      Empty,       spaceMatters));
        NoNullRet("FilledSB", NullyEmptySB .Coalesce( FilledSB,      Space,       spaceMatters));
        NoNullRet("FilledSB", NullyEmptySB .Coalesce( FilledSB,      Text,        spaceMatters));
        NoNullRet("FilledSB", NullyEmptySB .Coalesce( FilledSB,      NullyEmpty,  spaceMatters));
        NoNullRet("FilledSB", NullyEmptySB .Coalesce( FilledSB,      NullySpace,  spaceMatters));
        NoNullRet("FilledSB", NullyEmptySB .Coalesce( FilledSB,      NullyFilled, spaceMatters));
                                                      
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullSB,        Null,        spaceMatters));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullSB,        Empty,       spaceMatters));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullSB,        Space,       spaceMatters));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullSB,        Text,        spaceMatters));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullSB,        NullyEmpty,  spaceMatters));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullSB,        NullySpace,  spaceMatters));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullSB,        NullyFilled, spaceMatters));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullyEmptySB,  Null,        spaceMatters));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullyEmptySB,  Empty,       spaceMatters));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullyEmptySB,  Space,       spaceMatters));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullyEmptySB,  Text,        spaceMatters));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullyEmptySB,  NullyEmpty,  spaceMatters));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullyEmptySB,  NullySpace,  spaceMatters));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullyEmptySB,  NullyFilled, spaceMatters));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullySpaceSB,  Null,        spaceMatters));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullySpaceSB,  Empty,       spaceMatters));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullySpaceSB,  Space,       spaceMatters));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullySpaceSB,  Text,        spaceMatters));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullySpaceSB,  NullyEmpty,  spaceMatters));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullySpaceSB,  NullySpace,  spaceMatters));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullySpaceSB,  NullyFilled, spaceMatters));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullyFilledSB, Null,        spaceMatters));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullyFilledSB, Empty,       spaceMatters));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullyFilledSB, Space,       spaceMatters));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullyFilledSB, Text,        spaceMatters));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullyFilledSB, NullyEmpty,  spaceMatters));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullyFilledSB, NullySpace,  spaceMatters));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullyFilledSB, NullyFilled, spaceMatters));
        NoNullRet(" ",        NullySpaceSB .Coalesce( EmptySB,       Null,        spaceMatters));
        NoNullRet(" ",        NullySpaceSB .Coalesce( EmptySB,       Empty,       spaceMatters));
        NoNullRet(" ",        NullySpaceSB .Coalesce( EmptySB,       Space,       spaceMatters));
        NoNullRet(" ",        NullySpaceSB .Coalesce( EmptySB,       Text,        spaceMatters));
        NoNullRet(" ",        NullySpaceSB .Coalesce( EmptySB,       NullyEmpty,  spaceMatters));
        NoNullRet(" ",        NullySpaceSB .Coalesce( EmptySB,       NullySpace,  spaceMatters));
        NoNullRet(" ",        NullySpaceSB .Coalesce( EmptySB,       NullyFilled, spaceMatters));
        NoNullRet(" ",        NullySpaceSB .Coalesce( SpaceSB,       Null,        spaceMatters));
        NoNullRet(" ",        NullySpaceSB .Coalesce( SpaceSB,       Empty,       spaceMatters));
        NoNullRet(" ",        NullySpaceSB .Coalesce( SpaceSB,       Space,       spaceMatters));
        NoNullRet(" ",        NullySpaceSB .Coalesce( SpaceSB,       Text,        spaceMatters));
        NoNullRet(" ",        NullySpaceSB .Coalesce( SpaceSB,       NullyEmpty,  spaceMatters));
        NoNullRet(" ",        NullySpaceSB .Coalesce( SpaceSB,       NullySpace,  spaceMatters));
        NoNullRet(" ",        NullySpaceSB .Coalesce( SpaceSB,       NullyFilled, spaceMatters));
        NoNullRet(" ",        NullySpaceSB .Coalesce( FilledSB,      Null,        spaceMatters));
        NoNullRet(" ",        NullySpaceSB .Coalesce( FilledSB,      Empty,       spaceMatters));
        NoNullRet(" ",        NullySpaceSB .Coalesce( FilledSB,      Space,       spaceMatters));
        NoNullRet(" ",        NullySpaceSB .Coalesce( FilledSB,      Text,        spaceMatters));
        NoNullRet(" ",        NullySpaceSB .Coalesce( FilledSB,      NullyEmpty,  spaceMatters));
        NoNullRet(" ",        NullySpaceSB .Coalesce( FilledSB,      NullySpace,  spaceMatters));
        NoNullRet(" ",        NullySpaceSB .Coalesce( FilledSB,      NullyFilled, spaceMatters));
                                                      
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullSB,        Null,        spaceMatters));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullSB,        Empty,       spaceMatters));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullSB,        Space,       spaceMatters));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullSB,        Text,        spaceMatters));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullSB,        NullyEmpty,  spaceMatters));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullSB,        NullySpace,  spaceMatters));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullSB,        NullyFilled, spaceMatters));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyEmptySB,  Null,        spaceMatters));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyEmptySB,  Empty,       spaceMatters));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyEmptySB,  Space,       spaceMatters));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyEmptySB,  Text,        spaceMatters));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyEmptySB,  NullyEmpty,  spaceMatters));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyEmptySB,  NullySpace,  spaceMatters));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyEmptySB,  NullyFilled, spaceMatters));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullySpaceSB,  Null,        spaceMatters));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullySpaceSB,  Empty,       spaceMatters));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullySpaceSB,  Space,       spaceMatters));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullySpaceSB,  Text,        spaceMatters));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullySpaceSB,  NullyEmpty,  spaceMatters));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullySpaceSB,  NullySpace,  spaceMatters));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullySpaceSB,  NullyFilled, spaceMatters));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyFilledSB, Null,        spaceMatters));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyFilledSB, Empty,       spaceMatters));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyFilledSB, Space,       spaceMatters));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyFilledSB, Text,        spaceMatters));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyFilledSB, NullyEmpty,  spaceMatters));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyFilledSB, NullySpace,  spaceMatters));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyFilledSB, NullyFilled, spaceMatters));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( EmptySB,       Null,        spaceMatters));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( EmptySB,       Empty,       spaceMatters));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( EmptySB,       Space,       spaceMatters));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( EmptySB,       Text,        spaceMatters));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( EmptySB,       NullyEmpty,  spaceMatters));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( EmptySB,       NullySpace,  spaceMatters));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( EmptySB,       NullyFilled, spaceMatters));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( SpaceSB,       Null,        spaceMatters));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( SpaceSB,       Empty,       spaceMatters));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( SpaceSB,       Space,       spaceMatters));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( SpaceSB,       Text,        spaceMatters));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( SpaceSB,       NullyEmpty,  spaceMatters));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( SpaceSB,       NullySpace,  spaceMatters));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( SpaceSB,       NullyFilled, spaceMatters));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( FilledSB,      Null,        spaceMatters));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( FilledSB,      Empty,       spaceMatters));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( FilledSB,      Space,       spaceMatters));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( FilledSB,      Text,        spaceMatters));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( FilledSB,      NullyEmpty,  spaceMatters));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( FilledSB,      NullySpace,  spaceMatters));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( FilledSB,      NullyFilled, spaceMatters));
                                                      
        NoNullRet("",         EmptySB      .Coalesce( NullSB,        Null,        spaceMatters));
        NoNullRet("",         EmptySB      .Coalesce( NullSB,        Empty,       spaceMatters));
        NoNullRet(" ",        EmptySB      .Coalesce( NullSB,        Space,       spaceMatters));
        NoNullRet(Text,       EmptySB      .Coalesce( NullSB,        Text,        spaceMatters));
        NoNullRet("",         EmptySB      .Coalesce( NullSB,        NullyEmpty,  spaceMatters));
        NoNullRet(" ",        EmptySB      .Coalesce( NullSB,        NullySpace,  spaceMatters));
        NoNullRet(Text,       EmptySB      .Coalesce( NullSB,        NullyFilled, spaceMatters));
        NoNullRet("",         EmptySB      .Coalesce( NullyEmptySB,  Null,        spaceMatters));
        NoNullRet("",         EmptySB      .Coalesce( NullyEmptySB,  Empty,       spaceMatters));
        NoNullRet(" ",        EmptySB      .Coalesce( NullyEmptySB,  Space,       spaceMatters));
        NoNullRet(Text,       EmptySB      .Coalesce( NullyEmptySB,  Text,        spaceMatters));
        NoNullRet("",         EmptySB      .Coalesce( NullyEmptySB,  NullyEmpty,  spaceMatters));
        NoNullRet(" ",        EmptySB      .Coalesce( NullyEmptySB,  NullySpace,  spaceMatters));
        NoNullRet(Text,       EmptySB      .Coalesce( NullyEmptySB,  NullyFilled, spaceMatters));
        NoNullRet(" ",        EmptySB      .Coalesce( NullySpaceSB,  Null,        spaceMatters));
        NoNullRet(" ",        EmptySB      .Coalesce( NullySpaceSB,  Empty,       spaceMatters));
        NoNullRet(" ",        EmptySB      .Coalesce( NullySpaceSB,  Space,       spaceMatters));
        NoNullRet(" ",        EmptySB      .Coalesce( NullySpaceSB,  Text,        spaceMatters));
        NoNullRet(" ",        EmptySB      .Coalesce( NullySpaceSB,  NullyEmpty,  spaceMatters));
        NoNullRet(" ",        EmptySB      .Coalesce( NullySpaceSB,  NullySpace,  spaceMatters));
        NoNullRet(" ",        EmptySB      .Coalesce( NullySpaceSB,  NullyFilled, spaceMatters));
        NoNullRet("FilledSB", EmptySB      .Coalesce( NullyFilledSB, Null,        spaceMatters));
        NoNullRet("FilledSB", EmptySB      .Coalesce( NullyFilledSB, Empty,       spaceMatters));
        NoNullRet("FilledSB", EmptySB      .Coalesce( NullyFilledSB, Space,       spaceMatters));
        NoNullRet("FilledSB", EmptySB      .Coalesce( NullyFilledSB, Text,        spaceMatters));
        NoNullRet("FilledSB", EmptySB      .Coalesce( NullyFilledSB, NullyEmpty,  spaceMatters));
        NoNullRet("FilledSB", EmptySB      .Coalesce( NullyFilledSB, NullySpace,  spaceMatters));
        NoNullRet("FilledSB", EmptySB      .Coalesce( NullyFilledSB, NullyFilled, spaceMatters));
        NoNullRet("",         EmptySB      .Coalesce( EmptySB,       Null,        spaceMatters));
        NoNullRet("",         EmptySB      .Coalesce( EmptySB,       Empty,       spaceMatters));
        NoNullRet(" ",        EmptySB      .Coalesce( EmptySB,       Space,       spaceMatters));
        NoNullRet(Text,       EmptySB      .Coalesce( EmptySB,       Text,        spaceMatters));
        NoNullRet("",         EmptySB      .Coalesce( EmptySB,       NullyEmpty,  spaceMatters));
        NoNullRet(" ",        EmptySB      .Coalesce( EmptySB,       NullySpace,  spaceMatters));
        NoNullRet(Text,       EmptySB      .Coalesce( EmptySB,       NullyFilled, spaceMatters));
        NoNullRet(" ",        EmptySB      .Coalesce( SpaceSB,       Null,        spaceMatters));
        NoNullRet(" ",        EmptySB      .Coalesce( SpaceSB,       Empty,       spaceMatters));
        NoNullRet(" ",        EmptySB      .Coalesce( SpaceSB,       Space,       spaceMatters));
        NoNullRet(" ",        EmptySB      .Coalesce( SpaceSB,       Text,        spaceMatters));
        NoNullRet(" ",        EmptySB      .Coalesce( SpaceSB,       NullyEmpty,  spaceMatters));
        NoNullRet(" ",        EmptySB      .Coalesce( SpaceSB,       NullySpace,  spaceMatters));
        NoNullRet(" ",        EmptySB      .Coalesce( SpaceSB,       NullyFilled, spaceMatters));
        NoNullRet("FilledSB", EmptySB      .Coalesce( FilledSB,      Null,        spaceMatters));
        NoNullRet("FilledSB", EmptySB      .Coalesce( FilledSB,      Empty,       spaceMatters));
        NoNullRet("FilledSB", EmptySB      .Coalesce( FilledSB,      Space,       spaceMatters));
        NoNullRet("FilledSB", EmptySB      .Coalesce( FilledSB,      Text,        spaceMatters));
        NoNullRet("FilledSB", EmptySB      .Coalesce( FilledSB,      NullyEmpty,  spaceMatters));
        NoNullRet("FilledSB", EmptySB      .Coalesce( FilledSB,      NullySpace,  spaceMatters));
        NoNullRet("FilledSB", EmptySB      .Coalesce( FilledSB,      NullyFilled, spaceMatters));
        
        NoNullRet(" ",        SpaceSB      .Coalesce( NullSB,        Null,        spaceMatters));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullSB,        Empty,       spaceMatters));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullSB,        Space,       spaceMatters));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullSB,        Text,        spaceMatters));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullSB,        NullyEmpty,  spaceMatters));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullSB,        NullySpace,  spaceMatters));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullSB,        NullyFilled, spaceMatters));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullyEmptySB,  Null,        spaceMatters));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullyEmptySB,  Empty,       spaceMatters));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullyEmptySB,  Space,       spaceMatters));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullyEmptySB,  Text,        spaceMatters));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullyEmptySB,  NullyEmpty,  spaceMatters));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullyEmptySB,  NullySpace,  spaceMatters));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullyEmptySB,  NullyFilled, spaceMatters));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullySpaceSB,  Null,        spaceMatters));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullySpaceSB,  Empty,       spaceMatters));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullySpaceSB,  Space,       spaceMatters));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullySpaceSB,  Text,        spaceMatters));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullySpaceSB,  NullyEmpty,  spaceMatters));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullySpaceSB,  NullySpace,  spaceMatters));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullySpaceSB,  NullyFilled, spaceMatters));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullyFilledSB, Null,        spaceMatters));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullyFilledSB, Empty,       spaceMatters));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullyFilledSB, Space,       spaceMatters));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullyFilledSB, Text,        spaceMatters));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullyFilledSB, NullyEmpty,  spaceMatters));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullyFilledSB, NullySpace,  spaceMatters));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullyFilledSB, NullyFilled, spaceMatters));
        NoNullRet(" ",        SpaceSB      .Coalesce( EmptySB,       Null,        spaceMatters));
        NoNullRet(" ",        SpaceSB      .Coalesce( EmptySB,       Empty,       spaceMatters));
        NoNullRet(" ",        SpaceSB      .Coalesce( EmptySB,       Space,       spaceMatters));
        NoNullRet(" ",        SpaceSB      .Coalesce( EmptySB,       Text,        spaceMatters));
        NoNullRet(" ",        SpaceSB      .Coalesce( EmptySB,       NullyEmpty,  spaceMatters));
        NoNullRet(" ",        SpaceSB      .Coalesce( EmptySB,       NullySpace,  spaceMatters));
        NoNullRet(" ",        SpaceSB      .Coalesce( EmptySB,       NullyFilled, spaceMatters));
        NoNullRet(" ",        SpaceSB      .Coalesce( SpaceSB,       Null,        spaceMatters));
        NoNullRet(" ",        SpaceSB      .Coalesce( SpaceSB,       Empty,       spaceMatters));
        NoNullRet(" ",        SpaceSB      .Coalesce( SpaceSB,       Space,       spaceMatters));
        NoNullRet(" ",        SpaceSB      .Coalesce( SpaceSB,       Text,        spaceMatters));
        NoNullRet(" ",        SpaceSB      .Coalesce( SpaceSB,       NullyEmpty,  spaceMatters));
        NoNullRet(" ",        SpaceSB      .Coalesce( SpaceSB,       NullySpace,  spaceMatters));
        NoNullRet(" ",        SpaceSB      .Coalesce( SpaceSB,       NullyFilled, spaceMatters));
        NoNullRet(" ",        SpaceSB      .Coalesce( FilledSB,      Null,        spaceMatters));
        NoNullRet(" ",        SpaceSB      .Coalesce( FilledSB,      Empty,       spaceMatters));
        NoNullRet(" ",        SpaceSB      .Coalesce( FilledSB,      Space,       spaceMatters));
        NoNullRet(" ",        SpaceSB      .Coalesce( FilledSB,      Text,        spaceMatters));
        NoNullRet(" ",        SpaceSB      .Coalesce( FilledSB,      NullyEmpty,  spaceMatters));
        NoNullRet(" ",        SpaceSB      .Coalesce( FilledSB,      NullySpace,  spaceMatters));
        NoNullRet(" ",        SpaceSB      .Coalesce( FilledSB,      NullyFilled, spaceMatters));
                                                      
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullSB,        Null,        spaceMatters));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullSB,        Empty,       spaceMatters));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullSB,        Space,       spaceMatters));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullSB,        Text,        spaceMatters));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullSB,        NullyEmpty,  spaceMatters));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullSB,        NullySpace,  spaceMatters));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullSB,        NullyFilled, spaceMatters));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyEmptySB,  Null,        spaceMatters));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyEmptySB,  Empty,       spaceMatters));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyEmptySB,  Space,       spaceMatters));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyEmptySB,  Text,        spaceMatters));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyEmptySB,  NullyEmpty,  spaceMatters));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyEmptySB,  NullySpace,  spaceMatters));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyEmptySB,  NullyFilled, spaceMatters));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullySpaceSB,  Null,        spaceMatters));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullySpaceSB,  Empty,       spaceMatters));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullySpaceSB,  Space,       spaceMatters));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullySpaceSB,  Text,        spaceMatters));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullySpaceSB,  NullyEmpty,  spaceMatters));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullySpaceSB,  NullySpace,  spaceMatters));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullySpaceSB,  NullyFilled, spaceMatters));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyFilledSB, Null,        spaceMatters));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyFilledSB, Empty,       spaceMatters));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyFilledSB, Space,       spaceMatters));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyFilledSB, Text,        spaceMatters));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyFilledSB, NullyEmpty,  spaceMatters));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyFilledSB, NullySpace,  spaceMatters));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyFilledSB, NullyFilled, spaceMatters));
        NoNullRet("FilledSB", FilledSB     .Coalesce( EmptySB,       Empty,       spaceMatters));
        NoNullRet("FilledSB", FilledSB     .Coalesce( EmptySB,       Space,       spaceMatters));
        NoNullRet("FilledSB", FilledSB     .Coalesce( EmptySB,       Text,        spaceMatters));
        NoNullRet("FilledSB", FilledSB     .Coalesce( EmptySB,       NullyEmpty,  spaceMatters));
        NoNullRet("FilledSB", FilledSB     .Coalesce( EmptySB,       NullySpace,  spaceMatters));
        NoNullRet("FilledSB", FilledSB     .Coalesce( EmptySB,       NullyFilled, spaceMatters));
        NoNullRet("FilledSB", FilledSB     .Coalesce( SpaceSB,       Empty,       spaceMatters));
        NoNullRet("FilledSB", FilledSB     .Coalesce( SpaceSB,       Space,       spaceMatters));
        NoNullRet("FilledSB", FilledSB     .Coalesce( SpaceSB,       Text,        spaceMatters));
        NoNullRet("FilledSB", FilledSB     .Coalesce( SpaceSB,       NullyEmpty,  spaceMatters));
        NoNullRet("FilledSB", FilledSB     .Coalesce( SpaceSB,       NullySpace,  spaceMatters));
        NoNullRet("FilledSB", FilledSB     .Coalesce( SpaceSB,       NullyFilled, spaceMatters));
        NoNullRet("FilledSB", FilledSB     .Coalesce( FilledSB,      Null,        spaceMatters));
        NoNullRet("FilledSB", FilledSB     .Coalesce( FilledSB,      Empty,       spaceMatters));
        NoNullRet("FilledSB", FilledSB     .Coalesce( FilledSB,      Space,       spaceMatters));
        NoNullRet("FilledSB", FilledSB     .Coalesce( FilledSB,      Text,        spaceMatters));
        NoNullRet("FilledSB", FilledSB     .Coalesce( FilledSB,      NullyEmpty,  spaceMatters));
        NoNullRet("FilledSB", FilledSB     .Coalesce( FilledSB,      NullySpace,  spaceMatters));
        NoNullRet("FilledSB", FilledSB     .Coalesce( FilledSB,      NullyFilled, spaceMatters));
    }

    /// <inheritdoc cref="_coalesce3argssbtotext" />
    [TestMethod]
    public void Coalesce_3Args_SBToString_Extensions_SpaceMatters_ExplicitBool()
    {
        NoNullRet("",         NullSB       .Coalesce( NullSB,        Null,        spaceMatters: true));
        NoNullRet("",         NullSB       .Coalesce( NullSB,        Empty,       spaceMatters: true));
        NoNullRet(" ",        NullSB       .Coalesce( NullSB,        Space,       spaceMatters: true));
        NoNullRet(Text,       NullSB       .Coalesce( NullSB,        Text,        spaceMatters: true));
        NoNullRet("",         NullSB       .Coalesce( NullSB,        NullyEmpty,  spaceMatters: true));
        NoNullRet(" ",        NullSB       .Coalesce( NullSB,        NullySpace,  spaceMatters: true));
        NoNullRet(Text,       NullSB       .Coalesce( NullSB,        NullyFilled, spaceMatters: true));
        NoNullRet("",         NullSB       .Coalesce( NullyEmptySB,  Null,        spaceMatters: true));
        NoNullRet("",         NullSB       .Coalesce( NullyEmptySB,  Empty,       spaceMatters: true));
        NoNullRet(" ",        NullSB       .Coalesce( NullyEmptySB,  Space,       spaceMatters: true));
        NoNullRet(Text,       NullSB       .Coalesce( NullyEmptySB,  Text,        spaceMatters: true));
        NoNullRet("",         NullSB       .Coalesce( NullyEmptySB,  NullyEmpty,  spaceMatters: true));
        NoNullRet(" ",        NullSB       .Coalesce( NullyEmptySB,  NullySpace,  spaceMatters: true));
        NoNullRet(Text,       NullSB       .Coalesce( NullyEmptySB,  NullyFilled, spaceMatters: true));
        NoNullRet(" ",        NullSB       .Coalesce( NullySpaceSB,  Null,        spaceMatters: true));
        NoNullRet(" ",        NullSB       .Coalesce( NullySpaceSB,  Empty,       spaceMatters: true));
        NoNullRet(" ",        NullSB       .Coalesce( NullySpaceSB,  Space,       spaceMatters: true));
        NoNullRet(" ",        NullSB       .Coalesce( NullySpaceSB,  Text,        spaceMatters: true));
        NoNullRet(" ",        NullSB       .Coalesce( NullySpaceSB,  NullyEmpty,  spaceMatters: true));
        NoNullRet(" ",        NullSB       .Coalesce( NullySpaceSB,  NullySpace,  spaceMatters: true));
        NoNullRet(" ",        NullSB       .Coalesce( NullySpaceSB,  NullyFilled, spaceMatters: true));
        NoNullRet("FilledSB", NullSB       .Coalesce( NullyFilledSB, Null,        spaceMatters: true));
        NoNullRet("FilledSB", NullSB       .Coalesce( NullyFilledSB, Empty,       spaceMatters: true));
        NoNullRet("FilledSB", NullSB       .Coalesce( NullyFilledSB, Space,       spaceMatters: true));
        NoNullRet("FilledSB", NullSB       .Coalesce( NullyFilledSB, Text,        spaceMatters: true));
        NoNullRet("FilledSB", NullSB       .Coalesce( NullyFilledSB, NullyEmpty,  spaceMatters: true));
        NoNullRet("FilledSB", NullSB       .Coalesce( NullyFilledSB, NullySpace,  spaceMatters: true));
        NoNullRet("FilledSB", NullSB       .Coalesce( NullyFilledSB, NullyFilled, spaceMatters: true));
        NoNullRet("",         NullSB       .Coalesce( EmptySB,       Null,        spaceMatters: true));
        NoNullRet("",         NullSB       .Coalesce( EmptySB,       Empty,       spaceMatters: true));
        NoNullRet(" ",        NullSB       .Coalesce( EmptySB,       Space,       spaceMatters: true));
        NoNullRet(Text,       NullSB       .Coalesce( EmptySB,       Text,        spaceMatters: true));
        NoNullRet("",         NullSB       .Coalesce( EmptySB,       NullyEmpty,  spaceMatters: true));
        NoNullRet(" ",        NullSB       .Coalesce( EmptySB,       NullySpace,  spaceMatters: true));
        NoNullRet(Text,       NullSB       .Coalesce( EmptySB,       NullyFilled, spaceMatters: true));
        NoNullRet(" ",        NullSB       .Coalesce( SpaceSB,       Null,        spaceMatters: true));
        NoNullRet(" ",        NullSB       .Coalesce( SpaceSB,       Empty,       spaceMatters: true));
        NoNullRet(" ",        NullSB       .Coalesce( SpaceSB,       Space,       spaceMatters: true));
        NoNullRet(" ",        NullSB       .Coalesce( SpaceSB,       Text,        spaceMatters: true));
        NoNullRet(" ",        NullSB       .Coalesce( SpaceSB,       NullyEmpty,  spaceMatters: true));
        NoNullRet(" ",        NullSB       .Coalesce( SpaceSB,       NullySpace,  spaceMatters: true));
        NoNullRet(" ",        NullSB       .Coalesce( SpaceSB,       NullyFilled, spaceMatters: true));
        NoNullRet("FilledSB", NullSB       .Coalesce( FilledSB,      Null,        spaceMatters: true));
        NoNullRet("FilledSB", NullSB       .Coalesce( FilledSB,      Empty,       spaceMatters: true));
        NoNullRet("FilledSB", NullSB       .Coalesce( FilledSB,      Space,       spaceMatters: true));
        NoNullRet("FilledSB", NullSB       .Coalesce( FilledSB,      Text,        spaceMatters: true));
        NoNullRet("FilledSB", NullSB       .Coalesce( FilledSB,      NullyEmpty,  spaceMatters: true));
        NoNullRet("FilledSB", NullSB       .Coalesce( FilledSB,      NullySpace,  spaceMatters: true));
        NoNullRet("FilledSB", NullSB       .Coalesce( FilledSB,      NullyFilled, spaceMatters: true));
                                                      
        NoNullRet("",         NullyEmptySB .Coalesce( NullSB,        Null,        spaceMatters: true));
        NoNullRet("",         NullyEmptySB .Coalesce( NullSB,        Empty,       spaceMatters: true));
        NoNullRet(" ",        NullyEmptySB .Coalesce( NullSB,        Space,       spaceMatters: true));
        NoNullRet(Text,       NullyEmptySB .Coalesce( NullSB,        Text,        spaceMatters: true));
        NoNullRet("",         NullyEmptySB .Coalesce( NullSB,        NullyEmpty,  spaceMatters: true));
        NoNullRet(" ",        NullyEmptySB .Coalesce( NullSB,        NullySpace,  spaceMatters: true));
        NoNullRet(Text,       NullyEmptySB .Coalesce( NullSB,        NullyFilled, spaceMatters: true));
        NoNullRet("",         NullyEmptySB .Coalesce( NullyEmptySB,  Null,        spaceMatters: true));
        NoNullRet("",         NullyEmptySB .Coalesce( NullyEmptySB,  Empty,       spaceMatters: true));
        NoNullRet(" ",        NullyEmptySB .Coalesce( NullyEmptySB,  Space,       spaceMatters: true));
        NoNullRet(Text,       NullyEmptySB .Coalesce( NullyEmptySB,  Text,        spaceMatters: true));
        NoNullRet("",         NullyEmptySB .Coalesce( NullyEmptySB,  NullyEmpty,  spaceMatters: true));
        NoNullRet(" ",        NullyEmptySB .Coalesce( NullyEmptySB,  NullySpace,  spaceMatters: true));
        NoNullRet(Text,       NullyEmptySB .Coalesce( NullyEmptySB,  NullyFilled, spaceMatters: true));
        NoNullRet(" ",        NullyEmptySB .Coalesce( NullySpaceSB,  Null,        spaceMatters: true));
        NoNullRet(" ",        NullyEmptySB .Coalesce( NullySpaceSB,  Empty,       spaceMatters: true));
        NoNullRet(" ",        NullyEmptySB .Coalesce( NullySpaceSB,  Space,       spaceMatters: true));
        NoNullRet(" ",        NullyEmptySB .Coalesce( NullySpaceSB,  Text,        spaceMatters: true));
        NoNullRet(" ",        NullyEmptySB .Coalesce( NullySpaceSB,  NullyEmpty,  spaceMatters: true));
        NoNullRet(" ",        NullyEmptySB .Coalesce( NullySpaceSB,  NullySpace,  spaceMatters: true));
        NoNullRet(" ",        NullyEmptySB .Coalesce( NullySpaceSB,  NullyFilled, spaceMatters: true));
        NoNullRet("FilledSB", NullyEmptySB .Coalesce( NullyFilledSB, Null,        spaceMatters: true));
        NoNullRet("FilledSB", NullyEmptySB .Coalesce( NullyFilledSB, Empty,       spaceMatters: true));
        NoNullRet("FilledSB", NullyEmptySB .Coalesce( NullyFilledSB, Space,       spaceMatters: true));
        NoNullRet("FilledSB", NullyEmptySB .Coalesce( NullyFilledSB, Text,        spaceMatters: true));
        NoNullRet("FilledSB", NullyEmptySB .Coalesce( NullyFilledSB, NullyEmpty,  spaceMatters: true));
        NoNullRet("FilledSB", NullyEmptySB .Coalesce( NullyFilledSB, NullySpace,  spaceMatters: true));
        NoNullRet("FilledSB", NullyEmptySB .Coalesce( NullyFilledSB, NullyFilled, spaceMatters: true));
        NoNullRet("",         NullyEmptySB .Coalesce( EmptySB,       Null,        spaceMatters: true));
        NoNullRet("",         NullyEmptySB .Coalesce( EmptySB,       Empty,       spaceMatters: true));
        NoNullRet(" ",        NullyEmptySB .Coalesce( EmptySB,       Space,       spaceMatters: true));
        NoNullRet(Text,       NullyEmptySB .Coalesce( EmptySB,       Text,        spaceMatters: true));
        NoNullRet("",         NullyEmptySB .Coalesce( EmptySB,       NullyEmpty,  spaceMatters: true));
        NoNullRet(" ",        NullyEmptySB .Coalesce( EmptySB,       NullySpace,  spaceMatters: true));
        NoNullRet(Text,       NullyEmptySB .Coalesce( EmptySB,       NullyFilled, spaceMatters: true));
        NoNullRet(" ",        NullyEmptySB .Coalesce( SpaceSB,       Null,        spaceMatters: true));
        NoNullRet(" ",        NullyEmptySB .Coalesce( SpaceSB,       Empty,       spaceMatters: true));
        NoNullRet(" ",        NullyEmptySB .Coalesce( SpaceSB,       Space,       spaceMatters: true));
        NoNullRet(" ",        NullyEmptySB .Coalesce( SpaceSB,       Text,        spaceMatters: true));
        NoNullRet(" ",        NullyEmptySB .Coalesce( SpaceSB,       NullyEmpty,  spaceMatters: true));
        NoNullRet(" ",        NullyEmptySB .Coalesce( SpaceSB,       NullySpace,  spaceMatters: true));
        NoNullRet(" ",        NullyEmptySB .Coalesce( SpaceSB,       NullyFilled, spaceMatters: true));
        NoNullRet("FilledSB", NullyEmptySB .Coalesce( FilledSB,      Null,        spaceMatters: true));
        NoNullRet("FilledSB", NullyEmptySB .Coalesce( FilledSB,      Empty,       spaceMatters: true));
        NoNullRet("FilledSB", NullyEmptySB .Coalesce( FilledSB,      Space,       spaceMatters: true));
        NoNullRet("FilledSB", NullyEmptySB .Coalesce( FilledSB,      Text,        spaceMatters: true));
        NoNullRet("FilledSB", NullyEmptySB .Coalesce( FilledSB,      NullyEmpty,  spaceMatters: true));
        NoNullRet("FilledSB", NullyEmptySB .Coalesce( FilledSB,      NullySpace,  spaceMatters: true));
        NoNullRet("FilledSB", NullyEmptySB .Coalesce( FilledSB,      NullyFilled, spaceMatters: true));
                                                      
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullSB,        Null,        spaceMatters: true));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullSB,        Empty,       spaceMatters: true));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullSB,        Space,       spaceMatters: true));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullSB,        Text,        spaceMatters: true));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullSB,        NullyEmpty,  spaceMatters: true));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullSB,        NullySpace,  spaceMatters: true));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullSB,        NullyFilled, spaceMatters: true));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullyEmptySB,  Null,        spaceMatters: true));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullyEmptySB,  Empty,       spaceMatters: true));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullyEmptySB,  Space,       spaceMatters: true));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullyEmptySB,  Text,        spaceMatters: true));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullyEmptySB,  NullyEmpty,  spaceMatters: true));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullyEmptySB,  NullySpace,  spaceMatters: true));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullyEmptySB,  NullyFilled, spaceMatters: true));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullySpaceSB,  Null,        spaceMatters: true));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullySpaceSB,  Empty,       spaceMatters: true));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullySpaceSB,  Space,       spaceMatters: true));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullySpaceSB,  Text,        spaceMatters: true));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullySpaceSB,  NullyEmpty,  spaceMatters: true));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullySpaceSB,  NullySpace,  spaceMatters: true));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullySpaceSB,  NullyFilled, spaceMatters: true));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullyFilledSB, Null,        spaceMatters: true));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullyFilledSB, Empty,       spaceMatters: true));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullyFilledSB, Space,       spaceMatters: true));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullyFilledSB, Text,        spaceMatters: true));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullyFilledSB, NullyEmpty,  spaceMatters: true));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullyFilledSB, NullySpace,  spaceMatters: true));
        NoNullRet(" ",        NullySpaceSB .Coalesce( NullyFilledSB, NullyFilled, spaceMatters: true));
        NoNullRet(" ",        NullySpaceSB .Coalesce( EmptySB,       Null,        spaceMatters: true));
        NoNullRet(" ",        NullySpaceSB .Coalesce( EmptySB,       Empty,       spaceMatters: true));
        NoNullRet(" ",        NullySpaceSB .Coalesce( EmptySB,       Space,       spaceMatters: true));
        NoNullRet(" ",        NullySpaceSB .Coalesce( EmptySB,       Text,        spaceMatters: true));
        NoNullRet(" ",        NullySpaceSB .Coalesce( EmptySB,       NullyEmpty,  spaceMatters: true));
        NoNullRet(" ",        NullySpaceSB .Coalesce( EmptySB,       NullySpace,  spaceMatters: true));
        NoNullRet(" ",        NullySpaceSB .Coalesce( EmptySB,       NullyFilled, spaceMatters: true));
        NoNullRet(" ",        NullySpaceSB .Coalesce( SpaceSB,       Null,        spaceMatters: true));
        NoNullRet(" ",        NullySpaceSB .Coalesce( SpaceSB,       Empty,       spaceMatters: true));
        NoNullRet(" ",        NullySpaceSB .Coalesce( SpaceSB,       Space,       spaceMatters: true));
        NoNullRet(" ",        NullySpaceSB .Coalesce( SpaceSB,       Text,        spaceMatters: true));
        NoNullRet(" ",        NullySpaceSB .Coalesce( SpaceSB,       NullyEmpty,  spaceMatters: true));
        NoNullRet(" ",        NullySpaceSB .Coalesce( SpaceSB,       NullySpace,  spaceMatters: true));
        NoNullRet(" ",        NullySpaceSB .Coalesce( SpaceSB,       NullyFilled, spaceMatters: true));
        NoNullRet(" ",        NullySpaceSB .Coalesce( FilledSB,      Null,        spaceMatters: true));
        NoNullRet(" ",        NullySpaceSB .Coalesce( FilledSB,      Empty,       spaceMatters: true));
        NoNullRet(" ",        NullySpaceSB .Coalesce( FilledSB,      Space,       spaceMatters: true));
        NoNullRet(" ",        NullySpaceSB .Coalesce( FilledSB,      Text,        spaceMatters: true));
        NoNullRet(" ",        NullySpaceSB .Coalesce( FilledSB,      NullyEmpty,  spaceMatters: true));
        NoNullRet(" ",        NullySpaceSB .Coalesce( FilledSB,      NullySpace,  spaceMatters: true));
        NoNullRet(" ",        NullySpaceSB .Coalesce( FilledSB,      NullyFilled, spaceMatters: true));
                                                      
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullSB,        Null,        spaceMatters: true));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullSB,        Empty,       spaceMatters: true));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullSB,        Space,       spaceMatters: true));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullSB,        Text,        spaceMatters: true));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullSB,        NullyEmpty,  spaceMatters: true));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullSB,        NullySpace,  spaceMatters: true));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullSB,        NullyFilled, spaceMatters: true));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyEmptySB,  Null,        spaceMatters: true));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyEmptySB,  Empty,       spaceMatters: true));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyEmptySB,  Space,       spaceMatters: true));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyEmptySB,  Text,        spaceMatters: true));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyEmptySB,  NullyEmpty,  spaceMatters: true));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyEmptySB,  NullySpace,  spaceMatters: true));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyEmptySB,  NullyFilled, spaceMatters: true));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullySpaceSB,  Null,        spaceMatters: true));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullySpaceSB,  Empty,       spaceMatters: true));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullySpaceSB,  Space,       spaceMatters: true));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullySpaceSB,  Text,        spaceMatters: true));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullySpaceSB,  NullyEmpty,  spaceMatters: true));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullySpaceSB,  NullySpace,  spaceMatters: true));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullySpaceSB,  NullyFilled, spaceMatters: true));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyFilledSB, Null,        spaceMatters: true));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyFilledSB, Empty,       spaceMatters: true));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyFilledSB, Space,       spaceMatters: true));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyFilledSB, Text,        spaceMatters: true));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyFilledSB, NullyEmpty,  spaceMatters: true));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyFilledSB, NullySpace,  spaceMatters: true));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( NullyFilledSB, NullyFilled, spaceMatters: true));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( EmptySB,       Null,        spaceMatters: true));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( EmptySB,       Empty,       spaceMatters: true));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( EmptySB,       Space,       spaceMatters: true));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( EmptySB,       Text,        spaceMatters: true));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( EmptySB,       NullyEmpty,  spaceMatters: true));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( EmptySB,       NullySpace,  spaceMatters: true));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( EmptySB,       NullyFilled, spaceMatters: true));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( SpaceSB,       Null,        spaceMatters: true));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( SpaceSB,       Empty,       spaceMatters: true));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( SpaceSB,       Space,       spaceMatters: true));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( SpaceSB,       Text,        spaceMatters: true));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( SpaceSB,       NullyEmpty,  spaceMatters: true));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( SpaceSB,       NullySpace,  spaceMatters: true));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( SpaceSB,       NullyFilled, spaceMatters: true));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( FilledSB,      Null,        spaceMatters: true));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( FilledSB,      Empty,       spaceMatters: true));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( FilledSB,      Space,       spaceMatters: true));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( FilledSB,      Text,        spaceMatters: true));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( FilledSB,      NullyEmpty,  spaceMatters: true));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( FilledSB,      NullySpace,  spaceMatters: true));
        NoNullRet("FilledSB", NullyFilledSB.Coalesce( FilledSB,      NullyFilled, spaceMatters: true));
                                                      
        NoNullRet("",         EmptySB      .Coalesce( NullSB,        Null,        spaceMatters: true));
        NoNullRet("",         EmptySB      .Coalesce( NullSB,        Empty,       spaceMatters: true));
        NoNullRet(" ",        EmptySB      .Coalesce( NullSB,        Space,       spaceMatters: true));
        NoNullRet(Text,       EmptySB      .Coalesce( NullSB,        Text,        spaceMatters: true));
        NoNullRet("",         EmptySB      .Coalesce( NullSB,        NullyEmpty,  spaceMatters: true));
        NoNullRet(" ",        EmptySB      .Coalesce( NullSB,        NullySpace,  spaceMatters: true));
        NoNullRet(Text,       EmptySB      .Coalesce( NullSB,        NullyFilled, spaceMatters: true));
        NoNullRet("",         EmptySB      .Coalesce( NullyEmptySB,  Null,        spaceMatters: true));
        NoNullRet("",         EmptySB      .Coalesce( NullyEmptySB,  Empty,       spaceMatters: true));
        NoNullRet(" ",        EmptySB      .Coalesce( NullyEmptySB,  Space,       spaceMatters: true));
        NoNullRet(Text,       EmptySB      .Coalesce( NullyEmptySB,  Text,        spaceMatters: true));
        NoNullRet("",         EmptySB      .Coalesce( NullyEmptySB,  NullyEmpty,  spaceMatters: true));
        NoNullRet(" ",        EmptySB      .Coalesce( NullyEmptySB,  NullySpace,  spaceMatters: true));
        NoNullRet(Text,       EmptySB      .Coalesce( NullyEmptySB,  NullyFilled, spaceMatters: true));
        NoNullRet(" ",        EmptySB      .Coalesce( NullySpaceSB,  Null,        spaceMatters: true));
        NoNullRet(" ",        EmptySB      .Coalesce( NullySpaceSB,  Empty,       spaceMatters: true));
        NoNullRet(" ",        EmptySB      .Coalesce( NullySpaceSB,  Space,       spaceMatters: true));
        NoNullRet(" ",        EmptySB      .Coalesce( NullySpaceSB,  Text,        spaceMatters: true));
        NoNullRet(" ",        EmptySB      .Coalesce( NullySpaceSB,  NullyEmpty,  spaceMatters: true));
        NoNullRet(" ",        EmptySB      .Coalesce( NullySpaceSB,  NullySpace,  spaceMatters: true));
        NoNullRet(" ",        EmptySB      .Coalesce( NullySpaceSB,  NullyFilled, spaceMatters: true));
        NoNullRet("FilledSB", EmptySB      .Coalesce( NullyFilledSB, Null,        spaceMatters: true));
        NoNullRet("FilledSB", EmptySB      .Coalesce( NullyFilledSB, Empty,       spaceMatters: true));
        NoNullRet("FilledSB", EmptySB      .Coalesce( NullyFilledSB, Space,       spaceMatters: true));
        NoNullRet("FilledSB", EmptySB      .Coalesce( NullyFilledSB, Text,        spaceMatters: true));
        NoNullRet("FilledSB", EmptySB      .Coalesce( NullyFilledSB, NullyEmpty,  spaceMatters: true));
        NoNullRet("FilledSB", EmptySB      .Coalesce( NullyFilledSB, NullySpace,  spaceMatters: true));
        NoNullRet("FilledSB", EmptySB      .Coalesce( NullyFilledSB, NullyFilled, spaceMatters: true));
        NoNullRet("",         EmptySB      .Coalesce( EmptySB,       Null,        spaceMatters: true));
        NoNullRet("",         EmptySB      .Coalesce( EmptySB,       Empty,       spaceMatters: true));
        NoNullRet(" ",        EmptySB      .Coalesce( EmptySB,       Space,       spaceMatters: true));
        NoNullRet(Text,       EmptySB      .Coalesce( EmptySB,       Text,        spaceMatters: true));
        NoNullRet("",         EmptySB      .Coalesce( EmptySB,       NullyEmpty,  spaceMatters: true));
        NoNullRet(" ",        EmptySB      .Coalesce( EmptySB,       NullySpace,  spaceMatters: true));
        NoNullRet(Text,       EmptySB      .Coalesce( EmptySB,       NullyFilled, spaceMatters: true));
        NoNullRet(" ",        EmptySB      .Coalesce( SpaceSB,       Null,        spaceMatters: true));
        NoNullRet(" ",        EmptySB      .Coalesce( SpaceSB,       Empty,       spaceMatters: true));
        NoNullRet(" ",        EmptySB      .Coalesce( SpaceSB,       Space,       spaceMatters: true));
        NoNullRet(" ",        EmptySB      .Coalesce( SpaceSB,       Text,        spaceMatters: true));
        NoNullRet(" ",        EmptySB      .Coalesce( SpaceSB,       NullyEmpty,  spaceMatters: true));
        NoNullRet(" ",        EmptySB      .Coalesce( SpaceSB,       NullySpace,  spaceMatters: true));
        NoNullRet(" ",        EmptySB      .Coalesce( SpaceSB,       NullyFilled, spaceMatters: true));
        NoNullRet("FilledSB", EmptySB      .Coalesce( FilledSB,      Null,        spaceMatters: true));
        NoNullRet("FilledSB", EmptySB      .Coalesce( FilledSB,      Empty,       spaceMatters: true));
        NoNullRet("FilledSB", EmptySB      .Coalesce( FilledSB,      Space,       spaceMatters: true));
        NoNullRet("FilledSB", EmptySB      .Coalesce( FilledSB,      Text,        spaceMatters: true));
        NoNullRet("FilledSB", EmptySB      .Coalesce( FilledSB,      NullyEmpty,  spaceMatters: true));
        NoNullRet("FilledSB", EmptySB      .Coalesce( FilledSB,      NullySpace,  spaceMatters: true));
        NoNullRet("FilledSB", EmptySB      .Coalesce( FilledSB,      NullyFilled, spaceMatters: true));
        
        NoNullRet(" ",        SpaceSB      .Coalesce( NullSB,        Null,        spaceMatters: true));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullSB,        Empty,       spaceMatters: true));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullSB,        Space,       spaceMatters: true));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullSB,        Text,        spaceMatters: true));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullSB,        NullyEmpty,  spaceMatters: true));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullSB,        NullySpace,  spaceMatters: true));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullSB,        NullyFilled, spaceMatters: true));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullyEmptySB,  Null,        spaceMatters: true));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullyEmptySB,  Empty,       spaceMatters: true));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullyEmptySB,  Space,       spaceMatters: true));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullyEmptySB,  Text,        spaceMatters: true));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullyEmptySB,  NullyEmpty,  spaceMatters: true));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullyEmptySB,  NullySpace,  spaceMatters: true));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullyEmptySB,  NullyFilled, spaceMatters: true));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullySpaceSB,  Null,        spaceMatters: true));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullySpaceSB,  Empty,       spaceMatters: true));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullySpaceSB,  Space,       spaceMatters: true));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullySpaceSB,  Text,        spaceMatters: true));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullySpaceSB,  NullyEmpty,  spaceMatters: true));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullySpaceSB,  NullySpace,  spaceMatters: true));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullySpaceSB,  NullyFilled, spaceMatters: true));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullyFilledSB, Null,        spaceMatters: true));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullyFilledSB, Empty,       spaceMatters: true));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullyFilledSB, Space,       spaceMatters: true));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullyFilledSB, Text,        spaceMatters: true));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullyFilledSB, NullyEmpty,  spaceMatters: true));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullyFilledSB, NullySpace,  spaceMatters: true));
        NoNullRet(" ",        SpaceSB      .Coalesce( NullyFilledSB, NullyFilled, spaceMatters: true));
        NoNullRet(" ",        SpaceSB      .Coalesce( EmptySB,       Null,        spaceMatters: true));
        NoNullRet(" ",        SpaceSB      .Coalesce( EmptySB,       Empty,       spaceMatters: true));
        NoNullRet(" ",        SpaceSB      .Coalesce( EmptySB,       Space,       spaceMatters: true));
        NoNullRet(" ",        SpaceSB      .Coalesce( EmptySB,       Text,        spaceMatters: true));
        NoNullRet(" ",        SpaceSB      .Coalesce( EmptySB,       NullyEmpty,  spaceMatters: true));
        NoNullRet(" ",        SpaceSB      .Coalesce( EmptySB,       NullySpace,  spaceMatters: true));
        NoNullRet(" ",        SpaceSB      .Coalesce( EmptySB,       NullyFilled, spaceMatters: true));
        NoNullRet(" ",        SpaceSB      .Coalesce( SpaceSB,       Null,        spaceMatters: true));
        NoNullRet(" ",        SpaceSB      .Coalesce( SpaceSB,       Empty,       spaceMatters: true));
        NoNullRet(" ",        SpaceSB      .Coalesce( SpaceSB,       Space,       spaceMatters: true));
        NoNullRet(" ",        SpaceSB      .Coalesce( SpaceSB,       Text,        spaceMatters: true));
        NoNullRet(" ",        SpaceSB      .Coalesce( SpaceSB,       NullyEmpty,  spaceMatters: true));
        NoNullRet(" ",        SpaceSB      .Coalesce( SpaceSB,       NullySpace,  spaceMatters: true));
        NoNullRet(" ",        SpaceSB      .Coalesce( SpaceSB,       NullyFilled, spaceMatters: true));
        NoNullRet(" ",        SpaceSB      .Coalesce( FilledSB,      Null,        spaceMatters: true));
        NoNullRet(" ",        SpaceSB      .Coalesce( FilledSB,      Empty,       spaceMatters: true));
        NoNullRet(" ",        SpaceSB      .Coalesce( FilledSB,      Space,       spaceMatters: true));
        NoNullRet(" ",        SpaceSB      .Coalesce( FilledSB,      Text,        spaceMatters: true));
        NoNullRet(" ",        SpaceSB      .Coalesce( FilledSB,      NullyEmpty,  spaceMatters: true));
        NoNullRet(" ",        SpaceSB      .Coalesce( FilledSB,      NullySpace,  spaceMatters: true));
        NoNullRet(" ",        SpaceSB      .Coalesce( FilledSB,      NullyFilled, spaceMatters: true));
                                                      
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullSB,        Null,        spaceMatters: true));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullSB,        Empty,       spaceMatters: true));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullSB,        Space,       spaceMatters: true));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullSB,        Text,        spaceMatters: true));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullSB,        NullyEmpty,  spaceMatters: true));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullSB,        NullySpace,  spaceMatters: true));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullSB,        NullyFilled, spaceMatters: true));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyEmptySB,  Null,        spaceMatters: true));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyEmptySB,  Empty,       spaceMatters: true));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyEmptySB,  Space,       spaceMatters: true));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyEmptySB,  Text,        spaceMatters: true));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyEmptySB,  NullyEmpty,  spaceMatters: true));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyEmptySB,  NullySpace,  spaceMatters: true));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyEmptySB,  NullyFilled, spaceMatters: true));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullySpaceSB,  Null,        spaceMatters: true));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullySpaceSB,  Empty,       spaceMatters: true));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullySpaceSB,  Space,       spaceMatters: true));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullySpaceSB,  Text,        spaceMatters: true));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullySpaceSB,  NullyEmpty,  spaceMatters: true));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullySpaceSB,  NullySpace,  spaceMatters: true));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullySpaceSB,  NullyFilled, spaceMatters: true));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyFilledSB, Null,        spaceMatters: true));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyFilledSB, Empty,       spaceMatters: true));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyFilledSB, Space,       spaceMatters: true));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyFilledSB, Text,        spaceMatters: true));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyFilledSB, NullyEmpty,  spaceMatters: true));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyFilledSB, NullySpace,  spaceMatters: true));
        NoNullRet("FilledSB", FilledSB     .Coalesce( NullyFilledSB, NullyFilled, spaceMatters: true));
        NoNullRet("FilledSB", FilledSB     .Coalesce( EmptySB,       Empty,       spaceMatters: true));
        NoNullRet("FilledSB", FilledSB     .Coalesce( EmptySB,       Space,       spaceMatters: true));
        NoNullRet("FilledSB", FilledSB     .Coalesce( EmptySB,       Text,        spaceMatters: true));
        NoNullRet("FilledSB", FilledSB     .Coalesce( EmptySB,       NullyEmpty,  spaceMatters: true));
        NoNullRet("FilledSB", FilledSB     .Coalesce( EmptySB,       NullySpace,  spaceMatters: true));
        NoNullRet("FilledSB", FilledSB     .Coalesce( EmptySB,       NullyFilled, spaceMatters: true));
        NoNullRet("FilledSB", FilledSB     .Coalesce( SpaceSB,       Empty,       spaceMatters: true));
        NoNullRet("FilledSB", FilledSB     .Coalesce( SpaceSB,       Space,       spaceMatters: true));
        NoNullRet("FilledSB", FilledSB     .Coalesce( SpaceSB,       Text,        spaceMatters: true));
        NoNullRet("FilledSB", FilledSB     .Coalesce( SpaceSB,       NullyEmpty,  spaceMatters: true));
        NoNullRet("FilledSB", FilledSB     .Coalesce( SpaceSB,       NullySpace,  spaceMatters: true));
        NoNullRet("FilledSB", FilledSB     .Coalesce( SpaceSB,       NullyFilled, spaceMatters: true));
        NoNullRet("FilledSB", FilledSB     .Coalesce( FilledSB,      Null,        spaceMatters: true));
        NoNullRet("FilledSB", FilledSB     .Coalesce( FilledSB,      Empty,       spaceMatters: true));
        NoNullRet("FilledSB", FilledSB     .Coalesce( FilledSB,      Space,       spaceMatters: true));
        NoNullRet("FilledSB", FilledSB     .Coalesce( FilledSB,      Text,        spaceMatters: true));
        NoNullRet("FilledSB", FilledSB     .Coalesce( FilledSB,      NullyEmpty,  spaceMatters: true));
        NoNullRet("FilledSB", FilledSB     .Coalesce( FilledSB,      NullySpace,  spaceMatters: true));
        NoNullRet("FilledSB", FilledSB     .Coalesce( FilledSB,      NullyFilled, spaceMatters: true));
    }
}