namespace JJ.Framework.Existence.Core.Tests;

[TestClass]
public class Coalesce_3Args_SBs_StaticSpaceMattersNoExplicit
{
    [TestMethod]
    public void Coalesce_3Args_SBs_StaticSpaceMattersNoExplicit_Batch1()
    {
        NoNullRet(                 Coalesce(NullSB,        NullSB,        NullSB,        spaceMatters: false));
        NoNullRet($"{EmptySB}", $"{Coalesce(NullSB,        NullSB,        NullSB,        spaceMatters: false)}");
        NoNullRet(   EmptySB,      Coalesce(NullSB,        NullSB,        NullyEmptySB,  spaceMatters: false));
        NoNullRet(   SpaceSB,      Coalesce(NullSB,        NullSB,        NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullSB,        NullSB,        NullyFilledSB, spaceMatters: false));
        NoNullRet(   EmptySB,      Coalesce(NullSB,        NullSB,        EmptySB,       spaceMatters: false));
        NoNullRet(   SpaceSB,      Coalesce(NullSB,        NullSB,        SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullSB,        NullSB,        FilledSB,      spaceMatters: false));
        NoNullRet(                 Coalesce(NullSB,        NullyEmptySB,  NullSB,        spaceMatters: false));
        NoNullRet($"{EmptySB}", $"{Coalesce(NullSB,        NullyEmptySB,  NullSB,        spaceMatters: false)}");
        NoNullRet(   EmptySB,      Coalesce(NullSB,        NullyEmptySB,  NullyEmptySB,  spaceMatters: false));
        NoNullRet(   SpaceSB,      Coalesce(NullSB,        NullyEmptySB,  NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullSB,        NullyEmptySB,  NullyFilledSB, spaceMatters: false));
        NoNullRet(   EmptySB,      Coalesce(NullSB,        NullyEmptySB,  EmptySB,       spaceMatters: false));
        NoNullRet(   SpaceSB,      Coalesce(NullSB,        NullyEmptySB,  SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullSB,        NullyEmptySB,  FilledSB,      spaceMatters: false));
        NoNullRet(                 Coalesce(NullSB,        NullySpaceSB,  NullSB,        spaceMatters: false));
        NoNullRet($"{EmptySB}", $"{Coalesce(NullSB,        NullySpaceSB,  NullSB,        spaceMatters: false)}");
        NoNullRet(   EmptySB,      Coalesce(NullSB,        NullySpaceSB,  NullyEmptySB,  spaceMatters: false));
        NoNullRet(   SpaceSB,      Coalesce(NullSB,        NullySpaceSB,  NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullSB,        NullySpaceSB,  NullyFilledSB, spaceMatters: false));
        NoNullRet(   EmptySB,      Coalesce(NullSB,        NullySpaceSB,  EmptySB,       spaceMatters: false));
        NoNullRet(   SpaceSB,      Coalesce(NullSB,        NullySpaceSB,  SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullSB,        NullySpaceSB,  FilledSB,      spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullSB,        NullyFilledSB, NullSB,        spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullSB,        NullyFilledSB, NullyEmptySB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullSB,        NullyFilledSB, NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullSB,        NullyFilledSB, NullyFilledSB, spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullSB,        NullyFilledSB, EmptySB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullSB,        NullyFilledSB, SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullSB,        NullyFilledSB, FilledSB,      spaceMatters: false));
        NoNullRet(                 Coalesce(NullSB,        EmptySB,       NullSB,        spaceMatters: false));
        NoNullRet($"{EmptySB}", $"{Coalesce(NullSB,        EmptySB,       NullSB,        spaceMatters: false)}");
        NoNullRet(   EmptySB,      Coalesce(NullSB,        EmptySB,       NullyEmptySB,  spaceMatters: false));
        NoNullRet(   SpaceSB,      Coalesce(NullSB,        EmptySB,       NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullSB,        EmptySB,       NullyFilledSB, spaceMatters: false));
        NoNullRet(   EmptySB,      Coalesce(NullSB,        EmptySB,       EmptySB,       spaceMatters: false));
        NoNullRet(   SpaceSB,      Coalesce(NullSB,        EmptySB,       SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullSB,        EmptySB,       FilledSB,      spaceMatters: false));
        NoNullRet(                 Coalesce(NullSB,        SpaceSB,       NullSB,        spaceMatters: false));
        NoNullRet($"{EmptySB}", $"{Coalesce(NullSB,        SpaceSB,       NullSB,        spaceMatters: false)}");
        NoNullRet(   EmptySB,      Coalesce(NullSB,        SpaceSB,       NullyEmptySB,  spaceMatters: false));
        NoNullRet(   SpaceSB,      Coalesce(NullSB,        SpaceSB,       NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullSB,        SpaceSB,       NullyFilledSB, spaceMatters: false));
        NoNullRet(   EmptySB,      Coalesce(NullSB,        SpaceSB,       EmptySB,       spaceMatters: false));
        NoNullRet(   SpaceSB,      Coalesce(NullSB,        SpaceSB,       SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullSB,        SpaceSB,       FilledSB,      spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullSB,        FilledSB,      NullSB,        spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullSB,        FilledSB,      NullyEmptySB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullSB,        FilledSB,      NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullSB,        FilledSB,      NullyFilledSB, spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullSB,        FilledSB,      EmptySB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullSB,        FilledSB,      SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullSB,        FilledSB,      FilledSB,      spaceMatters: false));
    }

    [TestMethod]
    public void Coalesce_3Args_SBs_StaticSpaceMattersNoExplicit_Batch2()
    {
        NoNullRet(                 Coalesce(NullyEmptySB,  NullSB,        NullSB,        spaceMatters: false));
        NoNullRet($"{EmptySB}", $"{Coalesce(NullyEmptySB,  NullSB,        NullSB,        spaceMatters: false)}");
        NoNullRet(   EmptySB,      Coalesce(NullyEmptySB,  NullSB,        NullyEmptySB,  spaceMatters: false));
        NoNullRet(   SpaceSB,      Coalesce(NullyEmptySB,  NullSB,        NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyEmptySB,  NullSB,        NullyFilledSB, spaceMatters: false));
        NoNullRet(   EmptySB,      Coalesce(NullyEmptySB,  NullSB,        EmptySB,       spaceMatters: false));
        NoNullRet(   SpaceSB,      Coalesce(NullyEmptySB,  NullSB,        SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyEmptySB,  NullSB,        FilledSB,      spaceMatters: false));
        NoNullRet(                 Coalesce(NullyEmptySB,  NullyEmptySB,  NullSB,        spaceMatters: false));
        NoNullRet($"{EmptySB}", $"{Coalesce(NullyEmptySB,  NullyEmptySB,  NullSB,        spaceMatters: false)}");
        NoNullRet(   EmptySB,      Coalesce(NullyEmptySB,  NullyEmptySB,  NullyEmptySB,  spaceMatters: false));
        NoNullRet(   SpaceSB,      Coalesce(NullyEmptySB,  NullyEmptySB,  NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyEmptySB,  NullyEmptySB,  NullyFilledSB, spaceMatters: false));
        NoNullRet(   EmptySB,      Coalesce(NullyEmptySB,  NullyEmptySB,  EmptySB,       spaceMatters: false));
        NoNullRet(   SpaceSB,      Coalesce(NullyEmptySB,  NullyEmptySB,  SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyEmptySB,  NullyEmptySB,  FilledSB,      spaceMatters: false));
        NoNullRet(                 Coalesce(NullyEmptySB,  NullySpaceSB,  NullSB,        spaceMatters: false));
        NoNullRet($"{EmptySB}", $"{Coalesce(NullyEmptySB,  NullySpaceSB,  NullSB,        spaceMatters: false)}");
        NoNullRet(   EmptySB,      Coalesce(NullyEmptySB,  NullySpaceSB,  NullyEmptySB,  spaceMatters: false));
        NoNullRet(   SpaceSB,      Coalesce(NullyEmptySB,  NullySpaceSB,  NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyEmptySB,  NullySpaceSB,  NullyFilledSB, spaceMatters: false));
        NoNullRet(   EmptySB,      Coalesce(NullyEmptySB,  NullySpaceSB,  EmptySB,       spaceMatters: false));
        NoNullRet(   SpaceSB,      Coalesce(NullyEmptySB,  NullySpaceSB,  SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyEmptySB,  NullySpaceSB,  FilledSB,      spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyEmptySB,  NullyFilledSB, NullSB,        spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyEmptySB,  NullyFilledSB, NullyEmptySB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyEmptySB,  NullyFilledSB, NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyEmptySB,  NullyFilledSB, NullyFilledSB, spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyEmptySB,  NullyFilledSB, EmptySB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyEmptySB,  NullyFilledSB, SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyEmptySB,  NullyFilledSB, FilledSB,      spaceMatters: false));
        NoNullRet(                 Coalesce(NullyEmptySB,  EmptySB,       NullSB,        spaceMatters: false));
        NoNullRet($"{EmptySB}", $"{Coalesce(NullyEmptySB,  EmptySB,       NullSB,        spaceMatters: false)}");
        NoNullRet(   EmptySB,      Coalesce(NullyEmptySB,  EmptySB,       NullyEmptySB,  spaceMatters: false));
        NoNullRet(   SpaceSB,      Coalesce(NullyEmptySB,  EmptySB,       NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyEmptySB,  EmptySB,       NullyFilledSB, spaceMatters: false));
        NoNullRet(   EmptySB,      Coalesce(NullyEmptySB,  EmptySB,       EmptySB,       spaceMatters: false));
        NoNullRet(   SpaceSB,      Coalesce(NullyEmptySB,  EmptySB,       SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyEmptySB,  EmptySB,       FilledSB,      spaceMatters: false));
        NoNullRet(                 Coalesce(NullyEmptySB,  SpaceSB,       NullSB,        spaceMatters: false));
        NoNullRet($"{EmptySB}", $"{Coalesce(NullyEmptySB,  SpaceSB,       NullSB,        spaceMatters: false)}");
        NoNullRet(   EmptySB,      Coalesce(NullyEmptySB,  SpaceSB,       NullyEmptySB,  spaceMatters: false));
        NoNullRet(   SpaceSB,      Coalesce(NullyEmptySB,  SpaceSB,       NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyEmptySB,  SpaceSB,       NullyFilledSB, spaceMatters: false));
        NoNullRet(   EmptySB,      Coalesce(NullyEmptySB,  SpaceSB,       EmptySB,       spaceMatters: false));
        NoNullRet(   SpaceSB,      Coalesce(NullyEmptySB,  SpaceSB,       SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyEmptySB,  SpaceSB,       FilledSB,      spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyEmptySB,  FilledSB,      NullSB,        spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyEmptySB,  FilledSB,      NullyEmptySB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyEmptySB,  FilledSB,      NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyEmptySB,  FilledSB,      NullyFilledSB, spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyEmptySB,  FilledSB,      EmptySB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyEmptySB,  FilledSB,      SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyEmptySB,  FilledSB,      FilledSB,      spaceMatters: false));
    }

    [TestMethod]
    public void Coalesce_3Args_SBs_StaticSpaceMattersNoExplicit_Batch3()
    {
        NoNullRet(                 Coalesce(NullySpaceSB,  NullSB,        NullSB,        spaceMatters: false));
        NoNullRet($"{EmptySB}", $"{Coalesce(NullySpaceSB,  NullSB,        NullSB,        spaceMatters: false)}");
        NoNullRet(   EmptySB,      Coalesce(NullySpaceSB,  NullSB,        NullyEmptySB,  spaceMatters: false));
        NoNullRet(   SpaceSB,      Coalesce(NullySpaceSB,  NullSB,        NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullySpaceSB,  NullSB,        NullyFilledSB, spaceMatters: false));
        NoNullRet(   EmptySB,      Coalesce(NullySpaceSB,  NullSB,        EmptySB,       spaceMatters: false));
        NoNullRet(   SpaceSB,      Coalesce(NullySpaceSB,  NullSB,        SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullySpaceSB,  NullSB,        FilledSB,      spaceMatters: false));
        NoNullRet(                 Coalesce(NullySpaceSB,  NullyEmptySB,  NullSB,        spaceMatters: false));
        NoNullRet($"{EmptySB}", $"{Coalesce(NullySpaceSB,  NullyEmptySB,  NullSB,        spaceMatters: false)}");
        NoNullRet(   EmptySB,      Coalesce(NullySpaceSB,  NullyEmptySB,  NullyEmptySB,  spaceMatters: false));
        NoNullRet(   SpaceSB,      Coalesce(NullySpaceSB,  NullyEmptySB,  NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullySpaceSB,  NullyEmptySB,  NullyFilledSB, spaceMatters: false));
        NoNullRet(   EmptySB,      Coalesce(NullySpaceSB,  NullyEmptySB,  EmptySB,       spaceMatters: false));
        NoNullRet(   SpaceSB,      Coalesce(NullySpaceSB,  NullyEmptySB,  SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullySpaceSB,  NullyEmptySB,  FilledSB,      spaceMatters: false));
        NoNullRet(                 Coalesce(NullySpaceSB,  NullySpaceSB,  NullSB,        spaceMatters: false));
        NoNullRet($"{EmptySB}", $"{Coalesce(NullySpaceSB,  NullySpaceSB,  NullSB,        spaceMatters: false)}");
        NoNullRet(   EmptySB,      Coalesce(NullySpaceSB,  NullySpaceSB,  NullyEmptySB,  spaceMatters: false));
        NoNullRet(   SpaceSB,      Coalesce(NullySpaceSB,  NullySpaceSB,  NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullySpaceSB,  NullySpaceSB,  NullyFilledSB, spaceMatters: false));
        NoNullRet(   EmptySB,      Coalesce(NullySpaceSB,  NullySpaceSB,  EmptySB,       spaceMatters: false));
        NoNullRet(   SpaceSB,      Coalesce(NullySpaceSB,  NullySpaceSB,  SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullySpaceSB,  NullySpaceSB,  FilledSB,      spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullySpaceSB,  NullyFilledSB, NullSB,        spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullySpaceSB,  NullyFilledSB, NullyEmptySB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullySpaceSB,  NullyFilledSB, NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullySpaceSB,  NullyFilledSB, NullyFilledSB, spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullySpaceSB,  NullyFilledSB, EmptySB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullySpaceSB,  NullyFilledSB, SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullySpaceSB,  NullyFilledSB, FilledSB,      spaceMatters: false));
        NoNullRet(                 Coalesce(NullySpaceSB,  EmptySB,       NullSB,        spaceMatters: false));
        NoNullRet($"{EmptySB}", $"{Coalesce(NullySpaceSB,  EmptySB,       NullSB,        spaceMatters: false)}");
        NoNullRet(   EmptySB,      Coalesce(NullySpaceSB,  EmptySB,       NullyEmptySB,  spaceMatters: false));
        NoNullRet(   SpaceSB,      Coalesce(NullySpaceSB,  EmptySB,       NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullySpaceSB,  EmptySB,       NullyFilledSB, spaceMatters: false));
        NoNullRet(   EmptySB,      Coalesce(NullySpaceSB,  EmptySB,       EmptySB,       spaceMatters: false));
        NoNullRet(   SpaceSB,      Coalesce(NullySpaceSB,  EmptySB,       SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullySpaceSB,  EmptySB,       FilledSB,      spaceMatters: false));
        NoNullRet(                 Coalesce(NullySpaceSB,  SpaceSB,       NullSB,        spaceMatters: false));
        NoNullRet($"{EmptySB}", $"{Coalesce(NullySpaceSB,  SpaceSB,       NullSB,        spaceMatters: false)}");
        NoNullRet(   EmptySB,      Coalesce(NullySpaceSB,  SpaceSB,       NullyEmptySB,  spaceMatters: false));
        NoNullRet(   SpaceSB,      Coalesce(NullySpaceSB,  SpaceSB,       NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullySpaceSB,  SpaceSB,       NullyFilledSB, spaceMatters: false));
        NoNullRet(   EmptySB,      Coalesce(NullySpaceSB,  SpaceSB,       EmptySB,       spaceMatters: false));
        NoNullRet(   SpaceSB,      Coalesce(NullySpaceSB,  SpaceSB,       SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullySpaceSB,  SpaceSB,       FilledSB,      spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullySpaceSB,  FilledSB,      NullSB,        spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullySpaceSB,  FilledSB,      NullyEmptySB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullySpaceSB,  FilledSB,      NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullySpaceSB,  FilledSB,      NullyFilledSB, spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullySpaceSB,  FilledSB,      EmptySB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullySpaceSB,  FilledSB,      SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullySpaceSB,  FilledSB,      FilledSB,      spaceMatters: false));
    }

    [TestMethod]
    public void Coalesce_3Args_SBs_StaticSpaceMattersNoExplicit_Batch4()
    {
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, NullSB,        NullSB,        spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, NullSB,        NullyEmptySB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, NullSB,        NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, NullSB,        NullyFilledSB, spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, NullSB,        EmptySB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, NullSB,        SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, NullSB,        FilledSB,      spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, NullyEmptySB,  NullSB,        spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, NullyEmptySB,  NullyEmptySB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, NullyEmptySB,  NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, NullyEmptySB,  NullyFilledSB, spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, NullyEmptySB,  EmptySB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, NullyEmptySB,  SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, NullyEmptySB,  FilledSB,      spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, NullySpaceSB,  NullSB,        spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, NullySpaceSB,  NullyEmptySB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, NullySpaceSB,  NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, NullySpaceSB,  NullyFilledSB, spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, NullySpaceSB,  EmptySB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, NullySpaceSB,  SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, NullySpaceSB,  FilledSB,      spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, NullyFilledSB, NullSB,        spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, NullyFilledSB, NullyEmptySB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, NullyFilledSB, NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, NullyFilledSB, NullyFilledSB, spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, NullyFilledSB, EmptySB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, NullyFilledSB, SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, NullyFilledSB, FilledSB,      spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, EmptySB,       NullSB,        spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, EmptySB,       NullyEmptySB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, EmptySB,       NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, EmptySB,       NullyFilledSB, spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, EmptySB,       EmptySB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, EmptySB,       SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, EmptySB,       FilledSB,      spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, SpaceSB,       NullSB,        spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, SpaceSB,       NullyEmptySB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, SpaceSB,       NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, SpaceSB,       NullyFilledSB, spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, SpaceSB,       EmptySB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, SpaceSB,       SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, SpaceSB,       FilledSB,      spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, FilledSB,      NullSB,        spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, FilledSB,      NullyEmptySB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, FilledSB,      NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, FilledSB,      NullyFilledSB, spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, FilledSB,      EmptySB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, FilledSB,      SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(NullyFilledSB, FilledSB,      FilledSB,      spaceMatters: false));
    }

    [TestMethod]
    public void Coalesce_3Args_SBs_StaticSpaceMattersNoExplicit_Batch5()
    {
        NoNullRet(                 Coalesce(EmptySB,       NullSB,        NullSB,        spaceMatters: false));
        NoNullRet($"{EmptySB}", $"{Coalesce(EmptySB,       NullSB,        NullSB,        spaceMatters: false)}");
        NoNullRet(   EmptySB,      Coalesce(EmptySB,       NullSB,        NullyEmptySB,  spaceMatters: false));
        NoNullRet(   SpaceSB,      Coalesce(EmptySB,       NullSB,        NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(EmptySB,       NullSB,        NullyFilledSB, spaceMatters: false));
        NoNullRet(   EmptySB,      Coalesce(EmptySB,       NullSB,        EmptySB,       spaceMatters: false));
        NoNullRet(   SpaceSB,      Coalesce(EmptySB,       NullSB,        SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(EmptySB,       NullSB,        FilledSB,      spaceMatters: false));
        NoNullRet(                 Coalesce(EmptySB,       NullyEmptySB,  NullSB,        spaceMatters: false));
        NoNullRet($"{EmptySB}", $"{Coalesce(EmptySB,       NullyEmptySB,  NullSB,        spaceMatters: false)}");
        NoNullRet(   EmptySB,      Coalesce(EmptySB,       NullyEmptySB,  NullyEmptySB,  spaceMatters: false));
        NoNullRet(   SpaceSB,      Coalesce(EmptySB,       NullyEmptySB,  NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(EmptySB,       NullyEmptySB,  NullyFilledSB, spaceMatters: false));
        NoNullRet(   EmptySB,      Coalesce(EmptySB,       NullyEmptySB,  EmptySB,       spaceMatters: false));
        NoNullRet(   SpaceSB,      Coalesce(EmptySB,       NullyEmptySB,  SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(EmptySB,       NullyEmptySB,  FilledSB,      spaceMatters: false));
        NoNullRet(                 Coalesce(EmptySB,       NullySpaceSB,  NullSB,        spaceMatters: false));
        NoNullRet($"{EmptySB}", $"{Coalesce(EmptySB,       NullySpaceSB,  NullSB,        spaceMatters: false)}");
        NoNullRet(   EmptySB,      Coalesce(EmptySB,       NullySpaceSB,  NullyEmptySB,  spaceMatters: false));
        NoNullRet(   SpaceSB,      Coalesce(EmptySB,       NullySpaceSB,  NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(EmptySB,       NullySpaceSB,  NullyFilledSB, spaceMatters: false));
        NoNullRet(   EmptySB,      Coalesce(EmptySB,       NullySpaceSB,  EmptySB,       spaceMatters: false));
        NoNullRet(   SpaceSB,      Coalesce(EmptySB,       NullySpaceSB,  SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(EmptySB,       NullySpaceSB,  FilledSB,      spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(EmptySB,       NullyFilledSB, NullSB,        spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(EmptySB,       NullyFilledSB, NullyEmptySB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(EmptySB,       NullyFilledSB, NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(EmptySB,       NullyFilledSB, NullyFilledSB, spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(EmptySB,       NullyFilledSB, EmptySB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(EmptySB,       NullyFilledSB, SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(EmptySB,       NullyFilledSB, FilledSB,      spaceMatters: false));
        NoNullRet(                 Coalesce(EmptySB,       EmptySB,       NullSB,        spaceMatters: false));
        NoNullRet($"{EmptySB}", $"{Coalesce(EmptySB,       EmptySB,       NullSB,        spaceMatters: false)}");
        NoNullRet(   EmptySB,      Coalesce(EmptySB,       EmptySB,       NullyEmptySB,  spaceMatters: false));
        NoNullRet(   SpaceSB,      Coalesce(EmptySB,       EmptySB,       NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(EmptySB,       EmptySB,       NullyFilledSB, spaceMatters: false));
        NoNullRet(   EmptySB,      Coalesce(EmptySB,       EmptySB,       EmptySB,       spaceMatters: false));
        NoNullRet(   SpaceSB,      Coalesce(EmptySB,       EmptySB,       SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(EmptySB,       EmptySB,       FilledSB,      spaceMatters: false));
        NoNullRet(                 Coalesce(EmptySB,       SpaceSB,       NullSB,        spaceMatters: false));
        NoNullRet($"{EmptySB}", $"{Coalesce(EmptySB,       SpaceSB,       NullSB,        spaceMatters: false)}");
        NoNullRet(   EmptySB,      Coalesce(EmptySB,       SpaceSB,       NullyEmptySB,  spaceMatters: false));
        NoNullRet(   SpaceSB,      Coalesce(EmptySB,       SpaceSB,       NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(EmptySB,       SpaceSB,       NullyFilledSB, spaceMatters: false));
        NoNullRet(   EmptySB,      Coalesce(EmptySB,       SpaceSB,       EmptySB,       spaceMatters: false));
        NoNullRet(   SpaceSB,      Coalesce(EmptySB,       SpaceSB,       SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(EmptySB,       SpaceSB,       FilledSB,      spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(EmptySB,       FilledSB,      NullSB,        spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(EmptySB,       FilledSB,      NullyEmptySB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(EmptySB,       FilledSB,      NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(EmptySB,       FilledSB,      NullyFilledSB, spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(EmptySB,       FilledSB,      EmptySB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(EmptySB,       FilledSB,      SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(EmptySB,       FilledSB,      FilledSB,      spaceMatters: false));
    }

    [TestMethod]
    public void Coalesce_3Args_SBs_StaticSpaceMattersNoExplicit_Batch6()
    {
        NoNullRet(                 Coalesce(SpaceSB,       NullSB,        NullSB,        spaceMatters: false));
        NoNullRet($"{EmptySB}", $"{Coalesce(SpaceSB,       NullSB,        NullSB,        spaceMatters: false)}");
        NoNullRet(   EmptySB,      Coalesce(SpaceSB,       NullSB,        NullyEmptySB,  spaceMatters: false));
        NoNullRet(   SpaceSB,      Coalesce(SpaceSB,       NullSB,        NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(SpaceSB,       NullSB,        NullyFilledSB, spaceMatters: false));
        NoNullRet(   EmptySB,      Coalesce(SpaceSB,       NullSB,        EmptySB,       spaceMatters: false));
        NoNullRet(   SpaceSB,      Coalesce(SpaceSB,       NullSB,        SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(SpaceSB,       NullSB,        FilledSB,      spaceMatters: false));
        NoNullRet(                 Coalesce(SpaceSB,       NullyEmptySB,  NullSB,        spaceMatters: false));
        NoNullRet($"{EmptySB}", $"{Coalesce(SpaceSB,       NullyEmptySB,  NullSB,        spaceMatters: false)}");
        NoNullRet(   EmptySB,      Coalesce(SpaceSB,       NullyEmptySB,  NullyEmptySB,  spaceMatters: false));
        NoNullRet(   SpaceSB,      Coalesce(SpaceSB,       NullyEmptySB,  NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(SpaceSB,       NullyEmptySB,  NullyFilledSB, spaceMatters: false));
        NoNullRet(   EmptySB,      Coalesce(SpaceSB,       NullyEmptySB,  EmptySB,       spaceMatters: false));
        NoNullRet(   SpaceSB,      Coalesce(SpaceSB,       NullyEmptySB,  SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(SpaceSB,       NullyEmptySB,  FilledSB,      spaceMatters: false));
        NoNullRet(                 Coalesce(SpaceSB,       NullySpaceSB,  NullSB,        spaceMatters: false));
        NoNullRet($"{EmptySB}", $"{Coalesce(SpaceSB,       NullySpaceSB,  NullSB,        spaceMatters: false)}");
        NoNullRet(   EmptySB,      Coalesce(SpaceSB,       NullySpaceSB,  NullyEmptySB,  spaceMatters: false));
        NoNullRet(   SpaceSB,      Coalesce(SpaceSB,       NullySpaceSB,  NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(SpaceSB,       NullySpaceSB,  NullyFilledSB, spaceMatters: false));
        NoNullRet(   EmptySB,      Coalesce(SpaceSB,       NullySpaceSB,  EmptySB,       spaceMatters: false));
        NoNullRet(   SpaceSB,      Coalesce(SpaceSB,       NullySpaceSB,  SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(SpaceSB,       NullySpaceSB,  FilledSB,      spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(SpaceSB,       NullyFilledSB, NullSB,        spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(SpaceSB,       NullyFilledSB, NullyEmptySB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(SpaceSB,       NullyFilledSB, NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(SpaceSB,       NullyFilledSB, NullyFilledSB, spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(SpaceSB,       NullyFilledSB, EmptySB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(SpaceSB,       NullyFilledSB, SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(SpaceSB,       NullyFilledSB, FilledSB,      spaceMatters: false));
        NoNullRet(                 Coalesce(SpaceSB,       EmptySB,       NullSB,        spaceMatters: false));
        NoNullRet($"{EmptySB}", $"{Coalesce(SpaceSB,       EmptySB,       NullSB,        spaceMatters: false)}");
        NoNullRet(   EmptySB,      Coalesce(SpaceSB,       EmptySB,       NullyEmptySB,  spaceMatters: false));
        NoNullRet(   SpaceSB,      Coalesce(SpaceSB,       EmptySB,       NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(SpaceSB,       EmptySB,       NullyFilledSB, spaceMatters: false));
        NoNullRet(   EmptySB,      Coalesce(SpaceSB,       EmptySB,       EmptySB,       spaceMatters: false));
        NoNullRet(   SpaceSB,      Coalesce(SpaceSB,       EmptySB,       SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(SpaceSB,       EmptySB,       FilledSB,      spaceMatters: false));
        NoNullRet(                 Coalesce(SpaceSB,       SpaceSB,       NullSB,        spaceMatters: false));
        NoNullRet($"{EmptySB}", $"{Coalesce(SpaceSB,       SpaceSB,       NullSB,        spaceMatters: false)}");
        NoNullRet(   EmptySB,      Coalesce(SpaceSB,       SpaceSB,       NullyEmptySB,  spaceMatters: false));
        NoNullRet(   SpaceSB,      Coalesce(SpaceSB,       SpaceSB,       NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(SpaceSB,       SpaceSB,       NullyFilledSB, spaceMatters: false));
        NoNullRet(   EmptySB,      Coalesce(SpaceSB,       SpaceSB,       EmptySB,       spaceMatters: false));
        NoNullRet(   SpaceSB,      Coalesce(SpaceSB,       SpaceSB,       SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(SpaceSB,       SpaceSB,       FilledSB,      spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(SpaceSB,       FilledSB,      NullSB,        spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(SpaceSB,       FilledSB,      NullyEmptySB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(SpaceSB,       FilledSB,      NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(SpaceSB,       FilledSB,      NullyFilledSB, spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(SpaceSB,       FilledSB,      EmptySB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(SpaceSB,       FilledSB,      SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(SpaceSB,       FilledSB,      FilledSB,      spaceMatters: false));
    }

    [TestMethod]
    public void Coalesce_3Args_SBs_StaticSpaceMattersNoExplicit_Batch7()
    {
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      NullSB,        NullSB,        spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      NullSB,        NullyEmptySB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      NullSB,        NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      NullSB,        NullyFilledSB, spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      NullSB,        EmptySB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      NullSB,        SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      NullSB,        FilledSB,      spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      NullyEmptySB,  NullSB,        spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      NullyEmptySB,  NullyEmptySB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      NullyEmptySB,  NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      NullyEmptySB,  NullyFilledSB, spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      NullyEmptySB,  EmptySB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      NullyEmptySB,  SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      NullyEmptySB,  FilledSB,      spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      NullySpaceSB,  NullSB,        spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      NullySpaceSB,  NullyEmptySB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      NullySpaceSB,  NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      NullySpaceSB,  NullyFilledSB, spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      NullySpaceSB,  EmptySB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      NullySpaceSB,  SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      NullySpaceSB,  FilledSB,      spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      NullyFilledSB, NullSB,        spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      NullyFilledSB, NullyEmptySB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      NullyFilledSB, NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      NullyFilledSB, NullyFilledSB, spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      NullyFilledSB, EmptySB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      NullyFilledSB, SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      NullyFilledSB, FilledSB,      spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      EmptySB,       NullSB,        spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      EmptySB,       NullyEmptySB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      EmptySB,       NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      EmptySB,       NullyFilledSB, spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      EmptySB,       EmptySB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      EmptySB,       SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      EmptySB,       FilledSB,      spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      SpaceSB,       NullSB,        spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      SpaceSB,       NullyEmptySB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      SpaceSB,       NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      SpaceSB,       NullyFilledSB, spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      SpaceSB,       EmptySB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      SpaceSB,       SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      SpaceSB,       FilledSB,      spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      FilledSB,      NullSB,        spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      FilledSB,      NullyEmptySB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      FilledSB,      NullySpaceSB,  spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      FilledSB,      NullyFilledSB, spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      FilledSB,      EmptySB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      FilledSB,      SpaceSB,       spaceMatters: false));
        NoNullRet(   FilledSB,     Coalesce(FilledSB,      FilledSB,      FilledSB,      spaceMatters: false));
    }
}