namespace JJ.Framework.Existence.Core.Tests;

[TestClass]
public class Coalesce_3Args_ValuesToText_ExtensionsZeroMattersFlagsInBack : TestBase
{
    [TestMethod]
    public void Coalesce_3Args_ValuesToText_ExtensionsZeroMattersFlagsInBack_Batch1()
    {
        NoNullRet("",   NullNum.Coalesce(  Nully0, NullText                           ));
        NoNullRet("",   NullNum.Coalesce(  Nully0, NullText,        zeroMatters: false));
        NoNullRet("",   NullNum.Coalesce(  Nully0, NullText,                     false));
        NoNullRet("0",  NullNum.Coalesce(  Nully0, NullText,        zeroMatters       ));
        NoNullRet("0",  NullNum.Coalesce(  Nully0, NullText,        zeroMatters: true ));
        NoNullRet("0",  NullNum.Coalesce(  Nully0, NullText,                     true ));
        NoNullRet("",   NullNum.Coalesce(  Nully0, Empty                              ));
        NoNullRet("",   NullNum.Coalesce(  Nully0, Empty,           zeroMatters: false));
        NoNullRet("",   NullNum.Coalesce(  Nully0, Empty,                        false));
        NoNullRet("0",  NullNum.Coalesce(  Nully0, Empty,           zeroMatters       ));
        NoNullRet("0",  NullNum.Coalesce(  Nully0, Empty,           zeroMatters: true ));
        NoNullRet("0",  NullNum.Coalesce(  Nully0, Empty,                        true ));
        NoNullRet(" ",  NullNum.Coalesce(  Nully0, Space                              ));
        NoNullRet(" ",  NullNum.Coalesce(  Nully0, Space,           zeroMatters: false));
        NoNullRet(" ",  NullNum.Coalesce(  Nully0, Space,                        false));
        NoNullRet("0",  NullNum.Coalesce(  Nully0, Space,           zeroMatters       ));
        NoNullRet("0",  NullNum.Coalesce(  Nully0, Space,           zeroMatters: true ));
        NoNullRet("0",  NullNum.Coalesce(  Nully0, Space,                        true ));
        NoNullRet(Text, NullNum.Coalesce(  Nully0, Text                               ));
        NoNullRet(Text, NullNum.Coalesce(  Nully0, Text,            zeroMatters: false));
        NoNullRet(Text, NullNum.Coalesce(  Nully0, Text,                         false));
        NoNullRet("0",  NullNum.Coalesce(  Nully0, Text,            zeroMatters       ));
        NoNullRet("0",  NullNum.Coalesce(  Nully0, Text,            zeroMatters: true ));
        NoNullRet("0",  NullNum.Coalesce(  Nully0, Text,                         true ));
        NoNullRet("",   NullNum.Coalesce(  Nully0, NullyEmpty                         ));
        NoNullRet("",   NullNum.Coalesce(  Nully0, NullyEmpty,      zeroMatters: false));
        NoNullRet("",   NullNum.Coalesce(  Nully0, NullyEmpty,                   false));
        NoNullRet("0",  NullNum.Coalesce(  Nully0, NullyEmpty,      zeroMatters       ));
        NoNullRet("0",  NullNum.Coalesce(  Nully0, NullyEmpty,      zeroMatters: true ));
        NoNullRet("0",  NullNum.Coalesce(  Nully0, NullyEmpty,                   true ));
        NoNullRet(" ",  NullNum.Coalesce(  Nully0, NullySpace                         ));
        NoNullRet(" ",  NullNum.Coalesce(  Nully0, NullySpace,      zeroMatters: false));
        NoNullRet(" ",  NullNum.Coalesce(  Nully0, NullySpace,                   false));
        NoNullRet("0",  NullNum.Coalesce(  Nully0, NullySpace,      zeroMatters       ));
        NoNullRet("0",  NullNum.Coalesce(  Nully0, NullySpace,      zeroMatters: true ));
        NoNullRet("0",  NullNum.Coalesce(  Nully0, NullySpace,                   true ));
        NoNullRet(Text, NullNum.Coalesce(  Nully0, NullyFilledText                    ));
        NoNullRet(Text, NullNum.Coalesce(  Nully0, NullyFilledText, zeroMatters: false));
        NoNullRet(Text, NullNum.Coalesce(  Nully0, NullyFilledText,              false));
        NoNullRet("0",  NullNum.Coalesce(  Nully0, NullyFilledText, zeroMatters       ));
        NoNullRet("0",  NullNum.Coalesce(  Nully0, NullyFilledText, zeroMatters: true ));
        NoNullRet("0",  NullNum.Coalesce(  Nully0, NullyFilledText,              true ));
        NoNullRet("1",  NullNum.Coalesce(  Nully1, NullText                           ));
        NoNullRet("1",  NullNum.Coalesce(  Nully1, NullText,        zeroMatters: false));
        NoNullRet("1",  NullNum.Coalesce(  Nully1, NullText,                     false));
        NoNullRet("1",  NullNum.Coalesce(  Nully1, NullText,        zeroMatters       ));
        NoNullRet("1",  NullNum.Coalesce(  Nully1, NullText,        zeroMatters: true ));
        NoNullRet("1",  NullNum.Coalesce(  Nully1, NullText,                     true ));
        NoNullRet("1",  NullNum.Coalesce(  Nully1, Empty                              ));
        NoNullRet("1",  NullNum.Coalesce(  Nully1, Empty,           zeroMatters: false));
        NoNullRet("1",  NullNum.Coalesce(  Nully1, Empty,                        false));
        NoNullRet("1",  NullNum.Coalesce(  Nully1, Empty,           zeroMatters       ));
        NoNullRet("1",  NullNum.Coalesce(  Nully1, Empty,           zeroMatters: true ));
        NoNullRet("1",  NullNum.Coalesce(  Nully1, Empty,                        true ));
        NoNullRet("1",  NullNum.Coalesce(  Nully1, Space                              ));
        NoNullRet("1",  NullNum.Coalesce(  Nully1, Space,           zeroMatters: false));
        NoNullRet("1",  NullNum.Coalesce(  Nully1, Space,                        false));
        NoNullRet("1",  NullNum.Coalesce(  Nully1, Space,           zeroMatters       ));
        NoNullRet("1",  NullNum.Coalesce(  Nully1, Space,           zeroMatters: true ));
        NoNullRet("1",  NullNum.Coalesce(  Nully1, Space,                        true ));
        NoNullRet("1",  NullNum.Coalesce(  Nully1, Text                               ));
        NoNullRet("1",  NullNum.Coalesce(  Nully1, Text,            zeroMatters: false));
        NoNullRet("1",  NullNum.Coalesce(  Nully1, Text,                         false));
        NoNullRet("1",  NullNum.Coalesce(  Nully1, Text,            zeroMatters       ));
        NoNullRet("1",  NullNum.Coalesce(  Nully1, Text,            zeroMatters: true ));
        NoNullRet("1",  NullNum.Coalesce(  Nully1, Text,                         true ));
        NoNullRet("1",  NullNum.Coalesce(  Nully1, NullyEmpty                         ));
        NoNullRet("1",  NullNum.Coalesce(  Nully1, NullyEmpty,      zeroMatters: false));
        NoNullRet("1",  NullNum.Coalesce(  Nully1, NullyEmpty,                   false));
        NoNullRet("1",  NullNum.Coalesce(  Nully1, NullyEmpty,      zeroMatters       ));
        NoNullRet("1",  NullNum.Coalesce(  Nully1, NullyEmpty,      zeroMatters: true ));
        NoNullRet("1",  NullNum.Coalesce(  Nully1, NullyEmpty,                   true ));
        NoNullRet("1",  NullNum.Coalesce(  Nully1, NullySpace                         ));
        NoNullRet("1",  NullNum.Coalesce(  Nully1, NullySpace,      zeroMatters: false));
        NoNullRet("1",  NullNum.Coalesce(  Nully1, NullySpace,                   false));
        NoNullRet("1",  NullNum.Coalesce(  Nully1, NullySpace,      zeroMatters       ));
        NoNullRet("1",  NullNum.Coalesce(  Nully1, NullySpace,      zeroMatters: true ));
        NoNullRet("1",  NullNum.Coalesce(  Nully1, NullySpace,                   true ));
        NoNullRet("1",  NullNum.Coalesce(  Nully1, NullyFilledText                    ));
        NoNullRet("1",  NullNum.Coalesce(  Nully1, NullyFilledText, zeroMatters: false));
        NoNullRet("1",  NullNum.Coalesce(  Nully1, NullyFilledText,              false));
        NoNullRet("1",  NullNum.Coalesce(  Nully1, NullyFilledText, zeroMatters       ));
        NoNullRet("1",  NullNum.Coalesce(  Nully1, NullyFilledText, zeroMatters: true ));
        NoNullRet("1",  NullNum.Coalesce(  Nully1, NullyFilledText,              true ));
        NoNullRet("",   NullNum.Coalesce(       0, NullText                           ));
        NoNullRet("",   NullNum.Coalesce(       0, NullText,        zeroMatters: false));
        NoNullRet("",   NullNum.Coalesce(       0, NullText,                     false));
        NoNullRet("0",  NullNum.Coalesce(       0, NullText,        zeroMatters       ));
        NoNullRet("0",  NullNum.Coalesce(       0, NullText,        zeroMatters: true ));
        NoNullRet("0",  NullNum.Coalesce(       0, NullText,                     true ));
        NoNullRet("",   NullNum.Coalesce(       0, Empty                              ));
        NoNullRet("",   NullNum.Coalesce(       0, Empty,           zeroMatters: false));
        NoNullRet("",   NullNum.Coalesce(       0, Empty,                        false));
        NoNullRet("0",  NullNum.Coalesce(       0, Empty,           zeroMatters       ));
        NoNullRet("0",  NullNum.Coalesce(       0, Empty,           zeroMatters: true ));
        NoNullRet("0",  NullNum.Coalesce(       0, Empty,                        true ));
        NoNullRet(" ",  NullNum.Coalesce(       0, Space                              ));
        NoNullRet(" ",  NullNum.Coalesce(       0, Space,           zeroMatters: false));
        NoNullRet(" ",  NullNum.Coalesce(       0, Space,                        false));
        NoNullRet("0",  NullNum.Coalesce(       0, Space,           zeroMatters       ));
        NoNullRet("0",  NullNum.Coalesce(       0, Space,           zeroMatters: true ));
        NoNullRet("0",  NullNum.Coalesce(       0, Space,                        true ));
        NoNullRet(Text, NullNum.Coalesce(       0, Text                               ));
        NoNullRet(Text, NullNum.Coalesce(       0, Text,            zeroMatters: false));
        NoNullRet(Text, NullNum.Coalesce(       0, Text,                         false));
        NoNullRet("0",  NullNum.Coalesce(       0, Text,            zeroMatters       ));
        NoNullRet("0",  NullNum.Coalesce(       0, Text,            zeroMatters: true ));
        NoNullRet("0",  NullNum.Coalesce(       0, Text,                         true ));
        NoNullRet("",   NullNum.Coalesce(       0, NullyEmpty                         ));
        NoNullRet("",   NullNum.Coalesce(       0, NullyEmpty,      zeroMatters: false));
        NoNullRet("",   NullNum.Coalesce(       0, NullyEmpty,                   false));
        NoNullRet("0",  NullNum.Coalesce(       0, NullyEmpty,      zeroMatters       ));
        NoNullRet("0",  NullNum.Coalesce(       0, NullyEmpty,      zeroMatters: true ));
        NoNullRet("0",  NullNum.Coalesce(       0, NullyEmpty,                   true ));
        NoNullRet(" ",  NullNum.Coalesce(       0, NullySpace                         ));
        NoNullRet(" ",  NullNum.Coalesce(       0, NullySpace,      zeroMatters: false));
        NoNullRet(" ",  NullNum.Coalesce(       0, NullySpace,                   false));
        NoNullRet("0",  NullNum.Coalesce(       0, NullySpace,      zeroMatters       ));
        NoNullRet("0",  NullNum.Coalesce(       0, NullySpace,      zeroMatters: true ));
        NoNullRet("0",  NullNum.Coalesce(       0, NullySpace,                   true ));
        NoNullRet(Text, NullNum.Coalesce(       0, NullyFilledText                    ));
        NoNullRet(Text, NullNum.Coalesce(       0, NullyFilledText, zeroMatters: false));
        NoNullRet(Text, NullNum.Coalesce(       0, NullyFilledText,              false));
        NoNullRet("0",  NullNum.Coalesce(       0, NullyFilledText, zeroMatters       ));
        NoNullRet("0",  NullNum.Coalesce(       0, NullyFilledText, zeroMatters: true ));
        NoNullRet("0",  NullNum.Coalesce(       0, NullyFilledText,              true ));
        NoNullRet("1",  NullNum.Coalesce(       1, NullText                           ));
        NoNullRet("1",  NullNum.Coalesce(       1, NullText,        zeroMatters: false));
        NoNullRet("1",  NullNum.Coalesce(       1, NullText,                     false));
        NoNullRet("1",  NullNum.Coalesce(       1, NullText,        zeroMatters       ));
        NoNullRet("1",  NullNum.Coalesce(       1, NullText,        zeroMatters: true ));
        NoNullRet("1",  NullNum.Coalesce(       1, NullText,                     true ));
        NoNullRet("1",  NullNum.Coalesce(       1, Empty                              ));
        NoNullRet("1",  NullNum.Coalesce(       1, Empty,           zeroMatters: false));
        NoNullRet("1",  NullNum.Coalesce(       1, Empty,                        false));
        NoNullRet("1",  NullNum.Coalesce(       1, Empty,           zeroMatters       ));
        NoNullRet("1",  NullNum.Coalesce(       1, Empty,           zeroMatters: true ));
        NoNullRet("1",  NullNum.Coalesce(       1, Empty,                        true ));
        NoNullRet("1",  NullNum.Coalesce(       1, Space                              ));
        NoNullRet("1",  NullNum.Coalesce(       1, Space,           zeroMatters: false));
        NoNullRet("1",  NullNum.Coalesce(       1, Space,                        false));
        NoNullRet("1",  NullNum.Coalesce(       1, Space,           zeroMatters       ));
        NoNullRet("1",  NullNum.Coalesce(       1, Space,           zeroMatters: true ));
        NoNullRet("1",  NullNum.Coalesce(       1, Space,                        true ));
        NoNullRet("1",  NullNum.Coalesce(       1, Text                               ));
        NoNullRet("1",  NullNum.Coalesce(       1, Text,            zeroMatters: false));
        NoNullRet("1",  NullNum.Coalesce(       1, Text,                         false));
        NoNullRet("1",  NullNum.Coalesce(       1, Text,            zeroMatters       ));
        NoNullRet("1",  NullNum.Coalesce(       1, Text,            zeroMatters: true ));
        NoNullRet("1",  NullNum.Coalesce(       1, Text,                         true ));
        NoNullRet("1",  NullNum.Coalesce(       1, NullyEmpty                         ));
        NoNullRet("1",  NullNum.Coalesce(       1, NullyEmpty,      zeroMatters: false));
        NoNullRet("1",  NullNum.Coalesce(       1, NullyEmpty,                   false));
        NoNullRet("1",  NullNum.Coalesce(       1, NullyEmpty,      zeroMatters       ));
        NoNullRet("1",  NullNum.Coalesce(       1, NullyEmpty,      zeroMatters: true ));
        NoNullRet("1",  NullNum.Coalesce(       1, NullyEmpty,                   true ));
        NoNullRet("1",  NullNum.Coalesce(       1, NullySpace                         ));
        NoNullRet("1",  NullNum.Coalesce(       1, NullySpace,      zeroMatters: false));
        NoNullRet("1",  NullNum.Coalesce(       1, NullySpace,                   false));
        NoNullRet("1",  NullNum.Coalesce(       1, NullySpace,      zeroMatters       ));
        NoNullRet("1",  NullNum.Coalesce(       1, NullySpace,      zeroMatters: true ));
        NoNullRet("1",  NullNum.Coalesce(       1, NullySpace,                   true ));
        NoNullRet("1",  NullNum.Coalesce(       1, NullyFilledText                    ));
        NoNullRet("1",  NullNum.Coalesce(       1, NullyFilledText, zeroMatters: false));
        NoNullRet("1",  NullNum.Coalesce(       1, NullyFilledText,              false));
        NoNullRet("1",  NullNum.Coalesce(       1, NullyFilledText, zeroMatters       ));
        NoNullRet("1",  NullNum.Coalesce(       1, NullyFilledText, zeroMatters: true ));
        NoNullRet("1",  NullNum.Coalesce(       1, NullyFilledText,              true ));
    }

    [TestMethod]
    public void Coalesce_3Args_ValuesToText_ExtensionsZeroMattersFlagsInBack_Batch2()
    {
        NoNullRet("",    Nully0.Coalesce(NullNum, NullText                           ));
        NoNullRet("",    Nully0.Coalesce(NullNum, NullText,        zeroMatters: false));
        NoNullRet("",    Nully0.Coalesce(NullNum, NullText,                     false));
        NoNullRet("0",   Nully0.Coalesce(NullNum, NullText,        zeroMatters       ));
        NoNullRet("0",   Nully0.Coalesce(NullNum, NullText,        zeroMatters: true ));
        NoNullRet("0",   Nully0.Coalesce(NullNum, NullText,                     true ));
        NoNullRet("",    Nully0.Coalesce(NullNum, Empty                              ));
        NoNullRet("",    Nully0.Coalesce(NullNum, Empty,           zeroMatters: false));
        NoNullRet("",    Nully0.Coalesce(NullNum, Empty,                        false));
        NoNullRet("0",   Nully0.Coalesce(NullNum, Empty,           zeroMatters       ));
        NoNullRet("0",   Nully0.Coalesce(NullNum, Empty,           zeroMatters: true ));
        NoNullRet("0",   Nully0.Coalesce(NullNum, Empty,                        true ));
        NoNullRet(" ",   Nully0.Coalesce(NullNum, Space                              ));
        NoNullRet(" ",   Nully0.Coalesce(NullNum, Space,           zeroMatters: false));
        NoNullRet(" ",   Nully0.Coalesce(NullNum, Space,                        false));
        NoNullRet("0",   Nully0.Coalesce(NullNum, Space,           zeroMatters       ));
        NoNullRet("0",   Nully0.Coalesce(NullNum, Space,           zeroMatters: true ));
        NoNullRet("0",   Nully0.Coalesce(NullNum, Space,                        true ));
        NoNullRet(Text,  Nully0.Coalesce(NullNum, Text                               ));
        NoNullRet(Text,  Nully0.Coalesce(NullNum, Text,            zeroMatters: false));
        NoNullRet(Text,  Nully0.Coalesce(NullNum, Text,                         false));
        NoNullRet("0",   Nully0.Coalesce(NullNum, Text,            zeroMatters       ));
        NoNullRet("0",   Nully0.Coalesce(NullNum, Text,            zeroMatters: true ));
        NoNullRet("0",   Nully0.Coalesce(NullNum, Text,                         true ));
        NoNullRet("",    Nully0.Coalesce(NullNum, NullyEmpty                         ));
        NoNullRet("",    Nully0.Coalesce(NullNum, NullyEmpty,      zeroMatters: false));
        NoNullRet("",    Nully0.Coalesce(NullNum, NullyEmpty,                   false));
        NoNullRet("0",   Nully0.Coalesce(NullNum, NullyEmpty,      zeroMatters       ));
        NoNullRet("0",   Nully0.Coalesce(NullNum, NullyEmpty,      zeroMatters: true ));
        NoNullRet("0",   Nully0.Coalesce(NullNum, NullyEmpty,                   true ));
        NoNullRet(" ",   Nully0.Coalesce(NullNum, NullySpace                         ));
        NoNullRet(" ",   Nully0.Coalesce(NullNum, NullySpace,      zeroMatters: false));
        NoNullRet(" ",   Nully0.Coalesce(NullNum, NullySpace,                   false));
        NoNullRet("0",   Nully0.Coalesce(NullNum, NullySpace,      zeroMatters       ));
        NoNullRet("0",   Nully0.Coalesce(NullNum, NullySpace,      zeroMatters: true ));
        NoNullRet("0",   Nully0.Coalesce(NullNum, NullySpace,                   true ));
        NoNullRet(Text,  Nully0.Coalesce(NullNum, NullyFilledText                    ));
        NoNullRet(Text,  Nully0.Coalesce(NullNum, NullyFilledText, zeroMatters: false));
        NoNullRet(Text,  Nully0.Coalesce(NullNum, NullyFilledText,              false));
        NoNullRet("0",   Nully0.Coalesce(NullNum, NullyFilledText, zeroMatters       ));
        NoNullRet("0",   Nully0.Coalesce(NullNum, NullyFilledText, zeroMatters: true ));
        NoNullRet("0",   Nully0.Coalesce(NullNum, NullyFilledText,              true ));
        NoNullRet("1",   Nully0.Coalesce( Nully1, NullText                           ));
        NoNullRet("1",   Nully0.Coalesce( Nully1, NullText,        zeroMatters: false));
        NoNullRet("1",   Nully0.Coalesce( Nully1, NullText,                     false));
        NoNullRet("0",   Nully0.Coalesce( Nully1, NullText,        zeroMatters       ));
        NoNullRet("0",   Nully0.Coalesce( Nully1, NullText,        zeroMatters: true ));
        NoNullRet("0",   Nully0.Coalesce( Nully1, NullText,                     true ));
        NoNullRet("1",   Nully0.Coalesce( Nully1, Empty                              ));
        NoNullRet("1",   Nully0.Coalesce( Nully1, Empty,           zeroMatters: false));
        NoNullRet("1",   Nully0.Coalesce( Nully1, Empty,                        false));
        NoNullRet("0",   Nully0.Coalesce( Nully1, Empty,           zeroMatters       ));
        NoNullRet("0",   Nully0.Coalesce( Nully1, Empty,           zeroMatters: true ));
        NoNullRet("0",   Nully0.Coalesce( Nully1, Empty,                        true ));
        NoNullRet("1",   Nully0.Coalesce( Nully1, Space                              ));
        NoNullRet("1",   Nully0.Coalesce( Nully1, Space,           zeroMatters: false));
        NoNullRet("1",   Nully0.Coalesce( Nully1, Space,                        false));
        NoNullRet("0",   Nully0.Coalesce( Nully1, Space,           zeroMatters       ));
        NoNullRet("0",   Nully0.Coalesce( Nully1, Space,           zeroMatters: true ));
        NoNullRet("0",   Nully0.Coalesce( Nully1, Space,                        true ));
        NoNullRet("1",   Nully0.Coalesce( Nully1, Text                               ));
        NoNullRet("1",   Nully0.Coalesce( Nully1, Text,            zeroMatters: false));
        NoNullRet("1",   Nully0.Coalesce( Nully1, Text,                         false));
        NoNullRet("0",   Nully0.Coalesce( Nully1, Text,            zeroMatters       ));
        NoNullRet("0",   Nully0.Coalesce( Nully1, Text,            zeroMatters: true ));
        NoNullRet("0",   Nully0.Coalesce( Nully1, Text,                         true ));
        NoNullRet("1",   Nully0.Coalesce( Nully1, NullyEmpty                         ));
        NoNullRet("1",   Nully0.Coalesce( Nully1, NullyEmpty,      zeroMatters: false));
        NoNullRet("1",   Nully0.Coalesce( Nully1, NullyEmpty,                   false));
        NoNullRet("0",   Nully0.Coalesce( Nully1, NullyEmpty,      zeroMatters       ));
        NoNullRet("0",   Nully0.Coalesce( Nully1, NullyEmpty,      zeroMatters: true ));
        NoNullRet("0",   Nully0.Coalesce( Nully1, NullyEmpty,                   true ));
        NoNullRet("1",   Nully0.Coalesce( Nully1, NullySpace                         ));
        NoNullRet("1",   Nully0.Coalesce( Nully1, NullySpace,      zeroMatters: false));
        NoNullRet("1",   Nully0.Coalesce( Nully1, NullySpace,                   false));
        NoNullRet("0",   Nully0.Coalesce( Nully1, NullySpace,      zeroMatters       ));
        NoNullRet("0",   Nully0.Coalesce( Nully1, NullySpace,      zeroMatters: true ));
        NoNullRet("0",   Nully0.Coalesce( Nully1, NullySpace,                   true ));
        NoNullRet("1",   Nully0.Coalesce( Nully1, NullyFilledText                    ));
        NoNullRet("1",   Nully0.Coalesce( Nully1, NullyFilledText, zeroMatters: false));
        NoNullRet("1",   Nully0.Coalesce( Nully1, NullyFilledText,              false));
        NoNullRet("0",   Nully0.Coalesce( Nully1, NullyFilledText, zeroMatters       ));
        NoNullRet("0",   Nully0.Coalesce( Nully1, NullyFilledText, zeroMatters: true ));
        NoNullRet("0",   Nully0.Coalesce( Nully1, NullyFilledText,              true ));
        NoNullRet("1",   Nully0.Coalesce(      1, NullText                           ));
        NoNullRet("1",   Nully0.Coalesce(      1, NullText,        zeroMatters: false));
        NoNullRet("1",   Nully0.Coalesce(      1, NullText,                     false));
        NoNullRet("0",   Nully0.Coalesce(      1, NullText,        zeroMatters       ));
        NoNullRet("0",   Nully0.Coalesce(      1, NullText,        zeroMatters: true ));
        NoNullRet("0",   Nully0.Coalesce(      1, NullText,                     true ));
        NoNullRet("1",   Nully0.Coalesce(      1, Empty                              ));
        NoNullRet("1",   Nully0.Coalesce(      1, Empty,           zeroMatters: false));
        NoNullRet("1",   Nully0.Coalesce(      1, Empty,                        false));
        NoNullRet("0",   Nully0.Coalesce(      1, Empty,           zeroMatters       ));
        NoNullRet("0",   Nully0.Coalesce(      1, Empty,           zeroMatters: true ));
        NoNullRet("0",   Nully0.Coalesce(      1, Empty,                        true ));
        NoNullRet("1",   Nully0.Coalesce(      1, Space                              ));
        NoNullRet("1",   Nully0.Coalesce(      1, Space,           zeroMatters: false));
        NoNullRet("1",   Nully0.Coalesce(      1, Space,                        false));
        NoNullRet("0",   Nully0.Coalesce(      1, Space,           zeroMatters       ));
        NoNullRet("0",   Nully0.Coalesce(      1, Space,           zeroMatters: true ));
        NoNullRet("0",   Nully0.Coalesce(      1, Space,                        true ));
        NoNullRet("1",   Nully0.Coalesce(      1, Text                               ));
        NoNullRet("1",   Nully0.Coalesce(      1, Text,            zeroMatters: false));
        NoNullRet("1",   Nully0.Coalesce(      1, Text,                         false));
        NoNullRet("0",   Nully0.Coalesce(      1, Text,            zeroMatters       ));
        NoNullRet("0",   Nully0.Coalesce(      1, Text,            zeroMatters: true ));
        NoNullRet("0",   Nully0.Coalesce(      1, Text,                         true ));
        NoNullRet("1",   Nully0.Coalesce(      1, NullyEmpty                         ));
        NoNullRet("1",   Nully0.Coalesce(      1, NullyEmpty,      zeroMatters: false));
        NoNullRet("1",   Nully0.Coalesce(      1, NullyEmpty,                   false));
        NoNullRet("0",   Nully0.Coalesce(      1, NullyEmpty,      zeroMatters       ));
        NoNullRet("0",   Nully0.Coalesce(      1, NullyEmpty,      zeroMatters: true ));
        NoNullRet("0",   Nully0.Coalesce(      1, NullyEmpty,                   true ));
        NoNullRet("1",   Nully0.Coalesce(      1, NullySpace                         ));
        NoNullRet("1",   Nully0.Coalesce(      1, NullySpace,      zeroMatters: false));
        NoNullRet("1",   Nully0.Coalesce(      1, NullySpace,                   false));
        NoNullRet("0",   Nully0.Coalesce(      1, NullySpace,      zeroMatters       ));
        NoNullRet("0",   Nully0.Coalesce(      1, NullySpace,      zeroMatters: true ));
        NoNullRet("0",   Nully0.Coalesce(      1, NullySpace,                   true ));
        NoNullRet("1",   Nully0.Coalesce(      1, NullyFilledText                    ));
        NoNullRet("1",   Nully0.Coalesce(      1, NullyFilledText, zeroMatters: false));
        NoNullRet("1",   Nully0.Coalesce(      1, NullyFilledText,              false));
        NoNullRet("0",   Nully0.Coalesce(      1, NullyFilledText, zeroMatters       ));
        NoNullRet("0",   Nully0.Coalesce(      1, NullyFilledText, zeroMatters: true ));
        NoNullRet("0",   Nully0.Coalesce(      1, NullyFilledText,              true ));
    }

    [TestMethod]
    public void Coalesce_3Args_ValuesToText_ExtensionsZeroMattersFlagsInBack_Batch3()
    {
        NoNullRet("1",   Nully1.Coalesce(NullNum, NullText                           ));
        NoNullRet("1",   Nully1.Coalesce(NullNum, NullText,        zeroMatters: false));
        NoNullRet("1",   Nully1.Coalesce(NullNum, NullText,                     false));
        NoNullRet("1",   Nully1.Coalesce(NullNum, NullText,        zeroMatters       ));
        NoNullRet("1",   Nully1.Coalesce(NullNum, NullText,        zeroMatters: true ));
        NoNullRet("1",   Nully1.Coalesce(NullNum, NullText,                     true ));
        NoNullRet("1",   Nully1.Coalesce(NullNum, Empty                              ));
        NoNullRet("1",   Nully1.Coalesce(NullNum, Empty,           zeroMatters: false));
        NoNullRet("1",   Nully1.Coalesce(NullNum, Empty,                        false));
        NoNullRet("1",   Nully1.Coalesce(NullNum, Empty,           zeroMatters       ));
        NoNullRet("1",   Nully1.Coalesce(NullNum, Empty,           zeroMatters: true ));
        NoNullRet("1",   Nully1.Coalesce(NullNum, Empty,                        true ));
        NoNullRet("1",   Nully1.Coalesce(NullNum, Space                              ));
        NoNullRet("1",   Nully1.Coalesce(NullNum, Space,           zeroMatters: false));
        NoNullRet("1",   Nully1.Coalesce(NullNum, Space,                        false));
        NoNullRet("1",   Nully1.Coalesce(NullNum, Space,           zeroMatters       ));
        NoNullRet("1",   Nully1.Coalesce(NullNum, Space,           zeroMatters: true ));
        NoNullRet("1",   Nully1.Coalesce(NullNum, Space,                        true ));
        NoNullRet("1",   Nully1.Coalesce(NullNum, Text                               ));
        NoNullRet("1",   Nully1.Coalesce(NullNum, Text,            zeroMatters: false));
        NoNullRet("1",   Nully1.Coalesce(NullNum, Text,                         false));
        NoNullRet("1",   Nully1.Coalesce(NullNum, Text,            zeroMatters       ));
        NoNullRet("1",   Nully1.Coalesce(NullNum, Text,            zeroMatters: true ));
        NoNullRet("1",   Nully1.Coalesce(NullNum, Text,                         true ));
        NoNullRet("1",   Nully1.Coalesce(NullNum, NullyEmpty                         ));
        NoNullRet("1",   Nully1.Coalesce(NullNum, NullyEmpty,      zeroMatters: false));
        NoNullRet("1",   Nully1.Coalesce(NullNum, NullyEmpty,                   false));
        NoNullRet("1",   Nully1.Coalesce(NullNum, NullyEmpty,      zeroMatters       ));
        NoNullRet("1",   Nully1.Coalesce(NullNum, NullyEmpty,      zeroMatters: true ));
        NoNullRet("1",   Nully1.Coalesce(NullNum, NullyEmpty,                   true ));
        NoNullRet("1",   Nully1.Coalesce(NullNum, NullySpace                         ));
        NoNullRet("1",   Nully1.Coalesce(NullNum, NullySpace,      zeroMatters: false));
        NoNullRet("1",   Nully1.Coalesce(NullNum, NullySpace,                   false));
        NoNullRet("1",   Nully1.Coalesce(NullNum, NullySpace,      zeroMatters       ));
        NoNullRet("1",   Nully1.Coalesce(NullNum, NullySpace,      zeroMatters: true ));
        NoNullRet("1",   Nully1.Coalesce(NullNum, NullySpace,                   true ));
        NoNullRet("1",   Nully1.Coalesce(NullNum, NullyFilledText                    ));
        NoNullRet("1",   Nully1.Coalesce(NullNum, NullyFilledText, zeroMatters: false));
        NoNullRet("1",   Nully1.Coalesce(NullNum, NullyFilledText,              false));
        NoNullRet("1",   Nully1.Coalesce(NullNum, NullyFilledText, zeroMatters       ));
        NoNullRet("1",   Nully1.Coalesce(NullNum, NullyFilledText, zeroMatters: true ));
        NoNullRet("1",   Nully1.Coalesce(NullNum, NullyFilledText,              true ));
        NoNullRet("1",   Nully1.Coalesce( Nully0, NullText                           ));
        NoNullRet("1",   Nully1.Coalesce( Nully0, NullText,        zeroMatters: false));
        NoNullRet("1",   Nully1.Coalesce( Nully0, NullText,                     false));
        NoNullRet("1",   Nully1.Coalesce( Nully0, NullText,        zeroMatters       ));
        NoNullRet("1",   Nully1.Coalesce( Nully0, NullText,        zeroMatters: true ));
        NoNullRet("1",   Nully1.Coalesce( Nully0, NullText,                     true ));
        NoNullRet("1",   Nully1.Coalesce( Nully0, Empty                              ));
        NoNullRet("1",   Nully1.Coalesce( Nully0, Empty,           zeroMatters: false));
        NoNullRet("1",   Nully1.Coalesce( Nully0, Empty,                        false));
        NoNullRet("1",   Nully1.Coalesce( Nully0, Empty,           zeroMatters       ));
        NoNullRet("1",   Nully1.Coalesce( Nully0, Empty,           zeroMatters: true ));
        NoNullRet("1",   Nully1.Coalesce( Nully0, Empty,                        true ));
        NoNullRet("1",   Nully1.Coalesce( Nully0, Space                              ));
        NoNullRet("1",   Nully1.Coalesce( Nully0, Space,           zeroMatters: false));
        NoNullRet("1",   Nully1.Coalesce( Nully0, Space,                        false));
        NoNullRet("1",   Nully1.Coalesce( Nully0, Space,           zeroMatters       ));
        NoNullRet("1",   Nully1.Coalesce( Nully0, Space,           zeroMatters: true ));
        NoNullRet("1",   Nully1.Coalesce( Nully0, Space,                        true ));
        NoNullRet("1",   Nully1.Coalesce( Nully0, Text                               ));
        NoNullRet("1",   Nully1.Coalesce( Nully0, Text,            zeroMatters: false));
        NoNullRet("1",   Nully1.Coalesce( Nully0, Text,                         false));
        NoNullRet("1",   Nully1.Coalesce( Nully0, Text,            zeroMatters       ));
        NoNullRet("1",   Nully1.Coalesce( Nully0, Text,            zeroMatters: true ));
        NoNullRet("1",   Nully1.Coalesce( Nully0, Text,                         true ));
        NoNullRet("1",   Nully1.Coalesce( Nully0, NullyEmpty                         ));
        NoNullRet("1",   Nully1.Coalesce( Nully0, NullyEmpty,      zeroMatters: false));
        NoNullRet("1",   Nully1.Coalesce( Nully0, NullyEmpty,                   false));
        NoNullRet("1",   Nully1.Coalesce( Nully0, NullyEmpty,      zeroMatters       ));
        NoNullRet("1",   Nully1.Coalesce( Nully0, NullyEmpty,      zeroMatters: true ));
        NoNullRet("1",   Nully1.Coalesce( Nully0, NullyEmpty,                   true ));
        NoNullRet("1",   Nully1.Coalesce( Nully0, NullySpace                         ));
        NoNullRet("1",   Nully1.Coalesce( Nully0, NullySpace,      zeroMatters: false));
        NoNullRet("1",   Nully1.Coalesce( Nully0, NullySpace,                   false));
        NoNullRet("1",   Nully1.Coalesce( Nully0, NullySpace,      zeroMatters       ));
        NoNullRet("1",   Nully1.Coalesce( Nully0, NullySpace,      zeroMatters: true ));
        NoNullRet("1",   Nully1.Coalesce( Nully0, NullySpace,                   true ));
        NoNullRet("1",   Nully1.Coalesce( Nully0, NullyFilledText                    ));
        NoNullRet("1",   Nully1.Coalesce( Nully0, NullyFilledText, zeroMatters: false));
        NoNullRet("1",   Nully1.Coalesce( Nully0, NullyFilledText,              false));
        NoNullRet("1",   Nully1.Coalesce( Nully0, NullyFilledText, zeroMatters       ));
        NoNullRet("1",   Nully1.Coalesce( Nully0, NullyFilledText, zeroMatters: true ));
        NoNullRet("1",   Nully1.Coalesce( Nully0, NullyFilledText,              true ));
        NoNullRet("1",   Nully1.Coalesce(      0, NullText                           ));
        NoNullRet("1",   Nully1.Coalesce(      0, NullText,        zeroMatters: false));
        NoNullRet("1",   Nully1.Coalesce(      0, NullText,                     false));
        NoNullRet("1",   Nully1.Coalesce(      0, NullText,        zeroMatters       ));
        NoNullRet("1",   Nully1.Coalesce(      0, NullText,        zeroMatters: true ));
        NoNullRet("1",   Nully1.Coalesce(      0, NullText,                     true ));
        NoNullRet("1",   Nully1.Coalesce(      0, Empty                              ));
        NoNullRet("1",   Nully1.Coalesce(      0, Empty,           zeroMatters: false));
        NoNullRet("1",   Nully1.Coalesce(      0, Empty,                        false));
        NoNullRet("1",   Nully1.Coalesce(      0, Empty,           zeroMatters       ));
        NoNullRet("1",   Nully1.Coalesce(      0, Empty,           zeroMatters: true ));
        NoNullRet("1",   Nully1.Coalesce(      0, Empty,                        true ));
        NoNullRet("1",   Nully1.Coalesce(      0, Space                              ));
        NoNullRet("1",   Nully1.Coalesce(      0, Space,           zeroMatters: false));
        NoNullRet("1",   Nully1.Coalesce(      0, Space,                        false));
        NoNullRet("1",   Nully1.Coalesce(      0, Space,           zeroMatters       ));
        NoNullRet("1",   Nully1.Coalesce(      0, Space,           zeroMatters: true ));
        NoNullRet("1",   Nully1.Coalesce(      0, Space,                        true ));
        NoNullRet("1",   Nully1.Coalesce(      0, Text                               ));
        NoNullRet("1",   Nully1.Coalesce(      0, Text,            zeroMatters: false));
        NoNullRet("1",   Nully1.Coalesce(      0, Text,                         false));
        NoNullRet("1",   Nully1.Coalesce(      0, Text,            zeroMatters       ));
        NoNullRet("1",   Nully1.Coalesce(      0, Text,            zeroMatters: true ));
        NoNullRet("1",   Nully1.Coalesce(      0, Text,                         true ));
        NoNullRet("1",   Nully1.Coalesce(      0, NullyEmpty                         ));
        NoNullRet("1",   Nully1.Coalesce(      0, NullyEmpty,      zeroMatters: false));
        NoNullRet("1",   Nully1.Coalesce(      0, NullyEmpty,                   false));
        NoNullRet("1",   Nully1.Coalesce(      0, NullyEmpty,      zeroMatters       ));
        NoNullRet("1",   Nully1.Coalesce(      0, NullyEmpty,      zeroMatters: true ));
        NoNullRet("1",   Nully1.Coalesce(      0, NullyEmpty,                   true ));
        NoNullRet("1",   Nully1.Coalesce(      0, NullySpace                         ));
        NoNullRet("1",   Nully1.Coalesce(      0, NullySpace,      zeroMatters: false));
        NoNullRet("1",   Nully1.Coalesce(      0, NullySpace,                   false));
        NoNullRet("1",   Nully1.Coalesce(      0, NullySpace,      zeroMatters       ));
        NoNullRet("1",   Nully1.Coalesce(      0, NullySpace,      zeroMatters: true ));
        NoNullRet("1",   Nully1.Coalesce(      0, NullySpace,                   true ));
        NoNullRet("1",   Nully1.Coalesce(      0, NullyFilledText                    ));
        NoNullRet("1",   Nully1.Coalesce(      0, NullyFilledText, zeroMatters: false));
        NoNullRet("1",   Nully1.Coalesce(      0, NullyFilledText,              false));
        NoNullRet("1",   Nully1.Coalesce(      0, NullyFilledText, zeroMatters       ));
        NoNullRet("1",   Nully1.Coalesce(      0, NullyFilledText, zeroMatters: true ));
        NoNullRet("1",   Nully1.Coalesce(      0, NullyFilledText,              true ));
    }

    [TestMethod]
    public void Coalesce_3Args_ValuesToText_ExtensionsZeroMattersFlagsInBack_Batch4()
    {
        NoNullRet("",         0.Coalesce(NullNum, NullText                           ));
        NoNullRet("",         0.Coalesce(NullNum, NullText,        zeroMatters: false));
        NoNullRet("",         0.Coalesce(NullNum, NullText,                     false));
        NoNullRet("0",        0.Coalesce(NullNum, NullText,        zeroMatters       ));
        NoNullRet("0",        0.Coalesce(NullNum, NullText,        zeroMatters: true ));
        NoNullRet("0",        0.Coalesce(NullNum, NullText,                     true ));
        NoNullRet("",         0.Coalesce(NullNum, Empty                              ));
        NoNullRet("",         0.Coalesce(NullNum, Empty,           zeroMatters: false));
        NoNullRet("",         0.Coalesce(NullNum, Empty,                        false));
        NoNullRet("0",        0.Coalesce(NullNum, Empty,           zeroMatters       ));
        NoNullRet("0",        0.Coalesce(NullNum, Empty,           zeroMatters: true ));
        NoNullRet("0",        0.Coalesce(NullNum, Empty,                        true ));
        NoNullRet(" ",        0.Coalesce(NullNum, Space                              ));
        NoNullRet(" ",        0.Coalesce(NullNum, Space,           zeroMatters: false));
        NoNullRet(" ",        0.Coalesce(NullNum, Space,                        false));
        NoNullRet("0",        0.Coalesce(NullNum, Space,           zeroMatters       ));
        NoNullRet("0",        0.Coalesce(NullNum, Space,           zeroMatters: true ));
        NoNullRet("0",        0.Coalesce(NullNum, Space,                        true ));
        NoNullRet(Text,       0.Coalesce(NullNum, Text                               ));
        NoNullRet(Text,       0.Coalesce(NullNum, Text,            zeroMatters: false));
        NoNullRet(Text,       0.Coalesce(NullNum, Text,                         false));
        NoNullRet("0",        0.Coalesce(NullNum, Text,            zeroMatters       ));
        NoNullRet("0",        0.Coalesce(NullNum, Text,            zeroMatters: true ));
        NoNullRet("0",        0.Coalesce(NullNum, Text,                         true ));
        NoNullRet("",         0.Coalesce(NullNum, NullyEmpty                         ));
        NoNullRet("",         0.Coalesce(NullNum, NullyEmpty,      zeroMatters: false));
        NoNullRet("",         0.Coalesce(NullNum, NullyEmpty,                   false));
        NoNullRet("0",        0.Coalesce(NullNum, NullyEmpty,      zeroMatters       ));
        NoNullRet("0",        0.Coalesce(NullNum, NullyEmpty,      zeroMatters: true ));
        NoNullRet("0",        0.Coalesce(NullNum, NullyEmpty,                   true ));
        NoNullRet(" ",        0.Coalesce(NullNum, NullySpace                         ));
        NoNullRet(" ",        0.Coalesce(NullNum, NullySpace,      zeroMatters: false));
        NoNullRet(" ",        0.Coalesce(NullNum, NullySpace,                   false));
        NoNullRet("0",        0.Coalesce(NullNum, NullySpace,      zeroMatters       ));
        NoNullRet("0",        0.Coalesce(NullNum, NullySpace,      zeroMatters: true ));
        NoNullRet("0",        0.Coalesce(NullNum, NullySpace,                   true ));
        NoNullRet(Text,       0.Coalesce(NullNum, NullyFilledText                    ));
        NoNullRet(Text,       0.Coalesce(NullNum, NullyFilledText, zeroMatters: false));
        NoNullRet(Text,       0.Coalesce(NullNum, NullyFilledText,              false));
        NoNullRet("0",        0.Coalesce(NullNum, NullyFilledText, zeroMatters       ));
        NoNullRet("0",        0.Coalesce(NullNum, NullyFilledText, zeroMatters: true ));
        NoNullRet("0",        0.Coalesce(NullNum, NullyFilledText,              true ));
        NoNullRet("1",        0.Coalesce( Nully1, NullText                           ));
        NoNullRet("1",        0.Coalesce( Nully1, NullText,        zeroMatters: false));
        NoNullRet("1",        0.Coalesce( Nully1, NullText,                     false));
        NoNullRet("0",        0.Coalesce( Nully1, NullText,        zeroMatters       ));
        NoNullRet("0",        0.Coalesce( Nully1, NullText,        zeroMatters: true ));
        NoNullRet("0",        0.Coalesce( Nully1, NullText,                     true ));
        NoNullRet("1",        0.Coalesce( Nully1, Empty                              ));
        NoNullRet("1",        0.Coalesce( Nully1, Empty,           zeroMatters: false));
        NoNullRet("1",        0.Coalesce( Nully1, Empty,                        false));
        NoNullRet("0",        0.Coalesce( Nully1, Empty,           zeroMatters       ));
        NoNullRet("0",        0.Coalesce( Nully1, Empty,           zeroMatters: true ));
        NoNullRet("0",        0.Coalesce( Nully1, Empty,                        true ));
        NoNullRet("1",        0.Coalesce( Nully1, Space                              ));
        NoNullRet("1",        0.Coalesce( Nully1, Space,           zeroMatters: false));
        NoNullRet("1",        0.Coalesce( Nully1, Space,                        false));
        NoNullRet("0",        0.Coalesce( Nully1, Space,           zeroMatters       ));
        NoNullRet("0",        0.Coalesce( Nully1, Space,           zeroMatters: true ));
        NoNullRet("0",        0.Coalesce( Nully1, Space,                        true ));
        NoNullRet("1",        0.Coalesce( Nully1, Text                               ));
        NoNullRet("1",        0.Coalesce( Nully1, Text,            zeroMatters: false));
        NoNullRet("1",        0.Coalesce( Nully1, Text,                         false));
        NoNullRet("0",        0.Coalesce( Nully1, Text,            zeroMatters       ));
        NoNullRet("0",        0.Coalesce( Nully1, Text,            zeroMatters: true ));
        NoNullRet("0",        0.Coalesce( Nully1, Text,                         true ));
        NoNullRet("1",        0.Coalesce( Nully1, NullyEmpty                         ));
        NoNullRet("1",        0.Coalesce( Nully1, NullyEmpty,      zeroMatters: false));
        NoNullRet("1",        0.Coalesce( Nully1, NullyEmpty,                   false));
        NoNullRet("0",        0.Coalesce( Nully1, NullyEmpty,      zeroMatters       ));
        NoNullRet("0",        0.Coalesce( Nully1, NullyEmpty,      zeroMatters: true ));
        NoNullRet("0",        0.Coalesce( Nully1, NullyEmpty,                   true ));
        NoNullRet("1",        0.Coalesce( Nully1, NullySpace                         ));
        NoNullRet("1",        0.Coalesce( Nully1, NullySpace,      zeroMatters: false));
        NoNullRet("1",        0.Coalesce( Nully1, NullySpace,                   false));
        NoNullRet("0",        0.Coalesce( Nully1, NullySpace,      zeroMatters       ));
        NoNullRet("0",        0.Coalesce( Nully1, NullySpace,      zeroMatters: true ));
        NoNullRet("0",        0.Coalesce( Nully1, NullySpace,                   true ));
        NoNullRet("1",        0.Coalesce( Nully1, NullyFilledText                    ));
        NoNullRet("1",        0.Coalesce( Nully1, NullyFilledText, zeroMatters: false));
        NoNullRet("1",        0.Coalesce( Nully1, NullyFilledText,              false));
        NoNullRet("0",        0.Coalesce( Nully1, NullyFilledText, zeroMatters       ));
        NoNullRet("0",        0.Coalesce( Nully1, NullyFilledText, zeroMatters: true ));
        NoNullRet("0",        0.Coalesce( Nully1, NullyFilledText,              true ));
        NoNullRet("1",        0.Coalesce(      1, NullText                           ));
        NoNullRet("1",        0.Coalesce(      1, NullText,        zeroMatters: false));
        NoNullRet("1",        0.Coalesce(      1, NullText,                     false));
        NoNullRet("0",        0.Coalesce(      1, NullText,        zeroMatters       ));
        NoNullRet("0",        0.Coalesce(      1, NullText,        zeroMatters: true ));
        NoNullRet("0",        0.Coalesce(      1, NullText,                     true ));
        NoNullRet("1",        0.Coalesce(      1, Empty                              ));
        NoNullRet("1",        0.Coalesce(      1, Empty,           zeroMatters: false));
        NoNullRet("1",        0.Coalesce(      1, Empty,                        false));
        NoNullRet("0",        0.Coalesce(      1, Empty,           zeroMatters       ));
        NoNullRet("0",        0.Coalesce(      1, Empty,           zeroMatters: true ));
        NoNullRet("0",        0.Coalesce(      1, Empty,                        true ));
        NoNullRet("1",        0.Coalesce(      1, Space                              ));
        NoNullRet("1",        0.Coalesce(      1, Space,           zeroMatters: false));
        NoNullRet("1",        0.Coalesce(      1, Space,                        false));
        NoNullRet("0",        0.Coalesce(      1, Space,           zeroMatters       ));
        NoNullRet("0",        0.Coalesce(      1, Space,           zeroMatters: true ));
        NoNullRet("0",        0.Coalesce(      1, Space,                        true ));
        NoNullRet("1",        0.Coalesce(      1, Text                               ));
        NoNullRet("1",        0.Coalesce(      1, Text,            zeroMatters: false));
        NoNullRet("1",        0.Coalesce(      1, Text,                         false));
        NoNullRet("0",        0.Coalesce(      1, Text,            zeroMatters       ));
        NoNullRet("0",        0.Coalesce(      1, Text,            zeroMatters: true ));
        NoNullRet("0",        0.Coalesce(      1, Text,                         true ));
        NoNullRet("1",        0.Coalesce(      1, NullyEmpty                         ));
        NoNullRet("1",        0.Coalesce(      1, NullyEmpty,      zeroMatters: false));
        NoNullRet("1",        0.Coalesce(      1, NullyEmpty,                   false));
        NoNullRet("0",        0.Coalesce(      1, NullyEmpty,      zeroMatters       ));
        NoNullRet("0",        0.Coalesce(      1, NullyEmpty,      zeroMatters: true ));
        NoNullRet("0",        0.Coalesce(      1, NullyEmpty,                   true ));
        NoNullRet("1",        0.Coalesce(      1, NullySpace                         ));
        NoNullRet("1",        0.Coalesce(      1, NullySpace,      zeroMatters: false));
        NoNullRet("1",        0.Coalesce(      1, NullySpace,                   false));
        NoNullRet("0",        0.Coalesce(      1, NullySpace,      zeroMatters       ));
        NoNullRet("0",        0.Coalesce(      1, NullySpace,      zeroMatters: true ));
        NoNullRet("0",        0.Coalesce(      1, NullySpace,                   true ));
        NoNullRet("1",        0.Coalesce(      1, NullyFilledText                    ));
        NoNullRet("1",        0.Coalesce(      1, NullyFilledText, zeroMatters: false));
        NoNullRet("1",        0.Coalesce(      1, NullyFilledText,              false));
        NoNullRet("0",        0.Coalesce(      1, NullyFilledText, zeroMatters       ));
        NoNullRet("0",        0.Coalesce(      1, NullyFilledText, zeroMatters: true ));
        NoNullRet("0",        0.Coalesce(      1, NullyFilledText,              true ));
    }

    [TestMethod]
    public void Coalesce_3Args_ValuesToText_ExtensionsZeroMattersFlagsInBack_Batch5()
    {
        NoNullRet("1",        1.Coalesce(NullNum, NullText                           ));
        NoNullRet("1",        1.Coalesce(NullNum, NullText,        zeroMatters: false));
        NoNullRet("1",        1.Coalesce(NullNum, NullText,                     false));
        NoNullRet("1",        1.Coalesce(NullNum, NullText,        zeroMatters       ));
        NoNullRet("1",        1.Coalesce(NullNum, NullText,        zeroMatters: true ));
        NoNullRet("1",        1.Coalesce(NullNum, NullText,                     true ));
        NoNullRet("1",        1.Coalesce(NullNum, Empty                              ));
        NoNullRet("1",        1.Coalesce(NullNum, Empty,           zeroMatters: false));
        NoNullRet("1",        1.Coalesce(NullNum, Empty,                        false));
        NoNullRet("1",        1.Coalesce(NullNum, Empty,           zeroMatters       ));
        NoNullRet("1",        1.Coalesce(NullNum, Empty,           zeroMatters: true ));
        NoNullRet("1",        1.Coalesce(NullNum, Empty,                        true ));
        NoNullRet("1",        1.Coalesce(NullNum, Space                              ));
        NoNullRet("1",        1.Coalesce(NullNum, Space,           zeroMatters: false));
        NoNullRet("1",        1.Coalesce(NullNum, Space,                        false));
        NoNullRet("1",        1.Coalesce(NullNum, Space,           zeroMatters       ));
        NoNullRet("1",        1.Coalesce(NullNum, Space,           zeroMatters: true ));
        NoNullRet("1",        1.Coalesce(NullNum, Space,                        true ));
        NoNullRet("1",        1.Coalesce(NullNum, Text                               ));
        NoNullRet("1",        1.Coalesce(NullNum, Text,            zeroMatters: false));
        NoNullRet("1",        1.Coalesce(NullNum, Text,                         false));
        NoNullRet("1",        1.Coalesce(NullNum, Text,            zeroMatters       ));
        NoNullRet("1",        1.Coalesce(NullNum, Text,            zeroMatters: true ));
        NoNullRet("1",        1.Coalesce(NullNum, Text,                         true ));
        NoNullRet("1",        1.Coalesce(NullNum, NullyEmpty                         ));
        NoNullRet("1",        1.Coalesce(NullNum, NullyEmpty,      zeroMatters: false));
        NoNullRet("1",        1.Coalesce(NullNum, NullyEmpty,                   false));
        NoNullRet("1",        1.Coalesce(NullNum, NullyEmpty,      zeroMatters       ));
        NoNullRet("1",        1.Coalesce(NullNum, NullyEmpty,      zeroMatters: true ));
        NoNullRet("1",        1.Coalesce(NullNum, NullyEmpty,                   true ));
        NoNullRet("1",        1.Coalesce(NullNum, NullySpace                         ));
        NoNullRet("1",        1.Coalesce(NullNum, NullySpace,      zeroMatters: false));
        NoNullRet("1",        1.Coalesce(NullNum, NullySpace,                   false));
        NoNullRet("1",        1.Coalesce(NullNum, NullySpace,      zeroMatters       ));
        NoNullRet("1",        1.Coalesce(NullNum, NullySpace,      zeroMatters: true ));
        NoNullRet("1",        1.Coalesce(NullNum, NullySpace,                   true ));
        NoNullRet("1",        1.Coalesce(NullNum, NullyFilledText                    ));
        NoNullRet("1",        1.Coalesce(NullNum, NullyFilledText, zeroMatters: false));
        NoNullRet("1",        1.Coalesce(NullNum, NullyFilledText,              false));
        NoNullRet("1",        1.Coalesce(NullNum, NullyFilledText, zeroMatters       ));
        NoNullRet("1",        1.Coalesce(NullNum, NullyFilledText, zeroMatters: true ));
        NoNullRet("1",        1.Coalesce(NullNum, NullyFilledText,              true ));
        NoNullRet("1",        1.Coalesce( Nully0, NullText                           ));
        NoNullRet("1",        1.Coalesce( Nully0, NullText,        zeroMatters: false));
        NoNullRet("1",        1.Coalesce( Nully0, NullText,                     false));
        NoNullRet("1",        1.Coalesce( Nully0, NullText,        zeroMatters       ));
        NoNullRet("1",        1.Coalesce( Nully0, NullText,        zeroMatters: true ));
        NoNullRet("1",        1.Coalesce( Nully0, NullText,                     true ));
        NoNullRet("1",        1.Coalesce( Nully0, Empty                              ));
        NoNullRet("1",        1.Coalesce( Nully0, Empty,           zeroMatters: false));
        NoNullRet("1",        1.Coalesce( Nully0, Empty,                        false));
        NoNullRet("1",        1.Coalesce( Nully0, Empty,           zeroMatters       ));
        NoNullRet("1",        1.Coalesce( Nully0, Empty,           zeroMatters: true ));
        NoNullRet("1",        1.Coalesce( Nully0, Empty,                        true ));
        NoNullRet("1",        1.Coalesce( Nully0, Space                              ));
        NoNullRet("1",        1.Coalesce( Nully0, Space,           zeroMatters: false));
        NoNullRet("1",        1.Coalesce( Nully0, Space,                        false));
        NoNullRet("1",        1.Coalesce( Nully0, Space,           zeroMatters       ));
        NoNullRet("1",        1.Coalesce( Nully0, Space,           zeroMatters: true ));
        NoNullRet("1",        1.Coalesce( Nully0, Space,                        true ));
        NoNullRet("1",        1.Coalesce( Nully0, Text                               ));
        NoNullRet("1",        1.Coalesce( Nully0, Text,            zeroMatters: false));
        NoNullRet("1",        1.Coalesce( Nully0, Text,                         false));
        NoNullRet("1",        1.Coalesce( Nully0, Text,            zeroMatters       ));
        NoNullRet("1",        1.Coalesce( Nully0, Text,            zeroMatters: true ));
        NoNullRet("1",        1.Coalesce( Nully0, Text,                         true ));
        NoNullRet("1",        1.Coalesce( Nully0, NullyEmpty                         ));
        NoNullRet("1",        1.Coalesce( Nully0, NullyEmpty,      zeroMatters: false));
        NoNullRet("1",        1.Coalesce( Nully0, NullyEmpty,                   false));
        NoNullRet("1",        1.Coalesce( Nully0, NullyEmpty,      zeroMatters       ));
        NoNullRet("1",        1.Coalesce( Nully0, NullyEmpty,      zeroMatters: true ));
        NoNullRet("1",        1.Coalesce( Nully0, NullyEmpty,                   true ));
        NoNullRet("1",        1.Coalesce( Nully0, NullySpace                         ));
        NoNullRet("1",        1.Coalesce( Nully0, NullySpace,      zeroMatters: false));
        NoNullRet("1",        1.Coalesce( Nully0, NullySpace,                   false));
        NoNullRet("1",        1.Coalesce( Nully0, NullySpace,      zeroMatters       ));
        NoNullRet("1",        1.Coalesce( Nully0, NullySpace,      zeroMatters: true ));
        NoNullRet("1",        1.Coalesce( Nully0, NullySpace,                   true ));
        NoNullRet("1",        1.Coalesce( Nully0, NullyFilledText                    ));
        NoNullRet("1",        1.Coalesce( Nully0, NullyFilledText, zeroMatters: false));
        NoNullRet("1",        1.Coalesce( Nully0, NullyFilledText,              false));
        NoNullRet("1",        1.Coalesce( Nully0, NullyFilledText, zeroMatters       ));
        NoNullRet("1",        1.Coalesce( Nully0, NullyFilledText, zeroMatters: true ));
        NoNullRet("1",        1.Coalesce( Nully0, NullyFilledText,              true ));
    }
}