using System.Collections.ObjectModel;

namespace JJ.Framework.Existence.Core.Tests;

[TestClass]
public class Has_Collection_Tests
{
    [TestMethod]
    public void Collection_FilledIn_True()
    {
        {
            IsTrue(Has(FilledArray));
            IsTrue(Has(FilledList));
            IsTrue(Has(FilledHashSet));
            IsTrue(Has(FilledIList));
            IsTrue(Has(FilledISet));
            IsTrue(Has(FilledICollection));
            IsTrue(Has(FilledIReadOnlyList));
            IsTrue(Has(FilledIReadOnlyCollection));
            IsTrue(Has(FilledIEnumerable));
            IsTrue(FilledArray.FilledIn());
            IsTrue(FilledList.FilledIn());
            IsTrue(FilledHashSet.FilledIn());
            IsTrue(FilledIList.FilledIn());
            IsTrue(FilledISet.FilledIn());
            IsTrue(FilledICollection.FilledIn());
            IsTrue(FilledIReadOnlyList.FilledIn());
            IsTrue(FilledIReadOnlyCollection.FilledIn());
            IsTrue(FilledIEnumerable.FilledIn());
            IsTrue(FilledIn(FilledArray));
            IsTrue(FilledIn(FilledIList));
            IsTrue(FilledIn(FilledISet));
            IsTrue(FilledIn(FilledIDict));
            IsTrue(FilledIn(FilledICollection));
            IsTrue(FilledIn(FilledIEnumerable));
            IsTrue(FilledIn(FilledList));
            IsTrue(FilledIn(FilledHashSet));
            IsTrue(FilledIn(FilledStack));
            IsTrue(FilledIn(FilledQueue));
            IsTrue(FilledIn(FilledLinkedList));
            IsTrue(FilledIn(FilledSortedList));
            IsTrue(FilledIn(FilledSortedSet));
            IsTrue(FilledIn(FilledDict));
            IsTrue(FilledIn(FilledDictKeyColl));
            IsTrue(FilledIn(FilledDictValColl));
            IsTrue(FilledIn(FilledIImmutableList));
            IsTrue(FilledIn(FilledIImmutableSet));
            IsTrue(FilledIn(FilledIImmutableStack));
            IsTrue(FilledIn(FilledIImmutableQueue));
            IsTrue(FilledIn(FilledIImmutableDict));
            IsTrue(FilledIn(FilledImmutableArray));
            IsTrue(FilledIn(FilledImmutableArrayBuilder));
            IsTrue(FilledIn(FilledImmutableList));
            IsTrue(FilledIn(FilledImmutableListBuilder));
            IsTrue(FilledIn(FilledImmutableHashSet));
            IsTrue(FilledIn(FilledImmutableHashSetBuilder));
            IsTrue(FilledIn(FilledImmutableStack));
            IsTrue(FilledIn(FilledImmutableQueue));
            IsTrue(FilledIn(FilledImmutableDict));
            IsTrue(FilledIn(FilledImmutableDictBuilder));
            IsTrue(FilledIn(FilledImmutableSortedSet));
            IsTrue(FilledIn(FilledImmutableSortedSetBuilder));
            IsTrue(FilledIn(FilledImmutableSortedDict));
            IsTrue(FilledIn(FilledImmutableSortedDictBuilder));
            IsTrue(FilledIn(FilledIReadOnlyList));
            IsTrue(FilledIn(FilledIReadOnlyCollection));
            IsTrue(FilledIn(FilledIReadOnlyCollection));
            IsTrue(FilledIn(FilledIReadOnlyList));
            IsTrue(FilledIn(FilledIReadOnlyDict));
            IsTrue(FilledIn(FilledReadOnlyCollection));
            IsTrue(FilledIn(FilledReadOnlyDict));
            IsTrue(FilledIn(FilledReadOnlyDictKeys));
            IsTrue(FilledIn(FilledReadOnlyDictVals));
            #if NET9_0_OR_GREATER
            IsTrue(FilledIn(FilledIReadOnlySet));
            IsTrue(FilledIn(FilledReadOnlySet));
            #endif
        }
        {
            IsTrue(Has(NullyFilledArray));
            IsTrue(Has(NullyFilledList));
            IsTrue(Has(NullyFilledHashSet));
            IsTrue(Has(NullyFilledIList));
            IsTrue(Has(NullyFilledISet));
            IsTrue(Has(NullyFilledICollection));
            IsTrue(Has(NullyFilledIReadOnlyList));
            IsTrue(Has(NullyFilledIReadOnlyCollection));
            IsTrue(Has(NullyFilledIEnumerable));
            IsTrue(NullyFilledArray.FilledIn());
            IsTrue(NullyFilledList.FilledIn());
            IsTrue(NullyFilledHashSet.FilledIn());
            IsTrue(NullyFilledIList.FilledIn());
            IsTrue(NullyFilledISet.FilledIn());
            IsTrue(NullyFilledICollection.FilledIn());
            IsTrue(NullyFilledIReadOnlyList.FilledIn());
            IsTrue(NullyFilledIReadOnlyCollection.FilledIn());
            IsTrue(NullyFilledIEnumerable.FilledIn());
            IsTrue(FilledIn(NullyFilledArray));
            IsTrue(FilledIn(NullyFilledIList));
            IsTrue(FilledIn(NullyFilledISet));
            IsTrue(FilledIn(NullyFilledIDict));
            IsTrue(FilledIn(NullyFilledICollection));
            IsTrue(FilledIn(NullyFilledIEnumerable));
            IsTrue(FilledIn(NullyFilledList));
            IsTrue(FilledIn(NullyFilledHashSet));
            IsTrue(FilledIn(NullyFilledStack));
            IsTrue(FilledIn(NullyFilledQueue));
            IsTrue(FilledIn(NullyFilledLinkedList));
            IsTrue(FilledIn(NullyFilledSortedList));
            IsTrue(FilledIn(NullyFilledSortedSet));
            IsTrue(FilledIn(NullyFilledDict));
            IsTrue(FilledIn(NullyFilledDictKeyColl));
            IsTrue(FilledIn(NullyFilledDictValColl));
            IsTrue(FilledIn(NullyFilledIImmutableList));
            IsTrue(FilledIn(NullyFilledIImmutableSet));
            IsTrue(FilledIn(NullyFilledIImmutableStack));
            IsTrue(FilledIn(NullyFilledIImmutableQueue));
            IsTrue(FilledIn(NullyFilledIImmutableDict));
            IsTrue(FilledIn(NullyFilledImmutableArray));
            IsTrue(FilledIn(NullyFilledImmutableArrayBuilder));
            IsTrue(FilledIn(NullyFilledImmutableList));
            IsTrue(FilledIn(NullyFilledImmutableListBuilder));
            IsTrue(FilledIn(NullyFilledImmutableHashSet));
            IsTrue(FilledIn(NullyFilledImmutableHashSetBuilder));
            IsTrue(FilledIn(NullyFilledImmutableStack));
            IsTrue(FilledIn(NullyFilledImmutableQueue));
            IsTrue(FilledIn(NullyFilledImmutableDict));
            IsTrue(FilledIn(NullyFilledImmutableDictBuilder));
            IsTrue(FilledIn(NullyFilledImmutableSortedSet));
            IsTrue(FilledIn(NullyFilledImmutableSortedSetBuilder));
            IsTrue(FilledIn(NullyFilledImmutableSortedDict));
            IsTrue(FilledIn(NullyFilledImmutableSortedDictBuilder));
            IsTrue(FilledIn(NullyFilledIReadOnlyList));
            IsTrue(FilledIn(NullyFilledIReadOnlyCollection));
            IsTrue(FilledIn(NullyFilledIReadOnlyCollection));
            IsTrue(FilledIn(NullyFilledIReadOnlyList));
            IsTrue(FilledIn(NullyFilledIReadOnlyDict));
            IsTrue(FilledIn(NullyFilledReadOnlyCollection));
            IsTrue(FilledIn(NullyFilledReadOnlyDict));
            IsTrue(FilledIn(NullyFilledReadOnlyDictKeys));
            IsTrue(FilledIn(NullyFilledReadOnlyDictVals));
            #if NET9_0_OR_GREATER
            IsTrue(FilledIn(NullyFilledIReadOnlySet));
            IsTrue(FilledIn(NullyFilledReadOnlySet));
            #endif
        }
    }
      
    [TestMethod]
    public void Collection_FilledIn_False()
    {
        {
            IsFalse(Has(EmptyArray));
            IsFalse(Has(EmptyList));
            IsFalse(Has(EmptyHashSet));
            IsFalse(Has(EmptyIList));
            IsFalse(Has(EmptyISet));
            IsFalse(Has(EmptyICollection));
            IsFalse(Has(EmptyIReadOnlyList));
            IsFalse(Has(EmptyIReadOnlyCollection));
            IsFalse(Has(EmptyIEnumerable));
            IsFalse(EmptyArray.FilledIn());
            IsFalse(EmptyList.FilledIn());
            IsFalse(EmptyHashSet.FilledIn());
            IsFalse(EmptyIList.FilledIn());
            IsFalse(EmptyISet.FilledIn());
            IsFalse(EmptyICollection.FilledIn());
            IsFalse(EmptyIReadOnlyList.FilledIn());
            IsFalse(EmptyIReadOnlyCollection.FilledIn());
            IsFalse(EmptyIEnumerable.FilledIn());
            IsFalse(FilledIn(EmptyArray));
            IsFalse(FilledIn(EmptyIList));
            IsFalse(FilledIn(EmptyISet));
            IsFalse(FilledIn(EmptyIDict));
            IsFalse(FilledIn(EmptyICollection));
            IsFalse(FilledIn(EmptyIEnumerable));
            IsFalse(FilledIn(EmptyList));
            IsFalse(FilledIn(EmptyHashSet));
            IsFalse(FilledIn(EmptyStack));
            IsFalse(FilledIn(EmptyQueue));
            IsFalse(FilledIn(EmptyLinkedList));
            IsFalse(FilledIn(EmptySortedList));
            IsFalse(FilledIn(EmptySortedSet));
            IsFalse(FilledIn(EmptyDict));
            IsFalse(FilledIn(EmptyDictKeyColl));
            IsFalse(FilledIn(EmptyDictValColl));
            IsFalse(FilledIn(EmptyIImmutableList));
            IsFalse(FilledIn(EmptyIImmutableSet));
            IsFalse(FilledIn(EmptyIImmutableStack));
            IsFalse(FilledIn(EmptyIImmutableQueue));
            IsFalse(FilledIn(EmptyIImmutableDict));
            IsFalse(FilledIn(EmptyImmutableArray));
            IsFalse(FilledIn(EmptyImmutableArrayBuilder));
            IsFalse(FilledIn(EmptyImmutableList));
            IsFalse(FilledIn(EmptyImmutableListBuilder));
            IsFalse(FilledIn(EmptyImmutableHashSet));
            IsFalse(FilledIn(EmptyImmutableHashSetBuilder));
            IsFalse(FilledIn(EmptyImmutableStack));
            IsFalse(FilledIn(EmptyImmutableQueue));
            IsFalse(FilledIn(EmptyImmutableDict));
            IsFalse(FilledIn(EmptyImmutableDictBuilder));
            IsFalse(FilledIn(EmptyImmutableSortedSet));
            IsFalse(FilledIn(EmptyImmutableSortedSetBuilder));
            IsFalse(FilledIn(EmptyImmutableSortedDict));
            IsFalse(FilledIn(EmptyImmutableSortedDictBuilder));
            IsFalse(FilledIn(EmptyIReadOnlyList));
            IsFalse(FilledIn(EmptyIReadOnlyCollection));
            IsFalse(FilledIn(EmptyIReadOnlyList));
            IsFalse(FilledIn(EmptyIReadOnlyCollection));
            IsFalse(FilledIn(EmptyIReadOnlyCollection));
            IsFalse(FilledIn(EmptyIReadOnlyList));
            IsFalse(FilledIn(EmptyIReadOnlyDict));
            IsFalse(FilledIn(EmptyReadOnlyCollection));
            IsFalse(FilledIn(EmptyReadOnlyDict));
            IsFalse(FilledIn(EmptyReadOnlyDictKeys));
            IsFalse(FilledIn(EmptyReadOnlyDictVals));
            #if NET9_0_OR_GREATER
            IsFalse(FilledIn(EmptyIReadOnlySet));
            IsFalse(FilledIn(EmptyReadOnlySet));
            #endif
        }
        {
            IsFalse(Has(NullableEmptyArray));
            IsFalse(Has(NullableEmptyList));
            IsFalse(Has(NullableEmptyHashSet));
            IsFalse(Has(NullableEmptyIList));
            IsFalse(Has(NullableEmptyISet));
            IsFalse(Has(NullableEmptyICollection));
            IsFalse(Has(NullableEmptyIReadOnlyList));
            IsFalse(Has(NullableEmptyIReadOnlyCollection));
            IsFalse(Has(NullableEmptyIEnumerable));
            IsFalse(NullableEmptyArray.FilledIn());
            IsFalse(NullableEmptyList.FilledIn());
            IsFalse(NullableEmptyHashSet.FilledIn());
            IsFalse(NullableEmptyIList.FilledIn());
            IsFalse(NullableEmptyISet.FilledIn());
            IsFalse(NullableEmptyICollection.FilledIn());
            IsFalse(NullableEmptyIReadOnlyList.FilledIn());
            IsFalse(NullableEmptyIReadOnlyCollection.FilledIn());
            IsFalse(NullableEmptyIEnumerable.FilledIn());
            IsFalse(FilledIn(NullableEmptyArray));
            IsFalse(FilledIn(NullableEmptyIList));
            IsFalse(FilledIn(NullableEmptyISet));
            IsFalse(FilledIn(NullableEmptyIDict));
            IsFalse(FilledIn(NullableEmptyICollection));
            IsFalse(FilledIn(NullableEmptyIEnumerable));
            IsFalse(FilledIn(NullableEmptyList));
            IsFalse(FilledIn(NullableEmptyHashSet));
            IsFalse(FilledIn(NullableEmptyStack));
            IsFalse(FilledIn(NullableEmptyQueue));
            IsFalse(FilledIn(NullableEmptyLinkedList));
            IsFalse(FilledIn(NullableEmptySortedList));
            IsFalse(FilledIn(NullableEmptySortedSet));
            IsFalse(FilledIn(NullableEmptyDict));
            IsFalse(FilledIn(NullableEmptyDictKeyColl));
            IsFalse(FilledIn(NullableEmptyDictValColl));
            IsFalse(FilledIn(NullableEmptyIImmutableList));
            IsFalse(FilledIn(NullableEmptyIImmutableSet));
            IsFalse(FilledIn(NullableEmptyIImmutableStack));
            IsFalse(FilledIn(NullableEmptyIImmutableQueue));
            IsFalse(FilledIn(NullableEmptyIImmutableDict));
            IsFalse(FilledIn(NullableEmptyImmutableArray));
            IsFalse(FilledIn(NullableEmptyImmutableArrayBuilder));
            IsFalse(FilledIn(NullableEmptyImmutableList));
            IsFalse(FilledIn(NullableEmptyImmutableListBuilder));
            IsFalse(FilledIn(NullableEmptyImmutableHashSet));
            IsFalse(FilledIn(NullableEmptyImmutableHashSetBuilder));
            IsFalse(FilledIn(NullableEmptyImmutableStack));
            IsFalse(FilledIn(NullableEmptyImmutableQueue));
            IsFalse(FilledIn(NullableEmptyImmutableDict));
            IsFalse(FilledIn(NullableEmptyImmutableDictBuilder));
            IsFalse(FilledIn(NullableEmptyImmutableSortedSet));
            IsFalse(FilledIn(NullableEmptyImmutableSortedSetBuilder));
            IsFalse(FilledIn(NullableEmptyImmutableSortedDict));
            IsFalse(FilledIn(NullableEmptyImmutableSortedDictBuilder));
            IsFalse(FilledIn(NullableEmptyIReadOnlyList));
            IsFalse(FilledIn(NullableEmptyIReadOnlyCollection));
            IsFalse(FilledIn(NullableEmptyIReadOnlyCollection));
            IsFalse(FilledIn(NullableEmptyIReadOnlyList));
            IsFalse(FilledIn(NullableEmptyIReadOnlyDict));
            IsFalse(FilledIn(NullableEmptyReadOnlyCollection));
            IsFalse(FilledIn(NullableEmptyReadOnlyDict));
            IsFalse(FilledIn(NullableEmptyReadOnlyDictKeys));
            IsFalse(FilledIn(NullableEmptyReadOnlyDictVals));
            #if NET9_0_OR_GREATER
            IsFalse(FilledIn(NullableEmptyIReadOnlySet));
            IsFalse(FilledIn(NullableEmptyReadOnlySet));
            #endif
        }
        {
            IsFalse(Has(NullArray));
            IsFalse(Has(NullList));
            IsFalse(Has(NullHashSet));
            IsFalse(Has(NullIList));
            IsFalse(Has(NullISet));
            IsFalse(Has(NullICollection));
            IsFalse(Has(NullIReadOnlyList));
            IsFalse(Has(NullIReadOnlyCollection));
            IsFalse(Has(NullIEnumerable));
            IsFalse(NullArray.FilledIn());
            IsFalse(NullList.FilledIn());
            IsFalse(NullHashSet.FilledIn());
            IsFalse(NullIList.FilledIn());
            IsFalse(NullISet.FilledIn());
            IsFalse(NullICollection.FilledIn());
            IsFalse(NullIReadOnlyList.FilledIn());
            IsFalse(NullIReadOnlyCollection.FilledIn());
            IsFalse(NullIEnumerable.FilledIn());
            IsFalse(FilledIn(NullArray));
            IsFalse(FilledIn(NullIList));
            IsFalse(FilledIn(NullISet));
            IsFalse(FilledIn(NullIDict));
            IsFalse(FilledIn(NullICollection));
            IsFalse(FilledIn(NullIEnumerable));
            IsFalse(FilledIn(NullList));
            IsFalse(FilledIn(NullHashSet));
            IsFalse(FilledIn(NullStack));
            IsFalse(FilledIn(NullQueue));
            IsFalse(FilledIn(NullLinkedList));
            IsFalse(FilledIn(NullSortedList));
            IsFalse(FilledIn(NullSortedSet));
            IsFalse(FilledIn(NullDict));
            IsFalse(FilledIn(NullDictKeyColl));
            IsFalse(FilledIn(NullDictValColl));
            IsFalse(FilledIn(NullIImmutableList));
            IsFalse(FilledIn(NullIImmutableSet));
            IsFalse(FilledIn(NullIImmutableStack));
            IsFalse(FilledIn(NullIImmutableQueue));
            IsFalse(FilledIn(NullIImmutableDict));
            IsFalse(FilledIn(NullImmutableArray));
            IsFalse(FilledIn(NullImmutableArrayBuilder));
            IsFalse(FilledIn(NullImmutableList));
            IsFalse(FilledIn(NullImmutableListBuilder));
            IsFalse(FilledIn(NullImmutableHashSet));
            IsFalse(FilledIn(NullImmutableHashSetBuilder));
            IsFalse(FilledIn(NullImmutableStack));
            IsFalse(FilledIn(NullImmutableQueue));
            IsFalse(FilledIn(NullImmutableDict));
            IsFalse(FilledIn(NullImmutableDictBuilder));
            IsFalse(FilledIn(NullImmutableSortedSet));
            IsFalse(FilledIn(NullImmutableSortedSetBuilder));
            IsFalse(FilledIn(NullImmutableSortedDict));
            IsFalse(FilledIn(NullImmutableSortedDictBuilder));
            IsFalse(FilledIn(NullIReadOnlyList));
            IsFalse(FilledIn(NullIReadOnlyCollection));
            IsFalse(FilledIn(NullIReadOnlyList));
            IsFalse(FilledIn(NullIReadOnlyCollection));
            IsFalse(FilledIn(NullIReadOnlyCollection));
            IsFalse(FilledIn(NullIReadOnlyList));
            IsFalse(FilledIn(NullIReadOnlyDict));
            IsFalse(FilledIn(NullReadOnlyCollection));
            IsFalse(FilledIn(NullReadOnlyDict));
            IsFalse(FilledIn(NullReadOnlyDictKeys));
            IsFalse(FilledIn(NullReadOnlyDictVals));
            #if NET9_0_OR_GREATER
            IsFalse(FilledIn(NullIReadOnlySet));
            IsFalse(FilledIn(NullReadOnlySet));
            #endif
        }
    }
    
    [TestMethod]
    public void Collection_IsNully_False()
    {
        {
            IsFalse(FilledArray.IsNully());
            IsFalse(FilledList.IsNully());
            IsFalse(FilledHashSet.IsNully());
            IsFalse(FilledIList.IsNully());
            IsFalse(FilledISet.IsNully());
            IsFalse(FilledICollection.IsNully());
            IsFalse(FilledIReadOnlyList.IsNully());
            IsFalse(FilledIReadOnlyCollection.IsNully());
            IsFalse(FilledIEnumerable.IsNully());
            IsFalse(IsNully(FilledArray));
            IsFalse(IsNully(FilledList));
            IsFalse(IsNully(FilledHashSet));
            IsFalse(IsNully(FilledIList));
            IsFalse(IsNully(FilledISet));
            IsFalse(IsNully(FilledICollection));
            IsFalse(IsNully(FilledIReadOnlyList));
            IsFalse(IsNully(FilledIReadOnlyCollection));
            IsFalse(IsNully(FilledIEnumerable));
        }
        {
            IsFalse(NullyFilledArray.IsNully());
            IsFalse(NullyFilledList.IsNully());
            IsFalse(NullyFilledHashSet.IsNully());
            IsFalse(NullyFilledIList.IsNully());
            IsFalse(NullyFilledISet.IsNully());
            IsFalse(NullyFilledICollection.IsNully());
            IsFalse(NullyFilledIReadOnlyList.IsNully());
            IsFalse(NullyFilledIReadOnlyCollection.IsNully());
            IsFalse(NullyFilledIEnumerable.IsNully());
            IsFalse(IsNully(NullyFilledArray));
            IsFalse(IsNully(NullyFilledList));
            IsFalse(IsNully(NullyFilledHashSet));
            IsFalse(IsNully(NullyFilledIList));
            IsFalse(IsNully(NullyFilledISet));
            IsFalse(IsNully(NullyFilledICollection));
            IsFalse(IsNully(NullyFilledIReadOnlyList));
            IsFalse(IsNully(NullyFilledIReadOnlyCollection));
            IsFalse(IsNully(NullyFilledIEnumerable));
        }
    }
    
    [TestMethod]
    public void Collection_IsNully_True()
    {
        {
            IsTrue(EmptyArray.IsNully());
            IsTrue(EmptyList.IsNully());
            IsTrue(EmptyHashSet.IsNully());
            IsTrue(EmptyIList.IsNully());
            IsTrue(EmptyISet.IsNully());
            IsTrue(EmptyICollection.IsNully());
            IsTrue(EmptyIReadOnlyList.IsNully());
            IsTrue(EmptyIReadOnlyCollection.IsNully());
            IsTrue(EmptyIEnumerable.IsNully());
            IsTrue(IsNully(EmptyArray));
            IsTrue(IsNully(EmptyList));
            IsTrue(IsNully(EmptyHashSet));
            IsTrue(IsNully(EmptyIList));
            IsTrue(IsNully(EmptyISet));
            IsTrue(IsNully(EmptyICollection));
            IsTrue(IsNully(EmptyIReadOnlyList));
            IsTrue(IsNully(EmptyIReadOnlyCollection));
            IsTrue(IsNully(EmptyIEnumerable));
        }
        {
            IsTrue(NullableEmptyArray.IsNully());
            IsTrue(NullableEmptyList.IsNully());
            IsTrue(NullableEmptyHashSet.IsNully());
            IsTrue(NullableEmptyIList.IsNully());
            IsTrue(NullableEmptyISet.IsNully());
            IsTrue(NullableEmptyICollection.IsNully());
            IsTrue(NullableEmptyIReadOnlyList.IsNully());
            IsTrue(NullableEmptyIReadOnlyCollection.IsNully());
            IsTrue(NullableEmptyIEnumerable.IsNully());
            IsTrue(IsNully(NullableEmptyArray));
            IsTrue(IsNully(NullableEmptyList));
            IsTrue(IsNully(NullableEmptyHashSet));
            IsTrue(IsNully(NullableEmptyIList));
            IsTrue(IsNully(NullableEmptyISet));
            IsTrue(IsNully(NullableEmptyICollection));
            IsTrue(IsNully(NullableEmptyIReadOnlyList));
            IsTrue(IsNully(NullableEmptyIReadOnlyCollection));
            IsTrue(IsNully(NullableEmptyIEnumerable));
        }
        {
            IsTrue(NullArray.IsNully());
            IsTrue(NullList.IsNully());
            IsTrue(NullHashSet.IsNully());
            IsTrue(NullIList.IsNully());
            IsTrue(NullISet.IsNully());
            IsTrue(NullICollection.IsNully());
            IsTrue(NullIReadOnlyList.IsNully());
            IsTrue(NullIReadOnlyCollection.IsNully());
            IsTrue(NullIEnumerable.IsNully());
            IsTrue(IsNully(NullArray));
            IsTrue(IsNully(NullList));
            IsTrue(IsNully(NullHashSet));
            IsTrue(IsNully(NullIList));
            IsTrue(IsNully(NullISet));
            IsTrue(IsNully(NullICollection));
            IsTrue(IsNully(NullIReadOnlyList));
            IsTrue(IsNully(NullIReadOnlyCollection));
            IsTrue(IsNully(NullIEnumerable));
        }
    }
    
    [TestMethod]
    public void ImmutableArray_Emptiness()
    {
        IsFalse(FilledIn(ImmutableArrayWithDefault));
        IsFalse(FilledIn(ImmutableArrayWithDefaultNullable));
        IsFalse(FilledIn(ImmutableArrayWithNew));  
        IsFalse(FilledIn(ImmutableArrayWithNewNullable));
    }
}
