namespace JJ.Framework.Existence.Core.Tests;

[TestClass]
public class Has_Coll_Tests
{
    // FilledIn / Has
    
    [TestMethod]
    public void Collection_FilledIn_True_WhenFilled()
    {
        IsTrue(Has(FilledArray));
        IsTrue(Has(FilledList));
        IsTrue(Has(FilledHashSet));
        IsTrue(Has(FilledIList));
        IsTrue(Has(FilledISet));
        IsTrue(Has(FilledIColl));
        IsTrue(Has(FilledIReadOnlyList));
        IsTrue(Has(FilledIReadOnlyColl));
        IsTrue(Has(FilledIEnumerable));
        IsTrue(FilledArray.FilledIn());
        IsTrue(FilledList.FilledIn());
        IsTrue(FilledHashSet.FilledIn());
        IsTrue(FilledIList.FilledIn());
        IsTrue(FilledISet.FilledIn());
        IsTrue(FilledIColl.FilledIn());
        IsTrue(FilledIReadOnlyList.FilledIn());
        IsTrue(FilledIReadOnlyColl.FilledIn());
        IsTrue(FilledIEnumerable.FilledIn());
        IsTrue(FilledIn(FilledArray));
        IsTrue(FilledIn(FilledIList));
        IsTrue(FilledIn(FilledISet));
        IsTrue(FilledIn(FilledIDict));
        IsTrue(FilledIn(FilledIColl));
        IsTrue(FilledIn(FilledIEnumerable));
        IsTrue(FilledIn(FilledList));
        IsTrue(FilledIn(FilledHashSet));
        IsTrue(FilledIn(FilledStack));
        IsTrue(FilledIn(FilledQueue));
        IsTrue(FilledIn(FilledLinkedList));
        IsTrue(FilledIn(FilledSortedList));
        IsTrue(FilledIn(FilledSortedSet));
        IsTrue(FilledIn(FilledDict));
        IsTrue(FilledIn(FilledDictKeyColl));
        IsTrue(FilledIn(FilledDictValColl));
        IsTrue(FilledIn(FilledIImmutableList));
        IsTrue(FilledIn(FilledIImmutableSet));
        IsTrue(FilledIn(FilledIImmutableStack));
        IsTrue(FilledIn(FilledIImmutableQueue));
        IsTrue(FilledIn(FilledIImmutableDict));
        IsTrue(FilledIn(FilledImmutableArray));
        IsTrue(FilledIn(FilledImmutableArrayBuilder));
        IsTrue(FilledIn(FilledImmutableList));
        IsTrue(FilledIn(FilledImmutableListBuilder));
        IsTrue(FilledIn(FilledImmutableHashSet));
        IsTrue(FilledIn(FilledImmutableHashSetBuilder));
        IsTrue(FilledIn(FilledImmutableStack));
        IsTrue(FilledIn(FilledImmutableQueue));
        IsTrue(FilledIn(FilledImmutableDict));
        IsTrue(FilledIn(FilledImmutableDictBuilder));
        IsTrue(FilledIn(FilledImmutableSortedSet));
        IsTrue(FilledIn(FilledImmutableSortedSetBuilder));
        IsTrue(FilledIn(FilledImmutableSortedDict));
        IsTrue(FilledIn(FilledImmutableSortedDictBuilder));
        IsTrue(FilledIn(FilledIReadOnlyList));
        IsTrue(FilledIn(FilledIReadOnlyColl));
        IsTrue(FilledIn(FilledIReadOnlyColl));
        IsTrue(FilledIn(FilledIReadOnlyList));
        IsTrue(FilledIn(FilledIReadOnlyDict));
        IsTrue(FilledIn(FilledReadOnlyColl));
        IsTrue(FilledIn(FilledReadOnlyDict));
        IsTrue(FilledIn(FilledReadOnlyDictKeys));
        IsTrue(FilledIn(FilledReadOnlyDictVals));
        #if NET9_0_OR_GREATER
        IsTrue(FilledIn(FilledIReadOnlySet));
        IsTrue(FilledIn(FilledReadOnlySet));
        #endif
        IsTrue(FilledIn(FilledConcurrentBag));
        IsTrue(FilledIn(FilledConcurrentQueue));
        IsTrue(FilledIn(FilledConcurrentStack));
        IsTrue(FilledIn(FilledConcurrentDict));
        IsTrue(FilledIn(FilledBlockingColl));
        IsTrue(FilledIn(FilledIProducerConsumerColl));
        IsTrue(FilledIn(FilledSortedDict));
        IsTrue(FilledIn(FilledSortedDictKeys));
        IsTrue(FilledIn(FilledSortedDictVals));
        #if NET9_0_OR_GREATER
        IsTrue(FilledIn(FilledOrderedDict));
        IsTrue(FilledIn(FilledOrderedDictKeys));
        IsTrue(FilledIn(FilledOrderedDictVals));
        #endif
        #if NET6_0_OR_GREATER
        IsTrue(FilledIn(FilledPrioQueue));
        IsTrue(FilledIn(FilledPrioQueueUnorderedColl));
        #endif
        IsTrue(FilledIn(FilledColl));
        IsTrue(FilledIn(FilledKeyedColl));
        IsTrue(FilledIn(FilledObservableColl));
        IsTrue(FilledIn(FilledReadOnlyObservableColl));
        IsTrue(FilledIn(FilledArrayList));
        IsTrue(FilledIn(FilledBitArray));
        IsTrue(FilledIn(FilledCollBase));
        IsTrue(FilledIn(FilledDictBase));
        IsTrue(FilledIn(FilledHashtable));
        IsTrue(FilledIn(FilledQueueNonGeneric));
        IsTrue(FilledIn(FilledReadOnlyCollBase));
        IsTrue(FilledIn(FilledSortedListNonGeneric));
        IsTrue(FilledIn(FilledStackNonGeneric));
        IsTrue(FilledIn(FilledHybridDict));
        IsTrue(FilledIn(FilledListDict));
        IsTrue(FilledIn(FilledNameObjectCollBase));
        IsTrue(FilledIn(FilledNameObjectCollBaseKeys));
        IsTrue(FilledIn(FilledNameValueColl));
        IsTrue(FilledIn(FilledOrderedDictNonGeneric));
        IsTrue(FilledIn(FilledStringColl));
        IsTrue(FilledIn(FilledStringDict));
        IsTrue(FilledIn(FilledIOrderedDict));
    }

    [TestMethod]
    public void Collection_FilledIn_True_ForNullable_WhenFilled()
    {
        IsTrue(Has(NullyFilledArray));
        IsTrue(Has(NullyFilledList));
        IsTrue(Has(NullyFilledHashSet));
        IsTrue(Has(NullyFilledIList));
        IsTrue(Has(NullyFilledISet));
        IsTrue(Has(NullyFilledIColl));
        IsTrue(Has(NullyFilledIReadOnlyList));
        IsTrue(Has(NullyFilledIReadOnlyColl));
        IsTrue(Has(NullyFilledIEnumerable));
        IsTrue(NullyFilledArray.FilledIn());
        IsTrue(NullyFilledList.FilledIn());
        IsTrue(NullyFilledHashSet.FilledIn());
        IsTrue(NullyFilledIList.FilledIn());
        IsTrue(NullyFilledISet.FilledIn());
        IsTrue(NullyFilledIColl.FilledIn());
        IsTrue(NullyFilledIReadOnlyList.FilledIn());
        IsTrue(NullyFilledIReadOnlyColl.FilledIn());
        IsTrue(NullyFilledIEnumerable.FilledIn());
        IsTrue(FilledIn(NullyFilledArray));
        IsTrue(FilledIn(NullyFilledIList));
        IsTrue(FilledIn(NullyFilledISet));
        IsTrue(FilledIn(NullyFilledIDict));
        IsTrue(FilledIn(NullyFilledIColl));
        IsTrue(FilledIn(NullyFilledIEnumerable));
        IsTrue(FilledIn(NullyFilledList));
        IsTrue(FilledIn(NullyFilledHashSet));
        IsTrue(FilledIn(NullyFilledStack));
        IsTrue(FilledIn(NullyFilledQueue));
        IsTrue(FilledIn(NullyFilledLinkedList));
        IsTrue(FilledIn(NullyFilledSortedList));
        IsTrue(FilledIn(NullyFilledSortedSet));
        IsTrue(FilledIn(NullyFilledDict));
        IsTrue(FilledIn(NullyFilledDictKeyColl));
        IsTrue(FilledIn(NullyFilledDictValColl));
        IsTrue(FilledIn(NullyFilledIImmutableList));
        IsTrue(FilledIn(NullyFilledIImmutableSet));
        IsTrue(FilledIn(NullyFilledIImmutableStack));
        IsTrue(FilledIn(NullyFilledIImmutableQueue));
        IsTrue(FilledIn(NullyFilledIImmutableDict));
        IsTrue(FilledIn(NullyFilledImmutableArray));
        IsTrue(FilledIn(NullyFilledImmutableArrayBuilder));
        IsTrue(FilledIn(NullyFilledImmutableList));
        IsTrue(FilledIn(NullyFilledImmutableListBuilder));
        IsTrue(FilledIn(NullyFilledImmutableHashSet));
        IsTrue(FilledIn(NullyFilledImmutableHashSetBuilder));
        IsTrue(FilledIn(NullyFilledImmutableStack));
        IsTrue(FilledIn(NullyFilledImmutableQueue));
        IsTrue(FilledIn(NullyFilledImmutableDict));
        IsTrue(FilledIn(NullyFilledImmutableDictBuilder));
        IsTrue(FilledIn(NullyFilledImmutableSortedSet));
        IsTrue(FilledIn(NullyFilledImmutableSortedSetBuilder));
        IsTrue(FilledIn(NullyFilledImmutableSortedDict));
        IsTrue(FilledIn(NullyFilledImmutableSortedDictBuilder));
        IsTrue(FilledIn(NullyFilledIReadOnlyList));
        IsTrue(FilledIn(NullyFilledIReadOnlyColl));
        IsTrue(FilledIn(NullyFilledIReadOnlyColl));
        IsTrue(FilledIn(NullyFilledIReadOnlyList));
        IsTrue(FilledIn(NullyFilledIReadOnlyDict));
        IsTrue(FilledIn(NullyFilledReadOnlyColl));
        IsTrue(FilledIn(NullyFilledReadOnlyDict));
        IsTrue(FilledIn(NullyFilledReadOnlyDictKeys));
        IsTrue(FilledIn(NullyFilledReadOnlyDictVals));
        #if NET9_0_OR_GREATER
        IsTrue(FilledIn(NullyFilledIReadOnlySet));
        IsTrue(FilledIn(NullyFilledReadOnlySet));
        #endif
        IsTrue(FilledIn(NullyFilledConcurrentBag));
        IsTrue(FilledIn(NullyFilledConcurrentQueue));
        IsTrue(FilledIn(NullyFilledConcurrentStack));
        IsTrue(FilledIn(NullyFilledConcurrentDict));
        IsTrue(FilledIn(NullyFilledBlockingColl));
        IsTrue(FilledIn(NullyFilledIProducerConsumerColl));
        IsTrue(FilledIn(NullyFilledSortedDict));
        IsTrue(FilledIn(NullyFilledSortedDictKeys));
        IsTrue(FilledIn(NullyFilledSortedDictVals));
        #if NET9_0_OR_GREATER
        IsTrue(FilledIn(NullyFilledOrderedDict));
        IsTrue(FilledIn(NullyFilledOrderedDictKeys));
        IsTrue(FilledIn(NullyFilledOrderedDictVals));
        #endif
        #if NET6_0_OR_GREATER
        IsTrue(FilledIn(NullyFilledPrioQueue));
        IsTrue(FilledIn(NullyFilledPrioQueueUnorderedColl));
        #endif
        IsTrue(FilledIn(NullyFilledColl));
        IsTrue(FilledIn(NullyFilledKeyedColl));
        IsTrue(FilledIn(NullyFilledObservableColl));
        IsTrue(FilledIn(NullyFilledReadOnlyObservableColl));
        IsTrue(FilledIn(NullyFilledArrayList));
        IsTrue(FilledIn(NullyFilledBitArray));
        IsTrue(FilledIn(NullyFilledCollBase));
        IsTrue(FilledIn(NullyFilledDictBase));
        IsTrue(FilledIn(NullyFilledHashtable));
        IsTrue(FilledIn(NullyFilledQueueNonGeneric));
        IsTrue(FilledIn(NullyFilledReadOnlyCollBase));
        IsTrue(FilledIn(NullyFilledSortedListNonGeneric));
        IsTrue(FilledIn(NullyFilledStackNonGeneric));
        IsTrue(FilledIn(NullyFilledHybridDict));
        IsTrue(FilledIn(NullyFilledListDict));
        IsTrue(FilledIn(NullyFilledNameObjectCollBase));
        IsTrue(FilledIn(NullyFilledNameObjectCollBaseKeys));
        IsTrue(FilledIn(NullyFilledNameValueColl));
        IsTrue(FilledIn(NullyFilledOrderedDictNonGeneric));
        IsTrue(FilledIn(NullyFilledStringColl));
        IsTrue(FilledIn(NullyFilledStringDict));
        IsTrue(FilledIn(NullyFilledIOrderedDict));
    }
      
    [TestMethod]
    public void Collection_FilledIn_False_WhenEmpty()
    {
        IsFalse(Has(EmptyArray));
        IsFalse(Has(EmptyList));
        IsFalse(Has(EmptyHashSet));
        IsFalse(Has(EmptyIList));
        IsFalse(Has(EmptyISet));
        IsFalse(Has(EmptyIColl));
        IsFalse(Has(EmptyIReadOnlyList));
        IsFalse(Has(EmptyIReadOnlyColl));
        IsFalse(Has(EmptyIEnumerable));
        IsFalse(EmptyArray.FilledIn());
        IsFalse(EmptyList.FilledIn());
        IsFalse(EmptyHashSet.FilledIn());
        IsFalse(EmptyIList.FilledIn());
        IsFalse(EmptyISet.FilledIn());
        IsFalse(EmptyIColl.FilledIn());
        IsFalse(EmptyIReadOnlyList.FilledIn());
        IsFalse(EmptyIReadOnlyColl.FilledIn());
        IsFalse(EmptyIEnumerable.FilledIn());
        IsFalse(FilledIn(EmptyArray));
        IsFalse(FilledIn(EmptyIList));
        IsFalse(FilledIn(EmptyISet));
        IsFalse(FilledIn(EmptyIDict));
        IsFalse(FilledIn(EmptyIColl));
        IsFalse(FilledIn(EmptyIEnumerable));
        IsFalse(FilledIn(EmptyList));
        IsFalse(FilledIn(EmptyHashSet));
        IsFalse(FilledIn(EmptyStack));
        IsFalse(FilledIn(EmptyQueue));
        IsFalse(FilledIn(EmptyLinkedList));
        IsFalse(FilledIn(EmptySortedList));
        IsFalse(FilledIn(EmptySortedSet));
        IsFalse(FilledIn(EmptyDict));
        IsFalse(FilledIn(EmptyDictKeyColl));
        IsFalse(FilledIn(EmptyDictValColl));
        IsFalse(FilledIn(EmptyIImmutableList));
        IsFalse(FilledIn(EmptyIImmutableSet));
        IsFalse(FilledIn(EmptyIImmutableStack));
        IsFalse(FilledIn(EmptyIImmutableQueue));
        IsFalse(FilledIn(EmptyIImmutableDict));
        IsFalse(FilledIn(EmptyImmutableArray));
        IsFalse(FilledIn(EmptyImmutableArrayBuilder));
        IsFalse(FilledIn(EmptyImmutableList));
        IsFalse(FilledIn(EmptyImmutableListBuilder));
        IsFalse(FilledIn(EmptyImmutableHashSet));
        IsFalse(FilledIn(EmptyImmutableHashSetBuilder));
        IsFalse(FilledIn(EmptyImmutableStack));
        IsFalse(FilledIn(EmptyImmutableQueue));
        IsFalse(FilledIn(EmptyImmutableDict));
        IsFalse(FilledIn(EmptyImmutableDictBuilder));
        IsFalse(FilledIn(EmptyImmutableSortedSet));
        IsFalse(FilledIn(EmptyImmutableSortedSetBuilder));
        IsFalse(FilledIn(EmptyImmutableSortedDict));
        IsFalse(FilledIn(EmptyImmutableSortedDictBuilder));
        IsFalse(FilledIn(EmptyIReadOnlyList));
        IsFalse(FilledIn(EmptyIReadOnlyColl));
        IsFalse(FilledIn(EmptyIReadOnlyList));
        IsFalse(FilledIn(EmptyIReadOnlyColl));
        IsFalse(FilledIn(EmptyIReadOnlyColl));
        IsFalse(FilledIn(EmptyIReadOnlyList));
        IsFalse(FilledIn(EmptyIReadOnlyDict));
        IsFalse(FilledIn(EmptyReadOnlyColl));
        IsFalse(FilledIn(EmptyReadOnlyDict));
        IsFalse(FilledIn(EmptyReadOnlyDictKeys));
        IsFalse(FilledIn(EmptyReadOnlyDictVals));
        #if NET9_0_OR_GREATER
        IsFalse(FilledIn(EmptyIReadOnlySet));
        IsFalse(FilledIn(EmptyReadOnlySet));
        #endif
        IsFalse(FilledIn(EmptyConcurrentBag));
        IsFalse(FilledIn(EmptyConcurrentQueue));
        IsFalse(FilledIn(EmptyConcurrentStack));
        IsFalse(FilledIn(EmptyConcurrentDict));
        IsFalse(FilledIn(EmptyBlockingColl));
        IsFalse(FilledIn(EmptyIProducerConsumerColl));
        IsFalse(FilledIn(EmptySortedDict));
        IsFalse(FilledIn(EmptySortedDictKeys));
        IsFalse(FilledIn(EmptySortedDictVals));
        #if NET9_0_OR_GREATER
        IsFalse(FilledIn(EmptyOrderedDict));
        IsFalse(FilledIn(EmptyOrderedDictKeys));
        IsFalse(FilledIn(EmptyOrderedDictVals));
        #endif
        #if NET6_0_OR_GREATER
        IsFalse(FilledIn(EmptyPrioQueue));
        IsFalse(FilledIn(EmptyPrioQueueUnorderedColl));
        #endif
        IsFalse(FilledIn(EmptyColl));
        IsFalse(FilledIn(EmptyKeyedColl));
        IsFalse(FilledIn(EmptyObservableColl));
        IsFalse(FilledIn(EmptyReadOnlyObservableColl));
        IsFalse(FilledIn(EmptyArrayList));
        IsFalse(FilledIn(EmptyBitArray));
        IsFalse(FilledIn(EmptyCollBase));
        IsFalse(FilledIn(EmptyDictBase));
        IsFalse(FilledIn(EmptyHashtable));
        IsFalse(FilledIn(EmptyQueueNonGeneric));
        IsFalse(FilledIn(EmptyReadOnlyCollBase));
        IsFalse(FilledIn(EmptySortedListNonGeneric));
        IsFalse(FilledIn(EmptyStackNonGeneric));
        IsFalse(FilledIn(EmptyHybridDict));
        IsFalse(FilledIn(EmptyListDict));
        IsFalse(FilledIn(EmptyNameObjectCollBase));
        IsFalse(FilledIn(EmptyNameObjectCollBaseKeys));
        IsFalse(FilledIn(EmptyNameValueColl));
        IsFalse(FilledIn(EmptyOrderedDictNonGeneric));
        IsFalse(FilledIn(EmptyStringColl));
        IsFalse(FilledIn(EmptyStringDict));
        IsFalse(FilledIn(EmptyIOrderedDict));
    }
      
    [TestMethod]
    public void Collection_FilledIn_False_ForNullable_WhenEmpty()
    {
        IsFalse(Has(NullableEmptyArray));
        IsFalse(Has(NullableEmptyList));
        IsFalse(Has(NullableEmptyHashSet));
        IsFalse(Has(NullableEmptyIList));
        IsFalse(Has(NullableEmptyISet));
        IsFalse(Has(NullableEmptyIColl));
        IsFalse(Has(NullableEmptyIReadOnlyList));
        IsFalse(Has(NullableEmptyIReadOnlyColl));
        IsFalse(Has(NullableEmptyIEnumerable));
        IsFalse(NullableEmptyArray.FilledIn());
        IsFalse(NullableEmptyList.FilledIn());
        IsFalse(NullableEmptyHashSet.FilledIn());
        IsFalse(NullableEmptyIList.FilledIn());
        IsFalse(NullableEmptyISet.FilledIn());
        IsFalse(NullableEmptyIColl.FilledIn());
        IsFalse(NullableEmptyIReadOnlyList.FilledIn());
        IsFalse(NullableEmptyIReadOnlyColl.FilledIn());
        IsFalse(NullableEmptyIEnumerable.FilledIn());
        IsFalse(FilledIn(NullableEmptyArray));
        IsFalse(FilledIn(NullableEmptyIList));
        IsFalse(FilledIn(NullableEmptyISet));
        IsFalse(FilledIn(NullableEmptyIDict));
        IsFalse(FilledIn(NullableEmptyIColl));
        IsFalse(FilledIn(NullableEmptyIEnumerable));
        IsFalse(FilledIn(NullableEmptyList));
        IsFalse(FilledIn(NullableEmptyHashSet));
        IsFalse(FilledIn(NullableEmptyStack));
        IsFalse(FilledIn(NullableEmptyQueue));
        IsFalse(FilledIn(NullableEmptyLinkedList));
        IsFalse(FilledIn(NullableEmptySortedList));
        IsFalse(FilledIn(NullableEmptySortedSet));
        IsFalse(FilledIn(NullableEmptyDict));
        IsFalse(FilledIn(NullableEmptyDictKeyColl));
        IsFalse(FilledIn(NullableEmptyDictValColl));
        IsFalse(FilledIn(NullableEmptyIImmutableList));
        IsFalse(FilledIn(NullableEmptyIImmutableSet));
        IsFalse(FilledIn(NullableEmptyIImmutableStack));
        IsFalse(FilledIn(NullableEmptyIImmutableQueue));
        IsFalse(FilledIn(NullableEmptyIImmutableDict));
        IsFalse(FilledIn(NullableEmptyImmutableArray));
        IsFalse(FilledIn(NullableEmptyImmutableArrayBuilder));
        IsFalse(FilledIn(NullableEmptyImmutableList));
        IsFalse(FilledIn(NullableEmptyImmutableListBuilder));
        IsFalse(FilledIn(NullableEmptyImmutableHashSet));
        IsFalse(FilledIn(NullableEmptyImmutableHashSetBuilder));
        IsFalse(FilledIn(NullableEmptyImmutableStack));
        IsFalse(FilledIn(NullableEmptyImmutableQueue));
        IsFalse(FilledIn(NullableEmptyImmutableDict));
        IsFalse(FilledIn(NullableEmptyImmutableDictBuilder));
        IsFalse(FilledIn(NullableEmptyImmutableSortedSet));
        IsFalse(FilledIn(NullableEmptyImmutableSortedSetBuilder));
        IsFalse(FilledIn(NullableEmptyImmutableSortedDict));
        IsFalse(FilledIn(NullableEmptyImmutableSortedDictBuilder));
        IsFalse(FilledIn(NullableEmptyIReadOnlyList));
        IsFalse(FilledIn(NullableEmptyIReadOnlyColl));
        IsFalse(FilledIn(NullableEmptyIReadOnlyColl));
        IsFalse(FilledIn(NullableEmptyIReadOnlyList));
        IsFalse(FilledIn(NullableEmptyIReadOnlyDict));
        IsFalse(FilledIn(NullableEmptyReadOnlyColl));
        IsFalse(FilledIn(NullableEmptyReadOnlyDict));
        IsFalse(FilledIn(NullableEmptyReadOnlyDictKeys));
        IsFalse(FilledIn(NullableEmptyReadOnlyDictVals));
        #if NET9_0_OR_GREATER
        IsFalse(FilledIn(NullableEmptyIReadOnlySet));
        IsFalse(FilledIn(NullableEmptyReadOnlySet));
        #endif
        IsFalse(FilledIn(NullableEmptyConcurrentBag));
        IsFalse(FilledIn(NullableEmptyConcurrentQueue));
        IsFalse(FilledIn(NullableEmptyConcurrentStack));
        IsFalse(FilledIn(NullableEmptyConcurrentDict));
        IsFalse(FilledIn(NullableEmptyBlockingColl));
        IsFalse(FilledIn(NullableEmptyIProducerConsumerColl));
        IsFalse(FilledIn(NullableEmptySortedDict));
        IsFalse(FilledIn(NullableEmptySortedDictKeys));
        IsFalse(FilledIn(NullableEmptySortedDictVals));
        #if NET9_0_OR_GREATER
        IsFalse(FilledIn(NullableEmptyOrderedDict));
        IsFalse(FilledIn(NullableEmptyOrderedDictKeys));
        IsFalse(FilledIn(NullableEmptyOrderedDictVals));
        #endif
        #if NET6_0_OR_GREATER
        IsFalse(FilledIn(NullableEmptyPrioQueue));
        IsFalse(FilledIn(NullableEmptyPrioQueueUnorderedColl));
        #endif
        IsFalse(FilledIn(NullableEmptyColl));
        IsFalse(FilledIn(NullableEmptyKeyedColl));
        IsFalse(FilledIn(NullableEmptyObservableColl));
        IsFalse(FilledIn(NullableEmptyReadOnlyObservableColl));
        IsFalse(FilledIn(NullableEmptyArrayList));
        IsFalse(FilledIn(NullableEmptyBitArray));
        IsFalse(FilledIn(NullableEmptyCollBase));
        IsFalse(FilledIn(NullableEmptyDictBase));
        IsFalse(FilledIn(NullableEmptyHashtable));
        IsFalse(FilledIn(NullableEmptyQueueNonGeneric));
        IsFalse(FilledIn(NullableEmptyReadOnlyCollBase));
        IsFalse(FilledIn(NullableEmptySortedListNonGeneric));
        IsFalse(FilledIn(NullableEmptyStackNonGeneric));
        IsFalse(FilledIn(NullableEmptyHybridDict));
        IsFalse(FilledIn(NullableEmptyListDict));
        IsFalse(FilledIn(NullableEmptyNameObjectCollBase));
        IsFalse(FilledIn(NullableEmptyNameObjectCollBaseKeys));
        IsFalse(FilledIn(NullableEmptyNameValueColl));
        IsFalse(FilledIn(NullableEmptyOrderedDictNonGeneric));
        IsFalse(FilledIn(NullableEmptyStringColl));
        IsFalse(FilledIn(NullableEmptyStringDict));
        IsFalse(FilledIn(NullableEmptyIOrderedDict));
    }
      
    [TestMethod]
    public void Collection_FilledIn_False_WhenNull()
    {
        IsFalse(Has(NullArray));
        IsFalse(Has(NullList));
        IsFalse(Has(NullHashSet));
        IsFalse(Has(NullIList));
        IsFalse(Has(NullISet));
        IsFalse(Has(NullIColl));
        IsFalse(Has(NullIReadOnlyList));
        IsFalse(Has(NullIReadOnlyColl));
        IsFalse(Has(NullIEnumerable));
        IsFalse(NullArray.FilledIn());
        IsFalse(NullList.FilledIn());
        IsFalse(NullHashSet.FilledIn());
        IsFalse(NullIList.FilledIn());
        IsFalse(NullISet.FilledIn());
        IsFalse(NullIColl.FilledIn());
        IsFalse(NullIReadOnlyList.FilledIn());
        IsFalse(NullIReadOnlyColl.FilledIn());
        IsFalse(NullIEnumerable.FilledIn());
        IsFalse(FilledIn(NullArray));
        IsFalse(FilledIn(NullIList));
        IsFalse(FilledIn(NullISet));
        IsFalse(FilledIn(NullIDict));
        IsFalse(FilledIn(NullIColl));
        IsFalse(FilledIn(NullIEnumerable));
        IsFalse(FilledIn(NullList));
        IsFalse(FilledIn(NullHashSet));
        IsFalse(FilledIn(NullStack));
        IsFalse(FilledIn(NullQueue));
        IsFalse(FilledIn(NullLinkedList));
        IsFalse(FilledIn(NullSortedList));
        IsFalse(FilledIn(NullSortedSet));
        IsFalse(FilledIn(NullDict));
        IsFalse(FilledIn(NullDictKeyColl));
        IsFalse(FilledIn(NullDictValColl));
        IsFalse(FilledIn(NullIImmutableList));
        IsFalse(FilledIn(NullIImmutableSet));
        IsFalse(FilledIn(NullIImmutableStack));
        IsFalse(FilledIn(NullIImmutableQueue));
        IsFalse(FilledIn(NullIImmutableDict));
        IsFalse(FilledIn(NullImmutableArray));
        IsFalse(FilledIn(NullImmutableArrayBuilder));
        IsFalse(FilledIn(NullImmutableList));
        IsFalse(FilledIn(NullImmutableListBuilder));
        IsFalse(FilledIn(NullImmutableHashSet));
        IsFalse(FilledIn(NullImmutableHashSetBuilder));
        IsFalse(FilledIn(NullImmutableStack));
        IsFalse(FilledIn(NullImmutableQueue));
        IsFalse(FilledIn(NullImmutableDict));
        IsFalse(FilledIn(NullImmutableDictBuilder));
        IsFalse(FilledIn(NullImmutableSortedSet));
        IsFalse(FilledIn(NullImmutableSortedSetBuilder));
        IsFalse(FilledIn(NullImmutableSortedDict));
        IsFalse(FilledIn(NullImmutableSortedDictBuilder));
        IsFalse(FilledIn(NullIReadOnlyList));
        IsFalse(FilledIn(NullIReadOnlyColl));
        IsFalse(FilledIn(NullIReadOnlyList));
        IsFalse(FilledIn(NullIReadOnlyColl));
        IsFalse(FilledIn(NullIReadOnlyColl));
        IsFalse(FilledIn(NullIReadOnlyList));
        IsFalse(FilledIn(NullIReadOnlyDict));
        IsFalse(FilledIn(NullReadOnlyColl));
        IsFalse(FilledIn(NullReadOnlyDict));
        IsFalse(FilledIn(NullReadOnlyDictKeys));
        IsFalse(FilledIn(NullReadOnlyDictVals));
        #if NET9_0_OR_GREATER
        IsFalse(FilledIn(NullIReadOnlySet));
        IsFalse(FilledIn(NullReadOnlySet));
        #endif
        IsFalse(FilledIn(NullConcurrentBag));
        IsFalse(FilledIn(NullConcurrentQueue));
        IsFalse(FilledIn(NullConcurrentStack));
        IsFalse(FilledIn(NullConcurrentDict));
        IsFalse(FilledIn(NullBlockingColl));
        IsFalse(FilledIn(NullIProducerConsumerColl));
        IsFalse(FilledIn(NullSortedDict));
        IsFalse(FilledIn(NullSortedDictKeys));
        IsFalse(FilledIn(NullSortedDictVals));
        #if NET9_0_OR_GREATER
        IsFalse(FilledIn(NullOrderedDict));
        IsFalse(FilledIn(NullOrderedDictKeys));
        IsFalse(FilledIn(NullOrderedDictVals));
        #endif
        #if NET6_0_OR_GREATER
        IsFalse(FilledIn(NullPrioQueue));
        IsFalse(FilledIn(NullPrioQueueUnorderedColl));
        #endif
        IsFalse(FilledIn(NullColl));
        IsFalse(FilledIn(NullKeyedColl));
        IsFalse(FilledIn(NullObservableColl));
        IsFalse(FilledIn(NullReadOnlyObservableColl));
        IsFalse(FilledIn(NullArrayList));
        IsFalse(FilledIn(NullBitArray));
        IsFalse(FilledIn(NullCollBase));
        IsFalse(FilledIn(NullDictBase));
        IsFalse(FilledIn(NullHashtable));
        IsFalse(FilledIn(NullQueueNonGeneric));
        IsFalse(FilledIn(NullReadOnlyCollBase));
        IsFalse(FilledIn(NullSortedListNonGeneric));
        IsFalse(FilledIn(NullStackNonGeneric));
        IsFalse(FilledIn(NullHybridDict));
        IsFalse(FilledIn(NullListDict));
        IsFalse(FilledIn(NullNameObjectCollBase));
        IsFalse(FilledIn(NullNameObjectCollBaseKeys));
        IsFalse(FilledIn(NullNameValueColl));
        IsFalse(FilledIn(NullOrderedDictNonGeneric));
        IsFalse(FilledIn(NullStringColl));
        IsFalse(FilledIn(NullStringDict));
        IsFalse(FilledIn(NullIOrderedDict));
    }
    
    // IsNully
    
    [TestMethod]
    public void Collection_IsNully_False_WhenFilled()
    {
        IsFalse(FilledArray.IsNully());
        IsFalse(FilledList.IsNully());
        IsFalse(FilledHashSet.IsNully());
        IsFalse(FilledIList.IsNully());
        IsFalse(FilledISet.IsNully());
        IsFalse(FilledIColl.IsNully());
        IsFalse(FilledIReadOnlyList.IsNully());
        IsFalse(FilledIReadOnlyColl.IsNully());
        IsFalse(FilledIEnumerable.IsNully());
        IsFalse(IsNully(FilledArray));
        IsFalse(IsNully(FilledList));
        IsFalse(IsNully(FilledHashSet));
        IsFalse(IsNully(FilledIList));
        IsFalse(IsNully(FilledISet));
        IsFalse(IsNully(FilledIColl));
        IsFalse(IsNully(FilledIReadOnlyList));
        IsFalse(IsNully(FilledIReadOnlyColl));
        IsFalse(IsNully(FilledIEnumerable));
    }
    
    [TestMethod]
    public void Collection_IsNully_False_ForNullable_WhenFilled()
    {
        IsFalse(NullyFilledArray.IsNully());
        IsFalse(NullyFilledList.IsNully());
        IsFalse(NullyFilledHashSet.IsNully());
        IsFalse(NullyFilledIList.IsNully());
        IsFalse(NullyFilledISet.IsNully());
        IsFalse(NullyFilledIColl.IsNully());
        IsFalse(NullyFilledIReadOnlyList.IsNully());
        IsFalse(NullyFilledIReadOnlyColl.IsNully());
        IsFalse(NullyFilledIEnumerable.IsNully());
        IsFalse(IsNully(NullyFilledArray));
        IsFalse(IsNully(NullyFilledList));
        IsFalse(IsNully(NullyFilledHashSet));
        IsFalse(IsNully(NullyFilledIList));
        IsFalse(IsNully(NullyFilledISet));
        IsFalse(IsNully(NullyFilledIColl));
        IsFalse(IsNully(NullyFilledIReadOnlyList));
        IsFalse(IsNully(NullyFilledIReadOnlyColl));
        IsFalse(IsNully(NullyFilledIEnumerable));
    }
    
    [TestMethod]
    public void Collection_IsNully_True_WhenEmpty()
    {
        IsTrue(EmptyArray.IsNully());
        IsTrue(EmptyList.IsNully());
        IsTrue(EmptyHashSet.IsNully());
        IsTrue(EmptyIList.IsNully());
        IsTrue(EmptyISet.IsNully());
        IsTrue(EmptyIColl.IsNully());
        IsTrue(EmptyIReadOnlyList.IsNully());
        IsTrue(EmptyIReadOnlyColl.IsNully());
        IsTrue(EmptyIEnumerable.IsNully());
        IsTrue(IsNully(EmptyArray));
        IsTrue(IsNully(EmptyList));
        IsTrue(IsNully(EmptyHashSet));
        IsTrue(IsNully(EmptyIList));
        IsTrue(IsNully(EmptyISet));
        IsTrue(IsNully(EmptyIColl));
        IsTrue(IsNully(EmptyIReadOnlyList));
        IsTrue(IsNully(EmptyIReadOnlyColl));
        IsTrue(IsNully(EmptyIEnumerable));
    }
    
    [TestMethod]
    public void Collection_IsNully_True_ForNullable_WhenEmpty()
    {
        IsTrue(NullableEmptyArray.IsNully());
        IsTrue(NullableEmptyList.IsNully());
        IsTrue(NullableEmptyHashSet.IsNully());
        IsTrue(NullableEmptyIList.IsNully());
        IsTrue(NullableEmptyISet.IsNully());
        IsTrue(NullableEmptyIColl.IsNully());
        IsTrue(NullableEmptyIReadOnlyList.IsNully());
        IsTrue(NullableEmptyIReadOnlyColl.IsNully());
        IsTrue(NullableEmptyIEnumerable.IsNully());
        IsTrue(IsNully(NullableEmptyArray));
        IsTrue(IsNully(NullableEmptyList));
        IsTrue(IsNully(NullableEmptyHashSet));
        IsTrue(IsNully(NullableEmptyIList));
        IsTrue(IsNully(NullableEmptyISet));
        IsTrue(IsNully(NullableEmptyIColl));
        IsTrue(IsNully(NullableEmptyIReadOnlyList));
        IsTrue(IsNully(NullableEmptyIReadOnlyColl));
        IsTrue(IsNully(NullableEmptyIEnumerable));
    }
    
    [TestMethod]
    public void Collection_IsNully_True_ForNulls()
    {
        IsTrue(NullArray.IsNully());
        IsTrue(NullList.IsNully());
        IsTrue(NullHashSet.IsNully());
        IsTrue(NullIList.IsNully());
        IsTrue(NullISet.IsNully());
        IsTrue(NullIColl.IsNully());
        IsTrue(NullIReadOnlyList.IsNully());
        IsTrue(NullIReadOnlyColl.IsNully());
        IsTrue(NullIEnumerable.IsNully());
        IsTrue(IsNully(NullArray));
        IsTrue(IsNully(NullList));
        IsTrue(IsNully(NullHashSet));
        IsTrue(IsNully(NullIList));
        IsTrue(IsNully(NullISet));
        IsTrue(IsNully(NullIColl));
        IsTrue(IsNully(NullIReadOnlyList));
        IsTrue(IsNully(NullIReadOnlyColl));
        IsTrue(IsNully(NullIEnumerable));
    }
    
    [TestMethod]
    public void ImmutableArray_AdditionalStatesOf_Emptiness()
    {
        IsFalse(FilledIn(ImmutableArrayWithDefault));
        IsFalse(FilledIn(ImmutableArrayWithDefaultNullable));
        IsFalse(FilledIn(ImmutableArrayWithNew));  
        IsFalse(FilledIn(ImmutableArrayWithNewNullable));
    }
}
