namespace JJ.Framework.Existence.Core.Tests;

[TestClass]
public class IsNully_Collection_No_Tests
{
    [TestMethod]
    public void IsNully_Collection_NoWhenFilled()
    {
        IsFalse(FilledArray.IsNully());
        IsFalse(FilledIList.IsNully());
        IsFalse(FilledISet.IsNully());
        IsFalse(FilledIDict.IsNully());
        IsFalse(FilledIColl.IsNully());
        IsFalse(FilledILookup.IsNully());
        IsFalse(FilledIEnumerable.IsNully());
        IsFalse(FilledList.IsNully());
        IsFalse(FilledHashSet.IsNully());
        IsFalse(FilledStack.IsNully());
        IsFalse(FilledQueue.IsNully());
        IsFalse(FilledLinkedList.IsNully());
        IsFalse(FilledSortedList.IsNully());
        IsFalse(FilledSortedSet.IsNully());
        IsFalse(FilledDict.IsNully());
        IsFalse(FilledDictKeyColl.IsNully());
        IsFalse(FilledDictValColl.IsNully());
        IsFalse(FilledIImmutableList.IsNully());
        IsFalse(FilledIImmutableSet.IsNully());
        IsFalse(FilledIImmutableStack.IsNully());
        IsFalse(FilledIImmutableQueue.IsNully());
        IsFalse(FilledIImmutableDict.IsNully());
        IsFalse(FilledImmutableArray.IsNully());
        IsFalse(FilledImmutableArrayBuilder.IsNully());
        IsFalse(FilledImmutableList.IsNully());
        IsFalse(FilledImmutableListBuilder.IsNully());
        IsFalse(FilledImmutableHashSet.IsNully());
        IsFalse(FilledImmutableHashSetBuilder.IsNully());
        IsFalse(FilledImmutableStack.IsNully());
        IsFalse(FilledImmutableQueue.IsNully());
        IsFalse(FilledImmutableDict.IsNully());
        IsFalse(FilledImmutableDictBuilder.IsNully());
        IsFalse(FilledImmutableSortedSet.IsNully());
        IsFalse(FilledImmutableSortedSetBuilder.IsNully());
        IsFalse(FilledImmutableSortedDict.IsNully());
        IsFalse(FilledImmutableSortedDictBuilder.IsNully());
        IsFalse(FilledIReadOnlyList.IsNully());
        IsFalse(FilledIReadOnlyColl.IsNully());
        IsFalse(FilledIReadOnlyList.IsNully());
        IsFalse(FilledIReadOnlyColl.IsNully());
        IsFalse(FilledIReadOnlyColl.IsNully());
        IsFalse(FilledIReadOnlyList.IsNully());
        IsFalse(FilledIReadOnlyDict.IsNully());
        IsFalse(FilledReadOnlyColl.IsNully());
        IsFalse(FilledReadOnlyDict.IsNully());
        IsFalse(FilledReadOnlyDictKeys.IsNully());
        IsFalse(FilledReadOnlyDictVals.IsNully());
        IsFalse(FilledArraySegment.IsNully());
        IsFalse(FilledMemory.IsNully());
        IsFalse(FilledReadOnlyMemory.IsNully());
        IsFalse(FilledReadOnlySequence.IsNully());
        IsFalse(FilledConcurrentBag.IsNully());
        IsFalse(FilledConcurrentQueue.IsNully());
        IsFalse(FilledConcurrentStack.IsNully());
        IsFalse(FilledConcurrentDict.IsNully());
        IsFalse(FilledBlockingColl.IsNully());
        IsFalse(FilledIProducerConsumerColl.IsNully());
        IsFalse(FilledSortedDict.IsNully());
        IsFalse(FilledSortedDictKeys.IsNully());
        IsFalse(FilledSortedDictVals.IsNully());
        IsFalse(FilledColl.IsNully());
        IsFalse(FilledKeyedColl.IsNully());
        IsFalse(FilledObservableColl.IsNully());
        IsFalse(FilledReadOnlyObservableColl.IsNully());
        IsFalse(FilledArrayList.IsNully());
        IsFalse(FilledBitArray.IsNully());
        IsFalse(FilledCollBase.IsNully());
        IsFalse(FilledDictBase.IsNully());
        IsFalse(FilledHashtable.IsNully());
        IsFalse(FilledQueueNonGeneric.IsNully());
        IsFalse(FilledReadOnlyCollBase.IsNully());
        IsFalse(FilledSortedListNonGeneric.IsNully());
        IsFalse(FilledStackNonGeneric.IsNully());
        IsFalse(FilledHybridDict.IsNully());
        IsFalse(FilledListDict.IsNully());
        IsFalse(FilledNameObjectCollBase.IsNully());
        IsFalse(FilledNameObjectCollBaseKeys.IsNully());
        IsFalse(FilledNameValueColl.IsNully());
        IsFalse(FilledOrderedDictNonGeneric.IsNully());
        IsFalse(FilledStringColl.IsNully());
        IsFalse(FilledStringDict.IsNully());
        IsFalse(FilledIOrderedDict.IsNully());
        #if NET9_0_OR_GREATER
        IsFalse(FilledOrderedDict.IsNully());
        IsFalse(FilledOrderedDictKeys.IsNully());
        IsFalse(FilledOrderedDictVals.IsNully());
        IsFalse(FilledIReadOnlySet.IsNully());
        IsFalse(FilledReadOnlySet.IsNully());
        #endif
        #if NET8_0_OR_GREATER
        IsFalse(FilledFrozenSet.IsNully());
        IsFalse(FilledFrozenDictionary.IsNully());
        #endif
        #if NET6_0_OR_GREATER
        IsFalse(FilledPrioQueue.IsNully());
        IsFalse(FilledPrioQueueUnorderedColl.IsNully());
        #endif

        IsFalse(IsNully(FilledArray));
        IsFalse(IsNully(FilledIList));
        IsFalse(IsNully(FilledISet));
        IsFalse(IsNully(FilledIDict));
        IsFalse(IsNully(FilledIColl));
        IsFalse(IsNully(FilledILookup));
        IsFalse(IsNully(FilledIEnumerable));
        IsFalse(IsNully(FilledList));
        IsFalse(IsNully(FilledHashSet));
        IsFalse(IsNully(FilledStack));
        IsFalse(IsNully(FilledQueue));
        IsFalse(IsNully(FilledLinkedList));
        IsFalse(IsNully(FilledSortedList));
        IsFalse(IsNully(FilledSortedSet));
        IsFalse(IsNully(FilledDict));
        IsFalse(IsNully(FilledDictKeyColl));
        IsFalse(IsNully(FilledDictValColl));
        IsFalse(IsNully(FilledIImmutableList));
        IsFalse(IsNully(FilledIImmutableSet));
        IsFalse(IsNully(FilledIImmutableStack));
        IsFalse(IsNully(FilledIImmutableQueue));
        IsFalse(IsNully(FilledIImmutableDict));
        IsFalse(IsNully(FilledImmutableArray));
        IsFalse(IsNully(FilledImmutableArrayBuilder));
        IsFalse(IsNully(FilledImmutableList));
        IsFalse(IsNully(FilledImmutableListBuilder));
        IsFalse(IsNully(FilledImmutableHashSet));
        IsFalse(IsNully(FilledImmutableHashSetBuilder));
        IsFalse(IsNully(FilledImmutableStack));
        IsFalse(IsNully(FilledImmutableQueue));
        IsFalse(IsNully(FilledImmutableDict));
        IsFalse(IsNully(FilledImmutableDictBuilder));
        IsFalse(IsNully(FilledImmutableSortedSet));
        IsFalse(IsNully(FilledImmutableSortedSetBuilder));
        IsFalse(IsNully(FilledImmutableSortedDict));
        IsFalse(IsNully(FilledImmutableSortedDictBuilder));
        IsFalse(IsNully(FilledIReadOnlyList));
        IsFalse(IsNully(FilledIReadOnlyColl));
        IsFalse(IsNully(FilledIReadOnlyList));
        IsFalse(IsNully(FilledIReadOnlyColl));
        IsFalse(IsNully(FilledIReadOnlyColl));
        IsFalse(IsNully(FilledIReadOnlyList));
        IsFalse(IsNully(FilledIReadOnlyDict));
        IsFalse(IsNully(FilledReadOnlyColl));
        IsFalse(IsNully(FilledReadOnlyDict));
        IsFalse(IsNully(FilledReadOnlyDictKeys));
        IsFalse(IsNully(FilledReadOnlyDictVals));
        IsFalse(IsNully(FilledArraySegment));
        IsFalse(IsNully(FilledMemory));
        IsFalse(IsNully(FilledReadOnlyMemory));
        IsFalse(IsNully(FilledReadOnlySequence));
        IsFalse(IsNully(FilledConcurrentBag));
        IsFalse(IsNully(FilledConcurrentQueue));
        IsFalse(IsNully(FilledConcurrentStack));
        IsFalse(IsNully(FilledConcurrentDict));
        IsFalse(IsNully(FilledBlockingColl));
        IsFalse(IsNully(FilledIProducerConsumerColl));
        IsFalse(IsNully(FilledSortedDict));
        IsFalse(IsNully(FilledSortedDictKeys));
        IsFalse(IsNully(FilledSortedDictVals));
        IsFalse(IsNully(FilledColl));
        IsFalse(IsNully(FilledKeyedColl));
        IsFalse(IsNully(FilledObservableColl));
        IsFalse(IsNully(FilledReadOnlyObservableColl));
        IsFalse(IsNully(FilledArrayList));
        IsFalse(IsNully(FilledBitArray));
        IsFalse(IsNully(FilledCollBase));
        IsFalse(IsNully(FilledDictBase));
        IsFalse(IsNully(FilledHashtable));
        IsFalse(IsNully(FilledQueueNonGeneric));
        IsFalse(IsNully(FilledReadOnlyCollBase));
        IsFalse(IsNully(FilledSortedListNonGeneric));
        IsFalse(IsNully(FilledStackNonGeneric));
        IsFalse(IsNully(FilledHybridDict));
        IsFalse(IsNully(FilledListDict));
        IsFalse(IsNully(FilledNameObjectCollBase));
        IsFalse(IsNully(FilledNameObjectCollBaseKeys));
        IsFalse(IsNully(FilledNameValueColl));
        IsFalse(IsNully(FilledOrderedDictNonGeneric));
        IsFalse(IsNully(FilledStringColl));
        IsFalse(IsNully(FilledStringDict));
        IsFalse(IsNully(FilledIOrderedDict));
        #if NET9_0_OR_GREATER
        IsFalse(IsNully(FilledOrderedDict));
        IsFalse(IsNully(FilledOrderedDictKeys));
        IsFalse(IsNully(FilledOrderedDictVals));
        IsFalse(IsNully(FilledIReadOnlySet));
        IsFalse(IsNully(FilledReadOnlySet));
        #endif
        #if NET8_0_OR_GREATER
        IsFalse(IsNully(FilledFrozenSet));
        IsFalse(IsNully(FilledFrozenDictionary));
        #endif
        #if NET6_0_OR_GREATER
        IsFalse(IsNully(FilledPrioQueue));
        IsFalse(IsNully(FilledPrioQueueUnorderedColl));
        #endif
    }
    
    [TestMethod]
    public void IsNully_Collection_NoWhenFilledNullable()
    {
        IsFalse(NullyFilledArray.IsNully());
        IsFalse(NullyFilledIList.IsNully());
        IsFalse(NullyFilledISet.IsNully());
        IsFalse(NullyFilledIDict.IsNully());
        IsFalse(NullyFilledIColl.IsNully());
        IsFalse(NullyFilledILookup.IsNully());
        IsFalse(NullyFilledIEnumerable.IsNully());
        IsFalse(NullyFilledList.IsNully());
        IsFalse(NullyFilledHashSet.IsNully());
        IsFalse(NullyFilledStack.IsNully());
        IsFalse(NullyFilledQueue.IsNully());
        IsFalse(NullyFilledLinkedList.IsNully());
        IsFalse(NullyFilledSortedList.IsNully());
        IsFalse(NullyFilledSortedSet.IsNully());
        IsFalse(NullyFilledDict.IsNully());
        IsFalse(NullyFilledDictKeyColl.IsNully());
        IsFalse(NullyFilledDictValColl.IsNully());
        IsFalse(NullyFilledIImmutableList.IsNully());
        IsFalse(NullyFilledIImmutableSet.IsNully());
        IsFalse(NullyFilledIImmutableStack.IsNully());
        IsFalse(NullyFilledIImmutableQueue.IsNully());
        IsFalse(NullyFilledIImmutableDict.IsNully());
        IsFalse(NullyFilledImmutableArray.IsNully());
        IsFalse(NullyFilledImmutableArrayBuilder.IsNully());
        IsFalse(NullyFilledImmutableList.IsNully());
        IsFalse(NullyFilledImmutableListBuilder.IsNully());
        IsFalse(NullyFilledImmutableHashSet.IsNully());
        IsFalse(NullyFilledImmutableHashSetBuilder.IsNully());
        IsFalse(NullyFilledImmutableStack.IsNully());
        IsFalse(NullyFilledImmutableQueue.IsNully());
        IsFalse(NullyFilledImmutableDict.IsNully());
        IsFalse(NullyFilledImmutableDictBuilder.IsNully());
        IsFalse(NullyFilledImmutableSortedSet.IsNully());
        IsFalse(NullyFilledImmutableSortedSetBuilder.IsNully());
        IsFalse(NullyFilledImmutableSortedDict.IsNully());
        IsFalse(NullyFilledImmutableSortedDictBuilder.IsNully());
        IsFalse(NullyFilledIReadOnlyList.IsNully());
        IsFalse(NullyFilledIReadOnlyColl.IsNully());
        IsFalse(NullyFilledIReadOnlyList.IsNully());
        IsFalse(NullyFilledIReadOnlyColl.IsNully());
        IsFalse(NullyFilledIReadOnlyColl.IsNully());
        IsFalse(NullyFilledIReadOnlyList.IsNully());
        IsFalse(NullyFilledIReadOnlyDict.IsNully());
        IsFalse(NullyFilledReadOnlyColl.IsNully());
        IsFalse(NullyFilledReadOnlyDict.IsNully());
        IsFalse(NullyFilledReadOnlyDictKeys.IsNully());
        IsFalse(NullyFilledReadOnlyDictVals.IsNully());
        IsFalse(FilledArraySegment.IsNully());
        IsFalse(FilledMemory.IsNully());
        IsFalse(FilledReadOnlyMemory.IsNully());
        IsFalse(FilledReadOnlySequence.IsNully());
        IsFalse(NullyFilledConcurrentBag.IsNully());
        IsFalse(NullyFilledConcurrentQueue.IsNully());
        IsFalse(NullyFilledConcurrentStack.IsNully());
        IsFalse(NullyFilledConcurrentDict.IsNully());
        IsFalse(NullyFilledBlockingColl.IsNully());
        IsFalse(NullyFilledIProducerConsumerColl.IsNully());
        IsFalse(NullyFilledSortedDict.IsNully());
        IsFalse(NullyFilledSortedDictKeys.IsNully());
        IsFalse(NullyFilledSortedDictVals.IsNully());
        IsFalse(NullyFilledColl.IsNully());
        IsFalse(NullyFilledKeyedColl.IsNully());
        IsFalse(NullyFilledObservableColl.IsNully());
        IsFalse(NullyFilledReadOnlyObservableColl.IsNully());
        IsFalse(NullyFilledArrayList.IsNully());
        IsFalse(NullyFilledBitArray.IsNully());
        IsFalse(NullyFilledCollBase.IsNully());
        IsFalse(NullyFilledDictBase.IsNully());
        IsFalse(NullyFilledHashtable.IsNully());
        IsFalse(NullyFilledQueueNonGeneric.IsNully());
        IsFalse(NullyFilledReadOnlyCollBase.IsNully());
        IsFalse(NullyFilledSortedListNonGeneric.IsNully());
        IsFalse(NullyFilledStackNonGeneric.IsNully());
        IsFalse(NullyFilledHybridDict.IsNully());
        IsFalse(NullyFilledListDict.IsNully());
        IsFalse(NullyFilledNameObjectCollBase.IsNully());
        IsFalse(NullyFilledNameObjectCollBaseKeys.IsNully());
        IsFalse(NullyFilledNameValueColl.IsNully());
        IsFalse(NullyFilledOrderedDictNonGeneric.IsNully());
        IsFalse(NullyFilledStringColl.IsNully());
        IsFalse(NullyFilledStringDict.IsNully());
        IsFalse(NullyFilledIOrderedDict.IsNully());
        #if NET9_0_OR_GREATER
        IsFalse(NullyFilledOrderedDict.IsNully());
        IsFalse(NullyFilledOrderedDictKeys.IsNully());
        IsFalse(NullyFilledOrderedDictVals.IsNully());
        IsFalse(NullyFilledIReadOnlySet.IsNully());
        IsFalse(NullyFilledReadOnlySet.IsNully());
        #endif
        #if NET8_0_OR_GREATER
        IsFalse(NullyFilledFrozenSet.IsNully());
        IsFalse(NullyFilledFrozenDictionary.IsNully());
        #endif
        #if NET6_0_OR_GREATER
        IsFalse(NullyFilledPrioQueue.IsNully());
        IsFalse(NullyFilledPrioQueueUnorderedColl.IsNully());
        #endif

        IsFalse(IsNully(NullyFilledArray));
        IsFalse(IsNully(NullyFilledIList));
        IsFalse(IsNully(NullyFilledISet));
        IsFalse(IsNully(NullyFilledIDict));
        IsFalse(IsNully(NullyFilledIColl));
        IsFalse(IsNully(NullyFilledILookup));
        IsFalse(IsNully(NullyFilledIEnumerable));
        IsFalse(IsNully(NullyFilledList));
        IsFalse(IsNully(NullyFilledHashSet));
        IsFalse(IsNully(NullyFilledStack));
        IsFalse(IsNully(NullyFilledQueue));
        IsFalse(IsNully(NullyFilledLinkedList));
        IsFalse(IsNully(NullyFilledSortedList));
        IsFalse(IsNully(NullyFilledSortedSet));
        IsFalse(IsNully(NullyFilledDict));
        IsFalse(IsNully(NullyFilledDictKeyColl));
        IsFalse(IsNully(NullyFilledDictValColl));
        IsFalse(IsNully(NullyFilledIImmutableList));
        IsFalse(IsNully(NullyFilledIImmutableSet));
        IsFalse(IsNully(NullyFilledIImmutableStack));
        IsFalse(IsNully(NullyFilledIImmutableQueue));
        IsFalse(IsNully(NullyFilledIImmutableDict));
        IsFalse(IsNully(NullyFilledImmutableArray));
        IsFalse(IsNully(NullyFilledImmutableArrayBuilder));
        IsFalse(IsNully(NullyFilledImmutableList));
        IsFalse(IsNully(NullyFilledImmutableListBuilder));
        IsFalse(IsNully(NullyFilledImmutableHashSet));
        IsFalse(IsNully(NullyFilledImmutableHashSetBuilder));
        IsFalse(IsNully(NullyFilledImmutableStack));
        IsFalse(IsNully(NullyFilledImmutableQueue));
        IsFalse(IsNully(NullyFilledImmutableDict));
        IsFalse(IsNully(NullyFilledImmutableDictBuilder));
        IsFalse(IsNully(NullyFilledImmutableSortedSet));
        IsFalse(IsNully(NullyFilledImmutableSortedSetBuilder));
        IsFalse(IsNully(NullyFilledImmutableSortedDict));
        IsFalse(IsNully(NullyFilledImmutableSortedDictBuilder));
        IsFalse(IsNully(NullyFilledIReadOnlyList));
        IsFalse(IsNully(NullyFilledIReadOnlyColl));
        IsFalse(IsNully(NullyFilledIReadOnlyList));
        IsFalse(IsNully(NullyFilledIReadOnlyColl));
        IsFalse(IsNully(NullyFilledIReadOnlyColl));
        IsFalse(IsNully(NullyFilledIReadOnlyList));
        IsFalse(IsNully(NullyFilledIReadOnlyDict));
        IsFalse(IsNully(NullyFilledReadOnlyColl));
        IsFalse(IsNully(NullyFilledReadOnlyDict));
        IsFalse(IsNully(NullyFilledReadOnlyDictKeys));
        IsFalse(IsNully(NullyFilledReadOnlyDictVals));
        IsFalse(IsNully(NullyFilledArraySegment));
        IsFalse(IsNully(NullyFilledMemory));
        IsFalse(IsNully(NullyFilledReadOnlyMemory));
        IsFalse(IsNully(NullyFilledReadOnlySequence));
        IsFalse(IsNully(NullyFilledConcurrentBag));
        IsFalse(IsNully(NullyFilledConcurrentQueue));
        IsFalse(IsNully(NullyFilledConcurrentStack));
        IsFalse(IsNully(NullyFilledConcurrentDict));
        IsFalse(IsNully(NullyFilledBlockingColl));
        IsFalse(IsNully(NullyFilledIProducerConsumerColl));
        IsFalse(IsNully(NullyFilledSortedDict));
        IsFalse(IsNully(NullyFilledSortedDictKeys));
        IsFalse(IsNully(NullyFilledSortedDictVals));
        IsFalse(IsNully(NullyFilledColl));
        IsFalse(IsNully(NullyFilledKeyedColl));
        IsFalse(IsNully(NullyFilledObservableColl));
        IsFalse(IsNully(NullyFilledReadOnlyObservableColl));
        IsFalse(IsNully(NullyFilledArrayList));
        IsFalse(IsNully(NullyFilledBitArray));
        IsFalse(IsNully(NullyFilledCollBase));
        IsFalse(IsNully(NullyFilledDictBase));
        IsFalse(IsNully(NullyFilledHashtable));
        IsFalse(IsNully(NullyFilledQueueNonGeneric));
        IsFalse(IsNully(NullyFilledReadOnlyCollBase));
        IsFalse(IsNully(NullyFilledSortedListNonGeneric));
        IsFalse(IsNully(NullyFilledStackNonGeneric));
        IsFalse(IsNully(NullyFilledHybridDict));
        IsFalse(IsNully(NullyFilledListDict));
        IsFalse(IsNully(NullyFilledNameObjectCollBase));
        IsFalse(IsNully(NullyFilledNameObjectCollBaseKeys));
        IsFalse(IsNully(NullyFilledNameValueColl));
        IsFalse(IsNully(NullyFilledOrderedDictNonGeneric));
        IsFalse(IsNully(NullyFilledStringColl));
        IsFalse(IsNully(NullyFilledStringDict));
        IsFalse(IsNully(NullyFilledIOrderedDict));
        #if NET9_0_OR_GREATER
        IsFalse(IsNully(NullyFilledOrderedDict));
        IsFalse(IsNully(NullyFilledOrderedDictKeys));
        IsFalse(IsNully(NullyFilledOrderedDictVals));
        IsFalse(IsNully(NullyFilledIReadOnlySet));
        IsFalse(IsNully(NullyFilledReadOnlySet));
        #endif
        #if NET8_0_OR_GREATER
        IsFalse(IsNully(NullyFilledFrozenSet));
        IsFalse(IsNully(NullyFilledFrozenDictionary));
        #endif
        #if NET6_0_OR_GREATER
        IsFalse(IsNully(NullyFilledPrioQueue));
        IsFalse(IsNully(NullyFilledPrioQueueUnorderedColl));
        #endif
    }
}