global using System;
global using System.Collections.Generic;
global using System.Collections.Immutable;
global using System.Linq;
global using System.Reflection;
global using System.Text;
global using System.Globalization;
global using Microsoft.VisualStudio.TestTools.UnitTesting;
global using JJ.Framework.Reflection.Core;
global using JJ.Framework.Testing.Core;
global using static System.String;
global using static System.Globalization.CultureInfo;
global using static JJ.Framework.Testing.AssertHelper;
global using static JJ.Framework.Testing.Core.AssertHelperCore;
global using static JJ.Framework.Existence.Core.FilledInHelper;
global using static JJ.Framework.Existence.Core.Tests.TestHelper;
global using static JJ.Framework.Reflection.Core.Reflect;