global using System;
global using System.Collections.Generic;
global using System.Diagnostics.CodeAnalysis;
global using JJ.Framework.Existence.Core.Tests.Helpers;
global using Microsoft.VisualStudio.TestTools.UnitTesting;
global using JJ.Framework.Existence.Core.Tests.Helpers.docs;
global using JJ.Framework.Existence.Core.Bool.Tests.docs;
global using static System.String;
global using static JJ.Framework.Existence.Core.FilledInHelper;
global using static JJ.Framework.Existence.Core.SpaceMatters;
global using static JJ.Framework.Existence.Core.ZeroMatters;
global using static JJ.Framework.Testing.Core.AssertCore;
