global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Globalization;
global using Microsoft.VisualStudio.TestTools.UnitTesting;
global using JJ.Framework.Common.Legacy;
global using static System.Array;
global using static System.Globalization.CultureInfo;
global using static JJ.Framework.Testing.Core.AssertCore;
global using static JJ.Framework.Testing.Core.DeltaDirectionEnum;
