global using System.Text;
global using System.Diagnostics;
global using System.Runtime.InteropServices;
global using JJ.Framework.Configuration.Core.Tests.Settings;
global using Microsoft.VisualStudio.TestTools.UnitTesting;
global using static System.String;
global using static System.StringComparison;
global using static System.Reflection.Assembly;
global using static System.IO.File;
global using static JJ.Framework.Testing.Core.AssertCore;
global using static JJ.Framework.Common.Legacy.EmbeddedResourceHelper;
