global using System.IO;
global using System.Linq;
global using System.Text;
global using Microsoft.VisualStudio.TestTools.UnitTesting;
global using JJ.Framework.IO.Core;
global using JJ.Framework.IO.Core.Tests;
global using static System.Console;
global using static System.Environment;
global using static JJ.Framework.Testing.Core.AssertCore;
global using static JJ.Framework.Testing.Core.TestRunner;
