global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Linq.Expressions;
global using System.Text;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using JJ.Framework.Common.Legacy;
global using JJ.Framework.Existence.Core;
global using JJ.Framework.Text.Core;
global using JJ.Framework.Reflection.Legacy;
global using JJ.Framework.Reflection.Core;
global using JJ.Framework.Testing.Legacy;
global using JJ.Framework.Testing.Core.docs;
global using static System.Math;
global using static System.String;
global using static System.Array;
global using static System.ArgumentNullException;
global using static System.Activator;
global using static System.Reflection.MethodBase;
global using static System.Reflection.BindingFlags;
global using static System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes;
global using static JJ.Framework.PlatformCompatibility.Core.DynamicallyAccessedMemberTypesEx;
global using static JJ.Framework.PlatformCompatibility.Core.ExceptionSupport;
global using static JJ.Framework.Testing.Legacy.AssertHelper;
global using static JJ.Framework.Testing.Core.AssertCore;
global using static JJ.Framework.Testing.Core.AssertHelperLegacy;
global using static JJ.Framework.Testing.Core.DeltaDirectionEnum;
global using static JJ.Framework.Testing.Core.TestHelperCore;
global using static JJ.Framework.Testing.Core.DebuggerDisplayFormatter;
global using static JJ.Framework.Existence.Core.FilledInHelper;
global using static JJ.Framework.Reflection.Legacy.ExpressionHelper;
global using static JJ.Framework.Reflection.Legacy.ReflectionHelper;
global using static JJ.Framework.Reflection.Core.Reflect;
global using ArgExpress = System.Runtime.CompilerServices.CallerArgumentExpressionAttribute;
global using Prio       = System.Runtime.CompilerServices.OverloadResolutionPriorityAttribute;
global using Dyn        = System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembersAttribute;