global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Linq.Expressions;
global using System.Text;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using JJ.Framework.Reflection.Core.docs;
global using static JJ.Framework.Reflection.ExpressionHelper;
global using static JJ.Framework.Reflection.Core.ReflectionHelperCore;
global using CallerAttribute = System.Runtime.CompilerServices.CallerMemberNameAttribute;
