global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Linq.Expressions;
global using System.Text;
global using System.Threading;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using System.Diagnostics; // For StackTrace
global using JetBrains.Annotations;
global using JJ.Framework.Common.Core;
global using JJ.Framework.Collections.Core;
global using JJ.Framework.Existence.Core;
global using JJ.Framework.Reflection.Legacy;
global using JJ.Framework.Reflection.Core.docs;
global using static System.Array;
global using static System.String; 
global using static System.Nullable;
global using static System.Environment;
global using static System.HashCode;
global using static System.ArgumentException;
global using static System.ArgumentNullException;
global using static System.StringComparison;
global using static System.Reflection.BindingFlags;
global using static System.Runtime.CompilerServices.MethodImplOptions;
global using static JJ.Framework.PlatformCompatibility.Core.ExceptionSupport;
global using static JJ.Framework.Common.Core.NameHelper;
global using static JJ.Framework.Collections.Core.StaticEnumerable;
global using static JJ.Framework.Existence.Core.FilledInHelper;
global using static JJ.Framework.Reflection.Legacy.ExpressionHelper;
global using static JJ.Framework.Reflection.Legacy.ReflectionHelper;
global using static JJ.Framework.Reflection.Core.Reflect;
global using static JJ.Framework.Reflection.Core.ReflectUtility;
global using static JJ.Framework.Reflection.Core.NullFlag;
global using static JJ.Framework.Reflection.Core.Debugging;
global using Caller       = System.Runtime.CompilerServices.CallerMemberNameAttribute;
global using Priority     = System.Runtime.CompilerServices.OverloadResolutionPriorityAttribute;
global using Prio         = System.Runtime.CompilerServices.OverloadResolutionPriorityAttribute;
global using PropDic      = System.Collections.Generic.Dictionary<(System.Type, string), System.Reflection.PropertyInfo?>;
global using FieldDic     = System.Collections.Generic.Dictionary<(System.Type, string), System.Reflection.FieldInfo?>;
global using PropsDic     = System.Collections.Generic.Dictionary<System.Type, System.Reflection.PropertyInfo[]>;
global using PropsDicDic  = System.Collections.Generic.Dictionary<System.Type, System.Collections.Generic.Dictionary<string, System.Reflection.PropertyInfo>>;
global using FieldsDic    = System.Collections.Generic.Dictionary<System.Type, System.Reflection.FieldInfo[]>;
global using FieldsDicDic = System.Collections.Generic.Dictionary<System.Type, System.Collections.Generic.Dictionary<string, System.Reflection.FieldInfo>>;
global using MethodDic0   = System.Collections.Generic.Dictionary<JJ.Framework.Reflection.Core.MethodKey0, System.Reflection.MethodInfo?>;
global using MethodDic1   = System.Collections.Generic.Dictionary<JJ.Framework.Reflection.Core.MethodKey1, System.Reflection.MethodInfo?>;
global using MethodDic2   = System.Collections.Generic.Dictionary<JJ.Framework.Reflection.Core.MethodKey2, System.Reflection.MethodInfo?>;
global using MethodDic3   = System.Collections.Generic.Dictionary<JJ.Framework.Reflection.Core.MethodKey3, System.Reflection.MethodInfo?>;
global using MethodDic4   = System.Collections.Generic.Dictionary<JJ.Framework.Reflection.Core.MethodKey4, System.Reflection.MethodInfo?>;
global using MethodDic5   = System.Collections.Generic.Dictionary<JJ.Framework.Reflection.Core.MethodKey5, System.Reflection.MethodInfo?>;
global using MethodDicN   = System.Collections.Generic.Dictionary<JJ.Framework.Reflection.Core.MethodKeyN, System.Reflection.MethodInfo?>;
//global using MethodDic2 = System.Collections.Generic.Dictionary<JJ.Framework.Reflection.Core.MethodKey2, System.Reflection.MethodInfo?>;
//global using MethodDic2 = System.Collections.Generic.Dictionary<JJ.Framework.Reflection.Core.NameTypesKey2, System.Reflection.MethodInfo?>;

