global using System;
global using System.Collections.Generic;
global using System.Globalization;
global using System.Linq;
global using System.Reflection;
global using System.Diagnostics;
global using JJ.Framework.Testing;
global using JJ.Framework.Reflection;
global using JJ.Framework.Exceptions.TypeChecking;
global using static System.String;
global using static System.StringComparison;
global using static System.Reflection.BindingFlags;
global using static System.Text.RegularExpressions.Regex;
global using static JJ.Framework.Common.CultureHelper;
global using static JJ.Framework.Testing.AssertHelper;