//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JJ.Framework.IO {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JJ.Framework.IO.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting files {0:0.0}% - {1}.
        /// </summary>
        internal static string DeletingFiles_WithPercentage_AndFileName {
            get {
                return ResourceManager.GetString("DeletingFiles_WithPercentage_AndFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done deleting {0} files..
        /// </summary>
        internal static string DoneDeletingFiles_WithCount {
            get {
                return ResourceManager.GetString("DoneDeletingFiles_WithCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done scanning. {0} duplicates found..
        /// </summary>
        internal static string DoneScanning_WithDuplicatesCount {
            get {
                return ResourceManager.GetString("DoneScanning_WithDuplicatesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing files....
        /// </summary>
        internal static string ListingFiles {
            get {
                return ResourceManager.GetString("ListingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing result....
        /// </summary>
        internal static string ProcessingResult {
            get {
                return ResourceManager.GetString("ProcessingResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning for duplicates....
        /// </summary>
        internal static string ScanningForDuplicates {
            get {
                return ResourceManager.GetString("ScanningForDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning for duplicates {0:0.##}%....
        /// </summary>
        internal static string ScanningForDuplicates_WithPercentage {
            get {
                return ResourceManager.GetString("ScanningForDuplicates_WithPercentage", resourceCulture);
            }
        }
    }
}
