namespace JJ.Framework.Existence.Core.Collections.Tests;

[TestClass]
public class Has_Collection_No : TestBase
{
    [TestMethod]
    public void Has_Collection_NoWhenEmpty()
    {
        IsFalse(Has(EmptyArray));
        IsFalse(Has(EmptyIList));
        IsFalse(Has(EmptyISet));
        IsFalse(Has(EmptyIDict));
        IsFalse(Has(EmptyIColl));
        IsFalse(Has(EmptyILookup));
        IsFalse(Has(EmptyIEnumerable));
        IsFalse(Has(EmptyList));
        IsFalse(Has(EmptyHashSet));
        IsFalse(Has(EmptyStack));
        IsFalse(Has(EmptyQueue));
        IsFalse(Has(EmptyLinkedList));
        IsFalse(Has(EmptySortedList));
        IsFalse(Has(EmptySortedSet));
        IsFalse(Has(EmptyDict));
        IsFalse(Has(EmptyDictKeyColl));
        IsFalse(Has(EmptyDictValColl));
        IsFalse(Has(EmptyIImmutableList));
        IsFalse(Has(EmptyIImmutableSet));
        IsFalse(Has(EmptyIImmutableStack));
        IsFalse(Has(EmptyIImmutableQueue));
        IsFalse(Has(EmptyIImmutableDict));
        IsFalse(Has(EmptyImmutableArray));
        IsFalse(Has(EmptyImmutableArrayBuilder));
        IsFalse(Has(EmptyImmutableList));
        IsFalse(Has(EmptyImmutableListBuilder));
        IsFalse(Has(EmptyImmutableHashSet));
        IsFalse(Has(EmptyImmutableHashSetBuilder));
        IsFalse(Has(EmptyImmutableStack));
        IsFalse(Has(EmptyImmutableQueue));
        IsFalse(Has(EmptyImmutableDict));
        IsFalse(Has(EmptyImmutableDictBuilder));
        IsFalse(Has(EmptyImmutableSortedSet));
        IsFalse(Has(EmptyImmutableSortedSetBuilder));
        IsFalse(Has(EmptyImmutableSortedDict));
        IsFalse(Has(EmptyImmutableSortedDictBuilder));
        IsFalse(Has(EmptyIReadOnlyList));
        IsFalse(Has(EmptyIReadOnlyColl));
        IsFalse(Has(EmptyIReadOnlyList));
        IsFalse(Has(EmptyIReadOnlyColl));
        IsFalse(Has(EmptyIReadOnlyColl));
        IsFalse(Has(EmptyIReadOnlyList));
        IsFalse(Has(EmptyIReadOnlyDict));
        IsFalse(Has(EmptyReadOnlyColl));
        IsFalse(Has(EmptyReadOnlyDict));
        IsFalse(Has(EmptyReadOnlyDictKeys));
        IsFalse(Has(EmptyReadOnlyDictVals));
        IsFalse(Has(EmptyArraySegment));
        IsFalse(Has(EmptyMemory));
        IsFalse(Has(EmptyReadOnlyMemory));
        IsFalse(Has(EmptyReadOnlySequence));
        IsFalse(Has(EmptyConcurrentBag));
        IsFalse(Has(EmptyConcurrentQueue));
        IsFalse(Has(EmptyConcurrentStack));
        IsFalse(Has(EmptyConcurrentDict));
        IsFalse(Has(EmptyBlockingColl));
        IsFalse(Has(EmptyIProducerConsumerColl));
        IsFalse(Has(EmptySortedDict));
        IsFalse(Has(EmptySortedDictKeys));
        IsFalse(Has(EmptySortedDictVals));
        IsFalse(Has(EmptyColl));
        IsFalse(Has(EmptyKeyedColl));
        IsFalse(Has(EmptyObservableColl));
        IsFalse(Has(EmptyReadOnlyObservableColl));
        IsFalse(Has(EmptyArrayList));
        IsFalse(Has(EmptyBitArray));
        IsFalse(Has(EmptyCollBase));
        IsFalse(Has(EmptyDictBase));
        IsFalse(Has(EmptyHashtable));
        IsFalse(Has(EmptyQueueNonGeneric));
        IsFalse(Has(EmptyReadOnlyCollBase));
        IsFalse(Has(EmptySortedListNonGeneric));
        IsFalse(Has(EmptyStackNonGeneric));
        IsFalse(Has(EmptyHybridDict));
        IsFalse(Has(EmptyListDict));
        IsFalse(Has(EmptyNameObjectCollBase));
        IsFalse(Has(EmptyNameObjectCollBaseKeys));
        IsFalse(Has(EmptyNameValueColl));
        IsFalse(Has(EmptyOrderedDictNonGeneric));
        IsFalse(Has(EmptyStringColl));
        IsFalse(Has(EmptyStringDict));
        IsFalse(Has(EmptyIOrderedDict));
        #if NET9_0_OR_GREATER
        IsFalse(Has(EmptyOrderedDict));
        IsFalse(Has(EmptyOrderedDictKeys));
        IsFalse(Has(EmptyOrderedDictVals));
        IsFalse(Has(EmptyIReadOnlySet));
        IsFalse(Has(EmptyReadOnlySet));
        #endif
        IsFalse(Has(EmptyFrozenSet));
        IsFalse(Has(EmptyFrozenDictionary));
        #if NET6_0_OR_GREATER
        IsFalse(Has(EmptyPrioQueue));
        IsFalse(Has(EmptyPrioQueueUnorderedColl));
        #endif
    }
      
    [TestMethod]
    public void Has_Collection_NoWhenEmptyNullable()
    {
        IsFalse(Has(NullableEmptyArray));
        IsFalse(Has(NullableEmptyIList));
        IsFalse(Has(NullableEmptyISet));
        IsFalse(Has(NullableEmptyIDict));
        IsFalse(Has(NullableEmptyIColl));
        IsFalse(Has(NullableEmptyILookup));
        IsFalse(Has(NullableEmptyIEnumerable));
        IsFalse(Has(NullableEmptyList));
        IsFalse(Has(NullableEmptyHashSet));
        IsFalse(Has(NullableEmptyStack));
        IsFalse(Has(NullableEmptyQueue));
        IsFalse(Has(NullableEmptyLinkedList));
        IsFalse(Has(NullableEmptySortedList));
        IsFalse(Has(NullableEmptySortedSet));
        IsFalse(Has(NullableEmptyDict));
        IsFalse(Has(NullableEmptyDictKeyColl));
        IsFalse(Has(NullableEmptyDictValColl));
        IsFalse(Has(NullableEmptyIImmutableList));
        IsFalse(Has(NullableEmptyIImmutableSet));
        IsFalse(Has(NullableEmptyIImmutableStack));
        IsFalse(Has(NullableEmptyIImmutableQueue));
        IsFalse(Has(NullableEmptyIImmutableDict));
        IsFalse(Has(NullableEmptyImmutableArray));
        IsFalse(Has(NullableEmptyImmutableArrayBuilder));
        IsFalse(Has(NullableEmptyImmutableList));
        IsFalse(Has(NullableEmptyImmutableListBuilder));
        IsFalse(Has(NullableEmptyImmutableHashSet));
        IsFalse(Has(NullableEmptyImmutableHashSetBuilder));
        IsFalse(Has(NullableEmptyImmutableStack));
        IsFalse(Has(NullableEmptyImmutableQueue));
        IsFalse(Has(NullableEmptyImmutableDict));
        IsFalse(Has(NullableEmptyImmutableDictBuilder));
        IsFalse(Has(NullableEmptyImmutableSortedSet));
        IsFalse(Has(NullableEmptyImmutableSortedSetBuilder));
        IsFalse(Has(NullableEmptyImmutableSortedDict));
        IsFalse(Has(NullableEmptyImmutableSortedDictBuilder));
        IsFalse(Has(NullableEmptyIReadOnlyList));
        IsFalse(Has(NullableEmptyIReadOnlyColl));
        IsFalse(Has(NullableEmptyIReadOnlyColl));
        IsFalse(Has(NullableEmptyIReadOnlyList));
        IsFalse(Has(NullableEmptyIReadOnlyDict));
        IsFalse(Has(NullableEmptyReadOnlyColl));
        IsFalse(Has(NullableEmptyReadOnlyDict));
        IsFalse(Has(NullableEmptyReadOnlyDictKeys));
        IsFalse(Has(NullableEmptyReadOnlyDictVals));
        IsFalse(Has(NullableEmptyArraySegment));
        IsFalse(Has(NullableEmptyMemory));
        IsFalse(Has(NullableEmptyReadOnlyMemory));
        IsFalse(Has(NullableEmptyReadOnlySequence));
        IsFalse(Has(NullableEmptyConcurrentBag));
        IsFalse(Has(NullableEmptyConcurrentQueue));
        IsFalse(Has(NullableEmptyConcurrentStack));
        IsFalse(Has(NullableEmptyConcurrentDict));
        IsFalse(Has(NullableEmptyBlockingColl));
        IsFalse(Has(NullableEmptyIProducerConsumerColl));
        IsFalse(Has(NullableEmptySortedDict));
        IsFalse(Has(NullableEmptySortedDictKeys));
        IsFalse(Has(NullableEmptySortedDictVals));
        IsFalse(Has(NullableEmptyColl));
        IsFalse(Has(NullableEmptyKeyedColl));
        IsFalse(Has(NullableEmptyObservableColl));
        IsFalse(Has(NullableEmptyReadOnlyObservableColl));
        IsFalse(Has(NullableEmptyArrayList));
        IsFalse(Has(NullableEmptyBitArray));
        IsFalse(Has(NullableEmptyCollBase));
        IsFalse(Has(NullableEmptyDictBase));
        IsFalse(Has(NullableEmptyHashtable));
        IsFalse(Has(NullableEmptyQueueNonGeneric));
        IsFalse(Has(NullableEmptyReadOnlyCollBase));
        IsFalse(Has(NullableEmptySortedListNonGeneric));
        IsFalse(Has(NullableEmptyStackNonGeneric));
        IsFalse(Has(NullableEmptyHybridDict));
        IsFalse(Has(NullableEmptyListDict));
        IsFalse(Has(NullableEmptyNameObjectCollBase));
        IsFalse(Has(NullableEmptyNameObjectCollBaseKeys));
        IsFalse(Has(NullableEmptyNameValueColl));
        IsFalse(Has(NullableEmptyOrderedDictNonGeneric));
        IsFalse(Has(NullableEmptyStringColl));
        IsFalse(Has(NullableEmptyStringDict));
        IsFalse(Has(NullableEmptyIOrderedDict));
        #if NET9_0_OR_GREATER
        IsFalse(Has(NullableEmptyOrderedDict));
        IsFalse(Has(NullableEmptyOrderedDictKeys));
        IsFalse(Has(NullableEmptyOrderedDictVals));
        IsFalse(Has(NullableEmptyIReadOnlySet));
        IsFalse(Has(NullableEmptyReadOnlySet));
        #endif
        IsFalse(Has(NullableEmptyFrozenSet));
        IsFalse(Has(NullableEmptyFrozenDictionary));
        #if NET6_0_OR_GREATER
        IsFalse(Has(NullableEmptyPrioQueue));
        IsFalse(Has(NullableEmptyPrioQueueUnorderedColl));
        #endif
    }
      
    [TestMethod]
    public void Has_Collection_NoWhenNull()
    {
        IsFalse(Has(NullArray));
        IsFalse(Has(NullIList));
        IsFalse(Has(NullISet));
        IsFalse(Has(NullIDict));
        IsFalse(Has(NullIColl));
        IsFalse(Has(NullILookup));
        IsFalse(Has(NullIEnumerable));
        IsFalse(Has(NullList));
        IsFalse(Has(NullHashSet));
        IsFalse(Has(NullStack));
        IsFalse(Has(NullQueue));
        IsFalse(Has(NullLinkedList));
        IsFalse(Has(NullSortedList));
        IsFalse(Has(NullSortedSet));
        IsFalse(Has(NullDict));
        IsFalse(Has(NullDictKeyColl));
        IsFalse(Has(NullDictValColl));
        IsFalse(Has(NullIImmutableList));
        IsFalse(Has(NullIImmutableSet));
        IsFalse(Has(NullIImmutableStack));
        IsFalse(Has(NullIImmutableQueue));
        IsFalse(Has(NullIImmutableDict));
        IsFalse(Has(NullImmutableArray));
        IsFalse(Has(NullImmutableArrayBuilder));
        IsFalse(Has(NullImmutableList));
        IsFalse(Has(NullImmutableListBuilder));
        IsFalse(Has(NullImmutableHashSet));
        IsFalse(Has(NullImmutableHashSetBuilder));
        IsFalse(Has(NullImmutableStack));
        IsFalse(Has(NullImmutableQueue));
        IsFalse(Has(NullImmutableDict));
        IsFalse(Has(NullImmutableDictBuilder));
        IsFalse(Has(NullImmutableSortedSet));
        IsFalse(Has(NullImmutableSortedSetBuilder));
        IsFalse(Has(NullImmutableSortedDict));
        IsFalse(Has(NullImmutableSortedDictBuilder));
        IsFalse(Has(NullIReadOnlyList));
        IsFalse(Has(NullIReadOnlyColl));
        IsFalse(Has(NullIReadOnlyList));
        IsFalse(Has(NullIReadOnlyColl));
        IsFalse(Has(NullIReadOnlyColl));
        IsFalse(Has(NullIReadOnlyList));
        IsFalse(Has(NullIReadOnlyDict));
        IsFalse(Has(NullReadOnlyColl));
        IsFalse(Has(NullReadOnlyDict));
        IsFalse(Has(NullReadOnlyDictKeys));
        IsFalse(Has(NullReadOnlyDictVals));
        IsFalse(Has(NullArraySegment));
        IsFalse(Has(NullMemory));
        IsFalse(Has(NullReadOnlyMemory));
        IsFalse(Has(NullReadOnlySequence));
        IsFalse(Has(NullConcurrentBag));
        IsFalse(Has(NullConcurrentQueue));
        IsFalse(Has(NullConcurrentStack));
        IsFalse(Has(NullConcurrentDict));
        IsFalse(Has(NullBlockingColl));
        IsFalse(Has(NullIProducerConsumerColl));
        IsFalse(Has(NullSortedDict));
        IsFalse(Has(NullSortedDictKeys));
        IsFalse(Has(NullSortedDictVals));
        IsFalse(Has(NullColl));
        IsFalse(Has(NullKeyedColl));
        IsFalse(Has(NullObservableColl));
        IsFalse(Has(NullReadOnlyObservableColl));
        IsFalse(Has(NullArrayList));
        IsFalse(Has(NullBitArray));
        IsFalse(Has(NullCollBase));
        IsFalse(Has(NullDictBase));
        IsFalse(Has(NullHashtable));
        IsFalse(Has(NullQueueNonGeneric));
        IsFalse(Has(NullReadOnlyCollBase));
        IsFalse(Has(NullSortedListNonGeneric));
        IsFalse(Has(NullStackNonGeneric));
        IsFalse(Has(NullHybridDict));
        IsFalse(Has(NullListDict));
        IsFalse(Has(NullNameObjectCollBase));
        IsFalse(Has(NullNameObjectCollBaseKeys));
        IsFalse(Has(NullNameValueColl));
        IsFalse(Has(NullOrderedDictNonGeneric));
        IsFalse(Has(NullStringColl));
        IsFalse(Has(NullStringDict));
        IsFalse(Has(NullIOrderedDict));
        #if NET9_0_OR_GREATER
        IsFalse(Has(NullOrderedDict));
        IsFalse(Has(NullOrderedDictKeys));
        IsFalse(Has(NullOrderedDictVals));
        IsFalse(Has(NullIReadOnlySet));
        IsFalse(Has(NullReadOnlySet));
        #endif
        IsFalse(Has(NullFrozenSet));
        IsFalse(Has(NullFrozenDictionary));
        #if NET6_0_OR_GREATER
        IsFalse(Has(NullPrioQueue));
        IsFalse(Has(NullPrioQueueUnorderedColl));
        #endif
    }
}